### ISSUE TITLE
Fast Global Registration does not populate `fitness`, `inlier_rmse`, and `corres

### ISSUE THREAD

**Issue by AndreiBarsan** [intel-isl/Open3D#1001]
**Bug description**
The `open3d.registration.RegistrationResult` object returned by `open3d.registration.registration_fast_based_on_feature_matching` contains confusing results, with fields like `fitness` always being 0 even if the match is nearly perfect.

**To Reproduce**
Steps to reproduce the behavior (from repository root):
 1. cd `examples/Python/Advanced/`
 2. Edit `fast_global_registration.py` to include `print(result_fast)` in the end.
 3. `python fast_global_registration.py`

**Expected behavior**
Either (1) shows some non-zero 'fitness' for a near-perfect match, or (2) the documents clearly state that FGR is not expected to populate this field (or inlier RMSE, correspondence set size, etc.)

**Actual behavior**
'fitness', 'inlier_rmse', and 'correspondence_set_size' are always zero, even when FGR works perfectly. Other methods, including the vanilla (slow) global registration and ICP always set these fields accordingly.

**Environment (please complete the following information):**
 - OS: Ubuntu 14.04
 - Python version: 3.6.8, 2.7
 - Open3D version: 0.6.0
 - Is this remote workstation?: no
 - How did you install Open3D?: conda

**Comment by qianyizh** [comment]
@syncle take a look?

**Comment by grosskc** [comment]
I can confirm this behavior:
OS: Ubuntu 18.04
Python: 3.6.8
Open3D 0.7.0
Not remote workstation
Installed via pip

**Comment by syncle** [comment]
Oh, thanks for pointing out the issue. I've submitted a fix for this.

**Comment by AndreiBarsan** [comment]
Awesome, thank you very much for the update and keep up the amazing work!
<3 Open3D!!!

**Comment by cgsaxner** [comment]
Hi, 
this might be a stupid question, but how can I get this bugfix?
I'm using open3d 0.8.0.0 and python 3.6.9 under Windows 10. I have updated my open3d package using conda, but still, 'fitness', 'inlier_rmse', and 'correspondence_set_size' are always zero.
Thank you!

**Comment by griegler** [comment]
@cgsaxner This PR was contributed after the `0.8` release. To get it, you can build open3d from source, or wait 2-3 weeks for the new release.

**Comment by cgsaxner** [comment]
Thanks a lot for the fast reply. Will build from source then!
