### ISSUE TITLE
is there any way to add class labels to geometry.PointCloud ? 

### ISSUE THREAD

**Issue by victor000000** [intel-isl/Open3D#1002]
I saw the voxel downsmaple source code,
 Open3D/src/Open3D/Geometry/DownSample.cpp: line 293, VoxelDownSampleAndTrace(...)
line 342: if (approximate_class) {
line 343: output->colors_.push_back(accpoint.second.GetMaxClass());

how do i add class labels to geometry.PointCloud instance by a numpy array? 
    so that i can take the advantage of the efficiency of c++ to get the class label for a voxel, instead of using the returned value 'cubics_ids' and numpy array of labels to get the voxel class label

**Comment by wyjforwjy** [comment]
Hi,do you add class label to pointcloud? I alse have this problem. I need add label to bbox.

**Comment by germanros1987** [comment]
This should be now possible with the new PointCloud class.

**Comment by anthonySemaan01** [comment]
Hello, I am using Geometry.PointCloud. I believe the feature is provided only to tensor PointCloud. Is there a way to add an additional dimension/channel through Geometry.PointCloud?
