### ISSUE TITLE
what is the meaning of params in saved json file?

### ISSUE THREAD

**Issue by ghoshaw** [intel-isl/Open3D#1015]
Hi, 
     I want to find the R T relation between the final 3D model and each frame, but I do not understand what the "information" "edge" "transforms" mean in the saved json file.   My purpose is to set few 3d  point  in the model, and then want to get the corresponding 2d point in each frame.

**Comment by qianyizh** [comment]
I don't understand your question. Can you elaborate? Posting a minimal code snippet would be helpful.

**Comment by ghoshaw** [comment]
sorry to bother you,  I figured it out myself.  But a new problem happens like #797, and I tried to use conda and install the open3d from source, but  the error "open3d-0.5.0.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform." is still on.

**Comment by qianyizh** [comment]
I will close this ticket and reopen #797
