### ISSUE TITLE
Open3D read_point_cloud skips NaNs 

### ISSUE THREAD

**Issue by renuka-apte** [intel-isl/Open3D#1016]
Open3D seems to remove NaNs forcibly while reading a pcd, which doesn't make sense for organized pcds. 

https://github.com/intel-isl/Open3D/blob/master/src/Open3D/IO/FileFormat/FilePCD.cpp#L768

**To repro**
```
pcd = o3d.io.read_point_cloud('file.pcd')
```

**Expected behavior**
Perhaps pass a flag that allows for the reading of organized point clouds. IOW, put that line ^ behind a flag.

**Comment by qianyizh** [comment]
I will add it as a feature request and let @germanros1987 to put it in the roadmap.

Also yes, in the current version, we assume the point cloud is an unorganized point cloud without NaNs. A flag to enable NaNs would be good.

**Comment by griegler** [comment]
Addressed in #1022
