### ISSUE TITLE
Question: How do I open the header of a PLY file?

### ISSUE THREAD

**Issue by vlall** [intel-isl/Open3D#1017]
I looked through the issues and the tutorials, and I cannot find how to view the PLY header to get other features on our data. I'm looking to covert the PLY file to data frame using this library, instead of using another PLY library.

Thanks!

**Comment by qianyizh** [comment]
I don't think it is exposed in Python interface.
In C++, we use RPLY, and the interface is wrapped in this file:
https://github.com/intel-isl/Open3D/blob/master/src/Open3D/IO/FileFormat/FilePLY.cpp

**Comment by vlall** [comment]
Does that mean we can't see the other features/properties besides the point co-ordinates? I know some other python libraries expose that data. Just curious, thanks!

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
