### ISSUE TITLE
Segmentation algorithm

### ISSUE THREAD

**Issue by kira-on** [intel-isl/Open3D#1018]
I have been using Open3D for a while.
I wonder if there are any segmentation algorithms in Open3D like:
http://pointclouds.org/documentation/tutorials/region_growing_segmentation.php#region-growing-segmentation
http://pointclouds.org/documentation/tutorials/cluster_extraction.php#cluster-extraction

I want to extract different objects from the point cloud.

Thank you

**Comment by qianyizh** [comment]
Not yet. It is currently on our roadmap.
@germanros1987 FYI

**Comment by griegler** [comment]
#1038 implemented DBSCAN for clustering/segmentation.
