### ISSUE TITLE
Supported mesh file formats

### ISSUE THREAD

**Issue by kongsgard** [intel-isl/Open3D#1019]
**Is your feature request related to a problem? Please describe.**
It is difficult to see which file formats are supported.

**Describe the solution you'd like**
I would like to easily get an overview of the supported mesh file formats on the documentation page, http://www.open3d.org/docs/tutorial/Basic/file_io.html, similar to the table given for point clouds.

Does the function `o3d.io.read_triangle_mesh` currently support .ply and .stl?
(https://github.com/intel-isl/Open3D/blob/master/src/Open3D/IO/ClassIO/TriangleMeshIO.h)

**Comment by qianyizh** [comment]
Yes I think it supports PLY and STL. But only standard version.

We should complete the doc. @germanros1987 FYI

**Comment by kongsgard** [comment]
Thanks for the quick feedback!
Is anyone working on support for .off-files? If not, I could add a PR on that.

**Comment by griegler** [comment]
@kongsgard I think nobody is currently working on it. Would be great to get a PR on that format!

**Comment by kongsgard** [comment]
#1035
