### ISSUE TITLE
extrinsic matrix and transform

### ISSUE THREAD

**Issue by XuyangBai** [intel-isl/Open3D#1027]
Hi, thanks for your sharing. I got confused when I use the function `open3d.create_point_cloud_from_rgbd_image`. There is a parameter called `extrinsic` and I have a 4 * 4 matrix which is the camera pose(camera-to-world, 4*4 matrix in homogeneous coordinates). So I just use  this matrix as the extrinsic matrix. However, I tried another way: I first use the default extrinsic matrix(`np.eye(4)`) to create the point cloud and then use `.transform` function to transform point cloud. Then the resulting point clouds are different. But I think they should be the same.

Could you please give me some explanation? Thank you so much.

**Comment by qianyizh** [comment]
extrinsic matrices convert world coordinates to camera coordinates. Thus you should use its inverse in `.transform`.

**Comment by XuyangBai** [comment]
Thank you so much for your explanation!

**Comment by yoon28** [comment]
@qianyizh Could you slightly give me more hint about this? I still don't get it why I should use inverse of extrinsic matrix to move objects.
