### ISSUE TITLE
Function: open3d.geometry.create_point_cloud_from_depth_image

### ISSUE THREAD

**Issue by EnrikDS** [intel-isl/Open3D#1028]
Hi, I am not 100% sure about the meaning of the arguments to this function, but there are two called "depth_scale" , "depth_trunc" that do not seem to have any effect on the pointcloud calling them from python.
I got a depth image and I would like to create a PointCloud discarding points whose distance to the camera are greater than a threshold. It does not seem to work. 

**To Reproduce**
Just call the function from a depth image.

**Expected behavior**
The expected behaviour is that further points should not appear in the point cloud after that call. They still appear. Also the (X,y,z) coordinates should be scaled with the scale parameter, they are not.

**Environment (please complete the following information):**
 - Ubuntu 16.04
 - Python version 3.6
 - Open3D version: open3d-python 0.7.0
 - Is this remote workstation?:  no
 - How did you install Open3D?: pip

The depth images are coming from pybullet.

**Comment by syncle** [comment]
"depth_scale" , "depth_trunc" should work. Could you check the scale of your depth data to be manipulated? The parameter for "depth_scale" , "depth_trunc" should be consistent with the input depth in terms of the scale.
