### ISSUE TITLE
Not able to use some of the functions in open3d.

### ISSUE THREAD

**Issue by liyiqiao02** [intel-isl/Open3D#1030]
Hi,
I use $pip3 install open3d to install open3d. I am able to load point cloud and visualize point cloud using the functions from open3d. But I am not able to use functions like "voxel_down_sample".
AttributeError: 'open3d.open3d.geometry.PointCloud' object has no attribute 'voxel_down_sample'
Do you have any idea about that?

Thanks

**Comment by abhijaysingh** [comment]
@liyiqiao02  I was facing the same. Compiling from source will fix this issue.

**Comment by griegler** [comment]
The same problem as in #1028. The online documentation is unfortunately associated with the master branch and not the latest release. You should be able to use `open3d.geometry.voxel_down_sample(pointcloud_object)`.

**Comment by yxlao** [comment]
fixed with #1055

**Comment by lgribeiro** [comment]
Replace this function:
downpcd = pcd.voxel_down_sample(voxel_size=0.05)
for:
downpcd = o3d.geometry.voxel_down_sample(pcd,voxel_size=0.05)
It  works!  :)
