### ISSUE TITLE
Compiled Open3D can't run tutorial

### ISSUE THREAD

**Issue by bascoul** [intel-isl/Open3D#1033]
I followed the documentation of Open3D 0.7.0.0 (http://www.open3d.org/docs/getting_started.html#id3) and retrieved the tutorials on: https://github.com/intel-isl/Open3D but there is no correspondence between the two which gives systematic errors.
The first tutorial : python rgbd_redwood.py give this error:  
AttributeError: type object 'open3d.open3d.geometry.RGBDImage' has no attribute 'create_from_color_and_depth'
Is there a compiled version to download that is correct?
Thanks

**Comment by kongsgard** [comment]
Earlier versions can be found here: https://pypi.org/project/open3d-python/0.7.0.0/#history
I tested with 0.7.0.0 and 0.6.0.0 and got the same error message. However with 0.5.0.0 and earlier versions open3d has no attribute 'io', and thus requires some changes to the tutorial code to use the RGBDImage function.

It therefore seems like compiling from source (which fixes the issue) is the best approach currently.

**Comment by yxlao** [comment]
yes, we're working on simultaneously providing docs for previous versions and `master` branch in the docs website

**Comment by Resays** [comment]
File Name: rgbd_redwood.py
AttributeError: type object 'open3d.open3d.geometry.RGBDImage' has no attribute 'RGBDImage'
Still No Solutions ...

**Comment by Resays** [comment]
Found a solution: 
rgbd_image = o3d.geometry.create_rgbd_image_from_color_and_depth(color_raw, depth_raw)
Just skipped RGBDImage and its working now

**Comment by yxlao** [comment]
close with #1055
