### ISSUE TITLE
create_sphere() doesn't exist

### ISSUE THREAD

**Issue by gerardoglz** [intel-isl/Open3D#1034]
The code:

import open3d as o3d
mesh_sphere = o3d.geometry.TriangleMesh.create_sphere(radius=1.0)

produces an error:
AttributeError: type object 'open3d.open3d.geometry.TriangleMesh' has no attribute 'create_sphere'

for any type of basic geometry, such as a box, sphere, etc.

Also, please update your tutorials to correct that issue, i.e. 
http://open3d.org/docs/tutorial/Basic/visualization.html#geometry-primitives

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.5
 - Open3D version: 0.7
 - Is this remote workstation?:  no
 - How did you install Open3D?: pip

**Comment by griegler** [comment]
The same problem as in #1028. The online documentation is unfortunately associated with the master branch and not the latest release. You should be able to use `o3d.create_mesh_sphere()`.

**Comment by yxlao** [comment]
fixed with #1055
