### ISSUE TITLE
How to use point cloud to make triangle mesh?

### ISSUE THREAD

**Issue by AhnHyeongHyun** [intel-isl/Open3D#1037]
Hi. all 
Question. How to use point cloud to make triangle mesh?

**Comment by griegler** [comment]
This is possible with a surface reconstruction method, e.g. Ball Pivoting, or Poisson. Neither is yet implemented in open3d, but we are working on it.

**Comment by lookquad** [comment]
Hi is there any update on this? I mean is there a way to convert a point cloud into triangle mesh?

**Comment by prewettg** [comment]
Open3D does now support surface reconstruction and there is a [tutorial](http://www.open3d.org/docs/release/tutorial/geometry/surface_reconstruction.html) for using the various algorithms.
