### ISSUE TITLE
Visual 3d voxel grid from numpy 3d array

### ISSUE THREAD

**Issue by rjtshrm** [intel-isl/Open3D#1040]
I have a numpy 3d cube containing voxels data. Is there any way i can convert it to point cloud and visualize it.

**Comment by griegler** [comment]
You could use `np.where(grid == 1)` on your `grid` to get the voxel indices, where the grid data is `1`. Concatenating those, you can then use `pcd = o3d.geometry.PointCloud(); pcd.points = o3d.utility.Vector3dVector(cat_indices)` to set the point coordinates.

**Comment by rjtshrm** [comment]
Why are we comparing grid values with 1. Wouldn't it be better to compare it with values <= 0 as voxels with values less than 0 contains the surface.

**Comment by griegler** [comment]
You can use any condition you like. I assumed occupancy grids, but if you have TSDF values then `<= 0` might be more appropriate.

**Comment by rjtshrm** [comment]
Thanks
