### ISSUE TITLE
 object 'open3d.open3d.geometry.VoxelGrid' has no attribute 'create_from_point_cloud'"

### ISSUE THREAD

**Issue by DariusKopka** [intel-isl/Open3D#1042]
import open3d as o3d

o3d.geometry.VoxelGrid.create_from_point_cloud(pcd, voxel_size=0.05)

throw the folling error:

AttributeError("type object 'open3d.open3d.geometry.VoxelGrid' has no attribute 'create_from_point_cloud'",)

**Comment by griegler** [comment]
Have installed open3d via pip/conda? Then this is related to #1013. 
@yxlao Any progress on the online documentation?

**Comment by Anksss3d** [comment]
I was facing the same issue, I uninstalled open3d-python and installed just "open3d" package. 
It is working properly now.

**Comment by wangsijieQAQ** [comment]
> I was facing the same issue, I uninstalled open3d-python and installed just "open3d" package.
> It is working properly now.

It really works, Thanks!
