### ISSUE TITLE
open3d.vector3dvector() is very slow

### ISSUE THREAD

**Issue by wyjforwjy** [intel-isl/Open3D#1045]
open3d.vector3dvector() is very slow.And i install open3d by 'pip install open3d-python==0.7.0.0'.anynoe has encoutered this problem?

**Comment by yxlao** [comment]
`Vector3dVector` is optimized for numpy array with `float64` datatype with memory mapping. Try using `np.float64` array as input.

Example benchmark:
```python
import open3d as o3d
import numpy as np
import time

foo = np.ones((1000000, 3), dtype=np.int32).tolist()
s = time.time()
bar = o3d.utility.Vector3dVector(foo)
print("time python list:", time.time() - s)

foo = np.ones((1000000, 3), dtype=np.int32)
s = time.time()
bar = o3d.utility.Vector3dVector(foo)
print("time numpy int32:", time.time() - s)

foo = np.ones((1000000, 3), dtype=np.float64)
s = time.time()
bar = o3d.utility.Vector3dVector(foo)
print("time numpy float64:", time.time() - s)
```

Output:
```
time python list: 1.6182281970977783
time numpy int32: 0.8991620540618896
time numpy float64: 0.008487939834594727
```

**Comment by wyjforwjy** [comment]
Thank you very much! @yxlao

**Comment by wyjforwjy** [comment]
In the question “Vector3dvector and other vector Eigen bindings speed up ”: 
open3d.Vector3dVector: (2000000, 3)
open3d -> numpy: 0.024798s
numpy -> open3d: 0.000017s
how did you make it so fast?

**Comment by wyjforwjy** [comment]
@yxlao

**Comment by wyjforwjy** [comment]
I mean that numpy -> open3d: 0.000017s, and in your answer   time numpy float64: 0.008487939834594727s .It's a great difference!

**Comment by wyjforwjy** [comment]
@yxlao hope for your reply~~

**Comment by yxlao** [comment]
@wyjforwjy could you show a complete script of how you get the `open3d -> numpy` and `numpy -> open3d` benchmark numbers?

If your question is "how did you make it so fast?", it's implemented in https://github.com/intel-isl/Open3D/pull/657, by reducing python API calls at the python binding level.

In my additional tests:

```python
import open3d as o3d
import numpy as np
import time

np_vals = np.ones((1000000, 3), dtype=np.float64)
s = time.time()
o3d_vals = o3d.utility.Vector3dVector(np_vals)
print("time numpy->open3d:", time.time() - s)

s = time.time()
np_vals = np.asarray(o3d_vals)
print("time open3d->numpy:", time.time() - s)
```

Output:
```
time numpy->open3d: 0.007127285003662109
time open3d->numpy: 9.751319885253906e-05
```

So my current conclusion is: 
1) To go from `numpy->open3d` using `Vector3dVector`, make sure to use `np.float64`.
2) Even with the `np.float64` trick, going from `open3d->numpy` is still faster than `numpy->open3d`.

**Comment by dasantonym** [comment]
> Output:
> 
> ```
> time numpy->open3d: 0.007127285003662109
> time open3d->numpy: 9.751319885253906e-05
> ```
> 
> So my current conclusion is:
> 
>     1. To go from `numpy->open3d` using `Vector3dVector`, make sure to use `np.float64`.
> 
>     2. Even with the `np.float64` trick, going from `open3d->numpy` is still faster than `numpy->open3d`.

@yxlao (or who this might otherwise be of interest to): I am just starting out with Open3D (version 0.17.0) having issues with point cloud performance as well.

If I run the sample code posted above, I get the following times:

```
time numpy->open3d: 0.003468036651611328
time open3d->numpy: 1.5735626220703125e-05
```

But if I change it to:

```python
np_vals = np.random.random_sample((3, 1000000)).T.astype(np.float64)
s = time.time()
o3d_vals = o3d.utility.Vector3dVector(np_vals)
print("time numpy->open3d:", time.time() - s)

s = time.time()
np_vals = np.asarray(o3d_vals)
print("time open3d->numpy:", time.time() - s)
```

I get:

```
time numpy->open3d: 0.33545708656311035
time open3d->numpy: 1.0013580322265625e-05
```

Notice that the array initialised with random numbers initialises about 100x slower than the one initialised with ones.

Is my observation correct or am I missing something here? And how can I speed this up?

**Comment by happyjason9** [comment]
@yxlao Thank you so mush!!!
