### ISSUE TITLE
TriangleMesh missing function is_intersecting

### ISSUE THREAD

**Issue by 51N84D** [intel-isl/Open3D#1047]
I'm trying to use the function is_intersecting from the TriangleMesh class, but I'm getting the error:

AttributeError: 'open3d.open3d.geometry.TriangleMesh' object has no attribute 'is_intersecting'

**Comment by griegler** [comment]
Can you provide more details, like how did you install open3d, which version are you using, and can you provide a code snippet that is not working?

**Comment by 51N84D** [comment]
I've installed open3d-python using pip. Here is the code snippet:

`import numpy as np
import open3d as o3d

#Load mesh
mesh = o3d.io.read_triangle_mesh("./data/bunny/bunny.ply")

point1 = np.expand_dims(np.asarray([0,0.1,0]), axis = 0)
point2 = np.expand_dims(np.asarray([0,0,0]), axis = 0)
point3 = np.expand_dims(np.asarray([0.05,0,0]), axis = 0)


points = np.concatenate((point1, point2, point3), axis = 0)
triangle_face = np.expand_dims(np.asarray([0, 1, 2]), axis = 0)

#--------------------VISUALIZATION-----------------------------
tri = o3d.geometry.TriangleMesh()
tri.triangles = o3d.utility.Vector3iVector(triangle_face)
tri.vertices = o3d.utility.Vector3dVector(points)
#o3d.visualization.draw_geometries([tri, mesh])
#------------------------------------------------------------

mesh.is_intersecting(tri)
`


This results in the error:
AttributeError: 'open3d.open3d.geometry.TriangleMesh' object has no attribute 'is_intersecting'

**Comment by 51N84D** [comment]
Ah, I found I was using version 0.6 rather than 0.7. Upgrading solved the problem
