### ISSUE TITLE
Is there any support for .obj file?

### ISSUE THREAD

**Issue by LYHTHU** [intel-isl/Open3D#1054]
It seems that both `open3d.read_triangle_mesh` and ` open3d.io.read_triangle_mesh` fails reading .obj file.
It shows "Read geometry::TriangleMesh failed: unknown file extension."
I tested it with a plane model in ShapeNet.

**Comment by griegler** [comment]
It should be possible with the code in the master branch (compile from source), but not with the versions installed from pip/conda.

**Comment by LYHTHU** [comment]
> It should be possible with the code in the master branch (compile from source), but not with the versions installed from pip/conda.

And is there any support for convert tri-mesh to point cloud now? Thanks.
