### ISSUE TITLE
Python interface of open3d.geometry.sample_points_poisson_disk

### ISSUE THREAD

**Issue by XLechter** [intel-isl/Open3D#1057]
Hi, I read the official doc and I found that in python interface:
open3d.geometry.sample_points_poisson_disk() is not found. While other sampling methods like open3d.geometry.voxel_down_sample() can work properly.
I get open3d 0.7.0.0 from pip install.
Thank you.

**Comment by yxlao** [comment]
@XLechter it works for me (ubuntu 18.04, py3.6, open3d 0.7.0 from pip)

Could you include a terminal log, where you create a fresh virtual env, install open3d from pip and run `python -c "import open3d; print(open3d.geometry.sample_points_poisson_disk)"`

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
