### ISSUE TITLE
How to disable read_point_cloud command line output? 

### ISSUE THREAD

**Issue by XuyangBai** [intel-isl/Open3D#1062]
Hi. I was wondering if there's any way to suppress the output to the command line related to ` read_point_cloud` every time I run my program. I am talking about this:
```
Reading PLY: [========================================] 100%
Reading PLY: [========================================] 100%
Reading PLY: [========================================] 100%
Reading PLY: [========================================] 100%
Reading PLY: [========================================] 100%
```

**Comment by kongsgard** [comment]
Suppressing command line output for `read_point_cloud` is not supported.
The same applies to all read/write functions. Perhaps a `suppress_cmd_output` flag should be added to these?

**Comment by griegler** [comment]
Actually, it is possible by setting global the verbosity level. See #884.
