### ISSUE TITLE
Determine scaling before registration ?

### ISSUE THREAD

**Issue by HndsmJohn** [intel-isl/Open3D#1063]
Hello everyone,

**Is your feature request related to a problem? Please describe.**
I use the Open3D ICP Registration algorithms to try to match two point clouds, one coming from a depth camera, one extracted from a STL file. The goal is to determine a precise relative position of the camera with the filmed object, given a comparison between the two point clouds.

![Models](https://user-images.githubusercontent.com/26006858/60820713-4d969980-a1a2-11e9-8c66-57ddf7eac30e.png)

The red object represents the cloud coming from the camera, the green one is from the STL file.
On this case, for developing purposes, I used 2 similar point clouds of the same object, the red one is only downsampled and rescaled to be twice as big as the green one.

**Describe the solution you'd like**
The Global and ICP registrations work both very fine when the two compared point clouds are about the same size but i can't have a correct transformation matrix when they aren't. Is there any way that the registration can determine if there is a scaling operation to do before computing the transformation matrix ?

**Describe alternatives you've considered**
I considered using my depth camera data in order to have a rough first estimation of the scaling operation to apply but i wondered if there were any direct solution provided by Open3D.

Thank you in advance.

**Comment by syncle** [comment]
``TransformationEstimationPointToPoint`` has ``with_scaling`` option. With this, you can specify whether you would like to solve for 6D rigid transformation as well as the scale parameter.
