### ISSUE TITLE
Incorrect voxel_down_sample usage in tutorial

### ISSUE THREAD

**Issue by supreethsubbaraya** [intel-isl/Open3D#1067]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
The following line in the PointCloud tutorial does not work. 'geometry' package does not have any method called 'voxel_down_sample'

downpcd = o3d.geometry.voxel_down_sample(pcd, voxel_size=0.05)

**To Reproduce**

Run the following lines of code

pcd = o3d.io.read_point_cloud("../../TestData/fragment.pcd")
downpcd = o3d.geometry.voxel_down_sample(pcd, voxel_size=0.05)

**Expected behavior**

I expect the tutorial to show the right method to call for down sampling

**Environment (please complete the following information):**
Any OS

**Additional context**

**Comment by griegler** [comment]
What version of open3d are you using?
Can you post the result of `o3d.__version__ `, because it is working for me in version `0.7`.

**Comment by supreethsubbaraya** [comment]
The output of o3d.__version__ is '0.7.0.0'. I am able to use other methods say in visualization, io etc as shown in the documentation. I am seeing trouble in geometry methods such as 'estimate_normals', 'voxel_down_sample'

**Comment by griegler** [comment]
How did you install open3d, and what OS are you using?

**Comment by supreethsubbaraya** [comment]
I installed open3d from source. i am using Ubuntu 18.04.2.

**Comment by griegler** [comment]
I see. You were looking at the wrong documentation then. For the documentation related to the master branch look at [latest](http://www.open3d.org/docs/latest/tutorial/Basic/pointcloud.html).
