### ISSUE TITLE
How to save integrated color and depth image along with integrated.ply file in ReconstructionSystem

### ISSUE THREAD

**Issue by Resays** [intel-isl/Open3D#1072]
Using the code from ReconstructionSystem, I want to have an integrated color and depth image with integrated.ply file, is it possible to have them both? 
cause later I will grab the objects from a newly constructed .ply file using programming python code

**Comment by Resays** [comment]
anybody can help ? ... what should i do ?

**Comment by qianyizh** [comment]
@yxlao take a look?

**Comment by theNded** [comment]
Need more specific definition of the  feature request. Meaning of 'Integrated color and depth **image**' is kind of ambiguous.

**Comment by Resays** [comment]
Ok, let me explain it in details
I successfully captured 100 images with realsense camera, right?
then I successfully constructed a 3D scene using ReconstructionSystem provided in Open3D examples
and as a result, ReconstructionSystem is displaying and saved a 3D .ply file as a whole scene 
so, I need to save the final color image and depth image after registration of these images as i'm receiving .ply file

I hope you may understand what I'm saying ... if anything else then I can show the process I followed.

**Comment by theNded** [comment]
Can you specify if your requirement is in the following:
1. 2D **input** color/depth images with estimated poses, or
2. 3D colored point clouds by unprojecting **input** color/depth images using estimated poses, or
3. 2D **rendering** from the ply.

**Comment by Resays** [comment]
These are the images i used, color and depth
![1](https://user-images.githubusercontent.com/50095407/61583876-624b3800-ab79-11e9-8636-fa893846bd4a.jpg)
and this is the output .ply file i generated with ReconstructionSystem
![11-1](https://user-images.githubusercontent.com/50095407/61583885-81e26080-ab79-11e9-9212-8b6809916240.jpg)

This one was the camera intrinsic
```
{
    "width": 640,
	"height": 480,
	"intrinsic_matrix": [ 625.637, 0, 0, 0, 625.637, 0, 319.944, 241.388, 1 ]
}
```
and now i want to have a color and depth image along with .ply file

**Comment by Resays** [comment]
3. 2D rendering from the ply (color and depth) both images are required and can I get the objects from .ply file as well? using coding or giving points to ply file?
crop_point_cloud is working with mouse clicks but I want to crop point cloud by giving points in the code
like I have to detect the objects in point cloud and later need to grab only objects as 3D objects from whole point cloud file.
is it possible?

**Comment by Resays** [comment]
any help @theNded  ?

**Comment by theNded** [comment]
I'm not sure about the python interface, but we can render images in C++ using the precomputed camera poses.
[Ref](https://github.com/theNded/Open3D/blob/cuda/examples/Cuda/Demo/ScalableFusionCuda.cpp#L95)
The camera poses can be obtained in python like [this](https://github.com/intel-isl/Open3D/blob/master/examples/Python/ReconstructionSystem/integrate_scene.py#L44), and in C++ like [this](https://github.com/theNded/Open3D/blob/cuda/examples/Cuda/ReconstructionSystem/IntegrateScene.h#L46) (there might have been changes in APIs).

Regarding the second request, we don't support masking in mesh now. If your input are point indices that are consistent with integrated.ply, then we may find a workaround for this to preprocess mesh before rendering.

**Comment by germanros1987** [comment]
@Resays is this issue still bothering you?
