### ISSUE TITLE
How to display textured mesh in Visualizer window.

### ISSUE THREAD

**Issue by lvgeng** [intel-isl/Open3D#1074]
### **Displaying images in 3D space of visualizer as a quad?**
I am wondering, is there some kind of way to display a textured mesh? Or a simpler version, is there any way to display a quad textured by a rectangle image in the visualizer along side with point clouds, linesets, and other geometries?

Currenly I am using the way suggested by @qianyizh
https://github.com/intel-isl/Open3D/issues/525#issuecomment-417601602
But it does not seem to be a suitable solution while there are a lot of images needed to be displayed. There is a trade off between image resolution (or I should say the points amount of the point cloud converted from it.) and the frame rate of the viewer. 

According to https://github.com/intel-isl/Open3D/issues/525
It seems that open3D does not have modules dealing with that. But According to this issue:
https://github.com/intel-isl/Open3D/issues/1050
It appears that the images is something in the 3D space of the visualizer, otherwise there would be no "behind"

### **Displaying textured mesh?**
According to the tutorial 
http://www.open3d.org/docs/release/tutorial/Basic/visualization.html#geometry-primitives
it is possible to add some predefined geometry primitives and read triangle mesh then display it. 
However I did not find anything for texturing. 

### **Displaying transparent geometry?**
Em... I did not find how to set the alpha channel of geometries. Is it possible?

I would be really happy if these functions are available in open3D!

**Comment by syncle** [comment]
We are working on this. Some of efforts are merged recently. Please check #1194 and #1208.

**Comment by lvgeng** [comment]
> We are working on this. Some of efforts are merged recently. Please check #1194 and #1208.

Em... I failed to find the TexturedTriangleMesh API in documents... 
I wish to be able to modify the UV map (Like assign different texture for a triangle, or at least to be able to tell the id of the certain triangle and its vertexes so that I can modify it with some other tools?)

BTW:
The rendering looks good!

**Comment by germanros1987** [comment]
This is solved in the new visualization system.
