### ISSUE TITLE
Geometry.PointCloud has no attribute 'rotate' or 'scale'

### ISSUE THREAD

**Issue by HndsmJohn** [intel-isl/Open3D#1076]
Hi, I used pip to install Open3D in my environment and when I try to use the "rotate" or "scale" members of geometry.PointCloud I got an error that this class doesn't have these attributes even though I saw they are present in the documentation. Are these functions considered work in progress or did I install the package incorrectly ?

In advance, thank you for your answer.

**Comment by griegler** [comment]
If you have installed the latest version via pip, then `rotate` and `scale` should be available for the `PointCloud` objects. What is the output of `import open3d as o3d; print(o3d.__version__)`?

**Comment by griegler** [comment]
That's the problem then. Can you try to reinstall open3d via pip again and test the version. It should be `0.7.0.0` to access the above mentioned methods.

**Comment by HndsmJohn** [comment]
Yes that was it, thank you very much.
