### ISSUE TITLE
Viusalizer cannot keep window exist without while True loop.

### ISSUE THREAD

**Issue by lvgeng** [intel-isl/Open3D#1081]
The goal:

I want to have a window running non-blockingly, which I can drag the camera and close the window by pressing ESC.

Also I hope to be able to add new geometry into the scene by calling functions. (Hope it is not within the while true loop.)

cause if there is a While True loop I would lose control of the entire program, and it seems that function poll_events() is kind of slow, which would choke the program from doing anything else.

The class open3d.geometry has functions:

open3d.geometry.run()
and 
open3d.geometry.create_window()

I expect it to be able to be non_blocking and run by itself without an external while loop.
But it seems that function run() is creating a blocking window, which would pause the program at there unless press ESC to close the window.

Is it possible to add more geometry when using run()?

The most annoying thing is that the created window automatically closes when the poll_events is not called in a loop. Is it possible to create

**Comment by syncle** [comment]
@qianyizh: Could you comment on this?

**Comment by germanros1987** [comment]
@lvgeng is this issue still bothering you?

**Comment by germanros1987** [comment]
This is now possible and demonstrated in this example: https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/add-geometry.py
