### ISSUE TITLE
Point cloud support for transparency channel

### ISSUE THREAD

**Issue by Timu777** [intel-isl/Open3D#1086]
I don't see an option for a transparency channel in the info for the open3d.PointCloud class. For the work I am doing and I imagine many others as well, being able to define a transparency for each point would be extremely helpful.

If an option for specifying an RGBA value per point were available, open3D would be much more useful. Being able to specify the size of each point is also a possibility, but doesn't create as attractive point clouds. The proposed alternative I have seen elsewhere is to basically render little spheres, however if we are trying to visualize millions of points, this becomes less feasible. Is it a goal at the moment to add RGBA as a point-cloud visualization feature to open3D at some point in the future?

**Comment by yxlao** [comment]
In fact, we plan to support arbitrary data for point clouds (e.g. the user can attach label per point). To correctly visualize point sizes and transparency, we'll have to update the visualizer as well.

**Comment by germanros1987** [comment]
We are also working on an update of the shaders to support transparencies.

**Comment by germanros1987** [comment]
It seems this is not going to be a feasible feature in the end. Having different values of transparency per point is not supported by Filament. There is support for transparency at an object level (i.e., different point clouds), but this doesn't solve your problem.

We will end up implementing new shaders where the point size varies according to the distance. This may be a solution for your problem.

**Comment by richardrl** [comment]
@germanros1987 Is there any update on the transparency channel? How can we do it on a per object level?

**Comment by AlexanderKhazatsky** [comment]
Bump ^

**Comment by Borja21091** [comment]
Any news on the transparency per object feature?

**Comment by mantelllo** [comment]
Still relevant ^
