### ISSUE TITLE
compile issue about fmt/format.h

### ISSUE THREAD

**Issue by ShiwenH** [intel-isl/Open3D#1089]
I am using VS2015 to compile the project.
I got these errors:

**Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	Log	C:\Users\huang\Desktop\Open3D-master\src\Open3D\Utility\Console.h	35**	

The directory of fmt in 3rdParty is not added in the project Addtional Include Directories.

**Comment by griegler** [comment]
Did you init/update the submodules: `git submodule update --init --recursive`, i.e., is the code in the 3rdparty folder? Our CI tests VS2015 and it builds there: https://ci.appveyor.com/project/yxlao/open3d/builds/26181125

**Comment by ShiwenH** [comment]
this command works for me. Thanks so much. I manually downloading the 3rdprty folder and the error appear. Now I can compile it with VS2015. Please close this issue.

**Comment by nkhedekar** [comment]
The same error can also be caused by not adding ${Open3D_LIBRARIES} in your target_link_libraries
