### ISSUE TITLE
Little error in the reconstruction system example

### ISSUE THREAD

**Issue by a17sans** [intel-isl/Open3D#1091]
**Describe the bug**
In `make_fragments.py`, line 27, in the example of the git, I got : 

`rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(color, depth, depth_trunc=config["max_depth"], convert_rgb_to_intensity=convert_rgb_to_intensity)`

and got an error telling that there is no `create_from_color_and_depth()` method in the `RGBDImage` class

The method to be called is (if I am not wrong) : 
`create_rgbd_image_from_color_and_depth()` that is in the `o3d.geometry` class. 

Well at least it works perfectly for me with the following line : 

`rgbd_image = o3d.geometry.create_rgbd_image_from_color_and_depth(color, depth, depth_trunc=config["max_depth"], convert_rgb_to_intensity=convert_rgb_to_intensity)`

**Environment**
 - OS: Windows 10
 - Python version: 3.6
 - Open3D version: 0.7.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Comment by griegler** [comment]
That is because the Open3D API did change. The example code in the git master branch reflects the new API which is not compatible with the one you get when installing via pip.
