### ISSUE TITLE
EstimateNormals - Transitition between 0.4 and 0.7

### ISSUE THREAD

**Issue by goatShaver** [intel-isl/Open3D#1093]
I am using PointCloudRegistration from user TimFelle. It relies heavily on Open3D. This is a section of code that loads the point cloud files. It uses EstimateNormals. Open3D appears to have changed significantly or I am missing something. Can you point me to a resolution of how to map this code for Open3D 0.4 to Open3D 0.7?

// Load the datafiles
size_t nSurfaces = dataName.size();
vector<geometry::PointCloud> model(nSurfaces);
for (int s = 0; s < nSurfaces; s++)
   io::ReadPointCloud(dataName[s], model[s]);
for (int s = 0; s < nSurfaces; s++) {
	if (!model[s].HasNormals())
	{
	  **EstimateNormals(model[s])**;
	  model[s].NormalizeNormals();
	}
}

**Comment by Andreachen0707** [comment]
Try ```model[s].EstimateNormals(geometry::KDTreeSearchParamKNN())```

**Comment by goatShaver** [comment]
This appears to have been it - everything compiles now. I unfortunately can't test as my data is on machine at home and I'm on vacation through end of this week.
Thanks for the advice/input - much appreciated.
