### ISSUE TITLE
How to save draw_geometries output as png or jpg

### ISSUE THREAD

**Issue by rupeshchandgude** [intel-isl/Open3D#1095]
Is there any way to save output of draw_geometries as jpg or png format in python?

**Comment by Nerolf05** [comment]
This tutorial should be helpful: [customized visualization](http://www.open3d.org/docs/release/tutorial/Advanced/customized_visualization.html#customized-visualization) then go to "Capture images in a customized animation" 
The example shows the "vis.capture_screen_float_buffer(False)" Method to take a screenshot, which could be saved using the "plt.imsave()" Method.

**Comment by Nerolf05** [comment]
I have an additional question.
Is there a way to close my visualizer/figure? I want to make a movie of my pointcloud at different epochs using python.

Thanks in advance

**Comment by rupeshchandgude** [comment]
> I have an additional question.
> Is there a way to close my visualizer/figure? I want to make a movie of my pointcloud at different epochs using python.
> 
> Thanks in advance

Thanks @Nerolf05 .I also stuck in that point. I am able to store the image once I close the visualizer output. I have to deploy my code on server,where I may not able to close the visualizer output manually. I get to know how to hide window by (vis.create_window(visible = False)), but after loading pcd to it, if we run "vis.run()" command terminal gets hang.

**Comment by rupeshchandgude** [comment]
@Nerolf05  Currently I am able to store depth image, but the same logic fails for storing RGB image.
I use following code for depth :
`vis = o3d.visualization.Visualizer()
vis.create_window(visible = False)
vis.add_geometry(pcd)
depth = vis.capture_depth_float_buffer(True)
plt.imshow(np.asarray(depth))`
For RGB image : 
`vis = o3d.visualization.Visualizer()
vis.create_window(visible = False)
vis.add_geometry(pcd)
img = vis.capture_screen_float_buffer(True)
plt.imshow(np.asarray(img))`

**Comment by Nerolf05** [comment]
@rupeshchandgude  i use `vis.capture_screen_image(path, do_render)` to capture the screen.

I also tried to close the Visualizer with a second Process, but i wasnt able to do it successfully.

**Comment by rupeshchandgude** [comment]
@Nerolf05  Maybe we should  try to find the way to close that window programmatically, so the code will go further to save output.

**Comment by rupeshchandgude** [comment]
@Nerolf05 Following function can be used to store image without visualizer output .

>  vis = o3d.visualization.Visualizer()
    vis.create_window()
    vis.add_geometry(pcd)
    vis.update_geometry()
    vis.poll_events()
    vis.update_renderer()
    vis.capture_screen_image(path)
    vis.destroy_window()

**Comment by ArashJavan** [comment]
Hello, sorry, but i have to repoen this issue, because the proposed method by @Nerolf05  raises following exception:

```
    vis.update_geometry()
TypeError: update_geometry(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.open3d.visualization.Visualizer, arg0: open3d.open3d.geometry.Geometry) -> bool
```

**Comment by alainchau** [comment]
@ArashJavan The following should work on v0.10.0:
```
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(pcd)
vis.update_geometry(pcd)
vis.poll_events()
vis.update_renderer()
vis.capture_screen_image(path)
vis.destroy_window()
```

**Comment by szat** [comment]
For anyone that wonders: to get the depth map into a local variable without displaying:

vis = o3d.visualization.Visualizer()
vis.create_window(visible=False)
vis.add_geometry(mesh)
vis.update_geometry(mesh)
vis.poll_events()
vis.update_renderer()
depth = vis.capture_depth_float_buffer(do_render=False)
vis.destroy_window()

**Comment by Stchena** [comment]
If your screenshots turn out dark/black/without anything, you're probably missing the `do_render` option inside your `capture_screen_image` call

**Comment by happyiminjay1** [comment]
vis = o3d.visualization.Visualizer()
    vis.create_window(visible=False)
    vis.add_geometry(pcd)
    vis.update_geometry(pcd)
    vis.poll_events()
    vis.update_renderer()
    vis.capture_screen_image('f{i}.png',do_render=True)
    vis.destroy_window()
