### ISSUE TITLE
Files with Unicode path are not read

### ISSUE THREAD

**Issue by mwil** [intel-isl/Open3D#1098]
**Describe the bug**
(This may only apply to Windows 10) I'm trying to read a PCD file using `open3d.io.read_point_cloud`. The operation yields the correct result if the path to the file is in ASCII, but for paths that include Unicode characters the read operation returns an empty object.

`os.path.isfile()` returns true for the file including Unicode, and I use the same path for other operations without issue. I think it must be related to how Open3D handles the path internally.

**To Reproduce**
- Create a Unicode folder ("出典データ" for me)
- Try reading the file using `read_point_cloud`

**Expected behavior**
Read the file from any valid location.

**Environment (please complete the following information):**
 - OS: Win 10 Pro
 - Python version: 3.7.3
 - Open3D version: 0.7.0
 - Is this remote workstation? no
 - How did you install Open3D? conda

**Comment by griegler** [comment]
Yes, seems to be related to Windows and `fopen`. Cf. https://stackoverflow.com/questions/396567/is-there-a-standard-way-to-do-an-fopen-with-a-unicode-string-file-path
Not sure what the best way is to handle this. @yxlao @qianyizh any suggestions?

**Comment by griegler** [comment]
Can you test PR #1190 if it fixes your problem?

**Comment by griegler** [comment]
Fixed in #1190.
