### ISSUE TITLE
VoxelGrid.voxels.append() does not append

### ISSUE THREAD

**Issue by SilvioJin** [intel-isl/Open3D#1101]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
open3d.geometry.VoxelGrid.voxels.append(voxel) does not append the voxel object or any other object.

My goal is to create a VoxelGrid object from a numpy array of shape (128,128,128).

**To Reproduce**
```
import open3d as o3d
import numpy as np

vg = o3d.geometry.VoxelGrid()
vox = o3d.geometry.Voxel()
vox.grid_index = np.array([  7,  59, 101])
vg.voxels.append(vox)
```

but `print(vg.voxels)` just returns `[]`
and of course `print(vg.has_voxels)` says `<bound method PyCapsule.has_voxels of geometry::VoxelGrid with 0 voxels.>`

**Expected behavior**
vg.voxels should contain the Voxel object 

**Environment (please complete the following information):**
 - OS: OSX Mojave 10.14.5 
 - Python version: 3.6.5
 - Open3D version: 0.7.0.0
 - Is this remote workstation?:  no
 - How did you install Open3D?: conda

**Comment by griegler** [comment]
That seems to be a limitation of [pybind11](https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#making-opaque-types). As the `VoxelGrid` class is subject to some changes anyway it might not be worth to implement a fix atm. 
What you can however do to achieve your goal is to first collect all voxels in a Python list, and then assign this list to the `VoxelGrid`

```
voxels = []
vox = o3d.geometry.Voxel()
vox.grid_index = np.array([  7,  59, 101])
voxels.append(vox)
vg.voxels = voxels
```
