### ISSUE TITLE
RemoveStatisticalOutliers function bugs

### ISSUE THREAD

**Issue by XuChengHUST** [intel-isl/Open3D#1105]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
RemoveStatisticalOutliers function (Open3D/src/Open3D/Geometry/DownSample.cpp) bugs makes it not working properly.
line 454: kdtree.SearchKNN(points_[i], int(nb_neighbors), tmp_indices, dist);
the dist here is the **squared** Euclidean dist, and should **NOT** be accumulated directly.
but as in line 458: mean = std::accumulate(dist.begin(), dist.end(), 0.0) / dist.size();
the squared_dists are directly averaged to get the mean_dist value. In fact, the squared_dist should be first "sqrt()" to get the correct mean_dist.

A reference implement of this function is in pcl library is in line 113-116 of "pcl/filters/include/pcl/filters/impl/statistical_outlier_removal.hpp"
// Calculate the mean distance to its neighbors
    double dist_sum = 0.0;
    for (int k = 1; k < mean_k_ + 1; ++k)  // k = 0 is the query point
      dist_sum += sqrt (nn_dists[k]);

**Comment by griegler** [comment]
Addressed in #1126.
