### ISSUE TITLE
Global optimization speed

### ISSUE THREAD

**Issue by ShiwenH** [intel-isl/Open3D#1106]
Hi, I read the tutorial.http://www.open3d.org/docs/release/tutorial/Advanced/multiway_registration.html 
I've rewrited it into c++ and found that the speed is not good.
The input is 10 frames and each frame contains around 60,000 points.
I've also set the voxel size to a value which I think is a reasonable value.
It costs me 25s to process 10 frames.
The result is good but the speed is not. If I input more frames, the time will increase dramatically.

My code is here: https://github.com/ShiwenH/Open3DTest/blob/master/Source.cpp.

Am I using the SDK in a right way?

**Comment by syncle** [comment]
After a quick look, [these lines](https://github.com/ShiwenH/Open3DTest/blob/master/Source.cpp#L34-L37) are suspicious: Why you are using original point clouds for the rough ICP alignment? Rather than that, it is recommended to use a downsampled point cloud set. It will boost computation speed.

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
