### ISSUE TITLE
How to save screen capture？

### ISSUE THREAD

**Issue by ArcPi** [intel-isl/Open3D#1110]
I use this code try to save screen capture，there is no error，but the image saved is black. How to save screen capture？
`
vis = o3d.visualization.Visualizer()  
vis.create_window()
vis.add_geometry(pcd)
vis.update_geometry()
vis.poll_events()
vis.update_renderer()
vis.capture_screen_image('test.png')
vis.run()
vis.destroy_window()`

**Comment by griegler** [comment]
Have you tried: `vis.capture_screen_image('test.png', true)`?
Is the window visible and showing the image prior to this function call, i.e., try to add `time.sleep(5)` before the `capture_screen_image`?

**Comment by prerakmody** [comment]
When I do the following, it works
```
import time
import open3d as o3d

# Visualize Point Cloud
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(pcd)

# Read camera params
param = o3d.io.read_pinhole_camera_parameters('cameraparams.json')
ctr = vis.get_view_control()
ctr.convert_from_pinhole_camera_parameters(param)

# Updates
vis.update_geometry()
vis.poll_events()
vis.update_renderer()

# Capture image
time.sleep(1)
vis.capture_screen_image('cameraparams.png')
# image = vis.capture_screen_float_buffer()

# Close
vis.destroy_window()
```

I apparently do not need to `vis.run()`. 

I also wonder if there is a way to capture images much faster without rendering it on the screen?

**Comment by aj96** [comment]
@prerakmody What platform are you using Open3D on? I tried your code snippet on macos, and it doesn't work. I can visualize the image using plt.imshow, but no matter what I use the save the image, plt.imsave, plt.savefig, cv2.imwrite, it never writes to file. I can confirm that using open3d visualization causes any function that writes to file to fail, even if you are not writing to file the visualization from open3d.
