### ISSUE TITLE
running open3d RGBD odometry on multiple threads

### ISSUE THREAD

**Issue by svabhishek29** [intel-isl/Open3D#1116]
hi,

is it possible to run RGBD odometry on multiple threads so that all the cpu cores are used to calculate the transformation fast, as in real time?

i need to use RGBD odometry as i need to use pose graph optimization 

Thanks

**Comment by syncle** [comment]
RGBD odometry itself runs multi-threaded. For the real-time application, how about considering to use [GPU branch of RGBD odometry](https://github.com/theNded/Open3D)?
