### ISSUE TITLE
Isolated groups of pcd in the stitching results

### ISSUE THREAD

**Issue by lvgeng** [intel-isl/Open3D#1123]
![image](https://user-images.githubusercontent.com/9252650/63259247-c5fa7b00-c275-11e9-983c-cbbefa8ee290.png)

While I am playing with the reconstruction_system... I captured some data with a realsense camera but it seems that the stitching result is weird.

I noticed that it is because of the transformation estimation between images, not the pose graph optimization(Well... although it might be something makes it worse.)

I mean, I am totally fine if it has some false positive matching that make two images overlapping in the wrong way, but why there are isolated groups?

I am just curious about this and if there is some kind of solution, it would be even better.

**Comment by wissalsayhi** [comment]
Hi, 
I'm having the same issue. did you manage to figure it out ?

**Comment by germanros1987** [comment]
@lvgeng do you still care about this? @wissalsayhi if you are having the same issue, could you post your point clouds and the results?

@theNded do you have any bandwidth to take a look?

**Comment by theNded** [comment]
This is mainly because of a lack of structure in the dataset and FGR fails. Closed for now, will reopen if problem arises.
