### ISSUE TITLE
camera.PinholeCameraIntrinsic.set_intrinsics, TypeError

### ISSUE THREAD

**Issue by Moon0shang** [intel-isl/Open3D#1127]
the errors is like this

```
File "read.py", line 116, in <module>
    intr.set_intrinsics(width=width,height=height,fx=fx,fy=fy,cx=cx,cy=cy)
TypeError: set_intrinsics(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.open3d.camera.PinholeCameraIntrinsic, width: int, height: int, fx: float, fy: float, cx: float, cy: float) -> None
Invoked with: kwargs: width=640, height=480, fx=575.816, fy=575.816, cx=320.0, cy=240.0
```
i've tried `int(width/height)`, `float(cx/cy/fx/fy)`, but the problem still exist, how can i solve it?

**Comment by syncle** [comment]
Could you try cx=319.5, cy=239.5?

**Comment by dhrosquete** [comment]
I'm having the same issue, still can't figure it out

**Comment by theNded** [comment]
Could you check if `o3d.camera.PinholeCameraIntrinsic(int(width), int(height), fx, fy, cx, cy)` is working?

**Comment by Moon0shang** [comment]
> Could you try cx=319.5, cy=239.5?

It doesn't work either.
```
TypeError: set_intrinsics(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.open3d.camera.PinholeCameraIntrinsic, width: int, height: int, fx: float, fy: float, cx: float, cy: float) -> None
Invoked with: kwargs: width=640, height=480, fx=575.816, fy=575.816, cx=319.5, cy=239.5
```

**Comment by Moon0shang** [comment]
> the errors is like this
> 
> ```
> File "read.py", line 116, in <module>
>     intr.set_intrinsics(width=width,height=height,fx=fx,fy=fy,cx=cx,cy=cy)
> TypeError: set_intrinsics(): incompatible function arguments. The following argument types are supported:
>     1. (self: open3d.open3d.camera.PinholeCameraIntrinsic, width: int, height: int, fx: float, fy: float, cx: float, cy: float) -> None
> Invoked with: kwargs: width=640, height=480, fx=575.816, fy=575.816, cx=320.0, cy=240.0
> ```
> 
> i've tried `int(width/height)`, `float(cx/cy/fx/fy)`, but the problem still exist, how can i solve it?

Problem sloved! It's a bug caused by my careless, I make a wrong use of `intr= o3d.camera.PinholeCameraIntrinsic()` for losing the `()`

**Comment by Moon0shang** [comment]
> Could you check if `o3d.camera.PinholeCameraIntrinsic(int(width), int(height), fx, fy, cx, cy)` is working?

Thank you for your help!

**Comment by Moon0shang** [comment]
> I'm having the same issue, still can't figure it out

Problem sloved! It's a bug caused by my careless, I make a wrong use of `intr= o3d.camera.PinholeCameraIntrinsic()` for losing the `()`

**Comment by dhrosquete** [comment]
Thank you @Moon0shang !!!
