### ISSUE TITLE
Getting error in custom_draw_geometry while running code on server machine

### ISSUE THREAD

**Issue by rupeshchandgude** [intel-isl/Open3D#1129]
I want to store .ply file output to as a image. For that I have created custom_draw_geometry function to store pcd as image file. The code is as follows: 

> def custom_draw_geometry(pcd,output_img_folder,output_file):
    vis = o3d.visualization.Visualizer()
    vis.create_window()
    vis.add_geometry(pcd)
    vis.update_geometry()
    vis.poll_events()
    vis.update_renderer()
    vis.capture_screen_image(output_img_folder+output_file+'.png')
    vis.destroy_window()
    return (output_img_folder+output_file+'.png')

Above code works fine if I run it on local machine. But when I run it on server machine I got following error: 

> libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
GLFW Error: GLX: Failed to create context: BadMatch (invalid parameter attributes)
Failed to create window

The error occurs at  **vis.create_window()**

Is there any solution to tackle this problem?

**Comment by griegler** [comment]
I assume that you are not using X forwarding and therefore, no windows can be created. You should look at headless rendering here: http://www.open3d.org/docs/release/tutorial/Advanced/headless_rendering.html.

**Comment by meder411** [comment]
I have this same error currently, actually. I am running inside a docker container. X forwarding is set up, it seems—I’ve tested it with the `xeyes` application. Is there any clear resolution?

**Comment by atyshka** [comment]
@meder411 Any solution? Also using x forwarding
