### ISSUE TITLE
using tracking camera pose information to generate a log file used for creating a 3d pointcloud

### ISSUE THREAD

**Issue by NikithaChilukuri** [intel-isl/Open3D#1133]
I want to use tracking camera together with a depth camera to construct a 3D pointcloud  in Open3D. However, I am not able to figure out how to create the log file using the pose information from tracking camera. I have found two types of log files here -(https://github.com/intel-isl/Open3D/tree/master/examples/TestData/RGBD), a trajectory.log file and odometry.log file. I would like to know the difference between the two, which one must be used in my experiment and how I can create that log file. Thank you

**Comment by FLS-BP-US** [comment]
Did you make any progress on this or find an alternative method?

**Comment by NikithaChilukuri** [comment]
No, i haven't figured out a way to do it.

**Comment by germanros1987** [comment]
@qianyizh could you please comment on this?

**Comment by germanros1987** [comment]
@syncle could you advise how to proceed?

**Comment by theNded** [comment]
This is the original format definition: http://redwood-data.org/indoor/regbasic.html
Basically you only need to reorganize your trajectory in the format of
```
source_frame_id    target_frame_id    total_frames
4x4 transformation matrix (camera to world)
```
