### ISSUE TITLE
Cannot run examples 

### ISSUE THREAD

**Issue by minkuanc** [intel-isl/Open3D#1134]
Hi, I just install Open 3D and try to run the examples in the master. The version I install is 0.7.0 and I found that many examples cannot be run. I checked and realized that many defined classes in the examples are only included in the latest version of Open 3D. However, if I follow the instruction from the document, all I get is 0.7.0. Could anyone know how to deal with situation like this?
Many thanks in advance.

**Comment by yxlao** [comment]
If you'd like to keep using 0.7.0
1) pip install Open3D 0.7.0
2) clone Open3D repo, checkout to 0.7.0 branch `git checkout v0.7.0 -b my-branch`
3) run examples there
4) read docs from http://www.open3d.org/docs/release/

If you'd like the latest version
1) clone Open3D repo, checkout `master` branch
2) build Open3D from source and install
3) run examples there
4) read docs from http://www.open3d.org/docs/latest/
