### ISSUE TITLE
How to generate polygon volume file to crop mesh

### ISSUE THREAD

**Issue by rupeshchandgude** [intel-isl/Open3D#1138]
I want to crop the mesh. I have seen example mentioned in open3d document  to crop chair from fragment.ply . I have following mesh from with I want to extract only paper part of mesh. How can I generate polygon volume file attached mesh.

Mesh : [https://drive.google.com/file/d/1boppYj-lYJGpqButUbxm2NL--xgR4WNg/view?usp=sharing](url)

**Comment by syncle** [comment]
Please see [this tutorial](http://www.open3d.org/docs/release/tutorial/Advanced/interactive_visualization.html). 

In short, with the following demo script, you will be able to save polygons in json format.
```
def demo_crop_geometry():
    print("Demo for manual geometry cropping")
    print(
        "1) Press 'Y' twice to align geometry with negative direction of y-axis"
    )
    print("2) Press 'K' to lock screen and to switch to selection mode")
    print("3) Drag for rectangle selection,")
    print("   or use ctrl + left click for polygon selection")
    print("4) Press 'C' to get a selected geometry and to save it")
    print("5) Press 'F' to switch to freeview mode")
    pcd = o3d.io.read_point_cloud("../../TestData/ICP/cloud_bin_0.pcd")
    o3d.visualization.draw_geometries_with_editing([pcd])
```

**Comment by satejm1** [comment]
How exactly would you save the JSON? You can get a copy of the selected model by pressing 'C', but not the JSON.

**Comment by nsedoglavich** [comment]
@syncle, the link to the tutorial is not working. If you happen to know of the updated location of the tutorial, please let me know.

Regards!

**Comment by liuliu66** [comment]
@syncle Hi, I use this demo_crop_geometry function to my point cloud file and segment part of the point cloud into .ply, but the json file do not save the polygon. The json file is :

{
	"axis_max" : 0.0,
	"axis_min" : 0.0,
	"bounding_polygon" : null,
	"class_name" : "SelectionPolygonVolume",
	"orthogonal_axis" : "",
	"version_major" : 1,
	"version_minor" : 0
}

Is that I do not correct draw polygon? Thanks!

**Comment by uneron** [comment]
Here is a currently working link to the tutorial:
http://www.open3d.org/docs/release/tutorial/visualization/interactive_visualization.html

**Comment by jeojeda** [comment]
Hi, do you know how can I adjust the options from the tutorial example?
http://www.open3d.org/docs/release/tutorial/visualization/interactive_visualization.html
I would like to understand how the options are defined.

Also I am trying to save a json file without the "y" option so I can 3d orbit a bit and adjust a different view. In this case the json file is empty.
This is the example with the "Y" option.
![Screenshot 2022-08-29 162422_y option](https://user-images.githubusercontent.com/71338620/187225231-e15747db-989e-4967-b287-5dd6bf61cfb4.jpg)
```
{
	"axis_max" : 3.292724609375,
	"axis_min" : -6.9871826171875,
	"bounding_polygon" : 
	[
		[ -0.10963821306064035, 0.070105379640618026, 0.0 ],
		[ 0.077505749603585181, 0.070105379640618026, 0.0 ],
		[ 0.077505749603585181, -0.12532434563037387, 0.0 ],
		[ -0.10963821306064035, -0.12532434563037387, 0.0 ]
	],
	"class_name" : "SelectionPolygonVolume",
	"orthogonal_axis" : "Z",
	"version_major" : 1,
	"version_minor" : 0
}
```
And this is the example without the "Y" option.
![Screenshot 2022-08-29 162144](https://user-images.githubusercontent.com/71338620/187225241-88e2ff2f-eb21-46a4-9350-77cb2e817c36.jpg)
```
{
	"axis_max" : 0.0,
	"axis_min" : 0.0,
	"bounding_polygon" : null,
	"class_name" : "SelectionPolygonVolume",
	"orthogonal_axis" : "",
	"version_major" : 1,
	"version_minor" : 0
}
```

**Comment by prasq** [comment]
"Hello everyone,

I'm relatively new to Open3D and I'm encountering an issue with using the o3d.visualization.draw_geometries_with_editing([pcd]) function to save the selected volume for cropping. Despite pressing 'Y' before selecting the area, the volume I select appears to be empty in the resulting JSON file. I would greatly appreciate any guidance or insights on how to address this issue.

Thank you in advance for your help!"
