### ISSUE TITLE
PointCloud has no member EstimateNormals and VoxelDownSample

### ISSUE THREAD

**Issue by HndsmJohn** [intel-isl/Open3D#1145]
Hello,

I'm trying to compile my C++ code on a OrangePi. It is a simple program just to test an ICP registration so at one point I have to estimate the normals and downsample my pointclouds.
It compiles with no problem on my computer but it seems that the two functions are missing on the OrangePi.

I load two PLY files to two pointclouds : 
```
  auto src_ptr = std::make_shared<open3d::geometry::PointCloud>();
  auto trgt_ptr = std::make_shared<open3d::geometry::PointCloud>();
  open3d::io::ReadPointCloudFromPLY(src_ply,*src_ptr);
  open3d::io::ReadPointCloudFromPLY(trgt_ply,*trgt_ptr);
```

then I try to use the EstimateNormals and VoxelDownSample functions : 
```
  src_ptr->EstimateNormals();
  trgt_ptr->EstimateNormals();
  src_ptr = src_ptr->VoxelDownSample(3);
  trgt_ptr = trgt_ptr->VoxelDownSample(3);
```

At that point i got these errors : 

> using element_type = class open3d::geometry::PointCloud' {aka 'class open3d::geometry::PointCloud'} has no member named 'EstimateNormals'; did you mean 'HasNormals'?

> 'using element_type = class open3d::geometry::PointCloud' {aka 'class open3d::geometry::PointCloud'} has no member named 'VoxelDownSample'

I build the library from source, the version open3D version is 0.7.0.0. I checked the PointCloud.h file and it seems that the implementation is correct and untouched. 
The gcc version on my computer is :

> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

The one on the OrangePi is : 

> gcc (Debian 8.3.0-6) 8.3.0.

**Environment (please complete the following information):**
 - OS: Armbian Linux 4.19.63-sunxi64
 - Python version: 2.7.16
 - Open3D version: 0.7.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: build from source with gcc

**Comment by yxlao** [comment]
in `0.7.0`, use `geometry::EstimateNormals` and `geometry::VoxelDownSample` see:
https://github.com/intel-isl/Open3D/blob/v0.7.0/examples/Cpp/PointCloud.cpp#L80
https://github.com/intel-isl/Open3D/blob/v0.7.0/examples/Cpp/PointCloud.cpp#L108
You'll need to use the examples from the 0.7.0 tag.
