### ISSUE TITLE
write_point_cloud encodes ply/pcd

### ISSUE THREAD

**Issue by sheshappanavar** [intel-isl/Open3D#1148]
**Description of the bug**
Read a pcd file(consider this as source pcd file), normalized the points, centered the object by subtracting with mean, wrote to another pcd file(consider this as destination pcd file). If the destination pcd file is opened in a text editor it doesn't show the x,y,z points, instead shows some encoding(please see screenshots). Similar behavior is observed if one tries to write a .ply file.

**To Reproduce**
1. Download chair.pcd from here (https://github.com/TonythePlaneswalker/pcn/blob/master/demo_data/chair.pcd)

2. Run below python script (make sure to place this python script and chair.pcd file in the same directory).

import os
import numpy as np
import open3d as o3d

if __name__ == '__main__':
    input = o3d.io.read_point_cloud('chair.pcd')
    input = np.array(input.points)
    mins = np.min(input, axis=0)
    maxs = np.max(input, axis=0)
    diff_max_min = maxs - mins
    norm = (input - mins) / diff_max_min
    center = norm - np.mean(norm, axis=0)
    center_pc = o3d.geometry.PointCloud()
    center_pc.points = o3d.utility.Vector3dVector(center)
    o3d.io.write_point_cloud('normalized_centered_chair.pcd', center_pc)

3. open normalized_centered_chair.pcd in a text editor 
 
**Expected behavior**
The destination file (normalized_centered_chair.pcd) should show the points when opened in a text editor.

**Screenshots**
Source pcd file (chair.pcd)
![image](https://user-images.githubusercontent.com/2320460/63902785-ff9b5680-c9d8-11e9-8c43-17c40e048a64.png)

Destination pcd file (normalized_centered_chair.pcd)
![image](https://user-images.githubusercontent.com/2320460/63902938-b7c8ff00-c9d9-11e9-85d9-b34777638a3c.png)

**Environment (please complete the following information):**
 - OS: OSX Mojave
 - Python version: 3.6.8
 - Open3D version: 0.7.0.0
 - Is this remote workstation?: no (Macbook Pro Laptop)
 - How did you install Open3D?: pip

** Additional Comments **
Test the contents of file copy_of_fragment.pcd written by the below code.
Link: http://www.open3d.org/docs/release/tutorial/Basic/file_io.html

import open3d as o3d
if __name__ == "__main__":
    print("Testing IO for point cloud ...")
    pcd = o3d.io.read_point_cloud("../../TestData/fragment.pcd")
    print(pcd)
    o3d.io.write_point_cloud("copy_of_fragment.pcd", pcd)

**Comment by griegler** [comment]
Note that both file formats that you have mentioned support binary and ascii output. In Open3D you can pass a `write_ascii` parameter (default is set to `false`) in `write_triangle_mesh`. Hence, your default output will be binary.
