### ISSUE TITLE
Is there a bug in estimate_normals?

### ISSUE THREAD

**Issue by nickponline** [intel-isl/Open3D#1151]
I am computing normals for a point cloud and they all appear to be in the positive x-direction?

I have my code here:

https://stackoverflow.com/questions/57734044/why-are-open3d-normals-incorrect-in-x-direction

**Comment by griegler** [comment]
I think you already have a solution in the stackoverflow thread. Just for completeness: `estimate_normals` just fits a plane in the vicinity of a given point and from this plane we derive the normal of the point. However, there are always two possible normals  `+-n` and we need other methods to align them.
