### ISSUE TITLE
Non-blocking visualization doesn't support interactive?

### ISSUE THREAD

**Issue by yzl96** [intel-isl/Open3D#1153]
Hi, I'm using Non-blocking visualization, it works well, I can diplay a sequence of point cloud, but I find now the visualization doesn't support interactive, I can't zoom, change view, and so on. the follow is my code:
`
pcd = open3d.geometry.PointCloud()
    vis = open3d.visualization.Visualizer()
    vis.create_window()
    vis.add_geometry(pcd)
    opt = vis.get_render_option()
    opt.point_size = 1.0

for .....:
         pcd.points = open3d.utility.Vector3dVector(pts_lidar[0, :, :3])
        vis.add_geometry(pcd)
        vis.update_renderer()
        vis.update_geometry()
        vis.poll_events()
`
And I find simple change pcd.points, and use vis.update_geometry() will not change the point cloud display, must call vis.add_geometry(pcd)

**Comment by zzq1016** [comment]
same question I have. 

And I add 3D bounding box for every frame of a series of  point cloud by add_geometry and remove_geometry. This made a movie. When 3d bbox was update(add_geometry and remove_geometry.),  the movie  shocked; where without 3d bbox, only point cloud, the movie did not shocked.  How can I fixed it? 

Thanks for any help

**Comment by yzl96** [comment]
@zzq1016 , Hi, can you tell me how you add bounding box?, I'm trying to add bounding box, following # examples/Python/Basic/bounding_volume.py, but it can't run, I already install 0.7 version open3d....

**Comment by zzq1016** [comment]
I modify [github/3DOD_thesis/visualization/visualize_eval_val_seq.py](url) to add bbox.

**Comment by yzl96** [comment]
@zzq1016 , I fix that, the visualization can interactive  with box on.
![Screenshot from 2019-09-03 21-26-59](https://user-images.githubusercontent.com/31734981/64177267-bdb75800-ce91-11e9-9984-78d8f65f58b7.png)

remeber, if you use add_geometry() more than once, the visualization will not be interactive, so for a sequence of point cloud, just use add_geometry(pcd) at the first, then update pcd, the same with bbox.

**Comment by zzq1016** [comment]
@yzl96 How update bbox?  For every point cloud frame, bboxes are different. So, for each frame of a lidar cloud sequence, I add_geometry(bboxes), display and then remove_geometry(bbox). 

Did you dispaly  a sequence of point cloud as a continuous video or only a image once?

**Comment by perryshao** [comment]
> same question I have.
> 
> And I add 3D bounding box for every frame of a series of point cloud by add_geometry and remove_geometry. This made a movie. When 3d bbox was update(add_geometry and remove_geometry), the movie shocked:
> 
> ![destroy](https://user-images.githubusercontent.com/23305020/64155876-41f3e600-ce66-11e9-8032-30d408deed23.gif)
> 
> where without remove_geometry, the movie did not shocked:
> ![no_destroy](https://user-images.githubusercontent.com/23305020/64155868-3e605f00-ce66-11e9-88a6-7d5ada7393a7.gif)
> 
> How can I fixed it?
> 
> Thanks for any help

@zzq1016 have you fixed the problem? my movie is also shocked, i don't know the reason.

**Comment by flyaudio** [comment]
> 
> 
> @zzq1016 , I fix that, the visualization can interactive with box on.
> ![Screenshot from 2019-09-03 21-26-59](https://user-images.githubusercontent.com/31734981/64177267-bdb75800-ce91-11e9-9984-78d8f65f58b7.png)
> 
> remeber, if you use add_geometry() more than once, the visualization will not be interactive, so for a sequence of point cloud, just use add_geometry(pcd) at the first, then update pcd, the same with bbox.

By following your suggestion on using add_geometry() once only, It didn't work for me.
BTW, I compile the open3d source code using master branch,  not pip installation

**Comment by TommasoBendinelli** [comment]
my points do not get update with update geometry

**Comment by MaxChanger** [comment]
I think it makes sense to solve this bug, and I got stuck when visualizing BBox.
When using non-blocking to visualize the PointCloud and BBox of each frame, I got the same result as the above picture.
Any progress? @zzq1016 @yzl96 
Call @griegler for help

**Comment by gaurav00700** [comment]
I am also facing the same issue suring visualzation of 3d bounding boxes. I there any fix for this  ?

**Comment by saurabheights** [comment]
@gaurav00700 Can you provide some small data and code to replicate the issue?

**Comment by gaurav00700** [comment]
> @gaurav00700 Could you update the code to be complete. I dont know what create_3dbbox_mesh, update_geometry_o3d, etc.
> 
> Having a complete example will allow me to quickly make changes and see what is going wrong.
> 
> Furthermore, just from a quick look, I think you should keep an array of previous frame bboxes so that you can remove them before adding new boxes. Also, update_renderer should be called after the removal of bounding boxes of previous frame.

I have updated the code in above comment.
Can you please check and seggest me how to resolve the issue.

**Comment by saurabheights** [comment]
@gaurav00700 Could you also provide some sample value for corner_pnts_bboxs?

**Comment by saurabheights** [comment]
@gaurav00700 So,  it lols like a bug. I did the setup with randomly generated bounding boxes. Add and remove geometry blocked interactive movement like zoom. By passing `reset_bounding_box=False`, I was able to circumvent the issue.

```
import random
import time

import open3d as o3d


def create_3dbbox_mesh(old_boxes):
    """
    Corner boxes is list of corner points in shape (3x8)
    """
    new_bboxes = []
    for bbox in old_boxes:
        if len(old_boxes) > 3 and random.random() < 0.1:
            # delete the bounding box
            continue
        new_bbox = bbox.translate([0.00001, 0, 0])
        new_bbox.color = [1, 0, 0]
        new_bboxes.append(new_bbox)


    if len(new_bboxes) < 8:
        bbox = o3d.geometry.AxisAlignedBoundingBox([0, 0, 0],
                                                   [1, 1, 1])
        new_bbox = bbox.translate([random.random(), random.random(), random.random()])
        new_bbox.color = [1, 0, 0]
        new_bboxes.append(new_bbox)

    return new_bboxes


# Create a visualization object and window
create_o3d_obj = False
vis = o3d.visualization.Visualizer()
vis.create_window()

# create pcd object
point_cloud_o3d = o3d.geometry.PointCloud()

# Flag for first loop
create_o3d_obj = None
old_bboxes = create_3dbbox_mesh([])
prev_bboxes = create_3dbbox_mesh([])
for bbox_mesh in prev_bboxes:
    vis.add_geometry(bbox_mesh, reset_bounding_box=False)
for _ in range(1000):
    # 1: create bounding box meshes
    # function to create bounding box mesh using corner points
    bbox_meshes = create_3dbbox_mesh(prev_bboxes)

    # 2 Add a sample pointcloud to
    dataset = o3d.data.PLYPointCloud()
    office = o3d.io.read_point_cloud(dataset.path)
    point_cloud_o3d.points = o3d.utility.Vector3dVector(office.points)

    # 3: add or update geometry objects
    if not create_o3d_obj:
        vis.add_geometry(point_cloud_o3d)  # add point cloud
        create_o3d_obj = True  # change flag
    else:
        vis.update_geometry(point_cloud_o3d)  # update point cloud

    print(len(bbox_meshes))
    for bbox_mesh in bbox_meshes:  # add bbox_3d meshes
        vis.add_geometry(bbox_mesh, reset_bounding_box=False)

    for bbox_mesh in prev_bboxes:
        vis.remove_geometry(bbox_mesh, reset_bounding_box=False)

    prev_bboxes = bbox_meshes

    # 4 update o3d window
    if not vis.poll_events():
        break
    vis.update_renderer()
```

**Comment by gaurav00700** [comment]
> @gaurav00700 So, it looks like a bug. I did the setup with randomly generated bounding boxes. Add and remove geometry blocked interactive movement like zoom. By passing `reset_bounding_box=False`, I was able to circumvent the issue.
> 
> ```
> import random
> import time
> 
> import open3d as o3d
> 
> 
> def create_3dbbox_mesh(old_boxes):
>     """
>     Corner boxes is list of corner points in shape (3x8)
>     """
>     new_bboxes = []
>     for bbox in old_boxes:
>         if len(old_boxes) > 3 and random.random() < 0.1:
>             # delete the bounding box
>             continue
>         new_bbox = bbox.translate([0.00001, 0, 0])
>         new_bbox.color = [1, 0, 0]
>         new_bboxes.append(new_bbox)
> 
> 
>     if len(new_bboxes) < 8:
>         bbox = o3d.geometry.AxisAlignedBoundingBox([0, 0, 0],
>                                                    [1, 1, 1])
>         new_bbox = bbox.translate([random.random(), random.random(), random.random()])
>         new_bbox.color = [1, 0, 0]
>         new_bboxes.append(new_bbox)
> 
>     return new_bboxes
> 
> 
> # Create a visualization object and window
> create_o3d_obj = False
> vis = o3d.visualization.Visualizer()
> vis.create_window()
> 
> # create pcd object
> point_cloud_o3d = o3d.geometry.PointCloud()
> 
> # Flag for first loop
> create_o3d_obj = None
> old_bboxes = create_3dbbox_mesh([])
> prev_bboxes = create_3dbbox_mesh([])
> for bbox_mesh in prev_bboxes:
>     vis.add_geometry(bbox_mesh, reset_bounding_box=False)
> for _ in range(1000):
>     # 1: create bounding box meshes
>     # function to create bounding box mesh using corner points
>     bbox_meshes = create_3dbbox_mesh(prev_bboxes)
> 
>     # 2 Add a sample pointcloud to
>     dataset = o3d.data.PLYPointCloud()
>     office = o3d.io.read_point_cloud(dataset.path)
>     point_cloud_o3d.points = o3d.utility.Vector3dVector(office.points)
> 
>     # 3: add or update geometry objects
>     if not create_o3d_obj:
>         vis.add_geometry(point_cloud_o3d)  # add point cloud
>         create_o3d_obj = True  # change flag
>     else:
>         vis.update_geometry(point_cloud_o3d)  # update point cloud
> 
>     print(len(bbox_meshes))
>     for bbox_mesh in bbox_meshes:  # add bbox_3d meshes
>         vis.add_geometry(bbox_mesh, reset_bounding_box=False)
> 
>     for bbox_mesh in prev_bboxes:
>         vis.remove_geometry(bbox_mesh, reset_bounding_box=False)
> 
>     prev_bboxes = bbox_meshes
> 
>     # 4 update o3d window
>     if not vis.poll_events():
>         break
>     vis.update_renderer()
> ```

Thank you for the help. Adding argument `reset_bounding_box=False`  while adding and removing bounding boxes fixed the probelm for me.

**Comment by saurabheights** [comment]
@gaurav00700 When reset_bounding_box is set to True, the problem is it resets the view. When your code is running with new `add_geometry/remove_geometry`, it continuously resets the view of Visualizer. This happens so fast, that mouse events are probably getting ignored right away. Hence, visualizer becomes non-interactive.

I have put it in my todo list to update [tutorial](http://www.open3d.org/docs/release/tutorial/visualization/non_blocking_visualization.html) with this information when adding or removing geometry.
