### ISSUE TITLE
set view point for video and video vibrated when destroy bounding box 

### ISSUE THREAD

**Issue by zzq1016** [intel-isl/Open3D#1158]
And I add 3D bounding box for every frame of a sequence of  point cloud by add_geometry and remove_geometry. This made a video. When 3d bbox was update(add_geometry and remove_geometry),  the video  vibrated:

![destroy](https://user-images.githubusercontent.com/23305020/64155876-41f3e600-ce66-11e9-8032-30d408deed23.gif)
and as above gif, the view is bird view and can not change. How can I change or set view point?

 where without remove_geometry,  the video did not vibrate:
![no_destroy](https://user-images.githubusercontent.com/23305020/64155868-3e605f00-ce66-11e9-88a6-7d5ada7393a7.gif)

How can I fixed it? 

Thanks for any help

@syncle, @adamlofts , @martinruenz

**Comment by syncle** [comment]
Adding and removing geometry resets viewpoint automatically. This is why it vibrates. How about saving viewpoint and use the viewpoint parameter once the geometry added/removed? Some useful example for this purpose is [here](https://github.com/intel-isl/Open3D/blob/master/examples/Python/Advanced/load_save_viewpoint.py).

**Comment by perryshao** [comment]
@syncle thank you. your answer really help me with this problem which i have tried to solve it for a long time. I just came across this good answer today.

**Comment by MaxChanger** [comment]
The above-mentioned link may be invalid and can be found in Tag v0.8.0 [load_save_viewpoint.py](https://github.com/intel-isl/Open3D/blob/v0.8.0/examples/Python/Advanced/load_save_viewpoint.py)

**Comment by negiabhinit** [comment]
I have faced a similar issue... can anyone share how to visualize point clouds and bounding boxes for successive frames spontaneously using open3d? @syncle, @adamlofts , @martinruenz
