### ISSUE TITLE
generate point cloud with XYZ/XYZRGB format from mesh file(.obj)

### ISSUE THREAD

**Issue by kaixin-bai** [intel-isl/Open3D#1168]
if i have a mesh file like .obj, whether it is possible to get a point cloud file with format XYZ or XYZRGB with using Open3D?

**Comment by griegler** [comment]
Not sure what your goal is? Do you have a `TriangleMesh` read from a `obj` file and you want the vertices as `PointCloud`? If yes, you could do it like

```
mesh = o3d.io.read_triangle_mesh('file.obj')
pcd = o3d.geometry.PointCloud()
pcd.points = mesh.vertices
pcd.colors = mesh.vertex_colors
pcd.normals = mesh.vertex_normals
```

**Comment by kaixin-bai** [comment]
> Not sure what your goal is? Do you have a `TriangleMesh` read from a `obj` file and you want the vertices as `PointCloud`? If yes, you could do it like
> 
> ```
> mesh = o3d.io.read_triangle_mesh('file.obj')
> pcd = o3d.geometry.PointCloud()
> pcd.points = mesh.vertices
> pcd.colors = mesh.vertex_colors
> pcd.normals = mesh.vertex_normals
> ```
Hi, griegler,
Thanks for your reply. I mean how to convert mesh file to point cloud. I tried the code and got the error below. I install Open3D by pip.

Write geometry::PointCloud failed: unknown file extension.

**Comment by griegler** [comment]
I still do not know what you are trying to achieve. Do you have a minimal code example that shows where you get the errors?

**Comment by kaixin-bai** [comment]
mesh = o3d.io.read_triangle_mesh('/data/textured.obj')
pcdmesh = o3d.geometry.PointCloud()
pcdmesh.points = mesh.vertices
pcdmesh.colors = mesh.vertex_colors
o3d.io.write_point_cloud("pcdmesh.txt", pcdmesh)
c = np.loadtxt('pcdmesh.txt')

Error like this:
Read geometry::TriangleMesh failed: unknown file extension.
Write geometry::PointCloud failed: unknown file extension.
FileNotFoundError: [Errno 2] No such file or directory: 'pcdmesh.txt'

I want point cloud file with XYZRGB format, like this:
-0.027846 -0.0142395 -0.0589482 65 67 59 
-0.0275219 -0.0139881 -0.0590616 55 58 49 
-0.0280927 -0.0142529 -0.0587905 36 39 35 
-0.0282721 -0.0136681 -0.0589085 60 64 58 
-0.0280645 -0.0135111 -0.0590076 80 83 75 
-0.0284768 -0.0137646 -0.0587381 50 52 50 
-0.0284044 -0.0135479 -0.0588771 55 57 53 
-0.0300605 -0.0131893 -0.0521288 128 129 126

**Comment by griegler** [comment]
`txt` is not a supported file format. You can use  `o3d.io.write_point_cloud("pcdmesh.xyzrgb", pcdmesh)` to write in the format you like (although the color values will be in the range of `[0, 1]`). See http://www.open3d.org/docs/release/tutorial/Basic/file_io.html#point-cloud for more formats.

**Comment by kaixin-bai** [comment]
thanks a lot! I can get point cloud with "mesh.vertices" sometimes, but is it possible just to sample point clouds on the mesh file with Open3D?  
![Screenshot from 2019-09-24 15-16-49](https://user-images.githubusercontent.com/38804949/65514826-60d21f00-dede-11e9-8ae0-b81c84571441.png)
![Screenshot from 2019-09-24 15-16-27](https://user-images.githubusercontent.com/38804949/65514827-60d21f00-dede-11e9-91e3-0310edef4b0b.png)

**Comment by griegler** [comment]
http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.sample_points_uniformly
or
http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.sample_points_poisson_disk

**Comment by kaixin-bai** [comment]
Thanks very much!^_^

**Comment by Flock1** [comment]
@griegler, is there some way to create a mesh that's created from a `ply` file using an `obj` file? A lot of mesh datasets provide obj files instead of ply files.

**Comment by liyuanyaun** [comment]
> > Not sure what your goal is? Do you have a `TriangleMesh` read from a `obj` file and you want the vertices as `PointCloud`? If yes, you could do it like
> > ```
> > mesh = o3d.io.read_triangle_mesh('file.obj')
> > pcd = o3d.geometry.PointCloud()
> > pcd.points = mesh.vertices
> > pcd.colors = mesh.vertex_colors
> > pcd.normals = mesh.vertex_normals
> > ```
> 
> Hi, griegler,
> Thanks for your reply. I mean how to convert mesh file to point cloud. I tried the code and got the error below. I install Open3D by pip.
> 
> Read geometry::TriangleMesh failed: unknown file extension.
> Write geometry::PointCloud failed: unknown file extension.

hi could you share how to solve this problem? @kaixin-bai

**Comment by kaixin-bai** [comment]
> > > Not sure what your goal is? Do you have a `TriangleMesh` read from a `obj` file and you want the vertices as `PointCloud`? If yes, you could do it like
> > > ```
> > > mesh = o3d.io.read_triangle_mesh('file.obj')
> > > pcd = o3d.geometry.PointCloud()
> > > pcd.points = mesh.vertices
> > > pcd.colors = mesh.vertex_colors
> > > pcd.normals = mesh.vertex_normals
> > > ```
> > 
> > 
> > Hi, griegler,
> > Thanks for your reply. I mean how to convert mesh file to point cloud. I tried the code and got the error below. I install Open3D by pip.
> > Read geometry::TriangleMesh failed: unknown file extension.
> > Write geometry::PointCloud failed: unknown file extension.
> 
> hi could you share how to solve this problem? @kaixin-bai

The functions offered above "sample_points_uniformly" and "sample_points_poisson_disk" can be used for point cloud sampling on the mesh surface.

**Comment by smithbinky** [comment]
> if i have a mesh file like .obj, whether it is possible to get a point cloud file with format XYZ or XYZRGB with using Open3D?

r is not over x,y,z,c and _-"boi"ranked in systems a_g31#.
