### ISSUE TITLE
Replace GLFW with a library that could be used in threads other than main

### ISSUE THREAD

**Issue by martinakos** [intel-isl/Open3D#1169]
The Visualizer in Open3D is good enough for many use cases but there is one feature of it that is a limitation for me. That's the limitation that GLFW has to run in the main thread. 

This limitation can be worked around when you are creating standalone modules. But in a larger system it forces me to architect my system around this limitation. Also from python I would like to be able to interactively, for debug purposes, add geometries and inspect the current ones while stopped at a breakpoint in the main thread. I could do this if the Visualizer could work in a different Thread. Because of these limitations I'm having to consider using a different visualization library.

**Comment by VinceDT** [comment]
+1

**Comment by TheButlah** [comment]
I think this is also causing issues for me - I get 
```

**Comment by germanros1987** [comment]
Folks, indeed, visualization is complicated and many of the popular libraries try very hard to be "interactive" by taking control of the main thread.

The good news is that we have upgraded the visualization module. Now you will have access to a Render class that lets you render into a buffer. You can decide to visualize that using the GUI module (which will require the main thread) or some other way. Actually, a possible alternative way is the new RPC protocol we are implementing #2090 

@benjaminum do you care to share the benefits of your rpc module?

**Comment by benjaminum** [comment]
With the RPC module it will be possible to run the visualizer in a separate process or even on a different computer and send the geometries over a socket or other transports to it. From my experience this will be especially useful for the interactive debugging you describe @martinakos.

**Comment by germanros1987** [comment]
@martinakos have you seen this example: https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/add-geometry.py ?
