### ISSUE TITLE
ICP Registration tends to worsen the seed transformation

### ISSUE THREAD

**Issue by EnrikDS** [intel-isl/Open3D#1170]
Hi,

I am using a simulated 3D environment and cloud point registration. The idea is to use the resultant transformation matrix as a odometry for our robot. This is feasible. As a seed for the local registration I am using a transformation matrix calculated via kinematics manipulations. In general this transformation is almost perfect. I would like to use the visual odometry to be more robust when the kinemtic odometry cannot be used, for example in case of slippage. 
When I try to use ICP (point to point or point to plane) to refine the seed (kinematic transformation) I have observed that they tend to worsen the transformation. Attached are the examples, in red the ICP with the seed transformation and in blue only the seed. The environment is a staircase and 2 trees on the background. In each image 2 cloudpoints are overlapped, corresponding to 2 pictures, before and after the movement of the robot. The coloured one is the resulting after the registration. As you can see, the output after registration is worse. Any ideas why this is happening?

[registration results.pdf](https://github.com/intel-isl/Open3D/files/3601151/registration.results.pdf)

Thanks you very much in advance.

Enrique

**Comment by syncle** [comment]
1) Try to adjust parameters for ICP - radius search, or K-nearest neighbors. 
2) Check your initial transformation is correct. As a quick check, visualize alignment with the initialization first.

**Comment by Resays** [comment]
and how can we fix or adjust values for initial transformation ?
`trans_init = np.asarray([[0.862, 0.011, -0.507, 0.5],
                             [-0.139, 0.967, -0.215, 0.7],  [0.487, 0.255, 0.835, -1.4], [0.0, 0.0, 0.0, 1.0]])`

and whats the meaning of these values ?
i just copied them from icp example ... dont know how to set them

**Comment by Resays** [comment]
i got this information and no registration happened:

> Initial alignment
registration::RegistrationResult with fitness = 0.000000, inlier_rmse = 0.000000, and correspondence_set size of 0
Access transformation to get result.
Apply point-to-point ICP
registration::RegistrationResult with fitness = 0.000000, inlier_rmse = 0.000000, and correspondence_set size of 0
Access transformation to get result.
Transformation is:
[[ 0.862  0.011  0.507  0.5  ]
 [ 0.139  0.967  0.215  0.7  ]
 [ 0.487  0.255  0.835 -1.4  ]
 [ 0.     0.     0.     1.   ]]


> Apply point-to-plane ICP
registration::RegistrationResult with fitness = 0.000000, inlier_rmse = 0.000000, and correspondence_set size of 0
Access transformation to get result.
Transformation is:
[[ 0.862  0.011  0.507  0.5  ]
 [ 0.139  0.967  0.215  0.7  ]
 [ 0.487  0.255  0.835 -1.4  ]
 [ 0.     0.     0.     1.   ]]

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
