### ISSUE TITLE
Wrong self intersecting triangles in triangle mesh

### ISSUE THREAD

**Issue by ShayGus** [intel-isl/Open3D#1171]
I export a non intersecting triangulated mesh from blender as a ply file.
Then import it into open3d in python (open3d-python ver. 0.7.0) as a TriangleMesh.
Then run a get_self_intersecting_triangles() on this mesh: 

mesh. get_self_intersecting_triangles()

I get many intersecting triangles although, there are no intersections in the ply file we export.

Is there any thing else I should take into consideration?
Any additional info I can provide to find the issue?

**Comment by griegler** [comment]
Can you provide a triangle mesh with the described problem to aid debugging?

**Comment by ShayGus** [comment]
Sure here it is:
[patch_square.ply.zip](https://github.com/intel-isl/Open3D/files/3604046/patch_square.ply.zip)



And here's the text of it:

ply
format ascii 1.0
comment Created by Blender 2.79 (sub 0) - www.blender.org, source file: ''
element vertex 392
property float x
property float y
property float z
element face 670
property list uchar uint vertex_indices
end_header
0.353972 0.040076 1.373050
0.354228 0.043402 1.379656
0.357662 0.042552 1.376781
0.350225 0.037071 1.369384
0.350484 0.040982 1.375864
0.346675 0.038054 1.372114
0.346917 0.041968 1.378729
0.350727 0.044241 1.382615
0.339490 0.044284 1.384593
0.339641 0.047509 1.391732
0.343437 0.046323 1.388634
0.335503 0.041491 1.380698
0.335619 0.045560 1.387630
0.353694 0.036240 1.366655
0.357374 0.039373 1.370215
0.361012 0.041926 1.373882
0.373269 0.013790 1.448147
0.377677 0.004503 1.446140
0.376176 0.014255 1.444252
0.370163 0.013940 1.452037
0.374122 0.003626 1.449932
0.370509 0.003833 1.453747
0.373295 -0.007260 1.450395
0.377916 -0.007588 1.446012
0.343043 0.039137 1.374894
0.343250 0.043110 1.381614
0.339319 0.040303 1.377741
0.347130 0.045242 1.385594
0.344452 -0.036410 1.457586
0.351935 -0.030909 1.456583
0.348562 -0.029913 1.460394
0.355952 -0.023475 1.459091
0.352542 -0.022371 1.462828
0.359435 -0.014710 1.460805
0.355932 -0.013645 1.464452
0.325316 -0.049652 1.456557
0.324887 -0.052462 1.448909
0.329052 -0.050055 1.452450
0.316853 -0.055085 1.441881
0.317050 -0.055322 1.434296
0.320825 -0.055159 1.437769
0.312970 -0.055291 1.438401
0.313401 -0.054697 1.430886
0.317520 -0.054712 1.426881
0.321066 -0.055219 1.430282
0.324718 -0.055055 1.433730
0.336580 -0.046654 1.451590
0.333013 -0.046176 1.455634
0.332667 -0.050314 1.448325
0.328632 -0.052674 1.444798
0.336228 -0.050636 1.444290
0.340057 -0.047127 1.447593
0.303776 -0.048011 1.421496
0.305624 -0.044625 1.414823
0.308114 -0.048269 1.417483
0.306693 -0.051038 1.424424
0.310999 -0.051136 1.420447
0.349265 -0.050906 1.428973
0.355695 -0.048206 1.428671
0.352820 -0.048236 1.432231
0.345717 -0.052455 1.425606
0.352155 -0.050624 1.425490
0.348718 -0.052107 1.422247
0.354919 -0.050235 1.422137
0.336030 -0.054246 1.415766
0.342390 -0.053691 1.415842
0.339140 -0.054168 1.419024
0.336568 -0.053270 1.409493
0.339425 -0.053788 1.412649
0.340060 -0.052710 1.406575
0.342776 -0.053175 1.409664
0.345596 -0.053089 1.412777
0.342072 0.015745 1.357702
0.337464 0.009624 1.360728
0.338608 0.016373 1.360673
0.336808 0.002589 1.361316
0.332593 -0.003365 1.365442
0.333257 0.003581 1.364618
0.328737 -0.008771 1.370200
0.329064 -0.002118 1.368847
0.329590 0.004652 1.367849
0.333935 0.010459 1.363897
0.335033 0.017190 1.363643
0.330217 0.011440 1.366968
0.331297 0.018159 1.366572
0.315112 0.022659 1.378933
0.321299 0.028010 1.376087
0.319311 0.021490 1.375656
0.317125 0.029217 1.379317
0.324168 0.033885 1.377710
0.328194 0.032684 1.374634
0.325360 0.026838 1.372973
0.323402 0.020347 1.372505
0.323546 0.040184 1.383426
0.319995 0.035165 1.380839
0.327506 0.044137 1.386805
0.327659 0.038880 1.380303
0.331567 0.042769 1.383720
0.331624 0.037684 1.377217
0.335495 0.036495 1.374271
0.332099 0.031539 1.371648
0.339270 0.035348 1.371434
0.335922 0.030420 1.368804
0.329335 0.025693 1.370009
0.327386 0.019232 1.369468
0.333189 0.024612 1.367122
0.316396 -0.027908 1.391606
0.319415 -0.023349 1.386236
0.320266 -0.028947 1.388152
0.315563 -0.022239 1.389807
0.318721 -0.017443 1.384359
0.322497 -0.018602 1.380968
0.323152 -0.024446 1.382977
0.324062 -0.029859 1.385119
0.314968 -0.016286 1.388111
0.318236 -0.011328 1.382570
0.314468 -0.010173 1.386369
0.317810 -0.005085 1.380733
0.321526 -0.006269 1.377077
0.321958 -0.012523 1.378997
0.325596 -0.013776 1.375644
0.326131 -0.019793 1.377856
0.325175 -0.007495 1.373576
0.329151 -0.015014 1.372535
0.329649 -0.020883 1.375072
0.326794 -0.025412 1.380163
0.327580 -0.030619 1.382415
0.330190 -0.026290 1.377596
0.330895 -0.031260 1.380001
0.387012 0.027297 1.417939
0.382338 0.032871 1.416901
0.384308 0.028144 1.420833
0.385187 0.032040 1.413930
0.379922 0.036870 1.412692
0.377005 0.037690 1.415782
0.379564 0.033606 1.419973
0.381720 0.028798 1.423855
0.385836 0.022971 1.424395
0.383399 0.023481 1.427257
0.387186 0.017869 1.427711
0.384859 0.018212 1.430237
0.347302 0.050821 1.407295
0.347309 0.049580 1.399931
0.343562 0.050702 1.403173
0.354546 0.049322 1.408179
0.350970 0.049770 1.404029
0.358023 0.048284 1.404961
0.354554 0.048790 1.400826
0.350968 0.048570 1.396747
0.358122 0.047043 1.420080
0.364852 0.043349 1.421155
0.361479 0.046150 1.416746
0.361633 0.044144 1.424533
0.368177 0.039743 1.425607
0.371165 0.039106 1.422241
0.368000 0.042566 1.417846
0.364740 0.045223 1.413469
0.371107 0.041795 1.414620
0.367960 0.044337 1.410270
0.374084 0.038412 1.418956
0.374161 0.040956 1.411462
0.371111 0.043397 1.407126
0.358038 0.047767 1.397698
0.354527 0.047525 1.393648
0.361413 0.047229 1.401811
0.364761 0.046283 1.398719
0.361463 0.046866 1.394621
0.358019 0.046701 1.390575
0.380450 -0.013888 1.442359
0.373821 -0.019303 1.445944
0.376443 -0.022074 1.442103
0.369268 -0.028006 1.444122
0.371911 -0.029572 1.440268
0.364633 -0.034695 1.441406
0.367377 -0.035576 1.437599
0.360395 -0.040144 1.438462
0.363227 -0.040599 1.434725
0.364814 0.045951 1.391603
0.361437 0.045930 1.387556
0.368061 0.045387 1.395681
0.371292 0.044439 1.392684
0.368106 0.045048 1.388631
0.364776 0.045059 1.384611
0.377154 0.039997 1.408354
0.374206 0.042392 1.404035
0.382898 0.036037 1.409689
0.380184 0.039076 1.405317
0.377307 0.041441 1.400998
0.383241 0.038175 1.402319
0.380379 0.040453 1.397982
0.371360 0.044248 1.385683
0.368074 0.044401 1.381672
0.374511 0.043611 1.389716
0.381077 0.023552 1.430369
0.382788 0.017834 1.433188
0.379116 0.029127 1.426991
0.376719 0.029435 1.430450
0.378796 0.023294 1.433764
0.380810 0.016841 1.436593
0.376817 0.034191 1.423162
0.374123 0.034731 1.426519
0.371332 0.035159 1.429967
0.374174 0.029560 1.434017
0.365130 0.040412 1.429057
0.368480 0.035636 1.433520
0.371506 0.029717 1.437686
0.376483 0.022882 1.437444
0.378655 0.015448 1.440338
0.373988 0.022551 1.441263
0.333531 -0.039651 1.384757
0.331966 -0.042885 1.389555
0.330143 -0.039405 1.387048
0.335434 -0.042951 1.387234
0.334047 -0.045768 1.392194
0.330362 -0.045829 1.394793
0.328355 -0.042737 1.392127
0.326621 -0.039038 1.389636
0.334950 -0.050328 1.400516
0.333829 -0.052251 1.406380
0.331229 -0.050666 1.403345
0.337448 -0.051797 1.403510
0.333028 -0.053706 1.412549
0.330146 -0.052639 1.409384
0.327416 -0.050961 1.406311
0.324590 -0.042457 1.394995
0.322839 -0.038574 1.392503
0.326572 -0.045783 1.397622
0.322586 -0.045739 1.400592
0.320588 -0.042162 1.398034
0.318844 -0.038013 1.395638
0.332544 -0.016252 1.369561
0.332916 -0.021896 1.372446
0.332294 -0.010101 1.366981
0.326376 0.012502 1.370051
0.325842 0.005759 1.371113
0.321903 0.006869 1.374332
0.322358 0.013605 1.373117
0.325318 -0.000936 1.372133
0.321577 0.000228 1.375591
0.317677 0.001357 1.379080
0.317863 0.007977 1.377650
0.313996 -0.003933 1.384520
0.313636 0.002465 1.382642
0.313633 0.009072 1.380988
0.318267 0.014722 1.376334
0.314081 0.015853 1.379687
0.336955 0.023592 1.364345
0.339639 0.029379 1.366037
0.343275 0.028422 1.363344
0.340571 0.022720 1.361539
0.342942 0.034286 1.368664
0.346559 0.033256 1.366012
0.346848 0.027572 1.360708
0.350094 0.032369 1.363370
0.365626 -0.005878 1.457889
0.369322 -0.006638 1.454173
0.366937 0.014396 1.455830
0.367013 0.004384 1.457513
0.363548 0.005098 1.461193
0.362060 -0.005018 1.461550
0.380472 0.007238 1.442243
0.381941 -0.000747 1.442447
0.384326 0.004103 1.439222
0.382588 0.010208 1.438531
0.384379 0.012393 1.435312
0.385875 0.007650 1.436234
0.386844 0.009851 1.434126
0.386105 0.013397 1.432671
0.368335 0.022854 1.448962
0.371260 0.022550 1.445121
0.368644 0.030006 1.441379
0.365695 0.030516 1.445123
0.365554 0.036248 1.437151
0.361978 0.041117 1.432559
0.309729 0.017003 1.383096
0.310800 0.023853 1.382334
0.309332 0.010182 1.384499
0.309557 0.003591 1.386403
0.310036 -0.002811 1.388394
0.310619 -0.009050 1.390327
0.311072 -0.015207 1.391988
0.307096 -0.014163 1.396023
0.306588 -0.007977 1.394338
0.307607 -0.020206 1.397561
0.311627 -0.021195 1.393598
0.312344 -0.026957 1.395225
0.308266 -0.026034 1.399094
0.306315 -0.035985 1.406545
0.303599 -0.040262 1.412527
0.302082 -0.035288 1.410622
0.310519 -0.036685 1.402656
0.307900 -0.040797 1.408556
0.312167 -0.041313 1.404783
0.309910 -0.045031 1.410888
0.314710 -0.037373 1.399017
0.316439 -0.041756 1.401304
0.318443 -0.045587 1.403774
0.314183 -0.045362 1.407183
0.323464 -0.051141 1.409499
0.322366 -0.053145 1.416058
0.319385 -0.051242 1.412919
0.326322 -0.052945 1.412602
0.329352 -0.054056 1.415823
0.325529 -0.054355 1.419314
0.315231 -0.051211 1.416593
0.314145 -0.053310 1.423588
0.318301 -0.053259 1.419735
0.321579 -0.054542 1.423019
0.328528 -0.055019 1.429804
0.328446 -0.054210 1.437209
0.335674 -0.054056 1.429423
0.332123 -0.054193 1.433254
0.339266 -0.052867 1.432888
0.335824 -0.052845 1.436749
0.332285 -0.052806 1.440739
0.332216 -0.054858 1.426020
0.339098 -0.053880 1.425766
0.335753 -0.054538 1.422416
0.342356 -0.053533 1.422299
0.342559 -0.052685 1.429152
0.346674 -0.047943 1.439759
0.353500 -0.044321 1.439149
0.350378 -0.043817 1.442941
0.349827 -0.048194 1.435955
0.356461 -0.044587 1.435368
0.357381 -0.039491 1.442217
0.354259 -0.038727 1.445989
0.347224 -0.043304 1.446847
0.343890 -0.042627 1.450715
0.343432 -0.047594 1.443658
0.351090 -0.037982 1.449833
0.347839 -0.037226 1.453716
0.355272 -0.031860 1.452806
0.358480 -0.032734 1.448972
0.362849 -0.025547 1.451695
0.359404 -0.024515 1.455396
0.361630 -0.033710 1.445189
0.366217 -0.026696 1.447966
0.370332 -0.017690 1.449716
0.366642 -0.016665 1.453478
0.362992 -0.015706 1.457155
0.339637 -0.050789 1.440276
0.342970 -0.050950 1.436383
0.346192 -0.051000 1.432608
0.377503 0.042322 1.393804
0.374342 0.043209 1.396793
0.371182 0.044189 1.399817
0.367974 0.045149 1.402879
0.364706 0.046077 1.405993
0.361392 0.047048 1.409168
0.350955 0.050278 1.411465
0.358036 0.048101 1.412415
0.354555 0.049045 1.415719
0.359322 -0.044760 1.431717
0.340497 -0.042027 1.454683
0.328821 -0.054950 1.422639
0.332501 -0.054640 1.419094
0.325000 -0.055145 1.426382
0.364598 0.043685 1.377702
0.361275 0.044350 1.380612
0.357893 0.045086 1.383557
0.354436 0.045892 1.386549
0.347265 0.047738 1.392691
0.350895 0.046774 1.389591
0.343537 0.048789 1.395851
0.345475 -0.053117 1.419037
0.348541 -0.052571 1.415888
0.351636 -0.051627 1.419003
0.324680 -0.054227 1.441267
0.320818 -0.054082 1.445377
0.321077 -0.052227 1.453066
0.312411 -0.048470 1.413621
0.316653 -0.048614 1.409960
0.320805 -0.048728 1.406521
0.324882 -0.048663 1.403369
0.328792 -0.048529 1.400407
0.332571 -0.048365 1.397591
0.336291 -0.048106 1.394943
0.309923 -0.053285 1.427573
0.309240 -0.031551 1.400788
0.313365 -0.032388 1.397018
0.317488 -0.033195 1.393544
0.305117 -0.030716 1.404800
0.304199 -0.025112 1.403198
0.300912 -0.029919 1.408939
0.321448 -0.034014 1.390281
0.325176 -0.034757 1.387291
0.328681 -0.035301 1.384688
0.331965 -0.035775 1.382319
0.334055 -0.031905 1.377751
0.299253 -0.039711 1.416639
0.301279 -0.044205 1.418887
3 0 1 2
3 3 4 0
3 5 6 4
3 4 7 1
3 8 9 10
3 11 12 8
3 13 0 14
3 14 2 15
3 16 17 18
3 19 20 16
3 21 22 20
3 20 23 17
3 24 25 6
3 26 8 25
3 25 10 27
3 6 27 7
3 28 29 30
3 30 31 32
3 32 33 34
3 35 36 37
3 38 39 40
3 41 42 39
3 39 43 44
3 40 44 45
3 37 46 47
3 36 48 37
3 49 50 48
3 48 51 46
3 52 53 54
3 55 54 56
3 57 58 59
3 60 61 57
3 62 63 61
3 64 65 66
3 64 67 68
3 68 69 70
3 68 71 65
3 72 73 74
3 75 76 77
3 76 78 79
3 77 79 80
3 74 81 82
3 73 77 81
3 81 80 83
3 82 83 84
3 85 86 87
3 88 89 86
3 86 90 91
3 87 91 92
3 93 89 94
3 95 96 93
3 97 98 96
3 89 98 90
3 90 99 100
3 11 99 98
3 26 101 99
3 100 101 102
3 92 103 104
3 91 100 103
3 103 102 105
3 104 105 84
3 106 107 108
3 109 110 107
3 107 111 112
3 108 112 113
3 114 115 110
3 116 117 115
3 115 118 119
3 110 119 111
3 111 120 121
3 119 122 120
3 120 78 123
3 121 123 124
3 113 125 126
3 112 121 125
3 125 124 127
3 126 127 128
3 129 130 131
3 132 133 130
3 130 134 135
3 131 135 136
3 137 136 138
3 139 138 140
3 141 142 143
3 141 144 145
3 145 146 147
3 142 147 148
3 149 150 151
3 152 153 150
3 150 154 155
3 151 155 156
3 156 157 158
3 155 159 157
3 157 134 160
3 158 160 161
3 148 162 163
3 147 164 162
3 162 165 166
3 163 166 167
3 168 169 170
3 170 171 172
3 172 173 174
3 174 175 176
3 167 177 178
3 166 179 177
3 177 180 181
3 178 181 182
3 161 183 184
3 160 133 183
3 183 185 186
3 184 186 187
3 187 188 189
3 182 190 191
3 181 192 190
3 140 193 194
3 138 195 193
3 193 196 197
3 194 197 198
3 136 199 195
3 135 159 199
3 199 154 200
3 195 200 196
3 196 201 202
3 200 153 201
3 201 203 204
3 202 204 205
3 198 206 207
3 197 202 206
3 206 205 208
3 207 208 18
3 209 210 211
3 212 213 210
3 210 214 215
3 211 215 216
3 217 218 219
3 220 67 218
3 218 221 222
3 219 222 223
3 216 224 225
3 215 226 224
3 224 227 228
3 225 228 229
3 124 230 231
3 123 232 230
3 84 233 104
3 83 234 233
3 233 235 236
3 104 236 92
3 80 237 234
3 79 122 237
3 237 118 238
3 234 238 235
3 235 239 240
3 238 117 239
3 239 241 242
3 240 242 243
3 92 244 87
3 236 240 244
3 244 243 245
3 87 245 85
3 84 246 82
3 105 247 246
3 246 248 249
3 82 249 74
3 102 250 247
3 24 250 101
3 5 251 250
3 250 248 247
3 251 252 248
3 3 253 251
3 21 254 255
3 21 256 257
3 256 258 257
3 257 259 254
3 18 260 207
3 17 261 260
3 260 262 263
3 207 263 198
3 198 264 194
3 263 265 264
3 264 266 267
3 194 267 140
3 16 268 19
3 18 269 16
3 208 270 269
3 269 271 268
3 205 272 270
3 204 273 272
3 85 274 275
3 245 276 274
3 243 277 276
3 242 278 277
3 241 279 278
3 116 280 279
3 279 281 282
3 280 283 281
3 114 284 280
3 109 285 284
3 284 286 283
3 287 288 289
3 290 291 287
3 292 293 291
3 291 53 288
3 294 292 290
3 229 295 294
3 228 296 295
3 295 297 292
3 298 299 300
3 223 301 298
3 222 302 301
3 301 303 299
3 304 305 56
3 300 306 304
3 299 307 306
3 306 43 305
3 308 309 45
3 308 310 311
3 311 312 313
3 309 313 314
3 315 316 310
3 317 318 316
3 316 60 319
3 310 319 312
3 320 321 322
3 323 324 321
3 321 175 325
3 322 325 326
3 51 327 328
3 329 322 327
3 327 326 330
3 328 330 331
3 331 332 29
3 330 333 332
3 332 334 335
3 29 335 31
3 326 336 333
3 325 173 336
3 336 171 337
3 333 337 334
3 334 338 339
3 337 169 338
3 169 22 338
3 339 22 255
3 31 340 33
3 335 339 340
3 340 255 254
3 33 254 259
3 314 341 50
3 313 342 341
3 341 320 329
3 50 329 51
3 312 343 342
3 319 57 343
3 343 59 323
3 342 323 320
3 180 344 192
3 345 189 344
3 165 346 179
3 347 184 346
3 346 187 345
3 179 345 180
3 146 348 164
3 349 158 348
3 348 161 347
3 164 347 165
3 350 351 144
3 352 151 351
3 351 156 349
3 144 349 146
3 324 176 175
3 59 353 324
3 46 328 354
3 354 331 28
3 302 355 303
3 221 356 302
3 356 66 317
3 356 315 355
3 307 44 43
3 303 357 307
3 355 308 357
3 357 45 44
3 2 358 15
3 359 191 358
3 7 360 1
3 361 178 360
3 360 182 359
3 1 359 2
3 362 27 10
3 362 163 363
3 363 167 361
3 27 361 7
3 142 362 364
3 364 10 9
3 318 62 60
3 66 365 318
3 65 366 365
3 365 367 62
3 36 368 49
3 369 40 368
3 368 45 309
3 49 309 314
3 370 369 36
3 293 54 53
3 297 371 293
3 372 304 371
3 371 56 54
3 296 372 297
3 227 373 296
3 374 298 373
3 373 300 372
3 214 375 226
3 376 219 375
3 375 223 374
3 226 374 227
3 377 217 376
3 213 376 214
3 378 56 305
3 42 305 43
3 285 379 286
3 106 380 285
3 381 294 380
3 380 290 379
3 286 382 383
3 379 287 382
3 382 289 384
3 113 385 108
3 386 225 385
3 385 229 381
3 108 381 106
3 128 387 126
3 388 211 387
3 387 216 386
3 126 386 113
3 389 388 128
3 390 289 288
3 391 288 53
3 0 4 1
3 3 5 4
3 5 24 6
3 4 6 7
3 8 12 9
3 11 97 12
3 13 3 0
3 14 0 2
3 16 20 17
3 19 21 20
3 21 255 22
3 20 22 23
3 24 26 25
3 26 11 8
3 25 8 10
3 6 25 27
3 28 331 29
3 30 29 31
3 32 31 33
3 34 33 259
3 35 370 36
3 38 41 39
3 39 42 43
3 40 39 44
3 37 48 46
3 36 49 48
3 49 314 50
3 48 50 51
3 52 391 53
3 55 52 54
3 57 61 58
3 60 62 61
3 62 367 63
3 64 68 65
3 64 221 67
3 68 67 69
3 68 70 71
3 76 232 78
3 77 76 79
3 74 73 81
3 73 75 77
3 81 77 80
3 82 81 83
3 85 88 86
3 88 94 89
3 86 89 90
3 87 86 91
3 93 96 89
3 95 97 96
3 97 11 98
3 89 96 98
3 90 98 99
3 11 26 99
3 26 24 101
3 100 99 101
3 92 91 103
3 91 90 100
3 103 100 102
3 104 103 105
3 106 109 107
3 109 114 110
3 107 110 111
3 108 107 112
3 114 116 115
3 116 241 117
3 115 117 118
3 110 115 119
3 111 119 120
3 119 118 122
3 120 122 78
3 121 120 123
3 113 112 125
3 112 111 121
3 125 121 124
3 126 125 127
3 129 132 130
3 132 185 133
3 130 133 134
3 131 130 135
3 137 131 136
3 139 137 138
3 141 145 142
3 141 350 144
3 145 144 146
3 142 145 147
3 149 152 150
3 152 203 153
3 150 153 154
3 151 150 155
3 156 155 157
3 155 154 159
3 157 159 134
3 158 157 160
3 148 147 162
3 147 146 164
3 162 164 165
3 163 162 166
3 168 23 169
3 170 169 171
3 172 171 173
3 174 173 175
3 167 166 177
3 166 165 179
3 177 179 180
3 178 177 181
3 161 160 183
3 160 134 133
3 183 133 185
3 184 183 186
3 187 186 188
3 182 181 190
3 181 180 192
3 140 138 193
3 138 136 195
3 193 195 196
3 194 193 197
3 136 135 199
3 135 134 159
3 199 159 154
3 195 199 200
3 196 200 201
3 200 154 153
3 201 153 203
3 202 201 204
3 198 197 206
3 197 196 202
3 206 202 205
3 207 206 208
3 209 212 210
3 210 213 214
3 211 210 215
3 217 220 218
3 220 69 67
3 218 67 221
3 219 218 222
3 216 215 224
3 215 214 226
3 224 226 227
3 225 224 228
3 124 123 230
3 123 78 232
3 84 83 233
3 83 80 234
3 233 234 235
3 104 233 236
3 80 79 237
3 79 78 122
3 237 122 118
3 234 237 238
3 235 238 239
3 238 118 117
3 239 117 241
3 240 239 242
3 92 236 244
3 236 235 240
3 244 240 243
3 87 244 245
3 84 105 246
3 105 102 247
3 246 247 248
3 82 246 249
3 102 101 250
3 24 5 250
3 5 3 251
3 250 251 248
3 251 253 252
3 3 13 253
3 21 257 254
3 21 19 256
3 257 258 259
3 18 17 260
3 17 23 261
3 260 261 262
3 207 260 263
3 198 263 264
3 263 262 265
3 264 265 266
3 194 264 267
3 16 269 268
3 18 208 269
3 208 205 270
3 269 270 271
3 205 204 272
3 204 203 273
3 88 85 275
3 85 245 274
3 245 243 276
3 243 242 277
3 242 241 278
3 278 279 282
3 241 116 279
3 116 114 280
3 279 280 281
3 280 284 283
3 114 109 284
3 109 106 285
3 284 285 286
3 283 286 383
3 287 291 288
3 290 292 291
3 292 297 293
3 291 293 53
3 294 295 292
3 229 228 295
3 228 227 296
3 295 296 297
3 298 301 299
3 223 222 301
3 222 221 302
3 301 302 303
3 304 306 305
3 300 299 306
3 299 303 307
3 306 307 43
3 308 311 309
3 308 315 310
3 311 310 312
3 309 311 313
3 315 317 316
3 317 66 318
3 316 318 60
3 310 316 319
3 320 323 321
3 323 59 324
3 321 324 175
3 322 321 325
3 51 329 327
3 329 320 322
3 327 322 326
3 328 327 330
3 331 330 332
3 330 326 333
3 332 333 334
3 29 332 335
3 326 325 336
3 325 175 173
3 336 173 171
3 333 336 337
3 334 337 338
3 337 171 169
3 169 23 22
3 339 338 22
3 31 335 340
3 335 334 339
3 340 339 255
3 33 340 254
3 314 313 341
3 313 312 342
3 341 342 320
3 50 341 329
3 312 319 343
3 319 60 57
3 343 57 59
3 342 343 323
3 180 345 344
3 345 187 189
3 165 347 346
3 347 161 184
3 346 184 187
3 179 346 345
3 146 349 348
3 349 156 158
3 348 158 161
3 164 348 347
3 350 352 351
3 352 149 151
3 351 151 156
3 144 351 349
3 324 353 176
3 59 58 353
3 47 46 354
3 46 51 328
3 354 328 331
3 302 356 355
3 221 64 356
3 356 64 66
3 356 317 315
3 307 357 44
3 303 355 357
3 355 315 308
3 357 308 45
3 2 359 358
3 359 182 191
3 7 361 360
3 361 167 178
3 360 178 182
3 1 360 359
3 362 363 27
3 362 148 163
3 363 163 167
3 27 363 361
3 143 142 364
3 142 148 362
3 364 362 10
3 318 365 62
3 66 65 365
3 65 71 366
3 365 366 367
3 36 369 368
3 369 38 40
3 368 40 45
3 49 368 309
3 293 371 54
3 297 372 371
3 372 300 304
3 371 304 56
3 296 373 372
3 227 374 373
3 374 223 298
3 373 298 300
3 214 376 375
3 376 217 219
3 375 219 223
3 226 375 374
3 213 377 376
3 378 55 56
3 42 378 305
3 285 380 379
3 106 381 380
3 381 229 294
3 380 294 290
3 383 382 384
3 286 379 382
3 379 290 287
3 382 287 289
3 113 386 385
3 386 216 225
3 385 225 229
3 108 385 381
3 128 388 387
3 388 209 211
3 387 211 216
3 126 387 386
3 391 390 288

**Comment by ShayGus** [comment]
After doing some testing.
Was was fixed is the overall detection of the intersection, but when there are intersections the intersecting triangles returned are wrong.
For example for a mesh of 26306 triangles with a very small area of intersection we get a vector of 137714 intersections.
