### ISSUE TITLE
cannot use 'create_rgbd_image_from_color_and_depth' 'create_point_cloud_from_rgbd_image' after version update

### ISSUE THREAD

**Issue by kaixin-bai** [intel-isl/Open3D#1176]
code is below, after i update open3d to version 0.8.0.0, i got error like this:
```
rgbd = o3d.geometry.create_rgbd_image_from_color_and_depth(img, depth)
AttributeError: module 'open3d.open3d.geometry' has no attribute 'create_rgbd_image_from_color_and_depth'
```
```
image = np.array(img.copy())
H, W, _ = image.shape
fx, fy, cx, cy = get_intrinsic()
intrinsic = o3d.camera.PinholeCameraIntrinsic(W,H,fx,fy,cx,cy)
img = o3d.geometry.Image(image.astype(np.uint8))
depth = np.asarray(depth).astype(np.float32) / cam_scale
depth = o3d.geometry.Image(depth)
rgbd = o3d.geometry.create_rgbd_image_from_color_and_depth(img, depth)
pcd = o3d.geometry.create_point_cloud_from_rgbd_image(rgbd, intrinsic)
```
Could someone tell me how to fix it?
Thanks a lot!

**Comment by griegler** [comment]
The API changed in `0.8`.
The last two lines should be something like

```
rgbd = o3d.geometry.RGBDImage.create_from_color_and_depth(img, depth)
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd, intrinsic)
```

**Comment by rtuchman** [comment]
Hi @griegler , what are the required types and shapes of img, depth?

Thanks

**Comment by griegler** [comment]
@rtuchman `img` and `depth` should have the same `height` and `width`. `img` can have one, or three channels, `depth` should have a single channel. `img` can be `uint8`, or `float`. `depth` should be `float`.

**Comment by sharoseali** [comment]
> The API changed in `0.8`. The last two lines should be something like
> 
> ```
> rgbd = o3d.geometry.RGBDImage.create_from_color_and_depth(img, depth)
> pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd, intrinsic)
> ```

Thanks, @griegler  the resultant point cloud isn't well-drawn well and point cloud colours are also in grayscale not RGB. Any idea how to plot PFM correctly with the colour point cloud. THanks
