### ISSUE TITLE
Store the point indices that belong to a leaf/internal node in Octree

### ISSUE THREAD

**Issue by wfchen-umich** [intel-isl/Open3D#1178]
**Is your feature request related to a problem? Please describe.**

Would it be possible to store the point indices that belong to a leaf/internal node in Octree? Thank you very much.

**Describe the solution you'd like**
Could you either store the info as a field of OctreeNodeInfo or as a field of OctreeInternalNode?

**Describe alternatives you've considered**
I have gone through the python and cpp code and didn't see it store the indices any where.

**Additional context**

**Comment by syncle** [comment]
@griegler Could you help?

**Comment by griegler** [comment]
I think out of the box this is not supported at the moment. If we did set up the pybind11 bindings properly then you should be able to implement you own sub-class of `OctreeLeafNode` in Python that supports it ([reference](https://pybind11.readthedocs.io/en/master/advanced/classes.html#overriding-virtual-functions-in-python)). Another workaround for now would be to store the indices in the color values of `OctreeColorLeafNode`. 
Maybe @yxlao has another idea.

**Comment by farmakis** [comment]
Is there any update on that issue? Could the points be stored within an OctreeLeafNode by using the Octree.insert_point function?
For now using the 10.0.0 version of Open3D it seems like the Octree.locate_leaf_node function only returns OctreeColorLeafNode and not OctreeLeafNode which is required by the Octree.insert_point function. Could anyone help on this?
Thanks

**Comment by germanros1987** [comment]
@yxlao @theNded your input here would be really useful. Could you give your opinion, please?

**Comment by plusk01** [comment]
I like @griegler 's comment about custom `OctreeLeafNode` subclasses, though is seems the `ConvertFromPointCloud` interface would need to be overloaded/templated to allow specification of the custom init and update functions.

In addition to leaf nodes maintaining point indices, I would also like to see `OctreeInternalNode` be able to return a list of all point indices from the union of its children's point indices. This would be useful information when traversing with `Traverse`.
