### ISSUE TITLE
How to get colors in 3D with RGB and Depth image

### ISSUE THREAD

**Issue by Resays** [intel-isl/Open3D#1181]
I'm trying to create 3D from images (rgb + depth). i'm using RealSense D415
creating 3D is successful, but there is no RGB colors in 3D model. Its actually a black and white model.
im using this code:

```
from open3d import *
import matplotlib.pyplot as plt

if __name__ == "__main__":
    color_raw = read_image("0000108.jpg")
    depth_raw = read_image("0000108.png")
    rgbd_image = create_rgbd_image_from_color_and_depth(color_raw, depth_raw)
    intrinsic = read_pinhole_camera_intrinsic("camera_intrinsic.json")

    pcd = create_point_cloud_from_rgbd_image( rgbd_image, intrinsic )
    draw_geometries([pcd], window_name='Visualizer Window', width=1024, height=768)
```
Camera is RealSense D415, intrinsic i am using are:
`{
    "width" : 640,
	"height" : 480,
	"intrinsic_matrix" :
	[
		625.637,
		0,
		0,
		0,
		625.637,
		0,
		319.944,
		241.388,
		1
	]
}
`

![image](https://user-images.githubusercontent.com/50095407/65105001-66c38e00-da0e-11e9-8237-83411724a720.png)

![local](https://user-images.githubusercontent.com/50095407/64933938-7d3cde80-d882-11e9-9ee0-cfcfcc9dabdc.jpg)

Why i can't see the colors as i can see on RGB image ?

**Comment by griegler** [comment]
Could you post the output of `print(np.asarray(rgbd_image.color))`? I guess that this contains values in the range `[0, 255]`, but the `PointCloud` (and the `Visualizer`) expects colors in the range of `[0,1]`.

**Comment by Resays** [comment]
Here are the values: for rgbd_image.color
`[[0.43083134 0.43475297 0.43475297 ... 0.4779569  0.47011372 0.46619216]
 [0.42298824 0.4269098  0.43083134 ... 0.47403532 0.47011372 0.46619216]
 [0.43660784 0.43660784 0.4405294  ... 0.4779569  0.47403532 0.47011372]
 ...
 [0.1643843  0.13301176 0.10163921 ... 0.01054902 0.01447059 0.01952157]
 [0.10163921 0.08987451 0.08595294 ... 0.01285098 0.0156     0.01952157]
 [0.10560392 0.08599608 0.07423138 ... 0.01285098 0.0156     0.01952157]]`

**Comment by griegler** [comment]
According to the output above (`Color image : 640 x 480, with 1 channels`) you have an image with just one channel, hence the point cloud only has gray values. I guess you will also only see a grayscale image if you do `draw_geometries([color_raw])`, or `plt.imshow(np.asarray(color_raw))`.

**Comment by Resays** [comment]
when i use this code, its showing me 3 channels with the same image

`image = cv2.imread('RGBD/00000.jpg')
print( image.shape )`

> Output: (480, 640, 3)

How can i use all three channels to draw the 3D from color and depth image with RGB colors ?

**Comment by Resays** [comment]
`plt.imshow(np.asarray(color_raw))` gave me RGB image
![image](https://user-images.githubusercontent.com/50095407/65216108-d8710a00-daea-11e9-8e31-34ce55f3c777.png)

**Comment by Resays** [comment]
@griegler  .. any suggestion?

**Comment by griegler** [comment]
Ok, the problem is in `create_rgbd_image_from_color_and_depth`. This function has a parameter `convert_rgb_to_intensity` which is default set to `True`. If you set it to `False`, it should work.

**Comment by Resays** [comment]
`rgbd_image = create_rgbd_image_from_color_and_depth(color_raw, depth_raw, False)`
no view for 3D ... am i doing it correctly ?

**Comment by griegler** [comment]
Your are now setting `depth_scale` to `False`, [see here](http://www.open3d.org/docs/release/python_api/open3d.geometry.RGBDImage.html#open3d.geometry.RGBDImage.create_from_color_and_depth). You should write  `create_rgbd_image_from_color_and_depth(color_raw, depth_raw, convert_rgb_to_intensity=False)`.

**Comment by Resays** [comment]
Yeah, Thanks a lot ... now I can have colors in 3D view.

**Comment by Resays** [comment]
![image](https://user-images.githubusercontent.com/50095407/65253142-1a26a280-db35-11e9-9d39-236c4e47a02f.png)

**Comment by Resays** [comment]
one more question ... 3D view is not perfect like images ... why is that so?
is there any solution to have a more accurate view like RGB images?

**Comment by Resays** [comment]
Another question ... I want to crop only cup and clock from 3D view as a separate object, 
how can I crop them using code, don't wanna use open3D cropping example with mouse clicks
I want to grab the 3D objects using python code.
any solution?

**Comment by anil-bit** [comment]
@Resays how did you find the intrinsic metrics for both the camera

**Comment by Akash-Kumbar** [comment]
> Ok, the problem is in `create_rgbd_image_from_color_and_depth`. This function has a parameter `convert_rgb_to_intensity` which is default set to `True`. If you set it to `False`, it should work.

I think this should be mentioned in the documentation
