### ISSUE TITLE
How do we create the log file from the data obtained from the tracking camera for the purpose of rgbd integration?

### ISSUE THREAD

**Issue by TonduriGopinath7** [intel-isl/Open3D#1182]
Dear Open3D users.

Please **search and see relevant questions/discussions** before adding a new issue in this place.

If the question is related to some **application** (I have this depth images, how can I do ...) or a **quick question** (how to use Open3D how can I access a point from a point cloud ...), we strongly recommend to visit [Open3D's chatting room](https://discord.gg/D35BGvn). Please remember this Github issue board is mostly dedicated to Bug report and Feature request.

**Comment by yxlao** [comment]
Could you be more specific about "log file from the data obtained from the tracking camera"
- what data do you want to store
- where is the data coming form

**Comment by TonduriGopinath7** [comment]
I need to create a odometry.log for rgbd integration .(**https://github.com/intel-isl/Open3D/blob/master/examples/Python/Advanced/rgbd_integration.py**)
My data is coming from T265 camera which gives us rotation in terms of quaternions and translation data

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
