### ISSUE TITLE
how to get intrinsic parameters of Azure Kinect with Open3D?

### ISSUE THREAD

**Issue by kaixin-bai** [intel-isl/Open3D#1183]
how to get intrinsic parameters of Azure Kinect with python script?

Thanks a lot!

**Comment by theNded** [comment]
You can use `azure_kinect_mkv_reader.py` reader to decode a recorded mkv (either from the official recorder or our recorder). It will write the intrinsics to a json file `intrinsic.json`

See this line:
https://github.com/intel-isl/Open3D/blob/master/examples/Python/ReconstructionSystem/sensors/azure_kinect_mkv_reader.py#L54
