### ISSUE TITLE
Wrong self intersecting triangle mesh

### ISSUE THREAD

**Issue by ShayGus** [intel-isl/Open3D#1185]
Related Bug: #1171 

After doing some testing on the merged fix.
What was fixed is the overall detection of the intersection (is_intersecting), but when there are intersections the intersecting triangles returned are wrong.
For example for a mesh of 26306 triangles with a very small area of intersection we get a vector of 137714 intersections.

Mesh attached:
[hand.zip](https://github.com/intel-isl/Open3D/files/3617053/hand.zip)

**Comment by griegler** [comment]
I think that might be a problem with this particular mesh. It seems that this is a triangle soup, not a triangle mesh, i.e. no face is connected with another face. But they are still touching on the boundaries, hence you get all the intersections. You can compare also with the result from e.g., MeshLab.

**Comment by ShayGus** [comment]
I see thanks for the input.
Can you tell when this patch will be pushed to pip? And whether we can use it wit a GPU?

**Comment by griegler** [comment]
The patch will be included in the next release, which I think will only be in two months or so. There are ongoing works for GPU support, but I can not give an estimate now when this exact feature will have full support.

**Comment by ShayGus** [comment]
Thanks

**Comment by xleEmesent** [comment]
@griegler , Hi, it looks like there are some issues in is_self_intersecting() python api for some testing dataset. It does not return anything. I ran the "is_edge_manifold" and "is_vertex_manifold()", both methods are running fine. The issues is in is_self_intersecting(). Can you have a look at this method? Thanks.
