### ISSUE TITLE
Pointcloud visualization with nan values

### ISSUE THREAD

**Issue by victorjoos** [intel-isl/Open3D#1188]
**Describe the bug**
Trying to visualize a pointcloud containing NaN values (with no additional geometries) doesn't show anything. When removing the NaN values or adding other geometries (e.g. a LineSet), there's no problems.

**To Reproduce**
Code to reproduce the behavior:
```python
import open3d
import numpy as np
points = np.array([[1,0,0],[0,1,0],[0,0,1], [np.nan, np.nan, np.nan]])
opcd = open3d.geometry.PointCloud()
opcd.points = open3d.utility.Vector3dVector(points)
open3d.visualization.draw_geometries([opcd])
```

**Expected behavior**
Three points in space. Instead the canvas is completely blank, and even trying to move around doesn't show anything.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 
 - Open3D version: 0.8.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Comment by syncle** [comment]
The geometry is not defined with nan values. The visualizer assumes the coordinate is finite. @victorjoos do you have a common use case for this? How about filtering such nan values before using visualizer instead of expecting visualizer softly ignores them?

**Comment by SebastianGrans** [comment]
I too have this issue. Getting a warning rather than nothing would have been appreciated. 

I am using a commercial structured light 3D scanner which returns a 1200x1920x3   array (I.e. xyz values for each pixel coordinate). Hence it makes sense to have in the array.

**Comment by awied1404** [comment]
I had the same issue. I agree with @SebastianGrans that a warning would be nice to have instead of just showing nothing as I spent some time until I figured out that my point cloud captured with a structured light 3D scanner has lots of NaN values.
