### ISSUE TITLE
Reading velodyne PCAP-File

### ISSUE THREAD

**Issue by ArashJavan** [intel-isl/Open3D#1196]
**Is your feature request related to a problem? Please describe.**
I would like to know if it is possible to read pcap-files recorded with velodyne.
Unfortunately i could not find a way to read these files using any pytohn cloud-lib :(,
- except ROS.

**Comment by syncle** [comment]
It seems not that easy. Could you try https://github.com/UnaNancyOwen/VelodyneCapture and save point cloud as pcd or ply files to play with Open3D?

**Comment by ArashJavan** [comment]
@syncle Thanks for your reply. Well at least I implemented a tiny pure python application which does that.
https://github.com/ArashJavan/veloparser

**Comment by syncle** [comment]
Thanks for the pointer @ArashJavan! Closing for now.
