### ISSUE TITLE
Change of Visualization Parameters between versions? 

### ISSUE THREAD

**Issue by RapIt** [intel-isl/Open3D#1197]
I did a version update from 0.7 to 0.8 today. I did absolutely no other changes than adjusting the API calls which changed between the versions, but my visualization broke anyway:

left: 0.7 / right: 0.8
![issue](https://user-images.githubusercontent.com/844913/65345210-041eed80-dbda-11e9-9fd5-5022a84a9938.png)

- the color map changed
- the zoom-limit in the newer version is lower so that I cannot zoom far enough.
- the point cloud is smaller because the z-translation value in the extrinsic matrix changed (except of this single value both intrinsic, extrinsic and other ViewControl parameters are exactly the same. PCL values are also the same. ) 

The old version is way better, but I would like to use some of the new features. A hint into the right direction in the changelog / code would be great. I have no clue what to change in order to restore the old behavior. I only use default parameters so far and add my geometries (PCLs and MeshSpheres) with `add_geometry`.

Thanks!

EDIT
I made some further observations: The ViewTrajectory is 
```
"boundingbox_max" : [ 0.97073449050827609, 0.76746450924137721, 0.0 ],
"boundingbox_min" : [ -1.1379995291273886, -0.7524822081574073, -2.4096000194549561 ],
"field_of_view" : 59.999999999999993,
"front" : [ 0.0, 0.0, 1.0 ],
"lookat" : [ -0.08363251930955623, 0.0074911505419849589, -1.204800009727478 ],
"up" : [ 0.0, 1.0, 0.0 ],
"zoom" : 0.40847723131794877
```
,but when I manually print the bbox values before adding the pcl to the renderer its max values are `[0.97073449  0.76746451 -1.1128]`, so the z value is falsely set to 0.0. That causes the lookat to be calculated wrong, too and the colormap is applied to a "wrong" range. That does not happen in the 0.7 version, the max bbox values are correct there. How can I fix that?

EDIT 2

I fixed it for me by building from source after setting the z value of max_bound_ in https://github.com/intel-isl/Open3D/blob/80915c28353286868849f8b6fcd122bd0e62b826/src/Open3D/Geometry/BoundingVolume.h#L94 to a negative limit. The issue is caused by the combination of bounding boxes when adding 3d geometries, see https://github.com/intel-isl/Open3D/blob/80915c28353286868849f8b6fcd122bd0e62b826/src/Open3D/Geometry/BoundingVolume.h#L118. Since the z axis is negative, the initial value of 0.0 is always greater, so the BoundingVolume is not calculated correctly.

**Comment by gdo-contilio** [comment]
Ditto. Updated to 0.8, previously calling draw_geometries() would display a zoomed-in view of point clouds, regardless of there points where (useful for quick viewing results). 
Now point clouds are far away from the center and in a zoomed out view which is not optimal. 
There is no documentation of the changes either.

Any ideas how to revert back to the older viewing functionality?
Thanks!

**Comment by RapIt** [comment]
See my EDIT 2 for a fix, which worked for me. It probably solves the issue, but I am not familiar enough with the code and potential side effects to make a PR. Maybe @griegler can comment, he implemented the new bounding volume features.

**Comment by griegler** [comment]
Thanks for pointing this out, I will need to look a bit deeper into this.

**Comment by griegler** [comment]
@RapIt can you share the geometry/code to reproduce the visualization in your first post?

**Comment by griegler** [comment]
@RapIt maybe you can test #1205 if it fixes your problem?

**Comment by RapIt** [comment]
I just tested the fix, it works perfectly now. No need for example code then? Thank you for the fast response, I will close this issue.

**Comment by griegler** [comment]
Great! No need for the data/code then.
