### ISSUE TITLE
Finding the difference between two point clouds

### ISSUE THREAD

**Issue by lexer21** [intel-isl/Open3D#1199]
Dear Open3D users.

Lets say I have point cloud P1 of some fixed object O1. Then I add another object (which can be anything) O2 in real life to the O1 and make another point cloud P2. How would I go about finding the differences between point clouds P1 and P2 so I can extract out the point cloud of object O2?

So far I have aligned the two point clouds via the global_registration.py script and tried to find the difference via a naive method by calculating differences but it just takes to long. 

Note: Because the way our system is set up I cannot get the point cloud of object O2 directly.

**Comment by syncle** [comment]
How about voxelize the two point clouds, and find the differences in the voxel domain?

**Comment by syncle** [comment]
Closing for now due to inactivity. @lexer21 Please reopen this issue if necessary.

**Comment by 1939938853** [comment]
Hello,

I think that to find the difference between two point clouds can be one of the important segmentation steps -- some thing like the morphological operation in 2D image processing.

I saw that it is possible to do the "add" operation with both pcd and voxel. But both have no "subtraction" operation. 

Can you give a hint how to go the subtraction ether in pcd or in voxel or in octrees?  

I saw someone points out to detect the two point clouds difference: point-wise calculate the nearest neighbor point distance as in Matlab or comparing the octrees difference in PCL.

What can be the solution in Open3D?

Thank you!
