### ISSUE TITLE
Add PyQt or NanoGui support for visualization function

### ISSUE THREAD

**Issue by xufangda** [intel-isl/Open3D#1200]
**Is your feature request related to a problem? Please describe.**
I need to interactively illustrate and control the pointcloud data, with gui element. Could you please give a simple demo or document on how to add open3d visualizer into pyqt or nanogui???

**Describe the solution you'd like**
As suggested by @syncle in [issue342](https://github.com/intel-isl/Open3D/issues/342), nanogui can provide the ability to integrate open3d visualizer, but how???

We don't even know what object is open3d visualizer, how to invoke it in nanogui...

Is that possible to make a demo for nanogui or PyQt? It is very important to provide a gui interface to build up large project!

**Comment by syncle** [comment]
We are actually working on this. Please try [this working branch](https://github.com/intel-isl/Open3D/tree/gui).

**Comment by 1939938853** [comment]
I'm also looking for Open3D GUI solution. But which file in this branch can show it?

Thank you!

**Comment by germanros1987** [comment]
0.10 just integrates IMGUI and provides new GUI classes. This should be good enough to close this issue.

**Comment by mastrogiorgis** [comment]
Hi @germanros1987 
I know this is a closed issue, but it would be very useful to have PyQt5 integration so then is easier to use menus and guis from QT.

**Comment by JianqiangDing** [comment]
> 0.10 just integrates IMGUI and provides new GUI classes. This should be good enough to close this issue.

Hi, the changelog of release 0.10 mentioned that IMGUI has already integrated into, but  it seems that 0.10 does not provide python binding for IMGUI, or did i miss something? is it just for C++ so far?
