### ISSUE TITLE
Add read_from_nparray_function to create pointcloud

### ISSUE THREAD

**Issue by xufangda** [intel-isl/Open3D#1201]
I have to apply a customized filter based on norms. I get points and norms from the PointCloud np.asarray function. After I filtered out pointcloud, I found there is no way to regenerate PointCloud from np.array....

This is very important to me....

**Comment by griegler** [comment]
http://www.open3d.org/docs/release/python_api/open3d.utility.Vector3dVector.html#open3d.utility.Vector3dVector
