### ISSUE TITLE
how to get surface normal map from depth image?

### ISSUE THREAD

**Issue by kaixin-bai** [intel-isl/Open3D#1204]
i have color image, depth image, camera intrinsic. Is it possible to generate a surface normal image from depth image with Open3D? Thanks a lot!

**Comment by kaixin-bai** [comment]
for example, i have i color image like this: 
![Screenshot from 2019-09-26 15-41-11](https://user-images.githubusercontent.com/38804949/65693135-17b3d380-e074-11e9-9abd-1ca9f84b8dda.png)
with depth image and camera intrinsic i got the normal of the generated point cloud.
![Screenshot from 2019-09-26 15-42-08](https://user-images.githubusercontent.com/38804949/65693243-46ca4500-e074-11e9-90e1-a5bdf509a04e.png)
and what i got with vis.capture_screen_float_buffer() is not what i want.
![Screenshot from 2019-09-26 15-43-43](https://user-images.githubusercontent.com/38804949/65693418-8b55e080-e074-11e9-9cff-984622f5def1.png)

How can i get a new normal colored image? thanks a lot!

**Comment by kaixin-bai** [comment]
Problem solved

**Comment by StefanZt** [comment]
Can you please tell me how to solve it? i rendered rgb image and depth image from an obj, now i want to render a vertex normal image at the same time, but i can't find a way to do it.
