### ISSUE TITLE
Maybe-uninitialized tetramesh.cpp

### ISSUE THREAD

**Issue by RickPoppe** [intel-isl/Open3D#1206]
While installing Open3D I get the following error message about the tetramesh.cpp file

![image](https://user-images.githubusercontent.com/55833726/65676992-19b86b00-e051-11e9-803c-206ae5f11e72.png)

I try to build Open3D 0.8.0 from source on Ubuntu 16.04 with python 3.6.3
I can get around this problem by removing -Werror in the CMakeLists.txt, but this is of course only a temporary solution. So does anyone know how to fix this issue.

**Comment by griegler** [comment]
@benjaminum Can it happen that `order` is uninitialized here?
https://github.com/intel-isl/Open3D/blob/91d393921206497fd1e35d93345b13755ff93a63/src/Open3D/Geometry/TetraMesh.cpp#L309-L319

**Comment by RickPoppe** [comment]
The code is the same as the one you show. However it could be that order does not have values, when all the if statements are skipped.

**Comment by benjaminum** [comment]
It should never happen that all branches are skipped if the tetrahedron is sane.
I will check if it is better to remove the last "else if" or to add an else branch.

**Comment by griegler** [comment]
Fixed in #1212
