### ISSUE TITLE
How to use open3d.geometry.OrientedBoundingBox as crop volum to crop point cloud?

### ISSUE THREAD

**Issue by nan0755** [intel-isl/Open3D#1210]
`open3d.geometry.OrientedBoundingBox` can specify the center, but I want to know how to set the 3D bounding box's width, height, length and, roll, pitch, yaw?
In addition, the `crop_point_cloud` func  in Open3D can only use `min_bound` and `max_bound` to crop. Is there a direct API for `OrientedBoundingBox` cropping?

I have checked  [#852](https://github.com/intel-isl/Open3D/issues/852) and found no solution.

**Comment by griegler** [comment]
Both functionalities are not implemented yet, but would be nice to have.
As a workaround you can rotate and scale the `x_axis`, `z_axis` and `y_axis` of the `OrientedBoundingBox` in Python. Similarly, you can use the inverse rotation on the PointCloud and crop it with an `min_bound, max_bound`.

**Comment by nan0755** [comment]
I have found the C++ API of this, but  when dould python API come out?
I think these funcs above are very useful in 3D perception projects.

**Comment by nan0755** [comment]
I can use PCL to do this.
But the reason why I use open3d is that it's familiar with python, so I suggest Open3D maintainer to implement more func in python, otherwise Open3D cannot defeat PCL by using C++.

Thanks.

**Comment by griegler** [comment]
Added in #1218.
