### ISSUE TITLE
View point not captured while reading pcd files

### ISSUE THREAD

**Issue by RachitB11** [intel-isl/Open3D#1213]
When I simply read and write the pcd file as shown below, I saw that the viewpoint in the pcd was getting reset to identity. Shouldn't the IO be retaining the viewpoint as well?
```
    pcd = o3d.io.read_point_cloud(input_file)
    o3d.io.write_point_cloud(output_file, pcd)
```
input.pcd
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb normal_x normal_y normal_z intensity weight curvature
SIZE 4 4 4 4 4 4 4 4 4 4
TYPE F F F F F F F F F F
COUNT 1 1 1 1 1 1 1 1 1 1
WIDTH 1567485
HEIGHT 1
VIEWPOINT -55.6948 -43.715 -35.9986 1 0 0 0
POINTS 1567485
```
output.pcd
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z normal_x normal_y normal_z rgb
SIZE 4 4 4 4 4 4 4
TYPE F F F F F F F
COUNT 1 1 1 1 1 1 1
WIDTH 1476089
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1476089
```

There is also a reduction in the number of points and some fields get removed. Is there a way to retain the exact same pcd?

**Comment by griegler** [comment]
Right now there is not view-point associated with the geometry classes, i.e., 'PointCloud'. Therefore, `write_point_cloud` can also not store it to the `pcd` file. @yxlao maybe that is something that we can then store in the additional data of the new geometry classes, but at the moment I think this is out of scope of this library.
