### ISSUE TITLE
How can I use open3d to import two "like-to-like" point cloud using an existing 4 x 4 matrix in Jupyter? New to Python and working on a project, please

### ISSUE THREAD

**Issue by Mitch-PyOpen** [intel-isl/Open3D#1214]

**Comment by syncle** [comment]
Could you specify the question bit more?

**Comment by Mitch-PyOpen** [comment]
Thanks so much, Syncle. I have two sets of point cloud and I want to open both with the same 4 x 4 
transformation matrix. How can I use open3d to import these two in Jupyter, please? 

import numpy as np
import matplotlib.pyplot as pp
import open3d as o3d

pcd = o3d.io.read_point_cloud("Local Disk (D:)/Point Clouds.xyz")

xyz = np.array([[ 0.82,  -0.082,  -0.55,  15],
       [ 0.13,  0.98,  0.06, -56.1],
       [ 0.54, -0.12, 0.82, -157.4],
       [0.0, 0.0, 0.0, 1.0]])

print('xyz')

pcd = o3d.geometry.PointCloud()

o3d.io.write_point_cloud("Local Disk (D:)/Point Clouds.xyz", pcd)

This is what I have written but it is not importing? I am sure I am missing something

Many thanks.

**Comment by syncle** [comment]
Check out [our documentation page](http://www.open3d.org/docs). 
[this for point cloud transform](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.transform) and [Jupyter notebook visualization](http://www.open3d.org/docs/release/tutorial/Basic/jupyter.html).

**Comment by Mitch-PyOpen** [comment]
Thanks so much for this. I will try this now and get back.
