### ISSUE TITLE
Pass more than colors, normals and points when subsampling pointcloud

### ISSUE THREAD

**Issue by lelouedec** [intel-isl/Open3D#1215]
Good morning,

I am working with point clouds and deep learning and for each point wish to keep the associated annotation (class) when subsampling. The "hack" I am using right now is for a binary classification where I store the class in normals and know of to differenciate the classes based on the normal value once subsampled. However, it doesn't work with multiple classes. 
It would be nice to have a way to keep these values maybe by passing  a rule to choose which class to keep when downsampled.

**Comment by griegler** [comment]
At the moment it is not possible without workarounds. We are currently working on refactoring the code, cf. GPU support and this will enable to append arbitrary data with the geometry data structures.
