### ISSUE TITLE
 the "o3d.geometry.PointCloud.create_from_depth_image" function's param "depth_scale" not work?

### ISSUE THREAD

**Issue by luwc1009** [intel-isl/Open3D#1225]
i use this function to trans a depth image to pointclouds, and i set the depth_scale= 1000,but i got the pointcloud whose scale is mm not m,and i change the depth_scale = 10000,i got the same out put ,what's wrong?

my open3d version is 0.8.0.0,python version is 2.7

here are some of my code :
`        source_depth_image = o3d.geometry.Image(self.depth_image_array[source_id])`
`       source_pcd = o3d.geometry.PointCloud.create_from_depth_image(source_depth_image, self.intrinsic,depth_scale=1000.0, depth_trunc=1000.0, stride=1)`
i got the mean of source_pcd by:
`print np.asarray(source_pcd.points).mean(axis=0) `
the output is :
`array([-15.03491085, 124.80328023, 694.21251241])`
it seems like that its scale is still mm。i am confused

**Comment by syncle** [comment]
I cannot reproduce the issue (using open3d 0.9)


### input (with depth_scale=1000)
```
import open3d as o3d
import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":
    print("Read Redwood dataset")
    depth_raw = o3d.io.read_image("../../TestData/RGBD/depth/00000.png")
    pcd = o3d.geometry.PointCloud.create_from_depth_image(depth_raw, 
            o3d.camera.PinholeCameraIntrinsic(
            o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)
            ,
            np.identity(4),
            depth_scale=1000.0, depth_trunc=1000.0)
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
    print(np.asarray(pcd.points)[1,:])
    o3d.visualization.draw_geometries([pcd])
```
output
```
[-0.36311428  0.77907617 -1.78999996]
```

### input (with depth_scale=10000)
```
import open3d as o3d
import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":
    print("Read Redwood dataset")
    depth_raw = o3d.io.read_image("../../TestData/RGBD/depth/00000.png")
    pcd = o3d.geometry.PointCloud.create_from_depth_image(depth_raw, 
            o3d.camera.PinholeCameraIntrinsic(
            o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)
            ,
            np.identity(4),
            depth_scale=10000.0, depth_trunc=10000.0)
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
    print(np.asarray(pcd.points)[1,:])
    o3d.visualization.draw_geometries([pcd])
```
output
```
[-0.03631143  0.07790762 -0.17900001]
```

Please use [one of the template](https://github.com/intel-isl/Open3D/issues/new/choose) for the question.

**Comment by luwc1009** [comment]
thanks for your reply, i will upgrade my open3d, and have a try. and sorry for not use the template,i will revise it

**Comment by spacewalk01** [comment]
Getting following error when running above code:

`RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::geometry::PointCloud> __cdecl open3d::geometry::PointCloud::CreateFromDepthImage(const class open3d::geometry::Image &,const class open3d::camera::PinholeCameraIntrinsic &,const class Eigen::Matrix<double,4,4,0,4,4> &,double,double,int,bool)) D:\a\Open3D\Open3D\cpp\open3d\geometry\PointCloudFactory.cpp:151: Unsupported image format.`
