### ISSUE TITLE
"Read PNG failed: unable to parse header" error.

### ISSUE THREAD

**Issue by GustavoCamargoRL** [intel-isl/Open3D#1229]
Hi, i'm trying to read a depth map image to use that to make a point cloud of it, but i'm getting the following message from the terminal "[Open3D WARNING] Read PNG failed: unable to parse header. "

Here is the following code:

        std::string filename = "room.png";
	    open3d::camera::PinholeCameraIntrinsic instrinsic;
	    instrinsic.SetIntrinsics(960, 480, 564.3, 564.3, 540, 270);
        open3d::geometry::Image depth;
	    open3d::io::ReadImage(filename, depth);

and that's the following PNG image, with uint16 data.
![room](https://user-images.githubusercontent.com/45178010/66504355-5481c080-ea9f-11e9-871e-2b7f4a131357.png)

**Comment by syncle** [comment]
I cannot reproduce error. Could you specify your environment? 
```
>>> import open3d as o3d
>>> o3d.io.read_image("/Users/jaesik/Downloads/github.png")
Image of size 480x272, with 1 channels.
```
Please use one of [the issue template](https://github.com/intel-isl/Open3D/issues/new/choose) to report an issue.

**Comment by griegler** [comment]
@syncle just a guess, but are we only parsing/loading `uint8` data? The image above is `uint16`.

**Comment by GustavoCamargoRL** [comment]
I'm running this at windows 10, with c++ in visual studio 2017.
As i'm trying to make a point cloud out of that image, the rest of the code is this:
 
        open3d::geometry::PointCloud pointCloud;
	    pointCloud.CreateFromDepthImage(depth, instrinsic, extrinsic);

and in the pointCloud.h file in line 212, you have a specification of the image format :
 "/// The input depth image can be either a float image, or a uint16_t image." 
so that's why i'm trying to load a uint16 image with "open3d::io::ReadImage"

**Comment by theNded** [comment]
@GustavoCamargoRL Can you please double check the path? In C++ if the executable and the file are not in the same directory reading will also fail.
`uint16` is supported.

**Comment by GustavoCamargoRL** [comment]
@theNded yes, they're in the same directory, that's why i was not understanding the error, apparently it worked writing the whole path.
