### ISSUE TITLE
register_key_callback doesn't work

### ISSUE THREAD

**Issue by aydoo** [intel-isl/Open3D#1230]
**Describe the bug**
When I add a key using `register_key_callback(key, callback)`, it doesn't work. Callback is not called when key is pressed. Also, the key encoding is not clear from the docs.

**To Reproduce**
```
import numpy as np
import open3d as o3d

def key_callback(vis):
    print('key')

points = np.random.rand(100000, 3)
point_cloud = o3d.PointCloud()
point_cloud.points = o3d.Vector3dVector(points)

vis = o3d.visualization.VisualizerWithKeyCallback()
vis.create_window()
vis.add_geometry(point_cloud)
vis.register_key_callback(41, key_callback)

vis.run()
vis.destroy_window()
```

**Expected behavior**
When I press A, which should be keycode 41, I expect 'key' to be printed. Also, when running and I hit H, I can see that the key is not registered under:

> Keys registered for callback functions --
>     [)]
>     The default functions of these keys will be overridden.

**Environment (please complete the following information):**
 - OS:  Ubuntu 16.04
 - Python version: 3.5.2
 - Open3D version: latest
 - Is this remote workstation?: no
 - How did you install Open3D?: pip3

**Comment by syncle** [comment]
We are using ``GLFW_KEY`` for ``register_key_callback`` function. Based on [this document](https://www.glfw.org/docs/latest/group__keys.html), ``a`` is ``65``. 

The following code should work out of the box (with Open3D 0.9): 
```
import numpy as np
import open3d as o3d

def key_callback(vis):
    print('key')

points = np.random.rand(100000, 3)
point_cloud = o3d.geometry.PointCloud()
point_cloud.points = o3d.utility.Vector3dVector(points)

vis = o3d.visualization.VisualizerWithKeyCallback()
vis.create_window()
vis.add_geometry(point_cloud)
vis.register_key_callback(65, key_callback)

vis.run()
vis.destroy_window()
```

**Comment by orgicus** [comment]
Hi,

I found @syncle 's comment (including the link and python example extremely helpful.

Just as a minor addition, if anyone wants to add a keyboard shorcut (e.g. use modifier keys), [`register_key_action_callback`](http://www.open3d.org/docs/release/python_api/open3d.visualization.VisualizerWithKeyCallback.html#open3d.visualization.VisualizerWithKeyCallback.register_key_action_callback) is very useful.

Here's a tweaked version of the above example:

```python
import numpy as np
import open3d as o3d

def key_callback(vis):
    print('key')

def key_action_callback(vis, key, action):
    print('key',key, action)

points = np.random.rand(100000, 3)
point_cloud = o3d.geometry.PointCloud()
point_cloud.points = o3d.utility.Vector3dVector(points)

vis = o3d.visualization.VisualizerWithKeyCallback()
vis.create_window()
vis.add_geometry(point_cloud)
vis.register_key_callback(65, key_callback)
# s
vis.register_key_action_callback(83, key_action_callback)

vis.run()
vis.destroy_window()
```
You can use `key == 2` to repeat an action if the key is pressed and `action` to make a keyboard shortcut (e.g. `ctrl + s` = `action ==2`)

- `key == 1` : key pressed (then goes to 0 when released)
- `key == 2` : key held down (repeat input)
- `action == 0` : no modifier keys
- `action == 1` : shift is pressed
- `action == 2` : ctrl is pressed
- `action == 3` : ctrl + shift is pressed
- `action == 4` : alt is pressed
- `action == 5` : alt + shift is pressed
- `action == 6` : ctrl + alt is pressed

Hope this helps,
George

**Comment by whizbuzzer** [comment]
> Hi,
> 
> I found @syncle 's comment (including the link and python example extremely helpful.
> 
> Just as a minor addition, if anyone wants to add a keyboard shorcut (e.g. use modifier keys), [`register_key_action_callback`](http://www.open3d.org/docs/release/python_api/open3d.visualization.VisualizerWithKeyCallback.html#open3d.visualization.VisualizerWithKeyCallback.register_key_action_callback) is very useful.
> 
> Here's a tweaked version of the above example:
> 
> ```python
> import numpy as np
> import open3d as o3d
> 
> def key_callback(vis):
>     print('key')
> 
> def key_action_callback(vis, key, action):
>     print('key',key, action)
> 
> points = np.random.rand(100000, 3)
> point_cloud = o3d.geometry.PointCloud()
> point_cloud.points = o3d.utility.Vector3dVector(points)
> 
> vis = o3d.visualization.VisualizerWithKeyCallback()
> vis.create_window()
> vis.add_geometry(point_cloud)
> vis.register_key_callback(65, key_callback)
> # s
> vis.register_key_action_callback(83, key_action_callback)
> 
> vis.run()
> vis.destroy_window()
> ```
> 
> You can use `key == 2` to repeat an action if the key is pressed and `action` to make a keyboard shortcut (e.g. `ctrl + s` = `action ==2`)
> 
>     * `key == 1` : key pressed (then goes to 0 when released)
> 
>     * `key == 2` : key held down (repeat input)
> 
>     * `action == 0` : no modifier keys
> 
>     * `action == 1` : shift is pressed
> 
>     * `action == 2` : ctrl is pressed
> 
>     * `action == 3` : ctrl + shift is pressed
> 
>     * `action == 4` : alt is pressed
> 
>     * `action == 5` : alt + shift is pressed
> 
>     * `action == 6` : ctrl + alt is pressed
> 
> 
> Hope this helps, George

@orgicus Hi George,

Do you know how to identify which key has been pressed? I tried using the KeyEvent and KeyName classes, but did not find much success. E.g: I am creating a method that responds differently to different keys. My current workaround has been uniquely defining methods for each key press, and then feeding a corresponding method to `vis.register_key_action_callback(<GLFW_KEY>, key_action_callback)` depending on which key was pressed; I typed this command as many times as the number of keys that I am going to use for my visualizer.

Therefore, do you know anything that would help me simplify this process and reduce the lines of code?

**Comment by orgicus** [comment]
Hi @whizbuzzer 

I vaguelly remember digging through the GLFW refrence for [keys](https://www.glfw.org/docs/3.3/group__keys.html) and [modifiers](https://www.glfw.org/docs/3.3/group__mods.html) but I can't remember if they matched or were slightly different in Open3D for some reason.

That's why I used this (`print('key',key, action)`) in the callback to easily print the key and modifier values.
Kinda hacky, but did the job.

I'm not sure I've got a way to simplify it, other than another dirty hack which is another of writing the same thing.
So, current you kave something like `vis.register_key_action_callback(your_key, your_callback)` and you don't want to keep copy/pasting the line and modifying the key and function.
You could change if for something like `for key in your_list_of_keys: vis.register_key_action_callback(key, all_keys_callback)` and in the calback you'd check the key and call the right function (perhaps with a key/int to function lookup ?).
It's an idea :)

Let me know if the above makes sense and is helpful.

**Comment by whizbuzzer** [comment]
> Hi @whizbuzzer
> 
> I vaguelly remember digging through the GLFW refrence for [keys](https://www.glfw.org/docs/3.3/group__keys.html) and [modifiers](https://www.glfw.org/docs/3.3/group__mods.html) but I can't remember if they matched or were slightly different in Open3D for some reason.
> 
> That's why I used this (`print('key',key, action)`) in the callback to easily print the key and modifier values. Kinda hacky, but did the job.
> 
> I'm not sure I've got a way to simplify it, other than another dirty hack which is another of writing the same thing. So, current you kave something like `vis.register_key_action_callback(your_key, your_callback)` and you don't want to keep copy/pasting the line and modifying the key and function. You could change if for something like `for key in your_list_of_keys: vis.register_key_action_callback(key, all_keys_callback)` and in the calback you'd check the key and call the right function (perhaps with a key/int to function lookup ?). e.g.
> 
> ```python
> keys_to_calls = {
>  83, function_reference_1
>  84, function_reference_2
>  # ... etc
> }
> 
> for key in keys_to_calls:
>     vis.register_key_action_callback(key, keys_to_calls[key])
> ```
> 
> mildly better than:
> 
> ```python
> def all_keys_callback(vis, key, action):
>     if key == 83 and action == 0:
>         print('call function 1')
>     if key == 84 and action == 0:
>         print('call function 2')
>     # etc.   
> 
> keys = [83, 84] # more keys, etc.
> for key in keys:
>     vis.register_key_action_callback(key, all_keys_callback)
>     
> ```
> 
> It's an idea, not sure how useful though :)

Hi @orgicus thank you for the reply! Your code has one problem though which is that in the for loop, for some reason, only the last key is being registered. What I am trying to is create a functionality that will let me move a polygon in the with arrow keys in the visualizer. If I were to type out the `vis.register_key_action_callback()` consecutively, then I can do this (although moving the polygon diagonally is still not working). I was looking for a way to reduce the lines of code, and have a common function that would execute according to which key I pressed rather than having a different function for each key.

**Comment by gaurav00700** [comment]
Hello @orgicus  , 
I am trying to visualize multiple point cloud with interactive visualization using below code.
My intension is to change point cloud when key 'N' is pressed.
But pointcloud is not updating somehow.

```
idx = 0
def change_geometry(vis):
    global idx
    idx += 1 # Increment idx
    idx = idx % len(pcds) 
    vis.update_geometry(pcds[idx])
    vis.poll_events()
    vis.update_renderer() 

pcds = [pcd1, pcd2, pcd3..]  # o3d.geometry.PointCloud()
vis = o3d.visualization.VisualizerWithKeyCallback()

vis.create_window(width = 640, height = 640, left=700, top=0)
vis.add_geometry(pcds[0])

vis.register_key_callback(ord("N"), change_geometry)
vis.run()
```
