### ISSUE TITLE
Support for simultaneous multi-sensor capture using K4A / Realsense

### ISSUE THREAD

**Issue by stephansturges** [intel-isl/Open3D#1233]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem. 

**Describe the solution you'd like**
Is there a plan to implement simultaneous capture using the Intel Realsense or Microsoft Kinect 4 Azure sensors?  One interesting specificity of these sensors is that they support hardware synchronisation, and it's possible to use multiple sensors connected to one host. It would be great to have this directly inside Opend3D if possible!

**Describe alternatives you've considered**
I have tested synchronised capture using ROS with the realsense cameras and using the command-line applications that come as part of the Kinect SDK, but neither are very clean or easy to use. 

**Additional context**
Multi-sensor capture would open the way to integrating SLAM systems / extrinsic mapping directly in Open3D for these sensors in the future, which would be a very useful feature for many applications.

**Comment by theNded** [comment]
This is an interesting proposal. We do have a similar plan to develop a stack of protocals to support most popular RGB-D sensors and provide an abstract interface, but the priority is lower for now :(

**Comment by stephansturges** [comment]
That's interesting too :) 

FYI the Kinect at least has a very simple / clean way of adressing multiple cameras. In case you want to look into it you can find some code for using 2 cameras here: 
https://github.com/forestsen/KinectAzureDKProgramming/blob/master/Aruco_TwoKinects_Calibration_Extrinsics/Source_TwoKinects_Calibration.cpp

Cheers!

**Comment by theNded** [comment]
Thanks for the demo!
Close for now. Will refer to this issue when we start to work on this part.
