### ISSUE TITLE
Setting custom CMAKE_INSTALL_PREFIX causes compilation to fail

### ISSUE THREAD

**Issue by jasjuang** [intel-isl/Open3D#1234]
**To Reproduce**

```
git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D && mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
make -j
```

Here is the error message after `make -j`

```
make[2]: *** No rule to make target '3rdparty_install/lib/x86_64-linux-gnu/libturbojpeg.a', needed by 'lib/libOpen3D.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:523: recipe for target 'src/Open3D/CMakeFiles/Open3D.dir/all' failed
make[1]: *** [src/Open3D/CMakeFiles/Open3D.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

I can confirm that without setting a custom `CMAKE_INSTALL_PREFIX` it compiles successfully.

**Expected behavior**
I expect it to compile successfully. I can set custom `CMAKE_INSTALL_PREFIX` and compile other popular open-source libraries like opencv, tinyobjloader etc successfully.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: not sure
 - Open3D version: Latest master
 - Is this remote workstation?: no
 - How did you install Open3D?: build from source

**Comment by germanros1987** [comment]
@yxlao is this still happening? Can you reproduce it?

**Comment by yxlao** [comment]
this issue has been fixed
