### ISSUE TITLE
Hi , I am having trouble running an ICP registration in python with open3d package. while I want to draw the alignment object, I face with this error : [Open3D WARNING] Read geometry::PointCloud failed: unknown file extension. does anyone know how the solution? 

### ISSUE THREAD

**Issue by parisaa-riyahi** [intel-isl/Open3D#1243]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by syncle** [comment]
Please check the supported formats from [here](http://www.open3d.org/docs/release/tutorial/Basic/file_io.html?highlight=supported%20format#point-cloud)

**Comment by parisaa-riyahi** [comment]
Thanks 

> Please check the supported formats from [here](http://www.open3d.org/docs/release/tutorial/Basic/file_io.html?highlight=supported%20format#point-cloud)

Thank you. :)
