### ISSUE TITLE
Clean mesh extracted from ScalableTSDFVolume

### ISSUE THREAD

**Issue by martinakos** [intel-isl/Open3D#1246]
When I extract the mesh from a ScalableTSDFVolume I get a number of artifacts flying around the object of interest. I imagine that this is because of noisy depth maps or not totally correct image registrations. I would like to clean these artifacts from the mesh. I could do clustering on the point cloud and then use TriangleMesh.select_down_sample to remove the artifacts from the initial mesh. However, the clustering may take a long time to compute as it's a large point cloud. 

I wonder if there is something I could do directly on the mesh. I know there is only one object of interest and it's the largest, and I wonder if the mesh structure stores something like topology or polyhedron id that I could use to have a quick selection of the largest cluster directly on the mesh.

**Comment by theNded** [comment]
Regarding noise, you can try to use a smaller `sdf_trunc` in ScalableTSDFVolume initialization before you integrate.
In the default setting, `voxel_length=tsdf_cubic_size/512 = 0.0058, sdf_trunc=0.04`. This config will integrate depth in 7 voxels around surfaces, which may introduce noise. You may reduce it to sdf_trunc to 0.02 or 0.01. Note this should be able to reduce noise, but there may be some holes in the mesh.

For clustering, you can check DBSCAN
http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.cluster_dbscan

**Comment by martinakos** [comment]
I had sdf_trunc set to 5*voxel_length. I've changed it to just 3 and I get more noise artifacts. If I increase it to 7 I get a bit less artifacts but it takes longer to integrate.
I have already tried point clustering (with cylantro not dbscan) and it takes over 100s for my case, which is too slow. I'm not sure if dbscan would be much faster.

What I'm looking for is see if I can do some selection directly on the mesh, for example if there was some topology information stored in the mesh, I guess I could do that. any suggestions?

**Comment by martinakos** [comment]
I tried dbscan and for the amount of data I have it took around 5mins. I can't exactly tell because I didn't time it. and when I time it it crashed my machine. 

I think that what I'm looking for is to leverage the TriangleMesh.adjacency_list 
I see there are various filtering algorithms implemented int TriangleMesh like simplify_vertex_clustering and simplify_quadric_decimation but I haven't found any function to selected the largest connected cluster. Is there anything like this implemented?

**Comment by griegler** [comment]
@martinakos there is no `TriangleMesh` method yet that does what you want, i.e., clustering the triangle soup and then removing mesh parts where the number of triangles, or the surface area is smaller than a given threshold. That said, those algorithms sound useful and we might consider implementing them.

**Comment by martinakos** [comment]
Ok. I look forward to this functionality being implemented in Open3D. For the moment I'll try to find this functionality in some other library. any suggestions where I could look?
