### ISSUE TITLE
Save a icp registered pointclouds as one open3d.geometry.PointCloud variable

### ISSUE THREAD

**Issue by deepakyeleshetty** [intel-isl/Open3D#1247]
Hi!

I have two pointclouds which I can register using icp and it works fine as shown in this [Open3D tutorial](http://www.open3d.org/docs/release/tutorial/Basic/icp_registration.html). However, to see how the registered pointcloud is, I always have to call the `draw_registration_result(source, destination, transformation)` function with parameters - source pointcloud, target pointcloud and ICP transformation matrix. It would be really handy if it is possible to access the registered pointcloud as a single `open3d.geometry.PointCloud` variable for further use. 

If I understood properly, the `draw_registration_result(source, destination, transformation)` function transforms the `source` to the `target` using the `transformation` matrix from the ICP registration function and then visualizes both pointclouds (as `List[open3d.geometry.Geometry]`). 

I was wondering if there is any way to save the resulting pointcloud that we visualize from the `draw_registration_result(source, destination, transformation)` function, to one single pointcloud variable. 

Essentially, I want one single pointcloud from the viewpoint of the `target` pointcloud, and includes both - the `target` and the ICP transformed `source` points.

I am trying to do this and if there is any existing way to achieve this, please help me out. If not, could this be considered as a feature request?

Thanks!

**Comment by Resays** [comment]
do you find any method to save two combined point clouds in one point cloud after registration ?

**Comment by deepakyeleshetty** [comment]
Yep. It was a simple `+` operator. 

Transform the source pointcloud with ICP transformation matrix and save it in one pointcloud variable (`transformed_source`), add it with the target pointcloud (`target`) using the `+` operator and assign it to another pointcloud variable (`newpointcloud`).

```
newpointcloud = transformed_source + target 
o3d.visualization.draw_geometries(newpointcloud)
```

It gave the same result as the `draw_registration_result(source, target, transformation)` function when I visualized the pointcloud using `o3d.visualization.draw_geometries(newpointcloud)`. Even the number of points adds up.

**Comment by Resays** [comment]
in this scenario i have temp source and temp target like this :
`o3d.visualization.draw_geometries([source_temp, target_temp], width=1024, height=768)`

should i code like this ?

> newpointcloud = source_temp + target_temp
> o3d.visualization.draw_geometries(newpointcloud)
> o3d.visualization.write_point_cloud ( "result.ply", [newpointcloud])

**Comment by deepakyeleshetty** [comment]
After addition, the `newpointcloud` variable is of type _geometry::PointCloud_.

1. The `draw_geometries()` function accepts only **a list of geometry::PointCloud** variable as the first parameter. So, we should put `newpointcloud` within `[]` like `o3d.visualization.draw_geometries([newpointcloud])`
2. The `write_point_cloud()` function belongs to the io class and not to the visualization class. So it should be `o3d.io.write_point_cloud()` instead of `o3d.visualization.write_point_cloud()`. The function accepts only **geometry::PointCloud** variable as the second parameter. So we don't use a `[]`. Eg. `o3d.io.write_point_cloud("result.ply",newpointcloud)`

So overall you are right, except in using the `[]` brackets. 

In my previous comment I missed to include the `[]` but I edited it now.

**Comment by Resays** [comment]
i used this code but giving me error:

> def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.transform(transformation)
    #o3d.visualization.draw_geometries([source_temp, target_temp], width=1024, height=768)
    
    

> newpointcloud = source_temp + target_temp
    o3d.visualization.draw_geometries(newpointcloud)
    o3d.io.write_point_cloud ( "result.ply", newpointcloud)

but showing me error like this:

> TypeError: draw_geometries(): incompatible function arguments. The following argument types are supported:
    1. (geometry_list: List[open3d.open3d.geometry.Geometry], window_name: str = 'Open3D', width: int = 1920, height: int = 1080, left: int = 50, top: int = 50) -> None
Invoked with: geometry::PointCloud with 412490 points.

**Comment by Resays** [comment]
These are two point clouds and need to merge them with any registration method:
I am using Global Registration but it's unpredictable, not giving me exact results 
changed on every Run: 
 
![result](https://user-images.githubusercontent.com/50095407/67087600-36723980-f1de-11e9-900e-a85a83489a04.PNG)

**Comment by deepakyeleshetty** [comment]
I have never tried global registration but I did face a similar issue in ICP registration. I will explain what I observed and experienced. 

There are two main things to consider:
1. The background depth information.
2. The transformation between the source and target pointclouds. 

The depth points of the background surface (in your case - the wall) in both pointclouds are close to each other. Due to this, the algorithm sees an earlier convergence as it iterates through the points, resulting in the pointcloud that you got. The solution that worked for me was to eliminate these background points. I don't exactly know how to solve this after the pointcloud is obtained. But I did it with my camera's SDK. I used Realsense D435 camera and its SDK's post processing filter ([threshold filter](https://intelrealsense.github.io/librealsense/python_docs/_generated/pyrealsense2.threshold_filter.html#pyrealsense2.threshold_filter)) to exclude the points that are beyond a certain distance. This did improve the convergence to a great extent.

Another important thing that I observed was the initial transformation matrix that we give (`trans_init`). Instead of the matrix you entered (`np.asarray([[0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 0.0],[0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0]])`), maybe try estimating the transformation mathematically. If camera 1 is `20 cm` away from camera 2, the transformation matrix is:
```
trans_init = np.asarray([[1., 0., 0., 0.20],
                      [0., 1., 0., 0.],
                      [0., 0., 1., 0.],
                      [0., 0., 0., 1.]])
```
If there is a rotation, you need to find that too and multiply the entire sequence of transformation matrices in reverse order. This (article)[http://www.codinglabs.net/article_world_view_projection_matrix.aspx] has the formula to find the translation and rotation matrices. 

These are my observations and I was able to register the pointclouds properly after taking these 2 considerations. Hope it works for you too.

**Comment by Resays** [comment]
Ok, im goona read the article, and im using D415 so can you share the code?
whatever you did the experiment ... i want to review your code as well.

**Comment by Resays** [comment]
There is a little offset and i can't adjust it ... can u suggest what is missing in the parameters ?

> trans_init = np.asarray( [[0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 0.0],[0.1, 1.0, 0.0, 0.0], [0.0, 0.0, 0.1, 1.0]] )

![reg-without-background](https://user-images.githubusercontent.com/50095407/67139562-9c1cff00-f28c-11e9-8b4d-31b7a52bb809.PNG)

**Comment by deepyels** [comment]
Sorry I can't share my code because of IP restrictions. The result above looks better than the previous one. Maybe adjust the `threshold` (or `max_correspondence_distance`) parameter in the [register_icp()](http://www.open3d.org/docs/release/python_api/open3d.registration.registration_icp.html#open3d.registration.registration_icp) function? You could probably play around with that value. 

Also, check if you gave the right transformation matrix between source and target. If you had rotated it a little bit and didn't include it in the transformation matrix, the result will be affected. Break the camera movement from source to target step by step. Eg. 
1. Rotate source camera about 45 degrees around Y axis (+45 or -45 depending on the direction of rotation) -- Get a Rotation matrix `rot1`.
2. Translate 40 cm along negative X direction -- Get a translation matrix `tran1`
3. Rotate 45 degrees along Y such that the camera is exactly where the target is. -- Get a rotation matrix `rot2`
4. The resulting transformation matrix would be `trans_init = np.matmul(np.matmul(rot2,tran1),rot1)`

If adjusting both the `threshold` and the `trans_init` values doesn't help, try the whole thing with a new pointcloud with more depth elements. Maybe like a specific object (cup or teapot) from two perspectives with known camera transformation matrices. It should work, hopefully.

**Comment by MehranTaghipour** [comment]
> Yep. It was a simple `+` operator.
> 
> Transform the source pointcloud with ICP transformation matrix and save it in one pointcloud variable (`transformed_source`), add it with the target pointcloud (`target`) using the `+` operator and assign it to another pointcloud variable (`newpointcloud`).
> 
> ```
> newpointcloud = transformed_source + target 
> o3d.visualization.draw_geometries([newpointcloud])
> ```
> 
> It gave the same result as the `draw_registration_result(source, target, transformation)` function when I visualized the pointcloud using `o3d.visualization.draw_geometries([newpointcloud])`. Even the number of points adds up.

Dear deepakyeleshetty
Thanks so much for your explanation. I have same problem. but I don't know how can I transfer?! Is there any python code for tranformation? 

Bests
