### ISSUE TITLE
ClusterDBSCAN parameters setting

### ISSUE THREAD

**Issue by GustavoCamargoRL** [intel-isl/Open3D#1248]
Hey guys, i am trying to make a clusterization of a point cloud, using the  ClusterDBSCAN function, but i didn't found how to set the parameters properly "(double eps, size_t min_points, bool print_progress = false)". I was wondering if someone knows how are the parameters usually set for a general use?

**Comment by griegler** [comment]
Documentation is [here](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.cluster_dbscan).
With `eps` you can define the max Euclidean distance between two points that should belong to the same cluster. With `min_points` you define the minimal number of points that are necessary to create a cluster.
