### ISSUE TITLE
Please note the example code version and the open3d version via pip

### ISSUE THREAD

**Issue by MaxChanger** [intel-isl/Open3D#1252]
If I want to use open3d (python version) to do some work, according to `open3d.org/docs` I may perform the following steps: (use miniconda environment)
```shell
pip install open3d
git clone --recursive https://github.com/intel-isl/Open3D.git
# cd Open3D/examples/Python/Basic ansd test some examples, such as: 
python rgbd_redwood.py
python pointcloud.py
# ...
```
But when I tested `python visualization.py`, I found some bugs.
```shell
python visualization.py

Load a ply point cloud, print it, and render it
Let's draw some primitives
We draw a few primitives using collection.
We draw a few primitives using + operator of mesh.
Let's draw a cubic using o3d.geometry.LineSet.
Traceback (most recent call last):
  File "visualization.py", line 68, in <module>
    lines=o3d.utility.Vector2iVector(lines),
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.open3d.geometry.LineSet()
    2. open3d.open3d.geometry.LineSet(arg0: open3d.open3d.geometry.LineSet)

Invoked with: kwargs: points=std::vector<Eigen::Vector3d> with 8 elements.
Use numpy.asarray() to access data., lines=std::vector<Eigen::Vector2i> with 12 elements.
Use numpy.asarray() to access data.

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
```
So I think the problem lies in the definition of `open3d.geometry.LineSet`, and then I read the source code to try to find a solution to the problem. But in `src/Open3D/Geometry/LineSet.h` I found:
```C++
class LineSet : public Geometry3D {
public:
    LineSet() : Geometry3D(Geometry::GeometryType::LineSet) {}
    LineSet(const std::vector<Eigen::Vector3d> &points,
            const std::vector<Eigen::Vector2i> &lines)
        : Geometry3D(Geometry::GeometryType::LineSet),
          points_(points),
          lines_(lines) {}
    ~LineSet() override {}
```
The definition of the class is completely correct, so I don't know where the problem is.

---------

After a while, my colleague told me that it might be a version issue. It has been confirmed that the code version is indeed the essence of solving the problem.
**The version of open3d installed via pip is 0.8.0, but the example code downloaded via github is the master branch.**
After that, I checkout the repo to tag v0.8.0, and review the file `open3d.geometry.LineSet` again, I found:
```C++
class LineSet : public Geometry3D {
public:
    LineSet() : Geometry3D(Geometry::GeometryType::LineSet) {}
    ~LineSet() override {}
```
Compared to the two versions, v0.8.0 is missing a constructor:
```C++
LineSet(const std::vector<Eigen::Vector3d> &points, const std::vector<Eigen::Vector2i> &lines)
```
If I compile through the source code of the `master branch` and then test based on `example code` of the `master branch`, there may be no problem.

---------

I wasted a lot of time because of my carelessness. I hope that you can mention this version issue somewhere to prevent more people from getting stuck with this problem. ^_^

**Comment by syncle** [comment]
Thanks for the note. We are actively developing our document and source code, so it might be inconsistency happens.
