### ISSUE TITLE
build error with XConvertSelectionreference

### ISSUE THREAD

**Issue by zhangxiaodi** [intel-isl/Open3D#1253]
//usrusr/bin/ld: /usr/local/lib/libglfw3.a(x11_window.c.o)/usr/bin/ld: /usr/local:/bin//ldlib:/ libglfw3.a/(usrx11_window.c.o/)local:/ libundefined/ libglfw3.areference( x11_window.c.oto) :symbol  undefined' XConvertSelectionreference' 
to/ /symbolusr /'libXConvertSelection/'x86_64
-/linux/-usrgnu//liblibX11.so.6/:x86_64 -errorlinux -addinggnu /symbolslibX11.so.6::  DSOerror  missingadding  fromsymbols :command  DSOline 
missing from command line
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
 undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
examples/Cpp/CMakeFiles/ViewDistances.dir/build.make:106: recipe for target 'bin/examples/ViewDistances' failed
make[2]: *** [bin/examples/ViewDistances] Error 1
src/Tools/CMakeFiles/ViewGeometry.dir/build.make:106: recipe for target 'bin/ViewGeometry' failed
make[2]: *** [bin/ViewGeometry] Error 1
src/Tools/CMakeFiles/ManuallyCropGeometry.dir/build.make:106: recipe for target 'bin/ManuallyCropGeometry' failed
make[2]: *** [bin/ManuallyCropGeometry] Error 1
CMakeFiles/Makefile2:1854: recipe for target 'examples/Cpp/CMakeFiles/ViewDistances.dir/all' failed
make[1]: *** [examples/Cpp/CMakeFiles/ViewDistances.dir/all] Error 2

**Comment by syncle** [comment]
It seems like an error when Open3D apps try to link some graphics libraries. Have you tried this script to install dependencies? https://github.com/intel-isl/Open3D/blob/master/util/scripts/install-deps-ubuntu.sh 
And please use the template to open a new issue.

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
