### ISSUE TITLE
Global Registration is Unpredictable, final result is not same on every Run 

### ISSUE THREAD

**Issue by Resays** [intel-isl/Open3D#1254]
These are two point clouds and need to merge them with any registration method:
I am using Global Registration but it's unpredictable, not giving me exact results
changed on every Run:

how to match both right and left point clouds exactly as explained in the example?

![image](https://user-images.githubusercontent.com/50095407/67088688-c1ecca00-f1e0-11e9-9f4e-91fc6c113ba7.png)
Console window Result:

> :: Load two point clouds and disturb initial pose.
> :: Downsample with a voxel size 0.050.
> :: Estimate normal with search radius 0.100.
> :: Compute FPFH feature with search radius 0.250.
> :: Downsample with a voxel size 0.050.
> :: Estimate normal with search radius 0.100.
> :: Compute FPFH feature with search radius 0.250.
> :: RANSAC registration on downsampled point clouds.
> Since the downsampling voxel size is 0.050,
> we use a liberal distance threshold 0.045.
> registration::RegistrationResult with fitness = 0.396936, inlier_rmse = 0.027044, and correspondence_set size of 285
> Access transformation to get result.
> :: Point-to-plane ICP registration is applied on original point
> clouds to refine the alignment. This time we use a strict
> distance threshold 0.020.
> registration::RegistrationResult with fitness = 0.000000, inlier_rmse = 0.000000, and correspondence_set size of 0
> Access transformation to get result.

Code (using Open3D) file and two point cloud file are attached:
[global_registration.zip](https://github.com/intel-isl/Open3D/files/3743531/global_registration.zip)

**Comment by syncle** [comment]
Looks RANSAC+FPFH fails as there are no geometrical landmarks not enough for the matching. Could you try RGBD registration instead (I presume the two-point clouds from depth images)

**Comment by Resays** [comment]
You are asking about "RGBD odometry", right ?

**Comment by MaxChanger** [comment]
@Resays 
Hello, I meet the same issue with you. [#1264 ](https://github.com/intel-isl/Open3D/issues/1264) Have you found a way to solve this problem?
I did some testing, and found something interested, I hope you can help me to ensure it.

the command recommend in tutorial like this:
```shell
python run_system.py config/tutorial.json --make --register --refine --integrate
```
Obviously, we can roughly divide it into two categories, fragment generation and registration.
```shell
①  python run_system.py config/tutorial.json --make 
②  python run_system.py config/tutorial.json --register --refine --integrate
```
After using ① to generate the fragments,  we keep the fragments folder unchanged, no matter how many times the ② command is used, the result is almost the same every time.

But once we regenerate the fragments using command ①, the result may be different.
