### ISSUE TITLE
To show the intensity map on a gray scale point cloud?

### ISSUE THREAD

**Issue by aGIToz** [intel-isl/Open3D#1256]
I have a gray scale pointcloud ( intensity value is same in all the 3 channels). I can visualize it with open3d. Is there any way to visualize the intensity map on the pointcloud. By that I mean the points with large intensity are displayed as Red color and with less intensity are displayed as Voilet.

**Comment by syncle** [comment]
How about mapping gray value to colormap using ``matplotlib``?

**Comment by aGIToz** [comment]
Yes, thanks I already did that but using the opencv. I should have closed this issue but here is how I did it:

```python
t =  np.load("your_gray_scale_file.npz")
t = t["texture"]  # t is your N by 1 grayscale matrix with values between 0 to 1

#convert it to uint
t = np.uint8(255*t)

#apply the colormap
t_c = cv.applyColorMap(t, cv.COLORMAP_JET)/255 # This wiil yield t_c with shape of N by 1 by 3

#indexing to get N by 3, colored texture
t_c = t_c[:,0,:]
# Now one can use the coloured texture with the position cords to visualize the intensity map on pointcloud 

```
