### ISSUE TITLE
Changing ICPConvergenceCriteria and displayed value

### ISSUE THREAD

**Issue by apiszcz** [intel-isl/Open3D#1258]
When setting the relative_rmse the result returned does not have enough precision to show smaller values. However the value is set correctly. perhaps %0.9f for the print format.

(Pdb) o3d.registration.ICPConvergenceCriteria(relative_rmse = 0.0000001)
registration::ICPConvergenceCriteria class with relative_fitness = 0.000001, relative_rmse = 0.000000, and max_iteration = 30

**Comment by griegler** [comment]
Fixed in #1274.
