### ISSUE TITLE
[Open3D WARNING] Read OBJ failed: Material file not found.

### ISSUE THREAD

**Issue by SYSUMSD** [intel-isl/Open3D#1259]
When I tried to use read_triangle_mesh to read a mesh files in obj format, I met a mistake.

```
>>> import open3d as o3d
>>> a = o3d.io.read_triangle_mesh("/home/user/data_3d/A.obj",print_progress = True)

```
the error liked this:

```
[Open3D WARNING] Read OBJ failed: Material file [ A.mtl ] not found.
Failed to load material file(s). Use default material.

Segmentation fault

```
and python console exited.

The error says there isn't a mtl file. 
But A.mtl, A.obj and A.jpg are all in data_3d directory and I can open this obj object using Meshlab .

Environment:
 - OS:  Ubuntu 18.04.3
 - Python version:3.7.3
 - Open3D version:0.8.0.0
 - Is this remote workstation?: yes 
 - How did you install Open3D?: 
the open3d installed using pip or conda or build_from_source all had these problem.

**Comment by theNded** [comment]
Can you please shared the files? There might be a problem in file parsing.

**Comment by theNded** [comment]
Ah, sorry, this feature was not included in 0.8.0.0. It should have been supported in #1194. You may compile from the source, or wait for the next release with official support.

**Comment by SYSUMSD** [comment]
> Ah, sorry, this feature was not included in 0.8.0.0. It should have been supported in #1194. You may compile from the source, or wait for the next release with official support.

I have read #1194 discussion.  Do you mean that this feature is still in development stage?
The package I have used is compile from the source download from https://github.com/intel-isl/Open3D.git.  It looks like these files didn't include changes your made.
Maybe I should wait for the new release supporting this file type.....

**Comment by SYSUMSD** [comment]
> Ah, sorry, this feature was not included in 0.8.0.0. It should have been supported in #1194. You may compile from the source, or wait for the next release with official support.

@theNded 
Hi, I have downloaded the source code using code 'git clone --recursive https://github.com/intel-isl/Open3D' today and compile from this source. But the problem is still exist...

Is there any other method to deal with this problem?

looking forward to your early reply.

**Comment by shiyoung77** [comment]
I met the same problem. I think it is a bug that the function looks for .mtl file in the current working directory rather than the directory where .obj file is located. Please fix. Thanks. @theNded

**Comment by kaixin-bai** [comment]
@shiyoung77 if i set the .mtl file in the current working directory, it still doesn't work and no error is printed.

**Comment by theNded** [comment]
@SYSUMSD Sorry for the late reply, did you install via `make install-pip-package'? Otherwise you would be still using the 0.8.0.0 version.
It should be able to load a textured cube if installed correctly.
https://github.com/intel-isl/Open3D/blob/master/examples/Python/Basic/visualization.py

@shiyoung77 , @kaixin-bai can you please try the same and see if the lateset version is installed?

**Comment by shiyoung77** [comment]
After cloned the latest repo and compiled from source. The issue is gone. Thanks. @theNded

**Comment by Jianghanxiao** [comment]
Has this feature been available in the 0.10.0.0 version? Currently, I still met the problem that the textures are not loaded correctly. Could anyone help?

**Comment by griegler** [comment]
@Jianghanxiao can you provide more details, or an example.
@errissa @prewettg can you please have a look.

**Comment by errissa** [comment]
@Jianghanxiao Would you please share any error messages you see on the console when you try to load the model? Also, if you can share the model. that would be helpful as well.

**Comment by ttsesm** [comment]
@errissa I am having a similar problem as well check my message [here](https://github.com/intel-isl/Open3D/issues/1484#issuecomment-687173998), not sure whether it is material file related or not but you can find the model attached.

Not sure what is the issue though.

**Comment by ucalyptus** [comment]
@theNded what if I dont have an mtl file for my mesh, is there a Material=None kinda flag that suppresses this warning?
