### ISSUE TITLE
The results of the ReconstructionSystem usually fail, and registration result is not ideal

### ISSUE THREAD

**Issue by MaxChanger** [intel-isl/Open3D#1264]
I have tested the living room data of redwood in your tutorial. The first time I got a particularly bad result, but when I ran the second time I found that the result was barely acceptable. So I ran it many times, but I got different results every time. How should I understand this problem ?
There are four failed cases:
![four_error_result](https://user-images.githubusercontent.com/35401968/67393896-e0363980-f5d5-11e9-8288-10f27a769b10.png)

**Comment by theNded** [comment]
See #797 #831 
Can you try either of [Disable OpenMP] and [Disable joblib]?

**Comment by MaxChanger** [comment]
Thanks @theNded, I will check and try it.

**Comment by MaxChanger** [comment]
> See #797 #831
> Can you try either of [Disable OpenMP] or [Disable joblib]?

I try to turn off multithreading by using `"python_multi_threading": false ,
` in config/tutorial.json, but did not find obvious improvements.

I did some testing, and then found something interested, I hope you can help me to ensure it.

the command recommend in official tutorial like this:
```shell
python run_system.py config/tutorial.json --make --register --refine --integrate
```

Obviously, we can roughly divide it into two categories, fragment generation and registration.
```shell
①  python run_system.py config/tutorial.json --make 
②  python run_system.py config/tutorial.json --register --refine --integrate
```
After using ① to generate the fragments, we keep the fragments folder unchanged, no matter how many times the ② command is used, the result is almost the same every time.

But once we regenerate the fragments using command ①, the result may be different.

**Comment by theNded** [comment]
Ah, I wanted to check if there's any fragment that doesn't make sense. They seem to be correct according to your description. Then the problem should be within registration.

**Comment by MaxChanger** [comment]
I agree with your opinion, I also think that because of the registration failed, the final result is not good.
But after my test, I can't find out if the registration itself has a problem (--register --refine --integrate), or in the make fragments stage(--make), as show in #1281 

So I don't know what I should do, improve the precision of the registration or optimize the make fragments section.
