### ISSUE TITLE
Add concave hull function for point clouds

### ISSUE THREAD

**Issue by HowcanoeWang** [intel-isl/Open3D#1267]
**Is your feature request related to a problem? Please describe.**
I am doing some point cloud analysis, I am benefited a lot from the build-in convex hull functions, I also need to calculate the concave hull to get another volume estimation.

**Describe the solution you'd like**
Will it possible to provide a function in `o3d.geometry.PointCloud` class, called `compute_concave_hull(self)` and Returns `open3d.geometry.TriangleMesh` of that?

**Describe alternatives you've considered**
If you can provide a function to calculate the perimeter and volume of the generated convex or concave hull, that would be very nice. Currently, I need to use `scipy.spatical` package to get these values.

Anyway, thanks a lot for such a good package!

**Comment by griegler** [comment]
The concept of a concave hull is not very well defined in contrast to the convex hull. Do you have a specific algorithm in mind?

**Comment by HowcanoeWang** [comment]
> The concept of a concave hull is not very well defined in contrast to the convex hull. Do you have a specific algorithm in mind?

https://www.mathworks.com/help/matlab/ref/alphashape.html
https://www.mathworks.com/help/matlab/ref/alphashape.boundaryfacets.html

Hoping something like these (though these materials are implemented in Matlab)

Or https://stackoverflow.com/questions/26303878/alpha-shapes-in-3d

BTW, it seems `compute_concave_hull(self, alpha=0.5)` need an alpha parameter.

**Comment by griegler** [comment]
Implemented in #1320.
