### ISSUE TITLE
Large PTS reading issue

### ISSUE THREAD

**Issue by YouYue123** [intel-isl/Open3D#1278]
**Problem**

I am facing problem when loading a 4 billion **.PTS** point cloud file. Because the number of pts is exceeding the limit of signed 32 int (2,147,483,647) by referencing [this doc](https://en.cppreference.com/w/cpp/language/types)

**Solution**

I realised in Open3D you are reading header of PTS as integer, I made my change to unsigned long long for header reading. 

It works well from my side, dose this changing look like a good solution from you? I can make a pull request for this issue to support large PTS reading.

**Comment by syncle** [comment]
Addressed via #1279. Thanks @YouYue123!
