### ISSUE TITLE
After --refine, the integrate result become worse

### ISSUE THREAD

**Issue by MaxChanger** [intel-isl/Open3D#1281]
**Describe the bug**
After `--refine`, the integrate result become worse.
I follow the official tutorial using Open3D, and found out that the results of each reconstruction are different, and in most cases it is worse #1264 #1254 . So I did a lot of tests to find out where the problem is. 

When I used `debug/visualize_alignment.py` to see the registration between two fragments, the parameter `--before_optimized` made me found some differences. I found a strange registration in using `config["template_refined_posegraph_optimized"]`, but is normal in `config["template_global_posegraph"]`.

So, I modify the line in  `integrate_scene.py`,  use the posegraph in `global_registration_optimized.json` instead of `refined_registration_optimized.json` and get a better result than using `--refine`.
```python
    pose_graph_fragment = o3d.io.read_pose_graph(   
        # join(path_dataset, config["template_refined_posegraph_optimized"])) # refined_registration_optimized.json
        join(path_dataset, config["template_global_posegraph_optimized"])) # global_registration_optimized.json
```

**Expected behavior**
I don't understand why this happens, and why the result of integrate becomes worse after refinement.

**Screenshots**
![without_refine_step](https://user-images.githubusercontent.com/35401968/67857685-60b6e600-fb52-11e9-81cd-737ba9527a5a.png)
> the left image using `global_registration_optimized.json`， the right image using `refined_registration_optimized.json`

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.6.9
 - Open3D version: 0.8.0
 - Is this remote workstation?: no
 - How did you install Open3D?:  `conda install -c open3d-admin open3d`

**Comment by theNded** [comment]
It's seems like a wrong loop closure was not filtered (which should have been). 

Are you using FGR or RANSAC?
Also, can you please upload these .json files?

**Comment by MaxChanger** [comment]
Yes, I use the .josn files in tutorial [config/tutorial.josn](https://github.com/intel-isl/Open3D/blob/master/examples/Python/ReconstructionSystem/config/tutorial.json) without any change.
The default is RANSAC，right?

**Comment by theNded** [comment]
Sorry I didn't make it clear. Can you please share the pose graphs' json files? Also, can you identify the fragment ids with strange registrations? A screenshot can be very helpful.

**Comment by MaxChanger** [comment]
@theNded Thank you very much, I will continue to try the solution you provided to find out if there are any problems.

**Comment by MaxChanger** [comment]
I get your point, and I change the method of `"icp_method": "point_to_plane"` in tutorial.json
The picture below is a comparison of two icp_methods, in the same fragments folder (same once --make)

![Screenshot from 2019-10-31 14-36-47](https://user-images.githubusercontent.com/35401968/67924729-5ba67500-fbec-11e9-927d-0c2c1c1dc745.png)
> the left is `"icp_method": "point_to_plane"` and the right is `"icp_method": "color"`

**Comment by MaxChanger** [comment]
@theNded  I checked your analysis in #1286 
I don't know if you remember it seems that there are many mistakes in the --refine stage, but there are no mistakes in the --register stage. However, multiscale_icp is called in both stages, that is, color_icp is used in both stages. 
**The difference between the two is the downsample in the --register stage, while the --refine stage does not.**
> As you mentioned:
it seems that some ill color gradiants polluted the linear system

**I guess it's due to some noise points in original ply file without downsample, am I right ?**

https://github.com/intel-isl/Open3D/blob/e6568ea3ee57a53828c6353a1da04638c9a234e4/examples/Python/ReconstructionSystem/register_fragments.py#L66-L68

https://github.com/intel-isl/Open3D/blob/e6568ea3ee57a53828c6353a1da04638c9a234e4/examples/Python/ReconstructionSystem/refine_registration.py#L93-L102

**Comment by MaxChanger** [comment]
@theNded  I did a little try, also downsample in the --refine stage, the code is as follows, the function `preprocess_point_cloud` is the same as `register_fragments.py`, I thought it would get a good result, but I got **two different bad scenes.**
So the problem does not seem to be down sampling.

![Screenshot from 2019-11-06 15-39-32](https://user-images.githubusercontent.com/35401968/68278635-be948200-00ac-11ea-93c1-560069c684bd.png)



```python
def register_point_cloud_pair(ply_file_names, s, t, transformation_init,
                              config):
    print("reading %s ..." % ply_file_names[s])
    source = o3d.io.read_point_cloud(ply_file_names[s])
    print("reading %s ..." % ply_file_names[t])
    target = o3d.io.read_point_cloud(ply_file_names[t]) 

    (source_down, source_fpfh) = preprocess_point_cloud(source, config) 
    (target_down, target_fpfh) = preprocess_point_cloud(target, config)
    (transformation, information) = \
                local_refinement(source_down, target_down, transformation_init, config)   

    # (transformation, information) = \
    #         local_refinement(source, target, transformation_init, config)   
    if config["debug_mode"]:
        print(transformation)
        print(information)
    return (transformation, information)
```
