### ISSUE TITLE
Can I use Open3D on android?If so,how do i compile Open3D by NDK?

### ISSUE THREAD

**Issue by liyuan90** [intel-isl/Open3D#1290]
Can I use Open3D on android?If so,how do i compile Open3D by NDK?

**Comment by syncle** [comment]
That sounds interesting, but we haven't tested in the official CI branch. 
If you don't mind, could you try [building NDK using cmake](https://developer.android.com/ndk/guides/cmake)? I presume it would work because Open3D build-chain is based on CMake.

**Comment by liyuan90** [comment]
Thanks, With reference to https://github.com/pezcode/open3d-core-android, I've compiled.

**Comment by TheBricktop** [comment]
@griegler  Pezcode version should be added as a reference of open3d cross platform ports to the main readme or wiki cause its crucial for working with mobile arcore/arkit/rgbd enabled devices.

**Comment by raju535482** [comment]
I have compiled Open3d till version 0.10.0, but I need to compile for version 0.15.1. How do I do it?

**Comment by Norlandz** [comment]
any updates? 

I kept getting things like 
```
CMake Error at /usr/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
```

I tried to removed some not needed dependencies but the flags seems never get respected. 

Am I suppose to compile this on a Linux x86_64 machine then generate a .so file for arm64 Android device or what? Im lost. 

Any success with a demo cmake command? 

I tried to change the flags, or even the source cmakelist file. no luck. 
eventually i got all sorts of ai hallucination flags that doesnt work:

```
cmake -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$NDK_PATH/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI="arm64-v8a" \
    -DANDROID_PLATFORM=android-24 \
    -DANDROID_STL=c++_shared \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_GUI=OFF \
    -DBUILD_PYTHON_MODULE=OFF \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_UNIT_TESTS=OFF \
    -DBUILD_WEBRTC=OFF \
    -DENABLE_HEADLESS_RENDERING=OFF \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUILD_PYTORCH_OPS=OFF \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
    -DBUILD_JUPYTER_EXTENSION=OFF \
    -DUSE_BLAS=OFF \
    -DBUILD_VISUALIZATION=OFF \
    -DBUILD_GLFW=OFF \
    -DBUILD_GLEW=OFF \
    -DOPEN3D_USE_X11=OFF \
    -DANDROID=1 \
    -DCMAKE_SYSTEM_NAME=Android \
    ..
```

also. multiple ndk or cmake version tried. 


or should i just abandon this open3d thing on Android device?
