### ISSUE TITLE
AttributeError: object has no attribute 'cluster_dbscan'

### ISSUE THREAD

**Issue by GustavoCamargoRL** [intel-isl/Open3D#1299]
Hi i'm trying to run the python clustering example with my own point cloud, but i'm getting the following error:
"Traceback (most recent call last):
  File "c:/Users/cluster.py", line 26, in <module>
    labels = np.array(pcl.cluster_dbscan(eps=0.05, min_points=10, print_progress=True))
AttributeError: 'open3d.open3d.geometry.PointCloud' object has no attribute 'cluster_dbscan'"

I'm running it on windows 10, python 3.7 and open3D 0.7
And that's the code:

```py
# Open3D: www.open3d.org
# The MIT License (MIT)
# See license file or visit www.open3d.org for details

# examples/Python/Basic/clustering.py

import numpy as np
import open3d as o3d
import matplotlib.pyplot as plt


#rgb = o3d.io.read_image("Color0263.png")
#depth = o3d.io.read_image("Depth0263.png")

#rgbd = create_rgbd_image_from_color_and_depth(rgb,depth,convert_rgb_to_intensity=False)
#intrinsic = o3d.camera.PinholeCameraIntrinsic(564.3, 564.3, 480, 270, 960, 540)
#pcl = create_point_cloud_from_rgbd_image( rgbd, intrinsic)
pcl = o3d.io.read_point_cloud("output.ply")
#pcl.cluster_dbscan(eps=0.05, min_points=10)
o3d.utility.set_verbosity_level(o3d.utility.Debug)

cmap = plt.get_cmap("tab20")
print("has %d points" % (np.asarray(pcl.points).shape[0]))
o3d.visualization.draw_geometries([pcl])

labels = np.array(pcl.cluster_dbscan(eps=0.05, min_points=10, print_progress=True))
max_label = labels.max()
print("has %d clusters" % (max_label + 1))

colors = cmap(labels / (max_label if max_label > 0 else 1))
colors[labels < 0] = 0
pcl.colors = o3d.utility.Vector3dVector(colors[:, :3])
o3d.visualization.draw_geometries([pcl])
```

And that's the point cloud i'm using

[output.zip](https://github.com/intel-isl/Open3D/files/3809368/output.zip)

**Comment by griegler** [comment]
`cluster_dbscan` was only added in `0.8`, see [here](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.cluster_dbscan).

**Comment by GustavoCamargoRL** [comment]
@griegler Oh i see, but i had another problem with 0.8, i downloaded it from "pip install open3d" but i couldn't import it using "import open3d".
Do you know why i can't import it? that's why i was using the 0.7 version from "pip install open3d-python"

**Comment by griegler** [comment]
@GustavoCamargoRL maybe you could open another issue on that topic with more context, e.g., error message, OS, etc.
