### ISSUE TITLE
Unable to import open3D 0.8

### ISSUE THREAD

**Issue by GustavoCamargoRL** [intel-isl/Open3D#1301]
Hi, i'm trying to use open3D 0.8 with python. I followed [this](http://www.open3d.org/docs/release/getting_started.html) tutorial, apparently everthing was installed since no error message has been shown. But when i try to "import open3d" that's the following error: "ModuleNotFoundError: No module named 'open3d'".

I also tried installing the open3d 0.7 with "pip install open3d-python" and i could import the library, so my problem is specifically with open3D 0.8 .

I have already checked that open3d 0.8 is installed with "pip list" command.

Running on windows 10, with python 3.7.0

Does anyone knows what's happening ?

**Comment by IkonOne** [comment]
I had the same issue but don't remember the entire solution.  I do know that Open3d 0.8 will not work with python 3.7.  You must use 3.6 per the documentation: http://www.open3d.org/docs/release/getting_started.html#installing-from-pypi-or-conda

**Comment by GustavoCamargoRL** [comment]
@IkonOne in deed i saw that in the documentation, and tried using python 3.6 and it also didn't worked. and in [pypi site](https://pypi.org/project/open3d/) they say that work with 3.7 so i thought that the open3d documentation maybe was out of date. either way, 3.6 and 3.7 didn't worked for me.

**Comment by AlbertoMQ** [comment]
I get this when doing conda install with python 3.7

**Comment by LangeJustin** [comment]
I made it work by by creating a virtual envirement with python 3.8. Please make sure that your scripts are also running on python 3.8 by using `python3.8 pythonfile.py` for instance. It seems that this is a problem related to python 3.7.

**Comment by germanros1987** [comment]
This issue should be solved for 0.10. @LangeJustin by any chance, have you tried with 0.10?

**Comment by yxlao** [comment]
In general, we recommend:
- Using a python virtual env (such as conda)
- Make sure the python env that you installed open3d is the same as the one that you run open3d
- Make sure the python is 64 bit, not 32
