### ISSUE TITLE
Saving Meshes after sharpening

### ISSUE THREAD

**Issue by plevshad** [intel-isl/Open3D#1302]
**Describe the bug**
Open3d can't write or open properly a mesh (created from a point cloud using the pivoting ball function) which has been sharpened. It can write a .ply mesh file, however when visualizing it, its just a bunch of random triangles.

**To Reproduce**
  

1. Load point cloud:
  pcd = o3d.io.read_point_cloud(
        os.path.join(".ply") )

2. Convert point cloud into a mesh: 
    mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting (pcd,
                                        o3d.utility.DoubleVector([1,2,3,4]))
    print(np.asarray(mesh.vertices))
    print(np.asarray(mesh.triangles))
    mesh =  o3d.geometry.TriangleMesh.compute_triangle_normals (mesh)

3. Visual check if the mesh has been created properly:
    o3d.visualization.draw_geometries ([mesh])

4. Sharpening of the mesh
    mesh =  mesh.filter_sharpen(number_of_iterations=1, strength=0.005)

5. Saving of the sharpened mesh
    o3d.io.write_triangle_mesh(
        os.path.join(path, "meshes/", ".ply"), mesh)

6. Opening of the saved sharpened mesh
    mesh = o3d.io.read_triangle_mesh(
         os.path.join(path, "meshes",".ply") )
    o3d.visualization.draw_geometries([mesh])

**Expected behavior**
Open3D is able to properly load the point cloud, create the mesh and sharpen the mesh.
However, it is unable to properly save the sharpened mesh or read the not-properly saved mesh.

**Screenshots**
Screenshot of the sharpened mesh:
![mesh_after_sharpening](https://user-images.githubusercontent.com/57444293/68300892-001e3080-009f-11ea-944d-48d43462b0a5.png)

Screenshot of the experienced bug when loading a saved sharpened mesh:
![saved_sharpened_mesh](https://user-images.githubusercontent.com/57444293/68300929-17f5b480-009f-11ea-8ee1-74ecdb7b4afa.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Python version:3.6
 - Open3D version: 0.8.0
 - Is this remote workstation?:  no
 - How did you install Open3D?: pip 

**Additional context**
When saving the sharpened mesh the terminal outputs the following statement multiple times:
RPly: Failed writing green of vertex 56040 (binary output: uchar)
RPly: Failed writing red of vertex 56041 (binary output: uchar)
RPly: Failed writing blue of vertex 56056 (binary output: uchar)
RPly: Failed writing vertex_indices of face 0 (binary output: uchar)

As well as when opening the saved sharpened mesh:
RPly: Error reading 'vertex_indices' of 'face' number 93304
[Open3D WARNING] Read PLY failed: unable to read file:

Thanks a lot for your time!

**Comment by griegler** [comment]
There seems to be something wrong with writing the file, given the context it could be that the color values are problematic. Could you post the output of `print(np.asarray(mesh.vertex_colors))` before you write the mesh to ply.

**Comment by plevshad** [comment]
@griegler 
Thanks for taking a look so fast, adding print(np.asarray(mesh.vertex_colors)) before writing the mesh outputs the following matrices:

[[0.70033333 0.5404902  0.79892157]
 [0.70029412 0.54511765 0.83647059]
 [0.49335294 0.3644902  0.30741176]
 ...
 [0.20123529 0.12623529 0.05166667]
 [0.09029412 0.06664706 0.04298039]
 [0.06666667 0.04705882 0.05882353]]

The point cloud was created using EnSenso SDK, N35 camera. 
However, so far we haven't encounter any other problems with these point clouds.

**Comment by griegler** [comment]
Looks ok. Another check, does any attribute contain `NaN`, or `inf`? Could you show me the output of 

```python
print(np.all(np.isfinite(np.asarray(mesh.vertices))))
print(np.all(np.isfinite(np.asarray(mesh.vertex_colors))))
print(np.all(np.isfinite(np.asarray(mesh.vertex_normals))))
print(np.all(np.isfinite(np.asarray(mesh.triangles))))
```

**Comment by plevshad** [comment]
Hey @griegler ,
Sure no worries, running the code including again the `print(np.asarray(mesh.vertex_colors))`
and
```
print(np.all(np.isfinite(np.asarray(mesh.vertices))))
print(np.all(np.isfinite(np.asarray(mesh.vertex_colors))))
print(np.all(np.isfinite(np.asarray(mesh.vertex_normals))))
print(np.all(np.isfinite(np.asarray(mesh.triangles))))
```
Results in the following output at the terminal:
Mesh sharpening
[[0.70033333 0.5404902  0.79892157]
 [0.70029412 0.54511765 0.83647059]
 [0.49335294 0.3644902  0.30741176]
 ...
 [0.20123529 0.12623529 0.05166667]
 [0.09029412 0.06664706 0.04298039]
 [0.06666667 0.04705882 0.05882353]]
True
True
True
True

If it's handier for you, I can send as well the data set so you can test it !!

**Comment by griegler** [comment]
Yes, given that seems also to be correct, it would be great if you could share the data.

**Comment by plevshad** [comment]
@griegler ,
okey here is the data, the file named: window_int_02.ply is the original point cloud.
While the file named: mesh_window02_before_optimization01.ply is the erroneously saved saved mesh.

[window data test set.zip](https://github.com/intel-isl/Open3D/files/3820466/window.data.test.set.zip)

**Comment by griegler** [comment]
Ok, two things coming together here. After `filter_sharpen` the `vertex_colors` can get out of bounds `[0,1]`. However, `write_triangle_mesh` with ply as format expects that the color values are in that range, otherwise you get the warnings you see in your terminal.

A quick fix is to add
```python
mesh.vertex_colors = o3d.utility.Vector3dVector(
    np.clip(np.asarray(mesh.vertex_colors), 0, 1)
)
```
after the call to sharpen. You might want to re-normalize the normals, too.

I will submit a PR to fix the problem in writing meshes to ply soon.

**Comment by griegler** [comment]
#1306 should fix the problem.
