### ISSUE TITLE
How change the position of 3D object 

### ISSUE THREAD

**Issue by Resays** [intel-isl/Open3D#1304]
I have few objects in 3D generated from RGB + Depth image using create_rgbd_image_from_color_and_depth method

now I want to change the position of objects from one place to another like this
how can i move them to the left or right ?
![objts](https://user-images.githubusercontent.com/50095407/68394100-8fffcf80-01b0-11ea-8010-c6860f372ff5.JPG)

**Comment by griegler** [comment]
You can use [translate](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.translate) on the `PointCloud`. It also depends in which dimension you want to move it. For a visual help you could also display a coordinate frame, see [here](http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.create_coordinate_frame).

**Comment by Resays** [comment]
Thanks, let me try it first

**Comment by Resays** [comment]
Well, Basically i want to adjust the objects on its place like in the picture, objects (Books, Clock, Bottle) are in one objects.ply file and 2nd file is scene.ply, I want to place the objects in their place. looks like they are not on the right place, got it?

![Frame-12-with-objects](https://user-images.githubusercontent.com/50095407/68396754-69906300-01b5-11ea-9aa2-59352839359a.JPG)

**Comment by griegler** [comment]
As I already mentioned, you can use `translate`.
```python
pcd = o3d.io.read_point_cloud('objects.ply')
pcd.translate([x,y,z])
```
You have to figure out `x,y,z`, there is not really an automatic way to do that.

**Comment by Resays** [comment]
Yeah, i got the xyz points .. so should I do some addition or subtraction in x plan to move the objects from right to left ?
