### ISSUE TITLE
ImportError: /lib64/libm.so.6: version 'GLIBC_2.27' not found

### ISSUE THREAD

**Issue by ytyfeng** [intel-isl/Open3D#1307]
**ImportError: /lib64/libm.so.6: version 'GLIBC_2.27' not found**
When I tried to install Open3D from source on a ppc64le system, I was able to compile and install it using ```make```, but I wasn't able to import it and use it in Python because of a GLIBC issue. It seems that Open3D works for GLIBC versions up to 2.27 but not 2.28, since the GLIBC version is 2.28 on my system. 
**To Reproduce**
1. ```git clone --recursive https://github.com/intel-isl/Open3D```
2. ```cd Open3D; mkdir build; cd build```
3. ```cmake -DPYTHON_EXECUTABLE=`which python` -DCMAKE_INSTALL_PREFIX=~/ .. ```
4. ```make -j$(nproc) ```
5. ```make install-pip-package```
6. ```python -c "import open3d"``` 

**Expected behavior**
When I import Open3D in Python, it gives me this error: 
```
$ python -c "import open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.conda/envs/test/lib/python3.6/site-packages/open3d/__init__.py", line 35, in <module>
    from .open3d import * # py2 py3 compatible
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/.conda/envs/test/lib/python3.6/site-packages/open3d/open3d.cpython-36m-powerpc64le-linux-gnu.so)
```

**Environment:**
 - OS: CentOS 7, 
 - ppc64le architecture
 - Python version: 3.6
 - Open3D version: latest
 - Is this remote workstation?: yes
 - How did you install Open3D?: build_from_source
```
$ ldd --version
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.

$ gcc --version
gcc (GCC) 8.3.1 20190304 (Advance-Toolchain-at12.0) [revision 269374]
Copyright (C) 2018 Free Software Foundation, Inc.

```

**Additional context**
Additionally, is it possible to provide a conda package that can be used on ppc64le systems? Currently when I try to use conda to install Open3D, it cannot find the package that would work for my system. 
When I use ```conda install -c open3d-admin open3d```, it gives me this error: 
```
PackagesNotFoundError: The following packages are not available from current channels:

  - open3d
```

**Comment by SarahChane98** [comment]
Hi @ytyfeng have you solved the bug? I am having the same problem...

**Comment by ytyfeng** [comment]
> Hi @ytyfeng have you solved the bug? I am having the same problem...
Hi, @SarahChane98 
Are you using IBM’s ppcle64 system as well? 
Do you have this file? /opt/at12.0/lib64/ld64.so.2

For me, it was a dynamic linker problem.

**Comment by chenerg** [comment]
I met the same question after pip install, and I solved it by specifying a version.

`python -m pip install open3d==0.9`, and seems 1.0 is not compatible with my system.

**Comment by navid-mahmoudian** [comment]
Hello,
I have the same problem. Is there any better solution than downgrading to open3d 0.9? I also read somewhere that upgrading os my help, but neither of these solutions suits me because I am running my program on a cluster.

**Comment by ytyfeng** [comment]
What is your GLIBC version? 
```
ldd --version
```
Open3D requires GLIBC 2.27.

**Comment by ychechik** [comment]
on my server only open3d=0.8 works. this is his specs:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.2) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by ytyfeng** [comment]
Did you build from source? According to the documentation, the latest version requires Ubuntu 18.04+. http://www.open3d.org/docs/release/compilation.html#system-requirements

**Comment by yxlao** [comment]
Thanks @ytyfeng, yes this is expected. as mentioned in https://github.com/intel-isl/Open3D#python-quick-start:

Pre-built pip and conda packages support Ubuntu 18.04+, macOS 10.14+ and Windows 10 (64-bit) with Python 3.5, 3.6, 3.7 and 3.8. If you have other Python versions or operating systems, please compile Open3D from source.

**Comment by jinfagang** [comment]
@yxlao  Sad to say I build from source also got error:

```
[ 28%] Generating ../../../../bin/resources/colorMap.filamat
../../../../filament/src/ext_filament/bin/matc: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ../../../../filament/src/ext_filament/bin/matc)
cpp/open3d/visualization/gui/CMakeFiles/GuiResources.dir/build.make:96: recipe for target 'bin/resources/colorMap.filamat' failed
make[2]: *** [bin/resources/colorMap.filamat] Error 1
CMakeFiles/Makefile2:2098: recipe for target 'cpp/open3d/visualization/gui/CMakeFiles/GuiResources.dir/all' failed
make[1]: *** [cpp/open3d/visualization/gui/CMakeFiles/GuiResources.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by adizhol** [comment]
+1 ubuntu 16.04, build from source v0.11.0

**Comment by rchangj** [comment]
I ran into the same issue with version 0.13.0. I compiled the glib 2.27 and using LD_PRELOAD with open3d 0.13.0 and got "Segmentation fault"
Is there any solution for this issue?

**Comment by dichotomies** [comment]
> I ran into the same issue with version 0.13.0. I compiled the glib 2.27 and using LD_PRELOAD with open3d 0.13.0 and got "Segmentation fault"
> Is there any solution for this issue?

I've described a solution to this problem in [this post](https://github.com/mind/wheels/issues/7#issuecomment-1107649169). The part about `patchelf` is crucial to get it working.

I am now able to run Open3D 15.1 with CentOS 7.9.

**Comment by Changzhen17** [comment]
Hello,  I am having the same problem. Currently mine is 2.23. How do I upgrade to 2.27?
