### ISSUE TITLE
Access Data in "azure_kinect_viewer.py"

### ISSUE THREAD

**Issue by f-sh-f-sh** [intel-isl/Open3D#1326]
Hi, 

In the file "azure_kinect_viewer.py", how can I get access to data as a numpy array data. When I print out _rgbd_ in the code, I get the following:

```
Color image : 1280x720, with 3 channels.
Depth image : 512x512, with 1 channels.
Use numpy.asarray to access buffer data.
```

Using np.asarray(rgbd) also does not give the data. 

Thanks

**Comment by griegler** [comment]
Try `np.asarray(rgbd.color)` and `np.asarray(rgbd.depth)`.

**Comment by edwardnguyen1705** [comment]
Hi @griegler ,
if I use:
`im_d = np.asarray(rgbd.depth)`
`im_depth = im_d *255.0 / im_d.max()`
`cv2.imshow("azure kinect demo", im_depth)`
`cv2.waitKey(0)`

The image is black. But if I use the original `azure_kinect_viewer.py` both rgb and depth images are shown correctly. Do you have any suggestion?

**Comment by griegler** [comment]
not sure, but it might be that `cv2` assumes a different scaling for the specific `dtype`. You can try `import matplotlib.pyplot as plt; plt.imshow(im_d); plt.show();`. This should automatically normalize your depth.
