### ISSUE TITLE
RGBD_integration pose format in trajectory.log file

### ISSUE THREAD

**Issue by andreasmarxer** [intel-isl/Open3D#1340]
I currently started working with the rgbd_integration for generating a colored 3D mesh.
I did work with the example code and adapt it to my own dataset. At the point of generating the trajectory.log file with including the poses I got confussed.

In the documentation (http://redwood-data.org/indoor/fileformat.html) it is written that the transform should be from the camera to the world frame, the transform is: `[P_w; 1] = T_wc * [P_c; 1]`

But when doing so I got very bad results. Could it be that there is a fault in the documentation and on should use the inverse transfo from world to camera frame?
Because when doing so, I get better, but still not a really good 3d representation.

I read also about another user posting about this in the Discord chat, but no answers were provided. 
![image](https://user-images.githubusercontent.com/45263298/69428498-a0c44f80-0d31-11ea-882f-ef38ef6920c1.png)

Another question regarding the example pose format:
![image](https://user-images.githubusercontent.com/45263298/69428685-1e885b00-0d32-11ea-926e-21f666c3e76f.png)

Where is the origin of the world frame in the generated 3d mesh located?
It would make sense that it is at the first frame, therefore the first transform should have identity for rotation and no translation.But only the first rotation is identity, not the first translation.
So where is the origion of the world frame located in the example?

**Comment by germanros1987** [comment]
@syncle @qianyizh any ideas?

**Comment by theNded** [comment]
If you have bad results either way then there might be problems within other configurations. Can you please verify if the adaptation works for the official datasets such as stanford/lounge?

**Comment by andreasmarxer** [comment]
I will verify tomorrow that it works with the official datasets. Although also the dataset I recorded with ROS looks fine when visualized as DepthCloud in Rviz with a decay time of 10 frames.
What I already did is testing it with the 5 example images of the chair, there it worked perfectly fine!

And further, I don't have bad results either way. I have bad and not really satisfying results.
Interesting is that when I integrate 20 images, as mentioned it's not satisfying:
![image](https://user-images.githubusercontent.com/45263298/69444903-974adf80-0d51-11ea-88b5-479c66f26334.png)

When I do pack them in 4 groups of 6 (with overlapping), then the integration looks fine as shown for two examples: 
![image](https://user-images.githubusercontent.com/45263298/69445366-759e2800-0d52-11ea-96b8-c1b8a5b75c97.png)


Isn't this weird? What could be the issue for this?

**Comment by andreasmarxer** [comment]
> If you have bad results either way then there might be problems within other configurations. Can you please verify if the adaptation works for the official datasets such as stanford/lounge?

Do you mean this dataset? http://buildingparser.stanford.edu/dataset.html

The term adaption may have been somewhat misleading. I only adapted the RGB and Depth data paths and the Intrinsics, as opposed to the Example code!

**Comment by theNded** [comment]
Sorry for the confusion, this is not what I've mentioned. 
The dataset can be downloaded with [this script](https://github.com/intel-isl/Open3D/blob/master/examples/Python/ReconstructionSystem/scripts/download_stanford.sh) shipped with Open3D.

**Comment by andreasmarxer** [comment]
Thank you. In the meantime, I managed to solve the problem.
Indeed it was a problem within the poses I used.

Thank you very much for the help!

**Comment by theNded** [comment]
Cool, good luck!
