### ISSUE TITLE
Where is the definition of minimum_correspondence_ratio?

### ISSUE THREAD

**Issue by MaxChanger** [intel-isl/Open3D#1341]
Hello, I am trying to modify some of parameters of `o3d.odometry.compute_rgbd_odometry()` via `OdometryOption()`, in the official docs, I find the parameter - `minimum_correspondence_ratio`, but I can't find its definition in cpp and python. 

Can you provide some help, I guess it is currently a static value is fixed in the code.

![Selection_049](https://user-images.githubusercontent.com/35401968/69437118-9e87e280-0d7d-11ea-84dc-4886ca7cf4ac.png)

**Comment by theNded** [comment]
This should be a bug in the docs. The class does not contain this parameter, see https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Odometry/OdometryOption.h#L34

**Comment by theNded** [comment]
In the latest docs this option is not there:
http://www.open3d.org/docs/release/python_api/open3d.odometry.OdometryOption.html
Can you please provide the link to the incorrect doc?

**Comment by MaxChanger** [comment]
Thanks, I also did not find the relevant definition in this OdometryOption.h before.
So, how does `compute_rgbd_odometry`  return success and failure? If it is based on the overlap rate of two frames, then where is this part of the code implemented?

**Comment by theNded** [comment]
The relevent code is here:
https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Odometry/Odometry.cpp#L434

Basically, in each iteration we build a 6x6 linear system to solve for the pose. If this linear system is ill-posed, we regard it as a failure.

**Comment by szx0112** [comment]
The minimum_correspondence_ratio is still mentioned in this page:
[http://www.open3d.org/docs/release/tutorial/Basic/rgbd_odometry.html](http://www.open3d.org/docs/release/tutorial/Basic/rgbd_odometry.html)
