### ISSUE TITLE
convert_from_pinhole_camera_parameters does not work

### ISSUE THREAD

**Issue by yanghtr** [intel-isl/Open3D#1343]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I try to use  `set_intrinsics`  and `convert_from_pinhole_camera_parameters` to change the intrinsic of the camera, the example code is here
```
import numpy as np 
import open3d as o3d
vis = o3d.visualization.Visualizer()
vis.create_window('camera_view', 320, 240, 50, 50, False) # width, height, left, top, is_window_visible

fx = 115
fy = 115
ctr = vis.get_view_control()
init_param = ctr.convert_to_pinhole_camera_parameters()
# set initial intrinsic
cx = init_param.intrinsic.width / 2 - 0.5
cy = init_param.intrinsic.height / 2 - 0.5
init_param.intrinsic.set_intrinsics(init_param.intrinsic.width, 
    init_param.intrinsic.height, fx, fy, cx, cy)
print(init_param.intrinsic.intrinsic_matrix)

ctr.convert_from_pinhole_camera_parameters(init_param)
current_param = ctr.convert_to_pinhole_camera_parameters()
print(current_param.intrinsic.intrinsic_matrix)
```
And I get this result with the latest version of open3d (0.8.0.0):
```
[[115.    0.  159.5]
 [  0.  115.  119.5]
 [  0.    0.    1. ]]
[[120.    0.  159.5]
 [  0.  120.  119.5]
 [  0.    0.    1. ]]
```
It is strange that the focal length 115 is changed to a new number 120, and I don't know where it comes from. 

**To Reproduce**
just run the full code stated above

**Expected behavior**
The two output should be the same, which means the second should also prints a 115 focal length.

**Screenshots**
No

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: python 3.6
 - Open3D version: 0.8.0.0
 - Is this remote workstation?:  no
 - How did you install Open3D?: pip

**Additional context**
No

**Comment by pablospe** [comment]
Try with:

ctr.convert_from_pinhole_camera_parameters(init_param, **allow_arbitrary=True**)

See PR https://github.com/intel-isl/Open3D/pull/2564
Example (python): https://github.com/pablospe/open3D_depthmap_example

**Comment by ubt0001** [comment]
I have the same problem when using open3d==0.17.0 on python3.10. 
On version 0.16.0 `convert_from_pinhole_camera_parameters` seems to be working properly.

**Comment by cwreynolds** [comment]
@ubt0001 this may be related to a different issue, that `get_view_control()` has a bug in 0.17.0, see https://github.com/isl-org/Open3D/issues/6009 

There is a pending fix in https://github.com/isl-org/Open3D/pull/6116

**Comment by OSobky** [comment]
> I have the same problem when using open3d==0.17.0 on python3.10. On version 0.16.0 `convert_from_pinhole_camera_parameters` seems to be working properly.

I am facing the same problem with 0.17.0

**Comment by pablospe** [comment]
Fixed in https://github.com/isl-org/Open3D/pull/6116 (as noted by @cwreynolds)

**Comment by XunshanMan** [comment]
> I have the same problem when using open3d==0.17.0 on python3.10. On version 0.16.0 `convert_from_pinhole_camera_parameters` seems to be working properly.

I faced the same problem on open3d 0.17.0, where changing the open3d visualizer view is not working at all.
Then I use
```
pip install open3d==0.16
```
everything goes well.

**Comment by JennySeidenschwarz** [comment]
Using open3d 0.16.1 on mac and weirdly enough the extrinsic parameters are updated when accessing them with ```ctr.convert_to_pinhole_camera_parameters().extrinsic```, but the visualization itself does not change. Am I missing something? Do I need to feed back the view_control somehow to the visualizer?

**Comment by lpanaf** [comment]
> Using open3d 0.16.1 on mac and weirdly enough the extrinsic parameters are updated when accessing them with `ctr.convert_to_pinhole_camera_parameters().extrinsic`, but the visualization itself does not change. Am I missing something? Do I need to feed back the view_control somehow to the visualizer?

Having the same problem..
