### ISSUE TITLE
The Point Cloud is flipped

### ISSUE THREAD

**Issue by Bai426** [intel-isl/Open3D#1344]
Hi, I use one color image and depth image to generate a point cloud by "o3d.geometry.RGBDImage.create_from_color_and_depth()", then display with "o3d.visualization.draw_geometries()", but the model shows the point cloud is flipped. How can I handle this problem?
 
![image](https://user-images.githubusercontent.com/44070434/69498139-882f7300-0eb2-11ea-9667-960d2ec9c7cb.png)
![image](https://user-images.githubusercontent.com/44070434/69498146-8d8cbd80-0eb2-11ea-8375-44acebd000c3.png)
![image](https://user-images.githubusercontent.com/44070434/69498156-9b424300-0eb2-11ea-9c20-0fb575f7895f.png)

**Comment by theNded** [comment]
Can you please share the images and the intrinsic matrix?

**Comment by Bai426** [comment]
Hi, these are the image and depth image. I used a ZED camera to get left and right images, then the built-in program produce the depth. However, if I used the left and depth camera to create a 3D point cloud with the example of Open3D, but the point cloud seems flipped. I don't know why.

Best!
Mike
________________________________

**Comment by theNded** [comment]
I cannot see the attachments, can you please put a link somewhere?

**Comment by theNded** [comment]
Your depth image is stored in RGB format, which is not supported. Can you please first convert it to a 16bit 1 channel png with 1mm as the unit?

**Comment by Bai426** [comment]
Thank you. You are right, I need use right format for depth data. After I used 16-bit data, the 3D reconstruction is correct. Thanks again.
