### ISSUE TITLE
Examples for Hidden point Removal

### ISSUE THREAD

**Issue by pdhimal1** [intel-isl/Open3D#1346]
https://github.com/intel-isl/Open3D/pull/1144 added the ability to compute ConvexHull and also Hidden Point Removal Operator.

There was some discussion about adding an example to showcase the new functionality. Not sure if that ever materialized.

I wasn't able to call this function.

I read the point cloud data:
```
import numpy as np
import open3d as o3d

pcd = o3d.io.read_point_cloud("../data/data-master/tutorials/ism_test_michael.pcd")

#o3d.visualization.draw_geometries([pcd])
```
Visualization works fine.

When calling `pcd.hidden_point_removal(<viewpoint>, <radius>)`, I get:
```
open3d.open3d.geometry.PointCloud' object has no attribute 'hidden_point_removal
```
Also, in 1a72ecad632dfa4d79633da6cbe5c7388ddad292 why can't we return the remaining point (after applying the HPR operator) as a point cloud?

http://www.open3d.org/docs/latest/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.hidden_point_removal

**Comment by griegler** [comment]
An example is [here](https://github.com/intel-isl/Open3D/blob/master/examples/Python/Basic/hidden_point_removal.py).

**Comment by melhousni** [comment]
Where can I find this example? It seems like it was moved/deleted.

**Comment by griegler** [comment]
http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html#Hidden-point-removal

**Comment by melhousni** [comment]
Thank you for the link. 
I am trying to remove occluded points based on a 3d pose (x,y,z,yaw,pitch,roll), but i am not sure how to convert that into the camera and diameter parameters that the function uses. Any idea on how to do that?

**Comment by theUpsider** [comment]
any updates on @melhousni s question? Im struggeling to find that as well.

**Comment by wengzehang** [comment]
+1 Also struggling to this problem of how to convert it into the camera space.

**Comment by domef** [comment]
I'm having the same problem, I don't know how to convert the camera parameters.

**Comment by Hamza-Robotics** [comment]
Any updates on this regarding the camera parameters?

**Comment by s-suraj-08** [comment]
any updates on how to set the extrinsic and intrinsic parameters for the camera used

**Comment by areichel90** [comment]
camera and radius are documented in the cited paper here: https://dl.acm.org/doi/pdf/10.1145/1276377.1276407
