### ISSUE TITLE
camera coordinate system of visualization

### ISSUE THREAD

**Issue by yanghtr** [intel-isl/Open3D#1347]
I want to know the camera coordinate definition of `capture_depth_float_buffer`. I search the document and issue and find no place to mention it.  By drawing the world coordinate system frame, I know that the world coordinate system is x right, y up, -z forward (-z points to inner).
When I use the function `capture_depth_float_buffer` to capture depth, the depth is captured by a camera posed using the current view point. However, what is the camera coordinate? Is it a x right, y down, z forward camera?   Or some other camera coordinate system, such as x right, y up, z forward?

**Comment by theNded** [comment]
In computer vision, the conventional coordinate system is x right, y down, z forward. 
<pre>
    ^
   /
 z
/
--- x --->
|
y
|
v
</pre>
We consistently follow this convention in Open3D. 
OpenGL has a different convention, but we have handled the conversion in `capture_depth_buffer`. As long as you do not access this internal representation, you don't have to worry about it.
