### ISSUE TITLE
get_rotation_matrix_from_xyz  isn't in Open3d.geometry?

### ISSUE THREAD

**Issue by prass-anyvision** [intel-isl/Open3D#1351]
get_rotation_matrix_from_xyz(..)  isn't in Open3d.geometry?

Can't find that method. 

Examples refer to that : https://github.com/intel-isl/Open3D/blob/master/examples/Python/Basic/transformation.py

**Comment by griegler** [comment]
Right, `get_rotation_matrix_from_xyz()` is currently not exposed in `open3d.geometry`, only in `open3d.geometry.Geometry3D` and its sub-classes. For now you can use `open3d.geometry.Geometry3D.get_rotation_matrix_from_xyz()`.

**Comment by prass-anyvision** [comment]
Thanks - can I rotate with a rotation matrix or do I have to estimate euler angles or axis angles?

**Comment by griegler** [comment]
Once you have a rotation matrix, you can use it in the `rotate` methods. The functions `get_rotation_matrix_from_*` are just convenience functions to get a rotation matrix from different rotation representations.

**Comment by griegler** [comment]
#1355 exposes `get_rotation_matrix_from_*` in `open3d.geometry`.

**Comment by prass-anyvision** [comment]
That was fast!
