### ISSUE TITLE
Number of iterations

### ISSUE THREAD

**Issue by edwincasallas22** [intel-isl/Open3D#1352]
Hello
I'm working with point clouds taken with a Kinect. My goal is the total registration for 3D mapping of places or crops. I'm using the multiway registration code.

I'm wondering if there is a way to change the number of iterations of this code? I've seen that it only does 30 iterations by default.

**Comment by argosvr** [comment]
same question.. then following the topic.

**Comment by griegler** [comment]
Do you mean the number of iterations for pose graph optimization? If yes, you can look at the method `run_posegraph_optimization` in `optimize_posegraph.py`. There, the `o3d.registration.global_optimization` method takes a `o3d.registration.GlobalOptimizationConvergenceCriteria` as parameter. According to the [doc](http://www.open3d.org/docs/release/python_api/open3d.registration.GlobalOptimizationConvergenceCriteria.html#open3d.registration.GlobalOptimizationConvergenceCriteria), you can pass `max_iter` there.

**Comment by edwincasallas22** [comment]
> Do you mean the number of iterations for pose graph optimization? If yes, you can look at the method `run_posegraph_optimization` in `optimize_posegraph.py`. There, the `o3d.registration.global_optimization` method takes a `o3d.registration.GlobalOptimizationConvergenceCriteria` as parameter. According to the [doc](http://www.open3d.org/docs/release/python_api/open3d.registration.GlobalOptimizationConvergenceCriteria.html#open3d.registration.GlobalOptimizationConvergenceCriteria), you can pass `max_iter` there.

**Comment by edwincasallas22** [comment]
griegler
I am working with this code:
`# Open3D: www.open3d.org
# The MIT License (MIT)
# See license file or visit www.open3d.org for details

# examples/Python/Advanced/multiway_registration.py

import open3d as o3d
import numpy as np
import copy
from open3d import *

max_iter = 80
voxel_size = 0.02
radius_normal = voxel_size * 2
max_correspondence_distance_coarse = voxel_size * 15
max_correspondence_distance_fine = voxel_size * 1.5


def load_point_clouds(voxel_size=0.0):
    pcds = []
    for i in range(63):
       # pcd = o3d.io.read_point_cloud("../../TestData/ICP/robert_%d.pcd" % i)
       # pcd = o3d.io.read_point_cloud("../../TestData/ICP/degree_%d.pcd" % i)

        pcd = o3d.io.read_point_cloud("../../TestData/ICP/salaNoche/inputCloud%d.pcd" % i)
        pcd_down = pcd.voxel_down_sample(voxel_size=voxel_size)
        pcd_down.estimate_normals(o3d.geometry.KDTreeSearchParamHybrid(radius=radius_normal, max_nn=30))
        pcds.append(pcd_down)
    return pcds


def pairwise_registration(source, target):
    print("Apply point-to-plane ICP")
    source.estimate_normals(o3d.geometry.KDTreeSearchParamHybrid(radius = 0.05, max_nn = 30))
    target.estimate_normals(o3d.geometry.KDTreeSearchParamHybrid(radius = 0.05, max_nn = 30))

    icp_coarse = o3d.registration.registration_icp(
        source, target, max_correspondence_distance_coarse, np.identity(4),
        o3d.registration.TransformationEstimationPointToPlane())
    icp_fine = o3d.registration.registration_icp(
        source, target, max_correspondence_distance_fine,
        icp_coarse.transformation,
        o3d.registration.TransformationEstimationPointToPlane())
    transformation_icp = icp_fine.transformation
    information_icp = o3d.registration.get_information_matrix_from_point_clouds(
        source, target, max_correspondence_distance_fine,
        icp_fine.transformation)
    return transformation_icp, information_icp


def full_registration(pcds, max_correspondence_distance_coarse,
                      max_correspondence_distance_fine):
    pose_graph = o3d.registration.PoseGraph()
    odometry = np.identity(4)
    pose_graph.nodes.append(o3d.registration.PoseGraphNode(odometry))
    n_pcds = len(pcds)
    for source_id in range(n_pcds):
        for target_id in range(source_id + 1, n_pcds):
            transformation_icp, information_icp = pairwise_registration(
                pcds[source_id], pcds[target_id])
            print("Build o3d.registration.PoseGraph")
            if target_id == source_id + 1:  # odometry case
                odometry = np.dot(transformation_icp, odometry)
                pose_graph.nodes.append(
                    o3d.registration.PoseGraphNode(np.linalg.inv(odometry)))
                pose_graph.edges.append(
                    o3d.registration.PoseGraphEdge(source_id,
                                                   target_id,
                                                   transformation_icp,
                                                   information_icp,
                                                   uncertain=False))
            else:  # loop closure case
                pose_graph.edges.append(
                    o3d.registration.PoseGraphEdge(source_id,
                                                   target_id,
                                                   transformation_icp,
                                                   information_icp,
                                                   uncertain=True))
    return pose_graph


if __name__ == "__main__":

    o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Debug)
    pcds_down = load_point_clouds(voxel_size)
    o3d.visualization.draw_geometries(pcds_down)

    print("Full registration ...")
    pose_graph = full_registration(pcds_down,
                                   max_correspondence_distance_coarse,
                                   max_correspondence_distance_fine)

    print("Optimizing PoseGraph ...")
    option = o3d.registration.GlobalOptimizationOption(
        max_correspondence_distance=max_correspondence_distance_fine,
        edge_prune_threshold=0.25,
        reference_node=0)
    o3d.registration.global_optimization(
        pose_graph, o3d.registration.GlobalOptimizationLevenbergMarquardt(),
        o3d.registration.GlobalOptimizationConvergenceCriteria(max_iteration = max_iter), option)

    print("Transform points and display")
    for point_id in range(len(pcds_down)):
        print(pose_graph.nodes[point_id].pose)
        pcds_down[point_id].transform(pose_graph.nodes[point_id].pose)
    o3d.visualization.draw_geometries(pcds_down)

    print("Make a combined point cloud")
    pcds = load_point_clouds(voxel_size)
    pcd_combined = o3d.geometry.PointCloud()
    for point_id in range(len(pcds)):
        pcds[point_id].transform(pose_graph.nodes[point_id].pose)
        pcd_combined += pcds[point_id]
    pcd_combined_down = pcd_combined.voxel_down_sample(voxel_size=voxel_size)
    o3d.io.write_point_cloud("multiway_registration.pcd", pcd_combined_down)
    o3d.visualization.draw_geometries([pcd_combined_down])`

This code has 30 iterations by default. What I want are more iterations to improve the 3D mapping of my point clouds.

But I don't know how to do this. I've searched everywhere and haven't found the best way. You could help me?

**Comment by edwincasallas22** [comment]
griegler
I am working with this code [http://www.open3d.org/docs/release/tutorial/Advanced/multiway_registration.html](url)


This code has 30 iterations by default. What I want are more iterations to improve the 3D mapping of my point clouds.

But I don't know how to do this. I've searched everywhere and haven't found the best way. You could help me?

**Comment by griegler** [comment]
As already stated above, you have to add `max_iter=100`, or whatever value you like to `o3d.registration.GlobalOptimizationConvergenceCriteria` in `run_posegraph_optimization`.
