### ISSUE TITLE
Octree.create_from_point_cloud ends in segmentation fault

### ISSUE THREAD

**Issue by agrodet** [intel-isl/Open3D#1359]
Hello, I'm a new user of Open3D, and I like it very much but I'm facing an issue with octrees.

**Describe the bug**
When running octree.create_from_point_cloud() on a point cloud that I read from a custom PCD format, my script ends in Segmentation fault: 11

**To Reproduce**
0. `myfile.pcd` header is as follows
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z normal_x normal_y normal_z custom1 custom2 custom3 custom4 custom5
SIZE 4 4 4 4 4 4 4 4 4 4 4
TYPE F F F F F F F F U F F
COUNT 1 1 1 1 1 1 1 1 1 1 1
WIDTH 862983
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 862983
DATA binary_compressed
```
1. Run the following script
```
import open3d as o3d
pcd = o3d.io.read_point_cloud("myfile.pcd")
octree = o3d.geometry.Octree(8)
octree.convert_from_point_cloud(pcd)
```
2. The script crashes -> Segmentation fault: 11

**Expected behavior**
I've tried running the same code by replacing `myfile.pcd` by the `fragment.pcd` file available as an example in Open3D. The convertion works and I can visualize it without any issue. So I expect this piece of code to work with my custom file.

**Environment (please complete the following information):**
 - OS: MacOS Catalina 10.15.1
 - Python version: 3.7.3
 - Open3D version: github master branch November 27
 - Is this remote workstation?: no
 - How did you install Open3D?: built from source as indicated on http://www.open3d.org/docs/release/compilation.html

**What I have tried**
Having a custom format, and a DATA binary_compressed, I tried to write the point cloud into a file and re-read it before running convert_from_point_cloud(pcd) so I have a more "standard" format
```
pcd = o3d.io.read_point_cloud("myfile.pcd")
o3d.io.write_point_cloud("Test.pcd", pcd)
test = o3d.io.read_point_cloud("Test.pcd")
octree = o3d.geometry.Octree(8)
octree.convert_from_point_cloud(test)
```
-> No success

I also tried to reduce the number of points -> No success

However, no problem occurs when using a voxel_grid
```
pcd = o3d.io.read_point_cloud("myfile.pcd")
voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(pcd, 0.01)
octree = o3d.geometry.Octree(8)
octree.create_from_voxel_grid(voxel_grid)
o3d.visualization.draw_geometries([octree])
```

**Comment by pcaudal** [comment]
Hello,
Firstly, thanks for your great job on Open3D (0.9.0) (Python 3.7).

I have the same issues with the same tests and more, because problems occurs when I try to test:
```
pcd = o3d.io.read_point_cloud("myfile.pcd")
voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(pcd, 0.01)
octree = o3d.geometry.Octree(8)
octree.create_from_voxel_grid(voxel_grid)
o3d.visualization.draw_geometries([octree])
```
where VoxelGrid.create_from_point_cloud seems not implemented...
If you are interested, I can send you my pcd file.

Regards
