### ISSUE TITLE
Errors occurred after "cmake -DBUILD_EIGEN3=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON -DBUILD_JSONCPP=ON -DBUILD_PNG=ON  .."

### ISSUE THREAD

**Issue by zengletian1491** [intel-isl/Open3D#1368]
Open3D installation on the Ubuntu 16.04LTS.

1)Pybind11 was installed correctly with the following commands:
cmake ..
make
sudo make install

2)Then node and npm were installed correctly with the following commands:
sudo apt install nodejs-legacy
sudo apt install npm

3) However, at the stage of installing Open3D, errors occurred with the following command:
cmake -DBUILD_EIGEN3=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON -DBUILD_JSONCPP=ON -DBUILD_PNG=ON  ..

the detailed information is as follows:
**Open3D-master/build$ cmake -DBUILD_EIGEN3=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON -DBUILD_JSONCPP=ON -DBUILD_PNG=ON  ..**
-- No CMAKE_BUILD_TYPE specified, default to Debug
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Open3D 0.8.0.0
-- Compiling on Unix
-- Disable RealSense since it is not fully supported on Linux.
-- Using installed OpenMP 
CMake Warning (dev) at /usr/local/share/cmake-3.15/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  3rdparty/CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python3.5 (found version "3.5.2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- Building EIGEN3 from source (BUILD_EIGEN3=ON)
-- Building GLEW from source (BUILD_GLEW=ON)
-- Building GLFW from source (BUILD_GLFW=ON)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using X11 for window creation
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Building JSONCPP from source (BUILD_JSONCPP=ON)
-- Building LIBPNG from source (BUILD_PNG=ON)
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Building libjpeg-turbo from source (BUILD_JPEG=ON)
-- Building libjpeg-turbo from source
-- Looking for a ASM_NASM compiler
-- Looking for a ASM_NASM compiler - NOTFOUND
-- NASM assembler not found - libjpeg-turbo performance may suffer
**CMake Error at /usr/local/share/cmake-3.15/Modules/ExternalProject.cmake:2611 (message):
  No download info given for 'ext_turbojpeg' and its source directory:

   /home/zeng/SoftwareExtractPackages/Open3D-master/3rdparty/libjpeg-turbo/libjpeg-turbo

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE**
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/ExternalProject.cmake:3204 (_ep_add_download_command)
  3rdparty/libjpeg-turbo/libjpeg-turbo.cmake:45 (ExternalProject_Add)
  3rdparty/CMakeLists.txt:170 (include)

**-- Building PYBIND11 from source (BUILD_PYBIND11=ON)
CMake Error at 3rdparty/CMakeLists.txt:187 (add_subdirectory):
  The source directory

    /home/zeng/SoftwareExtractPackages/Open3D-master/3rdparty/pybind11

  does not contain a CMakeLists.txt file.**

-- Building TINYFILEDIALOGS from source
-- Building tinyobjloader from source
-- Building QHULL from source
CMake Warning (dev) at /usr/local/share/cmake-3.15/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  src/Open3D/CMakeLists.txt:60 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Open3D;glew;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;dl;/usr/lib/x86_64-linux-gnu/libX11.so;glfw;/usr/lib/x86_64-linux-gnu/libGL.so;turbojpeg;jsoncpp;png;zlib;tinyfiledialogs;tinyobjloader;qhullcpp;qhullstatic_r
-- Replacing glfw with glfw3
-- Open3D;glew;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;dl;/usr/lib/x86_64-linux-gnu/libX11.so;glfw3;/usr/lib/x86_64-linux-gnu/libGL.so;turbojpeg;jsoncpp;png;zlib;tinyfiledialogs;tinyobjloader;qhullcpp;qhullstatic_r
-- Using Python executable: /usr/bin/python3.5
-- npm found at: /usr/bin/npm. Jupyter support will be enabled.
-- ENABLE_JUPYTER is set to ON
-- Using Python version: 3.5
-- Using Python version major: 3
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- PYPI_PACKAGE_NAME: open3d
-- Configuring incomplete, errors occurred!
**See also "/home/zeng/SoftwareExtractPackages/Open3D-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/zeng/SoftwareExtractPackages/Open3D-master/build/CMakeFiles/CMakeError.log".**

Could you please give me a hand?Thanks very much!

**Comment by theNded** [comment]
Please make sure to use `git clone --recursive https://github.com/intel-isl/Open3D` to clone all the submodules.

Also, it will be more helpful to highlight the errors instead of asking the developers to look for them.

**Comment by oseh** [comment]
> Please make sure to use `git clone --recursive https://github.com/intel-isl/Open3D` to clone all the submodules.
> 
> Also, it will be more helpful to highlight the errors instead of asking the developers to look for them.

hey I have used git clone and i am still getting the same issue

**Comment by imbible** [comment]
Same issue in Release 0.9.0. I downloaded the zip and tried to compile. It prompts error at 3rdparty/libjpeg-turbo.
