### ISSUE TITLE
MacOS: Cannot save screen capture to file

### ISSUE THREAD

**Issue by aj96** [intel-isl/Open3D#1371]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I would like to make a video of point clouds using open3d visualization, but whenever I run the open3d visualization, it is impossible to write anything to file. plt.imsave, plt.savefig, cv2.imwrite, etc., all cannot write to file, even if the data I am trying to write to file is not the open3d visualization.

**To Reproduce**
Below is some minimal code to reproduce the issue. No matter how I played around with this code, I could not get it to write to file.
```
    vis = o3d.visualization.Visualizer()
    vis.create_window(visible=True)
    vis.add_geometry(pcd)

    vis.run()
    image = np.asarray(vis.capture_screen_float_buffer(do_render=True)).copy()
    vis.destroy_window()
    image *= 255
    image = image.astype(np.uint8)
    cv2.imwrite("image.png", image)
```

**Expected behavior**
Should be able to write image to file.

**Environment (please complete the following information):**
 - OS: OSX Mojave
 - Python version: 3.7.3
 - Open3D version: 0.7.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Comment by syncle** [comment]
Could you [check out this example](http://www.open3d.org/docs/release/tutorial/Advanced/customized_visualization.html#capture-images-in-a-customized-animation)?

**Comment by germanros1987** [comment]
With the new visualization module, this problem is solved.
