### ISSUE TITLE
WinAPI macro 'max' make conflict with std::max in RenderOption.h

### ISSUE THREAD

**Issue by WraithKim** [intel-isl/Open3D#1372]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When including Win32-related header file in C++ project using Open3D, there is compile error *Expected identifier*. (Maybe it is right, because my visual studio is non-english)  
I think this bug came out from macro `#define max...` in Win32-related header.

**To Reproduce**
I try to include `combaseapi.h` so...
1. In visual studio, create any sample c++ project that has dependency with Open3D.
2. Include `combaseapi.h` and `Open3D/Open3D.h` , then compile it.
3. See error

**Expected behavior**
There are several compile error from `RenderOption.h`. And when you open the file, you can see red underline at `std::max`, `std::min` and so on.

**Screenshots**
![캡처](https://user-images.githubusercontent.com/7982279/70023891-2373c700-15dc-11ea-84b2-ccc55640071e.PNG)
This is a header file in my sample project.
``` c++
#include <omp.h>
#include <CorError.h>
#include <combaseapi.h>
#include <Open3D/Open3D.h>
#include <Open3D/Registration/FastGlobalRegistration.h>
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version:
 - Open3D version: 0.7.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: Visual studio 2019

**Additional context**
I just report about it, because I didn't find any related issue with it. So if this is a known issue, then please close it.

**Comment by ssheorey** [comment]
Hi @WraithKim you should be able to work around this by including the Open3D headers before the Windows headers ("combaseapi.h").  See here for advice on header include order:
https://stackoverflow.com/a/2762596
