### ISSUE TITLE
Read XYZ failed

### ISSUE THREAD

**Issue by tjnewton** [intel-isl/Open3D#1379]
**Describe the bug**
While attempting to read an XYZ file Open3D generates an error. Each line of the input file contains three values separated by commas, e.g., 694386.212,5155487.512,381.036. There are 5000 lines in the file. File attached below. 

**To Reproduce**
1. import open3d as o3d
2. pcd = o3d.io.read_point_cloud('test.txt',format='xyz')
3. See error: [Open3D WARNING] Read XYZ failed: unable to open file: test.txt

**Expected behavior**
Expected point cloud to be read into pcd.

**Environment (please complete the following information):**
 - OS: OSX Mojave 10.14.6
 - Python version: 3.6.9
 - Open3D version: 0.8.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: conda install -c open3d-admin open3d

[test.txt](https://github.com/intel-isl/Open3D/files/3924245/test.txt)
![open3d](https://user-images.githubusercontent.com/54011699/70253490-2b487e00-1738-11ea-92fe-5d3c75687d7d.png)

**Comment by griegler** [comment]
The error indicates, that you might have specified the wrong path to the file.
Further, xyz expects that the values are separated by one space, not commas.

**Comment by tjnewton** [comment]
After changing the delimiter to spaces the error goes away (can you state the space delimiter requirement in the documentation?), but the dataset does not plot properly with o3d.visualization.draw_geometries([pcd]). It appears only as a small read square (attached above).

**Comment by griegler** [comment]
Might be this problem: https://github.com/intel-isl/Open3D/issues/1197
Should be gone, if you compile the source from the master branch.

**Comment by QinZiwen** [comment]
http://www.open3d.org/docs/release/tutorial/Basic/file_io.html tall me that each line contains [x, y, z], where x, y, z are the 3D coordinates of read format xyz. The separator I understand is "," but it's actually a space. Is it necessary to modify here？

**Comment by stefangachter** [comment]
Yes, indeed, documentation is confusing in this regard. My assumption was as well that delimiter is comma not single space. Please update documentation or make it. Another suggestion, make header "skipable" not only for pts format. Thnaks!

**Comment by briandrye** [comment]
Please update the documentation and provide an example that shows the spacing. Thanks.

**Comment by briandrye** [comment]
Please update the documentation and provide an example that shows the spacing. Thanks.

**Comment by suijunqiang** [comment]
@tjnewton 
in my case, I read PointCloud with 0 points when calling the o3d.io.read_point_cloud.

**Comment by suijunqiang** [comment]
@tjnewton 
you are right changing the delimiter to spaces the error goes away! ahhhhhh.....

**Comment by molihub** [comment]
I get the same reslut: PointCloud with 0 points.
