### ISSUE TITLE
3rdparty fmt version problem

### ISSUE THREAD

**Issue by libChan** [intel-isl/Open3D#1382]
**Describe the bug**
Trying to build from source on windows, I got error "could not open file fmt/time.h in Open3D\Utility\Console.cpp". Checking [fmt release](https://github.com/fmtlib/fmt/releases), I found time.h has been removed since version 6.0.0.

> Removed deprecated fmt/time.h. Use fmt/chrono.h instead.

So I manually edit it and build successfully. May be better to fix it? (my personal view)

**Comment by theNded** [comment]
Could you please try `git --recursive clone` instead of downloading it alone? The bundled fmt lib version in `3rdparty` is 5.3.0.
