### ISSUE TITLE
Read PTS failed: unable to read header

### ISSUE THREAD

**Issue by fthou** [intel-isl/Open3D#1384]
When I tried to load .pts files, it failed and post

```
[Open3D WARNING] Read PTS failed: unable to read header.
geometry::PointCloud with 0 points.
```

My code is as follows:
```
import numpy as np
import open3d as o3d
import os

if __name__ == "__main__":

    print("Load a pts point cloud, print it, and render it")
    path_name = r'D:\data\shapenetcore_partanno_segmentation_benchmark_v0\02691156\points'
    file_name = '1a32f10b20170883663e90eaf6b4ca52.pts'
    pf = os.path.join(path_name, file_name)
    pcd = o3d.io.read_point_cloud(pf)
    print(pcd)
```

Could you help me with this?

Thank you very much!

**Comment by griegler** [comment]
Hard to tell what the problem is without seeing the file. Could you provide it?

**Comment by fthou** [comment]
Yes. The .ptx file can not be attached here. Could you download it from here:
https://drive.google.com/open?id=1fwO_KIXvUpyniny4_7ntVoy3uTLeOxvf

Thank you very much.

**Comment by fthou** [comment]
I succeeded with np.loadtxt. I think you can include this case that the .ptx file has no header into the package open3d.

**Comment by zyoungDL** [comment]
> I succeeded with np.loadtxt. I think you can include this case that the .ptx file has no header into the package open3d.

Could you tell how to include this case?
