### ISSUE TITLE
How do you render camera previews / images in Open3D?

### ISSUE THREAD

**Issue by nickponline** [intel-isl/Open3D#1385]
I am trying to render a number of cameras positions with a preview of what each camera sees using textured quads in Open3D. 

But I can't see if this is possible. All I can see in the docs is `o3d.geometry.Image` but that just renders an image without letting me position and orient it in the scene. Ideally I'd like to render an image on a quad and position and rotate.

**Comment by nickponline** [comment]
I want to do something like this:

![image](https://user-images.githubusercontent.com/590151/70382842-97cda380-1917-11ea-8cf1-f80286e52f37.png)

**Comment by griegler** [comment]
I do not think it is possible with `Image`, but you could use a textured mesh (#1194) for the image part and then draw the camera frame with a `LineSet`.

**Comment by nickponline** [comment]
Thanks I used a triangle mesh for each and it works. Would be nice to enable double sides rendering somehow but not a big deal. Closing

**Comment by ShougangShen** [comment]
> Thanks I used a triangle mesh for each and it works. Would be nice to enable double sides rendering somehow but not a big deal. Closing

Hello, I want to render like yours. I use triangle mesh with texture and it works. But when the number of elements (image texture) increasing, the open3d won't response and can't display. I I'd like to know how you do it？Could you please tell me? It's better to have a code demo. Thanks!
