### ISSUE TITLE
Manifold detection algorithm does not identify inverted triangles

### ISSUE THREAD

**Issue by sam598** [intel-isl/Open3D#1386]
**Describe the bug**

None of the manifold detection tools are able to identify an inverted face as manifold geometry. However the function to create a "half triangle mesh" from a "triangle mesh" fails if the source mesh has an inverted face, and says that the mesh is not manifold.

**To Reproduce**

This line:
`half_triangle_mesh = o3d.geometry.HalfEdgeTriangleMesh.create_from_mesh(triangle_mesh)`

Results in:
`RuntimeError: Converting mesh to half-edge mesh filed, not manifold`

These functions report 0 non-manifold edges and vertices, and that the mesh is vertex and edge manifold:
```
triangle_mesh.get_non_manifold_vertices()
triangle_mesh.get_non_manifold_edges(allow_boundary_edges=True)
triangle_mesh.is_vertex_manifold()
triangle_mesh.is_edge_manifold(allow_boundary_edges=True)
```

**Expected behavior**
1) "is_edge_manifold" should return false if a "triangle mesh" cannot be converted into a "half triangle mesh".

2) "remove_non_manifold_edges" should remove edges that have adjacent triangles with opposite winding directions (as opposed to opposite normal directions).

3) Maybe there needs to be a function to fix inverted faces? Or an "is_face_manifold" function?

**Screenshots**

Here is a simplified example mesh showing the offending triangle.

<img width="548" alt="Screen Shot 2019-12-08 at 11 54 04 AM" src="https://user-images.githubusercontent.com/10446449/70395425-58ed2b80-19b3-11ea-8738-71c23ee0ad66.png">

This is just an example to illustrate the issue. An actual mesh may have 1 flipped face out of 1000 that is impractical to manually find and fix.

**Comment by griegler** [comment]
The problem in the mesh is not really related to its manifold, but with the orientation.
There are already functions like `IsOrientable` and `OrientTriangles`, what might be missing is a function that returns a list of inverted faces. Is this what you are looking for?

**Comment by sam598** [comment]
Yup "OrientTriangles" fixes that issue. It wasn't initially clear to me what the intent of that function was.
