### ISSUE TITLE
Textured OBJs render without the texture. 

### ISSUE THREAD

**Issue by nickponline** [intel-isl/Open3D#1387]
**Describe the bug**

Textures for .OBJ files not rendering:

**To Reproduce**
1. Download the example obj, mtl, jpg from http://paulbourke.net/dataformats/obj/minobj.html
2. Run this code:

```
mesh = o3d.io.read_triangle_mesh("capsule.obj", print_progress=True)
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh])
```

**Expected behavior**
A textured mesh.

**Screenshots**
I only get an untextured mesh:
![image](https://user-images.githubusercontent.com/590151/70474225-0e3ce380-1a87-11ea-84c7-4e8927d7e9c9.png)

Not console errors, and all files are in the root with the python script. 
I have tried other OBJ files with textures too and can't get any to work with the texture.

**Environment (please complete the following information):**
 Python3, Mac OSX (Catalina), Open3D 0.8

**Comment by griegler** [comment]
Did you compile from source? Open3D 0.8 does not include the ability to handle textured mesh, this was added later.

**Comment by nickponline** [comment]
No, what's the best way to get the latest version in Python?

**Comment by nickponline** [comment]
Works when built from source:

![image](https://user-images.githubusercontent.com/590151/70480301-3a129600-1a94-11ea-831e-6644de73ec13.png)

**Comment by daranday** [comment]
We need to reopen this issue. The exact same problem happens with 0.12.0.0 but 0.10.0.0 works, on Mac Catalina.
