### ISSUE TITLE
Matrix vs Isometry

### ISSUE THREAD

**Issue by seath49** [intel-isl/Open3D#139]
I noticed that Eigen::Matrix4d is used through out the code (when it represents a rigid transformation, Eigen::Isometry3d should be used). In the current library state it is not a big performance / precision drawback. In the future, it could pose a disadvantage e.g. when calling .inverse().

**Comment by syncle** [comment]
That's good point. Can you contribute to replace ``Eigen::Matrix4d``? The issue need to consider is in [py3d_eigen.cpp](https://github.com/IntelVCL/Open3D/blob/master/src/Python/py3d_eigen.cpp) as the matrix buffer is directly copied to 4x4 numpy matrix.

**Comment by seath49** [comment]
I will try to find some time next week. I don't use the library, so can't commit much time to it. But I appreciate the effort of making actually usable lib, compared to the big one. Keep it light :)

**Comment by syncle** [comment]
No problem. Another reason is that some transformation in Open3D deals with scale changes. See point-to-point ICP in [TransformationEstimation.cpp](https://github.com/IntelVCL/Open3D/blob/master/src/Core/Registration/TransformationEstimation.cpp). Isometry3d consists of rotation and translation component, so it cannot express scaling factor.

**Comment by qianyizh** [comment]
Good point about performance and precision. I think it is fine for now. But if anyone is motivated, feel free to take the token and make a PR.
