### ISSUE TITLE
Can you get mouse clicked x, y on the visualizer?

### ISSUE THREAD

**Issue by nickponline** [intel-isl/Open3D#1391]
Is there a way to simple get the mouse clicked `x, y` on the visualizer and set a callback to run on that.

**Comment by prewettg** [comment]
You can inherit from Visualizer (or one of its descendants) and override
open3d::visualization::MouseButtonCallback().  You can see an example of
how you could use this at open3d::visualization::VisualizerWithEditing.

Cheers,
Geoff Prewett
