### ISSUE TITLE
[Open3D WARNING] Read OBJ failed: Cannot open file

### ISSUE THREAD

**Issue by aycameric** [intel-isl/Open3D#1394]
Hi,

I am trying to read an .obj file and convert it to a point cloud, but I get the Error that the .obj file can't be read. I created the .obj file from a .stl file in FreeCAD. How can I check if there is an issue with the .obj file or is there another way to solve this? Can I also read a .stl file and convert the mesh to a triangle mesh object? Thank you.

My code is this:
tmesh=o3d.io.read_triangle_mesh("~/Desktop/models/megablock.obj") #here it throws the error
meshpcl = tmesh.sample_points_poisson_disk(1000, 100, None)
o3d.visualization.draw_geometries([meshpcl])

**Comment by griegler** [comment]
What is the error that is thrown?

**Comment by aycameric** [comment]
This one: [Open3D WARNING] Read OBJ failed: Cannot open file

**Comment by griegler** [comment]
can you share the file, would be easier to debug.

**Comment by aycameric** [comment]
The .obj file type is not supported to be posted in here but the content looks like this, if it helps:

# Created by FreeCAD <http://www.freecadweb.org>
v 0.000000 0.500001 0.000000
v 0.000000 0.500001 55.500000
v 0.000000 63.000000 0.000000
v 0.000000 63.000000 55.500000
v 0.007600 0.413176 0.000000
v 0.007600 0.413176 55.500000
v 0.007600 0.500001 55.586823

**Comment by griegler** [comment]
Have you checked that you pass a valid path to `o3d.io.read_triangle_mesh`? The error message indicates that you path points to no valid `obj` file.

**Comment by aycameric** [comment]
The absolute path "~/Desktop/models/megablock.obj" should be ok, shouldn't it? The file exists in the folder..

**Comment by griegler** [comment]
Try to replace `~` with the path to the home dir. It could be that the symbol for some reason is not resolved.

**Comment by aycameric** [comment]
That was indeed the problem, it is working now.. thanks a lot!
