### ISSUE TITLE
Loading colored meshes (not just textured meshes)

### ISSUE THREAD

**Issue by sammo2828** [intel-isl/Open3D#1398]
**Is your feature request related to a problem? Please describe.**
I tried to load and draw a mesh in o3d but the colors didn't show. The mesh's materials, which contain color and other information are not supported.
Looks like there was a recent feature to load textured meshes (with only one texture), but colored meshes are not supported. Also, colored vertexes are supported, but colored triangles are not yet supported.

**Describe the solution you'd like**
Support textured and colored meshes.

**Describe alternatives you've considered**
Since vertex colors are already supported, it may be possible to extract vertex colors from the mesh and then convert meshes into multiple repeated triangles, to color individual faces, but that's really a bad idea!

**Comment by griegler** [comment]
Sorry, I do not fully understand your feature request, or what you mean with colored meshes. Do you want to have support for colored triangles? And what file format are you referring to for I/O?

**Comment by sammo2828** [comment]
Yes, this is about support for colored triangles, AND support for file formats that have colored triangles.

Try this model that I converted from https://www.blender.org/download/demo-files/

[bmw.zip](https://github.com/intel-isl/Open3D/files/3965545/bmw.zip)

![image](https://user-images.githubusercontent.com/1911995/70870345-4774d680-1fe6-11ea-8916-9bcbeff11c30.png)

**Comment by theNded** [comment]
1. This model stores quad mesh, which is not yet supported in o3d afaik.
2. This MTL file stores **lighting** rather than **triangle color**. We do not have mature lighting support in the current version, but a team is working on refactoring everything for visualization. This feature may be supported later.
