### ISSUE TITLE
What is the difference between AxisAlignedBoundingBox and OrientedBoundingBox?

### ISSUE THREAD

**Issue by prass-anyvision** [intel-isl/Open3D#1403]
When I rotate my cloud arbitarily, the axis aligned bounding box changes it's vertices with respect to the point cloud, but oriented bounding box does not. 

I am unable to understand how, or why, and in general, what is the difference. Could you help me out?

**Comment by griegler** [comment]
Both bounding boxes encapsulate your geometry. `AxisAlignedBoundingBox` as the same suggest is aligned with the x,y,z axis. If you visualize it, the lines will always align with the coordinate system. On the other hand `OrientedBoundingBox` has a rotation, so it is not aligned with the coordinate system, but could more tightly fit the geometry. Right now, the oriented bounding box is computed via PCA, which is far from optimal, hence, does not produce the tightest possible fit.

**Comment by prass-anyvision** [comment]
Thanks, makes a lot of sense!

So  does this hold valid then ? The axis I refer to are the "oriented" axes then.
```
box_points[0, :] - box_points[1, :]  # x_axis
box_points[0, :] - box_points[2, :]  # y_axis
box_points[0, :] - box_points[3, :] # z_axis
```

Also, are there other methods for the bounding box fit? I could perhaps implement something if it's required.

**Comment by griegler** [comment]
To get the rotated axis, you could just use the rotation matrix member of `OrientedBoundingBox` and rotate the vector by it, e.g., in Python `box.R @ np.array([1,0,0]).reshape(3,1)`.

There are exact and approximate algorithms. For a start, you can have a look [here](https://en.wikipedia.org/wiki/Minimum_bounding_box_algorithms#Three_dimensions).
