### ISSUE TITLE
In get_oriented_bounding_box().get_box_points(), what are the connectivity of the points?

### ISSUE THREAD

**Issue by prass-anyvision** [intel-isl/Open3D#1404]
Which points are connected to which points?

I have this that I saw in the c++ Implementation :- 
```
points[0] = center_ - x_axis - y_axis - z_axis;
points[1] = center_ + x_axis - y_axis - z_axis;
points[2] = center_ - x_axis + y_axis - z_axis;
points[3] = center_ - x_axis - y_axis + z_axis;
points[4] = center_ + x_axis + y_axis + z_axis;
points[5] = center_ - x_axis + y_axis + z_axis;
points[6] = center_ + x_axis - y_axis + z_axis;
points[7] = center_ + x_axis + y_axis - z_axis;
```

I can reconstruct the axes from these equations but I don't know what they mean. An extension to #1403

**Comment by griegler** [comment]
To see which points get connected, you can have a look [here](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Geometry/LineSetFactory.cpp#L84).
