### ISSUE TITLE
How to crop point clouds/meshes using the new crop function in 0.9.0?

### ISSUE THREAD

**Issue by ytyfeng** [intel-isl/Open3D#1410]
I've noticed that Open3D has changed some of the functions quite a bit in the new 0.9.0 release. In previous versions, the geometry.PointCloud.crop() function takes in min_bound and max_bound, but in the 0.9.0 version it takes in two bounding boxes. What does the second bounding box do?
I don't think the documentation is very clear for the crop function. It says both of the two arguments of the function are AxisAlignedBoundingBox.  http://www.open3d.org/docs/latest/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.crop

**Comment by ArashJavan** [comment]
+1

**Comment by griegler** [comment]
You can have a look at `examples/Python/Basic/bounding_volume.py`.  The steps are (1) creating a bounding box ` bbox = o3d.geometry.AxisAlignedBoundingBox(min_bound=(-30, 0, -10), max_bound=(10, 20, 10))` and (2) using it to crop `geom.crop(bbox)`.

**Comment by nickponline** [comment]
@griegler This doesn't work for meshes with textures, it removes the textures.
