### ISSUE TITLE
How to create a open3d.pointcloud using x,y,z  in numpy format?

### ISSUE THREAD

**Issue by JimXu1989** [intel-isl/Open3D#1415]
Hello,
I want to know how to create a open3d.pointcloud using x,y,z  in numpy format?

I have search the document, but I didn't find relative information

Thanks a lot!

**Comment by theNded** [comment]
```python
import open3d as o3d
import numpy as np
pcd = o3d.geometry.PointCloud()
# Change rand(1000, 3) to whatever xyz you want to convert
pcd.points = o3d.utility.Vector3dVector(np.random.rand(1000, 3).astype(np.float64))
o3d.visualization.draw_geometries([pcd])
```

**Comment by JimXu1989** [comment]
> ```python
> import open3d as o3d
> import numpy as np
> pcd = o3d.geometry.PointCloud()
> # Change rand(1000, 3) to whatever xyz you want to convert
> pcd.points = o3d.utility.Vector3dVector(np.random.rand(1000, 3).astype(np.float64))
> o3d.visualization.draw_geometries([pcd])
> ```

Thanks for reply!
Could you show me how could I also add color information (r,g,b) in the 3D data which in numpy format?
