### ISSUE TITLE
RegistrationICP: double free or corruption (out)

### ISSUE THREAD

**Issue by chenshida** [intel-isl/Open3D#1416]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I use RegistrationICP to match two point cloud, and it raise error like this:
double free or corruption (out)

**To Reproduce**
my code as follows:
```
auto o3d_cloud_model = std::make_shared<open3d::geometry::PointCloud>();
auto o3d_cloud_prematch = std::make_shared<open3d::geometry::PointCloud>();
# read cloud ...
# before ICP registration, show point cloud first
open3d::visualization::DrawGeometries({o3d_cloud_model, o3d_cloud_prematch}, "PointCloud", 1600, 900);
# begin ICP match, and here will rasie error
auto registration_result = open3d::registration::RegistrationICP(
            *o3d_cloud_model, *o3d_cloud_prematch, 50, Eigen::Matrix4d::Identity(),
                open3d::registration::TransformationEstimationPointToPoint(false),
                open3d::registration::ICPConvergenceCriteria(0.0000001, 0.0000001, 100)
    );
```

**Expected behavior**
the code will terminal in icp match, and print info like this:
double free or corruption (out)
Aborted (core dumped)

**Screenshots**
before ICP match, cloud visualization like this
![cloud_show](https://user-images.githubusercontent.com/26617742/71497105-b2999500-2891-11ea-83a6-9c9bebf1900c.png)
and error here:
![error_log](https://user-images.githubusercontent.com/26617742/71497124-c1804780-2891-11ea-949f-ea83d74c3218.png)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Python version: python3.6
 - Open3D version: 0.0.7
 - Is this remote workstation?: yes
 - How did you install Open3D?: for python, use pip install, for c++ use gcc build
**Additional context**
for the same point cloud data, I use python run RegistrationICP and set same param, and it work well, so ,why c++ will cause this problem, and how can I fix it.

**Comment by shuochen365** [comment]
I also had the same mistake. Have you solved it？

**Comment by chenshida** [comment]
I create a new file and paste code, rebuild it and than it work well. but I don`t  know why create new file can solve this problem.

**Comment by shuochen365** [comment]
Thank you very much.
 Can you share your code and data？I want to test it on my side.

**Comment by chenshida** [comment]
give me you email address, i`ll send you in my free time.

**Comment by shuochen365** [comment]
I have finished Python version.Thank you very much.
