### ISSUE TITLE
Configurable FOV max and min

### ISSUE THREAD

**Issue by pablospe** [intel-isl/Open3D#1427]
In file [ViewControl.cpp#L36](https://github.com/intel-isl/Open3D/blob/fab6441b763b4964ef898cbb3fae8d10ef98442f/src/Visualization/Visualizer/ViewControl.cpp#L36):
> const double ViewControl::FIELD_OF_VIEW_MAX = 90.0;

I was wondering why there is a strict max for the FOV.

As example, one could need to render a depth map from a mesh using the headless rendering example, but such strict limit would restrict the possible camera parameters that can be rendered. More precisely, I am using ConvertFromPinholeCameraParameters and this limitation happens in [ViewControl.cpp#L36](https://github.com/intel-isl/Open3D/blob/fab6441b763b4964ef898cbb3fae8d10ef98442f/src/Visualization/Visualizer/ViewControl.cpp#L36)

> field_of_view_ =
>             std::max(std::min(fov_rad * 180.0 / M_PI, FIELD_OF_VIEW_MAX),
>                      FIELD_OF_VIEW_MIN);

Same for the zoom control, but there is already one issue for this purpose: issue #497

**Comment by pablospe** [comment]
Related issues: #1417 and #1389

**Comment by pablospe** [comment]
To made it work I commented some code, something like this: https://github.com/pablospe/Open3D/commit/206f92641945fe24731b173801a6d29d1a839d6b

Recompile Open3D (and if you want the python wrapper):
```
cd build/
make install-pip-package -j16
pip3 install lib/python_package/pip_package/open3d-0.8.0.0-cp36-cp36m-linux_x86_64.whl
```

**Comment by radmahdi** [comment]
> To made it work I commented some code, something like this: [pablospe@206f926](https://github.com/pablospe/Open3D/commit/206f92641945fe24731b173801a6d29d1a839d6b)

I am afraid this  just ignores the assert function, and the parameters are not really taking into account!

**Comment by germanros1987** [comment]
@pablospe this is solved in the new version rendering API.

**Comment by pablospe** [comment]
From what I see there is not a way to render to an image or depthmap with the current API (the equivalent to `capture_depth_float_buffer`). Also the option to use intrinsic/extrinsic matrix to control the view.

Based on this replies:
https://github.com/intel-isl/Open3D/issues/2190#issuecomment-713555104
https://github.com/intel-isl/Open3D/issues/2190#issuecomment-713622044

Do you have more information about it?

Also I recently pushed a PR https://github.com/intel-isl/Open3D/pull/2564, which allows this with the old viewer.
