### ISSUE TITLE
Window cannot be closed during non-blocking visualization in Python

### ISSUE THREAD

**Issue by mirkoGschwindt** [intel-isl/Open3D#1432]
When running the non_blocking_visualization.py example in Python, it is not possible to close the window during the process by clicking the x button in the top right corner. Is there a way to get around that issue?

1. Run non_blocking_visualization.py
2. Try to close the window

**Expected behavior**
I expected the currently open window to close.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.7.5
 - Open3D version: 0.8.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Comment by mths2601** [comment]
I am facing a similar problem. Is there any way to check whether the window has been closed while the loop for non-blocking visualization is running? 
Thanks

**Comment by mirkoGschwindt** [comment]
I solved the problem by putting poll_events() in an if clause like this:

if not vis.poll_events():
     break

**Comment by mths2601** [comment]
That solved it for me, too. Thanks a lot!

**Comment by syncle** [comment]
Thanks @mirkoGschwindt

**Comment by addriumruss** [comment]
Problem solved. Thanks much @mirkoGschwindt !

**Comment by LuBuJin** [comment]
解决了，赞了

**Comment by cwreynolds** [comment]
It was a similar question that led me to look in the doc, then report https://github.com/isl-org/Open3D/issues/6076 (“Visualizer.poll_events() — documentation missing important details”)
