### ISSUE TITLE
why the point clouds are not required for optimization ?

### ISSUE THREAD

**Issue by pyni** [intel-isl/Open3D#1444]
Hi, i still have a question.
In your demo:

    print("Optimizing PoseGraph ...")
    option = GlobalOptimizationOption(
            max_correspondence_distance = max_correspondence_distance_fine,
            edge_prune_threshold = 0.25,
            reference_node = 0)
    global_optimization(pose_graph,
            GlobalOptimizationLevenbergMarquardt(),
            GlobalOptimizationConvergenceCriteria(), option)
And graph is defined as :

pose_graph.nodes.append(PoseGraphNode(np.linalg.inv(odometry)))
pose_graph.edges.append(PoseGraphEdge(source_id, target_id,
transformation_icp, information_icp, uncertain = False))

It seems that, the whole optimization process requires no point clouds as input. I can hardly understand it.  Could you please explain it? i am a new learner for this area.

**Comment by syncle** [comment]
With your transformation matrix, the information matrix can tell you what is the approximate L2 error. For more details, please see: http://redwood-data.org/indoor/registration.html
