### ISSUE TITLE
Aure Kinect and IMU

### ISSUE THREAD

**Issue by argosvr** [intel-isl/Open3D#1445]
I'm using the new Azure Kinect and can get interesting results but open3d uses the Azure Kinect is just used as an images recorder. Is it possible to use the IMU to get more precises results ? It could be used also with the DR400 realsense with IMU ..
Do you have any projects about using IMU data ?

**Comment by anuj0707** [comment]
There is the possible option of using the ROS package for Azure Kinect 
https://github.com/microsoft/Azure_Kinect_ROS_Driver
But to use it with Open3D you will have to convert the ROS PointCloud2 data to open3D format

**Comment by kaixin-bai** [comment]
https://github.com/ykoneee/k4a-python

**Comment by Sudoki** [comment]
I'm using a realsense 435i and I will definitely want to use IMU data to help with registration. Would be really useful to have an example using existing odometry :)
