### ISSUE TITLE
Expose python binding for SetGlobalColorMap()

### ISSUE THREAD

**Issue by prerakmody** [intel-isl/Open3D#1458]
**Context**
The [Visualization tutorials webpage](http://www.open3d.org/docs/release/tutorial/Basic/visualization.html#rendering-styles) shows how some keypress combinations can change the color map of the point cloud (_Shift + 0/1/2/3/4_)

**Requirement**
Is there a way to call this [_SetGlobalColorMap()_](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Visualization/Visualizer/VisualizerCallback.cpp#L249) function via python? I would like to do this via code and not via a key press. I am specifically interested in the [Gray Color Map](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Visualization/Utility/ColorMap.cpp#L63)

Other References
- [Enum defining all the color maps](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Visualization/Utility/ColorMap.h#L38)

**Comment by syncle** [comment]
That's actually a good suggestion. @qianyizh what do you think? Do we have a reason to not to expose these functions?

**Comment by qianyizh** [comment]
No, we should expose them for interface parity.

**Comment by germanros1987** [comment]
In Open3D 0.11, using the new rendering module, you can specify any colormap you like. You can see an example of this here: https://github.com/intel-isl/Open3D-ML/blob/master/examples/visualize.py

**Comment by Leerw** [comment]
@germanros1987  it is complicated, can we expose this api to python?
