### ISSUE TITLE
Support for Intel realsense SR305 RGBD images ?

### ISSUE THREAD

**Issue by devshank3** [intel-isl/Open3D#1462]
Dear Open3D officials / Users ,

Tried to implement SR305 RGBD images acquired through the same realsense capture script (examples/Python/ReconstructionSystem/sensors/realsense_recorder.py).

successfully  recorded the RGBD dataset and executed the reconstruction pipeline , but the end result was not perfect and even fragment creation was not properly done and left out with sparse reconstruction 

1 . Anybody successfully implemented SR305 with Open3D recons pipeline ?
2.  Any alignment issues with the code as it is structured coded light ?

**Comment by syncle** [comment]
Have you got a luck to find a solution? I think you need to use custom intrinsic parameters to get successful reconstruction.

**Comment by devshank3** [comment]
Hi @syncle i was not able to find a way around.

I used the intrinsic.json generated by the recorder script , but noting happened.

I doubt the depth format , if im not wrong 
Is there some thing with the format
because in **D435i** depth data the near objects are darker and in **SR305** depth data near was greyish farther was dark.

I also raised a issue in intel realsense official repo

https://github.com/IntelRealSense/librealsense/issues/5761

Also i see lot of issues with respect to the depth format wrt **SR305**

Please any help from the community is welcomed  and thank you

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by devshank3** [comment]
Thanks @germanros1987  @syncle 

I will post the question on forum

Closing this issue

**Comment by devshank3** [comment]
![image](https://user-images.githubusercontent.com/52159502/156760509-bb4f8f57-760e-4589-8089-90f838b29066.png)


This issue is fixed https://github.com/IntelRealSense/librealsense/releases/tag/v2.47.0
