### ISSUE TITLE
surface reconstruction poisson vs python 2.7

### ISSUE THREAD

**Issue by PerspectivesLab** [intel-isl/Open3D#1463]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
F strings are not implemented for python 2.7, all demos working with F string for python 3.6 are not working

**To Reproduce**
1. cd 'examples\Python\Advanced'
2. python surface_reconstruction_poisson.py
3. F strings are not implemented for python 2.7 => please change your documentation

**Expected behavior**
surface_reconstruction_poisson.py should work with python 2.7 as specified in the docs

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX Mojave, Ubuntu 16.04, Windows 10.0]
 - Python version:
 - Open3D version:
 - Is this remote workstation?: yes or no
 - How did you install Open3D?: pip or conda or build_from_source (provide build method, such as GCC, Xcode, Visual Studio, and so on)

**Additional context**

**Comment by syncle** [comment]
Umm, I cannot see any f-strings in the aforementioned script. @griegler, could have you look?

**Comment by griegler** [comment]
No, I checked all the surface_reconstruction_*.py files and did not find any f-strings. @PerspectivesLab did you had another file in mind?
