### ISSUE TITLE
azure_kinect_recorder.py --> RuntimeError: logger with name 'k4a_logger' already exists 

### ISSUE THREAD

**Issue by martinakos** [intel-isl/Open3D#1467]
If I run the azure_kinect_recorder.py I can see the view with the rgb and depth images. 
The moment I press [SPACE] to start, I get "RuntimeError: logger with name 'k4a_logger' already exists". This happens in this line:  self.recorder.open_record(self.filename)

Any ideas why this happens?

I mostly wanted to use the recorder because I've read in  #1183 that's the only way of finding the camera intrinsics.

**Comment by SeanStephensenAIRM** [comment]
Have you tried using the SDK's built in k4arecorder.exe through command line? This does not solve the actual issue, but should help you get an .mkv recording with less hassle if it's possible on your system.

**Comment by ez4lionky** [comment]
I met the same problem on Ubuntu 16.04 :(

**Comment by yxlao** [comment]
Hi, this issue should have been resolved in the latest Open3D (with Ubuntu 18.04+ or Windows). Please create a new PR if the issue still occurs.
