### ISSUE TITLE
Support reading and writing of arbitrary properties

### ISSUE THREAD

**Issue by chrisranderson** [intel-isl/Open3D#1468]
**Is your feature request related to a problem? Please describe.**
We would like to use open3d to store labeled point cloud data, but in order to store the label of the data, we would have to store each class in a separate file, or associate a second file with the point cloud to store labels for regression outputs.

**Describe the solution you'd like**
I'd like an interface like this:
```python
property_name = 'class'
numpy_array_of_values = np.zeros((len(point_cloud.points), 1))
point_cloud.write_property(property_name, numpy_array_of_values)
point_cloud.read_property(property_name)
```

**Describe alternatives you've considered**
Store each class in a separate file, or associate a second file with the point cloud to store labels for regression outputs. You would have to make sure the order of the points was the same.

**Additional context**
We're using the PLY format for point clouds - I'm pretty sure the format itself supports arbitrary properties.

**Comment by chrisranderson** [comment]
Related:
https://github.com/intel-isl/Open3D/issues/1086: this is a generalization of that
https://github.com/intel-isl/Open3D/issues/1002: this is a feature request, not a question

**Comment by griegler** [comment]
We are currently working on refactoring the code to support CUDA. In addition to that, we already planned that the geometry classes will get associated properties exactly for the purposes as you described. You can look at the gpu branch for progress on that.

**Comment by chrisranderson** [comment]
Great, thank you!

**Comment by prewettg** [comment]
@chrisranderson This isn't my area of expertise, but I believe that open3d.t.geometry.PointCloud already supports properties. I think you can do:
```
def makeTensor(np_array, copy=False):
    if copy or not np_array.data.c_contiguous:
        return o3d.core.Tensor(np_array)
    else:
        return o3d.core.Tensor.from_numpy(np_array)

tcloud.point["nameOfProp"] = makeTensor(property_data_as_nparray)
```

Does this solve your problem?

**Comment by chrisranderson** [comment]
Maybe 🙂I'm actually at a new job now so "my" problem has been "solved" haha. If you would like to keep this issue open as a suggestion, that's fine. If you'd like to close it, that's fine too.
