### ISSUE TITLE
Add function to VisualizerWithEditing to return points selected using rectangle or polygon select

### ISSUE THREAD

**Issue by tristanheywood** [intel-isl/Open3D#1482]
**Is your feature request related to a problem? Please describe.**
Currently `VisualizerWithEditing` has a function `get_picked_points`, which returns the indexes of points that have been picked using the gui. `VisualizerWithEditing` supports selecting points by dragging a rectangle or creating a polygon, however there is currently no way for user code to access these selected points. 

**Describe the solution you'd like**
I propose adding a function `get_selected_points`, which works similarly to `get_picked_points` but returns the indexes of the points in the selection rectangle or selection polygon. I have created a possible implementation of such a function on a fork: https://github.com/tristanheywood/Open3D/compare/master...tristanheywood:point_selection 
If you guys are happy with this implementation I will submit a PR. 

**Describe alternatives you've considered**
We could also use a callback function. When the user makes a selection the callback would be called with the indexes of the selected points and the `Visualizer` object. But this might get messy given there is already an animation callback. 

**Additional context**
My use case for this is building a simple tool for labelling pointclouds. The function would allow me to select a bunch of points and assign them to a class. I have created a simple test for my implementation of `get_selected_points` below. Any points selected using the gui will be coloured a shade of red. 

```
# <create pcd>
vis = VisualizerWithEditing()
vis.create_window()
vis.add_geometry(pcd)

def cb(v):
    idx = v.get_selected_points()
    # get_selected_points returns an empty list unless there is an active selection
    if len(idx) > 0: 
        np.asarray(pcd.colors)[idx] *= np.array([1, 0, 0])
        v.update_geomety()

vis.register_animation_callback(cb)
vis.run()
```

**Comment by griegler** [comment]
You may want to have a look at [`VisualizerWithVertexSelection`](http://www.open3d.org/docs/release/python_api/open3d.visualization.VisualizerWithVertexSelection.html#open3d.visualization.VisualizerWithVertexSelection).

**Comment by tristanheywood** [comment]
![open3d_selector](https://user-images.githubusercontent.com/17230594/73589955-01fc6200-44dd-11ea-8ecb-2f44d1318f09.gif)
This is what I'd like to be able to do - use the `SelectionPolygon` to select multiple points and access the indexes of these points in Python, so I can for example, change the colour. 

I made this using the `get_selected_points` function I implemented on my fork.

**Comment by griegler** [comment]
Actually, you can also draw a rectangle in `VisualizerWithVertexSelection` to select multiple vertices at once. 
https://github.com/intel-isl/Open3D/pull/1390

**Comment by tristanheywood** [comment]
Ahh ok, sorry, I didn't see that. 

`VisualizerWithVertexSelection` only selects points which are not obscured, so it doesn't quite fit my use-case. I'm working with aerial lidar data and I want to be able to e.g. select a tree by looking from directly above and dragging a rectangle around it. `VisualizerWithVertexSelection` would only select the canopy, since the other points will be obscured. Potentially I could get around this by making the point size as small as possible, but it's not ideal.

**Comment by griegler** [comment]
I see. Maybe @prewettg knows a solution to that problem.

**Comment by prewettg** [comment]
`VisualizerWithVertexSelection` intentionally only selects visible vertices, although if selected all vertices is a common use case we could add a key to toggle it. However, if you comment out lines 374-381 (the section bookended by the `glColorMask()` calls) it will select all vertices. We pick vertices by drawing all the points with a unique color and then reading the color buffer back and undoing the color to get the index of the point. In order to not pick the points on the back side we have to draw the mesh to the depth buffer so that when we draw the points the ones on the back side fail the depth buffer test. But if you simply don't draw the mesh into the depth buffer, all the vertices will get drawn into the picking buffer. Note that if one point is exactly behind another, though, it will still not get picked, and there's not a lot we can do about that.

**Comment by FarahSaeed** [comment]
Hi Is this feature available in current version. I am trying to access the selected volume or points from python.

**Comment by kaustubh-shrotri** [comment]
Why is `VisualizerWithVertexSelection` returning list of PickedPoint objects and not the List of Int like the `VisualizerWithEditing`?

This is what I am getting when I am using the `get_picked_points()` function.

`[<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FC70>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FCB0>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FCF0>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FD30>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FD70>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FDB0>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FDF0>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FE30>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FE70>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FEB0>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FEF0>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FF30>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FF70>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471FFB0>, 
<open3d.cpu.pybind.visualization.PickedPoint object at 0x00000233D471C030>]`

How to retrieve the point indices or the points itself from these objects?

**Comment by ArchakGoel** [comment]
Also need this feature!

**Comment by ParvezAlam123** [comment]
class NonBlockVisualizer:
    def __init__(self, point_size=1, background_color=[0, 0, 0]):
        self.__visualizer = o3d.visualization.Visualizer()
        self.__visualizer.create_window()
        opt = self.__visualizer.get_render_option()
        opt.background_color = np.asarray(background_color)
        opt = self.__visualizer.get_render_option()
        opt.point_size = point_size

        self.__pcd_vis = o3d.geometry.PointCloud()
        self.__initialized = False
        
        
        
     
         
        
        
        
        
    
    def add_bounding_box(self, center, length, width, height, orientation):
       # Define the vertices of the bounding box
       vertices = np.asarray([
             [length/2, width/2, height/2],
             [-length/2, width/2, height/2],
             [-length/2, -width/2, height/2],
             [length/2, -width/2, height/2],
             [length/2, width/2, -height/2],
             [-length/2, width/2, -height/2],
             [-length/2, -width/2, -height/2],
             [length/2, -width/2, -height/2]])

       # Rotate the vertices based on the orientation
       R = np.array([[np.cos(orientation), -np.sin(orientation), 0],
                  [np.sin(orientation), np.cos(orientation), 0],
                  [0, 0, 1]])
       vertices = vertices @ R.T

       # Translate the vertices to the center of the bounding box
       vertices = vertices + center

       # Define the edges of the bounding box
       edges = np.array([[0, 1], [1, 2], [2, 3], [3, 0],
                      [4, 5], [5, 6], [6, 7], [7, 4],
                      [0, 4], [1, 5], [2, 6], [3, 7]])

       # Create the LineSet geometry
       line_set = o3d.geometry.LineSet()
       line_set.points = o3d.utility.Vector3dVector(vertices)
       line_set.lines = o3d.utility.Vector2iVector(edges)

       # Set the colors of the edges
       colors = [[1, 0, 0] for i in range(len(edges))]
       line_set.colors = o3d.utility.Vector3dVector(colors)
       
       return line_set 
       
       
    

    def update_renderer(self, pcd, bb_list, wait_time=0):
        self.__pcd_vis.points = pcd.points
        self.__pcd_vis.colors = pcd.colors
        
        
        
        if not self.__initialized:
            self.__initialized = True
            self.__visualizer.add_geometry(self.__pcd_vis)
            
          
            for dim_of_bb in bb_list:
               line_set = self.add_bounding_box(dim_of_bb[0], dim_of_bb[1], dim_of_bb[2], dim_of_bb[3], dim_of_bb[4])
               self.__visualizer.add_geometry(line_set)
               lines.append(line_set)    
        else:
            self.__visualizer.update_geometry(self.__pcd_vis)
            
            for i in range(len(lines)):
               self.__visualizer.remove_geometry(lines[i])
               
            lines.clear()
            
            
            for dim_of_bb in bb_list:
               line_set = self.add_bounding_box(dim_of_bb[0], dim_of_bb[1], dim_of_bb[2], dim_of_bb[3], dim_of_bb[4])
               self.__visualizer.add_geometry(line_set)
               lines.append(line_set)
               
               
           
        self.__visualizer.poll_events()
        self.__visualizer.update_renderer()
        
       
        
        
        if wait_time > 0:
            time.sleep(wait_time)
            
In the above code , I am not able to use mouse for zoom in or zoom out. Can anyone help ?

**Comment by ParvezAlam123** [comment]
class NonBlockVisualizer:
    def __init__(self, point_size=1, background_color=[0, 0, 0]):
        self.__visualizer = o3d.visualization.Visualizer()
        self.__visualizer.create_window()
        opt = self.__visualizer.get_render_option()
        opt.background_color = np.asarray(background_color)
        opt = self.__visualizer.get_render_option()
        opt.point_size = point_size

        self.__pcd_vis = o3d.geometry.PointCloud()
        self.__initialized = False
        
        
        
     
         
        
        
        
        
    
    def add_bounding_box(self, center, length, width, height, orientation):
       # Define the vertices of the bounding box
       vertices = np.asarray([
             [length/2, width/2, height/2],
             [-length/2, width/2, height/2],
             [-length/2, -width/2, height/2],
             [length/2, -width/2, height/2],
             [length/2, width/2, -height/2],
             [-length/2, width/2, -height/2],
             [-length/2, -width/2, -height/2],
             [length/2, -width/2, -height/2]])

       # Rotate the vertices based on the orientation
       R = np.array([[np.cos(orientation), -np.sin(orientation), 0],
                  [np.sin(orientation), np.cos(orientation), 0],
                  [0, 0, 1]])
       vertices = vertices @ R.T

       # Translate the vertices to the center of the bounding box
       vertices = vertices + center

       # Define the edges of the bounding box
       edges = np.array([[0, 1], [1, 2], [2, 3], [3, 0],
                      [4, 5], [5, 6], [6, 7], [7, 4],
                      [0, 4], [1, 5], [2, 6], [3, 7]])

       # Create the LineSet geometry
       line_set = o3d.geometry.LineSet()
       line_set.points = o3d.utility.Vector3dVector(vertices)
       line_set.lines = o3d.utility.Vector2iVector(edges)

       # Set the colors of the edges
       colors = [[1, 0, 0] for i in range(len(edges))]
       line_set.colors = o3d.utility.Vector3dVector(colors)
       
       return line_set 
       
       
    

    def update_renderer(self, pcd, bb_list, wait_time=0):
        self.__pcd_vis.points = pcd.points
        self.__pcd_vis.colors = pcd.colors
        
        
        
        if not self.__initialized:
            self.__initialized = True
            self.__visualizer.add_geometry(self.__pcd_vis)
            
          
            for dim_of_bb in bb_list:
               line_set = self.add_bounding_box(dim_of_bb[0], dim_of_bb[1], dim_of_bb[2], dim_of_bb[3], dim_of_bb[4])
               self.__visualizer.add_geometry(line_set)
               lines.append(line_set)    
        else:
            self.__visualizer.update_geometry(self.__pcd_vis)
            
            for i in range(len(lines)):
               self.__visualizer.remove_geometry(lines[i])
               
            lines.clear()
            
            
            for dim_of_bb in bb_list:
               line_set = self.add_bounding_box(dim_of_bb[0], dim_of_bb[1], dim_of_bb[2], dim_of_bb[3], dim_of_bb[4])
               self.__visualizer.add_geometry(line_set)
               lines.append(line_set)
               
               
           
        self.__visualizer.poll_events()
        self.__visualizer.update_renderer()
        
       
        
        
        if wait_time > 0:
            time.sleep(wait_time)
            
In the above code , I am not able to use mouse for zoom in or zoom out. Can anyone help ?
