### ISSUE TITLE
Where is "compute_point_cloud_to_point_cloud_distance"?

### ISSUE THREAD

**Issue by hzxie** [intel-isl/Open3D#1490]
The developers change API every release!!
I cannot find "compute_point_cloud_to_point_cloud_distance" anymore.

SO ANGRY!!!!!

**Comment by hzxie** [comment]
BTW, the search function in the docs page is not working at all!!
![Screen Shot 2020-02-04 at 11 28 26 AM](https://user-images.githubusercontent.com/1730504/73711347-7fc0a780-4741-11ea-812f-6937cd9d3d9e.png)

**Comment by hzxie** [comment]
Moved to "http://www.open3d.org/docs/0.8.0/python_api/open3d.geometry.PointCloud.html" since 0.8.0.

**Comment by Hammania689** [comment]
Thanks mate for the posting the solution. This should probably be put in the documentation?

**Comment by MengHao666** [comment]
> Moved to "http://www.open3d.org/docs/0.8.0/python_api/open3d.geometry.PointCloud.html" since 0.8.0.

I don't know clearly what do u mean. How can I use such function again?

**Comment by vra** [comment]
> > Moved to "http://www.open3d.org/docs/0.8.0/python_api/open3d.geometry.PointCloud.html" since 0.8.0.
> 
> I don't know clearly what do u mean. How can I use such function again?

I guess this may be the solution but I didn't check the results:

old style:
```python
foo = o3d.geometry.PointCloud()
bar = o3d.geometry.PointCloud()
distance = o3d.compute_point_cloud_to_point_cloud_distance(foo, bar)
```

new style:
```python
foo = o3d.geometry.PointCloud()
bar = o3d.geometry.PointCloud()
distance = foo.compute_point_cloud_distance(bar)
```
