### ISSUE TITLE
extract 3D geometric shapes from point cloud

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [intel-isl/Open3D#1502]
Curious to know if we can extract/detect 3d shapes from a point cloud. ex - give a point cloud can we extract all cone, spears, and plans from it and also get its location in 3d space.

**Comment by griegler** [comment]
Open3D contains [`segment_plane`](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.segment_plane) that might be applicable. For other shapes a similar method needs to be implemented.

**Comment by xiaodongww** [comment]
Sorry to reopen this issue, I also want to know is there any progress in shape detection.

@griegler `segment_pane` seems only to segment the largest plane.  Does open3d support general plane detection? 

For other shapes, (e.g. cone, spears, plans), is there any open box to use? I just found this paper and [the relevant code](https://github.com/alessandro-gentilini/Efficient-RANSAC-for-Point-Cloud-Shape-Detection). I am not sure if it is the best way to detect basic geometric shapes and was wonder if there any useable libraries.

> Ruwen Schnabel, Roland Wahl, Reinhard Klein. Efficient RANSAC for Point-Cloud Shape Detection. Comput. Graph. Forum 26(2): 214-226 (2007).

Any suggestion will be helpful. Thanks!
