### ISSUE TITLE
Convert own features into Feature()

### ISSUE THREAD

**Issue by BlankCheng** [intel-isl/Open3D#1503]
Dear Open3D users.

Hello! May I ask how to convert my own point-wise features(2048*128) into open3d type `Fearure()` to do RANSAC? I haven't found an API or similar issues, sorry to bother(.

**Comment by germanros1987** [comment]
@syncle any hints?

**Comment by BlankCheng** [comment]
I find the solution, just write:
`o3d_feat = o3d.Feature()
o3d_feat = own_feat.T`
