### ISSUE TITLE
Select_down_sample blocks update_geometry

### ISSUE THREAD

**Issue by richardrl** [intel-isl/Open3D#1506]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Using `select_down_sample` gets you a downsampled pointcloud. However, this pointcloud does not work with the visualizer. calls to visualizer.update_geometry(downsampled_pcd) do not have any effect; only the initial pointcloud is shown in the visualizer.

**To Reproduce**
`    downsampled_pcd = pcd.select_down_sample(plane_idxs, invert=True)

while True:
            vis.update_geometry(downsampled_pcd)
`

**Expected behavior**
The visualizer should show the latest pointcloud.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX Mojave, Ubuntu 16.04, Windows 10.0]
 - Python version:
 - Open3D version:
 - Is this remote workstation?: yes or no
 - How did you install Open3D?: pip or conda or build_from_source (provide build method, such as GCC, Xcode, Visual Studio, and so on)

**Additional context**

**Comment by g2ragrawal** [comment]
down_sample will decrease no of points in cloud and its working  fine 
[https://github.com/intel-isl/Open3D/blob/2ebd0a71320aa1a20bd978c5d7bbc2238fc92061/examples/Python/Basic/pointcloud_plane_segmentation.py](refer docs here)
![down_cloud](https://user-images.githubusercontent.com/38563307/74216256-cf671c00-4cc9-11ea-92c5-635424acb8e7.png)
maybe you are trying to zoom_out point cloud for that refer [https://github.com/intel-isl/Open3D/issues/828](here) use ctr.scale for zoom

**Comment by g2ragrawal** [comment]
down_sample will decrease no of points in cloud and its working fine
refer doc here #1287 
![down_cloud](https://user-images.githubusercontent.com/38563307/74216388-3f75a200-4cca-11ea-9975-7ee22b9ee48f.png)

maybe you are trying to zoom_out point cloud for that refer https://github.com/intel-isl/Open3D/issues/828 use ctr.scale for zoom_out

**Comment by griegler** [comment]
The problem seems to be that `select_down_sample` produces a new `PointCloud`. So, visualizer does not have a reference to it and can not update it (Given that you called `add_geometry` with `pcd`, not with `downsampled_pcd`).
To make `update_geometry` work, you will need to call `add_geometry` with `downsampled_pcd`.
