### ISSUE TITLE
open3d::geometry::ComputeNormal citation

### ISSUE THREAD

**Issue by nachovizzo** [intel-isl/Open3D#1507]
Simple question:

Is the **`open3d::geometry::ComputeNormal`** based on any particular approach?
```cpp
Eigen::Vector3d ComputeNormal(const PointCloud &cloud,
                              const std::vector<int> &indices,
                              bool fast_normal_computation);
```
The path to the method can be found in [source](https://github.com/intel-isl/Open3D/blob/5f80019468928ca7771a3a14a4ac731246497e2d/src/Open3D/Geometry/EstimateNormals.cpp#L220)

**Comment by griegler** [comment]
It is based on fitting a plane to neighboring points (`KDTreeSearchParam`). How and why this works is for example described [here](https://www.ilikebigbits.com/2015_03_04_plane_from_points.html).

**Comment by nachovizzo** [comment]
Thanks!

**Comment by syncle** [comment]
I think the right citation for normal estimation from point set is
> H. Hoppe et al., Surface Reconstruction from Unorganized Points, Computer Graphics, 26(2):71–78, 1992

Its extended work is 
> N. J. Mitra et al., Estimating Surface Normals in Noisy Point Cloud Data, International Journal of Computational Geometry and Applications, 2004

The second method is not implemented in Open3D, but this paper states that [H. Hoppe et al. 1992] is the original work for normal estimation from a point cloud.

**Comment by griegler** [comment]
@syncle note that Open3D has not fully implemented Hoppe et al. as it would also include the orientation of the normals based on a MST?

**Comment by syncle** [comment]
@griegler That's a good point. I agree because ``ComputeNormal`` does not include normal correction using MST. Does #1130 include MST or its variants? The combination of ``ComputeNormal`` and MST would be helpful, and we may cite [H. Hoppe et al. 1992].

**Comment by griegler** [comment]
@syncle No, #1130 is based on the assumption that you already have a `PointCloud` with normals. It does not touch on the aspects of normal computation.

**Comment by syncle** [comment]
Good to know. Many thanks!
