### ISSUE TITLE
Possibility to turn off the BUILD_QHULL option

### ISSUE THREAD

**Issue by HSarham** [intel-isl/Open3D#1508]
On Ubuntu 18.04 when the libqhull-dev package is installed it produces a conflict with the qhull that is compiled within Open3D. In case of for example using pcl in the same project, this may lead to a runtime error: https://github.com/intel-isl/Open3D/issues/1364

Right now the only solution I have found is to stop using libpcl in my project which is not a good solution in my opinon. On the other hand it is not possible to turn off the BUILD_QHULL option, otherwise there is a hardcoded cmake error.

I suggest to make it possible for the project to use the native libqhull-dev package on the system as a solution for the conflict.

**Comment by germanros1987** [comment]
@yxlao could you please take a look at this conflict?

**Comment by Kunika21** [comment]
Have you got this resolved?

**Comment by germanros1987** [comment]
@yxlao do we have a solution for this?

**Comment by lwohlhart** [comment]
hi everyone, any update regarding this ?
the conflict with the 3rdparty qhull is rather hindering

**Comment by lwohlhart** [comment]
@HSarham  just FYI  I just found a USE_SYSTEM_QHULL  option in the CMakeLists
judging from configuration `-DUSE_SYSTEM_QHULL=ON` should  actually solve our problems.
I'll try to confirm this later

**Comment by HSarham** [comment]
@lwohlhart My problem was when I was using the version 0.9. Now it seems that BUILD_QHULL has been replaced with USE_SYSTEM_QULL although I have not tested to see if it works.

**Comment by lwohlhart** [comment]
@yxlao @HSarham I guess we could close this Issue, what do you say ?

**Comment by HSarham** [comment]
@lwohlhart Ok, I closed it.

**Comment by manhha1402** [comment]
I set the cmake flag: `-DUSE_SYSTEM_QHULLCPP=ON`, but the build config still use build qhullcpp from source
![Screenshot from 2022-03-22 18-06-42](https://user-images.githubusercontent.com/20105284/159468274-b2abd581-6ee7-4a79-a04e-ecf6dffbf028.png)
