### ISSUE TITLE
Pointclouds created with Open3d have a pyramidal form

### ISSUE THREAD

**Issue by grigorovici-andreea** [intel-isl/Open3D#1516]
Pointclouds created from depth with Open3d have a pyramidal form.

Is this intended or do we miss some sort of transformation to get to the cubic form?

Thank you

**Comment by griegler** [comment]
Could you provide sample code and data?

**Comment by grigorovici-andreea** [comment]
Hello,
The python code line, where we create the pointcloud, you can find it here: https://github.com/analogdevicesinc/aditof_sdk/blob/8fba6918c8569f50f1d12e2a4428edc425069cd9/bindings/python/examples/showPointCloud/showPointCloud.py#L108.

Below are some results (for the pointcloud I attached both front and side view)

![depth_dispalyed](https://user-images.githubusercontent.com/54316691/74653814-a646ff80-5191-11ea-8e39-d01018919007.PNG)
![pointcloud_front](https://user-images.githubusercontent.com/54316691/74653815-a7782c80-5191-11ea-848d-1041fab86255.PNG)
![pointcloud_side](https://user-images.githubusercontent.com/54316691/74653816-a810c300-5191-11ea-94f1-a005742112da.PNG)


Thank you

**Comment by syncle** [comment]
Here are a few suggestions:
- Consider updating the camera intrinsic parameter in 113th line.
- Use ``[`` or ``]`` key in visualizer to see the point clouds in orthogonal projection mode. If the planar scene looks planar, it should be fine.

**Comment by germanros1987** [comment]
@grigorovici-andreea is this issue solved?

**Comment by grigorovici-andreea** [comment]
Hello,
I added the camera intrinsic parameters, and the resulted point cloud still has a pyramidal form. 
(https://github.com/analogdevicesinc/aditof_sdk/blob/3760cb8352001377e68088b68a01b712f083ea23/bindings/python/examples/showPointCloud/showPointCloud.py#L72)

I also have a question for intrinsic parameters. Does open3d need these parameters in pixels or in meters (I used them in pixels)?

Also, if I use the [ ] keys it seems there isn't much of a change. Please see below the images resulted and advise based on that. 

![depth_dispalyed_2](https://user-images.githubusercontent.com/54316691/74935309-b4468b80-53f0-11ea-9f72-bfbe99a6973e.PNG)
![pointcloud_after](https://user-images.githubusercontent.com/54316691/74935453-efe15580-53f0-11ea-84ca-5f6bed1c1ace.PNG)
![pointcloud_before](https://user-images.githubusercontent.com/54316691/74935454-f079ec00-53f0-11ea-9f60-761b30e93860.PNG)




Thank you a lot.

**Comment by syncle** [comment]
Check your depth map is metric and it is correctly stored without low-bit quantization. Use the correct camera intrinsic. It should be like [this example.](http://www.open3d.org/docs/release/tutorial/Basic/rgbd_images/redwood.html)

**Comment by grigorovici-andreea** [comment]
Hello,

Yes, that is the example I used as a reference.

Below is a short script that reads the depth image and creates the pointcloud. The result I get is the same. 
Could you check it out and advise if the pyramidal form is intended by pointcloud creation from open3D?

https://gist.github.com/grigorovici-andreea/e02ef93044fa85bd17ae517fb0e537d7

![depth](https://user-images.githubusercontent.com/54316691/75754933-4b3b0e00-5d36-11ea-9556-2a4bffd0a371.png)

Thank you

**Comment by grigorovici-andreea** [comment]
Hello, 

Do you have any updates on this topic?

Thank you a lot.

**Comment by germanros1987** [comment]
Do you have any additional advice @syncle ?

**Comment by syncle** [comment]
Actually I am not sure what is the burning issue here. Do you mean the captured geometry is distorted? Could you try to adjust to seeing the scene from the top, and check any distortion or skew artifact being observed?

In general, depth cameras follow the pin-hole camera model, and the captured scene makes the [camera frustum](https://en.wikipedia.org/wiki/Viewing_frustum).

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by grigorovici-andreea** [comment]
Hello,

This seems to be solved.

Thank you for your help.

**Comment by liuliu66** [comment]
@grigorovici-andreea Hi, have you solved this issue? How did you do in it?
