### ISSUE TITLE
Wrong visualization of texture mesh

### ISSUE THREAD

**Issue by ipa-mah** [intel-isl/Open3D#1529]
Probably this bug is from `tinyobjloader` library but I just reproduce it here. My texture mesh has multiple texture files (.png). I built Open3D from source.
The texture mesh visualized in MeshLab:
![meshlab](https://user-images.githubusercontent.com/20105284/74986228-6d30b880-5439-11ea-9078-96e48f152608.png)
The texture mesh visualized in Open3D:
![open3d](https://user-images.githubusercontent.com/20105284/74986249-77eb4d80-5439-11ea-8650-63174584d456.png)
Source code in C++:
```
std::string data_path = "../data1/";

    std::string texture_file = data_path+"textured.obj";
    auto mesh_ptr = std::make_shared<open3d::geometry::TriangleMesh>();
    if (open3d::io::ReadTriangleMesh(texture_file, *mesh_ptr)) {
        open3d::utility::LogInfo("Successfully read {}", texture_file);
    } else {
        open3d::utility::LogWarning("Failed to read {}", texture_file);
        return 1;
    }
    mesh_ptr->ComputeVertexNormals();
    open3d::visualization::DrawGeometries({mesh_ptr}, "Mesh", 1600, 900);
```

**Comment by theNded** [comment]
#1517 is supposed to support this feature. Can you please share the link to this model for an additional test before merging? Thanks!

**Comment by ipa-mah** [comment]
I updated updated version. The visualization is correct now. Thanks.
![open3d_v2](https://user-images.githubusercontent.com/20105284/75019090-929ce100-5490-11ea-8aa9-6fd6b20c9a0e.png)
