### ISSUE TITLE
can't use open3d.geometry.VoxelGrid.voxels

### ISSUE THREAD

**Issue by Moxinlin** [intel-isl/Open3D#1535]
i try to run the code following:
import numpy as np
import open3d as o3d

pcd = o3d.io.read_point_cloud("/Users/MXL/Desktop/sample_1.pcd")
print(pcd)
print(np.asarray(pcd.points))

vox_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(pcd, 0.5)
print(np.asarray(vox_grid.voxels))

then error occurs.
The output is:
geometry::PointCloud with 868 points.
[[ -12.9654   -167.1241     49.004299]
 [ -12.1589   -170.9985     49.029999]
 [ -11.1866   -165.2412     49.045101]
 ...
 [ -34.132301 -168.87849    70.202904]
 [ -34.552101 -166.7314     70.232903]
 [ -34.345001 -167.79601    70.259804]]
Traceback (most recent call last):
  File "pcd2voxel_file.py", line 13, in <module>
    print(np.asarray(vox_grid.voxels))
TypeError: unhashable type: 'numpy.ndarray'

**Comment by maciejmatuszak** [comment]
can be reproduced in simplier way: 
```python
voxelGrid: VoxelGrid = VoxelGrid.create_dense(origin=[0, 0, 0],
                                                  voxel_size=0.1,
                                                  width=1,
                                                  height=1,
                                                  depth=1)
voxels  = voxelGrid.voxels
```

**Comment by Moxinlin** [comment]
Hi, maciejmatuszak. Thank you for your reply.  I rollback the version to 0.8.00 and the original code also works.

**Comment by noahstier** [comment]
I have discovered this bug also.

Is there a way to get PyBind to treat the Eigen::vector3d keys as tuples instead of numpy arrays?

 Otherwise maybe the "voxels" Python binding should be replaced with a get_voxels method that creates and returns a new unordered map, keying on tuples instead.

**Comment by noahstier** [comment]
I was able to get what I needed using this patch

```
diff --git a/src/Python/open3d_pybind/geometry/voxelgrid.cpp b/src/Python/open3d_pybind/geometry/voxelgrid.cpp
index 7b85f186..7412f26c 100644
--- a/src/Python/open3d_pybind/geometry/voxelgrid.cpp
+++ b/src/Python/open3d_pybind/geometry/voxelgrid.cpp
@@ -120,6 +118,8 @@ void pybind_voxelgrid(py::module &m) {
             .def("create_from_octree", &geometry::VoxelGrid::CreateFromOctree,
                  "octree"_a
                  "Convert from Octree.")
+            .def("get_voxels", &geometry::VoxelGrid::GetVoxels,
+                  "Get a list of ``Voxel``: Voxels contained in voxel grid")
             .def_static("create_dense", &geometry::VoxelGrid::CreateDense,
                         "Creates a voxel grid where every voxel is set (hence "
                         "dense). This is a useful starting point for voxel "
diff --git a/src/Open3D/Geometry/VoxelGrid.cpp b/src/Open3D/Geometry/VoxelGrid.cpp
index abdc81f3..2a2da6a1 100644
--- a/src/Open3D/Geometry/VoxelGrid.cpp
+++ b/src/Open3D/Geometry/VoxelGrid.cpp
@@ -356,5 +356,16 @@ VoxelGrid &VoxelGrid::CarveSilhouette(
     return *this;
 }
 
+std::vector<Voxel> VoxelGrid::GetVoxels()
+{
+  std::vector<Voxel> result;
+  result.reserve(voxels_.size());
+  for (const auto& keyval : voxels_)
+  {
+    result.push_back(keyval.second);
+  }
+  return result;
+}
+
 }  // namespace geometry
 }  // namespace open3d
diff --git a/src/Open3D/Geometry/VoxelGrid.h b/src/Open3D/Geometry/VoxelGrid.h
index b31feb13..2741e738 100644
--- a/src/Open3D/Geometry/VoxelGrid.h
+++ b/src/Open3D/Geometry/VoxelGrid.h
@@ -237,6 +237,8 @@ public:
             const Eigen::Vector3d &min_bound,
             const Eigen::Vector3d &max_bound);
 
+    std::vector<Voxel> GetVoxels();
+
 public:
     /// Size of the voxel.
     double voxel_size_ = 0.0;
```

**Comment by kosuke55** [comment]
@noahstier
I got what I wanted with this patch. Thank you very much. I created PR on your behalf.

**Comment by noahstier** [comment]
Thanks. It might also be good to remote the `voxels` method from the Python bindings
