### ISSUE TITLE
Animation for sequential visualization from geometry list

### ISSUE THREAD

**Issue by hyeokhyen** [intel-isl/Open3D#1538]
Hi,
From the document, the animation examples only shows animations for view points changes, rotation, translation for input geometry.

How to sequentially visualize list of geometry one by one?
Any example code for that?

I will appreciate your reply.

**Comment by syncle** [comment]
Hello @hyeokhyen. Please refer to [this example](https://github.com/intel-isl/Open3D/blob/master/examples/Python/ReconstructionSystem/sensors/realsense_pcd_visualizer.py): it reads RGBD images, transforms it into a point clouds, and finally visualize live point sets.

**Comment by chrisranderson** [comment]
@syncle That link is dead, can you post an updated one?

**Comment by HM102** [comment]
@syncle , link is dead
