### ISSUE TITLE
Point Cloud visualization GLFW Error

### ISSUE THREAD

**Issue by FelipeDelgadoR** [intel-isl/Open3D#1550]
Hello everyone,
I've been using Open3D 0.7.0 for a while now, playing with point clouds...
I visualize my pointclouds with open3d.visualization.draw_geometries
Often when I move the point clouds in the window I get this error:

`[Open3D Error] GLFW Error: Failed to make context current`

even with having this error printed in the console, I could keep working and moving around the point cloud with no issues

Now, I updated my Open3D to version 0.9.0 and the error is shutting down my script... so now I cannot move and visualize the point cloud as I'd like, it still shows me the point cloud, but as soon as I start moving it, it shuts my program...

Is there a fix for this? maybe I have to install or upgrade some other library?
Thanks!

**Comment by syncle** [comment]
Hi, Could you try to install dependencies using the scripts [here](https://github.com/intel-isl/Open3D/tree/master/util/scripts) and build from source?

**Comment by morejiik** [comment]
Hello! Same problem here. The same script I'm using was working a week ago, With the only difference that I was not getting any error in the console (as far as I remember correctly).
Win 10, Python 3.7.6 (64bit) and Open3D 0.9.0

**Comment by morejiik** [comment]
Here some more details on the error:
```
Traceback (most recent call last):
  File ".../Exercise1/02_example.py", line 23, in <module>
    o3d.visualization.draw_geometries([pcd])
RuntimeError: [Open3D ERROR] GLFW Error: WGL: Failed to make context current: Handle non valido.
```

**Comment by morejiik** [comment]
Update: after some days and a PC reboot, everything seems to work correctly. I haven't changed anything and I don't know what caused the issue.

**Comment by ZhangLanTao** [comment]
hi, I have the same problem, I build open3d from source and when draw_geometries(),my scrip shut down.
`RuntimeError: [Open3D ERROR] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。`

**Comment by germanros1987** [comment]
@ZhangLanTao even after installing the dependencies, the problem persists?

**Comment by syncle** [comment]
@FelipeDelgadoR @morejiik @ZhangLanTao How did you use draw_geometries? Are you using in Jupyter Notebook?

**Comment by ZhangLanTao** [comment]
nope， I'm using it in pycharm, I set GPU to NVIDIA's card and the problem haven't occur so far.


 
---Original---

**Comment by ZhangLanTao** [comment]
Yes, I switched to NVIDIA's GPU and it works&nbsp;


 
---Original---

**Comment by morejiik** [comment]
> 
> 
> @FelipeDelgadoR @morejiik @ZhangLanTao How did you use draw_geometries? Are you using in Jupyter Notebook?

This is the code:

```
pcd  = o3d.io.read_point_cloud('pcd.ply')

print(np.asarray(pcd.points).shape)
print(np.asarray(pcd.colors).shape)

o3d.visualization.draw_geometries([pcd])
```

No, I'm using Visual Studio Code.
Sometimes it crashes with the same error, sometimes it works..

@ZhangLanTao how did you switch to the Nvidia GPU?

**Comment by ZhangLanTao** [comment]
> > @FelipeDelgadoR @morejiik @ZhangLanTao How did you use draw_geometries? Are you using in Jupyter Notebook?
> 
> This is the code:
> 
> ```
> pcd  = o3d.io.read_point_cloud('pcd.ply')
> 
> print(np.asarray(pcd.points).shape)
> print(np.asarray(pcd.colors).shape)
> 
> o3d.visualization.draw_geometries([pcd])
> ```
> 
> No, I'm using Visual Studio Code.
> Sometimes it crashes with the same error, sometimes it works..
> 
> @ZhangLanTao how did you switch to the Nvidia GPU?

you can refer to issue #1598, It works on my PC.

**Comment by FelipeDelgadoR** [comment]
It still works with open3D 0.8.0, not sure what's the deal.
Using pycharm with python 3.7

**Comment by ixgnaz** [comment]
Using a good independent Graphics card that supports openGL is an effective solution.

**Comment by kezkabarra** [comment]
Hi! Same problem here. Windows 10; python 3.6.10; open3D 0.9.0.0. in Anaconda.
Try to solve it using [#1598](https://github.com/intel-isl/Open3D/issues/1598), but dont know how to using Anaconda. Someone? It would be a pity to stop using it because of this now that we were gettin along...

**Comment by ZhangLanTao** [comment]
change a graphics card may help


 
---Original---

**Comment by kezkabarra** [comment]
Well, I could do that for me. But Im developping an application to deploy in many computers the solution should be more generalistic. Maybe try different version combinations of python and opend3D? Anyone with no independent graphics card working in Windows with no issues?

**Comment by janulicny** [comment]
Hi. Like Felipe mentions in the original post, the error is happening in Open3D versions prior to 0.9 as well, but it was failing silently in the  background. Since 0.9  the whole visualizer throws an error and shuts down.

On the screenshot below, you can see console print outs for running same script with 0.8 and 0.10.0.1 version.
On the left, GLFW fails several times. The errors are logged, but I was able to continue to use the visualizer (zoom, rotate, etc.) and without the log, I would have not noticed anything.
On the right, the script shuts down with the first error.

![image](https://user-images.githubusercontent.com/29164793/96128732-05623d00-0ef6-11eb-875d-0e8916b8b1c2.png)

I am not sure if this error handling change was deliberate decision or if it is even coming from Open3D code, but since I have a laptop with only internal GPU, the suggested workaround does not work for me and I would appreciate reverting back to the silent fails in background.

**Comment by germanros1987** [comment]
@errissa could you have a look at this issue?

**Comment by errissa** [comment]
@janulicny We deliberately changed error logging to throw an exception if the severity is high enough which is why your script no longer continues past the first error. I will investigate if the error could safely be reported as a warning instead.

**Comment by errissa** [comment]
@janulicny Please try latest master. GLFW errors are now logged as warnings so they don't force the program to quit.

**Comment by janulicny** [comment]
@errissa Can confirm that the behavior is the same as with 0.8. Thank you!
![image](https://user-images.githubusercontent.com/29164793/98662192-b74f2680-2347-11eb-9fbc-bb36906485ed.png)

**Comment by errissa** [comment]
Yes, the behavior is the same with respect to the logging. GLFW errors are logged to the console but don't stop the program just like in 0.8.

**Comment by diskov** [comment]
> @FelipeDelgadoR @morejiik @ZhangLanTao How did you use draw_geometries? Are you using in Jupyter Notebook?

Hello, I am using Jupyter notebook to visualize a .ply file with open3d and get the message: 
![image](https://user-images.githubusercontent.com/62543957/101012007-0b25e780-3563-11eb-9723-ff10d64fda62.png)

I know it may not be the same exact problem but I was wondering if you would have any ideas on what I could do to fix it? 

Thanks!!

**Comment by nachoreimat** [comment]
I was having the same issue from time to time.
I have followed this step:

> Go to Nvidia Control Panel > Manage 3d settings > select preferred graphics processor. By default you can see auto-select. Change it to your desired GPU.

and it seems to work now. Give it a try
