### ISSUE TITLE
How can I correctly set the view of camera to get correct render images?

### ISSUE THREAD

**Issue by densechen** [intel-isl/Open3D#1553]
Hi, 
I want to use Open3D to render some depth and color images of a object which is located in the origin o f world coords. And this would be useful and meaningful for generating large scale depth and color image for 3d computer vision task. 
And the following is my code:
`import open3d as o3d
import numpy as np
from scipy.spatial.transform import Rotation
import transforms3d
from tqdm import tqdm
from glob import glob
import os
import math

import argparse

class Render(object):
    """ Render 3d mesh models with random views.
    Only used for ShapeNetCore.v1.
    """

    def __init__(self, input_dir, output_dir, number_of_views, image_width=640, image_height=480):
        super().__init__()
        self.input_dir = input_dir
        self.output_dir = output_dir

        os.makedirs(self.output_dir, exist_ok=True)

        self.number_of_views = number_of_views

        self.image_height = image_height
        self.image_width = image_width

    def get_points(self):
        """
        See https://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere.

        :param n_points: number of points
        :type n_points: int
        :return: list of points
        :rtype: numpy.ndarray
        """

        rnd = 1.
        points = []
        offset = 2. / self.number_of_views
        increment = math.pi * (3. - math.sqrt(5.))

        for i in range(self.number_of_views):
            y = ((i * offset) - 1) + (offset / 2)
            r = math.sqrt(1 - pow(y, 2))

            phi = ((i + rnd) % self.number_of_views) * increment

            x = math.cos(phi) * r
            z = math.sin(phi) * r

            points.append([x, y, z])

        # visualization.plot_point_cloud(np.array(points))
        return np.array(points)

    def get_views(self):
        """
        Generate a set of views to generate depth maps from.

        :param n_views: number of views per axis
        :type n_views: int
        :return: rotation matrices
        :rtype: [numpy.ndarray]
        """

        Rs = []
        ts = []
        points = self.get_points()

        for i in range(points.shape[0]):
            # https://math.stackexchange.com/questions/1465611/given-a-point-on-a-sphere-how-do-i-find-the-angles-needed-to-point-at-its-ce
            longitude = - math.atan2(points[i, 0], points[i, 1])
            latitude = math.atan2(points[i, 2], math.sqrt(points[i, 0] ** 2 + points[i, 1] ** 2))

            R_x = np.array([[1, 0, 0],
                            [0, math.cos(latitude), -math.sin(latitude)],
                            [0, math.sin(latitude), math.cos(latitude)]])
            R_y = np.array([[math.cos(longitude), 0, math.sin(longitude)],
                            [0, 1, 0],
                            [-math.sin(longitude), 0, math.cos(longitude)]])

            R = R_y.dot(R_x)
            Rs.append(R)
            ts.append(points[i])

        return Rs, ts

    def sample_views(self, ref_view):
        # points = np.random.rand(3) + 0.5  # 0.5 ~ 1.5 meter
        # sign = np.random.choice([-1, 1], size=3)  # possitive or negtive
        # points = sign * points

        # # target vec
        # target_vec = - points
        # target_vec = target_vec / np.linalg.norm(target_vec)
        # source_vec = np.array([0, 0, 1], dtype=np.float32)

        # angle = np.arccos(np.dot(source_vec, target_vec))
        # normal = np.cross(source_vec, target_vec)
        # normal = normal / np.linalg.norm(normal)

        # skew = np.array([
        #     [0, -normal[2], normal[1]],
        #     [normal[2], 0, -normal[0]],
        #     [-normal[1], normal[0], 0]])

        # R = np.cos(angle) + (1-np.cos(angle)) * skew * \
        #            skew + np.sin(angle) * skew
        # # R = np.eye(3) + skew * np.sin(angle) + skew * skew * (1 - np.cos(angle))

        # a = np.dot(target_vec, np.linalg.inv(R))
        # a = a / np.linalg.norm(a)

        # M = np.eye(4)
        # M[:3, :3] = np.linalg.inv(R)
        # M[:3, 3] = -points

        # ref_view.extrinsic = M
        # return ref_view
        extrinsic = np.eye(4)
        Rs, ts = self.get_views()

        extrinsic[:3, :3] = Rs[0]
        extrinsic[:3, 3] = ts[0]
        ref_view.extrinsic = np.linalg.inv(extrinsic)
        return ref_view

    def load_filelist(self):
        return {
            k: [n for n in glob(os.path.join(k, "*"))
                                if os.path.isdir(os.path.join(n, "images"))]
            for k in glob(os.path.join(self.input_dir, "*"))}

    def load_obj(self, path):
        return o3d.io.read_triangle_mesh(path)

    def camera_parameters(self, views):
        original_pose = views.extrinsic

        rotations_eul = np.random.randint(-10, 10, size=(3)) / 100.0

        pose = np.dot(
            transforms3d.affines.compose([0, 0, 0],
                    Rotation.from_euler("xyz", rotations_eul).as_matrix(),
                                                    [1, 1, 1]),
                    np.asarray(original_pose))

        views.extrinsic = pose.T

        return views

    def save_info(self, cam, path):
        o3d.io.write_pinhole_camera_parameters(path, cam)

    def render(self,):
        # get filelist
        filelist = self.load_filelist()

        # define viewer
        viewer = o3d.visualization.Visualizer()
        viewer.create_window(width=self.image_width,
                             height=self.image_height, visible=False)

        for k, v in filelist.items():
            print("processing {}".format(k))
            for f in tqdm(v):

                # get mesh
                mesh = self.load_obj(os.path.join(f, "model.obj"))

                # mkdir
                output_dir = f.replace(self.input_dir, self.output_dir)
                os.makedirs(output_dir, exist_ok=True)

                viewer.add_geometry(mesh)
                control = viewer.get_view_control()
                ref_view = control.convert_to_pinhole_camera_parameters()
                # get views
                # views = self.sample_views(ref_view)

                for i in range(self.number_of_views):
                    # create camera intrinsic
                    views = self.sample_views(ref_view)
                    control.convert_from_pinhole_camera_parameters(views)

                    viewer.capture_depth_image(os.path.join(output_dir, "{:04d}-depth.png".format(i)), do_render=True, depth_scale=1000.0)
                    viewer.capture_screen_image(os.path.join(output_dir, "{:04d}-color.png".format(i)), do_render=True)

                    # save info
                    self.save_info(views, os.path.join(output_dir, "{:04d}-info.json".format(i)))

                    viewer.reset_view_point(True)

                viewer.remove_geometry(mesh, reset_bounding_box = True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="render ShapeNetCore.v1")

    parser.add_argument("input_dir", help="root of ShapeNetCore.v1")
    parser.add_argument("output_dir", help="root of RenderedShapeNetCore.v1")
    parser.add_argument("--number_of_views", type=int, default=100, help="number of views for each instances")
    parser.add_argument("--image_width", type=int, default=640)
    parser.add_argument("--image_height", type=int, default=480)
    args = parser.parse_args()

    render = Render(input_dir=args.input_dir, output_dir=args.output_dir, number_of_views=args.number_of_views, image_width=args.image_width, image_height=args.image_height)
    
    print("Starting rendering...")
    render.render()
    print("Done")
                
`

However, I failed to caculate a correct camera pose/views for 'control.convert_from_pinhole_camera_parameters', which means I failed to make the camera always point to the object which is located in the original of world coord.  
Can anyone help me out here?
Thanks very much!

**Comment by StephanHasler** [comment]
I think the convert_from_pinhole_camera_parameter might be buggy.
If do the following:
```
        camera_parameters = view_control.convert_to_pinhole_camera_parameters()
        print("{}\n"
              "{}".format(camera_parameters.extrinsic, camera_parameters.intrinsic.intrinsic_matrix))
        camera_parameters.extrinsic = numpy.array(
             [[1., 0., 0., 0.],
              [0., 1., 0., 0.],
              [0., 0., 1., 0.],
              [0., 0., 0., 1.]])

        view_control.convert_from_pinhole_camera_parameters(camera_parameters)

        camera_parameters = view_control.convert_to_pinhole_camera_parameters()
        print("{}\n"
              "{}".format(camera_parameters.extrinsic, camera_parameters.intrinsic.intrinsic_matrix))
```
I get the result:
```
# Initial values:
[[ 1.  0.  0. -0.]
 [-0. -1. -0.  0.]
 [-0. -0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[ 692.82032303    0.          399.5       ]
 [   0.          692.82032303  399.5       ]
 [   0.            0.            1.        ]]

# Values after customization of extrinsic parameters:
[[  1.   0.   0.  nan]
 [ -0.   1.  -0.  nan]
 [  0.   0.   1.  nan]
 [  0.   0.   0.   1.]]
[[ 692.82032303    0.          399.5       ]
 [   0.          692.82032303  399.5       ]
 [   0.            0.            1.        ]]
```
So some 'nan' values are produced. Still the visualization works but seems to the default viewpoint.

**Comment by StephanHasler** [comment]
I did a further test:
Even without changing the extrinsic parameters I get the 'nan's.
So it is a bug. I will open an issue.

**Comment by densechen** [comment]
@StephanHasler Thanks for interesting in this question. Before that, I never noticed the nan value in the parameters.

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by harry1576** [comment]
@densechen did you ever end up solving this issue?
I am trying to do the same thing - if you could share some code that would be great.
Cheers,
Harry

**Comment by nishadgothoskar** [comment]
I am also encountering this nan issue. If anyone has found a solution and can share, it'd be much appreciated!
