### ISSUE TITLE
Docker compilation doesn't work out of the box

### ISSUE THREAD

**Issue by CiaoAnkit** [intel-isl/Open3D#1563]
I am trying to compile Open3d via Docker on my macOS Catalina.
To do so, I git pulled the Open3d repo and follow the instruction for [docker image building:](http://www.open3d.org/docs/release/tutorial/docker/docker-gui.html#docker-files)

`$ cd <open3d_path>/util/docker/open3d_xvfb/tools`

`$ ./build.sh`

`$ ./run.sh`

The build is successful but when I execute `run.sh`

> -- PYPI_PACKAGE_NAME: open3d
-- Configuring incomplete, errors occurred!
See also "/root/open3d/build/CMakeFiles/CMakeOutput.log".
See also "/root/open3d/build/CMakeFiles/CMakeError.log".

The content of `CMakeError.log` are:

> 

> Looking for a ASM_NASM compiler failed with the following output:
-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_ASM_NASM_COMPILER could be found.

> Tell CMake where to find the compiler by setting either the environment
  variable "ASM_NASM" or the CMake cache entry CMAKE_ASM_NASM_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.

>-- Configuring incomplete, errors occurred!
See also /root/open3d/3rdparty/CMakeFiles/CheckASM_NASM/CMakeFiles/CMakeOutput.log".
See also "/root/open3d/3rdparty/CMakeFiles/CheckASM_NASM/CMakeFiles/CMakeError.log".

Then, I `./attach.sh` to get inside the docker image. The content of `/root/open3d/3rdparty/CMakeFiles/CheckASM_NASM/CMakeFiles/CMakeError.log` are:

> Checking whether the ASM_NASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
Checking whether the ASM_NASM compiler is HP using "-V" did not match "HP C":
Checking whether the ASM_NASM compiler is Intel using "--version" did not match "(ICC)":
Checking whether the ASM_NASM compiler is SunPro using "-V" did not match "Sun C":
Checking whether the ASM_NASM compiler is XL using "-qversion" did not match "XL C":
Checking whether the ASM_NASM compiler is MSVC using "/?" did not match "Microsoft":
Checking whether the ASM_NASM compiler is TI using "-h" did not match "Texas Instruments":
Checking whether the ASM_NASM compiler is IAR using "" did not match "IAR Assembler":
Checking whether the ASM_NASM compiler is ARMCC using "" did not match "(ARM Compiler)|(ARM Assembler)":
Checking whether the ASM_NASM compiler is NASM using "-v" did not match "(NASM version)":
Checking whether the ASM_NASM compiler is YASM using "--version" did not match "(yasm)":

I also tried to recompile with:

 `root@open3d-xvfb:~/open3d# cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DPYTHON_EXECUTABLE=/usr/bin/python3 -DBUILD_PYBIND11=OFF -DBUILD_PYTHON_MODULE=OFF -DBUILD_PYTHON_TUTORIALS=OFF -DCMAKE_INSTALL_PREFIX=~/open3d_install CMakeLists.txt`

But still the same error. I believe it should work out of the box in the docker image, but anyway, please tell me what wrong am I doing here?

PS: Other things I have tried to is manually run the scripts under `~/open3d/util/scripts/` inside docker terminal.

**Comment by syncle** [comment]
@yxlao could you help @ankitphd?

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by yxlao** [comment]
Closing as the Docker build is no longer maintained and removed from the repo. We'll add back docker support for CI in the future.
