### ISSUE TITLE
Cannot assign modified triangle_uvs to mesh

### ISSUE THREAD

**Issue by sam598** [intel-isl/Open3D#1574]
When modifying vertices directly this works:
`mesh.vertices = o3d.utility.Vector3dVector(vertices)`

However this does not work:
`mesh.triangle_uvs = o3d.utility.Vector2dVector(triangle_uvs)`

There does not appear to be a utility function for assigning new or modified uvs to a triangle mesh. Is there an alternative method for accomplishing this?

**Comment by germanros1987** [comment]
@griegler any comments on this?

**Comment by griegler** [comment]
`std::vector<Eigen::Vector2d>` is not properly exposed via pybind. 
I submitted a PR (#1623) to fix the problem.
