### ISSUE TITLE
2d screen elements

### ISSUE THREAD

**Issue by richardrl** [intel-isl/Open3D#1576]
How to put up some 2d elements on the screen?

For example, I want to design a [HUD](https://en.wikipedia.org/wiki/Head-up_display) visualizing the forces on the end effector. This HUD should stick the screen and not move when the camera angle moves.

**Comment by germanros1987** [comment]
We are about to release a new GUI API that will allow users to do that.

See example:
![image](https://user-images.githubusercontent.com/38517452/76557968-b59c2e80-6459-11ea-916d-38cc01039de6.png)

**Comment by richardrl** [comment]
> We are about to release a new GUI API that will allow users to do that.
> 
> See example:
> ![image](https://user-images.githubusercontent.com/38517452/76557968-b59c2e80-6459-11ea-916d-38cc01039de6.png)

Awesome!

**Comment by Zumbalamambo** [comment]
@germanros1987 is there any documentation for the new gui module?
