### ISSUE TITLE
Installation via pip on Windows 10 fails

### ISSUE THREAD

**Issue by maxpfingsthorn** [intel-isl/Open3D#1580]
**Describe the bug**
The command from the documentation to install the latest Open3D version on Windows 10 fails with 
ERROR: Could not find a version that satisfies the requirement open3d (from versions: none)
ERROR: No matching distribution found for open3d

On Linux, this works like a charm.

**To Reproduce**
1. pip install open3d

**Expected behavior**
Should install open3d, but Win packages not available?

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 64-bit, 1909
 - Python version: 3.7.2
 - PIP version: 20.0.2
 - Open3D version: 0.9.0
 - Is this remote workstation?:  no
 - How did you install Open3D?: not yet, pip does not work

**Comment by yxlao** [comment]
Can you try downloading from https://pypi.org/project/open3d/#files the corresponding version and install with pip directly? One possibility is the mismatch of virtualenv's python version with pip, or maybe the python distribution is 32 bit.

We have support for 2.7, 3.5, 3.6, 3.7 on Windows 64 bit.

**Comment by copterspace** [comment]
tried to install whl from https://pypi.org/project/open3d/#files on Windows 10 x64, Python 3.8:
```
>pip install open3d-0.9.0.0-cp37-cp37m-win_amd64.whl
ERROR: open3d-0.9.0.0-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

>pip -V
pip 20.0.2 from c:\program files\python38\lib\site-packages\pip (python 3.8)

>python -V
Python 3.8.1

>ver
Microsoft Windows [Version 10.0.17763.805]
```
is this because I use Python 3.8 (not 3.7), or some othre reason?

**Comment by drdelta** [comment]
I installed 3.8.2 earlier today and had the same issue.
After installing 3.7.7 and removing 3.8.2, it worked for me.

**Comment by copterspace** [comment]
Would it be possible for developers to compile .whl file also for 3.8? Library itself should be compatible, they only need to add Python 3.8 to Metadata file...?

**Comment by maxpfingsthorn** [comment]
Thank you all for the comments and help. It seems my Python version was 32-bit. I reinstalled the 64-bit version and it seems to work fine now. Still on Python 3.7.7 as well.

**Comment by copterspace** [comment]
What about compiling whl for Python 3.8?...

**Comment by theaveragedev** [comment]
Python 3.9 64 bit verion. Still having this issue.

**Comment by dllu** [comment]
same here, on linux, can't install pip on python 3.9.

```
pip install open3d
Defaulting to user installation because normal site-packages is not writeable
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
ERROR: Could not find a version that satisfies the requirement open3d
ERROR: No matching distribution found for open3d
```
