### ISSUE TITLE
Camera culling on cloud geometry rendering

### ISSUE THREAD

**Issue by AGAPIA** [intel-isl/Open3D#1581]
Hello,

I'm trying to render a point cloud but even when I set Z near to 0 I see the following problem: the points are rendered but they are not textured! How can I tune this and get more textured data close to the camera? 

If there is no Python API for tuning this, can you at least point me where to look in the CPP code please ?

I attached the images with the problem 
![close](https://user-images.githubusercontent.com/26081910/76238300-51e6eb00-6238-11ea-9380-2fcb45c84dc9.png)

**Comment by griegler** [comment]
Do you have a reference what it should look like? Are points missing, or are the wrongly colored?

**Comment by AGAPIA** [comment]
The points are there, but their triangles are not textured. See the many white points close to the camera at the bottom of the image.  For example take this below picture which is further to the image, and see that the textures are rendered correctly.
![image](https://user-images.githubusercontent.com/26081910/76282722-2f3cec80-62a1-11ea-9bfb-e70ddfb6a905.png)

**Comment by griegler** [comment]
I also noticed problem with some meshes and certain view points, but I could resolve it with setting z near and far. But you mentioned that you already tried that.
@yxlao do you have any idea?

**Comment by germanros1987** [comment]
@AGAPIA could you please send out the point cloud?

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by germanros1987** [comment]
@AGAPIA this is solved in our new rendering module.
