### ISSUE TITLE
object pose estimation

### ISSUE THREAD

**Issue by Kayumiy** [intel-isl/Open3D#1597]
examples / Python / ReconstructionSystem / opencv_pose_estimation.py

The code above is can be run on Windows but cannot show any result.
How to solve this problem?

**Comment by syncle** [comment]
that Python script contains utility functions. Check below scripts on how opencv_pose_estimation.py is being imported and used.

https://github.com/intel-isl/Open3D/blob/44a35978e78cf68a8368b90b173927ff0e0ef960/examples/Python/ReconstructionSystem/debug/pairwise_rgbd_alignment.py

https://github.com/intel-isl/Open3D/blob/499d245d80fda050319727ea99e8ea33fecb57f4/examples/Python/ReconstructionSystem/make_fragments.py
