### ISSUE TITLE
RuntimeError: [Open3D ERROR] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported.

### ISSUE THREAD

**Issue by orgicus** [intel-isl/Open3D#1598]
**Describe the bug**
Zooming and panning at some point crashes the visualiser.
Using the mouse wheel to zoom, then click and drag into a mesh (sometimes at tight angles/zooms) causes a crash.

I've tested this with both a pointcloud and triangle mesh.
I'm not sure if the dimensions/complexity of the mesh has anything to do with it or not.

Running in verbose mode outputs:
```bash
[Open3D DEBUG] Read geometry::TriangleMesh: 6678 triangles and 13356 vertices.
[Open3D DEBUG] GLFW init.
[Open3D DEBUG] Add geometry and update bounding box to [(-50732.6992, -51368.5000, -13202.2998) - (-28131.3008, -28069.9004, 17448.5996)]
[Open3D DEBUG] Global colormap init.
Traceback (most recent call last):
  File "o3d_viz_crash.py", line 12, in <module>
    o3d.visualization.draw_geometries([mesh])
RuntimeError: [Open3D ERROR] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported.
[Open3D DEBUG] Global colormap destruct.
[Open3D DEBUG] GLFW destruct.
```

To make this easy to reproduce I've provided the script and mesh along with a short screen recording [here](http://lifesine.eu/so/o3d_viz_crash.zip)

Notice the tight angle towards the end of the video (which ends with the crash)

**To Reproduce**
1. Download the [o3d_viz_crash.zip](http://lifesine.eu/so/o3d_viz_crash.zip)
2. unzip o3d_viz_crash.zip and `cd o3d_viz_crash`
3. run o3d_viz_crash.py
4. use a mouse with a mousewheel to mouse wheel zoom and mouse wheel click to drag at tight angles (see video for example)
5. observe crash

**Expected behavior**
Zooming in and panning should not crash the visualizer

**Screenshots**
See screencast in o3d_viz_crash.zip

**Environment**
 - OS: Windows 10.0 (version 1809, build 11763.1039)
 - Python version: 3.6.4 (64-bit)
 - Open3D version: 0.9.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

Please let me know if there any more info I could supply to make this easier.

**Update**
I may have found a culprit/workaround ?
If I use Settings > Graphics to explicitly allow Python to use the nVidia GPU the problems seems to go away, otherwise, on the Intel UHD Graphics 630 I can always easily crash the visualiser

![2020-03-11 12_50_23-Settings](https://user-images.githubusercontent.com/189031/76418753-1878c180-6397-11ea-8661-9320579ffcec.png)

![2020-03-11 12_52_10-Settings](https://user-images.githubusercontent.com/189031/76418893-58d83f80-6397-11ea-8aa2-5bcaaeafb319.png)

This may not be an open3d API bug, but a GLFW / GPU bug ?

Many thanks,
George

**Comment by akshat1136** [comment]
I tried the above solution but getting the same error. I have GTX1060 6GB in my laptop and launching Open3D with Spyder. 
Is there any way to check if the Open3D installed is even using the GPU?

**Comment by g2ragrawal** [comment]
https://stackoverflow.com/questions/8223811/top-command-for-gpus-using-cuda

**Comment by otepencelik** [comment]
I'm having the same error as the OP. I tried changing my graphics specifications to "High Performance", the error still often occurs. Are there any other solutions to this?

**Comment by aryasenna** [comment]
Hi, why is this closed?
For those with laptop with only integrated Intel GPU, then we have no solution.


Kinda ironic since this wonderful library is made by Intel... :(

**Comment by wzm2256** [comment]
Is this library still being maintained?
