### ISSUE TITLE
6D Object Pose Estimation 

### ISSUE THREAD

**Issue by Kayumiy** [intel-isl/Open3D#1603]
I am using Open3D dll in order to make 6d Object pose estimation project.

Is it possible to determine rotation info of the object in the image by using Open3D? 
Rotation info means roll, pitch and yaw angle of the object.

If there is not any method to do this, I am going to make myself in order to improve Open3D dll and achieve this task. However, I need a guide little a bit. 
Can anybody guide me to achieve this?

Thank You

**Comment by Kayumiy** [comment]
Is there any helpful methods which can identify object's pose in the scene in the Open3D dll?

**Comment by syncle** [comment]
I am not sure about a specific input output configuration from the question. Open3D provides basic registration pipelines (for now). Feel free use it for your purpose. For 6D pose estimation from an image, check-out [this comprehensive list](https://github.com/nkalavak/awesome-object-pose).

**Comment by Kayumiy** [comment]
If a paper airplane is on a table. And it is relative to the table. if the table's rotation angles (0,0,0), how to calculate airplane rotation angle relative to the table? Is it possible to determine by using Open3d dll ?

**Comment by Kayumiy** [comment]
How to measure object's orientation in image?
