### ISSUE TITLE
How to open the multitple "o3d.visualization.draw_geometries" windows simultaneously when using python(such as spyder)

### ISSUE THREAD

**Issue by luoyin500** [intel-isl/Open3D#1629]
Maybe it's a simple problem, but I am troubled:
When using spyder call open3d, two o3d.visualization.draw_geometries commands are called. To see the second result window, the first have to be closed.

**Comment by luoyin500** [comment]
What is the way to display two Windows simultaneously for comparison？

**Comment by griegler** [comment]
You can do it by creating your own `Visualizer` windows. Have a look [here](http://www.open3d.org/docs/release/tutorial/Advanced/non_blocking_visualization.html) for an example.

**Comment by luoyin500** [comment]
Thanks!

**Comment by BedirYilmaz** [comment]
> You can do it by creating your own `Visualizer` windows. Have a look [here](http://www.open3d.org/docs/release/tutorial/Advanced/non_blocking_visualization.html) for an example.

Unfortunately, the link seems to be broken.
