### ISSUE TITLE
Addon to Import Open3D formats into Blender 

### ISSUE THREAD

**Issue by SBCV** [intel-isl/Open3D#1632]
I've wrote an [addon ](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer) to import different file formats of several photogrammetry libraries into Blender. 
Now, it supports also Open3D file formats (i.e. *.json and *.log).

Here is an example of the imported fountain dataset.
![fountain_example](https://user-images.githubusercontent.com/19491335/76886103-90a42300-6880-11ea-8a27-69e82f323471.jpg)

 I hope this might be useful for others as well. Maybe you want to add a reference somewhere else to this?

Feel free to close this issue.

**Comment by germanros1987** [comment]
Thanks @SBCV, it looks great!
