### ISSUE TITLE
System Reconstruction more color independent

### ISSUE THREAD

**Issue by ArlenisChS** [intel-isl/Open3D#1634]
Hi, 
I’m using your 3D reconstruction system and it seems to me like is very attached to color. The thing is I’m trying to make a 3D segmentation by segmenting the object in all rgb images( I get black and white images). But when I change the color images for my segmented images is a total mess. Not even the fragments are working well( by this I’m not referring to a bug, is just that the images are not registering well). Is there a solution for this?? Could it be a feature to do it more color independent??

**Comment by theNded** [comment]
We use [RGBDOdometry](http://www.open3d.org/docs/release/tutorial/Basic/rgbd_odometry.html) to construct fragments. This module involves both color and depth data and computes image gradients for registration. 
A dirty workaround is to eliminate this predefined combination. You may change this [parameter](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Odometry/RGBDOdometryJacobian.cpp#L38) to 1.0.

**Comment by ArlenisChS** [comment]
> We use [RGBDOdometry](http://www.open3d.org/docs/release/tutorial/Basic/rgbd_odometry.html) to construct fragments. This module involves both color and depth data and computes image gradients for registration.
> A dirty workaround is to eliminate this predefined combination. You may change this [parameter](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Odometry/RGBDOdometryJacobian.cpp#L38) to 1.0 and recompile Open3D.

Well thanks, I’ve solved my problem by making all the estimation with the rgb-d images and at the end instead of integrate with those images I do it with the segmented ones, and it works. In fact I think is better this way. Sorry to bother. Still thanks!! 😊

**Comment by theNded** [comment]
> > We use [RGBDOdometry](http://www.open3d.org/docs/release/tutorial/Basic/rgbd_odometry.html) to construct fragments. This module involves both color and depth data and computes image gradients for registration.
> > A dirty workaround is to eliminate this predefined combination. You may change this [parameter](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Odometry/RGBDOdometryJacobian.cpp#L38) to 1.0 and recompile Open3D.
> 
> Well thanks, I’ve solved my problem by making all the estimation with the rgb-d images and at the end instead of integrate with those rgb images I do it with the segmented ones, and it works. In fact I think is better this way. Sorry to bother. Still thanks!! Great library btw... 😊

Cheers! 
Issue closed.
