### ISSUE TITLE
Question - Headless rendering with textured mesh

### ISSUE THREAD

**Issue by jbjeong** [intel-isl/Open3D#1638]
Hello, thanks for great work.

I have a question about the headless rendering.
I have tried to use headless rendering with textured mesh, but it didn't work.
I used the example code (headless_rendering.py) which the input data was changed 
(point cloud -> textured mesh).
As a result, the segmentation fault is raised after the line "vis.run()" ([headless_rendering-line59](https://github.com/intel-isl/Open3D/blob/179dcd2190c1342aabee8cdbadaae784d03b7199/examples/Python/Advanced/headless_rendering.py#L59))

[mesh info]
geometry:: TriangleMesh with 49998 points and 1000004 triangles, 
and textures of size (8192, 8192)

This textured mesh could be rendered with default rendering.
Can't headless rendering work with textured mesh?

**Comment by auzyze** [comment]
Hi, @jbjeong I got the same issue with headless rendering for textured mesh. Any update for this? Thanks!

**Comment by nachovizzo** [comment]
I'm also struggling with textured meshes. Apparently, there was some regression at some point. Some time ago there was an example loading the `crate.obj` object under the test_data dir. Now if you try to load with the original visualizer it doesn't work anymore. With the new visualizer, it does work

## Old Visualizer
![image](https://user-images.githubusercontent.com/21349875/95738269-3be75000-0c89-11eb-9fa1-c8ecc9239363.png)

## New Visualizer 
![image](https://user-images.githubusercontent.com/21349875/95738346-5d483c00-0c89-11eb-9563-90c69f227728.png)

**Comment by germanros1987** [comment]
@errissa could you unbreak this?

**Comment by errissa** [comment]
@nachovizzo This is now fixed.

**Comment by nachovizzo** [comment]
Amazing thanks!
