### ISSUE TITLE
"Outward" normal orientation method

### ISSUE THREAD

**Issue by SeanStephensenAIRM** [intel-isl/Open3D#1641]
I'd like to request an official method for orienting normals "outward" on a point cloud, or at least start a discussion on the technique for this objective. If a rigorous technique exists or can be described, it could be implemented as a method, similar to pcd.orient_normals_to_align_with_direction().

Motivation:
A poisson surface reconstruction of a cylindrical object fails, namely through generating a noise that is "planar". For example, here is a point cloud with non-oriented normals (some point "inwards", and some "outwards"):

![cyl1](https://user-images.githubusercontent.com/60408933/77211106-da834800-6ad0-11ea-8f6e-835537330e13.JPG)

and it's resulting poisson reconstruction. Low depth levels were used here to illustrate the effects of poisson noise (the issue here is not tightening the mesh):

![cyl2](https://user-images.githubusercontent.com/60408933/77211129-f1299f00-6ad0-11ea-984d-b43a609cec5c.JPG)

Here is the same point cloud with normals oriented "outward" using a rudimentary method of my own:

![cyl3](https://user-images.githubusercontent.com/60408933/77211150-043c6f00-6ad1-11ea-94ff-0d930aa36193.JPG)

and the resulting mesh, who's noise is more "cylindrical":

![cyl4](https://user-images.githubusercontent.com/60408933/77211179-19b19900-6ad1-11ea-99dc-efe5b7b647da.JPG)

I still have other issues to sort out in my reconstruction process such as cleaning low density points, so perhaps this issue of outward-oriented normals is not as important as I'm thinking it is. I'd love to hear thoughts on this.

**Comment by griegler** [comment]
The problem is we do not have a method to orient the normals like using a minimum spanning tree in Open3D. We already discussed it in #270, #1507, #1522. I think @syncle wanted to work on it? Can you tell your status. Otherwise, I could have a look at it next week.

**Comment by germanros1987** [comment]
solved.
