### ISSUE TITLE
Headless rendering: OSMesa: Failed to create context

### ISSUE THREAD

**Issue by lucivpav** [intel-isl/Open3D#1647]
I have followed the [instructions](http://www.open3d.org/docs/release/tutorial/Advanced/headless_rendering.html) on headless rendering. To test things out I tried running the `headless_rendering.py` script, which throws an error: `RuntimeError: [Open3D ERROR] GLFW Error: OSMesa: Failed to create context`.

**To Reproduce**
1. Follow the [instructions](http://www.open3d.org/docs/release/tutorial/Advanced/headless_rendering.html) on headless rendering
2. `cd Open3D/examples/Python/Advanced` _note that the path mentioned in the instructions seems outdated, unless I am missing something_
3. `python3 headless_rendering.py`

**Expected behavior**
No error shows and the example prints the following:

```Capture image 00000
Capture image 00001
Capture image 00002
Capture image 00003
Capture image 00004
Capture image 00005
:
Capture image 00030
```

**Environment**
 - OS: Debian 4.9.65-3+deb9u1 x86_64
 - Python version: 3.5.3
 - Open3D version: v0.9.0 (git tag)
 - Is this remote workstation?: yes
 - How did you install Open3D?: from source using [these](http://www.open3d.org/docs/release/tutorial/Advanced/headless_rendering.html#build-open3d-with-osmesa) instructions (GCCcore/6.4.0)

**Additional context**
I have compiled OSMesa from source, as is described in the [instructions](http://www.open3d.org/docs/release/tutorial/Advanced/headless_rendering.html#install-osmesa).

**Comment by stbjelcevic** [comment]
I am having the exact same issue, hope someone can provide an answer soon!

**Comment by yanghtr** [comment]
pvarvak's pull request could solve the problem. I followed his instruction and solve it. Just a note, for those who could not use LLVM, I found that his method also works with a slight change (I just copy his instructions here and modify some code):

```
    # download OSMesa 19.0.8 release
    (py3env) $ curl -O https://mesa.freedesktop.org/archive/mesa-19.0.8.tar.xz
    (py3env) $ tar xvf mesa-19.0.8.tar.xz
    (py3env) $ cd mesa-19.0.8
    (py3env) $ ./configure --prefix=$HOME/osmesa \
        --disable-osmesa --disable-driglx-direct --disable-gbm --enable-dri \
        --with-gallium-drivers=swrast --enable-autotools --enable-gallium-osmesa
    (py3env) $ make -j$(nproc)
    (py3env) $ make install
    # this installed OSMesa libraries to $HOME/osmesa/lib; in order for Open3D to pick it up
    # LD_LIBRARY_PATH needs to be updated to include it:
    (py3env) $ export LD_LIBRARY_PATH="$HOME/osmesa/lib:$LD_LIBRARY_PATH"
    # this needs to be done for every shell, or you can add it to your .bashrc
    (py3env) $ cd ~/Open3D
    (py3env) $ mkdir build&&cd build
    (py3env) $ cmake -DENABLE_HEADLESS_RENDERING=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON \
    -DPYTHON_EXECUTABLE:FILEPATH=PATH_TO_YOUR_PYTHON
        -DOSMESA_INCLUDE_DIR=$HOME/osmesa/include -DOSMESA_LIBRARY="$HOME/osmesa/lib/libOSMesa.so" \
        ..
    (py3env) $ make -j$(nproc)
    (py3env) $ make install-pip-package

```
