### ISSUE TITLE
when building the solution in “Debug” and “x64” mode on Windows 10-64bit System, errors occur

### ISSUE THREAD

**Issue by zengletian1491** [intel-isl/Open3D#1657]
Compiling Environment：
Windows 10-64bit System
Visual Studio 15 2017

The compiling under “Release” and “x64” mode is OK. However, when building the solution in “Debug” and “x64” mode, errors occur as follows:

  | Code | Interpretations | Project | File | Line
-- | -- | -- | -- | -- | --
Error | LNK1104 | cannot open   file“..\..\lib\Debug\Open3D-gd.lib” | ConvertPointCloud | D:\Software\Open3D\Open3D\build\src\Tools\LINK | 1
Error | LNK1104 | cannot open   file“..\..\..\lib\Debug\Open3D-gd.lib” | ManuallyAlignPointCloud | D:\Software\Open3D\Open3D\build\src\Tools\ManuallyAlignPointCloud\LINK | 1
Error | LNK1104 | cannot open   file“..\..\lib\Debug\Open3D-gd.lib” | ManuallyCropGeometry | D:\Software\Open3D\Open3D\build\src\Tools\LINK | 1
Error | LNK1104 | cannot open   file“..\..\lib\Debug\Open3D-gd.lib” | MergeMesh | D:\Software\Open3D\Open3D\build\src\Tools\LINK | 1
Error | LNK1189 | Library limit   exceeded for 65535 objects | Open3D | D:\Software\Open3D\Open3D\build\src\Open3D\LINK | 1
Error | LNK1104 | cannot open   file“..\..\lib\Debug\Open3D-gd.lib” | ViewGeometry | D:\Software\Open3D\Open3D\build\src\Tools\LINK | 1
Error | LNK1104 | cannot open   file“..\..\lib\Debug\Open3D-gd.lib” | open3d   (Python\open3d) | D:\Software\Open3D\Open3D\build\src\Python\LINK | 1
Error |   | Invalid   distribution name or version syntax: -PYPI-PACKAGE-NAME---PROJECT-VERSION- | pip-package | D:\Software\Open3D\Open3D\build\src\Python\CUSTOMBUILD | 1
Error | MSB6006 | “cmd.exe”exited，code 1。 | python-package | C:\Program   Files (x86)\Microsoft Visual   Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets | 209

Could you please give me some suggestions? Thank you!

**Comment by qianyizh** [comment]
Can you try adding `/bigobj` to your compiler options?
This should address LNK1189 that seems to be the root cause.

**Comment by zengletian1491** [comment]
> /bigobj
I do as what you say! But it does not work！Thank you all the same!

**Comment by zengletian1491** [comment]
However, the same question still exits for Debug mode.
