### ISSUE TITLE
RuntimeError: QH5 qhull precision error (qh_mergefacet)?

### ISSUE THREAD

**Issue by ibrahimLearning** [intel-isl/Open3D#1659]
@adamlofts @benjaminum @martinruenz @griegler 
I am trying  to create  tetrahedral mesh using the following code segment:
```
pcd=o3d.io.read_point_cloud(pcdF, format="xyz")
pcd_voxel_down=pcd.voxel_down_sample(voxel_size=0.3)
TetraMesh=o3d.geometry.TetraMesh.create_from_point_cloud(pcd_voxel_down)
print(TetraMesh)
```
Environment:
Windows 10
Python 3.6 (Anaconda)
open3d version 0.9.0.0
However, it produces the following error:

> TetraMesh=o3d.geometry.TetraMesh.create_from_point_cloud(pcd_voxel_down)
> RuntimeError: QH5 qhull precision error (qh_mergefacet): wide merge for facet f283050 into f283051 for mergetype 7 (ridge).  maxdist 8.5e-06 mindist  0 vertexdist 0.19  Allow with 'Q15' (allow_widemax)
> ERRONEOUS FACET:
> - f283050
>     - flags: top newfacet mergehorizon cycledone dupridge mergeridge1
>     - normal:   0.04582   0.7042 -2.591e-06  -0.7085
>     - offset:   -2782952
>     - vertices: p171171(v12857) p143006(v9483) p75230(v5350) p167898(v1603)
>     - neighboring facets: f272820 f283051 f272818
>     - ridges:
>      - r261562 tested simplicialtop
>            vertices: p143006(v9483) p75230(v5350) p167898(v1603)
>            between f283050 and f272820
>      - r376764 simplicialtop simplicialbot
>            vertices: p171171(v12857) p143006(v9483) p167898(v1603)
>            between f283050 and f272820
>      - r376766 simplicialtop
>            vertices: p171171(v12857) p143006(v9483) p75230(v5350)
>            between f283051 and f283050
>      - r376763 simplicialtop simplicialbot
>            vertices: p171171(v12857) p75230(v5350) p167898(v1603)
>            between f272818 and f283050
> ERRONEOUS OTHER FACET:
> - f283051
>     - flags: top upperDelaunay newfacet dupridge mergeridge2
>     - normal:  -0.04582  -0.7042 2.591e-06   0.7085
>     - offset:    2783020
>     - vertices: p171171(v12857) p143006(v9483) p67203(v7513) p75230(v5350)
>     - neighboring facets: f222945 f283047 f283050 f283052
>     - ridges:
>      - r261559 tested simplicialtop
>            vertices: p143006(v9483) p67203(v7513) p75230(v5350)
>            between f283051 and f222945
>      - r376765 simplicialtop simplicialbot
>            vertices: p171171(v12857) p67203(v7513) p75230(v5350)
>            between f283047 and f283051
>      - r376766 simplicialtop
>            vertices: p171171(v12857) p143006(v9483) p75230(v5350)
>            between f283051 and f283050
>      - r376767 simplicialtop simplicialbot
>            vertices: p171171(v12857) p143006(v9483) p67203(v7513)
>            between f283052 and f283051
> 
> While executing:  | qhull d Qbb Qt
> Options selected for Qhull 2018.0.1.r 2018/12/28:
>   run-id 282852609  delaunay  Qbbound-last  Qtriangulate  _pre-merge
>   _zero-centrum  Pgood  _max-width 1.2e+02  Error-roundoff 4.6e-09
>   _one-merge 4.2e-08  _near-inside 2.1e-07  Visible-distance 2.8e-08
>   U-max-coplanar 2.8e-08  Width-outside 5.6e-08  _wide-facet 1.7e-07
>   _narrow-hull 1.7e-10
> Last point added to hull was p171171.  Last merge was #116851.
> 
> At error exit:
> 
> Delaunay triangulation by the convex hull of 220156 points in 4-d:
> 
>   Number of input sites: 12660
>   Total number of deleted points due to merging: 197
>   Total number of nearly incident points: 207299
>   Number of Delaunay regions: 0
>   Number of non-simplicial Delaunay regions: 17078
> 
> Statistics for:  | qhull d Qbb Qt
> 
>   Number of points processed: 12857
>   Number of hyperplanes created: 228994
>   Number of facets in hull: 37409
>   Number of distance tests for qhull: 91327789
>   Number of distance tests for merging: 3524930
>   Number of distance tests for checking: 0
>   Number of merged facets: 121266
>   Maximum distance of merged point above facet: 2e-07 (4.4x)
>   Maximum distance of merged vertex below facet: -2.1e-06 (46.1x)
> 
> precision problems (corrected unless 'Q0' or an error)
>      40 ridges with multiple neighbors

**Comment by benjaminum** [comment]
Hi, can you provide the data to reproduce this? Does this happen in general for voxel downsampled point clouds?

**Comment by ibrahimLearning** [comment]
@benjaminum 
Yes, you are right. Will I ignore voxel downsampled?

**Comment by benjaminum** [comment]
Do you mean it only happens with voxel_downsample?

**Comment by ibrahimLearning** [comment]
@benjaminum 
No, it was happened without voxel_downsample. I think in Qhull, maybe there is another argument which is used for scaling large data! but how can I use it in open3d?

**Comment by benjaminum** [comment]
Yes, it is a problem in qhull. Unfortunately there is no way to change the parameters to qhull in the open3d interface. Do you have data to reproduce the problem that could be used to test the qhull parameters?

**Comment by ibrahimLearning** [comment]
@benjaminum 
Sorry to say that I want to share the data but I could not due to some rules of my company.

**Comment by benjaminum** [comment]
I understand that. Is it possible to reproduce the problem with some dummy data?

**Comment by benjaminum** [comment]
Please don't hesitate to reopen if there is new information on how we can reproduce the problem.

**Comment by msalazarcgeo** [comment]
Did some one could fix this issue?

**Comment by nissim-kurle** [comment]
Hey any update on this. Tried with a bunch of las files, getting the same error my code is as below.

```
import numpy as np
import laspy as lp
input_path="./File.las"
point_cloud=lp.file.File(input_path, mode="r")
points = np.vstack((point_cloud.x, point_cloud.y, point_cloud.z)).transpose()


alpha = 0.001
print(f"alpha={alpha:.3f}")
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha) #<- Read the api documentation.
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh], mesh_show_back_face=True)
```

create_from_point_cloud_alpha_shape <- this  is what is throwing the error which is as below:

RuntimeError: QH5 qhull precision error (qh_mergefacet): wide merge for facet f134454 into f134436 for mergetype 7 (ridge).  maxdist  0 mindist -7.8e-06 vertexdist 0.29  Allow with 'Q15' (allow_widemax)
ERRONEOUS FACET:

**Comment by Pooja3894** [comment]
import pylas
import laspy as lp
import numpy as np
import open3d as o3d

las = pylas.read('YOUR_FILE_PATH.laz')
las = pylas.convert(las)
point_cloud = pylas.convert(las)
xyz = np.vstack((point_cloud.x, point_cloud.y, point_cloud.z)).transpose()
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyz)
voxel_down_pcd = pcd.voxel_down_sample(voxel_size=0.55)
uni_down_pcd = pcd.uniform_down_sample(every_k_points=25)

alpha = 0.02
print(f"alpha={alpha:.3f}")
tetra_mesh, pt_map = o3d.geometry.TetraMesh.create_from_point_cloud(uni_down_pcd)
o3d.visualization.draw_geometries([tetra_mesh])

downsampling worked for me.
