### ISSUE TITLE
A possible bug in ClusterConnectedTriangles() method

### ISSUE THREAD

**Issue by Akella17** [intel-isl/Open3D#1661]
I think there is a mistake in the **open3d::geometry::TriangleMesh::ClusterConnectedTriangles** method in the following line ([Line 1414](https://github.com/intel-isl/Open3D/blob/1845da3dd6eb8b3d85d7dff2d94b82fcc7123eaf/src/Open3D/Geometry/TriangleMesh.cpp#L1414)):
```C++
tidx = triangle_queue.front();
```
Since **tidx** is also being used in the outer for loop, there is a chance for the outer loop to get shorted without sequentially looping over all the triangles. I suggest you could use a different variable inside the while loop to prevent this.

**Comment by griegler** [comment]
It should not be a problem, because the iteration expression of the loop is executed prior to checking the loop condition (see https://en.cppreference.com/w/cpp/language/for). However, it is not very clean. Would you be willing to submit a PR?

**Comment by Akella17** [comment]
Sure thing. I can submit a PR. Meanwhile, Here is a test case that fails the ClusterConnectedTriangles() function:
```C++
#include <iostream>
#include <fstream>
#include "Open3D/Open3D.h"

using namespace open3d;

int main()
{
    geometry::TriangleMesh mesh;
    mesh.vertices_ = {
    		{0.000000, 0.000000, 0.000000},
    		{0.500000, 0.866025, 0.000000},
    		{1.000000, 0.000000, 0.000000},
    		{0.500000, 0.866025, 0.000000},

            {2.000000, 0.000000, 0.000000},
    		{2.500000, 0.866025, 0.000000},
    		{3.000000, 0.000000, 0.000000},
    		{2.500000, 0.866025, 0.000000},

    		{4.000000, 0.000000, 0.000000},
    		{4.500000, 0.866025, 0.000000},
    		{5.000000, 0.000000, 0.000000},
    		{4.500000, 0.866025, 0.000000},

    		{6.000000, 0.000000, 0.000000},
    		{6.500000, 0.866025, 0.000000},
    		{7.000000, 0.000000, 0.000000},
    		{6.500000, 0.866025, 0.000000}};

    // mesh.triangles_ = {{0, 1, 2}, {0, 2, 3},
    // 				   {4, 5, 6}, {4, 6, 7},
    // 				   {8, 9, 10}, {8, 10, 11},
    // 				   {12, 13, 14}, {12, 14, 15}};

    mesh.triangles_ = {{0, 1, 2}, {12, 14, 15}, 
    				   {4, 5, 6}, {8, 10, 11},
    				   {8, 9, 10}, {4, 6, 7},
    				   {12, 13, 14}, {0, 2, 3}};

    std::vector<int> clusters;
    std::vector<size_t> cluster_n_triangles;
    std::vector<double> cluster_area;
    std::tie(clusters, cluster_n_triangles, cluster_area) = mesh.ClusterConnectedTriangles();

    std::cout << "Num. clusters: " << cluster_n_triangles.size() << std::endl;

    for(int temp: clusters)
    {
    	std::cout << temp << " ";
    }
    std::cout << std::endl;

    return 0;
}
```
The output upon running the code is as follows:
```
Num. clusters: 1
0 -1 -1 -1 -1 -1 -1 0 
```
However, the expected output is:
```
Num. clusters: 4
0 1 2 3 3 2 1 0
```

**Comment by griegler** [comment]
Thanks!
But the output of the code looks weird. `0 -1 -1 -1 -1 -1 -1 0 ` are the cluster indices, but how can they be negative?

**Comment by Akella17** [comment]
That's because the cluster indices of the triangles are initialized to -1. In the example I created, the first and last triangles are connected. The **tidx** iterator in the for loop ([line 1402](https://github.com/intel-isl/Open3D/blob/c5a3500594958f5b8e8da9499b78a6311f619015/src/Open3D/Geometry/TriangleMesh.cpp#L1402)) starts with 0 and then jumps to a value of 7 (last traingle index) inside the while loop ([line 1413](https://github.com/intel-isl/Open3D/blob/c5a3500594958f5b8e8da9499b78a6311f619015/src/Open3D/Geometry/TriangleMesh.cpp#L1413)) that implements the depth-first-search. As a result, the for loop ends after 0th iteration itself.

I will submit a PR that fixes this issue.
