### ISSUE TITLE
Creating pointcloud from RGBD image with a mask? 

### ISSUE THREAD

**Issue by XiangMochu** [intel-isl/Open3D#1662]
Is there any way I can create a point cloud from an RGBD image witn a mask image(like an image of 0 and 1-s) specifying where to create 3D points and where not?
I'm using it in an iterative optimization process, so manually cropping point clouds would be infeasible.

**Comment by griegler** [comment]
The function `PointCloud::CreateFromDepthImage` only projects valid depth values (values that are `>0`) if `project_valid_depth_only` is set to `true`. Hence, you could set all values that you don't want to project to a value `<= 0`.

**Comment by XiangMochu** [comment]
> The function `PointCloud::CreateFromDepthImage` only projects valid depth values (values that are `>0`) if `project_valid_depth_only` is set to `true`. Hence, you could set all values that you don't want to project to a value `<= 0`.

Thank you so much! That's exactly what I needed! It also works on `create_from_color_and_depth`
