### ISSUE TITLE
what is the status with line_width in LineSet?

### ISSUE THREAD

**Issue by aabramovrepo** [intel-isl/Open3D#1665]
Hi All,

   I'm using open3d 0.9.0 with Python 3.6 However, playing with `line_width` like:

`o3d.visualization.RenderOption.line_width=1.0`

or

`o3d.visualization.RenderOption.line_width=10.0`

does not take my anywhere... Is there any possibility to adjust line thickness in the LineSet object?

Thanks in advance for your help!

Best,
Alexey

**Comment by syncle** [comment]
OpenGL does not support line_width. I am quite sure it will be not supported in Open3D neither. Please checkout this post https://github.com/intel-isl/Open3D/issues/1480.

**Comment by aabramovrepo** [comment]
okay, thanks!
