### ISSUE TITLE
unable to import fmt

### ISSUE THREAD

**Issue by Kunika21** [intel-isl/Open3D#1667]
I am unable t import fmt from 3rd party libs.
I observed that the path given in cmake file which i inside folder 3rd party to fmt is set(fmt_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/fmt/include)
INSTALL_HEADERS(fmt)

shouldn't it be rather following?
set(fmt_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/fmt/include/fmt)
INSTALL_HEADERS(fmt)

**Comment by Kunika21** [comment]
Also, when I am using above, fmt is getting included but throwing numerous fatal errors while I am running make for "Open3D/cmakelists.txt' I guess it is because of version issues. I have installed fmt recursively from this repo only. Please suggest a way to resolve.

**Comment by germanros1987** [comment]
Is the issue persisting in 0.10?

**Comment by Kunika21** [comment]
It got resolved by then. I am sorry, forgot to close the issue.
