### ISSUE TITLE
Add setting random seed for SamplePoints methods in the TriangleMesh class

### ISSUE THREAD

**Issue by rowoflo** [intel-isl/Open3D#1682]
**Is your feature request related to a problem? Please describe.**
Currently the `TriangleMesh::SamplePointsUniformlyImpl` function uses a randomly generated number to initialize the random number generator ([here](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Geometry/TriangleMesh.cpp#L445)). This does not allow for the same set of points to be generated on consecutive trials, which is necessary for debugging, development, and unit testing.

**Describe the solution you'd like**
To fix this issue a `seed` argument can be added to the function calls that sets the seed for the random number generator. The `seed` argument can default to a "magic" value that keeps the current functionality (using a different random seed on each trial).

**Comment by chrisranderson** [comment]
This should be closed?

**Comment by rowoflo** [comment]
Yep.

**Comment by wmcnCG** [comment]
Is the random seed available in Python version 0.17? I don't see it in the docs:
http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.sample_points_uniformly

**Comment by Jboulery** [comment]
@rowoflo @chrisranderson Any reason for this `seed` parameter to be removed from version 0.16.0?
It is quite needed for reproducibility purposes...

**Comment by ervteng** [comment]
Can anyone confirm whether `o3d.utility.random.seed` will set the seed for this function as well?
