### ISSUE TITLE
How to add texture to the mesh

### ISSUE THREAD

**Issue by xuexiaoxiaohu** [intel-isl/Open3D#1687]
Hi, I use Poisson reconstruction method to convert the face point cloud with color to mesh,
and the mesh has vertex colors but has no texture.
I want to know how to add texture to the mesh. 
Looking forward to your reply!

**Comment by syncle** [comment]
You would require mesh parameterization to map a mesh to the texture map. Unfortunately, Open3D is not equipped with such functionality. Consider using other tools to make a texture map.

**Comment by xuexiaoxiaohu** [comment]
okay thank you



---Original---

**Comment by xuexiaoxiaohu** [comment]
Very thank you !



---Original---
