### ISSUE TITLE
Error with Python

### ISSUE THREAD

**Issue by robinfays12** [intel-isl/Open3D#1700]
Hello,

When I'm running your code on Jupyter-lab (Windows) here : https://github.com/intel-isl/Open3D/blob/master/examples/Python/ReconstructionSystem/sensors/azure_kinect_recorder.py

I have this problem :
![image](https://user-images.githubusercontent.com/56922763/79070990-5b50f080-7cd9-11ea-97ae-ad2468a3828a.png)

Can you help me please !

Thanks

Robin Fays

**Comment by syncle** [comment]
@robinfays12 could you try using our bug report template so that we can get more input on this?

**Comment by yxlao** [comment]
Please try again in a native python environment (e.g. from ananconda) on Windows. The azure Kinect support is not supported on Jupyter currently since it involves our custom visualizer.
