### ISSUE TITLE
Open3D on Jetson Nano

### ISSUE THREAD

**Issue by WuCrack** [intel-isl/Open3D#1702]
Hey there, as the title says, I'm trying to run some code, which works on a usual ubuntu system, on my new jetson nano (Quad-Core-ARM A57 CPU with 1,43 GHz). I've spend nearly one day trying to make it work and I don't have a clue what to do next.

By simply running the code in jupyter notebook I get the following error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-28e84fa140e2> in <module>
      4 import numpy as np
      5 import time
----> 6 import open3d as o3d
      7 import ezdxf
      8 import pptk

/usr/local/lib/python3.6/dist-packages/open3d/__init__.py in <module>
      7 
      8 if sys.platform == "linux" or sys.platform == "linux2":
----> 9     from open3d.linux import *
     10 elif sys.platform == "darwin":
     11     from open3d.macos import *

/usr/local/lib/python3.6/dist-packages/open3d/linux/__init__.py in <module>
      5 import importlib
      6 
----> 7 globals().update(importlib.import_module('open3d.linux.open3d').__dict__)

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ImportError: /usr/local/lib/python3.6/dist-packages/open3d/linux/open3d.so: cannot open shared object file: No such file or directory

I checked the directory and it is there, also the requested file.
I went to the Terminal and tried to run the file, just to see what happens next, getting the following:

jetson@jetson-desktop:~/Downloads/Open3D-master/util/scripts$ cd /usr/lib/python3.6/importlib
jetson@jetson-desktop:/usr/lib/python3.6/importlib$ dir
abc.py	_bootstrap_external.py	_bootstrap.py  __init__.py  machinery.py  __pycache__  util.py
jetson@jetson-desktop:/usr/lib/python3.6/importlib$ python --init--.py
unknown option --init--.py
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
jetson@jetson-desktop:/usr/lib/python3.6/importlib$ python __init__.py
Traceback (most recent call last):
  File "__init__.py", line 63, in <module>
    from ._bootstrap import __import__
ModuleNotFoundError: No module named '__main__._bootstrap'; '__main__' is not a package
jetson@jetson-desktop:/usr/lib/python3.6/importlib$ python __bootstrap__.py
python: can't open file '__bootstrap__.py': [Errno 2] No such file or directory

I read  about compiling from source, but was not able to do so and follow the steps...

Open3d-python appeares in version 0.3.0.0 when typing: conda list:
open3d-python             0.3.0.0                   <pip>

It's been installed using pip, since conda couldn't find a channel to install it. (Also pip3)
Conda Version is: conda 4.5.12

Do you have an idea what to do next? Do you need more informations on system?

Hope to hear from you =)

**Comment by syncle** [comment]
I cannot clearly see the reason based on the bug report. Could you check the following?
- open3d 0.3.0 seems to be outdated. Could you try with the latest release?
- bootstrap seems not properly imported. Open3D does not use bootstrap, maybe some other reason?

**Comment by WuCrack** [comment]
After deleting all build folders and re-build everything from begining for 3 times, I was able to compile it from source.
