### ISSUE TITLE
Problem with the ball pivoting function

### ISSUE THREAD

**Issue by jokrox** [intel-isl/Open3D#1725]
Hi there, 

I have tried to create a triangle mesh from a simple point cloud. However, the result shows very large holes. Is this algorithm prone to such large holes, or did I choose the wrong radius parameters? 

My code:

        pcd.estimate_normals()
        distances = pcd.compute_nearest_neighbor_distance()
        avg_dist = np.mean(distances)
        
        factor = 1.25
        radius = factor * avg_dist   
        radi =  o3d.utility.DoubleVector([radius, radius * 2])
       
        mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd, radi)

The result: 
<img width="722" alt="open3d" src="https://user-images.githubusercontent.com/64002363/79729957-6e267f00-82f0-11ea-97da-9a054c8263ee.png">

Afterwards I was able to fill the inner holes, but the connection with the outer edge could not be made. Although the distance between all neighboring points is 1.

**Comment by jokrox** [comment]
I was able to figure out the problem. It was due to faulty normals.

**Comment by q-chen95** [comment]
hi, i meet the same problem, how to solve this?
