### ISSUE TITLE
Is it possible to implement Euclidean Cluster Extraction in Open3D?

### ISSUE THREAD

**Issue by crea397** [intel-isl/Open3D#1733]
I want to do the clustering fast.

I thought that cluster_dbscan in Open3D or Euclidean Cluster Extraction in PCL would be a good choice for clustering point clouds.

What is the difference between these two?
Is cluster_dbscan not very fast?

Is it possible to implement Euclidean Cluster Extraction in Open3D?

**Comment by griegler** [comment]
DBScan has a notion of density and I think the wikipedia article explains it quite well (https://en.wikipedia.org/wiki/DBSCAN#Abstract_Algorithm). Euclidean Cluster Extraction just connects all points that are in a given radius to each other (does not handle noise/outliers). In the end, you have to query for both algorithms the neighboring points.


> Is it possible to implement Euclidean Cluster Extraction in Open3D?

Definitely. If you like, I can help you if you want to contribute it.
