### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by swinterbotix** [intel-isl/Open3D#1734]
**Describe the bug**
When installing open3d from pip, an Error message appears saying...

ERROR: jsonschema 3.2.0 has requirement six>=1.11.0, but you'll have six 1.10.0 which is incompatible.

**To Reproduce**
1. In a terminal (not virtual environment), type 'pip install open3d'
2. Wait a few seconds
3. See error

**Expected behavior**
No error message to appear and that the right version of 'six' is installed

**Screenshots**

![image](https://user-images.githubusercontent.com/52669772/80043794-48ec6900-84c8-11ea-9299-9d637bebfb7f.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 2.7.12
 - Open3D version: 0.9.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip version 20.0.2

**Additional context**

Open3d still imports correctly in python, but I'm not sure how necessary that dependency ( jsonschema 3.2.0) is.

**Comment by yxlao** [comment]
@swinterbotix could you try with python 3? This should avoid the issue with `six`. In the future, we'll be dropping python 2 support.

**Comment by swinterbotix** [comment]
I was already able to get it working using Python 3. I wanted to try using Python 2 though so that I could use Open3D in ROS (Kinetic and Melodic).

**Comment by syncle** [comment]
@swinterbotix Unfortunately, we are spending less time to check compatibility issue with Python 2.x. In the future, as @yxlao mentioned, Open3D will be released only with Python 3.x. Please understand this, since we are trying to focus on up-to-date environments. If you are willing to give a hand to solve the issue, that would be great though :)

**Comment by swinterbotix** [comment]
Ok, thanks for the update! If I come up with anything, I'll let you know.
