### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by Seealso** [intel-isl/Open3D#1743]
#  I run the open3d program in docker to exit
##  thank you very much
![20200424104625](https://user-images.githubusercontent.com/39869869/80169860-228a1300-8619-11ea-8ab1-a44806eb3586.jpg)

**Comment by syncle** [comment]
@Seealso Please provide more details to understand the situation, and use the TEMPLATE to report the issue.

**Comment by syncle** [comment]
Closing this issue since there is not much evidence to help. @Seealso please reopen this issue if needed.
