### ISSUE TITLE
Disparity map to point cloud using Open3d?

### ISSUE THREAD

**Issue by YangJae96** [intel-isl/Open3D#1744]
Hello, I am undergrated student in Seoul, Kookmin University. 

 I ran the tutorial (REDWOOD) creating point cloud by using one rgb image and depth image which is obtained by RGB-Depth camera.  
 
Just like this. I want to know whether there is a way to create point cloud using disparity map, which is created by stereo vision algorithm. Does open3d not support this stereo??

**Comment by syncle** [comment]
@YangJae96, if you transform disparity map to depth map, you can use ``create_from_depth_image``. 
You can make a depth map from the simple formula:
 ``depth = baseline * focal_length / disparity``. 

Open3D is not providing a direction function that changes disparity map to point cloud yet. If you know the standard disparity map format, it would be great to support (if you are willing to contribute, we can discuss further)

**Comment by YangJae96** [comment]
Thank you Professor. Can I ask you one more question? 
I  have produced the depth map by the equation you provided me. 
I also have seen the function create_from_depth_image. which  is inside Open3d.geometry.PointCloud!
But here I am facing a problem with producing a pointcloud. 

The top image is disparity map and the one below is depthmap created by the equation.
depth = baseline * focal_length / disparity.
![disparity and depthmap](https://user-images.githubusercontent.com/57695621/80473649-65354d80-8981-11ea-9422-47e71cc4ba7c.png)
![pointcloud](https://user-images.githubusercontent.com/57695621/80473652-66667a80-8981-11ea-9f6e-a7a0002f9b9b.png)
The top image is a point cloud.

I have used the open3d.camera.PinholeCameraIntrinsic method set_intrinsics(self, width, height, fx, fy, cx, cy)  to set the camera parameter and then used the function 
create_from_depth_image. But the result was a bad pointcloud.

I can't seem to find out what the problem is. The disparity image came from two images which is called stereo-pair.  Would this be a problem??  or is there something 
I am missing.

I am doing a school project and I really want to find out the issue
I appreciate your great help in advance.

**Comment by syncle** [comment]
Check every term in the equation are using the same units. To analyze point set, try press '-' key to make the point set more readable. It is often the case the visualized disparity map has such artifacts across the object's boundary.
