### ISSUE TITLE
Question on 3Dgeometry bounding boxes

### ISSUE THREAD

**Issue by achiatti** [intel-isl/Open3D#1746]
thanks for this great open resource!
I am using the Python binding and I have a question on the `open3d.geometry.OrientedBoundingBox` class.
When invoking the `get_box_points()` method in what order are the points returned?
I would need to compute the width, height and depth of the 3D box.

**Comment by griegler** [comment]
You can have a look [here](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Geometry/BoundingVolume.cpp#L114). It also shows how you could use the attributes `R`, `center`, and `extent` of `OrientedBoundingBox` to get the points in the order that you want.

**Comment by achiatti** [comment]
Thank you!

**Comment by stephen-derosa** [comment]
this leads to a 404 not found :/

**Comment by cwreynolds** [comment]
@stephen-derosa: I'm no Open3D expert, but I can wander aimlessly around a directory tree with the best of them. Looks like in the intervening three years, that file has moved to: 
https://github.com/isl-org/Open3D/blob/master/cpp/open3d/geometry/BoundingVolume.cpp

**Comment by Petros626** [comment]
@cwreynolds @griegler for my understanding it's this order?
```txt   
             4-------- 5
           /|         /|
          6 -------- 7 .
          | |        | |
          . 0 -------- 1
          |/         |/
          2 -------- 3

**Comment by cwreynolds** [comment]
@Petros626: Sorry I have not used them and have no insight.
