### ISSUE TITLE
Camera Intrinsic Matrix for System Reconstruction 

### ISSUE THREAD

**Issue by ArlenisChS** [intel-isl/Open3D#1750]
Hi there, sorry to bother, but I don’t get the question that I’m about to ask from your documentation. Thanks in advance. 
In order to make your reconstruction system work with another camera, you need to set the camera intrinsic matrix. But, as far as I’m concerned, RGB-D cameras have tow types of sensors: the RGB camera and the Depth camera. So, which camera intrinsic matrix is it?? The parameters form the RGB camera or the ones form the Depth camera??
Am I missing something?? Is it my mistake?? Again, sorry to bother. Thank!!

**Comment by noahstier** [comment]
The two cameras (RGB and depth) are assumed to have exact pixel-for-pixel correspondence, in other words they are assumed to have the same intrinsic and extrinsic matrices.

If your depth and color images don't correspond pixel-for-pixel, you'll need to register them.

**Comment by ArlenisChS** [comment]
> The two cameras (RGB and depth) are assumed to have exact pixel-for-pixel correspondence, in other words they are assumed to have the same intrinsic and extrinsic matrices.
> 
> If your depth and color images don't correspond pixel-for-pixel, you'll need to register them.

Thanks for your feedback!! Much appreciated!!
