### ISSUE TITLE
 'open3d.open3d.visualization.ViewControl' object has no attribute 'set_zoom'

### ISSUE THREAD

**Issue by EnricoBeltramo** [intel-isl/Open3D#1751]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Error when using o3d.visualization.draw_geometries with zoom parameter:
C:\Projects\Telecamere3D\Open3D\examples\Python\open3d_tutorial.py in jupyter_draw_geometries(geoms, window_name, width, height, left, top, point_show_normal, mesh_show_wireframe, mesh_show_back_face, lookat, up, front, zoom)
     51         vis.get_view_control().set_front(front)
     52     if zoom is not None:
---> 53         vis.get_view_control().set_zoom(zoom)
     54     if interactive:
     55         vis.run()

AttributeError: 'open3d.open3d.visualization.ViewControl' object has no attribute 'set_zoom'

**To Reproduce**
1. cd  examples\Python\Basic\rgbd_image.ipynb
2. python jupter notebook
3. See error

**Expected behavior**
a working sample

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX Mojave, Ubuntu 16.04, Windows 10.0] win10
 - Python version: 3.7.6
 - Open3D version: last stable
 - Is this remote workstation?:no
 - How did you install Open3D?: pip or conda or build_from_source (provide build method, such as GCC, Xcode, Visual Studio, and so on) conda

**Additional context**

**Comment by EnricoBeltramo** [comment]
I found that reverting the code of examples to tag 0.9.0 now all works. Is that correct? The examples of master aren't compatible with pip installer version?

**Comment by griegler** [comment]
Yes, the jupyter tutorials assume that you have the latest open3d build from master.

**Comment by joisse1101** [comment]
I'm using the latest open3d build from master but I am unable to run the code. I have a similar error: AttributeError: 'open3d.open3d.visualization.ViewControl' object has no attribute 'set_lookat'

How do I change the code of examples to tag 0.9.0?

**Comment by robotsir** [comment]
I think the issue is the documentation and examples version number are messed up.
