### ISSUE TITLE
Question: Add exsting normals to  open3d.geometry.PointCloud

### ISSUE THREAD

**Issue by kumuji** [intel-isl/Open3D#1753]
I can't find a way how to do that. 
open3d.geometry.PointCloud.normals is a property, and there is no interface to add them during initialization.

How to add normals to existing point cloud

**Comment by GericoVi** [comment]
Did you manage to get a solution to this? I can't seem to assign an existing array of normals to the point cloud object, but assigning to the `points` property works:

```python
pcd = open3d.geometry.PointCloud()
pcd.points = open3d.utility.Vector3dVector(pos_numpy) # works
pcd.normals = open3d.utility.Vector3dVector(normals_numpy) # doesn't work
```

The error is: `libc++abi: terminating with uncaught exception of type pybind11::cast_error:`
