### ISSUE TITLE
Installing Open3d under Ubuntu 20.04 with pip fails

### ISSUE THREAD

**Issue by FabianSchuetze** [intel-isl/Open3D#1758]
I cannot install open3d on Ubuntu 20.04 with pip. When I type:
`pip3 install open3d` I receive: 

```python
    ERROR: Could not find a version that satisfied the requirement opend3d (from versions: none)    
    ERROR: No matching distribution found for open3d
```

I'm working with Ubuntu 20.04 as a Windows Subsystem with pip 20.0.2. I can install other packages with pip such as numpy.

Do you have any advice for me how to proceed?

**Comment by g2ragrawal** [comment]
python version can also cause problem please check #1580

**Comment by FabianSchuetze** [comment]
Thanks @g2ragrawal , that was helpful to me!
