### ISSUE TITLE
How to save an image of any particular size using Open3D

### ISSUE THREAD

**Issue by bharadwajdhornala** [intel-isl/Open3D#1759]
Hi. thanks for a great library. I can save image using vis.capture_screen_image(). Suppose I want to save the image of size 256x256. Is there any method to do this?

Thanks!!

**Comment by g2ragrawal** [comment]
do you want to capture image with or without opening window?

**Comment by bharadwajdhornala** [comment]
Capture the image of any particular size without opening window

**Comment by g2ragrawal** [comment]
as of now you can do like this

import open3d
import numpy
import matplotlib.pyplot as plt
mesh=open3d.geometry.TriangleMesh()
s=mesh.create_sphere(5)
vis=open3d.visualization.Visualizer()
vis.create_window(visible=False)
vis.add_geometry(s)
def move_forward(vis):
  image = vis.capture_screen_float_buffer(False)
  image=numpy.asarray(image) 
  plt.imsave("test.png",image)
  vis.register_animation_callback(None)
  vis.destroy_window()
  return False
vis.register_animation_callback(move_forward)

vis.run()

resize screen float buffer
