### ISSUE TITLE
[improvement][windows]Branch of master codes doesn't not match online document

### ISSUE THREAD

**Issue by caibf** [intel-isl/Open3D#1764]
**Describe the bug**

Python wrapper `select_down_sample(self, indices, invert=False)` has been replaced with `select_by_index(self, indices, invert=False)` in the branch of **master**. However, [the onlince document](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud) following with this branch is not up-to-date.

The examples of the branche of **demo-scene** is not up-to-date yet. For example, [the online tutorial](http://www.open3d.org/docs/release/tutorial/Advanced/pointcloud_outlier_removal.html) used fillname **outlier_removal.py**, but the actual name is **pointcloud_outlier_removal.py**.

**Comment by syncle** [comment]
I assume you are looking at the 0.9 documentation http://www.open3d.org/docs/release/
The doc page by default shows the latest release of the library.

If you want to see the documentation of the master branch, please check http://www.open3d.org/docs/latest/
