### ISSUE TITLE
Is it possible to implement gridmap in open3d?

### ISSUE THREAD

**Issue by crea397** [intel-isl/Open3D#1765]
Set up a grid map in the xy plane represented by a rectangular grid with a certain width, and compute the dispersion in the z-axis in each cell.

In each cell, if the average value in the z-axis direction exceeds the threshold value, the data in the cell is treated as a three-dimensional object.

How to do this in open3D?

**Comment by syncle** [comment]
How about using VoxelGrid? http://www.open3d.org/docs/release/python_api/open3d.geometry.VoxelGrid.html
You may voxelize point sets, and take a custom operation over z-axis.

**Comment by crea397** [comment]
Thank you for your reply.

I have tried VoxelGrid.
I tried to run VoxelGrid.voxels to get the coordinates for each Voxel.
However, I couldn't run it with the following error.

`print(voxel.voxels)
TypeError: unhashable type: 'numpy.ndarray'`

Why do I get an error? voxel_grid.voxel_size was able to run.

If I use the VoxelGrid, how do I get the coordinates for each Voxel?
Also, how do I get the average of the z-coordinates of a cell (or Voxel) in a given xy plane?

Thank you very much.

**Comment by crea397** [comment]
**Solved**
I'm sorry.
I was looking at version 0.9 of the document.
I compiled Open3D from the source and reinstalled it.
Then, referring to the latest version of the documentation, I was able to get the coordinates of Voxel using VoxelGrid.get_voxels().
Thank you very much.
