### ISSUE TITLE
Is there any API that can achieve the effect of augmented reality visualization?

### ISSUE THREAD

**Issue by wuxiaolang** [intel-isl/Open3D#1766]
Is there any API that can achieve the effect of augmented reality visualization? For example, use the image obtained by the camera as a background. For example, use the image obtained by the camera as the background, and then display the 3D model from the three-dimensional space according to the camera model to the background. Thank you.

**Comment by syncle** [comment]
@wuxiaolang thanks for the request, but It's a bit out of scope that we are aiming for. Could you take a look https://github.com/ValveSoftware/openvr instead?
