### ISSUE TITLE
Close the Visualizer when needed

### ISSUE THREAD

**Issue by SystemDiagnosticss** [intel-isl/Open3D#1768]
Hello. I need to render 3d object without X server, after that make headless screenshot(without X server) and close  window immediately from code and finish my Python script. But now I need to press Ctrl+z or Q for close window.
How I can close Visualizer from code without Ctrl+z in Terminal or Q in Visualizer window ????

**Comment by syncle** [comment]
Could you take a look at this example?
http://www.open3d.org/docs/release/tutorial/Advanced/non_blocking_visualization.html
The window should be closed with ``vis.destroy_window()``

**Comment by Petros626** [comment]
@syncle link is down. https://www.open3d.org/docs/release/tutorial/visualization/non_blocking_visualization.html
