### ISSUE TITLE
Don't load textures in gltf

### ISSUE THREAD

**Issue by SystemDiagnosticss** [intel-isl/Open3D#1775]
**Describe the bug**
Don't load textures in gltf

**To Reproduce**
1. cd '...path'
2. python3 app.py
3. Console log: 
[Open3D INFO] The file contains more than one mesh. All meshes will be loaded as a single mesh.
geometry::TriangleMesh with 68510 points and 118356 triangles.
Field of view:  5.0

**Expected behavior**
I am loading gltf via  `mesh = open3d.io.read_triangle_mesh(...path)` but Visualizer dont load textures. Also in my case I have only 1 mesh pic.

**Screenshots**
![my](https://user-images.githubusercontent.com/15822541/80764804-230b3800-8b4a-11ea-999a-9c4a09d0f623.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Python version: 3.7
 - Open3D version: 0.9.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip3)

**Additional context**
My gltf:
[bee-lowpoly.zip](https://github.com/intel-isl/Open3D/files/4561694/bee-lowpoly.zip)

**Comment by syncle** [comment]
At this moment, Open3D only supports obj format for loading a texture map. We will put this request on our to-do-list, but it would be great if you give us a hand. :)

**Comment by SystemDiagnosticss** [comment]
@syncle Thanks for answer. Does obj with multiple textures support also or need only one texture img?

**Comment by germanros1987** [comment]
This is solved in the new rendering module. We have full support for gltf
