### ISSUE TITLE
python3.8 support (pypi and conda releases)

### ISSUE THREAD

**Issue by jccurtis** [intel-isl/Open3D#1781]
**Is your feature request related to a problem? Please describe.**

The current releases on [pypi](https://pypi.org/project/open3d/) and [conda](https://anaconda.org/open3d-admin/open3d) do not officially support python3.8

**Describe the solution you'd like**

Update the trove params to support python3.8

**Describe alternatives you've considered**

I haven't tried to build from source in a `conda` env but this would be a temporary fix. I'm downgrading to `python3.7` for now.

**Additional context**

Running in a `conda` env on macOS 10.15.

**Comment by yxlao** [comment]
Yes, we'll be supporting 3.8 in the next release.

**Comment by davidgraeff** [comment]
May I know why this ticket is closed? python 3.9 is still not listed as a supported environment in the docs or on any of the above mentioned package manager repositories. Using open3d is right now not a straight forward experience on modern distributions that only have python 3.9 like Fedora.
