### ISSUE TITLE
o3d.visualization.draw_geometries([img]). Img cannot be displayed in a format of. PNG type, and it will report an error.

### ISSUE THREAD

**Issue by HuQingsheng520** [intel-isl/Open3D#1784]
**IMPORTANT: Please use the following template to report the bug.**
_____
Traceback (most recent call last):
  File "E:/python_coding/Open3D-master/examples/Python/Basic/open3d_day13.py", line 38, in <module>
    o3d.visualization.draw_geometries([img])
RuntimeError: [Open3D ERROR] [CreateCoordinateFrame] size <= 0
**Describe the bug**
o3d.visualization.draw_geometries([img]).The function cannot display a two-dimensional image
**To Reproduce**
no

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/49577570/80860754-8c02c500-8c9c-11ea-8b92-a1bfa2f4bfa7.png)
![image](https://user-images.githubusercontent.com/49577570/80860758-958c2d00-8c9c-11ea-8a18-a49812e1af29.png)

**Environment (please complete the following information):**
 - OS:  Windows 10.0
 - Python version: 3.6.6
 - Open3D version: 0.9.0
 - Is this remote workstation?:  no
 - How did you install Open3D?: pip or conda or build_from_source (provide build method, such as GCC, Xcode, Visual Studio, and so on) pypi

**Additional context**
Img cannot be displayed in a format of. PNG type, and it will report an error. I hope that the function of displaying two-dimensional images can be added later, or opencv's processing on two-dimensional images is quite good.

**Comment by jwesolo** [comment]
See also:

https://github.com/intel-isl/Open3D/issues/1697
https://github.com/intel-isl/Open3D/issues/1678

**Comment by Zumbalamambo** [comment]
+1

**Comment by prewettg** [comment]
Tested with 0.12 and this appears to be fixed. Also works with the new visualizer using `o3d.visualization.draw(bg_image=img)`.
