### ISSUE TITLE
Python online documentation lacks azure kinect related functions / classes

### ISSUE THREAD

**Issue by daniel1v** [intel-isl/Open3D#1788]
From Open3D version 0.9 on, the python online documentation does not include the azure kinect  related features anymore.

Steps to reproduce:
visit [this site](http://www.open3d.org/docs/release/python_api/open3d.io.html) (v0.9 documentation)

Expected behavior:
visit [this site](http://www.open3d.org/docs/0.8.0/python_api/open3d.io.html) (v0.8 documentation)

**Comment by yxlao** [comment]
This is confirmed. The Kinect docs are not enabled in our Travis doc build by default. Will work on it.
