### ISSUE TITLE
get_point_indices_within_bounding_box sometimes return empty list even though there are many points within the box

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#1792]
Hello,

I'm facing an issue of empty list returned from the  get_point_indices_within_bounding_box, even though there are many points in the box that can be proven by 

`o3d.visualization.draw_geometries([bbox,pcd])`

What can be the problem? Too big? Here are my bbox prints
bbox points
[[ 1.91543903e+02  4.06216233e+02 -9.44216210e+00]
 [ 4.87694126e+02 -1.17739071e+02 -4.88146456e+00]
 [-2.61239117e+02  1.50335185e+02 -4.71488369e+00]
 [ 1.91985260e+02  4.07383736e+02  9.60267055e+01]
 [ 3.53524628e+01 -3.72452616e+02  1.05314681e+02]
 [-2.60797760e+02  1.51502688e+02  1.00753984e+02]
 [ 4.88135483e+02 -1.16571568e+02  1.00587403e+02]
 [ 3.49111062e+01 -3.73620119e+02 -1.54186151e-01]]

bbox is empty: False
bbox volume: 33018203.09962348
Center
[113.44818306  16.88180837  47.93625968]

Thank you in advance!

**Comment by griegler** [comment]
Is it possible for you to share your point cloud and the code to reproduce this?

**Comment by 1939938853** [comment]
Hello,

Here is the code to generate the box and get the index from my pcd
`import open3d as o3d
import numpy as np

pcd = o3d.io.read_point_cloud("pcd.pcd")
#o3d.visualization.draw_geometries([pcd])

xyz = np.array([[ 191.37540588,  406.16873721,   -3.95729281],
    [ 487.20517632, -116.87310088 ,  -4.83974038],
    [-260.37880283,  150.66017318,   -4.72208136],
    [  35.44502621, -372.4029362 ,    5.01155065],
    [ 191.37540588,  406.16873721,   96.04270719],
    [ 487.20517632, -116.87310088,   95.16025962],
    [-260.37880283,  150.66017318,   95.27791864],
    [  35.44502621, -372.4029362,   105.01155065]])

points = o3d.utility.Vector3dVector(xyz)

bbox = o3d.geometry.OrientedBoundingBox.create_from_points(points)
idx = bbox.get_point_indices_within_bounding_box(pcd.points)
print("The length of the selected point indeces within the bbox")
print(len(idx))
o3d.visualization.draw_geometries([pcd, bbox])
`
Here is the pcd file. After downloading rename it to pcd.pcd.
[pcd.zip](https://github.com/intel-isl/Open3D/files/4586598/pcd.zip)

Thank you in advance!

**Comment by griegler** [comment]
Should be fixed in #1798.

**Comment by 1939938853** [comment]
Thank you for the quick fix. Is it committed  in master branch? Why I cannot find it?

**Comment by griegler** [comment]
It is currently under review and will then be merged into master. If you need it now, you could clone the `oobfix` branch from here https://github.com/griegler/Open3D/tree/oobfix

**Comment by 1939938853** [comment]
The fix works well. Thank you!

**Comment by enting8696** [comment]
@1939938853 
Sorry to disturb you
I still want to ask how you can solve it
There is a point cloud in the bounding box
Upgrade version?

**Comment by NikkieStella** [comment]
I am also very curious as i face the same issue @1939938853  @griegler
