### ISSUE TITLE
Mesh geometry Selection

### ISSUE THREAD

**Issue by ohadNanovel** [intel-isl/Open3D#1825]
Can you add the option to select Mesh Geometries from Visualizer on runtime and invoking event when chosen?
As for now, only points from Pointclouds are able to be chosen.

### code example:
-   create cube
 ```
mesh_box = o3d.geometry.TriangleMesh.create_box(width=width,height=height, depth=depth)
mesh_box.compute_vertex_normals() # create shadows
mesh_box.paint_uniform_color([0, 0.9, 0])
mesh_box.translate([x_pos,z_pos,t_pos], relative=False)
```

- show and select the created 'mesh_box' Geometry with "shift + left click"
```
o3d.visualization.draw_geometries_with_editing([mesh_box ])
```

**Comment by shalini-maiti** [comment]
If I understand correctly, you're looking for a way to select vertices from a triangle mesh in the visualizer mode.

I found that this method is effective - open3d.visualization.VisualizerWithVertexSelection. We can use this exactly like how we used the visualizer with editing for pointclouds.

`  vis = o3d.visualization.VisualizerWithVertexSelection()
    vis.create_window()
    vis.add_geometry(mesh)
    vis.run()  
    vis.destroy_window()
    return vis.get_picked_points()`

When the visualizer opens up, on pressing shift you are shown all the vertices. Go ahead and select a bounding box of the vertices you need.

- reference ( http://www.open3d.org/docs/latest/python_api/open3d.visualization.VisualizerWithVertexSelection.html)

**Comment by germanros1987** [comment]
We are working on this for 0.12.

**Comment by prewettg** [comment]
0.12 supports selecting vertices from a TriangleMesh using `open3d.visualization.draw()` (see [`examples/python/gui/draw.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py)) and `open3d.visualization.O3DVisualizer` (see [the implementation of the `draw()` function in `python/open3d/visualization/draw.py`](https://github.com/intel-isl/Open3D/blob/master/python/open3d/visualization/draw.py)). 0.13 will support polygon selection (see #3252)

**Comment by joycewangsy** [comment]
how can i save the points i selected? thx

**Comment by olealgoritme** [comment]
> how can i save the points i selected? thx

press 'S' to save the selected polygon.

**Comment by manavkulshrestha** [comment]
> 0.12 supports selecting vertices from a TriangleMesh using `open3d.visualization.draw()` (see [`examples/python/gui/draw.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py)) and `open3d.visualization.O3DVisualizer` (see [the implementation of the `draw()` function in `python/open3d/visualization/draw.py`](https://github.com/intel-isl/Open3D/blob/master/python/open3d/visualization/draw.py)). 0.13 will support polygon selection (see #3252)

Looks like this link is dead and VisualizerWithVertexSelection is depricated and not to be used (the only indication of this appears to be in github issues, not docs). Can I get a good reference to what is supposed to be used?
