### ISSUE TITLE
TriangleMesh.crop() not working consistently

### ISSUE THREAD

**Issue by scimad** [intel-isl/Open3D#1826]
TriangleMesh.crop() is returning geometry::TriangleMesh with 0 points and 0 triangles sometimes. This however isn't happening every time I am running the following code.

I am trying to crop the planar region of a TriangleMesh, for which I first take all the `mesh.vertices` to a `PointCloud` and get `pcl.segment_plane()`. After getting the index of inliers, I create a bounding box from the points and crop the mesh accordingly.

```
o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Debug)
source_mesh = o3d.io.read_triangle_mesh("../../ply/integrated_slab4.ply")
o3d.utility.set_verbosity_level(o3d.utility.Debug)

###
### pcl_name, pcl, eps =  "source_mesh", source_mesh.sample_points_uniformly(int(1e5)), 0.05
###

pcl = o3d.geometry.PointCloud(source_mesh.vertices)
plane, inlier_indices = pcl.segment_plane(0.04, 1000, 100)

consensus_set = []
for index in inlier_indices:
    consensus_set.append(pcl.points[index])

print ("Number of points in consensus_set=", len(consensus_set))

inlier_points = o3d.utility.Vector3dVector(consensus_set)
bounding_box = o3d.geometry.OrientedBoundingBox.create_from_points(inlier_points)
mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.6)
o3d.visualization.draw_geometries([source_mesh] + [bounding_box] + [mesh_frame])

cropped_mesh = source_mesh.crop(bounding_box)
print(source_mesh, cropped_mesh)
o3d.visualization.draw_geometries([cropped_mesh] + [mesh_frame]+[bounding_box])

```

Surprisingly, I am getting correctly cropped planar mesh sometimes and completely empty mesh in random order. I can't be due to some random behavior in the RANSAC for `PointCloud.segment_plane()` as I am always getting consistent set of inliers.

[Demo Video of the problem](https://drive.google.com/file/d/1TaPkub66lQD7qqfRawz-MIirfCfvRewp/view?usp=sharing)

Environment:
 - Ubuntu 19.10
 - Python 3.7.5
 - Open3D 0.9.0.0 from pip

**Comment by griegler** [comment]
Can you try #1798.
