### ISSUE TITLE
Invalid tetra in TetraMesh when creating TriangleMesh with alpha shapes

### ISSUE THREAD

**Issue by NicoBux** [intel-isl/Open3D#1829]
When using #1621  work around for creating TraingleMesh from a point cloud with 'TriangleMesh.create_from_point_cloud_alpha_shape()', I get the following error: 
`[Open3D ERROR] [CreateFromPointCloudAlphaShape] invalid tetra in TetraMesh`

**To Reproduce**
1. Create point cloud by manually creating PointCloud() object, then adding in points from a Vector3dVector()
2. run:
` alpha = .03`
`tetra_mesh, pt_map = o3d.geometry.TetraMesh.create_from_point_cloud(pcd)`
`mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha, tetra_mesh, pt_map)`
3. See error

**Environment (please complete the following information):**
 - OS: [Windows 10.0]
 - Python version: 3.6.7
 - Open3D version: 0.9.0.0
 - Is this remote workstation?:  no
 - How did you install Open3D?: conda 

````

**Comment by griegler** [comment]
Maybe visualize your tetra mesh and the point cloud. Probably there is a tetra that has a triangle with zero area? The problem is [here](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Geometry/SurfaceReconstructionAlphaShape.cpp#L90-L94) that results in a 0 and would lead to a div by 0.

**Comment by LyceanEM** [comment]
I have experienced the same problem, with the same python version and Open3D version. Is there any way to work around this at present?

**Comment by buxbomber** [comment]
@griegler Unfortunately I am not able to visualize any Geometries. I get an error like: `Invoked with: geometry::TetraMesh with 5481 points and 34003 tetrahedra.` when using `o3d.visualization.draw_geometries(tetra_mesh)`. This persists with point clouds as well. I wonder if the issue is due to my conda install?

**Comment by buxbomber** [comment]
@griegler Unfortunately I am not able to visualize any type of Geometry. I get as error like `Invoked with: geometry::TetraMesh with 5481 points and 34003 tetrahedra.`. This happens with pointclouds. Is there another way to filter and remove zero-area tetra?

**Comment by griegler** [comment]
@buxbomber Is it possible to share a point cloud where this problem happens?

**Comment by buxbomber** [comment]
@griegler Oh jeez I did not realize `draw_geometries()` required a list as argument. The visualization works fine. However, I still am unsure on how to clean up the tetra_mesh.

**Comment by lschfr** [comment]
got the same problem with Open3D 0.10.0.1, Python 3.7.4, Windows 10 and a tetra-mesh built out of a point-cloud

**Comment by jaredbaggen** [comment]
Also have the same problem, Open3D 10.0.1 Python 3.8, Mac 10.15.6.

**Comment by Wuestengepard** [comment]
I also have this Problem. Drawing the Mesh and Pointcloud results in that Picture:
![image](https://user-images.githubusercontent.com/61849085/98657221-e95d8a00-2341-11eb-8bec-ba954a93c9a7.png)

After creating the TetraMesh, i also get the error:
[Open3D ERROR] [CreateFromPointCloudAlphaShape] invalid tetra in TetraMesh

The code i use:

`alpha = 0.002`
 `print(f"alpha={alpha:.3f}")`
` tetra_mesh, pt_map = o3d.geometry.TetraMesh.create_from_point_cloud(pcd)`
` o3d.visualization.draw_geometries([pcd,tetra_mesh], mesh_show_back_face=True)`
 `mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha, tetra_mesh, pt_map)`
` mesh.compute_vertex_normals()`
` o3d.visualization.draw_geometries([mesh], mesh_show_back_face=True)`

**Comment by mett96** [comment]
I have the same problem, any updates?

**Comment by halmusaibeli** [comment]
Same issue with me.
![image](https://user-images.githubusercontent.com/80288863/110772885-56fac380-8219-11eb-98d7-bf2839b91a38.png)

Code I am using:

`alpha = 0.03`
`print(f"alpha={alpha:.3f}")`
`tetra_mesh, pt_map = o3d.geometry.TetraMesh.create_from_point_cloud(pcd)`
`o3d.visualization.draw_geometries([pcd,tetra_mesh], mesh_show_back_face=True)`
`mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha, tetra_mesh, pt_map)`
`mesh.compute_vertex_normals()`
`o3d.visualization.draw_geometries([mesh], mesh_show_back_face=True)`

Output:

`mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha, tetra_mesh, pt_map)`
`RuntimeError: [Open3D ERROR] [CreateFromPointCloudAlphaShape] invalid tetra in TetraMesh`

**Comment by BenT00le** [comment]
im having the same issue is there any way to identify and remove the zero area triangles or the points that cause them before creating the tetramesh 
![Capture](https://user-images.githubusercontent.com/10393062/110853202-31e17180-8268-11eb-9760-9454878b8730.PNG)


    pcd.points = o3d.utility.Vector3dVector(surface)
    o3d.visualization.draw_geometries([pcd])
    alpha = 0.03
    print(f"alpha={alpha:.3f}")
    tetra_mesh, pt_map = o3d.geometry.TetraMesh.create_from_point_cloud(pcd)
    o3d.visualization.draw_geometries([tetra_mesh])
    m = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha, tetra_mesh, pt_map)
    m.compute_vertex_normals()
    o3d.visualization.draw_geometries([m], mesh_show_back_face=True)

**Comment by colinlaney** [comment]
> Maybe visualize your tetra mesh and the point cloud. Probably there is a tetra that has a triangle with zero area? The problem is [here](https://github.com/intel-isl/Open3D/blob/1728fc12934561321623c8798ef3b83059137321/cpp/open3d/geometry/SurfaceReconstructionAlphaShape.cpp#L89-L93) that results in a 0 and would lead to a div by 0.

So, @griegler, it would be nice to exit the current iteration rather than the entire for loop, and only ignore single tetrahedron rather than the entire mesh.

**Comment by runette** [comment]
any news on this - I am hitting in this in about 10 out of about 250 point clouds. All i am doing i bring in the point cloud and then 

```
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(cluster)
pcd.estimate_normals()
try:
    mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, .3)
except Exception as e:
    print(f"Cluster {array['ClusterID'][0]} error {str(e)}")
    mesh = o3d.geometry.TriangleMesh()
return mesh
```
