### ISSUE TITLE
code=98 (cudaErrorInvalidDeviceFunction)

### ISSUE THREAD

**Issue by sudoDev101** [intel-isl/Open3D#1830]
Hi all,

I am facing Cuda error while running ScalableFusionCuda.cpp

The error:
CUDA error at D:\Open3D\src\Cuda\Container\MemoryHeapCudaKernel.cuh:26 code=98(cudaErrorInvalidDeviceFunction) "cudaGetLastError()"

Environment

OS - Windows 10
Cuda Toolkit - 10.1
GPU - RTX 2060
Cuda Driver - 441.22
I could use some help on the issue and Thank you in advance for your help

**Comment by yxlao** [comment]
This is for the forked repo: https://github.com/theNded/Open3D. @theNded could potentially help with this.

**Comment by theNded** [comment]
Deprecated. Please check `example/python/reconstruction_system/tintegrate_rgbd.py` in the open3d's main repository.
