### ISSUE TITLE
k4a/k4a.h”: No such file or directory

### ISSUE THREAD

**Issue by WestbrookZero** [intel-isl/Open3D#1834]
My environment is  windows, vs2017, Open3D-0.8.0, When I check BUILD_AZURE_KINECT, cmake is right no error but  I have the following error in vs2017 : 
7>D:\InstallPath\Source\Open3D-0.8.0\src\Open3D\IO\Sensor\AzureKinect\K4aPlugin.cpp(27): fatal error C1083: 无法打开包括文件: “k4a/k4a.h”: No such file or directory
7>D:\InstallPath\Source\Open3D-0.8.0\src\Open3D\IO\Sensor\AzureKinect\AzureKinectSensor.cpp(29): fatal error C1083: 无法打开包括文件: “k4a/k4a.h”: No such file or directory
7>D:\InstallPath\Source\Open3D-0.8.0\src\Open3D\IO\Sensor\AzureKinect\AzureKinectSensorConfig.cpp(30): fatal error C1083: 无法打开包括文件: “k4a/k4a.h”: No such file or directory
7>D:\InstallPath\Source\Open3D-0.8.0\src\Open3D\IO\Sensor\AzureKinect\AzureKinectRecorder.cpp(39): fatal error C1083: 无法打开包括文件: “k4a/k4a.h”: No such file or directory
7>D:\InstallPath\Source\Open3D-0.8.0\src\Open3D\IO\Sensor\AzureKinect\MKVWriter.cpp(29): fatal error C1083: 无法打开包括文件: “k4a/k4a.h”: No such file or directory
7>D:\InstallPath\Source\Open3D-0.8.0\src\Open3D\IO\Sensor\AzureKinect\MKVReader.cpp(30): fatal error C1083: 无法打开包括文件: “k4a/k4a.h”: No such file or directory
7>已完成生成项目“IO.vcxproj”的操作 - 失败。
8>------ 已启动生成: 项目: Open3D, 配置: Debug x64 ------
8>LINK : fatal error LNK1181: 无法打开输入文件“D:\InstallPath\Source\Open3D-0.8.0\build\src\Open3D\IO\IO.dir\Debug\AzureKinectRecorder.obj”
8>已完成生成项目“Open3D.vcxproj”的操作 - 失败。
9>------ 已启动生成: 项目: open3d (Python\open3d), 配置: Debug x64 ------
10>------ 已启动生成: 项目: DepthCapture, 配置: Debug x64 ------
11>------ 已启动生成: 项目: IntegrateRGBD, 配置: Debug x64 ------
12>------ 已启动生成: 项目: Image, 配置: Debug x64 ------
13>------ 已启动生成: 项目: Flann, 配置: Debug x64 ------
14>------ 已启动生成: 项目: FileSystem, 配置: Debug x64 ------
15>------ 已启动生成: 项目: CameraPoseTrajectory, 配置: Debug x64 ------
16>------ 已启动生成: 项目: FileDialog, 配置: Debug x64 ------
15>LINK : fatal error LNK1104: 无法打开文件“..\..\lib\Debug\Open3D.lib”

**Comment by CUI-J** [comment]
I have the same problem, did you solved this problem?
