### ISSUE TITLE
Program crashes when using drawgeometries function

### ISSUE THREAD

**Issue by MoHamzawy** [intel-isl/Open3D#1837]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When I try to use the following:
o3d.draw_geometries([pcd])
the program crashes with an error : Process finished with exit code -1073741819 (0xC0000005)

![image](https://user-images.githubusercontent.com/64315042/82018950-96529500-9686-11ea-8de5-d1e8f7651dd3.png)

**Environment (please complete the following information):**
 - OS: [e.g. OSX Mojave, Ubuntu 16.04, Windows 10.0]
 - Python version:3.7.6
 - Open3D version:0.7.0
 - Is this remote workstation?: no
 - How did you install Open3D?: conda

**Additional context**

**Comment by yxlao** [comment]
What's your OS? Could you provide the complete code and data to reproduce this issue?

**Comment by MoHamzawy** [comment]
OS: Windows 10
code:

import open3d as o3d
pcd = o3d.read_point_cloud("pointcloud.pcd")
o3d.draw_geometries([pcd])


folders in conda site packages
[open3d.zip](https://github.com/intel-isl/Open3D/files/4632800/open3d.zip)

point cloud:

[pointcloud.zip](https://github.com/intel-isl/Open3D/files/4632819/pointcloud.zip)

**Comment by germanros1987** [comment]
This is solved using the newest rendering module in Open3D 0.11?
