### ISSUE TITLE
How can I check certain point, whether it is inside the point cloud or not?

### ISSUE THREAD

**Issue by ibrahimLearning** [intel-isl/Open3D#1840]
I want to check a certain point, 
whether it is inside of the point cloud or not?
Is there nay open3d function to do this?

**Comment by griegler** [comment]
What do you mean with _inside_ a point cloud? Could you give an example?

**Comment by ibrahimLearning** [comment]
> 
> 
> What do you mean with _inside_ a point cloud? Could you give an example?

Thank you very much for your comment. I have a point cloud data (xyz). 
Now I generated a point, say (5,4,-2). Is it possible to check the generated point? Is it within the point cloud or not?
Some people try to solve it by using Concave hull!

**Comment by griegler** [comment]
The problem is not well-defined for a point cloud. You could first mesh the point cloud, but you need to ensure a watertight mesh. In addition, Open3D lacks at the moment a 'point in mesh' test.

**Comment by liuxuzbg** [comment]
This tutorial may be helpful. http://www.open3d.org/docs/release/tutorial/geometry/distance_queries.html

> RaycastingScene directly provides functions to compute the unsigned and signed distance from a point to the mesh surface. It also provides a function to compute the occupancy at a query point.

> While the unsigned distance can always be computed, the signed distance and the occupancy are only valid if the mesh is watertight and the inside and outside are clearly defined. The signed distance is negative if the query point is inside the mesh. The occupancy is either 0 for points outside the mesh and 1 for points inside the mesh.
