### ISSUE TITLE
How can I save xyzrgb numpy array as a pointcloud (pcd) file?

### ISSUE THREAD

**Issue by ibrahimLearning** [intel-isl/Open3D#1841]
@benjaminum @yxlao 
from the documentation, I can save xyz points. but my array contains xyzrgb.
how can I save it from numpy array?

**Comment by yxlao** [comment]
you can save a point cloud to other formats like`.pts` or `ply`, or just save the numpy array

**Comment by ibrahimLearning** [comment]
@yxlao 
Thank you very much for your comment.
In my case,
pcd.points = open3d.utility.Vector3dVector(xyzrgb) is not working.
but
pcd.points=open3d.utility.Vector3dVector(xyzrgb) is OK.
Would you clarify this please?
