### ISSUE TITLE
How to compare the difference between two point cloud, voxels, octrees or meshes? 

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#1853]
Hello,

I think that to find the difference between two point clouds can be one of the important segmentation steps or applications, such as background subtraction.
 
I saw that it is possible to do the "add" operation with both pcd and voxel. But there is no "subtraction" operation. 

Can anyone show a hint how to do the subtraction ether in pcd or in voxel or in octrees?  Syncle mentioned about the voxelize and find the differences in voxel domain . But how?

I saw someone mentioned ways to detect the two point clouds difference: point-wise calculate the nearest neighbor point distance  in Matlab or compare the octrees difference in PCL.

What can be the solution in Open3D?

Thank you!

**Comment by griegler** [comment]
You could use [`compute_point_cloud_distance`](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.compute_point_cloud_distance) to get for each point from the source point cloud the nearest neighbor to the target point cloud. Then define a threshold to compute the difference.

**Comment by 1939938853** [comment]
Hi, 

It returns a DoubleVector. How can I make use of the DoubleVector to locate those points that are differ from each other? 

I saw that CloudCompare have some functions 
https://www.cloudcompare.org/doc/wiki/index.php?title=How_to_compare_two_3D_entities

**Comment by griegler** [comment]
I added a small tutorial in this PR: #1884

**Comment by 1939938853** [comment]
Thank you Gernot!

It's very helpful.

**Comment by Pdshende** [comment]
Hi,

To extract diffrence in point cloud insted of using nearest neighbour in Matlab is there any other approach we can follow because it is taking lot of time to me to extract different so if there is a efficient way to extract the different between two point clouds please let me know

**Comment by griegler** [comment]
@Pdshende can you open a new issue with more details on your problem and maybe describe why the solution proposed in this issue is not working.
