### ISSUE TITLE
Build for arm64/aarch64 - filament fails

### ISSUE THREAD

**Issue by fwarmuth** [intel-isl/Open3D#1859]
**Describe the bug**
Building for arm64 fails because filament download doesn't include lib/aarch64:
```
...
[ 16%] Linking CXX executable ../../bin/EncodeShader
[ 16%] Built target EncodeShader
Scanning dependencies of target filament_copy
cp: cannot stat 'lib/aarch64/*': No such file or directory
3rdparty/CMakeFiles/filament_copy.dir/build.make:57: recipe for target '3rdparty/CMakeFiles/filament_copy' failed
make[2]: *** [3rdparty/CMakeFiles/filament_copy] Error 1
CMakeFiles/Makefile2:345: recipe for target '3rdparty/CMakeFiles/filament_copy.dir/all' failed
make[1]: *** [3rdparty/CMakeFiles/filament_copy.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**To Reproduce**
Build form source using a arm64/aarch64 machine following the documentation step per step:
-> http://www.open3d.org/docs/release/compilation.html#ubuntu

**Expected behavior**
Successful build.

**Environment:**

- Operating system:
`Linux ai-xavier 4.9.140-tegra #1 SMP PREEMPT Tue Nov 5 13:37:19 PST 2019 aarch64 aarch64 aarch64 GNU/Linux`
- Python version: (e.g. Python 3.6)
`Python 3.6.9`
- Open3D version:
- Is this remote workstation?: `yes`
- How did you install Open3D?:  `build from source`
- Compiler version (if built from source): 
`gcc 7.5`
```clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Additional context**
It seems that the filament download does not include the aarch64 libs... therefore the build fails.
I did build this successfully months ago, so it seems that the download scripts misses something?

any hints would be great!

**Update**
`git checkout HEAD~15`
builds with ease, i got no time to narrow it down.

**Comment by parang17** [comment]
I have exactly the same issue. Here is mine. Please share if you have anything can solve this issue. I will share too! 

nvidia@nvidia-desktop:~/git/Open3D/build$ sudo make
[  1%] Built target tinyobjloader
[  3%] Built target ext_turbojpeg
[  9%] Built target qhullcpp
[ 13%] Built target qhullstatic_r
[ 14%] Built target jsoncpp
[ 15%] Built target tinyfiledialogs
[ 16%] Built target EncodeShader
cp: cannot stat 'lib/aarch64/*': No such file or directory
3rdparty/CMakeFiles/filament_copy.dir/build.make:57: recipe for target '3rdparty/CMakeFiles/filament_copy' failed
make[2]: *** [3rdparty/CMakeFiles/filament_copy] Error 1
CMakeFiles/Makefile2:345: recipe for target '3rdparty/CMakeFiles/filament_copy.dir/all' failed
make[1]: *** [3rdparty/CMakeFiles/filament_copy.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fwarmuth** [comment]
@parang17 1st - why do you do `sudo make`?? 
@parang17 2nd - read the update within the main issue.
@parang17 3rd - by now i must checkout `5a33facba26f1a7fa77301ad11cced98d3e5c9f5` for a successful build

**Workaround - warped up**:
```
# clone repo
git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D
# install dependencies
util/scripts/install-deps-ubuntu.sh assume-yes
# checkout state where filament has aarch libs
git checkout 5a33facba26f1a7fa77301ad11cced98d3e5c9f5
# normal build process
mkdir build
cd build
cmake ..
make -j$(nproc --all)
```
and then install as you like
```
make install-pip-package
```

**Comment by germanros1987** [comment]
@yxlao this is solved now, I think... right?

**Comment by yxlao** [comment]
Yes, it has been resolved. Now, filament will be built from source. See http://www.open3d.org/docs/release/arm.html.
