### ISSUE TITLE
AttributeError: 'open3d.open3d.geometry.PointCloud' object has no attribute 'select_by_index'

### ISSUE THREAD

**Issue by chowkamlee81** [intel-isl/Open3D#1860]
iam getting error below:

AttributeError: 'open3d.open3d.geometry.PointCloud' object has no attribute 'select_by_index'

Kindly help

eps = 0.45
point_cloud = np.fromfile('00020.bin',dtype=np.float32).reshape((-1,4))
pcd_data = open3d.geometry.PointCloud()
pcd_data.points = open3d.utility.Vector3dVector(point_cloud[:, :3])
plane_model, inliers = pcd_data.segment_plane(distance_threshold=0.01,ransac_n=3,num_iterations=1000)
[a, b, c, d] = plane_model
print(f"Plane equation: {a:.2f}x + {b:.2f}y + {c:.2f}z + {d:.2f} = 0")

inlier_cloud = pcd_data.select_by_index(inliers)

**Comment by griegler** [comment]
How did you install Open3D? If you installed it via pip/conda, then the method might be named `select_down_sample` (http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.select_down_sample).

**Comment by liuchangji** [comment]
i think your version is too old

**Comment by chandravaran** [comment]
This worked for me when I was using ros melodic and open3d!

> How did you install Open3D? If you installed it via pip/conda, then the method might be named `select_down_sample` (http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.select_down_sample).

**Comment by ssheorey** [comment]
Closing based on @chandravaran 's comment. Please let us know if this is still a problem.
