### ISSUE TITLE
Build Open3D falied----filament

### ISSUE THREAD

**Issue by CarlLyt** [intel-isl/Open3D#1861]
hi
i meet a make error like(ubuntu 16)
```
Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:811:26: error: specialization of ‘template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
 template<> struct utils::EnableBitMaskOperators<filament::backend::TargetBufferFlags>

Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘template<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };

/Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘template<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };

Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:811:26: error: specialization of ‘template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
 template<> struct utils::EnableBitMaskOperators<filament::backend::TargetBufferFlags>

Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘template<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };

Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:813:26: error: specialization of ‘template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
 template<> struct utils::EnableBitMaskOperators<filament::backend::TextureUsage>

Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘template<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };


Open3D/GUI/Application.cpp: In member function ‘open3d::gui::Application::RunStatus open3d::gui::Application::ProcessQueuedEvents()’:
Open3D/src/Open3D/GUI/Application.cpp:333:44: error: ‘glfwWaitEventsTimeout’ was not declared in this scope
     glfwWaitEventsTimeout(RUNLOOP_DELAY_SEC);
```

it seem the filament of the problem,but i use 
```
- git submodule update --init --recursive
```
command to download the 3rdparty
can someone help me?

**Comment by jiapei100** [comment]
Same here... I gave up building **filament** ... 
Can you build without **filament** ???

**Comment by yxlao** [comment]
@CarlLyt I think one potential problem is with Ubuntu 16. By default, [Open3D system requirement](http://www.open3d.org/docs/release/compilation.html#system-requirements) requires Ubuntu 18.04+. Ubuntu 16 is not supported officially.

If you have to use Ubuntu 16.04, here're the things you can try:

1. Disable the GUI app completely.
    ```bash
    -DENABLE_GUI=OFF
    ```
2. If you have to use the GUI app, try
    ```bash
    -DENABLE_GUI=ON -DBUILD_FILAMENT=ON
    ```
    This will try to build Filament from source instead of relying on pre-compiled Filament for 18.04.
3. Additionally, you shall also check out https://github.com/intel-isl/Open3D/blob/master/util/scripts/install-deps-ubuntu.sh and install `libc++-7-dev` and `libc++abi-7-dev`. The `install-deps-ubuntu.sh` is meant for Ubuntu 18.04, so you can try to install the packages manually instead of running the whole script on Ubuntu 16.

 
@jiapei100 yes, you can build without filament. Add the following flag:
```bash
-DENABLE_GUI=OFF
```
This will turn off the new standalone visualizer app but the rest of Open3D is not affected.

**Comment by adizhol** [comment]
@yxlao I'm facing the same problem and -DENABLE_GUI=OFF or -DENABLE_GUI=OFF doesn't help.
Cmake actually warns it's not using these variables.
```
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_FILAMENT
    ENABLE_GUI

```

**Comment by HananiJia** [comment]
> @yxlao我遇到了相同的问题，并且-DENABLE_GUI = OFF或-DENABLE_GUI = OFF无效。
> Cmake实际上警告它没有使用这些变量。
> 
> ```
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     BUILD_FILAMENT
>     ENABLE_GUI
> ```

Have you installed the corresponding version sudo apt-get install libc++-7-dev libc++abi-7-dev ?
I can't find the corresponding version
so i used apt-get instll libc++-8-dev libc++abi-8-dev
Is it because of this problem?

**Comment by HananiJia** [comment]
> @CarlLyt I think one potential problem is with Ubuntu 16. By default, [Open3D system requirement](http://www.open3d.org/docs/release/compilation.html#system-requirements) requires Ubuntu 18.04+. Ubuntu 16 is not supported officially.
> 
> If you have to use Ubuntu 16.04, here're the things you can try:
> 
> 1. Disable the GUI app completely.
>    ```shell
>    -DENABLE_GUI=OFF
>    ```
> 2. If you have to use the GUI app, try
>    ```shell
>    -DENABLE_GUI=ON -DBUILD_FILAMENT=ON
>    ```
>    
>    
>    This will try to build Filament from source instead of relying on pre-compiled Filament for 18.04.
> 3. Additionally, you shall also check out https://github.com/intel-isl/Open3D/blob/master/util/scripts/install-deps-ubuntu.sh and install `libc++-7-dev` and `libc++abi-7-dev`. The `install-deps-ubuntu.sh` is meant for Ubuntu 18.04, so you can try to install the packages manually instead of running the whole script on Ubuntu 16.
> 
> @jiapei100 yes, you can build without filament. Add the following flag:
> 
> ```shell
> -DENABLE_GUI=OFF
> ```
> 
> This will turn off the new standalone visualizer app but the rest of Open3D is not affected.
> 
> Feel free to comment if it doesn't solve the problem.


Are these two?
option(BUILD_GUI                  "Builds new GUI"                           ON )
option(BUILD_FILAMENT_FROM_SOURCE "Build filament from source"               ON)

**Comment by yxlao** [comment]
@HananiJia you're right. My previous answer was referring to the old master branch back on May 2020. Since then they have been renamed. 

@adizhol , please use the name:
```
option(BUILD_GUI "Builds new GUI" ON )
option(BUILD_FILAMENT_FROM_SOURCE "Build filament from source" ON)
```

**Comment by zjuwyz** [comment]
> hi
> i meet a make error like(ubuntu 16)
> 
> ```
> Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:811:26: error: specialization of ‘template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
>  template<> struct utils::EnableBitMaskOperators<filament::backend::TargetBufferFlags>
> 
> Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘template<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
>  struct EnableBitMaskOperators : public std::false_type { };
> 
> /Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘template<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
>  struct EnableBitMaskOperators : public std::false_type { };
> 
> Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:811:26: error: specialization of ‘template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
>  template<> struct utils::EnableBitMaskOperators<filament::backend::TargetBufferFlags>
> 
> Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘template<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
>  struct EnableBitMaskOperators : public std::false_type { };
> 
> Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:813:26: error: specialization of ‘template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
>  template<> struct utils::EnableBitMaskOperators<filament::backend::TextureUsage>
> 
> Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘template<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
>  struct EnableBitMaskOperators : public std::false_type { };
> 
> 
> Open3D/GUI/Application.cpp: In member function ‘open3d::gui::Application::RunStatus open3d::gui::Application::ProcessQueuedEvents()’:
> Open3D/src/Open3D/GUI/Application.cpp:333:44: error: ‘glfwWaitEventsTimeout’ was not declared in this scope
>      glfwWaitEventsTimeout(RUNLOOP_DELAY_SEC);
> ```
> 
> it seem the filament of the problem,but i use
> 
> ```
> - git submodule update --init --recursive
> ```
> 
> command to download the 3rdparty
> can someone help me?

FYI: I solved this problem by updating gcc from gcc5 to gcc7 on ubuntu16. There's no need to change options.
