### ISSUE TITLE
How to you access mesh.triangle_material_ids_ from python?

### ISSUE THREAD

**Issue by nickponline** [intel-isl/Open3D#1863]
I'm looking to remove vertices from a textured mesh with multiple texture. 

Using `remove_vertices_by_index` doesn't seem to work so I'm removing the `vertices`, `triangles`, `texture_uvs` and `triangle_materials` manually like this: 

```
    mesh.vertices = o3d.utility.Vector3dVector( cropped_vertices)
    mesh.triangles = o3d.utility.Vector3iVector( cropped_triangles)
    mesh.triangle_uvs = o3d.utility.Vector2dVector( cropped_triangle_uvs )
```

But I can't seem to access the `triangle_materials` from Python, so it jumbles the textures in the resulting mesh.

**Comment by XiangZhangPKU** [comment]
I met the same problem. One can read/visualize/write mesh with multiple textures, but there is no way to change/construct triangle_material_ids_ from Python. triangle_material_ids_ is not exposed to python interface.

**Comment by germanros1987** [comment]
@errissa does this work in the new rendering API?

**Comment by errissa** [comment]
Yes. This works in the new rendering API. There is still no way to access `triangle_material_ids_` from Python so this still doesn't work for old visualizer.

**Comment by errissa** [comment]
Please try master. `triangle_material_ids` is now exposed to python.
