### ISSUE TITLE
Is the first-person navigation recordable or exportable

### ISSUE THREAD

**Issue by amiltonwong** [intel-isl/Open3D#1865]
Hi, all,

The new 0.10 version features look quite amazing. Is the first-person navigation recordable or exportable to a file?

THX!

**Comment by germanros1987** [comment]
Hi,

Sorry for the delay. 

This is not possible out of the box at the moment, you could easily modify Open3D/Visualization/Visualizer/GuiVisualizer.cpp to add this feature.
