### ISSUE TITLE
Process finished with exit code -1073741515

### ISSUE THREAD

**Issue by bearinsuke** [intel-isl/Open3D#1871]
**Describe the bug**
I am building an octree with 10000 points, but the code crushed when converting octree from the point cloud. 

**To Reproduce**

import open3d as o3d
import numpy as np

pcd = o3d.io.read_triangle_mesh("xxx.ply")
pcd.compute_vertex_normals()
aaa = pcd.sample_points_poisson_disk(10000)
points = np.asarray(aaa.points)

octree = o3d.geometry.Octree()
octree.convert_from_point_cloud(aaa)
o3d.visualization.draw_geometries([octree])

pass

**Expected behavior**
a visualization of octree

**Environment (please complete the following information):**

- Operating system:  Windows 10 64-bit
- Python version: Python 3.7
- Open3D version: 0.10
- Is this remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): pycharm latest version

**Comment by CorneliusHsiao** [comment]
I have the same issue but I am converting to voxel grid and then octree successfully as discussed in #1359 . Hope this can get solved soon.
