### ISSUE TITLE
Getting DLL load failed Errors when trying to run

### ISSUE THREAD

**Issue by Styxny** [intel-isl/Open3D#1872]
**Describe the bug**
I have installed the package in venv using pycharm. Just trying to get a simple example to run, code is below, and _myfile_ is replaced with path to a .ply file.

import numpy as np
import open3d as o3d

def main():
    cloud = o3d.read_point_cloud("_myfile_" )
    o3d.draw_geometries([cloud])

if __name__ == "__main__":
    main()

but get these errors 

File "\_\_init\_\_.py", line 47, in <module>
    from open3d.open3d_pybind import camera
ImportError: DLL load failed while importing open3d_pybind: The specified module could not be found.

**Expected behavior**
Expected the code to run and display the pointcloud, but I am getting DLL error

**Environment (please complete the following information):**
Pycharm community most up-to-date version

- Operating system:  Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: 0.10.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by yxlao** [comment]
Please update with `pip install -U open3d` and get the `0.10.0.1` version and see if it works. 

In the updated `0.10.0.1` release, Open3D links the latest [visual c++ runtime](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) statically. So it should work out-of-the-box.

If `0.10.0.1` still doesn't work, let us know.

**Comment by Styxny** [comment]
That worked, thanks!

**Comment by Me817** [comment]
Hi, 
today I installed open3d on Windows 10 via pip and used python 3.7.4. I already updated open3d by the comment you mentioned above, so I already have open3d 0.10.0.1. But I still get the following error:
```

Traceback (most recent call last):
  File "C:/Users/PC/PycharmProjects/bachelorthesis_lindanis/interactive_visualization.py", line 9, in <module>
    import open3d as o3d
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\open3d\__init__.py", line 47, in <module>
    from open3d.open3d_pybind import camera
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```
Does anyone have an idea how to solve this?
Thank you in advance.

**Comment by ketai-dhr** [comment]
![165ec0d03b17f217542771c8ae2c9a78cd1cafd31bc1b0fad4e5c23e4225ecf7QzpcVXNlcnNcMTA1NzhcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDU4Mzg3MDA4OF92MlxJbWFnZUZpbGVzXDE2NTgxMTI3NDU3MDhfNDAwMjgwRTAtQkI2QS00ZGIyLUE3RjItQURBQTkwOTA0MTRCLnBuZw==](https://user-images.githubusercontent.com/60175845/179438673-c30b94db-9084-46ac-92ab-be1b9d6c7336.png)

hi , i update and it's not work still

**Comment by BastianGit** [comment]
Hi,

I had a similar issue during import of open3d version 0.16 and 0.15.1 with windows 11 and python 9.13. I managed to solve the problem by installing CUDA version 11.5 and setting the paths correctly in the system environment variables (cuda installation should be similar to: c>program files> nvidia gpu computing... > cuda > v11.5). Uninstall open3d and re-install.

I hope this helps!
Regards.
