### ISSUE TITLE
Compile error on MacOS Xcode 'CVMetalTextureCacheRef'

### ISSUE THREAD

**Issue by lineker10** [intel-isl/Open3D#1875]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Compile error on MacOS XCODE -> 
Unknown type name 'CVMetalTextureCacheRef'; did you mean 'CVOpenGLTextureCacheRef'?

**To Reproduce**

1. cmake
2. compile on Xcode
3. error occurred 
Unknown type name 'CVMetalTextureCacheRef'; did you mean 'CVOpenGLTextureCacheRef'?
**Expected behavior**
Please, solve the compile error.

**Screenshots**

metal context.h
85  // External textures.
86    CVMetalTextureCacheRef textureCache = nullptr;
       =>Unknown type name 'CVMetalTextureCacheRef'; did you mean   'CVOpenGLTextureCacheRef'?

**Environment (please complete the following information):**

- Operating system: OSX 10.15.4
- Python version:  Python 3.7.7
- Open3D version:
- Is this remote workstation?: no
- How did you install Open3D?:  build from source
- Compiler version (if built from source): clang 11.03 Xcode 11.5

**Additional context**
How to use openmp on MacOS Xcode?

**Comment by hxd0571** [comment]
Hi, lineker. How do you solve the problem?  How to set Xcode?
