### ISSUE TITLE
TriangleMesh.select_down_sample removing more points than indicated.

### ISSUE THREAD

**Issue by martinakos** [intel-isl/Open3D#1878]
Run this code with the attached pickle file:
[select_down_sample_test.zip](https://github.com/intel-isl/Open3D/files/4663293/select_down_sample_test.zip)

```
import pickle
import numpy as np
import open3d as o3d

vertices, triangles, indices  = pickle.load(open("select_down_sample_test.p", 'rb'))   

mesh = o3d.geometry.TriangleMesh()
mesh.triangles = o3d.utility.Vector3iVector(triangles)   
mesh.vertices = o3d.utility.Vector3dVector(vertices)      
new_mesh = mesh.select_down_sample(indices)    

print(mesh)
print(indices.shape)
print(new_mesh)
```

I get this output:

```
geometry::TriangleMesh with 107527 points and 212220 triangles.
(70956,)
geometry::TriangleMesh with 70947 points and 140702 triangles.
```
So **new_mesh** has less points than **indices**. This doesn't happen most of the time, but when it happens it messes up my algorithm as I don't know what indices are missing in the new_mesh.

It happens both in version 0.8.0.0 and 0.9.0.0.

**Comment by griegler** [comment]
What could happen is that after `select_down_sample` (now called `select_by_index`) also removes vertices that are no longer referenced by any valid triangle (it is calling `RemoveUnreferencedVertices`). Hence, the resulting mesh can have less vertices than `indices`. 

Maybe we should give more control, if those clean-up methods are called automatically. @yxlao what is your opinion.
