### ISSUE TITLE
Is it possible to have visualizer with editing and key callbacks?

### ISSUE THREAD

**Issue by stsdc** [intel-isl/Open3D#1885]
I'm using o3d 0.10.0 and I'm trying to select points and on `key_press` event send theme somewhere. Maybe there is possibility to create even some gui? Just need some sort of trigger.

**Comment by Me817** [comment]
Hello, have you solved this problem? I also encountered this problem. I am also trying to select points in a point cloud, save these points in a list and update the visualizer on key_press event with a new point cloud.

**Comment by stsdc** [comment]
@Me817 I'm using vispy now.

**Comment by Zumbalamambo** [comment]
@Me817 

This works for me,
```


from functools import partial

import open3d as o3d
import numpy as np

path = "file_name.png"


def save_image(vis):
    vis.capture_screen_image(path)
    print("Saved")
    return False


pcd = o3d.io.read_point_cloud("assets/pointcloud.pcd")
vis = o3d.visualization.VisualizerWithKeyCallback()
vis.create_window()
vis.get_render_option().background_color = np.asarray([0, 0, 0])

view_ctl = vis.get_view_control()
vis.add_geometry(pcd)
vis.register_key_callback(ord("S"), partial(save_image))
vis.run()
vis.destroy_window()
```

**Comment by tpwrules** [comment]
I'm having this probelm too. @Zumbalamambo that does not support editing so it does not help me.

**Comment by prewettg** [comment]
This is not possible from Python at the moment. We are currently redesigning how the visualizers and draw_geometries work so that they can use the new GUI and rendering frameworks, planned for 0.12.0.

**Comment by prewettg** [comment]
We have consolidated the functionalities of the visualizers and updated to use the new GUI module. You can use it as a replacement for draw_geometries and also add actions at the same time:
`open3d.visualization.draw([obj1, obj2, ...], actions=[("Trigger 1", callback1), ("Trigger 2", callback2), ...])`
and pass any Python function. You can see examples at [examples/python/gui/draw.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py). You can also use the visualizer directly, see the [draw() function itself](https://github.com/intel-isl/Open3D/blob/master/python/open3d/visualization/draw.py) for usage. This feature is in the `master` branch, and will be in the 0.12 release.

**Comment by Zumbalamambo** [comment]
@prewettg does open3d supports arbitrary camera matrices?

**Comment by prewettg** [comment]
@Zumbalamambo yes, 0.12 supports arbitrary camera matrices, but you need to use the new renderer. And it didn't make it into the new draw function as an argument, but you can set a callback to on_init, get the camera, and set it there.
