### ISSUE TITLE
Python crashes when displaying a textured mesh imported from OBJ file

### ISSUE THREAD

**Issue by chuong** [intel-isl/Open3D#1889]
**Describe the bug**
Python crashed without any error message when displaying a texture mesh. 

**To Reproduce**
This is the short script to reproduce the issue:

```
import open3d as o3d
mesh = o3d.io.read_triangle_mesh("Chorthippus_neu.obj")
o3d.visualization.draw_geometries([mesh])
```
Python crashed and exited after the 3rd line of code. The OBJ file is available in a zip file at https://drive.google.com/open?id=1X4tCISTG19ngW_9KbMU_m1IKCgv7j918

**Expected behavior**
Should display a textured mesh without issue. Or at least display an error message.

**Environment (please complete the following information):**
- Operating system: Windows 10 64-bit
- Python version: Python 3.7.3
- Open3D version: 0.10.0.1
- Is this remote workstation?: no
- How did you install Open3D?: pip in conda command window

**Additional context**
Meshlab opened and displayed the textured mesh without problem.

**Comment by germanros1987** [comment]
@errissa following up on this.

**Comment by errissa** [comment]
This is now fixed.
