### ISSUE TITLE
How to create a point cloud by x,y,z?

### ISSUE THREAD

**Issue by JimXu1989** [intel-isl/Open3D#1900]
**Is your feature request related to a problem? Please describe.**
I want to know whether there is a function can make a point cloud from x,y,z directly?

Thanks a lot!

**Comment by GnnrMrkr** [comment]
You mean like this?

```
p1 = [1, 2, 3]
p2 = [4, 5, 6]
xyz = np.vstack([p1, p2])
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyz)
```
p1 would be your first point with x = 1, y = 2, z = 3.
p2 would be your second point with x = 4, y = 5, z = 6.

Here are a few more methods: 
[NumPy Tutorial](http://www.open3d.org/docs/release/tutorial/Basic/working_with_numpy.html)

**Comment by JimXu1989** [comment]
> You mean like this?
> 
> ```
> p1 = [1, 2, 3]
> p2 = [4, 5, 6]
> xyz = np.vstack([p1, p2])
> pcd = o3d.geometry.PointCloud()
> pcd.points = o3d.utility.Vector3dVector(xyz)
> ```
> 
> p1 would be your first point with x = 1, y = 2, z = 3.
> p2 would be your second point with x = 4, y = 5, z = 6.
> 
> Here are a few more methods:
> [NumPy Tutorial](http://www.open3d.org/docs/release/tutorial/Basic/working_with_numpy.html)

Yes! Thanks a lot!!
