### ISSUE TITLE
FGR results does not look right

### ISSUE THREAD

**Issue by RiteshMahajan** [intel-isl/Open3D#1902]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I tried to register RGB-d images for TUM data set "rgbd_dataset_freiburg3_teddy". The results are not convincing. I am using the c++ version of open3d.

**To Reproduce**
1. read rgb-d images.
2. create point cloud.
3. down sample.
4. estimate normals , using  open3d::geometry::KDTreeSearchParamHybrid(0.1,                                                                 30))
5. compute FPFH using registration::ComputeFPFHFeature(*source_origin_pcd_regster,
                            open3d::geometry::KDTreeSearchParamHybrid(0.25, 100));
6. call FastGlobalRegistration with point clouds and FPFH features. using non cuda FGR

**Expected behavior**
The registration results for data sets with 100+ images does not look good.

**Screenshots**
1. for 50 images:
![teddy50](https://user-images.githubusercontent.com/14038237/82992863-6065c700-a01d-11ea-9a59-8c2d1eb06e34.png)
2. for 300 images:
![teddy300](https://user-images.githubusercontent.com/14038237/82992880-665ba800-a01d-11ea-99e6-0482ffc0a159.png)

**Environment (please complete the following information):**

- Operating system: ( Windows 10 64-bit)
- Open3D version: cuda version
- Is this remote workstation?: no
- How did you install Open3D?: (build from source using cmake)
- Compiler version (if built from source): (visual studio 2019)

**Additional context**

**Comment by theNded** [comment]
Please use `make_fragment` in the reconstruction pipeline to do this. RGB-D based visual odometry with pose graph makes more sence in this use case. If you somehow have to use point-cloud representation, use ICP-odometry instead of FGR. FGR is for rough global registration and is not a good candidate for this task.
