### ISSUE TITLE
How to access each cluster after clustering by pcl.cluster_dbscan?

### ISSUE THREAD

**Issue by JimXu1989** [intel-isl/Open3D#1910]
**Is your feature request related to a problem? Please describe.**
Hi, I want to access every cluster after the clustering functino, Ex. pcl.cluster_dbscan, the cluters is painted by different color in the demo code, I want to access the clusters and choose some cluster by some features for example Number of points, how could I make it?

Thanks a lot!!

**Describe the solution you'd like**
I want to have some function to access and choose the clusters.

**Comment by JimXu1989** [comment]
I solved this matter

**Comment by JoaoAVDuarte** [comment]
How did you solve it?
