### ISSUE TITLE
C++ Open3D CMAKE Error

### ISSUE THREAD

**Issue by YangJae96** [intel-isl/Open3D#1918]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I am having a error build C++ interface Open3D.
There seems to be no  "png.h" in the src directory. 
![image](https://user-images.githubusercontent.com/57695621/83515925-18f5a400-a511-11ea-85a9-0a90b05718c7.png)

**To Reproduce**
Steps to reproduce the behavior:  I tried to build from source C++ open3D. 
I got some errors when I typed in the command
"sudo make -j8"
I think it is getting error because there is no header file png.h inside the Open3D/src/Open3D/IO/FileFormat/ directory.. 

![image](https://user-images.githubusercontent.com/57695621/83515925-18f5a400-a511-11ea-85a9-0a90b05718c7.png)

**Expected behavior**

I expected a full 100% CMAKE Build.

**Screenshots**

![image](https://user-images.githubusercontent.com/57695621/83515925-18f5a400-a511-11ea-85a9-0a90b05718c7.png)

![image](https://user-images.githubusercontent.com/57695621/83516275-bbae2280-a511-11ea-8502-519654633373.png)

No png.h header file 
![image](https://user-images.githubusercontent.com/57695621/83516164-928d9200-a511-11ea-93bc-db739145e9df.png)

**Environment (please complete the following information):**

- Operating system: Ubuntu-16.04
- Python version: Python 3.6.10
- Open3D version: C++ Interface (Maybe the newest?)
- Is this remote workstation?: yes
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 5.5.0

**Additional context**
I think there is a error because there is no headfile png.h inside the directory. 
All the other Build targets have headfile next to the cpp file. 
But IO/FileFormate does not.
Is this the problem??

**Comment by femust** [comment]
@YangJae96  png_image is a type?

**Comment by yxlao** [comment]
Is it related to submodules? Try running `git submodule update --init --recursive`, or start from scratch with `git clone --recursive`.

If it is not a submodule problem, please share the full CMake config script.

**Comment by drmateo** [comment]
I was experimenting the same problem. In my case, I found that cmake was take libpng from the system during built, an straitforward solution was to setup BUILD_PNG=ON thus cmake is forced to take 3rdparity libpng.
