### ISSUE TITLE
Cannot disable read_point_cloud console output

### ISSUE THREAD

**Issue by Milogav** [intel-isl/Open3D#1921]
**Describe the bug**
Hi. I am using read_point_cloud to read some ply files and I am not able to supress console output.
I have tried to set the verbosity level to Error in order to supress the output but it keeps printing:

Format = auto
Extension = ply

**To Reproduce**

```
import open3d

v_level = open3d.utility.VerbosityLevel.Error
open3d.utility.set_verbosity_level(v_level)

ply_file = ...
pcd = open3d.io.read_point_cloud(ply_file)
```

**Expected behavior**
The ply files are read silently, with no console output

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: 0.10.0.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by griegler** [comment]
It seems that `utility::ConsoleProgressUpdater` prints in the constructor, see for example [here](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/IO/ClassIO/PointCloudIO.cpp#L124). Interestingly, the progress updater is not used in `TriangleMeshIO.cpp`.

@pvarvak You are currently working on IO and progress reporting? Could you have a look on a fix for this.

**Comment by dhirajsuvarna** [comment]
Request you to fix this as it is clutering the console output.

**Comment by dhirajsuvarna** [comment]
I am using the package from pip, the latest one.
It still has the problem.

**Comment by griegler** [comment]
It has been fixed in master, but this is not yet in pip/conda.

**Comment by HenryZh47** [comment]
Just a quick follow-up would it be on pip/conda anytime soon? Thanks

**Comment by aniqueakhtar** [comment]
It would be extremely helpful if you can give us a few lines of code that we can call to disable console output for this function?
Thank you

**Comment by agomezlyte** [comment]
It would be nice to know in which commits this was implemented

**Comment by griegler** [comment]
It seems to be here: https://github.com/intel-isl/Open3D/commit/0dc69423222c1786cad4015e25807e461e9e6ca7
