### ISSUE TITLE
Rotation of primitive shapes.

### ISSUE THREAD

**Issue by femust** [intel-isl/Open3D#1922]
Hey,

**Is your feature request related to a problem? Please describe.**
I propose to add to primitive shapes the rotation, so I could for example have a rotated coordinate axis.

**Describe the solution you'd like**
Something like this, though not sure whether for consistency reasons the rotation should be Matrix3D (since this is the case for PointCloud rotations)
```
std::shared_ptr<open3d::geometry::TriangleMesh> some_name(
    double size /* = 1.0*/,
    const Eigen::Vector3d &origin /* = Eigen::Vector3d(0.0, 0.0, 0.0)*/,
    const Eigen::Matrix4d &R) {
  if (size <= 0) {
    open3d::utility::LogError("[CreateCoordinateFrame] size <= 0");
  }
  auto mesh_frame = open3d::geometry::TriangleMesh::CreateSphere(0.06 * size);
  mesh_frame->ComputeVertexNormals();
  mesh_frame->PaintUniformColor(Eigen::Vector3d(0.5, 0.5, 0.5));

  std::shared_ptr<open3d::geometry::TriangleMesh> mesh_arrow;
  Eigen::Matrix4d transformation;

  mesh_arrow = open3d::geometry::TriangleMesh::CreateArrow(
      0.035 * size, 0.06 * size, 0.8 * size, 0.2 * size);
  mesh_arrow->ComputeVertexNormals();
  mesh_arrow->PaintUniformColor(Eigen::Vector3d(1.0, 0.0, 0.0));
  transformation << 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1;
  transformation = R * transformation;
  mesh_arrow->Transform(transformation);
  *mesh_frame += *mesh_arrow;

  mesh_arrow = open3d::geometry::TriangleMesh::CreateArrow(
      0.035 * size, 0.06 * size, 0.8 * size, 0.2 * size);
  mesh_arrow->ComputeVertexNormals();
  mesh_arrow->PaintUniformColor(Eigen::Vector3d(0.0, 1.0, 0.0));
  transformation << 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1;
  transformation = R * transformation;
  mesh_arrow->Transform(transformation);
  *mesh_frame += *mesh_arrow;

  mesh_arrow = open3d::geometry::TriangleMesh::CreateArrow(
      0.035 * size, 0.06 * size, 0.8 * size, 0.2 * size);
  mesh_arrow->ComputeVertexNormals();
  mesh_arrow->PaintUniformColor(Eigen::Vector3d(0.0, 0.0, 1.0));
  transformation << 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1;
  transformation = R * transformation;
  mesh_arrow->Transform(transformation);
  *mesh_frame += *mesh_arrow;

  mesh_frame->Translate(-origin, true);

  return mesh_frame;
}
```
**Describe alternatives you've considered**
Actually, maybe there is a trick on how to do it, but I couldn't figure out based on documentation.

**Additional context**
![image](https://user-images.githubusercontent.com/26916586/83639720-63c3fa00-a5ab-11ea-8005-45846cb83120.png)

**Comment by griegler** [comment]
Are you using the C++ or Python API? And are you using the latest code from `master`? Since `0.10` you can specify the rotation center for `rotate`. Hence, you could achieve what you wish via `mesh.rotate(R, center=[0,0,0])` in Python, or `mesh->Rotate(R, Eigen::Vector3d(0,0,0));` in C++.

**Comment by femust** [comment]
@griegler I'm using c++ api 0.10 , and you are right i can do this, i haven't noticed that actually.

Though for me more intuitive was to look for this, as a parameter for the function :)
