### ISSUE TITLE
Not very good result of Fast Global Registration

### ISSUE THREAD

**Issue by lyldev** [intel-isl/Open3D#1928]
**Describe the bug**
For convenience, I used the FastGlobalRegistrtion implementation in the Open3D library and used the sample code from this page:
http://www.open3d.org/docs/release/tutorial/Advanced/global_registration.html#id2

As I know, there is only a voxel_size para in Open3D's implemention. When I tune voxel_size , I can only get some not very good results.(as showed Screenshots below)

**To Reproduce**

1. copy code:
```
import open3d as o3d
import numpy as np
import copy
import time
from multiprocessing import Process

def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target_temp])


def preprocess_point_cloud(pcd, voxel_size):
    print(":: Downsample with a voxel size %.3f." % voxel_size)
   
    pcd_down = pcd.voxel_down_sample(voxel_size)
    print("--before down sample: ", pcd)
    print("--after down sample: ", pcd_down)

    # """
    # 调用 estimate_normals 估计法向量
    radius_normal = voxel_size * 2
    print(":: Estimate normal with search radius %.3f." % radius_normal)
    pcd_down.estimate_normals(
        o3d.geometry.KDTreeSearchParamHybrid(radius=radius_normal, max_nn=30))
    # """
    radius_feature = voxel_size * 5
    print(":: Compute FPFH feature with search radius %.3f." % radius_feature)
    pcd_fpfh = o3d.registration.compute_fpfh_feature(
        pcd_down,
        o3d.geometry.KDTreeSearchParamHybrid(radius=radius_feature, max_nn=100))
    return pcd_down, pcd_fpfh


def prepare_dataset(source_path, target_path, voxel_size):
    print(":: Load two point clouds and disturb initial pose.")
    source = o3d.io.read_point_cloud(source_path)
    # source = o3d.io.read_point_cloud(
            # "D:/WorkSpace/data/rgbd/ICL-NUIM dataset/living_room_traj0_frei_png/plynoise/0-noise0.0025bdlen.ply")
    target = o3d.io.read_point_cloud(target_path)
    # target = o3d.io.read_point_cloud(
            # "D:/WorkSpace/data/rgbd/ICL-NUIM dataset/living_room_traj0_frei_png/plynoise/20-noise0.0025bdlen.ply")
    print(source)
    print(target)
    trans_init = np.asarray([[0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 0.0],
                             [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0]])
    source.transform(trans_init)
    # draw_registration_result(source, target, np.identity(4))

    source_down, source_fpfh = preprocess_point_cloud(source, voxel_size)
    target_down, target_fpfh = preprocess_point_cloud(target, voxel_size)
    print(source_down)
    print(target_down)
    return source, target, source_down, target_down, source_fpfh, target_fpfh


def execute_fast_global_registration(source_down, target_down, source_fpfh,
                                     target_fpfh, voxel_size):
    # distance_threshold = voxel_size * 0.5
    distance_threshold = voxel_size * 0.5
    print(":: Apply fast global registration with distance threshold %.3f" \
            % distance_threshold)
    result = o3d.registration.registration_fast_based_on_feature_matching(
        source_down, target_down, source_fpfh, target_fpfh,
        o3d.registration.FastGlobalRegistrationOption(
            maximum_correspondence_distance=distance_threshold))
    return result

def run(label, source_path, target_path, voxel_size):

    source, target, source_down, target_down, source_fpfh, target_fpfh = \
            prepare_dataset(source_path, target_path, voxel_size)
    
    print(label, "--finish prepare dataset.")

    start = time.time()
    result_fast = execute_fast_global_registration(source_down, target_down,
                                                   source_fpfh, target_fpfh,
                                                   voxel_size)
    print(label, "Fast global registration took %.3f sec.\n" % (time.time() - start))
    print(label, result_fast)
    draw_registration_result(source_down, target_down,
                             result_fast.transformation)

if __name__ == "__main__":

    noise_label = 'noise: '
 
    noise_source_path = 'your path1'
    noise_target_path = 'your path2'
    
    voxel_size = 30

    noise_process = Process(target=run, args=(noise_label, noise_source_path, noise_target_path, voxel_size))
    # filtered_process = Process(target=run, args=(filtered_label, filtered_source_path, filtered_target_path, voxel_size))
    noise_process.start()
    # filtered_process.start()
    noise_process.join()
    # filtered_process.join()
    print ("Done")

```
2. run this python file
3. get not very good result

**Expected behavior**
The source and target cloud should be more consistent.

**Screenshots**
![image](https://user-images.githubusercontent.com/34240632/83843466-9864bc80-a737-11ea-8696-e3bcd72402ea.png)

**Environment (please complete the following information):**

- Operating system: (Windows 10 64-bit)
- Python version: (Python 3.7.3)
- Open3D version:  0.10.0.1
- Is this remote workstation?:  no
- How did you install Open3D?: pip

**Comment by bigpehi** [comment]
sorry,i have no idea with your problem. But i have a question as yours, it is what the voxel_size mean? Why it is different in different pointcloud file, I can only use voxel_size=0.00001 in my project, if I use 0.05 instead ,there will return an error. Thanks in advance.

**Comment by theNded** [comment]
@lyldev voxel size is way to large, it is 30 meters. Please try something smaller (like 0.05).
@bigpehi can you share a more detailed error log?
Also, FGR is faster but less stable than RANSAC. Please switch to RANSAC if you don't plan to run multi-way registration and still desire a high accuracy.

**Comment by bigpehi** [comment]
> @lyldev voxel size is way to large, it is 30 meters. Please try something smaller (like 0.05).
> @bigpehi can you share a more detailed error log?
> Also, FGR is faster but less stable than RANSAC. Please switch to RANSAC if you don't plan to run multi-way registration and still desire a high accuracy.

Thanks, I solved my problem yesterday, the reoson why i need use a smaller voxel_size is the different depth unit. I realized

**Comment by bigpehi** [comment]
> @lyldev voxel size is way to large, it is 30 meters. Please try something smaller (like 0.05).
> @bigpehi can you share a more detailed error log?
> Also, FGR is faster but less stable than RANSAC. Please switch to RANSAC if you don't plan to run multi-way registration and still desire a high accuracy.

Thanks😄, I solved my problem yesterday, the reoson why i need use a smaller voxel_size is the different depth unit. 
I realized 0.02 is 1000 times of 0.00002, so it is the times between "m" and "mm". 

By the way, do you know how can we choose a optimal voxel_size for our script?
Is voxel_size have relationship with the dense of point cloud or other parameter?
I want write a function , the input of it are some parameter like dense of point cloud ,and the output is a proper voxel_size.

**Comment by theNded** [comment]
It is very empirical, and we found 0.025 and 0.05 are usually good candidates according to our experiments.
