### ISSUE TITLE
Add a Mesh to a Existing Visualizer

### ISSUE THREAD

**Issue by Me817** [intel-isl/Open3D#1929]
Hello,

**Is your feature request related to a problem? Please describe.**
I am using the python api of Open3D 0.10.0. I would like to visualize some meshes via the visualizer and add a sphere to the visualized meshes in the opened visualizer by clicking on a button in my PyQt5 GUI. Until now I am able to open the visualizer with the meshes through a button click in my PyQt5 GUI but if I hit the add button to add a sphere mesh it opens a second visualizer in a new window (see Image 2).

**Describe the solution you'd like**
I would open a visualizer already showing a mesh by clicking the "Open Visualizer" button in my GUI and spawn a sphere I created in my GUI in the same visualizer by clicking on the "Add Sphere" button in my GUI.

**Describe alternatives you've considered**
I already read the non-blocking visualization example and the issues #389, #225, #343, #145, #305 but I cannot figure out how to do what I described above.

**Additional context**

![Visualizer1](https://user-images.githubusercontent.com/56630682/83870198-1d4ad880-a72e-11ea-9c34-09e9e1d2cb8c.PNG)
Image 1: This visualizer is opened by clicking on the "Open Visualizer" button.

![Visualizer2](https://user-images.githubusercontent.com/56630682/83870202-1f149c00-a72e-11ea-8cd0-4e1e5234ac49.PNG)
Image 2: By setting the properties of the sphere and clicking on the "Add Sphere" button the second visualizer gets opened.

In this file you can see the code for the "Add sphere" window where I call the methods to open the visualizers.
[Add_mesh_to_existing_visualizer.txt](https://github.com/intel-isl/Open3D/files/4735699/Add_mesh_to_existing_visualizer.txt)

Please let me know if you need more information.

**Comment by q-chen95** [comment]
Hello, Have you solved this problem? I also encountered this problem but I don't know how to solve it，but i think the reason may be:  The operations of the pyqt5 main window and the visualizer class are all running on the main thread.

**Comment by Me817** [comment]
Hello, no. I haven't solved this problem yet. But I keep trying. As soon as I have a solution, I'll be in touch.

**Comment by Me817** [comment]
Hi,

today I have found a solution to add a mesh to an existing Visualizer using a PyQt5 gui.
As you can see here:
![Added_Mesh_to_existing_Visualizer1](https://user-images.githubusercontent.com/56630682/86119086-22533b80-bad2-11ea-9706-d15a7f21a3fb.png)
This is the Visualizer I opened by clicking the "Open Visualizer"-button you can see in the gui in a comment above.
![Added_Mesh_to_existing_Visualizer2](https://user-images.githubusercontent.com/56630682/86119092-24b59580-bad2-11ea-8944-69670ede61f7.png)
By clicking the "Add Sphere "-button I am able to add the sphere mesh to the existing Visualizer.
Therefore I wrote these two methods for the button clicked events:
```
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_sphere.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtWidgets
import open3d as o3d

def clicked_open(self):
    # creates the visualizer
    self.vis = o3d.visualization.Visualizer()
    self.vis.create_window("Visualizer", 960, 540)
    # loads the point cloud and show it in the vis Visualizer
    pcd = o3d.io.read_point_cloud("../../../Desktop/bilder/pcd/00000.pcd")
    self.vis.add_geometry(pcd)

def clicked_add_sphere(self):
    # creates the sphere mesh
    self.sphere_radius = float(self.lineEdit_radius.text())
    self.red = float(self.lineEdit_red.text())
    self.green = float(self.lineEdit_green.text())
    self.blue = float(self.lineEdit_blue.text())
    sphere = o3d.geometry.TriangleMesh.create_sphere(radius=self.sphere_radius)
    sphere.compute_vertex_normals()
    sphere.paint_uniform_color([self.red, self.green, self.blue])
    # adds the sphere to the existing visualizer
    self.vis.add_geometry(sphere)
    self.vis.poll_events()
    # with run you are able to change the viewpoint angle with the mouse
    self.vis.run()
```
Hope this helps you solve the problem in your context.

**Comment by prewettg** [comment]
I'm not sure that Qt and the 0.10 visualizer will work together since they use different run loops, and we have no plans to integrate with Qt. However, we release an improved renderer and a GUI framework native to Open3D in 0.11. The [add-geometry.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/add-geometry.py) example shows two different ways of adding geometry using the new GUI. See [vis-gui.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/vis-gui.py) for a more comprehensive example.
