### ISSUE TITLE
building docs UnicodeDecodeError

### ISSUE THREAD

**Issue by johnbomidi** [intel-isl/Open3D#1933]
After compiling from source, I was building docs and was at the last step
http://www.open3d.org/docs/release/builddocs.html#Build

It copied the notebooks and was executing them, from file_io through kdtree; it was processing mesh and exited with this error:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2245: character maps to <undefined>

**To Reproduce**
After building from source, follow the steps in the python environment:
http://www.open3d.org/docs/release/builddocs.html

**Expected behavior**
"The docs html will be saved in docs/_out folder."

**Screenshots**
![image](https://user-images.githubusercontent.com/37553132/83979340-5a9c9b00-a8d3-11ea-9ded-4345ab1dea36.png)

**Environment:**

- Operating system: Windows 10 64-bit
- Python version: 3.8
- Open3D version: latest, 0.10.0
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): -G Visual Studio 2019

**Additional context**

**Comment by yxlao** [comment]
Thanks for reporting. We currently support building docs on Ubuntu/macOS. We may look into it in the future. In the meantime if you find a fix, please feel free to submit your fixes via a PR.
