### ISSUE TITLE
draw_geometrie issue when using the code example given in the documentation

### ISSUE THREAD

**Issue by Fred3D-tech** [intel-isl/Open3D#1940]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
draw_geometrie issue when using the code example given in the documentation

**To Reproduce**
using this tutorial : http://www.open3d.org/docs/release/tutorial/Basic/icp_registration.html
this command give an error:
    o3d.visualization.draw_geometries([source_temp, target_temp],
                                      zoom=0.4459,
                                      front=[0.9288, -0.2951, -0.2242],
                                      lookat=[1.6784, 2.0612, 1.4451],
                                      up=[-0.3402, -0.9189, -0.1996])

how can I orient the camera to get a usable view ? If I use the mouse only, I have a problem with the position of the light...

**Environment :**

- Operating system: Windows 10 64-bit
- Python version: Python 3.6
- Open3D version: open3d 0.10.0 
- Is this remote workstation?:  no
- How did you install Open3D?: conda

**Comment by griegler** [comment]
What is the problem exactly? Do you get an error, or is the camera view not satisfying? Are you using your own data, or the one of the tutorial?

**Comment by Fred3D-tech** [comment]
you get this error:
Traceback (most recent call last):
  File "C:/Anaconda3/sensors/registration.py", line 102, in <module>
    current_transformation = GlobalRegistration(source, target_cumul)
  File "C:/Anaconda3/sensors/registration.py", line 35, in GlobalRegistration
    up=[-0.3402, -0.9189, -0.1996])
TypeError: draw_geometries(): incompatible function arguments. The following argument types are supported:
    1. (geometry_list: List[open3d.open3d.geometry.Geometry], window_name: str = 'Open3D', width: int = 1920, height: int = 1080, left: int = 50, top: int = 50) -> None

Invoked with: [geometry::PointCloud with 5577595 points., geometry::PointCloud with 5973712 points.]; kwargs: zoom=0.4459, front=[0.9288, -0.2951, -0.2242], lookat=[1.6784, 2.0612, 1.4451], up=[-0.3402, -0.9189, -0.1996]
if you use this command instead:
o3d.visualization.draw_geometries([source, target])
it works...

**Comment by griegler** [comment]
I see. The tutorials use a monkey patched version of the `draw_geometries` method. You can use `jupyter_draw_geometries` from [here](https://github.com/intel-isl/Open3D/blob/master/examples/Python/open3d_tutorial.py) that supports the remaining keyword arguments. Note that the tutorials include this file by default.

**Comment by Fred3D-tech** [comment]
thank you but know I get:
Traceback (most recent call last):
  File "C:/Anaconda3/sensors/registration.py", line 156, in <module>
    current_transformation = GlobalRegistration(source, target_cumul)
  File "C:/Anaconda3/sensors/registration.py", line 88, in GlobalRegistration
    up=[-0.3402, -0.9189, -0.1996])
  File "C:/Anaconda3/sensors/registration.py", line 59, in jupyter_draw_geometries
    vis.get_view_control().set_lookat(lookat)
AttributeError: 'open3d.open3d.visualization.ViewControl' object has no attribute 'set_lookat'

Process finished with exit code 1

**Comment by salamanders** [comment]
Same here.  First time user, I start copy-pasting scripts to see if this will work at all, then get stuck for a while thinking I somehow installed the wrong version.    Now I'm not sure if I should paste the open3d_tutorial.py file at the head of my hello_world.py script, or some other technique.

It feels like a bug that the first simple scripts can't be copy/pasted and run.

**Comment by griegler** [comment]
@salamanders you are right. I fixed it in #1997.

**Comment by shivagur** [comment]
> 

@Fred3D-tech but in this o3d.visualization.draw_geometries([source, target]) what does source and target specifies ?...could you please help me out

**Comment by Jumponthemoon** [comment]
> All I am doing is running [this] (http://www.open3d.org/docs/release/tutorial/geometry/rgbd_image.html) tutorial on colab and still problem persists. ![Issue1](https://user-images.githubusercontent.com/97428436/173852201-1f57cc74-b9e9-4c50-bcd4-b7ed71a8c999.jpg)

Same problem here

**Comment by VimalMollyn** [comment]
It works if you remove the zoom param.
