### ISSUE TITLE
I tried to build the C++ implementation on Ubuntu but I go the error message: "MakeFile:149: recipe for target 'all' failed

### ISSUE THREAD

**Issue by brennanOnTheMoor** [intel-isl/Open3D#1949]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**

**To Reproduce**

1. cd '...'
2. python '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
- Python version: (e.g. Python 3.6)
- Open3D version:
- Is this remote workstation?: yes or no
- How did you install Open3D?: (e.g. pip, conda, build from source)
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

**Additional context**

**Comment by yxlao** [comment]
closing as no detailed commands and full error messages are provided, feel free to open a new issue with detailed info
