### ISSUE TITLE
C++ Style For contributing not clear

### ISSUE THREAD

**Issue by nachovizzo** [intel-isl/Open3D#1952]
Hello there, this is not really a bug but more sort of a question.

So, on the Open3D style guide, it says `"[DO] Use object-oriented design"`, **but**, judging for the implementation of the [FPFHFeature](https://github.com/intel-isl/Open3D/blob/c46b0b7667815754d735794f60fdbaac3721b2d4/src/Open3D/Registration/Feature.h#L70) it's not quite clear to me.

I want to start contributing to a small Keypoint detection library(`ISS`, `RoPs`, `MeshDoG`, `NARF`), and maybe others, depending on how much time I have. There is an open issue regarding this topic #1944 

To make it more clear, I've already implemented the `ISS` keypoint detector with 2 design approach. All the source code is available at the [github](https://github.com/nachovizzo/Open3D-Keypoints/blob/master/src/Open3D) repo, but an extract is the following

## Object-Oriented` approach (my choice)
**ISSKeypointDetector.h:**
```cpp
class ISSKeypointDetector {
public:
    explicit ISSKeypointDetector(
            const std::shared_ptr<geometry::PointCloud>& cloud)
        : cloud_(cloud), kdtree_(*cloud) {}

    /// Function to compute ISS keypoints for a point cloud.
    std::shared_ptr<geometry::PointCloud> ComputeKeypoints();

    /// Compute the model resolution;
    static double ComputeResolution(const geometry::PointCloud& cloud,
                                    const geometry::KDTreeFlann& kdtree);

    inline double ModelResolution() const {
        return ComputeResolution(*cloud_, kdtree_);
    }

protected:
    /// Helper function to compute the scatter matrix for a a point in the input
    /// pointcloud
    Eigen::Matrix3d ComputeScatterMatrix(const Eigen::Vector3d& p) const;

public:
    /// Input PointCloud where to extract the keypoints
    std::shared_ptr<geometry::PointCloud> cloud_;

    /// KDTree to accelerate nearest neighbour searches
    geometry::KDTreeFlann kdtree_;

    /// The radius of the spherical neighborhood used to compute the scatter
    /// matrix
    double salient_radius_ = 0.0;
    /// The non maxima suppression radius.
    double non_max_radius_ = 0.0;
    /// The upper bound on the ratio between the second and the first
    /// eigenvalue returned by the EVD.
    double gamma_21_ = 0.975;
    /// The upper bound on the ratio between the third and the second
    /// eigenvalue returned by the EVD.
    double gamma_32_ = 0.975;
    /// Minimum number of neighbors that has to be found while applying the
    /// non maxima suppression algorithm.
    int min_neighbors_ = 5;
};
```

**NOTE:** The C++ counterpart could be found [here](https://github.com/nachovizzo/Open3D-Keypoints/blob/master/src/Open3D/Keypoints/ISSKeypointDetector.cpp)
## Procedural programming approach
**ISSKeypointDetector.h:**
```cpp
namespace open3d {
namespace keypoints {

/// Function to compute ISS keypoints for a point cloud.
std::shared_ptr<geometry::PointCloud> ComputeISSKeypoints(
        const geometry::PointCloud& input,
        double salient_radius = 0.0,
        double non_max_radius = 0.0,
        double gamma_21 = 0.975,
        double gamma_32 = 0.975,
        int min_neighbors = 5);

/// Compute the model resolution;
double ComputeResolution(const geometry::PointCloud& cloud,
                         const geometry::KDTreeFlann& kdtree);
```
**NOTE:** The C++ counterpart could be found [here](https://github.com/nachovizzo/Open3D-Keypoints/blob/88a6c763e5eab2e8ec60c448e9cd58096c346f39/src/Open3D/Keypoints/ISSKeypointDetector.cpp)

## Timing

I didn't do a serious benchmark, although on the Armadillo mesh the `OO` approach was a bit faster than the procedural one.

## Is this even working?

Sure thing! Here are some nice results:
![ScreenCapture_2020-06-11-20-56-33](https://user-images.githubusercontent.com/21349875/84464889-13eccf00-ac4c-11ea-8879-6562d3d9ef18.png)
![ScreenCapture_2020-06-11-20-57-33](https://user-images.githubusercontent.com/21349875/84464895-15b69280-ac4c-11ea-84d3-32e682c07ec6.png)

**Comment by germanros1987** [comment]
Hi @nachovizzo,

It is a tough question. In the past, we have not had a very amazing OO design in Open3D, particularly for some of the functionalities coping with registration. However, we would like to make software that is easy to reuse and extend, without introducing too much computational overhead (this is what we are going for).

With this in mind, I prefer "your choice", even if it introduces a small overhead with respect to the procedural version. 

Thank you for your contribution!

**Comment by nachovizzo** [comment]
Ok, thanks for the reply.

I could also add the best of both worlds and add a static member function to the `PoinCloud` class like it's done with the Poisson reconstruction.
```cpp
    static std::tuple<std::shared_ptr<TriangleMesh>, std::vector<double>>
    CreateFromPointCloudPoisson(const PointCloud &pcd,
                                size_t depth = 8,
                                size_t width = 0,
                                float scale = 1.1f,
                                bool linear_fit = false);
```

Anyway, I will polish the implementation a bit and open a PR soon where we can discuss more details if you have any comments on #1944 please let me know. Thanks for the fast reply!
