### ISSUE TITLE
How to change width of LineSet?

### ISSUE THREAD

**Issue by mengxingshifen1218** [intel-isl/Open3D#1953]
I use Ctrl + +/-   to Increase/decrease width of LineSet, but no response，can I program it ？

**Comment by griegler** [comment]
The line width is currently defunct in OpenGL to the best of my knowledge. You can find workarounds in the issues using cylinders.

**Comment by germanros1987** [comment]
We will make sure to incorporate this feature in the new visualizer.

**Comment by mengxingshifen1218** [comment]
I'm looking forward to it.




---Original---

**Comment by theNded** [comment]
Addressed in #2803 in the new visualizer.
