### ISSUE TITLE
Render points as spheres instead of squares

### ISSUE THREAD

**Issue by Hippogriff** [intel-isl/Open3D#1957]
Points in point clouds are rendered as squares. Is it possible to render them as dots/spheres/balls? Rendering them as balls will look good in my opinion.

**Comment by germanros1987** [comment]
@errissa I believe this is currently not something we can do in an efficient way, am I wrong?

**Comment by errissa** [comment]
@germanros1987 There are a couple of ways we could implement this efficiently but both would take some time. Perhaps we can discuss at our next meeting.

**Comment by germanros1987** [comment]
We decided we won't be supporting this feature for the time being.

**Comment by MeyerBuaharon** [comment]
@germanros1987 Hey, I was wondering if this feature implemented yet?

**Comment by danemerson13** [comment]
+1 this would be a nice feature to have
