### ISSUE TITLE
Visualize Point Cloud Sequentially

### ISSUE THREAD

**Issue by Me817** [intel-isl/Open3D#1961]
Hello,

in my project I would like to visualize my point clouds sequentially in the same visualizer. 
I splitted a mkv file into frames, converted them to point clouds and saved them in a directory. Now I would like to open a visualizer with the first point cloud in the directory. When I press a key I would like to skipp to the next point cloud in the directory.
The approach would be:
1. visualize first point cloud
2. press GLFW_KEY_RIGHT
3. visualize next point cloud in the same window, in other words: replace the first point cloud with the second point cloud
4. press GLFW_KEY_RIGHT
5. replace the second with the third
and so on... until the end of the directory

I have already tried to implement this according to the examples interactive visualization and the azure_kinect_mkv_reader.py because there the visualizer shows the data sequentially. But not with key control.

Here is my approach:

```
# this code is created according to azure_kinect_mkv_reader.py  

     import open3d as o3d
     import os

     class VisualizerWithCallback:

        def __init__(self):
            self.flag_play = True
            self.flag_exit = False
            self.flag_next = False

        def space_callback(self, vis):
            self.flag_exit = True
            return False

        def enter_callback(self, vis):
            if self.flag_play:
                print('Playback paused, press [ENTER] to continue.')
            else:
                print('Playback resumed, press [ENTER] to pause.')
            self.flag_play = not self.flag_play
            return False

        def right_callback(self, vis):
            self.flag_next = True
            return False

        def run(self):
            glfw_key_enter = 257
            glfw_key_space = 32
            glfw_key_right = 262
            vis = o3d.visualization.VisualizerWithKeyCallback()
            vis.register_key_callback(glfw_key_enter, self.enter_callback)
            vis.register_key_callback(glfw_key_space, self.space_callback)
            vis.register_key_callback(glfw_key_right, self.right_callback)

            vis_geometry_added = False
            vis.create_window("Visualizer", 960, 540)

            print("Visualizer initialized. Press [ENTER] to pause/start, [SPACE] to exit.")

            pcd_dir = "../../Desktop/bilder/pcd/"

            pcd_file_list = []
            for pcd_file in os.listdir(pcd_dir):
                pcd_filename = os.fsdecode(pcd_file)
                if pcd_filename.endswith(".pcd"):
                    pcd_file_list.append(pcd_filename)

            idx = 0
            while idx <= len(pcd_file_list) and not self.flag_exit:
                if self.flag_play:
                    pcd = pcd_dir + pcd_file_list[idx]
                    read_pcd = o3d.io.read_point_cloud(pcd)
                    if pcd is None:
                        continue

                    if not vis_geometry_added:
                        vis.add_geometry(read_pcd)
                        vis_geometry_added = True
                        vis.run()

                # print("next: ", self.flag_next)
                if self.flag_next:
                    try:
                        print(pcd)
                        vis.update_geometry(read_pcd)
                    except NameError:
                        pass
                    vis.poll_events()
                    vis.update_renderer()
                    idx += 1

    if __name__ == "__main__":
        visualizer = VisualizerWithCallback()
        visualizer.run()
```
This code shows an empty visualizer. In the console I can see that he reads the different point clouds but they are not visualized. If I comment out the "if self.flag_next:" statement and bring the try-except- block on the same indention level as the if statements above only the first point cloud is visualize. Even though the other point clouds are read in. Sometimes I can pause and continue the reading process or exit with space but it does not response to the right_callback.

Does anyone have any idea how this can be implemented? 
Thank you in advance.

**Comment by liuchangji** [comment]
you need to use 
while(True):
     vis.add_geometry(read_pcd)
     vis.poll_events()
     vis.update_renderer()
     vis.clear_geometries()
to show cloud sequentially 


in the [tutoria](http://www.open3d.org/docs/release/tutorial/Advanced/non_blocking_visualization.html)l vis.update_geometry(read_pcd) must work with read_pcd.transform(trans)


but when you refresh the Visualizer all the time...you can't user your mouse to change view...i don't know how to solve thie problem

**Comment by Me817** [comment]
Many thanks for the quick response. 
Unfortunately, that doesn't work for me either. Either only the first point cloud is displayed and it does not change or nothing is displayed at all.  At what indentation level would I need to implement the `while(True)`-loop? Within the ```if self. flag_play```-statement?

I don't like to skip through the point clouds by mouse click. Is there a way to do this with keyboard input instead? This means that you can skip with the **"right arrow key"**; for example, or with **page up** or otherwise with the **space bar**. Because in the azure_kinect_mkv_reader.py example you can pause and continue the visualization of the point clouds via space bar or escape key.

Thank you in advance.

**Comment by g2ragrawal** [comment]
```
import open3d
import glob

def vis_dict(dict):
    pcds=sorted(glob.glob('{}/*.pcd'.format(dict)))
    print(pcds)
    vis=open3d.visualization.VisualizerWithKeyCallback()
    vis.create_window()
    idx=0
    pcd=open3d.io.read_point_cloud(pcds[idx])
    vis.add_geometry(pcd)
    #vis.update_renderer()
        
    def right_click(vis):
        nonlocal idx
        print('right_click')
        idx=idx+1
        vis.clear_geometries()
        pcd=open3d.io.read_point_cloud(pcds[idx])
        vis.add_geometry(pcd)
        
    def exit_key(vis):
        vis.destroy_window()
        
    vis.register_key_callback(262,right_click)
    vis.register_key_callback(32,exit_key)
    vis.poll_events()
    vis.run()
    #vis.destroy_window()    
        
if __name__=='__main__':
    vis_dict('/path/to/dict')
```

**Comment by Me817** [comment]
@g2ragrawal Thank youa lot for the code. I will try this tomorrow.

**Comment by Me817** [comment]
The script provided by @g2ragrawal works fine. I can skip forwards and backwards through the point cloud data and change the view point angle with the mouse. Thanks again.

**Comment by liuchangji** [comment]
The script provided by @g2ragrawal works fine.But I met a function problem.And I can change the view point angle with the mouse. So I read first frame point,and use mouse to change the view point to see it clearly.
But when I skip forwards  through the point cloud data,the view point angle will reset to the very beginning angle.Can I keep the current angle after I skip a point cloud?
