### ISSUE TITLE
Manipulate position coordinate of sphere by key events

### ISSUE THREAD

**Issue by Me817** [intel-isl/Open3D#1965]
Hello,

**Is your feature request related to a problem? Please describe.**
I would like to visualize a sphere in a point cloud similar to the spheres in the interactive visualization. But I would like to be able to move the sphere by mouse or keyboard interaction.

**Describe the solution you'd like**
I would like to visualize a point cloud together with a sphere. The sphere should be small and located in the middle of the point cloud. Then I would like to be able to move the sphere to a different place with different coordinates using shift+mouse dragging or the arrow keys on my keyboard. 

**Describe alternatives you've considered**
I saw that get_picked_points() or pick_points() prints the position of the sphere where I clicked. So maybe it is possible to change the x-coordinate of the sphere position by plus 1 pressing the right arrow key and -1 by pressing the left arrow key. And the same for y-coordinate by pressing the up arrow key (+1) or down arrow key (-1).
Or to drag the sphere with the shift + left mouse click and as soon as the shift + left mouse click is released the coordinates of the sphere are set.

**Additional context**
I would like to use these keys:
![tasten](https://user-images.githubusercontent.com/56630682/84786983-b9f25d80-afed-11ea-8c7a-b4ff2a8a62eb.png)

And I would like to manipulate these coordinates:
[Open3D INFO] Picked point 444 **(0.26, 0.48, -1.1)** to add in queue.
Maybe it is already possible but I can not find a solution in the documentation.

Thank you in advance.

**Comment by germanros1987** [comment]
@Me817 in the new Visualization app you can manipulate your models using mouse and keyboard. Have you tried that out?
Probably the main limitation right now is that the app is just for one model. We are working now on providing the new renderer and GUI as a python API so that you can easily create any variations of this functionality by yourself. 

This feature will be out in a few weeks.

**Comment by SilenKZYoung** [comment]
hello, did this issue has been fixed?

**Comment by prewettg** [comment]
Unfortunately we did had time to address this issue in the last release. I am working on the improved draw_geometries visualizer right now and will keep this use case in mind.

**Comment by Me817** [comment]
@germanros1987 Thank you for your advice. Unfortunately I do not know which Visualization App do you mean. Currently I use the VisualizerWithKeyCallback and add a coordinate frame to the point cloud in the visualizer. With the q-w-e-a-s-d-keys I add 0.01 or substract 0.01 to the current coordinates of the coordinate frame. To visualize the new position of the coordinate frame I remove it from the point cloud and add it at the new position. It works, but it would be nice to additionally have the option to left click on the coordinate frame, keep the left click pressed and move the coordinate frame to a different place in the point cloud and save the new position.
Is there a possibility to visualize the new position without removing and re-adding the coordinate frame to the point cloud/visualizer?
Thank you in advance.

**Comment by prewettg** [comment]
@Me817, @germanros1987 was referring to the Open3D viewer application, which is in `build/bin/Open3D` if you build from source, or available from download from [Github](https://github.com/intel-isl/Open3D/releases/tag/v0.11.2) (see "open3d-app-..."). Fly mode will let you move the camera's viewpoint with WASDF, rotate with the arrow keys, and a few others (see the Help menu in the app). It sounds like this is may be similar to what you want. However, if you are looking to move the selected point with the keyboard, I do not believe that is possible with our current visualizers at present. But, with the new open3d.visualization.draw() / open3d.visualization.O3DVisualizer, you can add action buttons with a callback of your choosing, which would at least address your use case, even if it is not ideal.

**Comment by chris-aeviator** [comment]
@prewettg are there any examples available howto use the O3DVisulalizer in python?

**Comment by prewettg** [comment]
[examples/python/gui/draw.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py) has several different examples of using the `draw()` function, including adding action buttons. If you want to use the O3DVisualizer directly, take a look at the code for `draw()`, which is in [python/open3d/visualization/draw.py](https://github.com/intel-isl/Open3D/blob/master/python/open3d/visualization/draw.py). (For anyone coming from Google, there is also a C++ example at [examples/cpp/Draw.cpp](https://github.com/intel-isl/Open3D/blob/master/examples/cpp/Draw.cpp)

**Comment by vanloctc** [comment]
> @Me817, @germanros1987 was referring to the Open3D viewer application, which is in `build/bin/Open3D` if you build from source, or available from download from [Github](https://github.com/intel-isl/Open3D/releases/tag/v0.11.2) (see "open3d-app-..."). Fly mode will let you move the camera's viewpoint with WASDF, rotate with the arrow keys, and a few others (see the Help menu in the app). It sounds like this is may be similar to what you want. However, if you are looking to move the selected point with the keyboard, I do not believe that is possible with our current visualizers at present. But, with the new open3d.visualization.draw() / open3d.visualization.O3DVisualizer, you can add action buttons with a callback of your choosing, which would at least address your use case, even if it is not ideal.

Hi @prewettg ,
To the present time, It seems we can't manipulate with points (select point) on the SceneWidget instead of open3D::visualization::Draw or DrawGeometriesWithEditing right ?
