### ISSUE TITLE
Add error tolerance to simplify_quadric_decimation

### ISSUE THREAD

**Issue by FreakTheMighty** [intel-isl/Open3D#1972]
**Is your feature request related to a problem? Please describe.**
I would like a way to decimate a mesh to a target face count while not exceeding a specified error threshold. This would allow me to aggressively decimate a mesh while ensuring that it doesn't diverge from the source mesh more than a certain amount.

**Describe the solution you'd like**
I propose the addition of an optional argument:
`open3d.geometry.simplify_quadric_decimation(input, target_number_of_triangles, max_error=None)`

**Describe alternatives you've considered**
I'm not terribly familiar with the the algorithm, but if it could return an error metric upon completion, then I could decimate with different values and observe the resulting error.

I also wondered if there are established algorithms for comparing source and decimated mesh similarity? If such an algorithm were provided, I could decimate with a particular target, compare the meshes, then adjust the input to the decimation accordingly.

**Comment by FreakTheMighty** [comment]
@griegler I've opened a pull request for this feature.

**Comment by griegler** [comment]
Thanks @FreakTheMighty
