### ISSUE TITLE
Why is MTL file saved with OBJ file as a default behavior?

### ISSUE THREAD

**Issue by tatsy** [intel-isl/Open3D#1974]
**Is your feature request related to a problem? Please describe.**

I am wondering why there is not a feature that disable writing MTL, and in my opinion, as a default behavior, it should not be saved.

```python
import open3d as o3d
mesh = o3d.io.read_triangle_mesh('bunny.ply')
o3d.io.write_triangle_mesh('bunny.obj', mesh)
# Then, "bunny.obj" and "bunny.mtl" is saved.
```

**Describe the solution you'd like**
This problem comes from the following part (and the codes above it).
https://github.com/intel-isl/Open3D/blob/b58440d61b882a5d0849a329c08a6bd8b85e15ba/cpp/open3d/io/file_format/FileOBJ.cpp#L383

I think we can add a flag like `write_mtl_file=True/False` as a parameter of `write_triangle_mesh` to disable saving the MTL file.

**Describe alternatives you've considered**
Actually, MTL file is only for OBJ file. Therefore, it can be strange to add `write_mtl_file` to `write_triangle_mesh` that can save other file formats such as PLY, OFF. etc. If we can determine whether the MTL file is necessary or not, it will be a much better solution (but I think it is rather difficult and someone want to add other flags to control what are saved or not). 

**Additional context**
I am happy to contribute this update.

**Comment by griegler** [comment]
@prewettg @errissa can you please take this into account.

**Comment by errissa** [comment]
@tatsy Thank you for offering to help with this feature request. If you are willing, we would welcome a PR implementing the change you suggested. Please review the contribution guidelines here: http://www.open3d.org/docs/release/contribute/contribute.html

We will be working on the IO code of Open3D in the near future so if you do not have time at the moment to contribute a PR we will take into account this feature request as we make changes to the IO.

**Comment by tatsy** [comment]
@griegler @errissa Thank you very much for your consideration. Of course, I am still happy to contribute to this update.

Before making a PR, I would like to ask which of the following two is more preferable.

1. Add a flag `write_mtl_file` to `WriteTriangleMesh`
2. Disable to save an MTL file when `write_triangle_uvs` is `False`

Although the 1st one is clearer to show how to enable or disable MTL file saving, it is not backward compatible because the number of arguments will be changed.

On the other hand, the second one is backward compatible because it does not change the input arguments. I think it is like a default behavior of MeshLab, and can be understood by people who are familiar to the software for 3D geometry processing. However, it cannot be really helpful to the beginners.

I also welcome another suggestion from you. Thank you!

**Comment by theNded** [comment]
@tatsy Thanks for your contribution. I prefer the second solution. Please let me know if you need help with the PR.

**Comment by tatsy** [comment]
@theNded Again, thank you very much for your help and the review for my code.

**Comment by theNded** [comment]
Thanks for your contribution! Closed since it is merged and resolved.
