### ISSUE TITLE
(make error) lost some .h file  when I compiling from source

### ISSUE THREAD

**Issue by Anita1683147070** [intel-isl/Open3D#1980]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
`/home/jiuzhang/hd4T/Open3D/cpp/open3d/io/FileFormat/FileOBJ.cpp:37:10: fatal error: tiny_obj_loader.h: 没有那个文件或目录
 #include <tiny_obj_loader.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/jiuzhang/hd4T/Open3D/cpp/open3d/geometry/SurfaceReconstructionPoisson.cpp:40:10: fatal error: PoissonRecon/Src/PreProcessor.h: 没有那个文件或目录
 #include "PoissonRecon/Src/PreProcessor.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cpp/open3d/geometry/CMakeFiles/geometry.dir/build.make:355: recipe for target 'cpp/open3d/geometry/CMakeFiles/geometry.dir/SurfaceReconstructionPoisson.cpp.o' failed
cpp/open3d/io/CMakeFiles/io.dir/build.make:303: recipe for target 'cpp/open3d/io/CMakeFiles/io.dir/FileFormat/FileOBJ.cpp.o' failed
make[2]: *** [cpp/open3d/geometry/CMakeFiles/geometry.dir/SurfaceReconstructionPoisson.cpp.o] Error 1
make[2]: *** [cpp/open3d/io/CMakeFiles/io.dir/FileFormat/FileOBJ.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:951: recipe for target 'cpp/open3d/geometry/CMakeFiles/geometry.dir/all' failed
make[1]: *** [cpp/open3d/geometry/CMakeFiles/geometry.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
In file included from /home/jiuzhang/hd4T/Open3D/cpp/open3d/io/FileFormat/FileGLTF.cpp:36:0:
/home/jiuzhang/hd4T/Open3D/cpp/open3d/io/FileFormat/tiny_gltf.h:1522:10: fatal error: stb_image.h: 没有那个文件或目录
 #include "stb_image.h"
          ^~~~~~~~~~~~~
compilation terminated.
cpp/open3d/io/CMakeFiles/io.dir/build.make:251: recipe for target 'cpp/open3d/io/CMakeFiles/io.dir/FileFormat/FileGLTF.cpp.o' failed
make[2]: *** [cpp/open3d/io/CMakeFiles/io.dir/FileFormat/FileGLTF.cpp.o] Error 1
CMakeFiles/Makefile2:984: recipe for target 'cpp/open3d/io/CMakeFiles/io.dir/all' failed
make[1]: *** [cpp/open3d/io/CMakeFiles/io.dir/all] Error 2
/home/jiuzhang/hd4T/Open3D/cpp/open3d/visualization/gui/Menu.cpp: In member function ‘open3d::gui::Menu::ItemId open3d::gui::Menu::Draw(const open3d::gui::DrawContext&, const char*, bool)’:
/home/jiuzhang/hd4T/Open3D/cpp/open3d/visualization/gui/Menu.cpp:223:42: error: invalid initialization of reference of type ‘const ImVec2&’ from expression of type ‘int’
     ImGui::SetNextWindowContentSize(width);
                                          ^
In file included from /home/jiuzhang/hd4T/Open3D/cpp/open3d/visualization/gui/Menu.cpp:33:0:
/home/jiuzhang/hd4T/Open3D/3rdparty/imgui/imgui.h:309:29: note: in passing argument 1 of ‘void ImGui::SetNextWindowContentSize(const ImVec2&)’
     IMGUI_API void          SetNextWindowContentSize(const ImVec2& size);                               // set next window content size (~ scrollable client area, which enforce the range of scrollbars). Not including window decorations (title bar, menu bar, etc.) nor WindowPadding. set an axis to 0.0f to leave it automatic. call before Begin()
                             ^~~~~~~~~~~~~~~~~~~~~~~~
cpp/open3d/visualization/gui/CMakeFiles/GUI.dir/build.make:277: recipe for target 'cpp/open3d/visualization/gui/CMakeFiles/GUI.dir/Menu.cpp.o' failed
make[2]: *** [cpp/open3d/visualization/gui/CMakeFiles/GUI.dir/Menu.cpp.o] Error 1
CMakeFiles/Makefile2:1173: recipe for target 'cpp/open3d/visualization/gui/CMakeFiles/GUI.dir/all' failed
make[1]: *** [cpp/open3d/visualization/gui/CMakeFiles/GUI.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`
"没有那个文件或目录"means "no such file or directiony"
**To Reproduce**
I got some errors when I typed in the command
"sudo make -j$"
 It is getting error because there is no header files  .h 
But I have updated 3rdparty

**Screenshots**
![QQ图片20200620100908](https://user-images.githubusercontent.com/39512152/85189083-2024fc00-b2de-11ea-8f3a-82c483d82d6e.png)

**Environment (please complete the following information):**

- Operating system: ( Ubuntu 18.04)
- Python version: ( Python 2.7)
- Open3D version: 
- Is this remote workstation?: yes
- How did you install Open3D?: ( build from source)
- Compiler version : (gcc 7.5.0, clang 6.0)

**Comment by comingtoyoulive** [comment]
I have the same problems..

**Comment by comingtoyoulive** [comment]
I solved it. you should fill the 3rdparty dir in root dir, but may be empty (there is no tiny_obj, poisson..).
It can be tackled by commanding 'git submodule update --init --recursive'. 
Even if not resolved in that way, there is some possibility. you should download the repo(https://github.com/intel-isl/Open3D-3rdparty) and replace directely the 3rdparty dir of the downloaded 3rdparty dir.

**Comment by NerdToMars** [comment]
understand you have updated 3rdparty lib, how did you update that?  if you using GitHub in China, might have some connection problem sometime. better check and show the content in your 3rdparty folder, it should have everything as listed in [Open3D/3rdparty/README.txt](github.com/intel-isl/Open3D/blob/master/3rdparty/README.txt);

**Comment by griegler** [comment]
Did you run `git clone --recursive https://github.com/intel-isl/Open3D` (note recursive), or `git submodule update --init --recursive`?

**Comment by Double-zh** [comment]
請問呢解決了嗎，我也遇到了類似的問題。
 [ 34%] Building CXX object cpp/open3d/visualization/gui/CMakeFiles/GUI.dir/Application.cpp.o
 In file included from /home/zhengzh/Open3D/build/_deps/fetch_filament-src/include/backend/Platform.h:22:0, from /home/zhengzh/Open3D/build/_deps/fetch_filament-src/include/filament/Engine.h:20, from /home/zhengzh/Open3D/cpp/open3d/visualization/rendering/filament/FilamentEngine.h:29, from /home/zhengzh/Open3D/cpp/open3d/visualization/gui/Application.cpp:47: /home/zhengzh/Open3D/build/_deps/fetch_filament-src/include/backend/DriverEnums.h:811:26: error: specialization of ‘template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive] template<> struct utils::EnableBitMaskOperators<filament::backend::TargetBufferFlags> ^ In file included from /home/zhengzh/Open3D/build/_deps/fetch_filament-src/include/backend/DriverEnums.h:22:0

**Comment by theNded** [comment]
For the original problem, please use the `recursive` clone or `submodule` update to synchronize the library. For the build issue, please try to upgrade to `g++ 7.5` or above, and file another issue if needed.
