### ISSUE TITLE
Reconstruct with depth image only

### ISSUE THREAD

**Issue by www158** [intel-isl/Open3D#1985]
Hello,
I want to use only depth image for reconstruction, but i do not know what code to change.I want help.
Thank you!

**Comment by theNded** [comment]
We don't support depth-only odometry now, but potentially you can try to extend [this module](https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/pipelines/odometry/RGBDOdometryJacobian.h) by adding other odometry methods as defined in [KinectFusion](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/ismar2011.pdf)

**Comment by www158** [comment]
> We don't support depth-only odometry now, but potentially you can try to extend [this module](https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/pipelines/odometry/RGBDOdometryJacobian.h) by adding other odometry methods as defined in [KinectFusion](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/ismar2011.pdf)

Thank you for your reply. I replaced color images into dummy image that has the single color,For example:
```
    # in register_one_rgbd_pair
    color_s = read_image("dummp.jpg")
```
I put dummy color image to the pipeline,And got good results.

**Comment by www158** [comment]
@theNded

**Comment by theNded** [comment]
This is quite unexpected lol, I thought there can be multiple issues with this method so didn't make a suggestion...

It is recommended to change [this parameter](https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/pipelines/odometry/RGBDOdometryJacobian.cpp#L38) to 1.0 if you choose this approach.
