### ISSUE TITLE
Add Intensity field to the pointcloud structure

### ISSUE THREAD

**Issue by nkhedekar** [intel-isl/Open3D#1989]
**Is your feature request related to a problem? Please describe.**
Most LiDARs provide points (xyz) with an intensity value. Even though reading of a file with xyzirgb is supported ([examples/Python/Basic/file_io.ipynb](examples/Python/Basic/file_io.ipynb)) through a .pts file, the intensity value is read but not used ([the read function being used](https://github.com/intel-isl/Open3D/blob/5935abc12bf2228d5f0a034b4040f24f1c8cdd11/cpp/open3d/io/FileFormat/FilePTS.cpp#L91)). 

A similar argument would hold even for the addition of a `ring` field. The intensity and ring fields are both present in the output from a rotation based lidar (eg. velodyne, ouster)

This need for the enhancement arises from the need to use the intensity and ring information of the points as well as the point location itself.

**Describe the solution you'd like**
Additional field of intensity and ring should be added to the pointcloud structure.
The `ReadPointCloudFromPTS` should be updated to store the intensity values it reads into this field.
A new function and extension should be defined that is able to read pointclouds that are saved with this information as xyzi and xyzir

**Comment by griegler** [comment]
Thanks for the request. We are currently rewriting the geometry classes and they will be able to store arbitrary fields per points for example. See #2074

**Comment by eltonhcchan** [comment]
@griegler May I know whether intensity is accessible from pointcloud, if so, how?
