### ISSUE TITLE
Realsense L515  RuntimeError: No device connected

### ISSUE THREAD

**Issue by wissalsayhi** [intel-isl/Open3D#1990]
Hi all, 

I'm trying to use realsense_record.py  to record data using Realsense L515. I keep having the error RuntimeError: No device connected although my device is connected with  USB3 and I can access the stream via intel viewer ! 

Any advice ! 

Thanks !

**Comment by FLS-BP-US** [comment]
The L515 does not support a lot resolutions/frame rates.  I got it work with:
  "d_capture_width": 1024,
  "d_capture_height": 768,
  "rgb_capture_width": 1280,
  "rgb_capture_height": 720,
  "capture_framerate": 30,
 My stream setup:
  d_config.enable_device(serial)
  d_config.enable_stream(rs.stream.depth, config["d_capture_width"], config["d_capture_height"], rs.format.z16, frame_rate)
  d_config.enable_stream(rs.stream.color, config["rgb_capture_width"], config["rgb_capture_height"], rs.format.bgr8, frame_rate)

I have not been successful with a reconstruction though.  I am running out of memory (32gb).  There might be a bug in the intrinsic file.

The following code will allow you to see your serial number.
def find_L515_device_serial():
    ctx = rs.context()
    devices = ctx.query_devices();
    for dev in devices:
        if dev.get_info(rs.camera_info.name) != "Intel RealSense L515":
            if dev.supports(rs.camera_info.name):
                print("Found L515 device:", dev.get_info(rs.camera_info.name))
            return dev.get_info(rs.camera_info.serial_number)
        else:
            return ""

**Comment by wissalsayhi** [comment]
Thank you very much . That solved my problem!

**Comment by devshank3** [comment]
Hi @FLS-BP-US,

where you able to port L515 RGBD sequence for Open3D reconstruction ?

**Comment by FLS-BP-US** [comment]
No, I believe there is an issue with depth units.  The D4xx uses 0.001m and
the L515 uses 0.00025m.  I tried scaling the L515's depth output but it
doesn't give usable results.
