### ISSUE TITLE
Silent version of open3d.io.read_point_cloud

### ISSUE THREAD

**Issue by FLS-BP-US** [intel-isl/Open3D#1994]
**Is your feature request related to a problem? When calling read_point_cloud, the following lines are printed to the console:
Format = auto
Extension = ply

**Describe the solution you'd like**
I can read the point cloud without lines being printed.

**Describe alternatives you've considered**
An optional silent flag be added.

**Comment by griegler** [comment]
Are you using the code from master? It seems to fixed in master.

**Comment by FLS-BP-US** [comment]
I am using the latest release for python.

**Comment by griegler** [comment]
Yes, it is for now only in master, not in the pip/conda packages.
