### ISSUE TITLE
OrientedBoundingBox.rotate Bug in conda v0.10.0.0 ?

### ISSUE THREAD

**Issue by OnlyRightNow** [intel-isl/Open3D#1996]
**OrientedBoundingBox.rotate Bug in v0.10.0?**
_____

**Description:**
If I rotate a OrientedBoundingBox and specify the **center of the rotation**, the OrientedBoundingBox gets **itself centered** at the specified center of the rotation. Yet, this is not the way it is specified in the [doc](http://www.open3d.org/docs/release/python_api/open3d.geometry.OrientedBoundingBox.html#open3d.geometry.OrientedBoundingBox.rotate).

This is especially weird because **other geometry types**, such as pointcloud, **work the expected way**; rotating around the specified transformation-center without being centered at this point. See below for an example.

**Example to reproduce:**
Create a oriented bounding box and rotate it 45 degrees around the origin of the frame. The rotated oriented bounding box gets centered at the origin (red).
Create a point cloud and rotate it 45 degrees around the origin of the frame. The rotated pointcould is rotated correctly around the origin, but is not centered at the origin (red).

```
obbox = bbox.get_oriented_bounding_box()
obbox.rotate(o3d.geometry.get_rotation_matrix_from_xyz(np.asarray([0, -np.pi/4, 0])), np.asarray([0, 0, 0]))
obbox.color = np.asarray([1, 0, 0])

pcd_copy = copy.deepcopy(pcd)
pcd_copy.rotate(o3d.geometry.get_rotation_matrix_from_xyz(np.asarray([0, -np.pi/4, 0])), np.asarray([0, 0, 0]))
pcd_copy.paint_uniform_color([1, 0, 0])

origin = o3d.geometry.TriangleMesh.create_coordinate_frame()
o3d.visualization.draw_geometries([origin, pcd, pcd_copy, bbox, obbox])
```
![bug_o3d_v0 10 0 0](https://user-images.githubusercontent.com/12793063/85530536-4e704780-b60e-11ea-909a-3d81025502f0.png)

**Expected behavior:**
The rotated oriented bounding box is rotated, in a similar fashion as the pointcloud, around the origin, but is **not centered** at the origin.

**Environment:**
- Operating system: Linux Mint 19.1
- Python version: 3.7.7
- Open3D version: 0.10.0.0 (conda)
- Is this a remote workstation?: No
- How did I install Open3D?: conda

**Comment by griegler** [comment]
Thanks for bringing this up. It is indeed a weird behavior and I fixed it in #1999.

**Comment by OnlyRightNow** [comment]
great thanks for the quick response! 
Is there a workaround before the release of the next version?

**Comment by griegler** [comment]
You should get the same result at the moment with (not tested, you might have to convert `obb.R, obb.center` to numpy first):

```python
obb.rotate(R=R @ obb.R, center=R @ (obb.center - center) + center)
```
