### ISSUE TITLE
get RGB coordinates (2D) after point cloud outlier removal

### ISSUE THREAD

**Issue by pieterbl86** [intel-isl/Open3D#2000]
Thanks for this great 3D software package, really enjoy working with it. 

I'm struggling with the last step of my image analysis, which requires to get the 2D coordinates (from the RGB image) after some point cloud filtering (statistical outlier removal). This question relates to #709

I'll summarize my analysis pipeline:

1. First get a ROI from the color image (RGB)
2. Clip the ROI on the XYZ-image (RGB and XYZ pixels are aligned)
3. Make a pointcloud from the XYZ-ROI
4. Remove the outliers using the remove_statistical_outlier function
5. Get the filtered ROI back and convert it to a binary mask so that it can be displayed / post-processed on the RGB image

I have reached to step 5 and there I'm failing to do a fast mapping on the RGB image.

The current code works, however is very slow (it usually takes 30-60 seconds for the last loop structure (assuming a pointcloud of +40.000 points)). It's pretty logic why the last loop is so slow (as it need to loop over all values):

```
# the bounding box coordinates of the ROI
bbox = np.array([214, 223, 501, 506]) 

# clip the xyz_img to the bounding-box
xyz_clipped_img = xyz_img[bbox[1]:bbox[3],bbox[0]:bbox[2]]
x = xyz_clipped_img[:,:,0].flatten()
y = xyz_clipped_img[:,:,1].flatten()
z = xyz_clipped_img[:,:,2].flatten()

# initialize the final mask (boolean array)
final_mask = np.zeros((xyz_clipped_img.shape[0],xyz_clipped_img.shape[1]),dtype=np.bool)

# make the point cloud
xyz = np.zeros((np.size(x), 3))
xyz[:, 0] = x
xyz[:, 1] = y
xyz[:, 2] = z
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyz)

# do the outlier removal
cl, ind = pcd.remove_statistical_outlier(nb_neighbors=50, std_ratio=0.05)

# search the xyz-coordinates of the filtered ROI in the original xyz_clipped_img
filtered_points = np.asarray(cl.points)
for j in range(filtered_points.shape[0]):
   id = np.where(np.any(xyz_clipped_img == filtered_points[j], axis = -1))
   final_mask[int(id[0][0]),int(id[1][0])] = True
```

**Comment by irfan798** [comment]
I believe indices stay the same
So if you have not down sampled the point cloud, you can do something like this:
```
flat = final_mask.flatten()
flat[ind] = True
final_mask = flat.reshape(final_mask.shape, order='C')
```
Also if `xyz_clipped_img` have X,Y,Z as values in it, you can make point cloud by reshaping it like:
```
xyz = xyz_clipped_img.reshape(-1, 3)
pcd.points = o3d.utility.Vector3dVector(xyz)
```
That should preserve indices
-1 in reshape means auto detect length of dimension

**Comment by pieterbl86** [comment]
> I believe indices stay the same
> So if you have not down sampled the point cloud, you can do something like this:
> 
> ```
> flat = final_mask.flatten()
> flat[ind] = True
> final_mask = flat.reshape(final_mask.shape, order='C')
> ```
> 
> Also if `xyz_clipped_img` have X,Y,Z as values in it, you can make point cloud by reshaping it like:
> 
> ```
> xyz = xyz_clipped_img.reshape(-1, 3)
> pcd.points = o3d.utility.Vector3dVector(xyz)
> ```
> 
> That should preserve indices
> -1 in reshape means auto detect length of dimension
> 
> So final code should look like this
> 
> ```
> # the bounding box coordinates of the ROI
> bbox = np.array([214, 223, 501, 506]) 
> 
> # clip the xyz_img to the bounding-box
> xyz_clipped_img = xyz_img[bbox[1]:bbox[3],bbox[0]:bbox[2]]
> 
> # initialize the final mask (boolean array)
> final_mask = np.zeros((xyz_clipped_img.shape[0],xyz_clipped_img.shape[1]),dtype=np.bool)
> 
> # make the point cloud
> pcd = o3d.geometry.PointCloud()
> pcd.points = o3d.utility.Vector3dVector(xyz_clipped_img.reshape(-1, 3))
> 
> # do the outlier removal
> cl, ind = pcd.remove_statistical_outlier(nb_neighbors=50, std_ratio=0.05)
> 
> # mark non-outlier points on xyz_clipped_img
> flat = final_mask.flatten()
> flat[ind] = True
> final_mask = flat.reshape(final_mask.shape, order='C')
> ```

@irfan798 thank you very much, this is a great addition. I inserted the code and it works, thanks again!
