### ISSUE TITLE
Shadows and rendering options

### ISSUE THREAD

**Issue by riccardomarin** [intel-isl/Open3D#201]
Hi,
I'm struggling to find some well documented set of options for Visualizer. It's possibile to cast the shadows?

Thanks
R

**Comment by qianyizh** [comment]
No, shadow casting has not been implemented.

The purpose of Visualizer is to provide a convenient way for visualization. Complicated rendering functions such as shadow, transparent surface, brdf, etc have been excluded from current implementation.

If they become a common request, we will consider adding it in future versions.

**Comment by syncle** [comment]
FYI, We are adopting a high-end rendering engine. This is [a working branch](https://github.com/intel-isl/Open3D/tree/gui).
