### ISSUE TITLE
.Stl export fails 

### ISSUE THREAD

**Issue by alexspace360** [intel-isl/Open3D#2012]
_____

**Describe the bug**
face a problem when exporting mesh as STL [Open3D WARNING] Write STL failed: compute normals first. 
 I have already computed them

**Screenshots**
![error stl](https://user-images.githubusercontent.com/62703745/85887269-bd54c880-b7e7-11ea-953b-a4081dcfa8c4.jpg)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version:  Python 3.6
- Open3D version:
- Is this remote workstation?: no
- How did you install Open3D?:  pip
-open3D 0.10.0
_____

**Comment by griegler** [comment]
Which normals did you compute? STL requires triangle normals.
Anyway, the error message can be improved.

**Comment by halmusaibeli** [comment]
Computing triangle normals with the line below works for me.
`poisson_mesh = o3d.geometry.TriangleMesh.compute_triangle_normals (poisson_mesh)`
