### ISSUE TITLE
Convex hull inconsistent 

### ISSUE THREAD

**Issue by mastrogiorgis** [intel-isl/Open3D#2022]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I'm trying to use ompute_convex_hull() function but the result is inconsistent and there are no parameters to adjust.

**To Reproduce**
Load and process a pcd using plane fit ransac

Then execute the following

```
 hull_mesh = inlier_cloud.compute_convex_hull()
   
 o3d.visualization.draw_geometries([hull_mesh[0]])

```
1. cd '...'
2. python '....'
3. See error

**Expected behavior**
I would expect the convex to be closely similar but not that different.

**Screenshots**
Here is the pointcloud
![image](https://user-images.githubusercontent.com/23278410/86005124-1ef57c80-ba0c-11ea-9e5f-d3b4a6ae0e59.png)

and here are the results when running using the same data.
![image](https://user-images.githubusercontent.com/23278410/86005152-29177b00-ba0c-11ea-939b-64557263ac16.png)
![image](https://user-images.githubusercontent.com/23278410/86005192-36cd0080-ba0c-11ea-8f1f-fe6bfa6d21d6.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7
- Open3D version: 0.10
- Is this remote workstation?:  no
- How did you install Open3D?:  conda 

**Additional context**

**Comment by griegler** [comment]
Can you provide your point cloud that is used to compute the convex hull? Also, have you checked if only the triangle orientation is inconsistent (in the visualizer hit `B` on the keyboard)?

**Comment by mastrogiorgis** [comment]
Thanks @griegler .
I tried to hit ` B ` and I get this:
![image](https://user-images.githubusercontent.com/23278410/86127983-a3adcc80-bad8-11ea-9430-9d2bf82d5dac.png)
What's that supposed to mean - the visualiser is causing this?

**Comment by griegler** [comment]
The triangles returned by the convex hull algorithm are not oriented consistently. Hence, you see holes in the standard visualization. By hitting `B` you see also triangles that are oriented in the opposite direction. You could try to call `orient_triangles` on the mesh. Anyways, it seems that qhull is not consistent in the way it returns the triangles, as different triangles are wrongly oriented.

**Comment by mastrogiorgis** [comment]
Is this fixed then?

**Comment by griegler** [comment]
No, that is dependent on how qhull works.

**Comment by mastrogiorgis** [comment]
Can I adjust any of the parameters to decrease the possibility of this happening all the time? I mean, PCL has a convex hull algorithm and didn't have issues there (well I had other issues on other algorithms '😂). Any idea on how to access the raw coordinates of the hull without worrying about the OpenGL's triangles? I use VTK to visualise anyhow.
Many thanks!

**Comment by griegler** [comment]
Do you have a complete runnable minimum example that shows the problem? I just tried to reproduce it with the code below and the triangle meshes are always identical (using different seeds).

```python
import numpy as np
import open3d as o3d

np.random.seed(18)

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(np.random.uniform(-1,1, size=(1000,3)))

hull0, _ = pcd.compute_convex_hull()
verts0 = np.asarray(hull0.vertices)
trias0 = np.asarray(hull0.triangles)

hull1, _ = pcd.compute_convex_hull()
verts1 = np.asarray(hull1.vertices)
trias1 = np.asarray(hull1.triangles)

print(np.abs(verts0 - verts1).max())
print(np.abs(trias0 - trias1).max())
```

**Comment by mastrogiorgis** [comment]
Sure - thanks for looking into this.

```
class planeProcessing:
    
    def __init__(self):
        pass
    
    def plane_fit_convex(pcd):
        pcds = []
        
        for i in range(4):
        
            
            plane_model, inliers = pcd.segment_plane(distance_threshold=0.01,
                                                 ransac_n=30,
                                                 num_iterations=1000)
            [a, b, c, d] = plane_model
            #print(f"Plane equation: {a:.2f}x + {b:.2f}y + {c:.2f}z + {d:.2f} = 0")
            
            inlier_cloud = pcd.select_by_index(inliers)
            inlier_cloud.paint_uniform_color([1.0, 0, 0])
            outlier_cloud = pcd.select_by_index(inliers, invert=True)
            
            pcd = outlier_cloud
            pt = np.asarray(outlier_cloud.points)
            dpt = pt.size/3
            # return only large PCs
            if dpt > 1000:
                #o3d.visualization.draw_geometries([inlier_cloud])
        
        
                hull_mesh = inlier_cloud.compute_convex_hull()
                o3d.visualization.draw_geometries([hull_mesh[0]])
                pcds.append(hull_mesh[0])
            return pcds
   
            
 
    pcd = o3d.io.read_point_cloud("0.pcd")
    
    plane_fit_convex(pcd)           
            
```


[0.zip](https://github.com/intel-isl/Open3D/files/4995959/0.zip)
zip has the pcd point cloud

**Comment by griegler** [comment]
I just had another look at your code and I think I know what the problem is: `segment_plane` will return different inlier points per run (it is a randomized algorithm in the end), hence you also get different convex hulls. So, the results are kind of expected. 
That said, another problem is that your points are almost co-planar (you segment a plane and compute the convex hull). This usually leads to precision problems.

**Comment by mastrogiorgis** [comment]
You are right here about the segment_plane, but the convex should fill the area without hitting B key. 
I used to get fine results with PCL in terms of hull processing. Any parameters I could change for compute_convex_hull?

**Comment by griegler** [comment]
Have you tried `orient_triangles`? http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.orient_triangles

**Comment by mastrogiorgis** [comment]
Yes! That worked.

`hull_mesh[0].orient_triangles()`
![image](https://user-images.githubusercontent.com/23278410/89028996-52863800-d325-11ea-9bc3-03c974b1d48c.png)

**Comment by wangmiaowei** [comment]
Thanks for your suggestion about using oriant_traingles. But I get a question how we can get the bounding vertices(cooridinates) of such a convex hull
