### ISSUE TITLE
Point Cloud Crop: How can I make it done automatically

### ISSUE THREAD

**Issue by LightCannon** [intel-isl/Open3D#2029]
Hello, as far as I know, In order to crop, I need to save the json file using the pop up window for saving after selecting the cropping polygon (inside VisualizerWithEditing) , then read the result json in cropping the point cloud. 

My Question is how can I automatically save the json with a certain name without popping up a save window? (or at the best case return this json directly from the visualizer) So that the user doesn't have to save first on his own with a certain name, then reload it using the name he entered. Is there a way around this?

**Comment by griegler** [comment]
@prewettg @errissa @germanros1987 that sounds like something that should be taken care of in the new visualizer functionality.

**Comment by prewettg** [comment]
It may be some time before the new visualizer will have this functionality. However, it already appears to exist in the C++ code: you can inherit from VisualizerWithEditing and set `use_dialog_ = false` in C++. If you are using Python you'd have to export that with Python bindings (see cpp/open3d/pybind/visualization/visualizer.cpp in the current master branch). Or if you'd like to make a pull request, move the use_dialog_ member from protected to public, and add a pybind for it.
