### ISSUE TITLE
open3d 0.10.0 support for Ubuntu16.04

### ISSUE THREAD

**Issue by EthanZhangYi** [intel-isl/Open3D#2037]
open3d v0.10.0 does NOT support Ubuntu16.04. `import open3d` raises an ImportError.
```
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/zhangyi/miniconda3/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so)
```
Ubuntu16.04 only supports up to `GLIBC_2.23'

**Comment by yxlao** [comment]
This is expected. As stated in readme:

> Pre-built pip and conda packages support Ubuntu 18.04+, macOS 10.14+ and
Windows 10 (64-bit) with Python 3.5, 3.6, 3.7 and 3.8. If you have other Python
versions or operating systems, please
[compile Open3D from source](http://www.open3d.org/docs/release/compilation.html).

For now, please compile from source.

(The proper solution is to build python packages with [`manylinux`](https://github.com/pypa/manylinux), which we may look into in the future.)

**Comment by adizhol** [comment]
@yxlao I'm trying to build v0.10.0 from source, and I'm getting this error:
```
In file included from /home/azholkover/code/Open3D/3rdparty/fmt/include/fmt/format.h:60:0,
                 from /home/azholkover/code/Open3D/src/Open3D/Utility/Console.h:35,
                 from /home/azholkover/code/Open3D/src/Open3D/Geometry/Image.h:34,
                 from /home/azholkover/code/Open3D/src/Open3D/Geometry/TriangleMesh.h:37,
                 from /home/azholkover/code/Open3D/src/Open3D/Geometry/SurfaceReconstructionBallPivoting.cpp:30:
/home/azholkover/code/Open3D/3rdparty/fmt/include/fmt/core.h:622:56: error: ‘fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>::formatter_type<Eigen::Transpose<Eigen::Matrix<double, 3, 1> > >::type f’ has incomplete type
     typename Context::template formatter_type<T>::type f;
                                                        ^
src/Open3D/Geometry/CMakeFiles/Geometry.dir/build.make:341: recipe for target 'src/Open3D/Geometry/CMakeFiles/Geometry.dir/SurfaceReconstructionBallPivoting.cpp.o' failed
make[2]: *** [src/Open3D/Geometry/CMakeFiles/Geometry.dir/SurfaceReconstructionBallPivoting.cpp.o] Error 1

```

**Comment by quantaji** [comment]
Hi, I managed to build open3d on manylinux2014 docker (based on centos7). I hope this can help https://github.com/quantaji/open3d-manylinux2014/tree/main
