### ISSUE TITLE
allow custom key callbacks for all Visualizer types

### ISSUE THREAD

**Issue by cmatija** [intel-isl/Open3D#2038]
In Python, when using Visualizer, adding custom key callbacks seems to only be possible for VisualizerWithKeyCallback (am I wrong about this? please let me know if so). That's unfortunate, as I would love to e.g. have the possibility to use a VisualizerWithEditing (to be able to select points) with custom key callbacks as well. 

A relatively straight-forward way to achieve this would be to implement a method to register custom key callbacks inside Visualizer.h so that all other Visualizer classes inheriting from it can benefit from that functionality as well. In that case, the class VisualizerWithKeyCallback wouldn't be necessary anymore, and so the whole library would retain the same functionality, in an even more general way than it does now, with less source files. Sound like a good idea?

**Comment by griegler** [comment]
@prewettg is currently in the process of creating Python bindings for the new visualizer that should have those capabilities.

**Comment by cmatija** [comment]
great, thanks a lot!
