### ISSUE TITLE
Change camera forward direction and draw depth plane

### ISSUE THREAD

**Issue by makeastir** [intel-isl/Open3D#2046]
I currently using open3d python for 3d visualization.

For my goal, I want to change camera forward direction using normal vector and want to draw depth plane for verify to plane sweeping method can fully cover point cloud.

So i converted depth map to point cloud and at this point. And then i want to change camera forward direction about normal vector. But i can't search information about that.

Clear up of my question :

1.How can i change camera forward direction using normal vector?

2.How can i draw depth plane in 3D point cloud ?

Could you give me advice ?

Below is my code:
```
import numpy as np
import open3d as o3d

def main():
  normal_0 = np.load('./normal_0.npy')
  normal_1 = (normal_0*(50/65535.)).reshape(3,1).astpye(np.float64)
  
  normal_0 = o3d.geometry.PointCloud()
  normal0.points = o3d.utility.Vector3dVector([normal_0])
  normal0.paint_uniform_color([1, 0.706, 0])
  
  cloud = o3d.io.read_point_cloud("pc.ply")
  o3d.visualzation.draw_geometries([cloud, normal0])
  VC = o3d.visualization.ViewControl()
  VC.set_front(normal0)
if __name__ == "__main__":
  main()
```

**Comment by BingXiong1995** [comment]
Have you solved this problem?

**Comment by BingXiong1995** [comment]
I solved this problem just now. You can use orient_normals_towards_camera_location to make the normal towards to camera. Here is my sample code:
```
    downpcd = pcd.voxel_down_sample(voxel_size=0.005)
    downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30),)
    downpcd.orient_normals_towards_camera_location(camera_location=np.array([0., 0., 0.]))
```
