### ISSUE TITLE
Compilation Instructions for Python 2 

### ISSUE THREAD

**Issue by MeiyingQin** [intel-isl/Open3D#2049]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Based on the instructions (http://www.open3d.org/docs/release/getting_started.html), the compilation should work for python 3. But the instructions here (http://www.open3d.org/docs/release/compilation.html#compilation) are for python 3, and failed for python 2 (I have to use python 2 to be compatible with my project). 

**To Reproduce**
1. Followed the instructions from: http://www.open3d.org/docs/release/compilation.html#compilation . The Python executable was checked and it is python 2.
2. run the sanity check: python -c "import open3d"
3. See error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/***/.local/lib/python2.7/site-packages/open3d/__init__.py", line 60, in <module>
    raise Exception("Open3D only supports Python 3.")
Exception: Open3D only supports Python 3.

**Expected behavior**
It should be able to import open3d without the error.

**Screenshots**

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04,
- Python version: Python 2.7.17
- Open3D version: 0.10
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5

**Additional context**

**Comment by griegler** [comment]
Open3D 0.9 was the last release with official support for Python 2. (http://www.open3d.org/2019/12/19/open3d-0-9-0-is-ready/)
