### ISSUE TITLE
Get intrinsic parameters from AzureKinectSensor

### ISSUE THREAD

**Issue by LuyaooChen** [intel-isl/Open3D#2051]
I create a k4a sensor by `k4a=o3d.io.AzureKinectSensor(config)`, and capture the rgbd image by `k4a.capture_frame()`.
Then I want to create a pointcloud from rgbd image by `o3d.geometry.PointCloud.create_from_rgbd_image`.
How to get the intrinsic parameters of Azure Kinect Sensor directly?

**Comment by www158** [comment]
Do you get the same resolution as the color image and depth image, If it is inconsistent, it cannot be compiled.here is 
my config.json:
{
    "path_dataset": "G:\\Open3D\\examples\\Python\\ReconstructionSystem\\sensors\\frameses1",
    "path_intrinsic": "G:\\Open3D\\examples\\Python\\ReconstructionSystem\\sensors\\frameses1/intrinsic.json",
    "depth_map_type": "redwood",
    "n_frames_per_fragment": 100,
    "n_keyframes_per_n_frame": 5,
    "min_depth": 0.3,
    "max_depth": 3.0,
    "voxel_size": 0.05,
    "max_depth_diff": 0.07,
    "preference_loop_closure_odometry": 0.1,
    "preference_loop_closure_registration": 5.0,
    "tsdf_cubic_size": 3.0,
    "icp_method": "color",
    "global_registration": "ransac",
    "python_multi_threading": "true",
    "folder_fragment": "fragments/",
    "template_fragment_posegraph": "fragments/fragment_%03d.json",
    "template_fragment_posegraph_optimized": "fragments/fragment_optimized_%03d.json",
    "template_fragment_pointcloud": "fragments/fragment_%03d.ply",
    "folder_scene": "scene/",
    "template_global_posegraph": "scene/global_registration.json",
    "template_global_posegraph_optimized": "scene/global_registration_optimized.json",
    "template_refined_posegraph": "scene/refined_registration.json",
    "template_refined_posegraph_optimized": "scene/refined_registration_optimized.json",
    "template_global_mesh": "scene/integrated.ply",
    "template_global_traj": "scene/trajectory.log"
}

intrinsic.json:
{
	"color_mode" : "MJPG_720P",
	"depth_mode" : "WFOV_2X2BINNED",
	"height" : 720,
	"intrinsic_matrix" : 
	[
		610.40960693359375,
		0.0,
		0.0,
		0.0,
		610.15240478515625,
		0.0,
		641.385498046875,
		365.62338256835938,
		1.0
	],
	"serial_number_" : "000376502412",
	"stream_length_usec" : 5366689,
	"width" : 1280
}


But I can only get the intrinsic of the color camera. I want to convert it to a point cloud through the depth image. Do you have the intrinsic of the depth camera?

**Comment by LuyaooChen** [comment]
@www158  In the function `capture_frame(self, enable_align_depth_to_color)` of open3d.io.AzureKinectSensor, you can set `enable_align_depth_to_color` True, then you can capture  color image and depth image with the same resolution. This is implemented in [Azure Kineck Sensor SDK](https://docs.microsoft.com/en-us/azure/kinect-dk/use-image-transformation). If you want to get calibration parameters, you can use C/C++, [look here](https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/classk4a_1_1device_ac857cfc66cd1c367d48cb83fba8a032c.html#ac857cfc66cd1c367d48cb83fba8a032c). It seems to  be not implemented in Open3D now.

**Comment by www158** [comment]
@LuyaooChen  Thank you for your advice. While recording I set the parameters  `--align_depth_to_color` ,and the window shows the same resolution as the color and the depth. But the resolution of the final color image is 1280x720(24), and the resolution of the depth image is 512x512(16), which is not consistent.

**Comment by LuyaooChen** [comment]
@www158  Sorry, I misremembered. I use [pyk4a](https://github.com/etiennedub/pyk4a) to capture image actually...

**Comment by theNded** [comment]
See #2071
