### ISSUE TITLE
how to capture high quality data for 3d reconstruction with D435

### ISSUE THREAD

**Issue by WSPeng** [intel-isl/Open3D#2053]
Hi, I am trying to use D435 to capture dataset for 3d reconstruction (http://www.open3d.org/docs/release/tutorial/ReconstructionSystem/capture_your_own_dataset.html). But the reconstruction result is not good due to the low quality data. Holding the camera with my hand may not be a good idea. May I ask is there any suggestion to capture good quality data with D435 for reconstruction? (like using tripod?)

**Comment by leomariga** [comment]
You can get better results using post-processing algorithms provided by the librealsense. There are information detailing the use of those filters[ in this page](https://dev.intelrealsense.com/docs/depth-post-processing). You can modify the file `realsense_recorder.py` and add filtering functions there. The available functions are [described here](https://intelrealsense.github.io/librealsense/python_docs/_generated/pyrealsense2.html)

``` python
# Define your filter
dec_filter = rs.decimation_filter()  # Decimation - reduces depth frame density
spat_filter = rs.spatial_filter()        # Spatial - edge-preserving spatial smoothing
temp_filter = rs.temporal_filter()   # Temporal - reduces temporal noise
thresh_filter = rs.threshold_filter() # Threshold - limits the max distance
depth_to_disparity = rs.disparity_transform(True)
disparity_to_depth = rs.disparity_transform(False)

# Change filters parameters
spat_filter.set_option(rs.option.filter_magnitude, 4)
temp_filter.set_option(rs.option.filter_smooth_alpha, 0.2)
temp_filter.set_option(rs.option.filter_smooth_delta, 50)

#Using Filtering
frame = dec_filter.process(aligned_depth_frame)
frame = thresh_filter.process(frame)
frame = depth_to_disparity.process(aligned_depth_frame)
frame = spat_filter.process(frame)
frame = temp_filter.process(frame)
frame = disparity_to_depth.process(frame)
```
You should find the parameters that best fits your problem, and also be aware of the trade-off that exists in using them.

**Comment by WSPeng** [comment]
> You can get better results using post-processing algorithms provided by the librealsense. There are information detailing the use of those filters[ in this page](https://dev.intelrealsense.com/docs/depth-post-processing). You can modify the file `realsense_recorder.py` and add filtering functions there. The available functions are [described here](https://intelrealsense.github.io/librealsense/python_docs/_generated/pyrealsense2.html)
> 
> ```python
> # Define your filter
> dec_filter = rs.decimation_filter()  # Decimation - reduces depth frame density
> spat_filter = rs.spatial_filter()        # Spatial - edge-preserving spatial smoothing
> temp_filter = rs.temporal_filter()   # Temporal - reduces temporal noise
> thresh_filter = rs.threshold_filter() # Threshold - limits the max distance
> depth_to_disparity = rs.disparity_transform(True)
> disparity_to_depth = rs.disparity_transform(False)
> 
> # Change filters parameters
> spat_filter.set_option(rs.option.filter_magnitude, 4)
> temp_filter.set_option(rs.option.filter_smooth_alpha, 0.2)
> temp_filter.set_option(rs.option.filter_smooth_delta, 50)
> 
> #Using Filtering
> frame = dec_filter.process(aligned_depth_frame)
> frame = thresh_filter.process(frame)
> frame = depth_to_disparity.process(aligned_depth_frame)
> frame = spat_filter.process(frame)
> frame = temp_filter.process(frame)
> frame = disparity_to_depth.process(frame)
> ```
> 
> You should find the parameters that best fits your problem, and also be aware of the trade-off that exists in using them.

Thank you ;D
