### ISSUE TITLE
(python) no open3d.registration when building from source

### ISSUE THREAD

**Issue by cmatija** [intel-isl/Open3D#2056]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When building from source (commit: 12ad57b9b2bb3dd58d3cded584848939bedb92f3) and installing the pip-package, from python, there is no open3d.registration module. In contrast, when installing open3d using pip install open3d, open3d.registration is there.

**To Reproduce**

simply follow the build instructions on the open3d website, run make install-pip-package, and then try to use open3d.registration in python code.

**Expected behavior**
open3d.registration should be there.

**Environment (please complete the following information):**

- Operating system: arch linux
- Python version: Python 3.7
- Open3D version: 0.10.1.0
- Is this remote workstation?: no
- How did you install Open3D?: build from source, using a conda environment-specific python interpreter
- Compiler version (if built from source): gcc 10.1.0

**Comment by pbeeson** [comment]
+1

**Comment by griegler** [comment]
If you compile a recent version (from master) of the code, you might find it via `o3d.pipelines.registration` (http://www.open3d.org/docs/latest/python_api/open3d.pipelines.registration.html)
