### ISSUE TITLE
Reconstruction system with Azure Kinect?

### ISSUE THREAD

**Issue by www158** [intel-isl/Open3D#2070]
I am using the color images and depth images obtained by Azure Kinect for Open3D reconstruction, I can't get a color image and a depth image at the same resolution. And the resolution of the depth images obtained by Azure Kinect can  be 640x576，320x288，512x512 and 1024x1024,cannot synchronize and match with color image.

Environment

- OS: Windows 10 64-bit
- Python version: Python 3.6.6
- Open3D version: 0.9.0
- Azure Kinect SDK: v1.2.0
- Is this remote workstation?: no

Because compilation doesn't pass this step:
![1594606134(1)](https://user-images.githubusercontent.com/67252756/87263840-e6b46a80-c4f0-11ea-9dcb-d6cf0499dd89.jpg)

**Comment by griegler** [comment]
@theNded should have an answer to this question.

**Comment by theNded** [comment]
Please refer to #2071 and use our mkv reader to parse the pre-stored mkv video captured from either Azure Kinect's official app or ours.
