### ISSUE TITLE
Get intrinsic from Azure Kinect? 

### ISSUE THREAD

**Issue by www158** [intel-isl/Open3D#2071]
Hello,
I've got a depth image , how to convert it to a point cloud. I can get the intrinsic of the color camera, but i don't know the intrinsic of the depth camera. Can anyone who has had success with this share any tips, or share the intrinsic for Kinect? Any parameters I can adjust in my case to get it running?

**Comment by griegler** [comment]
@theNded should have an answer to this.

**Comment by theNded** [comment]
We need the mkv file recorded by AzureKinect to parse the calibration. It will be stored in a json file `intrinsic.json`, see https://github.com/intel-isl/Open3D/blob/master/examples/python/ReconstructionSystem/sensors/azure_kinect_mkv_reader.py#L60
