### ISSUE TITLE
Open3d compiling failed

### ISSUE THREAD

**Issue by WSPeng** [intel-isl/Open3D#2079]
**Describe the bug**
open3d compiling failed

**To Reproduce**
According to the http://www.open3d.org/docs/release/compilation.html instruction.

1. mkdir build
2. cd build
3. sudo cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.6 ..
4.  sudo make -j$(nproc)

**Expected behavior**
The building process failed 

**Screenshots**
....
collect2: error: ld returned 1 exit status
cpp/apps/CMakeFiles/Open3DViewer.dir/build.make:135: recipe for target 'bin/Open3D/Open3D' failed
make[2]: *** [bin/Open3D/Open3D] Error 1
[ 78%] Built target ManuallyCropGeometry
CMakeFiles/Makefile2:1474: recipe for target 'cpp/apps/CMakeFiles/Open3DViewer.dir/all' failed
make[1]: *** [cpp/apps/CMakeFiles/Open3DViewer.dir/all] Error 2
...
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Environment (please complete the following information):**

- Operating system:  Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: master branch on commit 122a15b
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5 

**Additional context**

**Comment by rish-av** [comment]
Hey, how did you solve the issue?

**Comment by lqzhao** [comment]
Hey, how did you solve the issue?
