### ISSUE TITLE
Create HalfEdgeTriangleMesh from TriangleMesh failed

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2091]
Hello, 

I'm try to create HalfEdgeTriangleMesh from TriangleMesh. but with no success -- crash. I did the followings

`
    auto mesh = open3d::geometry::TriangleMesh::CreateFromPointCloudBallPivoting(*pcd, radii);
    mesh->RemoveNonManifoldEdges();
    mesh->RemoveDuplicatedVertices();
    mesh->RemoveDuplicatedTriangles();
    mesh->RemoveDegenerateTriangles();
    mesh->RemoveUnreferencedVertices();
    open3d::visualization::DrawGeometries({ mesh });
    auto half_edge_mesh = open3d::geometry::HalfEdgeTriangleMesh::CreateFromTriangleMesh(*mesh);
`

The triangle mesh can be displayed, it seems no problem. Anything more do I need to do before the creation of HalfEdgeTriangleMesh from TriangleMesh? It seems to be the problem of duplicate half-edge. But how to solve it?  

Thank you in advance!

**Comment by griegler** [comment]
Can you post any error message or warning that you get?
