### ISSUE TITLE
Unable to Compile from source on Ubuntu 18.04

### ISSUE THREAD

**Issue by zainmehdi** [intel-isl/Open3D#2094]
**Describe the bug**
I am just trying to compile from source. It compiles well for about 71% and then gives undefined reference errors.

**To Reproduce**
Just try to compile from source on Ubuntu machine.

**Screenshots**
![image](https://user-images.githubusercontent.com/21212125/88019988-d42bd800-cb65-11ea-8472-cac93b2aaf50.png)

- Operating system: ( Ubuntu 18.04, Windows 10 64-bit)
- Python version: (2.7)
- Open3D version:
- Is this remote workstation?: no
- How did you install Open3D?: ( build from source)
- Compiler version (if built from source): (gcc 7.5, )

**Comment by femust** [comment]
have you tried install the required files from scripts?

**Comment by zainmehdi** [comment]
Yes I tried. I will try to get it once again and get back here. Thanks

**Comment by zainmehdi** [comment]
I figured it out. Even after installing dependencies I was getting undefined reference error for libfilament. I just installed dependencies for libfilament as mentioned on their github wiki

    clang-7 or higher
    libglu1-mesa-dev
    libc++-7-dev (libcxx-devel and libcxx-static on Fedora) or higher
    libc++abi-7-dev (libcxxabi-static on Fedora) or higher
    ninja-build
    libxi-dev

and the issue was fixed. I hope it will help someone struggling with the same issue.
