### ISSUE TITLE
What are i, j, k used for here?

### ISSUE THREAD

**Issue by yd-yin** [intel-isl/Open3D#2095]
https://github.com/intel-isl/Open3D/blob/a3621c53546d289dc1cac875c12aca48b8d228bf/cpp/open3d/io/file_format/FileLOG.cpp#L60

The function `ReadPinholeCameraTrajectoryFromLOG` here seems to read camera parameters from a log file. 

I don't really understand the purpose of the three integer variables `i, j, k`. They are read first before the real extrinsic parameters.

It seems that these three variables are not used in this cpp file. I don't know if there are some other references.

**Comment by yd-yin** [comment]
https://github.com/intel-isl/Open3D/blob/a3621c53546d289dc1cac875c12aca48b8d228bf/examples/test_data/RGBD/trajectory.log#L1

Also, in example code, they are set to `0 0 1`, `1 1 2`, `2 2 3`, etc. They seem "magic", something like password or what

**Comment by griegler** [comment]
@theNded @yxlao can one of you have a look at this please.

**Comment by theNded** [comment]
This special file format is defined here: http://redwood-data.org/indoor/registration.html, only for reading/writing trajectory now.
