### ISSUE TITLE
Module 'open3d.open3d_pybind.geometry' has no attribute 'create_mesh_box'

### ISSUE THREAD

**Issue by ryanayf** [intel-isl/Open3D#2097]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
_module 'open3d.open3d_pybind.geometry' has no attribute 'create_mesh_box'

**To Reproduce**
I used the following code and it returns the above error

```
import open3d as o3d
import numpy as np
import copy
 
box = o3d.geometry.create_mesh_box(width=1.0, height=1.0, depth=1.0)
o3d.visualization.draw_geometries([box])

```

**Expected behavior**
But when I create the arrow mesh, it works completely fine:

`arrow = o3d.geometry.TriangleMesh.create_arrow(cylinder_radius=1.0e-5, cone_radius=1.5e-5, cylinder_height=5.0e-5, cone_height=4.0e-5, resolution=20, cylinder_split=4, cone_split=1)
`

**Screenshots**
This is the screenshot of the error: 
![image](https://user-images.githubusercontent.com/61911315/88107221-04e03180-cba7-11ea-9f87-e4598fb04b71.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7
- Open3D version: 0.10.0.1
- Is this remote workstation?: no
- How did you install Open3D?: pip install open3d

**Additional context**

**Comment by griegler** [comment]
In your version of open3d it is a member of `TriangleMesh` (http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.create_box)

`o3d.geometry.TriangleMesh.create_box()`
