### ISSUE TITLE
Estimate_normals() is not translation invariant?

### ISSUE THREAD

**Issue by WilliamKRobert** [intel-isl/Open3D#2108]
**Describe the bug**
When apply a translation to a point cloud, the results of estimate_normals are slightly different.

**To Reproduce**

1. follow the tutorial page: http://www.open3d.org/docs/release/tutorial/Basic/pointcloud.html
2. add a translation to the point cloud
3. calculate the difference of estimated normals (to avoid sign ambiguity, normals are taken absolute value)

**Expected behavior**
If I understand correctly, normal vectors are a local property and should not change after moving the point cloud to another position.

**Environment (please complete the following information):**

- Operating system: Ubuntu 16.04
- Python version: Python 3.7
- Open3D version: 0.9
- How did you install Open3D?: conda

**Comment by griegler** [comment]
@WilliamKRobert could you provide a minimum reproducible example that shows the problem. Thanks!

**Comment by WilliamKRobert** [comment]
It turns out to be an issue of normal direction. For the same point cloud, the direction of estimated normal flips randomly. I am closing the issue as it is not a bug of your code.
