### ISSUE TITLE
Save a 3-D point-cloud into an 2-D image without opening a window

### ISSUE THREAD

**Issue by somebodyus** [intel-isl/Open3D#2111]
**Is your feature request related to a problem? Please describe.**
I was able to save 3-D point-cloud image using the screen capture method. However, I will run the program in docker at a remote server. There is no X windows service, so the window displaying the point cloud cannot be opened. Is there any way to save the image without using screen capture method?

**Describe the solution you'd like**
I would like a method to directly save a 3-D point cloud from a viewpoint into a 2-D image without opening a window.

**Comment by griegler** [comment]
Did you have a look here: http://www.open3d.org/docs/release/tutorial/Advanced/headless_rendering.html?highlight=headless ?

**Comment by somebodyus** [comment]
I have successfully managed to run in headless rendering, but I got the following error when load the viewpoint.    

```
param = o3d.io.read_pinhole_camera_parameters("viewpoint.json")
vis.get_view_control().convert_from_pinhole_camera_parameters(param)
```
Error: 
`[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.`

**Comment by somebodyus** [comment]
> I have successfully managed to run in headless rendering, but I got the following error when load the viewpoint.
> 
> ```
> param = o3d.io.read_pinhole_camera_parameters("viewpoint.json")
> vis.get_view_control().convert_from_pinhole_camera_parameters(param)
> ```
> 
> Error:
> `[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.`
> 
> Note: The above statements have been tested OK for rendering with a GUI window.

Problem solved by calculating the intrinsic matrix using:
```
K = [[focal * width, 0, width / 2 - 0.5],
     [0, focal * width, height / 2 - 0.5],
     [0, 0, 1]]
```
Please see: https://github.com/intel-isl/Open3D/issues/1164

**Comment by tfy14esa** [comment]
Hi @somebodyus,
I am facing the same error message that you reported. For me, your solution sadly did not work. Could you perhaps send the script that you ran where it worked for you?
