### ISSUE TITLE
o3d.visualization.draw_geometries() incompactible function argument

### ISSUE THREAD

**Issue by Pradyumn10** [intel-isl/Open3D#2116]
I have been following the documentation of open3d and i have written the same code as given on http://www.open3d.org/docs/release/tutorial/Basic/visualization.html
for function draw geometries and also using the same data file i.e "fragment.ply". Now i am encountering an error while running the exact code.
" Error : TypeError: draw_geometries(): incompatible function arguments. The following argument types are supported:"
how can i resolve it

Operating System : Ubuntu 18.04
Python version = 3.6.7
open3d-python version = 0.7.0.0
open3d version = 0.10
installed using : pip3

**Comment by griegler** [comment]
Can you provide a minimal, reproducible example please.

**Comment by Pradyumn10** [comment]
![Screenshot from 2020-07-29 16-18-39](https://user-images.githubusercontent.com/63101822/88791384-3fedf080-d1b7-11ea-8a6a-a2d1107c02ea.png)

**Comment by griegler** [comment]
Could be that in your version of open3d some arguments of `draw_geometries` are not supported yet. Try compiling open3d from source, or remove the `zoom, front, lookat, up` params from the function call.

**Comment by Pradyumn10** [comment]
Tried with only one parameter i.e [pcd] and it worked.
Thank you!
