### ISSUE TITLE
Poisson surface reconstruction has random behavior

### ISSUE THREAD

**Issue by alexis-roche** [intel-isl/Open3D#2117]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
The mesh created from a point cloud using the create_from_point_cloud_poisson method is not the same across different calls to the function.

**To Reproduce**
Please run the following Python code assuming a point cloud file `data.ply`. 

```python
import sys
import open3d as o3d
import numpy as np
import pylab as plt

ntrials = 10
if len(sys.argv) > 1:
    ntrials = int(sys.argv[1])
    
pcd = o3d.io.read_point_cloud('data.ply')
meshes = [o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth=8, width=0, scale=1.1, linear_fit=False)[0]\
          for i in range(1 + ntrials)]
vertices = np.array([m.vertices for m in meshes])
errors = np.max(np.abs(vertices - vertices[0]), (1, 2))[1:]
print('Errors:', errors)
plt.plot(range(ntrials), errors, 'o:')
plt.title('Poisson reconstruction randomness')
plt.xlabel('Trial')
plt.ylabel('Deviation wrt reference')
plt.show() 
```

**Expected behavior**
The mesh output by Poisson reconstruction should always be the same.

**Screenshots**

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04.4 LTS
- Python version: Python 3.6.9
- Open3D version: 0.9.0.0
- Is this remote workstation?:no
- How did you install Open3D?: pip
- Compiler version (if built from source): 

**Additional context**

**Comment by griegler** [comment]
It is possible that this is due to multithreading. If you compile open3d from source you have a `n_threads` parameter in the `create_from_point_cloud_poisson` method. Setting this to `1` could resolve the issue.

**Comment by alexis-roche** [comment]
Thank you so much for your feedback Gernot. I will do that asap and let you know if it fixes the issue for me.

**Comment by alexis-roche** [comment]
I can confirm that setting `n_threads=1` after re-building open3d from the current git master branch fixes the reproducibility issue. Weirdly enough, the function also runs faster. Thanks again @griegler for your input.
