### ISSUE TITLE
Scaling pointclouds to the exact same size

### ISSUE THREAD

**Issue by agporto** [intel-isl/Open3D#2119]
Hi, thanks for the great library! 
I am trying figure out a straightforward way to scale two pointclouds (with complex shapes) to have the exact same size.  Let 's say you had two structures that were identical, but with very different absolute sizes and you wanted to register one to the other. I noticed that pointcloud geometry has a function to scale pointclouds using a float. My question is, is there any function within open3d capable of giving me this scaling parameter automatically based solely on the two pointclouds? Meaning, is there any way to calculate the difference in size between two pointclouds prior to any registration procedure?

**Comment by theNded** [comment]
You can use [TransformationEstimationPointToPoint](http://www.open3d.org/docs/release/python_api/open3d.registration.TransformationEstimationPointToPoint.html) with `with_scale=True`. This is used both in `registration_icp` and `registration_ransac_based_on_feature_matching` and will handle scale during registration.

**Comment by akkoumis** [comment]
As per the documentation:
The homogeneous transformation is given by

  𝑇=[𝑐𝐑  𝐭
         0    1]

Sets 𝑐=1
if with_scaling is False.

Could it be possible to replace c with a 3x3 matrix, taking into account different scales for different axes?

**Comment by cosama** [comment]
If using `with_scaling` in code similar to the global registration tutorial:

```python
result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
        source_down, target_down, source_fpfh, target_fpfh, True,
        distance_threshold,
        o3d.pipelines.registration.TransformationEstimationPointToPoint(True),  # with_scaling set to True
        3, [
            o3d.pipelines.registration.CorrespondenceCheckerBasedOnEdgeLength(
                0.2), # correspondence_edge_length lowered
            o3d.pipelines.registration.CorrespondenceCheckerBasedOnDistance(
                distance_threshold)
        ], o3d.pipelines.registration.RANSACConvergenceCriteria(100000, 0.999))
```

It is important to lower the `correspondence_edge_length` quite a bit as done in the code snipped here, otherwise it won't work with the scaling. Took me quite some time to figure this one out.
