### ISSUE TITLE
Will an algorithm similar to this icp variant in the pcl library be developed in the future? For example: IterativeClosestPointWithNormals

### ISSUE THREAD

**Issue by yangninghua** [intel-isl/Open3D#2122]
Will an algorithm similar to this icp variant in the pcl library be developed in the future? For example: IterativeClosestPointWithNormals

http://docs.ros.org/hydro/api/pcl/html/classpcl_1_1IterativeClosestPointWithNormals.html

**Comment by GnnrMrkr** [comment]
PCL only states they use an algorithm based on point-to-plane distances, but not exactly which one. 

Open3D has an implementation of the Algorithm by Chen and Medioni (1992), see the [corresponding section in the documentation](http://www.open3d.org/docs/release/tutorial/Basic/icp_registration.html#Point-to-plane-ICP).

I think this could be the variant you are looking for? If not, it would be helpful to know which algorithm exactly you mean.

**Comment by theNded** [comment]
We support both [point-to-point](http://www.open3d.org/docs/release/python_api/open3d.registration.TransformationEstimationPointToPoint.html) and [point-to-plane](http://www.open3d.org/docs/release/python_api/open3d.registration.TransformationEstimationPointToPlane.html). PointToPlane is what you want.
