### ISSUE TITLE
Questions about RANSACConvergenceCriteria

### ISSUE THREAD

**Issue by XuyangBai** [intel-isl/Open3D#2123]
Thanks for your great work. I am wondering the effect of `max_iteration` and `max_validation` in `RANSACConvergenceCriteria `. As shown [here](https://github.com/intel-isl/Open3D/blob/de9b015078aa3d86b3f54ba904aa309d2e054060/cpp/open3d/pipelines/registration/Registration.cpp#L217), when using the RANSAC based on correspondence, the aim of `max_iteration` and `max_validation` is the same, and the minimum value of them will be the iteration number. While for RANSAC based on feature matching ([code](https://github.com/intel-isl/Open3D/blob/de9b015078aa3d86b3f54ba904aa309d2e054060/cpp/open3d/pipelines/registration/Registration.cpp#L276)), since I am not an expert on OpenMP, I am not sure about the logic of the algorithm.  It seems every iteration in the for loop will increase the `itr ` by 1 and increase `total_validation` by one, so these two parameters are still having the same effect? If not, could you explain what is an iteration, and what is a validation?

Another question is that is there any plans to support the early stop scheme? For now it seems the algorithm runs as many iterations as we set (at least for ransac based on correspondence), which might be extremely slow.

Thanks a lot.

**Comment by theNded** [comment]
This is a very good point... we also don't quite understand why the initial author implemented it in this way. The roles `max_iteration` and `max_validation` play are also the same in feature based method. Therefore you may set these variables the same, or set one of them to be really large (to be ignored) and tune the other.

Return criteria is also a good suggestion. It is currently used in [RegistrationICP](https://github.com/intel-isl/Open3D/blob/de9b015078aa3d86b3f54ba904aa309d2e054060/cpp/open3d/pipelines/registration/Registration.cpp#L188) but not in RANSAC. You may only change several lines to enable this feature -- would you be willing to contribute and make a PR?

**Comment by XuyangBai** [comment]
Hi @theNded, I am glad to help but I think the situation between RANSAC and RegistrationICP should be different. ICP is **updating** the transformation matrix every iteration, thus we can early stop when the changes between two iterations are smaller than a threshold. However for RANSAC (take RANSAC based on correspondence as an example), in every iteration `ransac_n` number of correspondence are **randomly** sampled to estimate a transformation, so there is no way to early stop based on the changes between two iterations. I am not sure but I think RANSAC might update the theoretical iteration number based on the current inlier ratio in each iteration (and a pre-defined confidence level like 99.9%). So the maximum iteration number RANSAC needs will keep changing until the real iteration number reaches that value. Do you have some suggestions or references for the standard procedures?

**Comment by theNded** [comment]
You are right. But theoretical early termination is still a const value based on pre-estimated confidence, so there is no difference comparing to the current interface...

**Comment by XuyangBai** [comment]
But given a fixed pre-estimated confidence, the maximum iteration number changes with the inlier ratio updated every iteration, right? You may seed the opencv RANSAC implementation [here.](https://github.com/opencv/opencv/blob/2e6e9c14b5bc689f9444836bc245956d690ea42b/modules/calib3d/src/usac/ransac_solvers.cpp#L176)
