### ISSUE TITLE
"registration with fpfh return error sometimes"

### ISSUE THREAD

**Issue by kaixin-bai** [intel-isl/Open3D#2126]
i test registration with fpfh in a loop, code is below:
```
for i in range(100):
    result = o3d.registration.registration_ransac_based_on_feature_matching(
        match_model_pcd, scene_pcd, match_model_pcd_fpfh, scene_pcd_fpfh, distance_threshold,
        o3d.registration.TransformationEstimationPointToPoint(True), 3, [
            o3d.registration.CorrespondenceCheckerBasedOnEdgeLength(0.9),
            o3d.registration.CorrespondenceCheckerBasedOnDistance(
                distance_threshold)
        ], o3d.registration.RANSACConvergenceCriteria(4000000, 500))
    # if result.fitness < 0.504: continue
    print(result.fitness)
    o3d.visualization.draw_geometries([deepcopy(scene_pcd), deepcopy(match_model_pcd).transform(result.transformation)])
```

The result is strange sometimes.
the result should be like this(fitness 0.539):
![image](https://user-images.githubusercontent.com/38804949/89041010-eddad580-d344-11ea-8bfd-a4fbc8fe5b12.png)
Then i got result(fitness 1.0)
![image](https://user-images.githubusercontent.com/38804949/89041205-47430480-d345-11ea-8e03-db172c467675.png)

**Comment by kaixin-bai** [comment]
and also sometimes the model point cloud seems to be scaled in some loop.

**Comment by theNded** [comment]
`TransformationEstimationPointToPoint(True)` should take False instead. This flag indicates whether scaling is considered.
