### ISSUE TITLE
Color of TSDF mesh is incorrect

### ISSUE THREAD

**Issue by seann999** [intel-isl/Open3D#2129]
I am trying to use RGBD integration to construct a mesh.
It is supposed to be a beige wooden table with objects on it.
This is a partial render of the scene:
<img width="147" alt="ss2" src="https://user-images.githubusercontent.com/6847529/89170673-f3d9ec00-d5ba-11ea-9fdf-6179a895020a.png">
This is what I am getting from the TSDF:
<img width="151" alt="ss" src="https://user-images.githubusercontent.com/6847529/89170294-61d1e380-d5ba-11ea-8e32-8a6921f0e1a3.png">
The shape looks more or less correct, but the color is obviously incorrect.
I am passing 3 channel uint8 values for RGB.
What might be the problem?

**Comment by seann999** [comment]
I've solved the color problem, and it was something to do with how I created the RGBDImage.
Saving rgbd.color showed this, which is the pattern I saw on the odd mesh.
![rgb](https://user-images.githubusercontent.com/6847529/89214959-b7ca7980-d602-11ea-8b80-da6ca554d776.png)
I then changed
```color = o3d.geometry.Image(rgb)```
to
```
cv2.imwrite('rgb.png', rgb[:, :, [2, 1, 0]])
color = o3d.geometry.Image(o3d.io.read_image('rgb.png'))
```
and it was solved:
<img width="139" alt="ss3" src="https://user-images.githubusercontent.com/6847529/89215116-04ae5000-d603-11ea-8ebe-9f9a9655ff4d.png">
There are artifacts, but I'm pretty sure that it's a separate problem.
So I had assumed you can pass the numpy RGB to o3d.geometry.Image, but that was incorrect?

**Comment by theNded** [comment]
Yes, the current Image interface has some problems and the initialization is less friendly if you do not load from file. We are addressing this issue in the current iteration where we are replacing the internal data to an easy-to-use tensor.

**Comment by zhaozj89** [comment]
@theNded I still came across this problem currently. It would be nice if this issue could be fixed. Thanks.
