### ISSUE TITLE
set_lookat(), set_front(), set_up() usage of VisualControl

### ISSUE THREAD

**Issue by kazu0622** [intel-isl/Open3D#2139]
Hi!
I'm not familier with OpenGL. So, I wasn't able to understand how to use set_lookat(), set_front(), set_up().
Are there any explanation about that on your document?
And I'd like to understand the relationship between the description in this link page as below.
https://learnopengl.com/Getting-started/Camera

I'm grad you could give some comments for me.

Thanks.

**Comment by griegler** [comment]
How is this question related to Open3D?

**Comment by kazu0622** [comment]
@griegler My question is relating to this,
http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html
of set_front(), set_lookat(), set_up(). 
I wasn't able to understand how to use them.
Thanks.

**Comment by griegler** [comment]
I see, @errissa or @prewettg might be able to explain it in more detail.

**Comment by kazu0622** [comment]
@errissa @prewettg 
I thought Open3D's set_front(), set_lookat(), set_up() being compared with OpenGL's.
I'm grad if you could explain how to use these functions.

Thanks.

**Comment by B5paper** [comment]
`set_front()` and `set_up()` can set the pose of the coordinate frame, and `set_lookat()` can set the center point of the window.

Some examples:

```python
import open3d as o3d
coor_frame = o3d.geometry.TriangleMesh.create_coordinate_frame()
visualizer = o3d.visualization.Visualizer()
visualizer.create_window()
visualizer.add_geometry(coor_frame)
view_ctl = visualizer.get_view_control()
view_ctl.set_up((1, 0, 0))  # set the positive direction of the x-axis as the up direction
view_ctl.set_up((0, -1, 0))  # set the negative direction of the y-axis as the up direction
view_ctl.set_front((1, 0, 0))  # set the positive direction of the x-axis toward you
view_ctl.set_lookat((0, 0, 0))  # set the original point as the center point of the window
visualizer.run()
```

In the created window, RED axis represents x-axis, GREEN axis represents y-axis, and BLUE axis represents z-axis. You can change some components of the parameter to observer the corresponding result.

**Comment by kazu0622** [comment]
@B5paper
Thank you for giving me some detailed info. I'll try as you mentioned. 
Thanks a lot.

**Comment by jackjansen** [comment]
I've spent hours trying to understand how to position the view control, until I chanced up this bug report and he description by @B5paper . Could this _please_ be added to the Open3D documentation?

**Comment by errissa** [comment]
@jackjansen We are currently working on major updates to the documentation with respect to visualization as well as new tutorials. The updates will be part of the next release.

**Comment by HaoyouHan** [comment]
I'm still quite confused about these three parameters. Cuz I tried to control the point of view by setting setup and setfront. It works but I didn't understand why is that.

**Comment by HaoyouHan** [comment]
@B5paper

**Comment by ChlaegerIO** [comment]
Thank you I now understand what the functions do. But I want to set the camera position/translation in addition to the viewing direction (set_up, set_front). It should then render an image from that position and not center the camera that the point from set_lookat is centered in the window. Does someone have an idea how to do that?

**Comment by cwreynolds** [comment]
@ChlaegerIO: see the related discussion here [How do I set the 3D coordinates of the virtual camera when rendering point clouds? #7031](https://github.com/isl-org/Open3D/discussions/7031).

A confusing point is that Open3D an older “legacy” visualizer (`open3d.visualization.Visualizer`, as in the code example above) and a newer visualizer (`open3d..visualization.visualizer.O3DVisualizer`). The newer visualizer provides a function `O3DVisualizer::SetupCamera(fov, center, eye, up)` where the arguments are: field(/angle) of view, the look-at point, the look-from point or camera position, and a reference “up” direction which is a hint to control the camera's “roll” around the axis from eye to center.

In #7031, @Zhouwudexiazhou found that the first parameter “fov” is ignored, which seems to be a bug.

As near as I can tell, there is no API to set the eye/camera-position in the older `open3d.visualization.Visualizer`.

I hope that provides some help.

**Comment by Zhouwudexiazhou** [comment]
yes, i haved solved this problem a longtime ago.and first parmeter "fov" is ignored, i don't know how to solved this problem with 03DVisualizer.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "isl-org/Open3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月13日(星期三) 凌晨1:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [isl-org/Open3D] set_lookat(), set_front(), set_up() usage of VisualControl (#2139)





 
@ChlaegerIO: see the related discussion here How do I set the 3D coordinates of the virtual camera when rendering point clouds? #7031.
 
A confusing point is that Open3D an older “legacy” visualizer (open3d.visualization.Visualizer, as in the code example above) and a newer visualizer (open3d..visualization.visualizer.O3DVisualizer). The newer visualizer provides a function O3DVisualizer::SetupCamera(fov, center, eye, up) where the arguments are: field(/angle) of view, the look-at point, the look-from point or camera position, and a reference “up” direction which is a hint to control the camera's “roll” around the axis from eye to center.
 
In #7031, @Zhouwudexiazhou found that the first parameter “fov” is ignored, which seems to be a bug.
 
As near as I can tell, there is no API to set the eye/camera-position in the older open3d.visualization.Visualizer.
 
I hope that provides some help.
