### ISSUE TITLE
Error: open3d_tutorial module error

### ISSUE THREAD

**Issue by mingzengliu** [intel-isl/Open3D#2145]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**

OS: Win 64
Anaconda3(64-bit)
python 3.7.7

Bug: import open3d_tutorial error

**To Reproduce**

1. open : Anaconda prompt(Adaconda3)
2. conda install -c open3d-admin open3d (work well)
3. open: Spyder, then input the following code:
4.   import numpy as np
      import open3d as o3d
      import open3d_tutorial as o3dtut

     print("Testing mesh in open3d ...")
    mesh = o3dtut.get_knot_mesh()
    print(mesh)
    print('Vertices:')
    print(np.asarray(mesh.vertices))
    print('Triangles:')
    print(np.asarray(mesh.triangles))

5.  click: F5(run files)

6. see error:
     ModuleNotFoundError: No module named 'open3d_tutorial'

Problem: Why i can't find the module: open3d_tutorial, 
               or how to solve it? 

**Expected behavior**
How to import open3d_tutorial successfully or what I should do?

**Screenshots**
![image](https://user-images.githubusercontent.com/6506406/89610089-3f86e100-d8ac-11ea-81c3-1465496ffca0.png)

**Environment (please complete the following information):**

- Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)   Windows 10 64-bits
- Python version: (e.g. Python 3.6) Python 3.7
- Open3D version:  0.10.0.1
- Is this remote workstation?: no
- How did you install Open3D?: conda install -c open3d-admin open3d
- Compiler version (if built from source): no

**Additional context**

**Comment by griegler** [comment]
The file you are looking for is her (https://github.com/intel-isl/Open3D/blob/master/examples/python/open3d_tutorial.py). You can copy it to the same location as your script, this should solve your issue. Note that it is only required for the tutorials (visualization), but it is likely that you will not need it in your script.

**Comment by pknigth** [comment]
I am also facing the same error, I am using Jupyter notebook.  Could you anyone help me to solve the error.

**Comment by wolke26** [comment]
> The file you are looking for is her (https://github.com/intel-isl/Open3D/blob/master/examples/python/open3d_tutorial.py). You can copy it to the same location as your script, this should solve your issue. Note that it is only required for the tutorials (visualization), but it is likely that you will not need it in your script.

Sorry this link got removed. Please update it.
