### ISSUE TITLE
Any suggestions on adding color bar and indicators corresponding to point attributes

### ISSUE THREAD

**Issue by hibetterheyj** [intel-isl/Open3D#2147]
**Is your feature request related to a problem? Please describe.**
I'm frustrated about how to add a color bar and indicators corresponding to point attributes (e.g., height or intensity). For better display, in addition to colorization for different points, I also want to further present the corresponding attribute range and color of the specific attribute.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Very sorry for the rough ideas

**Describe alternatives you've considered**
No idea.

**Comment by benjaminum** [comment]
Just to better understand the idea, do you think about something like the color bar in this image?
![image](https://user-images.githubusercontent.com/217089/89726697-bee7f200-da1d-11ea-9aed-26702f68e1c4.png)

**Comment by hibetterheyj** [comment]
Nice. I try to use the `matplotlib.pyplot` to transform the intensity of points in the cloud into different colors as follows:
```python
def intensity2rgb(intensity:np.ndarray, params):

    def adjust_display_range_ratio(data, ratio):
        max_intensity = np.max(data)
        threshold = max_intensity * ratio
        data[data > threshold] = threshold
        return data

    def normalize(data):
        _range = np.max(data) - np.min(data)
        return (data - np.min(data)) / _range

    intensity = adjust_display_range_ratio(intensity, params.ratio)
    scalar = normalize(intensity)
    cmap = plt.get_cmap(params.color)

    rgba_img = cmap(scalar)
    rgb_img = np.delete(rgba_img, 3, 2)
    # print("{} points".format(np.squeeze(rgb_img).size))

    return np.squeeze(rgb_img)

intensity_vector = origin_points[:,3:4]
rgb_color_space = intensity2rgb(intensity_vector, params)
pcd.colors = o3d.utility.Vector3dVector(rgb_color_space)
```

Therefore, I would like to use different attributes to label the color bar and add different texts. 

Any suggestions? Many thanks!!!

**Comment by benjaminum** [comment]
The mapping you do is the way to go with the current visualization.
We are working on a new visualizer with customizable gui elements. Maybe it is possible to implement a color bar with the widgets we have. Do you have an idea @prewettg ?

**Comment by hibetterheyj** [comment]
Many thanks! Looking forward to your amazing work

**Comment by prewettg** [comment]
We do not have a widget for a colorbar such as in the image above. If you are exporting to an image, you could get a colorbar by drawing it onto the image using PIL (Python Imaging Library) or something like that.

**Comment by giswqs** [comment]
Any updates on this? I am also looking for a way to add a colorbar.

**Comment by giswqs** [comment]
This is what the colorbar looks like with [pyvista](https://github.com/pyvista/pyvista). It would be nice if open3d can add colorbar as well. 

![Peek 2022-03-02 14-30](https://user-images.githubusercontent.com/5016453/156435343-81ac8b50-1cb0-4538-80d1-0a9358b4af75.gif)

**Comment by Kin-Zhang** [comment]
I think it should be considered as a new feature[or give the basic example] not closed directly.

**Comment by AlbrechtK** [comment]
There is actually a way to do this. In my example I use matplotlib to generate the colorbar I need and generate a open3d material out of it. This is used on a flat box, showing the colorbar.

```
import matplotlib.pyplot as plt
import numpy as np
import io
import cv2
import open3d as o3d


'''
create the colorbar as desired in matplotlib
'''
rng = [-2, 12]
z_rng = np.arange(rng[1], rng[0], -0.1)
ax = plt.subplot()
im = ax.imshow(np.vstack((z_rng, z_rng, z_rng, z_rng)).T, extent=(0, 1, rng[0], rng[1]))
plt.tick_params(axis='x', which='both', bottom=False, top=False, labelbottom=False)
plt.ylabel('z [m]')

'''
write it to an IO buffer in memory
'''
buf = io.BytesIO()
plt.savefig(buf, format='png', bbox_inches='tight', dpi=100, transparent=True)

'''
read the buffer as a cv2 image (maybe also works directly into open3d?)
'''
buf.seek(0)
array = np.asarray(bytearray(buf.read()), dtype=np.uint8)
im = cv2.imdecode(array, cv2.IMREAD_UNCHANGED)

'''
convert image to a open3d material (texture) and map it on a thin box
'''
im_o3d = o3d.geometry.Image(cv2.cvtColor(im, cv2.COLOR_RGBA2BGRA))
box = o3d.geometry.TriangleMesh.create_box(im.shape[1]/10, im.shape[0]/10, 0.1, create_uv_map=True, map_texture_to_each_face=True)
box.compute_triangle_normals()

mat = o3d.visualization.rendering.MaterialRecord()
mat.shader = 'defaultLitTransparency' # 'defaultLit' would show background of box white
# mat.base_color = [1,1,1, 0.75]
mat.albedo_img = im_o3d


'''
create open3d scene to show the result
'''
o3d.visualization.gui.Application.instance.initialize()
w = o3d.visualization.O3DVisualizer('title', 1024, 768)
w.add_geometry('colorbar', box, mat)
w.reset_camera_to_default()
o3d.visualization.gui.Application.instance.add_window(w)
o3d.visualization.gui.Application.instance.run()
```
