### ISSUE TITLE
Difference in depth image captured from open3d azure viewer and k4viewer

### ISSUE THREAD

**Issue by zainmehdi** [intel-isl/Open3D#2160]
Hi,
I am trying to capture depth images using azure kinect recorder script. It seems like the depth range and quality of the image captured via open3d is different from what I get when I view it from k4viewer. Is there any parameter controlling this difference. Can I get the same range with open3d as well ? I am attaching both the pics for comparison. 
Thanks

Much more range can be seen in this pic
![AzureCapture_k4viewer](https://user-images.githubusercontent.com/21212125/89859256-8f7ee400-dbdb-11ea-85cd-45fc67a59e71.png)

Seems like range values have been clipped
![AzureCapture_open3D](https://user-images.githubusercontent.com/21212125/89859390-dc62ba80-dbdb-11ea-90df-47d307fafaa6.png)

**Comment by scimad** [comment]
> Is there any parameter controlling this difference?

Assuming that your are using python script, please modify the `examples/python/ReconstructionSystem/sensors/default_config.json` as per your need and pass it on the `--config` parameter in command line.

Should solve.

**Comment by zainmehdi** [comment]
@scimad thanks I will try.

**Comment by theNded** [comment]
We need consistent RGBD pairs for projection and unprojection. Wide angle depth images won't fit these models and there will be no trivial ways to process them without this explicit conversion/clipping. 
You may have to use official Kinect package to access the raw data...
