### ISSUE TITLE
Tutorial ReconstructionSystem, running very slow.

### ISSUE THREAD

**Issue by bumbastic** [intel-isl/Open3D#2162]
Hi,

I installed open3d master on a laptop, 7gen. I7, 16GB RAM, Ubuntu 18.04.
When I run the ReconstructionSystem tutorial with the 016 dataset as input, it takes hours to complete. Is this normal?.

**Comment by yxlao** [comment]
@theNded could you help with this?

**Comment by bumbastic** [comment]
A rebuild with Cuda support helped a lot. Still I see the first part making of fragments run significantly slower than the rest of the pipeline.

**Comment by bumbastic** [comment]
I ran with parallel processing. I saw that the first part with pair vice rgbd registration, ran slower than the rest of the pipeline. I don't think there is CUDA support for that function yet.
