### ISSUE TITLE
Identifying selected point cloud neighborhood in a headlesss visualization

### ISSUE THREAD

**Issue by gkalman1** [intel-isl/Open3D#2163]
Thank you for the beautiful software that I have only recently started exploring.

I have come across an issue that I have not been able to resolve. My usage is in a headless environment, for which I recompiled Open3D per recommended instructions. 

I am trying to identify a selected point/points/neighborhood from a 2D coordinate of the produced headless image. 

Ideally it would be something that allows to vs.pick_point(image_x,image_y) and then use vs.get_picked_points() as is. However, I have not found that functionality outside of the non-headless environment where the user simply "shift + left click" on the point.

Alternatively, and this can be a workaround for me, if there is an easy to perform transformation from point cloud's xyz[n x 3] matrix to image_xy[n x 2] (or image_xyd[n x 3] with d for depth) then I could just look for the click neighborhood in the clicked point's neighborhood of projected to image point cloud. But, I am too much of an Open3D newbie to figure out how to do get that transformation from (vis.get_view_control()).

Again, thank you for any help or suggestions that I may not have considered!!!

-Gary

**Comment by prewettg** [comment]
It looks like ViewControl doesn't export the matrix-getting functions to python, unfortunately. However, you can call `convert_to_pinhole_camera()` and then `intrinsic_matrix`, `get_focal_length()`, `get_principle_point()`, and `get_skew()` to construct the matrix you need.
