### ISSUE TITLE
Using known image camera poses, for faster reconstruction.

### ISSUE THREAD

**Issue by bumbastic** [intel-isl/Open3D#2168]
When I run the ReconstructionSystem tutorial scripts on my own images. it takes about 10-30 minutes to make a nice reconstruction.
A lot of work seems to go in to matching all images against each other. 
I already know the camera poses for my images, within a tolerance of +/-30mm and rotation within +/- 1deg. The images is already in a sequence where the camera moves along a straight line.   

If possible, I would like to significantly reduce the reconstruction time, by using the above described information as input.

Nice to have too:
I would like to constrain the matching to only optimize the images poses within given tolerances.
Option to throw away images that can't be matched within the given pose tolerances.

Is there already a way to do this?

**Comment by greatwallet** [comment]
I think maybe most of the time the "Reconstruction System" is doing is RGB-D/point-cloud pairwise-registration. Why don't you perform [`multiway registration`](http://www.open3d.org/docs/release/tutorial/Advanced/multiway_registration.html#Pose-graph) without the part of  `pairwise-registration` part, and loading your camera poses as initial input of `Pose Graph Optimization`?

**Comment by bumbastic** [comment]
Thank you for the tip. I will try it out.

**Comment by yanivx4x** [comment]
Hey @bumbastic  ,
Did you manage to do it? I am interested in the same solution.

**Comment by Zumbalamambo** [comment]
@bumbastic could you please share the tutorial code on rgb based pointcloud construction?

**Comment by bumbastic** [comment]
I don't have a tutorial for this. I think that the open3d python ReconstructionSystem example is great for converting rgbd images into pointclouds or meshes.

**Comment by Zumbalamambo** [comment]
How about mere rgb images? Is it possible to create pointcloud from rgb images?

**Comment by bumbastic** [comment]
Hmm.. Do you mean something like the phone app Display.Land? I don't work with something like this. I work with depth images not rgb.
