### ISSUE TITLE
[Suggestion] Would you like  cmake to use FindCUDAToolkit script?

### ISSUE THREAD

**Issue by tomofu74** [intel-isl/Open3D#2172]
**Is your feature request related to a problem? Please describe.**
I want to build Open3D with cuda on NVIDIA Jetson nano. But latest source from github with "BUILD_CUDA_MODULES" checked are configured "CUDA Compiler not found", in spite of my environment included nvcc working well.

**Describe the solution you'd like**
How about newer Cmake's script and set variable CUDAToolkit_ROOT=/usr/local/cuda
https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#module:FindCUDAToolkit

**Describe alternatives you've considered**
By the way, I try cmake with "-DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc", but it is not working.

**Additional context**
NVIDIA Jetson has CUDA and its compiler, but they not have "nvidia-smi" command.
https://forums.developer.nvidia.com/t/gpu-usage-info-nvidia-smi-is-not-there/76155

**Comment by yxlao** [comment]
What is your CMake version?

**Comment by tomofu74** [comment]
cmake Ver.3.18.1
![Screenshot from 2020-08-15 14-04-22](https://user-images.githubusercontent.com/19162094/90305859-0250cd80-df02-11ea-971d-554d6bca28b3.png)

BUILD_CUDA_MODULE -> ON

But Configuration Summary says,  CUDA Support --- OFF

**Comment by tomofu74** [comment]
![Open3d](https://user-images.githubusercontent.com/19162094/90305882-64a9ce00-df02-11ea-9af4-b887a14f1a62.png)
cmake Ver.3.18.1

BUILD_CUDA_MODULE -> ON

Configuration Summary says, CUDA Support ... OFF

**Comment by yxlao** [comment]
ARM64 is now supported. See the build guide at https://github.com/intel-isl/Open3D/blob/master/docs/arm.rst. If you encounter any problem, please create a new issue.
