### ISSUE TITLE
how to add L515 realsense support for open3d?

### ISSUE THREAD

**Issue by AndreV84** [intel-isl/Open3D#2181]
there is a solution for d400 around;
how to modify it to support l515?

**Comment by theNded** [comment]
I currently don't have this sensor on hand... Will take a look once I get the device.

**Comment by AndreV84** [comment]
@theNded if yo have d435i, cold you supply intel D435i intrinsics _either from CUDA config file or Captured dateset intrinsic file_
the file /camera_intrinsic.json
please?

**Comment by theNded** [comment]
Please check my answer in #2235

**Comment by AndreV84** [comment]
@theNded 
Could you help troubleshooting the issue below, please?
`./RunSystem /home/user/o3d/git_src/Open3D/theNded/Open3D/examples/Cuda/ReconstructionSystem/config/intel/test.json
..
[Open3D INFO] Active subvolumes in volume: 541
[Open3D INFO] Writing 697 subvolumes.

CUDA error at /home/user/o3d/git_src/Open3D/theNded/Open3D/src/Cuda/Integration/ScalableMeshVolumeCudaKernel.cuh:117 code=701(cudaErrorLaunchOutOfResources) "cudaGetLastError()"`

**Comment by germanros1987** [comment]
@ssheorey is working on this feature.

**Comment by AndreV84** [comment]
thank you for the update

**Comment by AndreV84** [comment]
@ssheorey 
has l515 support been implemented?

**Comment by ssheorey** [comment]
Yes, there is a new API using RealSense SDK v2.x. See this [tutorial](http://www.open3d.org/docs/latest/tutorial/sensor/realsense.html) 
[May be a few hours till the documentation is updated.]

**Comment by eltonhcchan** [comment]
Documentation mentioned Open3D (v0.12+) , where to get v0.12? 
Try to download Development version (pip) for Windows 10 using following command
pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.11.2+743f699-cp36-cp36m-win_amd64.whl

However, corresponding whl for Windows is not found.

**Comment by ssheorey** [comment]
Please try this wheel for now: 
https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.11.2-cp36-cp36m-win_amd64.whl
v0.12 will be released shortly.

**Comment by rancheng** [comment]
I use the following setting to align the depth and color before profile start, and it works for both `Realsense D455` and `Realsense L515`:

```python
    if args.record_imgs or args.record_rosbag:
        # note: using 640 x 480 depth resolution produces smooth depth boundaries
        #       using rs.format.bgr8 for color image format for OpenCV based image visualization
        config = rs.config()
        config.enable_stream(rs.stream.depth, 1024, 768, rs.format.z16, 30)
        config.enable_stream(rs.stream.color, 1280, 720, rs.format.bgr8, 30)

        # Align objects
        align_to = rs.stream.color
        align = rs.align(align_to)

        if args.record_rosbag:
            config.enable_record_to_file(path_bag)
    if args.playback_rosbag:
        config.enable_device_from_file(path_bag, repeat_playback=True)

    # Start streaming
    profile = pipeline.start(config)
```
