### ISSUE TITLE
Programmatically texturing a mesh

### ISSUE THREAD

**Issue by t-fi** [intel-isl/Open3D#2193]
I'm new to Open3D, please pardon my ignorance.

From the tutorials I see that one can easily load `.ply` files, including texture and render them. Now I am wondering, is it also possible to texture a mesh programmatically from Open3D? The mesh tutorial only shows [how to paint a mesh uniformly](http://www.open3d.org/docs/release/tutorial/Basic/mesh.html#Paint-mesh).

I know the basics about uv mapping and such, but have no idea how to do that with Open3D. I imagine texturing a mesh with some random noise texture (via a numpy array) for now, the exact uv mapping does not matter. Having a starting point would be great, could you kindly point me to some resources? I am willing to expand the tutorial once I figure things out :)

**Comment by griegler** [comment]
@t-fi if you want a result as shown in #1385, then this should be already possible with the Python API (creating textured meshes per camera; note that the uv mapping for this is straightforward). Let me know if you have something different in mind.

**Comment by t-fi** [comment]
Ah, I see. I explored the Python API and think I found some relevant functions. However I cannot get this to work:

``` python
import numpy as np
import open3d as o3d

# create an icosahedron
ico = o3d.geometry.TriangleMesh.create_icosahedron()

# create and assign a 100x100 float32 texture
texture = np.random.uniform(0, 1, (100, 100)).astype(np.float32)
ico.textures = [o3d.geometry.Image(texture)]

# create and assign some trivial uv mapping
triangle_uv = np.array([[0., 0.],[0.,1.],[1.,0]])
triangle_uvs = np.vstack([triangle_uv]*20) # ico has 20 faces
ico.triangle_uvs = o3d.utility.Vector2dVector(triangle_uvs)

# render the result
o3d.visualization.draw_geometries([ico])
```

But this segfaults immediately. I also tried a 3 channel textures and different UV mapping schemes. Do you see any obvious errors, or are those functions meant to be used completely differently?

**Comment by griegler** [comment]
@errissa @prewettg can one of you have a look at this please

**Comment by t-fi** [comment]
Thanks for looking into this! I dug a little more and found out that #2089 is about the same thing. That issue claims that something broke from `0.9` to `0.10` with allowing multiple textures per object. Downgrading to `0.9` and adjusting the above method to the old API does not work since #1623 was fixed after the `0.9` release. So this is broken in both the new and old version, and there is no way to do this properly at the moment.

**Comment by TobiFisch** [comment]
@griegler Is the approach I posted earlier valid? If so, I would consider the behavior a bug and not a feature request, like the issue label suggests.

**Comment by TobiFisch** [comment]
For anyone stumbling upon the same issue, simply storing and loading the mesh like this works in `0.10.0.0`:
``` python
import open3d as o3d
import numpy as np

# create an icosahedron
ico = o3d.geometry.TriangleMesh.create_icosahedron()

# create and assign a 100x100 float32 texture
texture = np.random.uniform(0, 1, (100, 100,3)).astype(np.float32)
ico.textures = [o3d.geometry.Image(texture)]

# create and assign some trivial uv mapping
triangle_uv = np.array([[0, 0], [0, 1], [1, 0]])
triangle_uvs = np.vstack([triangle_uv] * 20)  # ico has 20 faces
ico.triangle_uvs = o3d.utility.Vector2dVector(triangle_uvs)

# Store and load fixes the mesh :)
o3d.io.write_triangle_mesh("ico.obj", ico)
ico = o3d.io.read_triangle_mesh("ico.obj")

o3d.visualization.draw_geometries([ico])
```
