### ISSUE TITLE
Using Known Camera Poses Help

### ISSUE THREAD

**Issue by yanivx4x** [intel-isl/Open3D#2218]
Hello everyone,
I am trying to use known camera poses in the reconstruction system as opposed to the RGBD pairing, to improve speed and accuracy.

In order to do it, I build my own pose graph from my known position and rotation (Vector3 and Quaternion ) of each RGBD.
Here is the code I have written:

```
def make_posegraph_from_known_camera_poses(path_dataset, sid, eid,
                                 fragment_id, n_fragments,
                                 config):
    o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Error)
    pose_graph = o3d.registration.PoseGraph()
    for s in range(sid, eid):
        pose_graph.nodes.append(
            o3d.registration.PoseGraphNode(get_matrix_by_proj_number(s,config)))

    o3d.io.write_pose_graph(
        join(path_dataset, config["template_fragment_posegraph"] % fragment_id),
        pose_graph)
```

and the function to create the pose matrix:

```
def get_matrix_by_proj_number(id,config):

    # set the folders for positions and rotations
    positions_folder = join(config["path_dataset"], config["folder_positions"])
    rotations_folder = join(config["path_dataset"], config["folder_rotations"])
    
    # generate file names
    position_file_name = positions_folder  + str(id) + ".txt"
    rotation_file_name = rotations_folder  + str(id) + ".txt"
    
    # get the position and rotation for RGBD
    position = get_position_from_file(position_file_name)
    rotation = get_rotation_from_file(rotation_file_name)
    
    # create transformation mat
    mat = glm.identity(glm.mat4)
    mat = glm.translate(mat, position)
    angle = 2 * np.arccos(rotation.w)
    x = rotation.x / np.sqrt(1 - rotation.w * rotation.w)
    y = rotation.y / np.sqrt(1 - rotation.w * rotation.w)
    z = rotation.z / np.sqrt(1 - rotation.w * rotation.w)
    mat = glm.rotate(mat,  angle, [x,  y, z])
    mat = glm.transpose(mat)

    # convert to numpy
    x = np.array([mat[0],
                  mat[1],
                  mat[2],
                  mat[3]])
    # return inverse
    mat_inv = np.linalg.inv(x)

    # coords system transfer
    mat_inv[2,0] = mat_inv[2,0] * -1.0
    mat_inv[2, 1] = mat_inv[2, 1] * -1.0
    mat_inv[2, 2] = mat_inv[2, 2] * -1.0
    mat_inv[2, 3] = mat_inv[2, 3] * -1.0
    
    return mat_inv
```

I have to apply some transformation to the final matrix as the position and rotation are originally from Unity in which the Y direction is opposite to Open3D to the best of my knowledge.

I have checked and the **mat_inv** looks exactly like the view matrices I am using in Unity (except the opposite signed second matrix column).

Unfortunately, the final result is distorted:
![1](https://user-images.githubusercontent.com/18504020/90980888-ac65d080-e566-11ea-9f68-83d93c50ff74.jpg)

In addition, strangely enough, as I was playing around with the matrix creation I have found a manner of creation that almost makes it right but makes no sense from a logical point of view to me.
When I apply the rotation matrix as follows:
`mat = glm.rotate(mat,  angle, [x, -1.0 * y, z])`
That is the result:
![2](https://user-images.githubusercontent.com/18504020/90980991-1f6f4700-e567-11ea-93a0-077848c7556e.jpg)

Any ideas what am I missing? I read all the cpp source code of the TSDFVolume integrate method and everything seems like it should work.

Thanks on in advance, Yaniv.

**Comment by theNded** [comment]
Good catch! Unity uses a left-hand coordinate system, while open3d uses a right-hand system that is conventional in the computer vision community. See https://github.com/KhronosGroup/UnityGLTF/issues/257 as a reference.

To convert between these coordinate systems, you need to revert y axis. That's what you have done!
