### ISSUE TITLE
How to use view control in non-blocking visualization?

### ISSUE THREAD

**Issue by Dzhange** [intel-isl/Open3D#2219]
I'm trying to get several screenshots for some objects, however I found that I couldn't use view control in the rendering
Here is my code.
```
import glob
import open3d as o3d

# path = "./24/frame_001_recon.off"
# path = "./24/frame_000_gt.off"
paths = glob.glob("./24/*recon.off")
vis = o3d.visualization.Visualizer()
vis.create_window()
# vis.add_geometry(place_holder)
ctr = vis.get_view_control()
ctr.set_zoom(4)

for i,path in enumerate(paths):
    
    mesh = o3d.io.read_triangle_mesh(paths[i])
    mesh.compute_vertex_normals()
    vis.add_geometry(mesh)
    # vis.update_geometry(mesh)
    vis.poll_events()
    vis.update_renderer()    
    vis.capture_screen_image("temp_%04d.jpg" % i)
    vis.remove_geometry(mesh)    
vis.destroy_window()
```
Seems like the `zoom` operation doesn't work, did I used it wrong? Or does open3d doesn't support this operation?

**Comment by griegler** [comment]
I am not 100% certain, but I think that `add_geometry` updates the view control. Can you try to use `set_zoom` after your `add_geometry` call in the loop?

**Comment by Dzhange** [comment]
Thanks! This really solved my problem. 
BTW, I may suggest that the related doc should be made more clear.
