### ISSUE TITLE
Is there any way to capture vector image (SVG or PDF) from point cloud?

### ISSUE THREAD

**Issue by Haodong-Alex-Yao** [intel-isl/Open3D#2231]

**Comment by griegler** [comment]
No. What exactly do you have in mind?

**Comment by Haodong-Alex-Yao** [comment]
I used o3d.geometry.LineSet to draw 3D lines based on their end points. It works perfectly fine. But I still want to get the 2D projection of these lines from a certain angle as a vector image. I haven't found a way of doing it.

Thanks!

**Comment by griegler** [comment]
Sorry, but this is currently not possible, nor do we have currently plans to support this.
