### ISSUE TITLE
How to change obj file color in Visualizer

### ISSUE THREAD

**Issue by jay-thakur** [intel-isl/Open3D#2233]
Hi,

I am novice to `open3d`. I have below code to load obj, save viewpoint & image - 

```
    vis = o3d.visualization.Visualizer()
    vis.create_window(width = 264, height = 264, left=800, top=200)
    vis.add_geometry(pcd)
    vis.run()  # user changes the view and press "q" to terminate
    param = vis.get_view_control().convert_to_pinhole_camera_parameters()

    # save image
    vis.capture_screen_image(image_name)

    o3d.io.write_pinhole_camera_parameters(viewpoints_path_name, param)
```
I can see in visualizer & saving image also like this.
![image](https://user-images.githubusercontent.com/2772085/91275806-44013400-e79e-11ea-92ec-990b2b8c0545.png)

But i want my obj color like this -

![image](https://user-images.githubusercontent.com/2772085/91275909-65fab680-e79e-11ea-9a54-8a731a29a387.png)

Could anyone please guide how to do ? 

Do i need to change camera angle ? if yes how can i change camera angle ? 
or 
How can i change color in visualiser ?

**please guide/help**

Thanks,
Jay

**Comment by griegler** [comment]
You could try to turn the light of by getting the render options (http://www.open3d.org/docs/release/python_api/open3d.visualization.Visualizer.html#open3d.visualization.Visualizer.get_render_option) and set the property to false (http://www.open3d.org/docs/release/python_api/open3d.visualization.RenderOption.html#open3d.visualization.RenderOption.light_on), or zoom away from the object.

We are also working on a new visualization framework that allows changing the light intensity, which is not possible with the current one.

**Comment by jay-thakur** [comment]
Hi @griegler,

I tried below code - 

```
        opt = vis.get_render_option()
        opt.light_on = False 
```

after this i dont see any image in visualiser.
![image](https://user-images.githubusercontent.com/2772085/91473328-5bcbdb80-e8b6-11ea-953b-177c251f4167.png)

if we can just change image color to gray that would also work.

Please guide.

**Comment by prewettg** [comment]
The visualizer that you are using is limited and we are in the process of replacing the visualization with a much more full-featured renderer, as well as a UI toolkit.

If manually setting the lighting would work for your case, consider using the new Open3D viewer app, which allows you to set a wide variety of lighting settings. From your screenshot I suspect that you are using Windows; the current release only has builds for Linux and macOS. If either of those would work for you, you can try out the viewer with `<open3d_install_path>/bin/Open3D` (Linux) or `open <open3d_install_path>/Open3D.app` (macOS). The current master branch now builds on Windows, so if you are willing to live on the edge, you can build a Windows version.

If you need programmatic settings, most of what the C++ app reference above uses is now available in Python in the current master branch. Please see `examples/python/GUI/vis-gui.py` for a script that implements most of the features of the app in Python.

**Comment by griegler** [comment]
@jay-thakur Did you try http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html?highlight=paint_uniform_color#open3d.geometry.TriangleMesh.paint_uniform_color

**Comment by jay-thakur** [comment]
@griegler .  this worked.

```
    pcd.paint_uniform_color([0.5, 0.5, 0.5])
```

**Comment by jay-thakur** [comment]
@prewettg Thank you so much for help.
