### ISSUE TITLE
i435 json intrinsics request

### ISSUE THREAD

**Issue by AndreV84** [intel-isl/Open3D#2235]
*[Open3D WARNING] Read JSON failed: unable to open file:  /Open3D-for-Jetson/examples/Python/ReconstructionSystem/dataset/realsense/camera_intrinsic.json
could you supply the file for the camera, please?

**Comment by theNded** [comment]
It has various configurations and depends on your setup. 
The json file should have been recorded if you use our recorder: https://github.com/intel-isl/Open3D/blob/master/examples/python/ReconstructionSystem/sensors/realsense_recorder.py#L166

**Comment by AndreV84** [comment]
```
`./RunSystem /home/user/o3d/git_src/Open3D/theNded/Open3D/examples/Cuda/ReconstructionSystem/config/intel/test.json
..
[Open3D INFO] Active subvolumes in volume: 541
[Open3D INFO] Writing 697 subvolumes.

CUDA error at /home/user/o3d/git_src/Open3D/theNded/Open3D/src/Cuda/Integration/ScalableMeshVolumeCudaKernel.cuh:117 code=701(cudaErrorLaunchOutOfResources) "cudaGetLastError()"`
```
with i435 we got into this issue

**Comment by AndreV84** [comment]
![c1a69b293ae87be1cbe23592cdda2fa6c75fb66e](https://user-images.githubusercontent.com/16374873/94143619-9eee7f80-fe5f-11ea-839c-105e75be4663.png)
