### ISSUE TITLE
module 'open3d.open3d.geometry' has no attribute 'keypoint'

### ISSUE THREAD

**Issue by ZhengdiYu** [intel-isl/Open3D#2251]
Hi, I am using Version: **_0.10.0.1_**

```
pcd = open3d.geometry.PointCloud()
pcd.points = open3d.utility.Vector3dVector(ptcld)
kpt = open3d.compute_iss_keypoints(pcd)

>>>AttributeError: module 'open3d.open3d.geometry' has no attribute 'keypoint'
```

which version should I install for computing iss keypoints?

**Comment by griegler** [comment]
Did you install via conda, or pip? `compute_iss_keypoints` is only in master for the moment and will be in the next release.

**Comment by ZhengdiYu** [comment]
@griegler  Thank you for reply. I installed with pip

**Comment by griegler** [comment]
Then you can use the feature after building from source yourself. Note that the next release should be available within the next 3 weeks or so.

**Comment by ZhengdiYu** [comment]
@griegler OK, thank you, I will try to compile from source for the time being.

**Comment by agporto** [comment]
@griegler Is the next release still planned in the short term?

**Comment by griegler** [comment]
Yes it is. Unfortunately, there are a few delays. Maybe @germanros1987 can give a more precise update.
