### ISSUE TITLE
3D reconstruction from RGB-d data

### ISSUE THREAD

**Issue by upasana27** [intel-isl/Open3D#2252]
I am using the Open-LORIS scene dataset (https://lifelong-robotic-vision.github.io/dataset/scene.html) and would like to build a 3D map of the world from the Realsense D435i camera data. The following data is available from the dataset:- 
D435i | color | 30 | 848x480 | H:69 V:42 D:77
D435i | depth | 30 | 848x480 | H:91 V:65 D:100
D435i | aligned deptha | 30 | 848x480 | H:69 V:42 D:77
D435i | accel | 250 |   | -
D435i | gyro | 400 |   | -
T265 | fisheye1 | 30 | 848x800 | D:163
T265 | fisheye2 | 30 | 848x800 | D:163
T265 | accel | 62.5 |   | -
T265 | gyro | 200 |   | -
base | odom | 20b |   | -
LiDAR | laser scan | 40 | 1080 | H:270c
Using the librealsense SDK code for generating point cloud (https://github.com/IntelRealSense/librealsense/tree/master/examples/pointcloud), I get the XYZRGB point cloud. I can also use the pcl wrappers (https://github.com/IntelRealSense/librealsense/tree/master/wrappers/pcl) to get the point clouds in pcl format. Next step would be to generate a mesh from the point clouds. Any suggestions and possible solutions will be greatly appreciated.
Thank you!

**Comment by theNded** [comment]
We take RGB-D images as input to our reconstruction system. Please refer to http://www.open3d.org/docs/release/tutorial/ReconstructionSystem/capture_your_own_dataset.html. 
You would need to 
- re-organize your dataset as depicted in the link
- convert the intrinsic matrix from the dataset to the format as
```json
{
	"width" : 640,
	"height" : 480,
	"intrinsic_matrix" :
	[
		600.0,
		0,
		0,
		0,
		600.0,
		0,
		320.0,
		240.0,
		1
	]
}
```

**Comment by upasana27** [comment]
Hi @theNded, thank you for the help. I followed the steps, however the ply I am getting does not seem like a good visualisation.  Can you please check if everything is in the right format?
![Screenshot from 2020-09-02 16-42-18](https://user-images.githubusercontent.com/31506763/91974642-ac6e8900-ed3b-11ea-8a59-0905d165aa5a.png)
![Screenshot from 2020-09-02 16-42-29](https://user-images.githubusercontent.com/31506763/91974646-aed0e300-ed3b-11ea-89ec-4e1ef5f98834.png)
![Screenshot from 2020-09-02 16-42-37](https://user-images.githubusercontent.com/31506763/91974674-b98b7800-ed3b-11ea-832e-8c02b59094aa.png)
![Screenshot from 2020-09-02 16-42-51](https://user-images.githubusercontent.com/31506763/91974683-bbedd200-ed3b-11ea-8e3e-f4ded06a049d.png)
![Screenshot from 2020-09-02 16-43-02](https://user-images.githubusercontent.com/31506763/91974689-be502c00-ed3b-11ea-9406-08db1b5136f6.png)
![Screenshot from 2020-09-02 16-51-36](https://user-images.githubusercontent.com/31506763/91975195-a5944600-ed3c-11ea-9143-240befaaaacd.png)

**Comment by upasana27** [comment]
Hi @theNded, thanks for the help.

**Comment by robot-mh** [comment]
how is the result？ @upasana27
