### ISSUE TITLE
Can I keep the current view angle after loading next point cloud?

### ISSUE THREAD

**Issue by liuchangji** [intel-isl/Open3D#2264]
in #1961 Visualize Point Cloud Sequentially,
```
import open3d
import glob

def vis_dict(dict):
    pcds=sorted(glob.glob('{}/*.pcd'.format(dict)))
    print(pcds)
    vis=open3d.visualization.VisualizerWithKeyCallback()
    vis.create_window()
    idx=0
    pcd=open3d.io.read_point_cloud(pcds[idx])
    vis.add_geometry(pcd)
    #vis.update_renderer()
        
    def right_click(vis):
        nonlocal idx
        print('right_click')
        idx=idx+1
        vis.clear_geometries()
        pcd=open3d.io.read_point_cloud(pcds[idx])
        vis.add_geometry(pcd)
        
    def exit_key(vis):
        vis.destroy_window()
        
    vis.register_key_callback(262,right_click)
    vis.register_key_callback(32,exit_key)
    vis.poll_events()
    vis.run()
    #vis.destroy_window()    
        
if __name__=='__main__':
    vis_dict('/path/to/dict')
```
The script provided by @g2ragrawal works fine. I can skip forwards and backwards through the point cloud data and change the view point angle with the mouse. Thanks again.

But when I skip forwards through the point cloud data,the view point angle will reset to the very beginning angle.Can I keep the current angle after I skip a point cloud?

**Comment by griegler** [comment]
`add_geometries` resets the view. You could try to use [this function](http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html#open3d.visualization.ViewControl.convert_to_pinhole_camera_parameters) to save the parameters prior to adding and then restore the view with [this function](http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html#open3d.visualization.ViewControl.convert_from_pinhole_camera_parameters).

**Comment by liuchangji** [comment]
> `add_geometries` resets the view. You could try to use [this function](http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html#open3d.visualization.ViewControl.convert_to_pinhole_camera_parameters) to save the parameters prior to adding and then restore the view with [this function](http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html#open3d.visualization.ViewControl.convert_from_pinhole_camera_parameters).

Thanks a lot!

**Comment by zheyuanWang** [comment]
> `add_geometries` resets the view. You could try to use [this function](http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html#open3d.visualization.ViewControl.convert_to_pinhole_camera_parameters) to save the parameters prior to adding and then restore the view with [this function](http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html#open3d.visualization.ViewControl.convert_from_pinhole_camera_parameters).


Thanks for [griegler](https://github.com/griegler)'s reply, a short example may be as follows:
```
        self.o3d_visualizer = o3d.visualization.VisualizerWithKeyCallback()
        self.o3d_visualizer.clear_geometries()

        ctr  = self.o3d_visualizer.get_view_control()
        view_param =ctr.convert_to_pinhole_camera_parameters()

        # update points
        pcd = geometry.PointCloud()
        xyz = np.asarray(self.points[0:5000, :3])
        pcd.points = o3d.utility.Vector3dVector(xyz)
        self.o3d_visualizer.add_geometry(pcd)

        ctr.convert_from_pinhole_camera_parameters(view_param)

        self.o3d_visualizer.update_renderer()
        self.o3d_visualizer.poll_events()
        self.o3d_visualizer.run()

```
