### ISSUE TITLE
Capture image without running the visualizer.

### ISSUE THREAD

**Issue by EthanZhangYi** [intel-isl/Open3D#2271]
Currently I use the code below to generate the image rendered.
```python
visualizer.run()
visualizer.capture_screen_image(img_name, do_render=False)
```
However
(1) this can not work on a remote server since GUI is not available.
(2) I need to close the window manually each time, which is not suitable for visualization of a large batch of data.

Is there a better solution?

**Comment by griegler** [comment]
For headless rendering (1) look [here](http://www.open3d.org/docs/release/tutorial/Advanced/headless_rendering.html).
You can also close the window (2) from [Python](http://www.open3d.org/docs/release/python_api/open3d.visualization.Visualizer.html#open3d.visualization.Visualizer.close).

**Comment by EthanZhangYi** [comment]
@griegler 
Thanks for your reply.
For solution(1) I will try to build `open3d` for headless rendering.
For solution(2), I run the codes below, but I stiil need to close the window manually each time. It seems that `visualizer.run()` will block the current thread until the window is closed manually. Do you have any advice on it?
```python
visualizer.run()
visualizer.capture_screen_image(out_file, do_render=False)
visualizer.destroy_window()
```
or
```python
visualizer.run()
visualizer.capture_screen_image(out_file, do_render=False)
visualizer.close()
```

**Comment by griegler** [comment]
I see, you can solve (2) by having a look [here](http://www.open3d.org/docs/release/tutorial/Advanced/non_blocking_visualization.html)

**Comment by EthanZhangYi** [comment]
@griegler 
Thanks~
The `Non-blocking visualization` solved my problem.
