### ISSUE TITLE
Unable to convert PCD to PLY

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#2275]
I'm using the following code to convert PCD file to PLY.

```
import open3d as o3d


print("Testing IO for point cloud ...")
pcd = o3d.io.read_point_cloud("pointcloud.pcd")
print(pcd)
o3d.io.write_point_cloud("copy_of_fragment.ply", pcd)
```

Unfortunately the converted Pointcloud looks messy in blender. Is this the proper way of doing it?

**Comment by griegler** [comment]
This is the correct way. Can you please provide the `ply` file (or a similar one) that produces the problem. It would also be good to show screenshots of loading the `ply` and the `pcd` in Blender.
