### ISSUE TITLE
Removing the points that are over certain y value

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#2291]
Is it possible to remove the points that are over certain `y-value` using Open3D? I tried to check the python documentation but I couldn't be able to find one.

**Comment by griegler** [comment]
For a pointcloud you could use something like

```python
points = np.asarray(pcd.points)
mask = points[:,1] > y_threshold
pcd.points = o3d.utility.Vector3dVector(points[mask]) # normals and colors are unchanged

# alternative
pcd = pcd.select_by_index(np.where(points[:,1] > y_theshold)[0])
```

**Comment by Zumbalamambo** [comment]
@griegler I tried the above code. When I draw_geometries, the resultant point cloud still remains the same. :(

 I have images with known 6DOF position.. is it also possible to add RGB data to the point cloud?

**Comment by griegler** [comment]
Then I guess you do not have any points with a y-coordinate greater than the given threshold.
Regarding your second question you can use [`create_from_rgbd_image`](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.create_from_rgbd_image).

**Comment by Zumbalamambo** [comment]
@griegler I will try that thank you!...

I have used `pick_point()` to find out the threshold. It's on the z-axis. This is my code,


```
pcd = o3d.io.read_point_cloud("pointcloud.pcd")
z_threshold =4
points = np.asarray(pcd.points)
mask = points[:,2] > z_threshold
pcd.points = o3d.utility.Vector3dVector(points[mask]) # normals and colors are unchanged

# alternative
pcd = pcd.select_by_index(np.where(points[:,2] > z_threshold)[0])


o3d.visualization.draw_geometries([pcd])
```

am I doing it properly?

**Comment by griegler** [comment]
Here is a minimal working example (if it is not working then most likely the `threshold` is not what you think):

```python
import numpy as np
import open3d as o3d

# create test data
points = np.random.uniform(-1, 1, size=(100, 3))
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)

# threshold data
points = np.asarray(pcd.points)
pcd_sel = pcd.select_by_index(np.where(points[:, 2] > 0)[0])

# visualize different point clouds
o3d.visualization.draw_geometries([pcd])
o3d.visualization.draw_geometries([pcd_sel])
```

**Comment by Zumbalamambo** [comment]
@griegler it works! thanks :)

**Comment by JimXu1989** [comment]
> For a pointcloud you could use something like
> 
> ```python
> points = np.asarray(pcd.points)
> mask = points[:,1] > y_threshold
> pcd.points = o3d.utility.Vector3dVector(points[mask]) # normals and colors are unchanged
> 
> # alternative
> pcd = pcd.select_by_index(np.where(points[:,1] > y_theshold)[0])
> ```

Hi , thank you for the sharing,
While when I use the method, the color information disapeared

**Comment by PhillRob** [comment]
Thanks, this works great. I do have a plane object generated by `pcd.segment_plane`and what to select all points above the plane. How can I achieve this?
