### ISSUE TITLE
Can't set z-axis as the up-axis with the view control.

### ISSUE THREAD

**Issue by B5paper** [intel-isl/Open3D#2294]
Bug:

Can't set z-axis as the up-axis with the view control.

**To Reproduce**

Normal view:

```python
import numpy as np
import open3d as o3d

points = np.random.normal(0, 0.5, (1000, 3))
o3d_points = o3d.utility.Vector3dVector(points)
pc_geometry = o3d.geometry.PointCloud()
pc_geometry.points = o3d_points
coor_frame_geometry = o3d.geometry.TriangleMesh.create_coordinate_frame()

visualizer = o3d.visualization.Visualizer()
visualizer.create_window(width=600, height=500, left=450, top=250)
visualizer.add_geometry(pc_geometry)
visualizer.add_geometry(coor_frame_geometry)

view_ctl = visualizer.get_view_control()
view_ctl.set_up((0, 1, 0))
view_ctl.set_front((1, 0, 0))
view_ctl.set_lookat((0, 0, 0))
view_ctl.set_zoom(0.3)

visualizer.run()
visualizer.destroy_window()
```

Screenshot:

![normal_view](https://user-images.githubusercontent.com/18409864/92385106-dc56cb80-f143-11ea-98db-535ffeaf000e.png)

Wrong view:

```python
import numpy as np
import open3d as o3d

points = np.random.normal(0, 0.5, (1000, 3))
o3d_points = o3d.utility.Vector3dVector(points)
pc_geometry = o3d.geometry.PointCloud()
pc_geometry.points = o3d_points
coor_frame_geometry = o3d.geometry.TriangleMesh.create_coordinate_frame()

visualizer = o3d.visualization.Visualizer()
visualizer.create_window(width=600, height=500, left=450, top=250)
visualizer.add_geometry(pc_geometry)
visualizer.add_geometry(coor_frame_geometry)

view_ctl = visualizer.get_view_control()
view_ctl.set_up((0, 0, 1))  # can't set z-axis as the up-axis
view_ctl.set_front((1, 0, 0))
view_ctl.set_lookat((0, 0, 0))
view_ctl.set_zoom(0.3)

visualizer.run()
visualizer.destroy_window()
```

Screenshort:

![wrong_view](https://user-images.githubusercontent.com/18409864/92385145-f0023200-f143-11ea-8f3a-dd95b5339b22.png)

**My environment:**

Python version: 3.7.0

open3d version: 0.10.0.1

How did I install Open3D: pip

**Comment by satej1210** [comment]
Since the up vector is calculated as a cross product of the front vector and the right vector, the front vector needs to be set first, and then the up vector can be set in your code. 

Whenever you set any of the front, up or right vectors, the other vectors are recalculated.

So I modified your code by changing when the front and the up vectors are set:
```
view_ctl = visualizer.get_view_control()
view_ctl.set_front((1, 0, 0))
view_ctl.set_up((0, 0, 1))
view_ctl.set_lookat((0, 0, 0))
view_ctl.set_zoom(0.3)
```

The default values appear to be:
```
Front: <0,0,1>
Right: <1,0,0>
Up: <0,1,0>
```

And so when you set the up vector to be <0,0,1>, the right vector will be a cross product of <0,0,1> and <0,0,1>, which is <0,0,0>. This gives you that one dot in the middle of the window.

**Comment by B5paper** [comment]
@satej1210 Thank you for your explanation. I'll try as you mentioned.
