### ISSUE TITLE
Show Coordinates on hover

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#2306]
`draw_geometries` draws the point clouds, lines etc., to the UI. It would be nice to show the (x,y) coordinates when I hover over the window. It might help to debug as in opencv `imshow` window where the coordinates are shown in the  bottom corner

**Comment by Zumbalamambo** [comment]
@griegler @yxlao Is it possible to place multiple axes throughout the view? something like [this](https://i.ytimg.com/vi/SdBDATclhXM/maxresdefault.jpg)  where it's possible to place the multiple axes?

**Comment by Zumbalamambo** [comment]
@griegler I want to place multiple `coordinate_frames`

```
points = np.random.uniform(-1, 1, size=(100, 3))
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)

points = [pcd]
tvecs = [[0,0,0],[1,1,1],[2,2,2]]


for tvec in tvecs:
    keypoints_coords = o3d.geometry.TriangleMesh.create_coordinate_frame(
        size=0.1, origin=tvec)
    points.append(keypoints_coords)


o3d.visualization.draw_geometries(points)
```

The above code works fine. However when there are almost 70Million points, the entire window is getting killed. Is there anyways to optimize it?

**Comment by Zumbalamambo** [comment]
@griegler I'm trying to draw `coordinate_axes` as well as the `lineset`.

Following is my code,

```
import numpy as np
import open3d as o3d

# Create Dummy Point Cloud
points = np.random.uniform(-1, 1, size=(100, 3))
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
points = [pcd]

# Dummy tvec
tvecs = [[0,0,0],[1,1,1],[2,2,2]]

#buff
count   = 0
query_points = []
query_lines = []

#init window
visualizer = o3d.visualization.Visualizer()
visualizer.create_window()

for tvec in tvecs:
    # draw coordinate axes
    # TODO the coordinate lags behind
    visualizer.add_geometry(
        o3d.geometry.TriangleMesh().create_coordinate_frame(size=0.1, origin=tvec))

    # create line points
    count += 1
    query_lines.append([count - 1, count])
    query_points.append(tvec)

# draw line , pcd
query_colors = [[0, 255, 0] for i in range(len(query_lines))]
query_line_set = o3d.geometry.LineSet(
    points=o3d.utility.Vector3dVector(query_points),
    lines=o3d.utility.Vector2iVector(query_lines),
)
visualizer.add_geometry(query_line_set)
visualizer.add_geometry(pcd)

visualizer.run()
```
The problem is that the `coordinate_axes` lags behind the `lineset`. Both `lineset` as well as the `coordinate_axes` uses the same `tvec`. However, the `coordinate axes` lags behind the line.

**Comment by germanros1987** [comment]
Closing this issue since it is duplicated.
