### ISSUE TITLE
trans_init in ICP registration

### ISSUE THREAD

**Issue by wilsonren** [intel-isl/Open3D#2310]
Dear All:

I'm very new to PCL and I'm trying to walk through the examples provided by the documentation. When doing ICP registration, the documentation used the following code.
```
source = o3d.io.read_point_cloud("../../TestData/ICP/cloud_bin_0.pcd")
target = o3d.io.read_point_cloud("../../TestData/ICP/cloud_bin_1.pcd")
threshold = 0.02
trans_init = np.asarray([[0.862, 0.011, -0.507, 0.5],
                         [-0.139, 0.967, -0.215, 0.7],
                         [0.487, 0.255, 0.835, -1.4],
                         [0.0, 0.0, 0.0, 1.0]])
draw_registration_result(source, target, trans_init)
```
Could anyone please kindly tell me where does the trans_init come from? The documentation says global registration needs to be used to get the initial alignment (I'm assuming the initial alignment is the trans_init ), but I run the code in global registration and it didn't generate this matrix. I saw someone said estimate_normal needs to be used, and I did try this function as well, but I don't think I can get this matrix by using this function.

Thanks a lot, guys for your great help

**Comment by griegler** [comment]
This [tutorial](http://www.open3d.org/docs/release/tutorial/Advanced/global_registration.html) should help you to get started. It starts first with global registration and then shows how to do local refinement.
