### ISSUE TITLE
Error with ConvertFromPinholeCameraParameters

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#2313]
I'm using the following code to move the camera over a trajectory.

```
import open3d as o3d

def custom_draw_geometry_with_camera_trajectory(pcd):
    custom_draw_geometry_with_camera_trajectory.index = -1
    custom_draw_geometry_with_camera_trajectory.trajectory =\
            o3d.io.read_pinhole_camera_trajectory(
                    "assets/trajectory.json")
    custom_draw_geometry_with_camera_trajectory.vis = o3d.visualization.Visualizer(
    )


    def move_forward(vis):
        
        ctr = vis.get_view_control()
        glb = custom_draw_geometry_with_camera_trajectory
        if glb.index >= 0:
            print("Capture image {:05d}".format(glb.index))
            depth = vis.capture_depth_float_buffer(False)
            image = vis.capture_screen_float_buffer(False)

        glb.index = glb.index + 1
        if glb.index < len(glb.trajectory.parameters):
            ctr.convert_from_pinhole_camera_parameters(
                glb.trajectory.parameters[glb.index])
        else:
            custom_draw_geometry_with_camera_trajectory.vis.\
                    register_animation_callback(None)
        return False

    vis = custom_draw_geometry_with_camera_trajectory.vis
    vis.create_window()
    vis.add_geometry(pcd)
    vis.get_render_option().load_from_json("assets/rendering.json")
    vis.register_animation_callback(move_forward)
    vis.run()
    vis.destroy_window()
```

Following is my `trajectory.json`.

[trajectory.txt](https://github.com/intel-isl/Open3D/files/5203319/trajectory.txt)

It throws the following warning,

`[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.
`

why is that so? However, if I change the width and height to its default `1920,1080`, it works. But my camera matrix is not the same! How can I use my custom camera intrinsic instead of the default camera intrinsic with default width and height?

**Comment by Zumbalamambo** [comment]
@yxlao is there any possible fix for this bug? I see a lot of bugs with this function in GitHub issues :(

**Comment by Zumbalamambo** [comment]
Fixed with custom view control

**Comment by djl11** [comment]
You have the columns and rows mixed up in the trajectory.txt file, also you need to change the height and width like so:
`
vis.create_window(width=512, height=512)
`
See this [issue](https://github.com/intel-isl/Open3D/issues/1164) for more info
