### ISSUE TITLE
Strange blackout behavior with new GUI module on Ubuntu

### ISSUE THREAD

**Issue by cygann** [intel-isl/Open3D#2342]
**Describe the bug**
I am trying to use the new GUI module for point cloud visualizations on both MacOS and Ubuntu. I have been able to run the vis-gui.py demo just fine on MacOS, but when I try to run it on Ubuntu, the window goes dark whenever I interact with the scene through either zooming or clicking and dragging, making it very difficult to use. Also, a small colorful icon appears in the bottom-left corner when this happens.

If anyone can help with this, it would be much appreciated! 

**To Reproduce**

Built Open3D from source on Ubuntu and ran the vis-gui.py demo

**Expected behavior**
Expected to be able to view and interact with a 3D point cloud scene in a fairly seamless fashion

**Screenshots**
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/16779401/93266351-c4440500-f75e-11ea-91b2-8b8e82ba6f22.gif)

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04.5 LTS
- Python version: Python 3.8.5
- Open3D version: 9f2dd765d7922461a922f4f8d3a8857d47baf9ba
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5.0

**Comment by prewettg** [comment]
This is interesting, I've seen something similar on Windows but haven't had time to investigate. However, I've not seen this on Linux before. What driver / video card are you using? Are you able to test with a different video card / driver, or a newer driver?

**Comment by germanros1987** [comment]
@cygann do you have the same problem for the Open3D app? Could you try to build the app and compare it with the vis-gui.py script?

**Comment by cygann** [comment]
@prewettg The video card being used is an Intel® UHD Graphics (Comet Lake 3x8 GT2), and the driver is i915. I don't have any other video cards to test with unfortunately. How would you recommend trying to update to a newer driver (I haven't done this before)? The monitor resolution is 1920 x 1080 with scaling at 100%. 

@germanros1987 I built the Open3D app and it works wonderfully, no blackout issues there.

**Comment by prewettg** [comment]
I have an Intel i655 and I can reproduce it in Python. My guess is that it is the same issue that I see on Windows with the app. I'm going to have to do some investigation, I don't really have any good theories at the moment.

**Comment by cygann** [comment]
@prewettg As an update, I built the most recent version of Open3D from source today on the same machine, and it now works as expected without the blackout behavior!

**Comment by prewettg** [comment]
Thanks for letting me know. Originally we turned off MSAA while manipulating the model, and I've verified that with Filament 1.4.5, setting no MSAA (samples=1) works, but with Filament 1.8.1 it does not. I did not have a chance to spelunk in Filament to figure out why, but a different change merged yesterday removed turning off MSAA while manipulating the model for other reasons, and has the side effect of fixing this.

I'm going to close this, but if manipulating a triangle mesh model is painfully slow (for you or someone who finds this later) please let us know. (For point clouds you can lower the downsample_threshold parameter in either Open3DScene.add_geometry or directly with the Open3DScene.downsample_threshold property.)
