### ISSUE TITLE
How to view all the rectangles (line sets) plotted at the same plane?

### ISSUE THREAD

**Issue by B5paper** [intel-isl/Open3D#2345]
When I run the following code, I can only see two rectangles but not all, no matter how I scale the view. But actually there are 5 rectangles, which matplotlib can plot completely in a figure.

```python
import numpy as np
import open3d as o3d
import matplotlib.pyplot as plt

boxes = []
boxes.append([0, 58.65, 320.9, 374])
boxes.append([684.31, 165.66, 710.23, 242.31])
boxes.append([359.32, 182.26, 400.32, 285.85])
boxes.append([19.88, 179.87, 206.64, 238])
boxes.append([650.19, 158.35, 666.9, 192.77])
boxes = np.array(boxes)  # (5, 4), 4: (xmin, ymin, xmax, ymax)

# visualize using Open3D
geo_rectangles = []
for box in boxes:
    vertices = np.array([box[[0, 1]], box[[2, 1]], box[[2, 3]], box[[0, 3]]])  # (4, 2)
    vertices = np.concatenate((vertices, np.zeros((4, 1))), axis=-1)  # (4, 3)
    vertex_pairs = np.array([[0, 1], [1, 2], [2, 3], [3, 0]], dtype='int')  # (4, 2)
    o3d_vertices = o3d.utility.Vector3dVector(vertices)
    o3d_vertex_pairs = o3d.utility.Vector2iVector(vertex_pairs)
    geo_rectangle = o3d.geometry.LineSet(o3d_vertices, o3d_vertex_pairs)
    geo_rectangles.append(geo_rectangle)
o3d.visualization.draw_geometries(geo_rectangles, width=1000, height=800)

# visualize using matplotlib
ax = plt.gca()
for box in boxes:
    rect = plt.Rectangle(box[:2], width=box[2]-box[0], height=box[3]-box[1], fill=False, color='r')
    ax.add_patch(rect)
ax.set_xlim(boxes[:, 0].min() - 50, boxes[:, 2].max() + 50)
ax.set_ylim(boxes[:, 1].min() - 50, boxes[:, 3].max() + 50)
plt.show()
```

Screenshots:

![screenshot_1](https://user-images.githubusercontent.com/18409864/93329807-5972f680-f850-11ea-92d7-2e01cb26a650.png)

![screenshot_2](https://user-images.githubusercontent.com/18409864/93329850-698ad600-f850-11ea-84d1-85b2b21c4377.png)

![screenshot_3](https://user-images.githubusercontent.com/18409864/93329828-61329b00-f850-11ea-8724-6b76203ae957.png)

What should I do to see all the rectangles in Open3D?

**Comment by griegler** [comment]
There seems to be a problem with how the view of the visualizer is set in this case. If I change the boxes to 

```python
boxes = []
boxes.append([40,40,50,50])
boxes.append([30,30,40,40])
boxes.append([20,20,30,30])
boxes.append([10,10,20,20])
boxes.append([0, 0, 10,10])
```

the view is still not centered, but I can see (by moving in the visualizer) that all line sets are drawn.
@yxlao @errissa @prewettg do you have an idea were this problem might be?

**Comment by prewettg** [comment]
It doesn't look like `draw_geometries()` automatically centers the camera on the bounding box of the geometry. However, you can use the optional `lookat`, `up`, `front`, and `zoom` parameters to `draw_geometries()` to configure the camera.

**Comment by B5paper** [comment]
It seems that there are some bugs when using the middle wheel to zoom the view. I have tried `view_ctl = visualizer.get_view_control()` and `view_ctl.set_zoom(20)` to see all the rectangles, however, when I use the middle wheel to resize the view, the view is restored to its initial state.
