### ISSUE TITLE
ImGui::SetNextWindowContentWidth does not exists

### ISSUE THREAD

**Issue by FLS-BP-US** [intel-isl/Open3D#2353]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
SetNextWindowContentWidth is not a member of ImGui.

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: 3.8
- Open3D version: 0.10.1
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): VS2019
**Additional context**
ImGui::SetNextWindowContentWidth(float(width));
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'SetNextWindowContentWidth': is not a member of 'ImGui'	GUI	C:\Dev\GitHub\Open3D\cpp\open3d\visualization\gui\Menu.cpp	260

**Comment by prewettg** [comment]
It sounds like you are using a newer version of Dear ImGUI than we are. Do you have Dear ImGUI installed on your system for a different project? What is the output from cmake?
