### ISSUE TITLE
Principal Component Axis for Point Cloud Data

### ISSUE THREAD

**Issue by dhirajsuvarna** [intel-isl/Open3D#2368]
**Is your feature request related to a problem? Please describe.**
Finding the PCA is a helpful clue in analyzing the 3D data with the use in Registration Problems

**Describe the solution you'd like**
Would like an API which output the Principal Components in an ordered fashion.

**Describe alternatives you've considered**
Have had to switch to `trimesh` library to get this information. Though it doesn't support PCA on Point Cloud Data

**Additional context**
None

**Comment by griegler** [comment]
You could just use [`compute_mean_and_covariance`](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.compute_mean_and_covariance) and then use [`np.linalg.eig`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html) on the returned covariance matrix to get the principal components.

**Comment by dhirajsuvarna** [comment]
@griegler Tried your suggesion, sadly it doesn't give accurate results

**Comment by griegler** [comment]
PCA is not robust with respect to local point density changes. So, the difference can be that the mesh vertices in the first image are differently distributed than the points in the second image. Two possibilities: Either you create a point cloud from you triangle mesh (which should give you the same result as trimesh), or you try to use [`voxel_down_sample`](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.voxel_down_sample) prior to applying PCA.

**Comment by hariharan382** [comment]
hi how did you solve this problem , i too getting some unorthodox PCA from open3d
