### ISSUE TITLE
Basic tutorial is wrong and doesn't work

### ISSUE THREAD

**Issue by TimZaman** [intel-isl/Open3D#2370]
Website: http://www.open3d.org/docs/release/tutorial/Basic/jupyter.html
![image](https://user-images.githubusercontent.com/7721540/94057213-2cfd3400-fd94-11ea-912c-45f67a2be655.png)

Local:
![image](https://user-images.githubusercontent.com/7721540/94057192-240c6280-fd94-11ea-918a-47da6b99aa11.png)

**Comment by TimZaman** [comment]
Relates to https://github.com/intel-isl/Open3D/issues/2289 . Which is closed, but seems to me it makes sense to remove non-functional examples.

**Comment by yxlao** [comment]
Closing as this has been reflected in the latest docs, see http://www.open3d.org/docs/latest/
