### ISSUE TITLE
Mapping Images of known pose to the point cloud

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#2378]
I have the laser point cloud and corresponding images with known poses. Is it possible to map the image of the known pose to the point cloud?

**Comment by griegler** [comment]
I assume with known poses you mean that the images are registered with respect to the point cloud. I am not sure what you mean with mapping the image, but what you can do is coloring the points given the images.

**Comment by Zumbalamambo** [comment]
@griegler Yes... The images are registered with respect to the point cloud. Could you please share if there are any examples?
