### ISSUE TITLE
Big difference with remove_statistical_outlier on different device

### ISSUE THREAD

**Issue by zhixiongzuo** [intel-isl/Open3D#2379]
I use remove_statistical_outlier to do pointcloud outlier remove, but the results have a big difference on different device(remote server VS local server).
```
 pcl, ind = pcd.remove_statistical_outlier(nb_neighbors=20, std_ratio=2.0)
print(pcl)
```
My pointcloud have 21.2million points, after outlier remove on remote server ,there is 21 million points with remote server, but 20.5 million points with local server.
The result of outlier remove on remote server is not good at on local serves.
my remote server has 88 Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz, but local server has 12 Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz, they are both ubuntu16.04 ,with open3d=0.8 installed by conda, and python=3.7.

**Comment by griegler** [comment]
Likely related to #2344
