### ISSUE TITLE
Open3D GUI module view controls

### ISSUE THREAD

**Issue by cygann** [intel-isl/Open3D#2385]
Is there a way to modify the view/camera settings programmatically with the new GUI module? I would like to create some buttons that modify the view by moving left/right or zooming in/out, but I am having trouble figuring out how to do this. Any guidance would be appreciated!

**Comment by prewettg** [comment]
Yes, you can. Open3D.scene.camera returns a open3d.visualization.rendering.Camera object. Currently it only supports some simple manipulations, like setting the perspective and the equivalent of gluLookAt. If you want more full-featured movement, you might be interested in open3d.visualization.gui.SceneWidget, which supports panning and zooming. (You can get details in the Open3D viewer app by doing Help >> Show Controls.) It also allows you to set either an arcball-style camera rotation or a FPS-game style fly mode, which you could do with `SceneWidget.set_view_controls(SceneWidget.FLY)` (or SceneWidget.ROTATE_CAMERA).
