### ISSUE TITLE
module 'open3d' has no attribute 'integration'

### ISSUE THREAD

**Issue by Keudeugi** [intel-isl/Open3D#2388]
_____

**Describe the bug**
Importing open3d.integration is not working in python binding.

**To Reproduce**
in terminal,
`python`
`from open3d import io` # this works
`from open3d import integration` # ImportError

**Expected behavior**
open3d.integration imported

**Screenshots**
![image](https://user-images.githubusercontent.com/9735077/94503881-7a6d1b80-0242-11eb-960b-115efdd6ed88.png)

**Environment (please complete the following information):**

- Operating system: ubuntu 20.04
- Python version: 3.8.5
- Open3D version: latest (pulled from master)
- Is this remote workstation?: no
- How did you install Open3D?: from source
- Compiler version (if built from source): gcc 7.5

Thanks in advance.

**Comment by griegler** [comment]
In the master branch (and for the upcoming release) `integration` moved into `pipelines. See [here](http://www.open3d.org/docs/latest/python_api/open3d.pipelines.integration.html).

`from open3d.pipelines import integration` should work.

**Comment by Keudeugi** [comment]
open3d.pipelines.integration seemed work. Thanks. Closing issue.
