### ISSUE TITLE
filter_smooth_laplacian fails

### ISSUE THREAD

**Issue by suishicity** [intel-isl/Open3D#2390]
**Describe the bug**
After smoothed by `filter_smooth_laplacian ` , mesh seems to be disappeared. The one-ring  vertices seems to collapse into one points.

**To Reproduce**

```python
import open3d as o3d
mesh = o3d.io.read_triangle_mesh(...)
mesh = mesh.filter_smooth_laplacian(number_of_iterations=10, filter_scope=o3d.geometry.FilterScope.Vertex)
print(mesh.get_surface_area())

```

The surface area is about 1.0e-10

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version:  Python 3.7
- Open3D version:  0.10.0.1
- Is this remote workstation?: no
- How did you install Open3D?:  pip

**Comment by griegler** [comment]
That is expected behavior for Laplacian smoothing. See [here](http://graphics.stanford.edu/courses/cs468-12-spring/LectureSlides/06_smoothing.pdf) for a description. You can try to reduce the number of iterations, reduce `lambda`, or  use `filter_smooth_taubin` which does not suffer this problem.
