### ISSUE TITLE
Is `#ifdef _OPENMP` really a must?

### ISSUE THREAD

**Issue by nachovizzo** [intel-isl/Open3D#2395]
This is a question I've been asking myself for a while. But as far as I understood, one does not really need this:
```cpp
#ifdef _OPENMP
#pragma omp parallel
    {
#endif
```

AFIK, the idea is that if the compiler doesn't know how to eat the `#pragma` then it will ignore. Or is it because this generates a warning?

So if I have this naive example
```cpp
#include <iostream>
#include <vector>

int main() {
  const int N = 1 << 30;
  std::vector<int> x;
  x.reserve(N);
#pragma omp parallel for default(none) private(x)
  for (int i = 0; i < N; ++i) {
    x.emplace_back(i);
  }

  return 0;
}
```

With this CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.10)
project(pragma_omp)

set(CMAKE_BUILD_TYPE Release)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra")

option(ENABLE_OPENMP "Enable OpenMP" OFF)
if(ENABLE_OPENMP)
  find_package(OpenMP REQUIRED)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
endif()

add_executable(main main.cpp)
```

The only thing that the guard is preventing is this warning
```sh
/main.cpp:8: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
    8 | #pragma omp parallel for default(none) private(x)
      | 
```

Is this the reason behind the guard?

I'm just curious. Thanks!

**Comment by griegler** [comment]
Yes, the guard is only because of the warning. In the current build setup we regard warnings as errors.

**Comment by nachovizzo** [comment]
What if we add `-Wno-unknown-pragmas` to the C++ flags This disables the pragma warnings and will make the code more readable. I'm totally willing to make a PR for this since takes no brainpower.

Let me know what you guys think.

**Comment by griegler** [comment]
Looping in @yxlao

**Comment by nachovizzo** [comment]
@griegler @yxlao I just created a draft PR in case you want to have a look at how these changes would look

**Comment by yxlao** [comment]
@nachovizzo sounds good
