### ISSUE TITLE
compute_point_cloud_distance

### ISSUE THREAD

**Issue by sandwich25** [intel-isl/Open3D#2404]
I have a question regarding compute_point_cloud_distance,
How does the point correspondence determined?

**Comment by griegler** [comment]
For each point in the target point cloud the index and distance to the closest point in the source point cloud is returned. https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/geometry/PointCloud.cpp#L125

**Comment by sandwich25** [comment]
Thanks!

**Comment by karlita101** [comment]
> For each point in the target point cloud the index and distance to the closest point in the source point cloud is returned. https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/geometry/PointCloud.cpp#L125

Is this the euclidean distance?

**Comment by ilyak93** [comment]
@griegler, is this distance (euclidean and e.t.c) only of the points of the different pointclouds ?
Or does the measurement of how close a point to another point also by the colors if the pointsclouds have them ? 

In my use case I would want the distances of the XYZ of the closest points using two similarity metrics, one is of course the xyz distance itself, and the second one is the color similarity, is there any simple way to implement it using your library or any other ?

**Comment by lenn-arts** [comment]
> > For each point in the target point cloud the index and distance to the closest point in the source point cloud is returned. https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/geometry/PointCloud.cpp#L125
> 
> Is this the euclidean distance?

Looks like it, but I'd also like confirmation. Do you happen to know @griegler ?
