### ISSUE TITLE
Module not found error for Python GUI

### ISSUE THREAD

**Issue by rajanidulal** [intel-isl/Open3D#2410]
- Operating system: Windows 10 64-bit
- Python version: Python 3.6
- Is this remote workstation?:  no
- How did you install Open3D?:  build from source
- Cmake:  3.18.2

Hello, I am trying to run a file under examples/python/gui. It is giving me a module not found error for open3d.visualization.gui. Am I missing anything? Open3d is installed and open3d.visualization works for other files but not in files that are under GUI folder. 
![image](https://user-images.githubusercontent.com/56923694/94859058-92d36680-03f9-11eb-8241-551a3b76aa57.png)

Thank you!

**Comment by griegler** [comment]
Can you post the output of your cmake.

**Comment by rajanidulal** [comment]
Yes, I can,



THIRD_PARTY_DOWNLOAD_DIR is not specified, will download directly.
No CMAKE_BUILD_TYPE specified, default to RelWithDebInfo
Open3D 0.10.1.0
Using python from PYTHON_EXECUTABLE variable: C:/Users/rajan/anaconda3/python.exe
(PYTHON_EXECUTABLE matches python from PATH)
Building library Assimp from source
Building with OpenMP
Building library 3rdparty_dirent from source (WIN32)
Building library 3rdparty_dirent from source
Building library 3rdparty_eigen3 from source
Building library 3rdparty_flann from source
Building library 3rdparty_nanoflann from source
Building library 3rdparty_glew from source
Building library 3rdparty_glfw3 from source
Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
Using Win32 for window creation
Building third-party library JPEG from source
NASM assembler not found - libjpeg-turbo performance may suffer
libturbojpeg: WITH_CRT_DLL=OFF
Building library 3rdparty_jsoncpp from source
Building library 3rdparty_lzf from source
Building library 3rdparty_tritriintersect from source
Building third-party library zlib from source
Building third-party library libpng from source
Building library 3rdparty_rply from source
Building library 3rdparty_tinyfiledialogs from source
Building library 3rdparty_tinygltf from source
Building library 3rdparty_tinyobjloader from source
Building library 3rdparty_qhull_r from source
Building library 3rdparty_qhullcpp from source
Building library 3rdparty_fmt from source
pybind11 v2.5.0
Building library 3rdparty_poisson from source
Building library 3rdparty_imgui from source
Using prebuilt third-party library Filament
Filament is located at C:/Users/rajan/Desktop/python/Open3D/build/filament/src/ext_filament
Using MKL to support BLAS and LAPACK functionalities.
STATIC_MKL_INCLUDE_DIR: C:/Users/rajan/Desktop/python/Open3D/build/mkl_install/include/
STATIC_MKL_LIB_DIR: C:/Users/rajan/Desktop/python/Open3D/build/mkl_install/lib
STATIC_MKL_LIBRARIES: mkl_intel_ilp64;mkl_core;mkl_sequential;mkl_tbb_thread;tbb_static
BUILD_JUPYTER_EXTENSION is set to OFF
Using Python version: 3.8
Using Python version major: 3
PYPI_PACKAGE_NAME: open3d
========================================================================
Open3D 0.10.1.0 Configuration Summary
========================================================================
Enabled Features:
  OpenMP .................................. ON
  Headless Rendering ...................... OFF
  Azure Kinect Support .................... OFF
  CUDA Support ............................ OFF
  Build GUI ............................... ON
  Build Shared Library .................... ON
  Use Windows Static Runtime .............. ON
  Build Unit Tests ........................ OFF
  Build Examples .......................... 
  Build Python Module ..................... ON
  - with Jupyter Notebook Support ......... OFF
  Build Tensorflow Ops .................... OFF
  Build Pytorch Ops ....................... OFF
  Build Benchmarks ........................ OFF
  Bundle Open3D-ML ........................ OFF
  Build RPC interface ..................... OFF
  Force GLIBCXX_USE_CXX11_ABI= ............ 0
========================================================================
Third-Party Dependencies:
  EIGEN3 .................................. yes (build from source)
  FILAMENT ................................ yes (build from source)
  FLANN ................................... yes (build from source)
  FMT ..................................... yes (build from source)
  GLEW .................................... yes (build from source)
  GLFW .................................... yes (build from source)
  GOOGLETEST .............................. no
  IMGUI ................................... yes (build from source)
  JPEG .................................... yes (build from source)
  JSONCPP ................................. yes (build from source)
  LIBLZF .................................. yes (build from source)
  OPENGL .................................. yes (build from source)
  PNG ..................................... yes (build from source)
  PYBIND11 ................................ yes (build from source)
  QHULL ................................... yes (build from source)
  LIBREALSENSE ............................ no
  TINYFILEDIALOGS ......................... yes (build from source)
  TINYGLTF ................................ yes (build from source)
  TINYOBJLOADER ........................... yes (build from source)
========================================================================
Configuring done
Generating done

**Comment by rajanidulal** [comment]
Yes, I can.


THIRD_PARTY_DOWNLOAD_DIR is not specified, will download directly.
No CMAKE_BUILD_TYPE specified, default to RelWithDebInfo
Open3D 0.10.1.0
Using python from PYTHON_EXECUTABLE variable: C:/Users/rajan/anaconda3/python.exe
(PYTHON_EXECUTABLE matches python from PATH)
Building library Assimp from source
Building with OpenMP
Building library 3rdparty_dirent from source (WIN32)
Building library 3rdparty_dirent from source
Building library 3rdparty_eigen3 from source
Building library 3rdparty_flann from source
Building library 3rdparty_nanoflann from source
Building library 3rdparty_glew from source
Building library 3rdparty_glfw3 from source
Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
Using Win32 for window creation
Building third-party library JPEG from source
NASM assembler not found - libjpeg-turbo performance may suffer
libturbojpeg: WITH_CRT_DLL=OFF
Building library 3rdparty_jsoncpp from source
Building library 3rdparty_lzf from source
Building library 3rdparty_tritriintersect from source
Building third-party library zlib from source
Building third-party library libpng from source
Building library 3rdparty_rply from source
Building library 3rdparty_tinyfiledialogs from source
Building library 3rdparty_tinygltf from source
Building library 3rdparty_tinyobjloader from source
Building library 3rdparty_qhull_r from source
Building library 3rdparty_qhullcpp from source
Building library 3rdparty_fmt from source
pybind11 v2.5.0
Building library 3rdparty_poisson from source
Building library 3rdparty_imgui from source
Using prebuilt third-party library Filament
Filament is located at C:/Users/rajan/Desktop/python/Open3D/build/filament/src/ext_filament
Using MKL to support BLAS and LAPACK functionalities.
STATIC_MKL_INCLUDE_DIR: C:/Users/rajan/Desktop/python/Open3D/build/mkl_install/include/
STATIC_MKL_LIB_DIR: C:/Users/rajan/Desktop/python/Open3D/build/mkl_install/lib
STATIC_MKL_LIBRARIES: mkl_intel_ilp64;mkl_core;mkl_sequential;mkl_tbb_thread;tbb_static
BUILD_JUPYTER_EXTENSION is set to OFF
Using Python version: 3.8
Using Python version major: 3
PYPI_PACKAGE_NAME: open3d
========================================================================
Open3D 0.10.1.0 Configuration Summary
========================================================================
Enabled Features:
  OpenMP .................................. ON
  Headless Rendering ...................... OFF
  Azure Kinect Support .................... OFF
  CUDA Support ............................ OFF
  Build GUI ............................... ON
  Build Shared Library .................... ON
  Use Windows Static Runtime .............. ON
  Build Unit Tests ........................ OFF
  Build Examples .......................... 
  Build Python Module ..................... ON
  - with Jupyter Notebook Support ......... OFF
  Build Tensorflow Ops .................... OFF
  Build Pytorch Ops ....................... OFF
  Build Benchmarks ........................ OFF
  Bundle Open3D-ML ........................ OFF
  Build RPC interface ..................... OFF
  Force GLIBCXX_USE_CXX11_ABI= ............ 0
========================================================================
Third-Party Dependencies:
  EIGEN3 .................................. yes (build from source)
  FILAMENT ................................ yes (build from source)
  FLANN ................................... yes (build from source)
  FMT ..................................... yes (build from source)
  GLEW .................................... yes (build from source)
  GLFW .................................... yes (build from source)
  GOOGLETEST .............................. no
  IMGUI ................................... yes (build from source)
  JPEG .................................... yes (build from source)
  JSONCPP ................................. yes (build from source)
  LIBLZF .................................. yes (build from source)
  OPENGL .................................. yes (build from source)
  PNG ..................................... yes (build from source)
  PYBIND11 ................................ yes (build from source)
  QHULL ................................... yes (build from source)
  LIBREALSENSE ............................ no
  TINYFILEDIALOGS ......................... yes (build from source)
  TINYGLTF ................................ yes (build from source)
  TINYOBJLOADER ........................... yes (build from source)
========================================================================
Configuring done
Generating done

**Comment by germanros1987** [comment]
@prewettg could you please comment on this?

**Comment by rajanidulal** [comment]
@germanros1987 thanks, I solved this issue already.
