### ISSUE TITLE
How can I draw a mesh and a point cloud in a same window?

### ISSUE THREAD

**Issue by bigpehi** [intel-isl/Open3D#2436]
I want to draw a point cloud and a mesh in the same window, but my code seems doesn't work.
can you give me some clues? thank you in advance!
![image](https://user-images.githubusercontent.com/35166345/95312817-fbbb5280-08c1-11eb-934d-daeee16848a8.png)
![image](https://user-images.githubusercontent.com/35166345/95312843-05dd5100-08c2-11eb-821f-daa6f4078ee4.png)
my code:  o3d.visualization.draw_geometries([pcd,mesh_frame])
What is drawn by this code is a point cloud as picture1, and no mesh in it.

**Comment by griegler** [comment]
Could it be that the size of the point cloud is max larger than the mesh? What is the output of 

```python
print(pcd.get_min_bound(), pcd.get_max_bound())
print(mesh_frame.get_min_bound(), mesh_frame.get_max_bound())
```

If this is the problem, you can try to scale the mesh_frame (see [`size`](http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.create_coordinate_frame) parameter).

**Comment by bigpehi** [comment]
> Could it be that the size of the point cloud is max larger than the mesh? What is the output of
> 
> ```python
> print(pcd.get_min_bound(), pcd.get_max_bound())
> print(mesh_frame.get_min_bound(), mesh_frame.get_max_bound())
> ```
> 
> If this is the problem, you can try to scale the mesh_frame (see [`size`](http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.create_coordinate_frame) parameter).

LoL, Why am I so stupid! Anyway, Thank you for your reply, I have solved my problem.🤝
