### ISSUE TITLE
Is there a way to change axis size in GUI module?

### ISSUE THREAD

**Issue by cygann** [intel-isl/Open3D#2440]
I'm using the new GUI module and would like to show the axes on top of the visualization. `scene.scene.show_axes(True)` (Just like [here](https://github.com/intel-isl/Open3D/blob/7fcdd037eb5b074dbd4bed34f998d2f78bdbb389/examples/python/gui/vis-gui.py#L464)) toggles this on, but the size of the axes are quite massive and I was wondering if there was a way to scale it down. Thanks!

**Comment by prewettg** [comment]
At the moment the length of the axes are computed automatically based on the bounds of the model (you can see the computation in Open3DScene::RecreateAxis() in `cpp/open3d/visualization/rendering/Open3DScene.cpp`. Right now the axes are the length of the longest dimension, or 25% of the distance of the center of the model from the origin. I suppose if your model is very flat, like a plywood board, that would lead to some awkwardly sized axes. Can you attach a (small) version of the model?

**Comment by cygann** [comment]
To update and close this, I found that creating a TriangleMesh geometry of the axis through the `TriangleMesh.create_coordinate_frame` function worked well. The point clouds I was working with were very large and flat.

```
axis = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])
scene.scene.add_geometry("axis", axis, AXIS_MATERIAL)
```

Thank you!
