### ISSUE TITLE
Ubuntu 18.04 build fails on assimp

### ISSUE THREAD

**Issue by pauljurczak** [intel-isl/Open3D#2441]
On Ubuntu 18.04.5 with g++ 8.4.0 building from master branch fails here:
```
-- Installing: /home/paul/open3d/build/assimp/include/assimp/Compiler/poppack1.h
-- Installing: /home/paul/open3d/build/assimp/include/assimp/Compiler/pstdint.h
[ 17%] Completed 'ext_assimp'
[ 17%] Built target ext_assimp
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```
I minimized configuration options and tried again with the same result.

**Comment by pauljurczak** [comment]
BTW, I also tried to build from release version v0.10.0, but it crashes in a different spot:
```
[  2%] Building C object 3rdparty/CMakeFiles/qhullstatic_r.dir/qhull/src/libqhull_r/geom2_r.c.o
-- Performing Test RIGHT_SHIFT_IS_UNSIGNED - Failed
-- Performing Test __CHAR_UNSIGNED__
-- Performing Test __CHAR_UNSIGNED__ - Failed
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_VERSION_SCRIPT
-- Performing Test HAVE_VERSION_SCRIPT - Success
-- Linker supports GNU-style version scripts
-- CMAKE_EXECUTABLE_SUFFIX = 
-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
CMake Error at simd/CMakeLists.txt:41 (enable_language):
  No CMAKE_ASM_NASM_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM_NASM" or the CMake cache entry CMAKE_ASM_NASM_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.
```
Surprisingly when I disable `BUILD_QHULL` and `BUILD_TINYFILEDIALOGS` the configuration still reports dependencies not met:

![Screenshot from 2020-10-08 00-01-29](https://user-images.githubusercontent.com/4933032/95420851-75226780-08f9-11eb-9da4-a2ee4d10df56.png)

**Comment by pauljurczak** [comment]
I installed `nasm`, played with configuration settings and build went much further, but crashed here:
```
[ 80%] Linking CXX executable ../../bin/GLInfo
[ 81%] Linking CXX executable ../../bin/MergeMesh
[ 81%] Linking CXX executable ../../bin/ManuallyCropGeometry
/usr/bin/ld: cannot find -lc++
collect2: error: ld returned 1 exit status
src/Tools/CMakeFiles/GLInfo.dir/build.make:114: recipe for target 'bin/GLInfo' failed
make[2]: *** [bin/GLInfo] Error 1
CMakeFiles/Makefile2:1464: recipe for target 'src/Tools/CMakeFiles/GLInfo.dir/all' failed
make[1]: *** [src/Tools/CMakeFiles/GLInfo.dir/all] Error 2
```
I have a fully functional g++ 8.4.0 build chain.

**Comment by pauljurczak** [comment]
After a lot of trial and error, I managed to build a configuration, unfortunately without GUI.
```
Open3D 0.10.1.0 Configuration Summary
========================================================================
Enabled Features:
  OpenMP .................................. ON
  Headless Rendering ...................... OFF
  Azure Kinect Support .................... OFF
  CUDA Support ............................ ON
  Build GUI ............................... OFF
  Build Shared Library .................... OFF
  Build Unit Tests ........................ OFF
  Build Examples .......................... ON
  Build Python Module ..................... OFF
  Build Tensorflow Ops .................... OFF
  Build Pytorch Ops ....................... OFF
  Build Benchmarks ........................ ON
  Bundle Open3D-ML ........................ OFF
  Build RPC interface ..................... OFF
  Force GLIBCXX_USE_CXX11_ABI= ............ 0
========================================================================
Third-Party Dependencies:
  EIGEN3 .................................. yes (build from source)
  FILAMENT ................................ no
  FLANN ................................... yes (build from source)
  FMT ..................................... yes (build from source)
  GLEW .................................... yes (build from source)
  GLFW .................................... yes (build from source)
  GOOGLETEST .............................. no
  IMGUI ................................... no
  JPEG .................................... yes (build from source)
  JSONCPP ................................. yes (build from source)
  LIBLZF .................................. yes (build from source)
  OPENGL .................................. yes (build from source)
  PNG ..................................... yes (build from source)
  PYBIND11 ................................ yes (build from source)
  QHULL ................................... yes (build from source)
  LIBREALSENSE ............................ no
  TINYFILEDIALOGS ......................... yes (build from source)
  TINYGLTF ................................ yes (build from source)
  TINYOBJLOADER ........................... yes (build from source)
```

**Comment by manhha1402** [comment]
I have the same issue when building from master branch

**Comment by hy-son** [comment]
I also have the same problem after following the official compiling tutorial:

```
git clone --recursive https://github.com/intel-isl/Open3D
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=<open3d_install_directory> ..
```
The output of cmake:
```
[ 21%] Completed 'ext_assimp'
[ 21%] Built target ext_assimp
make: *** [all] Error 2
```
My version of cmake is 3.17.3 and I'm not on Ubuntu but RedHat 7.8.

**Comment by yxlao** [comment]
@pauljurczak did you do `git clone --recursive` or `git submodule update --init --recursive` if you have already cloned?

@pauljurczak regarding `/usr/bin/ld: cannot find -lc++`, it is related to filament build (with BUILD_GUI=ON), make sure you have https://github.com/intel-isl/Open3D/blob/2cce041736d7b47f87d2086bcf9bb83d077c016b/util/install_deps_ubuntu.sh#L21-L26 installed. 

@hy-son we need the line that is actually showing the error message.

**Comment by pauljurczak** [comment]
@yxlao 
1. I used  `git clone --recursive` 

2. Thanks for list of dependencies. Now it builds fine. Perhaps dependencies should be listed in build instructions.

3. The `assimp` build error is very cryptic, there is no useful context.

**Comment by hy-son** [comment]
@yxlao I just run  `cmake -DCMAKE_INSTALL_PREFIX=<open3d_install_directory> .. ` and the output was:
`[ 21%] Built target ext_assimp`
`make: *** [all] Error 2`
I'm not sure what do you mean by "the line that is actually showing the error message".

**Comment by yxlao** [comment]
@hy-son can you share the full terminal log and error message? 

`make: *** [all] Error 2` is the error message summary. Typically there are some other actual error messages printed before this. If they are not showing up, use `make VERBOSE=1`.

**Comment by mingyangpeng** [comment]
via "git clone --recursive https://github.com/intel-isl/Open3D" ,I find the third party library incompatibility(due to them have update)
I hate the submodule, Why not provide matching third-party libraries.

**Comment by yxlao** [comment]
@mingyangpeng if you run into problems with submodule, try `git submodule init --update --recursive`, or, simply start from scratch and clone again.

**Comment by x007jianjian** [comment]
I had the same error, which was caused by the cloning assimp error seemingly. When I stopped using the proxy in terminal, such error was solved and the assimp was cloned successfully

(
but why did I use the proxy in terminal previously？
To solve 'ext_mkl_include' cloning error.
lol.
)

**Comment by scimad** [comment]
I get similar issue, 
`Built target ext_assimp
make: *** [all] Error 2`

But  it builds fine if I delete everything from build folder and rebuild as instructed in official doc.

**Comment by AncientRemember** [comment]
git checkout v0.11.0

**Comment by Spritaro** [comment]
I was having the same problem but ```make -j1``` resulted in different error message.

```sh
[  3%] Building C object CMakeFiles/3rdparty_glew.dir/3rdparty/glew/src/glew.c.o
In file included from /tmp/Open3D/3rdparty/glew/src/glew.c:34:
/tmp/Open3D/3rdparty/glew/include/GL/glew.h:1205:14: fatal error: GL/glu.h: No such file or directory
 1205 | #    include <GL/glu.h>
      |              ^~~~~~~~~~
compilation terminated.
```

Installing ```libglu1-mesa-dev``` solved the error for me. Maybe the error message ```Built target ext_assimp make: *** [all] Error 2``` only showed up because ```make``` was running in parallel?
