### ISSUE TITLE
Unable to capture depth image from the pointcloud

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#2443]
I'm would like to capture the depth image from the point cloud. I'm using the following code to create the camera. I have ofcourse converted the cameramatrix in an open3d renderer compatible format..

```
import copy
import numpy
import open3d as o3d
from open3d.open3d_pybind import camera

pointcloud = o3d.io.read_point_cloud("assets/dataset/pointcloud.pcd")


def build_open3d_compat_camera_param(camera_parameters):
    #   * f_x and f_y must be equal
    #   * c_x must be equal to width / 2 - 0.5
    #   * c_y must be equal to height / 2 - 0.5
    intrinsics = camera_parameters.intrinsic
    width = intrinsics.width
    height = intrinsics.height
    cx_renderer = width / 2.0 - 0.5
    cy_renderer = height / 2.0 - 0.5
    f_renderer = max(intrinsics.get_focal_length())

    render_compatible_camera_parameters = copy.deepcopy(camera_parameters)
    render_compatible_camera_parameters.intrinsic.set_intrinsics(
        width, height, f_renderer, f_renderer, cx_renderer, cy_renderer)

    return render_compatible_camera_parameters


# camera params
focal_x = 3579.03
center_x = 2612.08
focal_y = 3576.44
center_y = 1719.79

# camera matrix - intrinsic
K = [[focal_x, 0, center_x],
     [0, focal_y, center_y],
     [0, 0, 1]]

# camera pose - extrinsic
original_pose = [[-0.000916, 0.518866, 0.854857, -1.12120745e+02],
                 [0.008149, 0.854857, -0.518866, 86.014819],
                 [-0.999900, 0.008000, -0.011300, 1.758000],
                 [0, 0, 0, 1]]

# Create camera matrix
camera_parameters = camera.PinholeCameraParameters()
camera_parameters.extrinsic = numpy.array(original_pose)
camera_parameters.intrinsic.set_intrinsics(width=5184, height=3456, fx=focal_x, fy=focal_y, cx=center_x, cy=center_y)

# convert to open3d compatible camera param
render_compatible_camera_parameters = build_open3d_compat_camera_param(camera_parameters)
intrinsics = render_compatible_camera_parameters.intrinsic

# create the visualizer
vis = o3d.visualization.Visualizer()

# use the render compatible params to create window
vis.create_window(
    width=intrinsics.width, height=intrinsics.height, left=0, top=0, visible=True)

view_control = vis.get_view_control()

# use render compatible parameter 
view_control.convert_from_pinhole_camera_parameters(render_compatible_camera_parameters)

vis.add_geometry(pointcloud)
vis.run()

```

Unfortunately, it throws the following error while trying to run convert the pinhole camera parameters,

`[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.`

How can I fix this? Isn't there any other way to retrieve the camera matrix from an arbitrary camera matrix?

**Comment by griegler** [comment]
The current visualizer does not support arbitrary principal points, but they have to fit the height and width of the window. This is a known issue and will be addressed in the new visualizer. See also #1164, #2036.

**Comment by Zumbalamambo** [comment]
@griegler after going through those threads, I have created this method called `build_open3d_compat_camera_param` which does the same. Unfortunately, the error still persists. Not sure if I'm doing it right :( 

Also  I have built open3d from source.   Which branch I must fork if this feature is available in any of the branches?

**Comment by griegler** [comment]
The new visualizer is still under development, but is continually added to the master branch. See [this](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/vis-gui.py) example.

**Comment by Zumbalamambo** [comment]
Thank you! I will try that approach
