### ISSUE TITLE
A mistake in TriangleMeshSimplification.cpp

### ISSUE THREAD

**Issue by suishicity** [intel-isl/Open3D#2444]
**Describe the bug**
I found a mistake in [TriangleMeshSimplification.cpp](https://github.com/intel-isl/Open3D/blob/1807774a3aaa23d54e5941a0db35234e11c5848e/cpp/open3d/geometry/TriangleMeshSimplification.cpp#L365). This mistake may not cause big problem. The  code is as follow
```cpp
                const Eigen::Vector3d& v0 = mesh->vertices_[vidx0];
                const Eigen::Vector3d& v1 = mesh->vertices_[vidx1];
                Eigen::Vector3d vmid = (v0 + v1) / 2;
                double cost0 = Qbar.Eval(v0);
                double cost1 = Qbar.Eval(v1);
                double costmid = Qbar.Eval(vbar);
                cost = std::min(cost0, std::min(cost1, costmid));
```
The  `costmid = Qbar.Eval(vbar)` shoud be `costmid = Qbar.Eval(vmid);`

**Environment (please complete the following information):**

- Operating system:  Windows 10 64-bit
- Python version:  Python 3.7
- Open3D version: 0.10.0

**Comment by griegler** [comment]
Thanks, that really seems to be a mistake. Could you open a PR with a fix?

**Comment by ximenesfel** [comment]
@suishicity and @griegler I would like to start contributing to open3d project. There is someone working in this issue? If not, can I open a PR?

**Comment by griegler** [comment]
@ximenesfel no, nobody addressed this issue so far. A PR would be great.

**Comment by ximenesfel** [comment]
@griegler I created this issue two days ago and  the CI is stuck in theses checks.

![github](https://user-images.githubusercontent.com/12705275/97366729-8e7a5c00-1886-11eb-84f9-4abd84e54df8.png)

This is normal? Is there a problem with CI?
