### ISSUE TITLE
Get vertex at axis Z (0,0,z) in python

### ISSUE THREAD

**Issue by sebaFP** [intel-isl/Open3D#2446]
Hello,
I want to know if is there a way to get the vertex index of the point nearest to z axis (like a raycasting) without using visualization (or using visualization but only code) using python.
The objective is start scanning using a reference, and later traslate the pointcloud using the coordinates of that reference but automatically.

Thank you!

**Comment by griegler** [comment]
You can use something like this

```python
vertices = np.asarray(mesh.vertices)
index = np.argsort(vertics[:,2])[0] # or [-1]
```
