### ISSUE TITLE
Open3D GUI scene add_geometry for other type of geometry such as box and line etc?

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2448]
Hello,

I played a little Open3D\examples\python\GUI\vis-gui.py, added the following two lines, but no box shown. Anything wrong here? Might be something wrong with the 3rd argument?

Thank you!

` box = geometry.get_oriented_bounding_box()
  self._scene.scene.add_geometry("__box__", box, self.settings.material) 
`

**Comment by prewettg** [comment]
The new renderer can only render triangle meshes, line sets, and point clouds at the moment. The result of `get_oriented_bounding_box()` is a `open3d.geometry.OrientedBoundingBox`, which can be converted to a LineSet with `open3d.geometry.LineSet.create_from_oriented_bounding_box()`. I've created a fix, which should be in the master branch in a day or two. You might also want to use an unlit material for your lines.
```
bounds = geometry.get_oriented_bounding_box()
bbox = open3d.geometry.LineSet.create_from_oriented_bounding_box(bounds)
bbox_material = open3d.visualization.rendering.Material()
bbox_material.base_color = [1.0, 0.5, 0.0, 1.0]  # orange
bbox_material.shader = "defaultUnlit"
self._scene.scene.add_geometry("__bbox__", bbox, bbox_material)
```
After #2520 is merged you will not need the 2nd line any more (as long as you rename the variable in line 1 to "bbox"), but you will need to compile from source or wait until the next release.
