### ISSUE TITLE
How can i change the dobule format of property x to float?thanks!!!!

### ISSUE THREAD

**Issue by BiaoBiaoLi** [intel-isl/Open3D#2450]
pcd = o3d.io.read_point_cloud("D:\PointCloud_DataSet\RedWood\loft\loft/mesh_0.ply")
points=np.asarray(pcd.points).astype(float)
pcd.points=o3d.open3d_pybind.utility.Vector3dVector(points)
o3d.io.write_point_cloud("D:\PointCloud_DataSet\RedWood\loft/mesh_0.ply", pcd, write_ascii=True, compressed=True)

mesh_0.ply
ply
format ascii 1.0
comment Created by Open3D
element vertex 128675
property double x
property double y
property double z
thanks!!!!

**Comment by yxlao** [comment]
@ShubhamAgarwal12, #2377 can address the PLY read of arbitrary dtype, and we can have another PR to address the PLY write to arbitrary dtype.

**Comment by BiaoBiaoLi** [comment]
I use the python，Is it have the same fuction in python？
in the io.py,it only has this two functions:
read_point_cloud(filename, format='auto', remove_nan_points=True, remove_infinite_points=True, print_progress=False)
write_point_cloud(filename, pointcloud, write_ascii=False, compressed=False, print_progress=False)
I can not address the PLY read of arbitrary dtype.
thanks!

**Comment by BiaoBiaoLi** [comment]
I also want to know how to change the point_cloud to mesh，thanks

**Comment by yxlao** [comment]
> I use the python，Is it have the same fuction in python？

We don't have the conversion function right now, as all of the pcd and mesh data are stored in double. But, soon we will add this functionality.

> I also want to know how to change the point_cloud to mesh，thanks

If you simply want the points and the vertices in mesh, simply do `my_mesh.vertices_ = pcd.points_`. However, this will not give you any triangles. If you need a mesh with triangles, see [surface reconstruction](http://www.open3d.org/docs/release/tutorial/geometry/surface_reconstruction.html).

**Comment by ShubhamAgarwal12** [comment]
You can use our tensor implementation for the conversion. Something like the following should work:
    
    import open3d as o3d
    import open3d.core as o3c

    pct = o3d.t.io.read_point_cloud("<in_file_path>")
    points=pct.point["points"].as_tensor().numpy()
    points=points.astype('float')
    pct.point["points"]= o3c.TensorList.from_tensor(o3c.Tensor(points))
    o3d.t.io.write_point_cloud("<out_file_path>", pct, write_ascii=True, compressed=True)

**Comment by cjwayn** [comment]
as of v0.17 onwards, TensorList doesnt work anymore.

Try this:
        points=np.asarray(pc.points)
        dtype = o3d.core.float32
        p_tensor = o3d.core.Tensor(points, dtype=dtype)
        pc = o3d.t.geometry.PointCloud(p_tensor) 
        o3d.t.io.write_point_cloud("tmp/float32.ply", pc, write_ascii=True)

**Comment by joeylitalien** [comment]
How would you go about doing the same for meshes?
