### ISSUE TITLE
remote error: upload-pack: not our ref d41dc4dd74acce21fb210e7625d5d135751fa9e5

### ISSUE THREAD

**Issue by zqhfox** [intel-isl/Open3D#2456]
git clone --recursive --branch ml-module https://github.com/intel-isl/Open3D.git

get error:

fatal: remote error: upload-pack: not our ref d41dc4dd74acce21fb210e7625d5d135751fa9e5
fatal: the remote end hung up unexpectedly
Fetched in submodule path '3rdparty/Eigen', but it did not contain d41dc4dd74acce21fb210e7625d5d135751fa9e5. Direct fetching of that commit failed.

**Comment by yxlao** [comment]
Please use `master`. As of today, the `ml-module` branch is out-dated, the last update was on Jun 20.
