### ISSUE TITLE
The output mesh (.obj) file does not have textures using crop function of open3d

### ISSUE THREAD

**Issue by LuZaiJiaoXiaL** [intel-isl/Open3D#2464]
The input mesh is a .obj file with full textures. I want to crop it to get a part as an output. However, the output mesh (.obj) file does not have textures using crop function. Is there a solution to solve it? 

key code_python

def seperate(tranglemesh):
        maxbox=tranglemesh.get_max_bound()
        minbox=tranglemesh.get_min_bound()
        crop_box=o3d.geometry.AxisAlignedBoundingBox([minbox[0],minbox[1],100],[maxbox[0],maxbox[1],151.2])
        pcdc=tranglemesh.crop(crop_box)
        o3d.io.write_triangle_mesh(outputpath,pcdc)

The output files include a .mtl file and .obj file. No textures files (.jpg or png) exist. And the mapping recorded in the .mtl file is also not complete.

Thank you for your comments and opinions.

**Comment by griegler** [comment]
Unfortunately, most of the mesh processing functions do not consider textures (or material maps). This includes also the crop method at the moment. We have it on our list.

**Comment by LuZaiJiaoXiaL** [comment]
OK. Thank you. I see.

**Comment by LuZaiJiaoXiaL** [comment]
By the way, may I know if there are some other open-source tools or platforms, which can realize this case? @griegler Thanks.

**Comment by griegler** [comment]
Maybe vcglib https://github.com/cnr-isti-vclab/vcglib

**Comment by LuZaiJiaoXiaL** [comment]
OK. Thanks.

**Comment by liuliu66** [comment]
@griegler Hi, has this function been implemented? It is important for me in cropping meshes. Thank you!

**Comment by nickponline** [comment]
@LuZaiJiaoXiaL @liuliu66  @griegler I'm also looking for this, or at least a workaround using other tools?

**Comment by zell180** [comment]
i'm looking for this, no fix or feature implementation?
