### ISSUE TITLE
How to use compiled-from-source library? #buildissue

### ISSUE THREAD

**Issue by EvaKrassnig** [intel-isl/Open3D#2465]
I am using Windows 10 and Visual Studio 2019, Python 3.8. I followed the steps to build from source for windows described here: http://www.open3d.org/docs/release/compilation.html#compilation-ubuntu-install
And could proceed with build and install until the step as shown in picture attached. (By the way: I am using Intel D435 and if I try to build the CMake file with the librealsense library I get an error message).
After compiling from source, how can I use these libraries in my own project? My apologies if the question is stupid, but up to now I only used pip packages which I could use in my own python projects by "Import....". Though I need geometry.TriangleMesh.Get_Volume, which is not included in the pip package. 

![BuildfromSource](https://user-images.githubusercontent.com/71384423/95871796-5f37fb00-0d6e-11eb-8138-f29dcd71b483.PNG)

**Comment by EvaKrassnig** [comment]
Thanks! This seems to work, I can see the function get_volume now. I will try out the function and close the issue after verifying.

**Comment by EvaKrassnig** [comment]
Can you please check if the o3d.registration module is included? I get an error message that this module does not exist.

**Comment by griegler** [comment]
Please check the docs and make sure `latest` is active. `o3d.registration` has been moved to `o3d.pipelines.registration`. http://www.open3d.org/docs/latest/python_api/open3d.pipelines.registration.html

**Comment by EvaKrassnig** [comment]
Thank you, that works!
