### ISSUE TITLE
3D reconstruction and color + depth images from .bag file

### ISSUE THREAD

**Issue by 4nightmare** [intel-isl/Open3D#2467]
Hi,

I'm trying to make a 3D reconstruction of a scene with an Intel realsense 435i camera.

I used your "reconstruction system" (from your python examples) after having recorded images through the "realsense_recorder".
It worked really well, but i was wondering if **is it possible to reconstruct a scene directly from a .bag file?**
I ask that because I have some recording from which i'd like to create a reconstruction.

[ I think this feature could be really useful, because one can keep the recorded file and extract later on data (like frame metadata, odometry. etc) regarding the frames used for the 3d recontruction. ]

**if not is there a way to extract from recorded .bag file colour and depth images and then process those with the reconstruction system?**

I tried to extract color and depth images using the realsense_converter tool ( https://github.com/IntelRealSense/librealsense/tree/master/tools/convert ) and then process them, but I can't get any ply file (neither in fragment neither in scene folders). I think that the depth images extracted with realsense converter are not saved in the same "color_scale" needed from O3D (I can see depth O3D images in a kind of greyscale and Rsense extracted ones in RGB color). **which is the "color_scale" utilized by the reconstruction system? do you know if is available in the Intel RealSense viewer software?**

 In add to that I just realized that I don't know how to extract from the .bag file recorded the "intrinsic.json" needed for the reconstruction. **is this intrinsic file to be extracted before at the beginning of the streaming (i.e. first frame)? or is needed to extract it per each frame?**

I hope someone can help me!

**Comment by zapaishchykova** [comment]
yes, you can extract color and depth from bag file, take a look into pyrealsence python library

**Comment by 4nightmare** [comment]
Hi @zapaishchykova ,

Thanks for your suggestion!

As I wrote above I used rs-converter to extract images from all the frames in the bag file (in add to the standard Intel Realsense Viewer option to pause the video and save images from the selected frames).

The problem is that when I  use this extracted images inside the O3D python Reconstruction-System I cannot achieve any Pointcloud reconstruction(neither in fragment neither in scene folders).

I think this is because of the method used from realsense converter/Viewer to save depth data inside the ending PNG file, but I'm not so sure on that.

Do you have some more information or suggestion?
I ask the same also to @theNded ?

**Comment by zapaishchykova** [comment]
Check your intrinsics? And maybe paste your code since it's hard to say what's wrong there

**Comment by antenna-fast** [comment]
Hi,what's the detail of the recontruction  with d435i?
For i can't get a true intrinsic, when i run --make ,it rise an error 
[Open3D ERROR] [ScalableTSDFVolume::Integrate] depth image size is (640 x 480), but got (-1 x -1) from intrinsic.

**Comment by ssheorey** [comment]
We now have support to extract frames and intrinsic parameters from a bag file (save_frames()). The reconstruction system can do this automatically if the input is a bag file instead of a folder.

Resolved by #2646
