### ISSUE TITLE
Not responding with many geometries

### ISSUE THREAD

**Issue by Jiayuan-Gu** [intel-isl/Open3D#2472]
**Describe the bug**
The interactive window is not responding when many geometries (>=400) are visualized.

**To Reproduce**

```python
import open3d as o3d
import numpy as np

points = np.random.uniform(-1.0, 1.0, size=[100000, 3])
boxes = np.random.uniform(0, 1, size=[400, 6])
pc = o3d.geometry.PointCloud()
pc.points = o3d.utility.Vector3dVector(points)
geometries = [pc]
for box in boxes:
    abb = o3d.geometry.AxisAlignedBoundingBox(box[0:3] - box[3:6] * 0.5, box[0:3] + box[3:6] * 0.5)
    geometries.append(abb)
o3d.visualization.draw_geometries(geometries)
```

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: e.g. Python 3.7
- Open3D version: 10.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by prewettg** [comment]
A very unfortunate and incorrect merge conflict resolution some time ago left us adding n^2 geometries. #2523 restores back to the requested number of geometries, which fixes this issue.
