### ISSUE TITLE
multiple synchronous kinects

### ISSUE THREAD

**Issue by Pran-chole-kf** [intel-isl/Open3D#2478]
Hi
I was wondering if it is possible to use open3d in **python** to capture a scene using multiple **synchronized** and **calibrated** kinect azure cameras. I am trying to do segmentation on the images. so I would also need to map a segmentation mask from **2d(image) to 3d (pointcloud)**. Is this possible ?

1. synchronize and calibrate multiple cameras
2. map an image mask from 2D to 3D

thanks

**Comment by yxlao** [comment]
Microsoft has documentation on [device synchronization](https://docs.microsoft.com/en-us/azure/kinect-dk/multi-camera-sync#:~:text=Each%20Azure%20Kinect%20DK%20device,the%20trigger%20timing%20between%20them.). Currently, Open3D does not support synchronized Kinect recording. We are open to pull requests if you developed your own synchronization system.
