### ISSUE TITLE
memory leak while loading stl file

### ISSUE THREAD

**Issue by lianghongzhuo** [intel-isl/Open3D#2479]
**Describe the bug**
when I load stl file generated from openscad I got `MemoryError: std::bad_alloc`
and try to run the same code on a server with 128 g memory, I found the memory is keeping increase and eventually fails to load stl file. Convert the stl file using meshlab can solve the problem.
**To Reproduce**

```
import open3d as o3d
o3d.io.read_triangle_mesh("mesh.stl")
```
**Environment (please complete the following information):**

- Operating system:  Ubuntu 18.04
- Python version:  Python 3.7
- Open3D version: 0.10
- Is this remote workstation?:  no
- How did you install Open3D?:  conda

**Additional context**
stl file I used:

[mesh.zip](https://github.com/intel-isl/Open3D/files/5384151/mesh.zip)

**Comment by lianghongzhuo** [comment]
update: I tested another stl file with binary format, it works. However I still cannot import ascii format stl

**Comment by yxlao** [comment]
Yes, the current STL reader assumes binary format. Added a fix in #2506

**Comment by lianghongzhuo** [comment]
Thanks!
