### ISSUE TITLE
python run_system.py config/realsense.json --make --register --refine --integrate on Debian 10 (Buster) doesn't work

### ISSUE THREAD

**Issue by nanotuxi** [intel-isl/Open3D#2489]
**Describe the bug**
running `.run_system.py config/realsense.json --make --register --refine --integrate` on Debian 10 (Buster) in a python virtual environment throws an error.
`Traceback (most recent call last):
  File "run_system.py", line 68, in <module>
    make_fragments.run(config)
  File "~/Open3D/examples/python/reconstruction_system/make_fragments.py", line 177, in run
    if config["python_multi_threading"].lower() == "true":
AttributeError: 'bool' object has no attribute 'lower'`

**My solution**
remove all `.lower()` methods from the corresponding files.
These are:
`make_fragments.py`
`refine_registration.py`
`register_fragments.py`

**To Reproduce**
1. Clone a fresh version of Open3d 0.11.0
2. configure, compile and install in a python virtiúal environment
3. cd into `Open3D/examples/python/reconstruction_system/sensors/`
4. record scene with `realsense_recorder.py` a scene (Intel Realsense D435i)
5. cd into `~/Open3D/examples/python/reconstruction_system` and run 
`optirun python run_system.py config/realsense.json --make --register --refine --integrate`

**Expected behavior**
The script should run without error and produce the files needed for reconstructing the recorded scene.

**Environment (please complete the following information):**

- Operating system: Debian GNU/Linux 10 (buster)
- Python version: Python 3.7.3
- Open3D version: 0.11.0
- Is this remote workstation?:  no
- How did you install Open3D?: build from source
- Compiler version:
gcc (Debian 8.3.0-6) 8.3.0 
clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final) Target: x86_64-pc-linux-gnu Thread model posix 
CUDA Version 10.1.243

**Comment by shuixing85** [comment]
Thanks a lot @nanotuxi , it works well with your way!
