### ISSUE TITLE
Python2 crash on rotate on OrientedBoundingBox

### ISSUE THREAD

**Issue by MRzNone** [intel-isl/Open3D#2494]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Calling rotate on OrientedBoundingBox lead to crash

**To Reproduce**
![image](https://user-images.githubusercontent.com/8140868/96241462-0b3c3a80-0f57-11eb-82b5-c1cd63487347.png)

**Expected behavior**
This should rotate the box

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04 LTS
- Python version: 2.7.18rc1
- Open3D version: 0.9.0.0
- Is this remote workstation?: both
- How did you install Open3D?: pip
- Compiler version (if built from source):gcc version 8.4.0 (Ubuntu 8.4.0-3ubuntu2)

**Comment by yxlao** [comment]
Python 2 is no longer supported. We recommend updating to Python 3+ and Open3D 0.10.0+.

**Comment by MRzNone** [comment]
Is there a version that is working with python2?  I have to use python2 for a project.
