### ISSUE TITLE
No source release for open3d 0.10.0.1 

### ISSUE THREAD

**Issue by ForceFaction** [intel-isl/Open3D#2498]
As it's not possible to comment on #2360 anymore, i need to open a new Ticket.

In #2360 it's suggested to use another link to the project's PyPi site. This was not the problem i meant there. If you compare with for example https://pypi.org/project/numpy/#files you can see that they offer a source package, besides the wheel packages. This is missing for open3d and necessary if a user wants to build from source. It's also used in some package managers (at least guix) that automatically try to deduce a package recipe for a given pypi package.

Hopefully this clarifies #2360 :smiley: 

forcefaction

**Comment by yxlao** [comment]
Thanks @ForceFaction for the clarification. 

In fact, the build steps for Open3D involves 3rd-party libraries, CUDA (if enabled), TensorFlow/PyTorch (if ML is enabled), etc. This makes putting all source code in the PyPi package a bit convoluted. We recommend checking out the source code directly and build using the [v0.11 guide](http://www.open3d.org/docs/release/compilation.html) or [v0.10 guide](http://www.open3d.org/docs/0.10.0/compilation.html).

**Comment by yxlao** [comment]
BTW, can't you comment in a closed issue?

**Comment by ForceFaction** [comment]
Hm okay i see, that's what i have to do then :smile: 

Not sure if i can, it was late and maybe i just didn't see correctly, sorry...
