### ISSUE TITLE
AttributeError: module 'open3d' has no attribute 'core'

### ISSUE THREAD

**Issue by NomitRwt** [intel-isl/Open3D#2504]
Error:
AttributeError: module 'open3d' has no attribute 'core'

To Reproduce:
If you have google account then open google colab
1. !pip install addict
2. !pip install open3d
3. import open3d

Expected behavior
It was running successfully yesterday and also addict was not required.

**Comment by benjaminum** [comment]
Can you try this?
```
!pip install addict pandas plyfile tqdm sklearn open3d
import open3d
```

BTW, do you know how to reset google colab? _Factory reset runtime_ does not clean up everything for me (packages are still installed after reset).

**Comment by NomitRwt** [comment]
@benjaminum seems to be working now. I am not sure about reset option. You can check [FAQ](https://research.google.com/colaboratory/faq.html#:~:text=Selecting%20Runtime%20%3E%20Factory%20reset%20runtime,or%20installation%20of%20incompatible%20software.). Thanks!
