### ISSUE TITLE
Open3d 0.11.0 (with PyTorch/CUDA) built failed on windows

### ISSUE THREAD

**Issue by nawara72** [intel-isl/Open3D#2507]
Hi
I have 2 issues and would appreciate your help

- I am trying to build open3d0.11.0 from source on windows using visual studio 2019
Get the following error,

15>C:\Program Files\Open3D-0.11.0\cpp\open3d/core/Atomic.h(44,48): error C2664: 'long _InterlockedExchangeAdd(volatile long *,long)': cannot convert argument 1 from 'uint32_t *' to 'volatile long *' (compiling source file C:\Program Files\Open3D-0.11.0\cpp\open3d\ml\pytorch\misc\RadiusSearchOpKernel.cpp)

- Also I tried to follow the instructions on https://github.com/intel-isl/Open3D-ML, but get the following error
python -c "import open3d.ml.torch as ml3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\cv\AppData\Local\Programs\Python\Python37\lib\site-packages\open3d\ml\torch\__init__.py", line 33, in <module>
    raise Exception('Open3D was not built with PyTorch support!')
Exception: Open3D was not built with PyTorch support!

I am assuming the pre-built pip packages for windows doesn't include  Open3D-ML ?

Thanks

**Comment by benjaminum** [comment]
Yes, the ML part is not included in the windows wheel at the moment due to some problems building the operators for Tensorflow. If you do not need the ML operators you can try to build without them.
The models for torch in Open3D-ML do not depend on them.

Another workaround would be to use the Windows Subsystem for Linux WSL with the Linux wheels.

**Comment by nawara72** [comment]
I have switched ML and cuda off, but i keep getting errors.
Eg
geometry\Line3D.h(117,9): error C3861: 'transform': identifier not found 

I had no issues with previous versions of Open3D
Any ideas how to fix?

Thanks

**Comment by ssheorey** [comment]
Can you replicate the error following our [build scripts](https://github.com/intel-isl/Open3D/blob/master/.github/workflows/windows.yml) on Windows? Select any of the matrix configuration options.

**Comment by nawara72** [comment]
Thanks for your reply, I am not sure I understand
My last message about the "transform" error
geometry\Line3D.h(117,9): error C3861: 'transform': identifier not found
is when I try to build open3d from source with visual studio

**Comment by ssheorey** [comment]
Let's try to isolate the error. Does this command line build work for you? This is from our CI build scripts.

```ps1
git clone --recursive https://github.com/intel-isl/Open3D.git
cd open3d
mkdir build
cd build
cmake -G "Visual Studio 16 2019" -A x64 -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX="C:\Program Files\Open3D" -DBUILD_SHARED_LIBS=OFF -DSTATIC_WINDOWS_RUNTIME=ON 
cmake --build . --parallel 2 --config Release --target INSTALL
```

**Comment by nawara72** [comment]
Thanks for your reply, I followed the steps you mentioned and that worked. I would now like to build the cuda module and the bundele-open3d-ml, could you please advise (cause that's what i believe is failing in my original build)

Thanks

**Comment by ssheorey** [comment]
We don't support CUDA on Windows for now. If you are able to get things running with `-DBUILD_CUDA_MODULE=ON` as an additional argument to `cmake`, please do submit a PR.
For Open3D-ML, we don't support the ML operations on Windows for now. Based on @benjaminum 's message, it may work to enable support for PyTorch. Can you try with `-DBUILD_PYTORCH_OPS=ON` as well?

**Comment by nawara72** [comment]
I tried the following
cmake .. -G "Visual Studio 16 2019" -A x64 -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX="C:\Program Files\Open3D" -DBUILD_SHARED_LIBS=OFF -DSTATIC_WINDOWS_RUNTIME=ON  -DBUILD_CUDA_MODULE=OFF  -DBUILD_PYTORCH_OPS=ON -DBUILD_TENSORFLOW_OPS=OFF -DBUNDLE_OPEN3D_ML=ON  -DOPEN3D_ML_ROOT="https://github.com/intel-isl/Open3D-ML.git" 
So with cuda off , pytorch on and tensorflow off
I got the following error

  Performing download step (git clone) for 'open3d_ml'
  Cloning into 'open3d_ml'...
  Octree.cpp
  FileLOG.cpp
  ssh: Could not resolve hostname c: Name or service not known
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  Cloning into 'open3d_ml'...
  FileOBJ.cpp
  PointCloud.cpp
  ssh: Could not resolve hostname c: Name or service not known
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  Cloning into 'open3d_ml'...
  Generating Code...
  PointCloudCluster.cpp
  ssh: Could not resolve hostname c: Name or service not known
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  -- Had to git clone more than once:
  CMake Error at C:/Program Files/Open3D/build/open3d_ml/tmp/open3d_ml-gitclone.cmake:31 (message):
            3 times.
    Failed to clone repository: 'C:/Program
    Files/Open3D/build/https:/github.com/intel-isl/Open3D-ML.git'


Thanks

**Comment by nawara72** [comment]
Any updates on building Open3D-ML, on Windows with PyTorch support?? Thanks

**Comment by michele-arrival** [comment]
> I tried the following
> cmake .. -G "Visual Studio 16 2019" -A x64 -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX="C:\Program Files\Open3D" -DBUILD_SHARED_LIBS=OFF -DSTATIC_WINDOWS_RUNTIME=ON -DBUILD_CUDA_MODULE=OFF -DBUILD_PYTORCH_OPS=ON -DBUILD_TENSORFLOW_OPS=OFF -DBUNDLE_OPEN3D_ML=ON -DOPEN3D_ML_ROOT="https://github.com/intel-isl/Open3D-ML.git"
> So with cuda off , pytorch on and tensorflow off
> I got the following error
> 
> [...]
> Failed to clone repository: 'C:/Program
> Files/Open3D/build/https:/github.com/intel-isl/Open3D-ML.git'
> 
> Thanks

To avoid this you need to to clone Open3D-ML to a separate folder and pass that location as OPEN3D_ML_ROOT

After this there's an error coming from some configuration of the CUDA build commands that raise `nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified`

the full command is 
````
  nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets(764,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\C
UDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_30,code=\"compute_30,compute_30\" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env -ccbin "C:\P
rogram Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64" -x cu  -IC:\Data\Open3D\cpp -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Data\Op
en3D\build\assimp\include -IC:\Data\Open3D\3rdparty\dirent -IC:\Data\Open3D\3rdparty\flann -IC:\Data\Open3D\3rdparty\nanoflann\include -IC:\Data\Open3D\3rdparty\glew\include -IC:\Data\Open3D\3rdparty\GLFW\inclu
de -I"C:\Data\Open3D\build\libjpeg-turbo-install\include" -IC:\Data\Open3D\3rdparty\jsoncpp\include -IC:\Data\Open3D\3rdparty\liblzf -IC:\Data\Open3D\3rdparty\tomasakeninemoeller\include -IC:\Data\Open3D\3rdpar
ty\libpng -IC:\Data\Open3D\3rdparty -IC:\Data\Open3D\3rdparty\rply\rply -IC:\Data\Open3D\3rdparty\tinyfiledialogs\include -IC:\Data\Open3D\3rdparty\tinygltf\tinygltf -IC:\Data\Open3D\3rdparty\tinyobjloader\tiny
objloader -IC:\Data\Open3D\3rdparty\qhull\src -IC:\Data\Open3D\3rdparty\PoissonRecon -IC:\Data\Open3D\3rdparty\imgui -IC:\Data\Open3D\build\filament\src\ext_filament\include -IC:\Data\Open3D\build\mkl_install\i
nclude -IC:\Data\Open3D\3rdparty\Eigen -IC:\Data\Open3D\3rdparty\fmt\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compi
le -cudart static /bigobj /Ob2 /EHsc /wd4522 /wd4190 /wd4819 /Wv:18 /WX /MP --expt-extended-lambda --Werror all-warnings,cross-execution-space-call,reorder,deprecated-declarations -std=c++14 -Xcompiler="/EHsc -
Ob2"    -D_WINDOWS -DNDEBUG -DMKL_ILP64 -DBUILD_CUDA_MODULE -DBUILD_CACHED_CUDA_MANAGER -D_GLIBCXX_USE_CXX11_ABI=0 -DWINDOWS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DNO
MINMAX -D_USE_MATH_DEFINES -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D__TBB_LIB_NAME=tbb_static -DOPEN3D_ENABLE_DLL_EXPORTS -DGLEW_STATIC -DTINYGLTF_IMPLEMENTATION -DSTB_IMAGE_IMPLEMENTATION -DSTB_IMAGE_WRITE_IMPLEME
NTATION -DTINYOBJLOADER_IMPLEMENTATION -DFMT_HEADER_ONLY=1 -D"CMAKE_INTDIR=\"Release\"" -DWIN32 -D_WINDOWS -D_CRT_SECURE_NO_WARNINGS -DNDEBUG -DMKL_ILP64 -DBUILD_CUDA_MODULE -DBUILD_CACHED_CUDA_MANAGER -D_GLIBC
XX_USE_CXX11_ABI=0 -DWINDOWS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DNOMINMAX -D_USE_MATH_DEFINES -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D__TBB_LIB_NAME=tbb_static -DOPEN
3D_ENABLE_DLL_EXPORTS -DGLEW_STATIC -DTINYGLTF_IMPLEMENTATION -DSTB_IMAGE_IMPLEMENTATION -DSTB_IMAGE_WRITE_IMPLEMENTATION -DTINYOBJLOADER_IMPLEMENTATION -DFMT_HEADER_ONLY=1 -D"CMAKE_INTDIR=\"Release\"" -D_MBCS
-Xcompiler "/EHsc /W3 /nologo /O2 /Fdcore.dir\Release\core.pdb /FS /Zi  /MT /GR" -o core.dir\Release\DefaultHashmapCUDA.obj "C:\Data\Open3D\cpp\open3d\core\hashmap\CUDA\DefaultHashmapCUDA.cu"" exited with code
1. [C:\Data\Open3D\build\cpp\open3d\core\core.vcxproj]
````

it should be a simple CMake configuration issue, however i can't really figure out what is wrong with it in the first place.

Any ideas?

**Comment by ssheorey** [comment]
@michele-arrival We have improved support for CUDA in Windows from PR #3380. Can you try rebuilding with CUDA + PyTorch and let us know if it works?

**Comment by nawara72** [comment]
Thanks for your reply, I just downloaded the latest cuda and tried using cmake and got the following error
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCUDACompiler.cmake:552 (message):
  The CMAKE_CUDA_ARCHITECTURES:

    61-real

  do not all work with this compiler.  Try:

    52

  instead.
Call Stack (most recent call first):
  CMakeLists.txt:436 (enable_language)
would appreciate your help

**Comment by ssheorey** [comment]
Hi @nawara72, you can specify your GPU's CUDA architecture with this CMake option. e.g.:

    cmake -D CMAKE_CUDA_ARCHITECTURES=52 <other cmake options> <source folder>

See the cmake documentation for more details about this. If this doesn't work, please provide more details:

- CUDA toolkit version
- CMake command line (or options set through the cmake GUI)

**Comment by nawara72** [comment]
Thanks for your help, all compiled and installed :-)

**Comment by ssheorey** [comment]
Sounds good. Please re-open this or a new issue if you face any other problems.

**Comment by ohlaris** [comment]
I am having the same issue and hope someone can help:

>>> import open3d.ml.tf as ml3d
2021-09-16 13:45:45.521089: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\open3d\ml\tf\__init__.py", line 32, in <module>
    raise Exception('Open3D was not built with TensorFlow support!')
Exception: Open3D was not built with TensorFlow support!

I am using:
Python 3.8.5
Tensorflow = 2.4.1
CUDA = 11.2

When using:
cmake -D CMAKE_CUDA_ARCHITECTURES=52 <other cmake options> <source folder>

what would be the <source folder>?
Should I go to the cmake folder or open3D folder? Sorry, I am new to cmake and compiling.
