### ISSUE TITLE
release 11.0 pip is (also) broken on google colab.

### ISSUE THREAD

**Issue by RussTedrake** [intel-isl/Open3D#2509]
**Describe the bug**
```
----> 2 import open3d as o3d

7 frames
/usr/local/lib/python3.6/dist-packages/open3d/_ml3d/utils/config.py in <module>()
      5 import yaml
      6 from importlib import import_module
----> 7 from addict import Dict
      8 
      9 

ModuleNotFoundError: No module named 'addict'
```

**To Reproduce**
[here is a notebook](https://colab.research.google.com/drive/1JpQ_90_jqX_dmFgZ5AAZ4gItx7a1aqf_#scrollTo=Fz00agxXp4CC) 
```
!pip install open3d
import open3d as o3d
```

**Environment (please complete the following information):**

Google Colab
Open3D version 11.0

**Comment by RussTedrake** [comment]
Ah, I see now this was noticed and closed in #2504.  But I would expect `pip install open3d` to work by itself, no?

**Comment by benjaminum** [comment]
Yes, let's keep this issue open until the problem is resolved.

**Comment by EricWiener** [comment]
Just installed with `conda` and get the exact same error. I was able to fix it with `conda install -c conda-forge addict`. I can create a new issue if you want.

**Comment by ssheorey** [comment]
Please install with `pip` in `conda` environments as well. We are planning to deprecate the `conda` packages.

**Comment by mochsner** [comment]
For what it's worth, I tried @EricWiener 's solution and still missing packages. Created issue to update the documentation as I find it misleading to still recommend Conda as the preferred install method (@ssheorey)
