### ISSUE TITLE
open3d==0.11.0 on Ubuntu 18.04: "libc++.so.1: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by EricCousineau-TRI** [intel-isl/Open3D#2518]
**Describe the bug**
Release 0.11.0 seems to fail when trying to import :( Encountered by @naveenoid
May relate other release issues (#2509 #2508) - FYI @russtedrake

**To Reproduce**

```
$ alias bash-isolate='env -i HOME=$HOME DISPLAY=$DISPLAY SHELL=$SHELL TERM=$TERM USER=$USER PATH=/usr/local/bin:/usr/bin:/bin bash --norc'
$ bash-isolate <<EOF
set -eux
env
cd $(mktemp -d)
python3 -I -m virtualenv -p python3 .
./bin/python -I -m pip install open3d==0.11.0
./bin/python -I -c 'import open3d as m; print(m.__version__)'
EOF
...
+ env
DISPLAY=:1
USER=eacousineau
PWD=/tmp/tmp.jpv39t50Yu
HOME=/home/eacousineau
TERM=screen
SHELL=/bin/bash
SHLVL=1
PATH=/usr/local/bin:/usr/bin:/bin
_=/usr/bin/env
+ cd /tmp/tmp.yZRbmGxHLJ
+ python3 -I -m virtualenv -p python3 .
...
+ ./bin/python -I -m pip install open3d==0.11.0
Collecting open3d==0.11.0
...
Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 argon2-cffi-20.1.0 async-generator-1.10 attrs-20.2.0 backcall-0.2.0 bleach-3.2.1 certifi-2020.6.20 cffi-1.14.3 cycler-0.10.0 decorator-4.4.2 defusedxml-0.6.0 entrypoints-0.3 importlib-metadata-2.0.0 ipykernel-5.3.4 ipython-7.16.1 ipython-genutils-0.2.0 ipywidgets-7.5.1 jedi-0.17.2 jinja2-2.11.2 jsonschema-3.2.0 jupyter-client-6.1.7 jupyter-core-4.6.3 jupyterlab-pygments-0.1.2 kiwisolver-1.2.0 matplotlib-3.3.2 mistune-0.8.4 nbclient-0.5.1 nbconvert-6.0.7 nbformat-5.0.8 nest-asyncio-1.4.1 notebook-6.1.4 numpy-1.19.2 open3d-0.11.0 packaging-20.4 pandocfilters-1.4.2 parso-0.7.1 pexpect-4.8.0 pickleshare-0.7.5 pillow-8.0.0 prometheus-client-0.8.0 prompt-toolkit-3.0.8 ptyprocess-0.6.0 pycparser-2.20 pygments-2.7.1 pyparsing-2.4.7 pyrsistent-0.17.3 python-dateutil-2.8.1 pyzmq-19.0.2 six-1.15.0 terminado-0.9.1 testpath-0.4.4 tornado-6.0.4 traitlets-4.3.3 wcwidth-0.2.5 webencodings-0.5.1 widgetsnbextension-3.5.1 zipp-3.3.1
+ ./bin/python -I -c 'import open3d as m; print(m.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmp.yZRbmGxHLJ/lib/python3.6/site-packages/open3d/__init__.py", line 64, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc++.so.1: cannot open shared object file: No such file or directory
```

**Expected behavior**
It works?

**Screenshots**
N/A

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6.9
- Open3D version: 0.11.0
- Is this remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): N/A

**Additional context**
Open3d is an awesome lib! Understandable on some distro issues; lemme know if there's any other info I can supply.

**Comment by jwnimmer-tri** [comment]
This is related to #2420.

As a work-around, adding `env LD_LIBRARY_PATH=lib/python3.6/site-packages/open3d` before `bin/python` resolves the loading error for me.  After also installing some more missing pip stuff (torch, etc.), I get `0.11.0` printed successfully.

The bug is that the `glob()`s are wrong:

https://github.com/intel-isl/Open3D/blob/v0.11.0/python/open3d/__init__.py#L54-L55

The first glob loads `libc++abi.so.1`.  So does the second one, depending on the iteration order returned by the OS's glob implementation.  We need to anchor the second glob so that it doesn't match the `libc++abi.so.1` but does match `libc++.so.1`.

**Comment by JzHuai0108** [comment]
I encountered a similar error in open3d for python3.9. 
```
OSError: libc++.so.1: cannot open shared object file: No such file or directory
```
It is solved by 
```
sudo apt install libc++-dev
```
according to [here](https://askubuntu.com/questions/1219027/problem-with-shared-library-libc-so-1-on-kubuntu-18-04).
