### ISSUE TITLE
Vector3iVector & Vector4iVector in python

### ISSUE THREAD

**Issue by ItayKishon** [intel-isl/Open3D#2525]
**Describe the bug**
Originally, I was trying to create a pointcloud from a (n,4) numpy array using Vector4iVector, with no success.
Upon further investigation, is seems that Vector3iVector (i.e. (n,3)) is behaving the same, with a similar error message.

**To Reproduce**
```
import open3d as o3d
import numpy as np
points3dfloat = (np.random.randn(500,3)*1000).astype(np.float32)
points3dint   = (np.random.randn(500,3)*1000).astype(np.int16  )
points4dint   = (np.random.randn(500,4)*1000).astype(np.int16  )
```
```
pcl = o3d.geometry.PointCloud()
pcl.points = o3d.utility.Vector3dVector(points3dfloat)
o3d.visualization.draw_geometries([pcl])
```
(working successfully, I can see the pointcloud)

```
pcl = o3d.geometry.PointCloud()
pcl.points = o3d.utility.Vector3iVector(points3dint)
o3d.visualization.draw_geometries([pcl])
```

Error:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-3-b165cd01c183> in <module>
>       1 pcl = o3d.geometry.PointCloud()
> ----> 2 pcl.points = o3d.utility.Vector3iVector(points3dint)
>       3 o3d.visualization.draw_geometries([pcl])
> 
> TypeError: (): incompatible function arguments. The following argument types are supported:
>     1. (self: open3d.open3d_pybind.geometry.PointCloud, arg0: open3d.open3d_pybind.utility.Vector3dVector) -> None
> 
> Invoked with: geometry::PointCloud with 0 points., std::vector<Eigen::Vector3i> with 500 elements.
> Use numpy.asarray() to access data.
> 
> Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
> <pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
> conversions are optional and require extra headers to be included
> when compiling your pybind11 module.
> 

```
pcl = o3d.geometry.PointCloud()
pcl.points = o3d.utility.Vector4iVector(points4dint)
o3d.visualization.draw_geometries([pcl])
```

Error:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-4-d3ca2865ff82> in <module>
>       1 pcl = o3d.geometry.PointCloud()
> ----> 2 pcl.points = o3d.utility.Vector4iVector(points4dint)
>       3 o3d.visualization.draw_geometries([pcl])
> 
> TypeError: (): incompatible function arguments. The following argument types are supported:
>     1. (self: open3d.open3d_pybind.geometry.PointCloud, arg0: open3d.open3d_pybind.utility.Vector3dVector) -> None
> 
> Invoked with: geometry::PointCloud with 0 points., std::vector<Eigen::Vector4i> with 500 elements.
> Use numpy.asarray() to access data.
> 
> Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
> <pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
> conversions are optional and require extra headers to be included
> when compiling your pybind11 module.

**Expected behavior**
A similar result to that of Vector3dVector.

**Environment:**

- Operating system: Windows 10 Pro 64
- Python version: Python 3.8.3, Conda 4.8.5
- Open3D version: 0.10.0.1 (I know there's a new version, 0.11, yet it's not yet available in conda. Moreover, according to the [changelog](http://www.open3d.org/2020/10/15/open3d-0-11-0/), those issues aren't solved in that release).
- Is this remote workstation?:  no
- How did you install Open3D?: conda
- Compiler version (if built from source): N/A

Thanks,
Itay

**Comment by sanskar107** [comment]
We only support (n, 3) arrays for `pcl.points`. Anyway you can use `Vector3dVector` for integer types as well.

**Comment by ItayKishon** [comment]
Thank you.
Do I understand correctly, that (n,3) are essentially z per each (x,y)?
If so, how can I implement any set of (x,y,z), meaning different z's for the same (x,y) ?

**Comment by sanskar107** [comment]
yes, `(x, y, z)` are 3d coordinates of points in a pointcloud.
