### ISSUE TITLE
Question: What is the difference between o3d.io.capture_frame() and o3d.io.record_frame()?

### ISSUE THREAD

**Issue by Me817** [intel-isl/Open3D#2526]
Hello, 
I tried the script provided by @kaixin-bai in #1437 and I get one coloured point cloud. But I would like to record a sequence of coloured point clouds not only one as you can do with azure_kinect_recorder.py. I saw that @kaixin-bai uses the function o3d.io.capture_frame() instead of o3d.io.record_frame() Open3D is using in their azure_kinect_recorder.py. What is the difference between o3d.io.capture_frame() and o3d.io.record_frame()? Is it possible to record a sequence of coloured point clouds with o3d.io.capture_frame()?
Thank you in advance.

**Comment by kaixin-bai** [comment]
Check the links below, you'll find that "capture_frame" can return only RGBD image, while "record_frame" can not only return RGBD image, but also save a mkv file for further applications.

[http://www.open3d.org/docs/release/python_api/open3d.io.AzureKinectSensor.html?highlight=capture_frame#open3d.io.AzureKinectSensor.capture_frame](url)

[http://www.open3d.org/docs/release/python_api/open3d.io.AzureKinectRecorder.html?highlight=record_frame](url)

**Comment by Me817** [comment]
Ah, I see. Thank you. 
I will close the issue now.
