### ISSUE TITLE
OSError: libc++.so.1: cannot open shared object file: No such file or directory (Since v0.11)

### ISSUE THREAD

**Issue by ch-sa** [intel-isl/Open3D#2531]
**Describe the bug**
I installed Open3D in my conda environment using pip. When running python and trying to import Open3D, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/christoph/miniconda3/envs/lab/lib/python3.6/site-packages/open3d/__init__.py", line 64, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/home/christoph/miniconda3/envs/lab/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc++.so.1: cannot open shared object file: No such file or directory
```

**To Reproduce**

1. Create a conda environment with python 3.6.12.
2. Install Open3D with pip `pip install Open3D`
3. Run python and `import open3d`

**Expected behavior**
I expected a successful import of Open3D. 

**Environment (please complete the following information):**

- Operating system: Linux Mint 20,
- Python version: Python 3.6.12
- Open3D version: 0.11.0
- Is this remote workstation?: no
- How did you install Open3D?: with pip in conda 4.9.0
- System: Kernel: 5.8.0-23-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.6.7 wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
- Machine:   Type: Laptop System: LENOVO product: 20UES00L00 v: ThinkPad T14 Gen 1 serial: <filter> Chassis: type: 10 serial: <filter> Mobo: LENOVO model: 20UES00L00 serial: <filter> UEFI: LENOVO v: R1BET36W(1.05 ) date: 06/11/2020 
- CPU: Topology: 8-Core model: AMD Ryzen 7 PRO 4750U with Radeon Graphics bits: 64 type: MT MCP arch: Zen rev: 1 L2 cache: 4096 KiB flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 54299 Speed: 1361 MHz min/max: 1400/1700 MHz Core speeds (MHz): 1: 1395 2: 1388 3: 2144 4: 1736 5: 1307 6: 1262 7: 1256 8: 1254 9: 1392 10: 1373 11: 1390 12: 1375 13: 1463 14: 1417 15: 1281 16: 1313 
- Graphics:  Device-1: AMD Renoir vendor: Lenovo driver: amdgpu v: kernel bus ID: 07:00.0 chip ID: 1002:1636 Display: x11 server: X.Org 1.20.8 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz OpenGL: renderer: AMD RENOIR (DRM 3.38.0 5.8.0-23-generic LLVM 10.0.0) v: 4.6 Mesa 20.0.8 direct render: Yes 

**Additional context**
Importing Open3D when installing version 0.10.0 worked fine.

**EDIT**
* Repeating the same process with Python 3.8.5 leads to the same error.

**Comment by NomitRwt** [comment]
You can check [#2518](https://github.com/intel-isl/Open3D/issues/2518) [#2420](https://github.com/intel-isl/Open3D/pull/2420)
