### ISSUE TITLE
pip: Separate extra requirements to other configs, like `open3d[ml]`?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [intel-isl/Open3D#2533]
**Is your feature request related to a problem? Please describe.**

My naive reading of this patch:
https://github.com/intel-isl/Open3D/pull/2513/files#diff-eb8b42d9346d0a5d371facf21a8bfa2d16fb49e213ae7c21f03863accebe0fcf

Leads me to believe that if `open3d` is distributed to `pypi` with builtin ML support, then installing `open3d` may also pull in those (heavy) deps.

**Describe the solution you'd like**

Is it possible to add a config option like `open3d[ml]`?

Here's an example from `trimesh`:
https://github.com/mikedh/trimesh/blob/4cacbffcd9bd1a637bf05b638bc3376464e3577b/setup.py
https://github.com/mikedh/trimesh/tree/4cacbffcd9bd1a637bf05b638bc3376464e3577b#basic-installation

Or has this already been considered?

**Describe alternatives you've considered**
N/A

**Additional context**

Latest `setuptools` docs seem to pushing the TOML `setup.cfg` approach pretty hard :(
Will see if I can figger out how to link to `setup.py` approach...

**Comment by yxlao** [comment]
The `open3d[ml]` approach could work. We've considered this approach (e.g. https://github.com/intel-isl/Open3D/pull/2513/commits/5a45eddb010f4b782a8e65fe9ebaf5f874318ef4#diff-eb8b42d9346d0a5d371facf21a8bfa2d16fb 49e213ae7c21f03863accebe0fcfR58), but it also has some drawbacks, e.g. compatibility issues for `conda install`. 

The current solution is that we'll make sure the ML's `requirements.txt` is as small as possible. We won't be including heavy dependencies like pytorch and tensorflow. We'll be releasing `0.11.1` soon with the new dependency setup.

**Comment by EricCousineau-TRI** [comment]
Awesome, thanks!

Should this issue remain open until the 0.11.1 release or there's a comment which minimizes the deps currently on master?

**Comment by sanskar107** [comment]
Open3D `0.11.1` is out now with minimal dependencies.

**Comment by EricCousineau-TRI** [comment]
Thanks!!!
