### ISSUE TITLE
AttributeError: module 'open3d.cuda.pybind.io' has no attribute 'AzureKinectMKVReader'

### ISSUE THREAD

**Issue by petteriTeikari** [intel-isl/Open3D#2544]
I tried to reproduce your tutorial on how to read Kinect Azure DK .mkvs from http://www.open3d.org/docs/latest/tutorial/Basic/azure_kinect.html#open3d-azure-kinect-mkv-reader

**Describe the bug**

Ran into the following error

```
python examples/python/reconstruction_system/sensors/azure_kinect_mkv_reader.py --input test_static.mkv
No output path, only play mkv
Traceback (most recent call last):
  File "examples/python/reconstruction_system/sensors/azure_kinect_mkv_reader.py", line 134, in <module>
    reader = ReaderWithCallback(args.input, args.output)
  File "examples/python/reconstruction_system/sensors/azure_kinect_mkv_reader.py", line 26, in __init__
    self.reader = o3d.io.AzureKinectMKVReader()
AttributeError: module 'open3d.cuda.pybind.io' has no attribute 'AzureKinectMKVReader'
```

![image](https://user-images.githubusercontent.com/1060514/97125164-ea2fd280-172a-11eb-97d2-f4efed821f3f.png)

**Expected behavior**

I assumed to have imported the reader correctly, but is the tutorial outdated or how should I import that?

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6, edit: _created a Python 3.8 venv and the problem persisted_
- Open3D version: 0.11.0
- Is this remote workstation?: yes or no
- How did you install Open3D?:`pip install open3d`
- CUDA version: Build cuda_11.1.TC455_06.29069683_0

**Comment by NomitRwt** [comment]
You can try using `pip install open3d==0.10.0` !

**Comment by petteriTeikari** [comment]
Well that yes worked @NomitRwt :+1:
