### ISSUE TITLE
RGBA png files are no longer supported in open3d.geometry.PointCloud.create_from_depth_image in v0.11.x

### ISSUE THREAD

**Issue by IvanCobotic** [intel-isl/Open3D#2547]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
In Open3D <v0.11.0 it was possible to read 4 channel RGBA png files with o3d.io.read_image(..) and then use the image to create a RGBDImage and later create a pointcloud with o3d.geometry.PointCloud.create_from_rgbd_image

This worked because o3d.io.read_image discarded the alpha channel and loaded the image as a 3 channel RGB image.

In v0.11.0 the behaviour of o3d.io.read_image() is changed so Open3D (correctly) reads a RGBA png file as a 4 channel image.

However, this causes the subsequent call to o3d.geometry.PointCloud.create_from_rgbd_image() to fail with error message
RuntimeError: [Open3D ERROR] [CreatePointCloudFromRGBDImage] Unsupported image format.

the reason is that o3d.geometry.PointCloud.create_from_rgbd_image has a check that only allows color images with exactly 1 or 3 channels, ie a RGBA image generates an error.

It seems logical that RGBA images should be supported when generating point clouds, although im not sure if this is a missing feature or a bug. It did however work in v0.10.0 and stopped working in v0.11.0

**To Reproduce**
intrinsic_o3d = intrinsic parameters for image used
rgb_path = path to RGBA png image
color_raw_rgba = o3d.io.read_image(rgb_path)
depth_raw = o3d.io.read_image(depth_path)
rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
                color_raw_rgba, depth_raw)
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
            rgbd_image,
            intrinsic_o3d)

in v0.10.0
this works (color_raw_rgba will have 3 channels, alpha channel is omitted)
in v0.11.0/v0.11.1
RuntimeError: [Open3D ERROR] [CreatePointCloudFromRGBDImage] Unsupported image format.

**Expected behavior**
If RGBA images are supported when reading an image it should be supported when generating point clouds with RGBD image pairs.

**Additional context**

**Comment by germanros1987** [comment]
@errissa could you please take a look at this?

**Comment by errissa** [comment]
@IvanCobotic PR #2577 addresses this issue.

**Comment by errissa** [comment]
Current master has the fix for this issue.
