### ISSUE TITLE
Open3D documentation in v0.11.0 has incorrect paths

### ISSUE THREAD

**Issue by IvanCobotic** [intel-isl/Open3D#2548]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
All paths in the Open3D documentation (from v0.11.0) have an extra inclusion of cpu.pybind

for instance, 
http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html

__init__(self: open3d.cpu.pybind.geometry.PointCloud) -> None

the cpu.pybind should not be included when listing the path.

in v0.9.0 the paths are correctly listed without inclusion of pybind artefacts

*

**Comment by Fred3D-tech** [comment]
and by the way the reconstruction system is not working anymore... even correcting the python problems, using the tutorial dataset, you don't get a correct result.

**Comment by sanskar107** [comment]
This is due to recent import changes in `v0.11`. @ssheorey  do you think we can change this ?
