### ISSUE TITLE
open3d.visualization.VisualizerWithVertexSelection produces Segmentation fault on Mac OS with v0.11.1

### ISSUE THREAD

**Issue by cygann** [intel-isl/Open3D#2552]
**Describe the bug**
I'm trying to use the open3d.visualization.VisualizerWithVertexSelection class to create an interactive visualization, however it always crashes with segmentation fault (Error message: `Segmentation fault: 11`).

**To Reproduce**

I wrote a simple script to test the behavior of VisualizerWithVertexSelection:
```
import open3d as o3d

pcd = o3d.io.read_point_cloud('test.pcd')
vis = o3d.visualization.VisualizerWithVertexSelection()

vis.create_window()
vis.add_geometry(pcd)
vis.run()
```
and ran it using Open3D v0.11.1, which produces a segmentation fault without opening any window. I switched my Open3D version to v0.11.0, and I was able to run the script without any trouble, so hopefully this can help identify the issue. Works just fine with both versions on Ubuntu.

**Expected behavior**
Expected to have a functional VisualizerWithVertexSelection window appear.

**Environment (please complete the following information):**

- Operating system: MacOS 10.15.6
- Python version: Python 3.7.1
- Open3D version: 0.11.1
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by rjsgml5698** [comment]
Did you satisfied OpenGL 3.3(At least)?

**Comment by jaredbaggen** [comment]
I'm also now getting this error but upon upgrade from 10 -> 11.1. It happens on `create_window()`.

**Comment by germanros1987** [comment]
@prewettg since you are the MacOS expert, can you comment on this issue?

**Comment by AhmadBaracat** [comment]
Reporting the same error (Segmentation Fault).

**Operating system:** MacOS Catalina 10.15.7
**Python version:** 3.8.5
**Open3D version:** 0.11.2
**Is this a remote workstation?:** no
**How did you install Open3D?** I tried both pip and conda installations


Snippet to reproduce the error:
```
import open3d as o3d
import numpy as np
pcl = o3d.geometry.PointCloud()
pcl.points = o3d.utility.Vector3dVector(np.random.randn(500,3))
o3d.visualization.draw_geometries([pcl])
```

**Comment by guy4261** [comment]
Going back down to `pip install open3d==0.10.0.0` made this code work. So if you're not using any `0.11.x` specific feature, that's what I'd recommend until they fix it :(

**Comment by cygann** [comment]
@guy4261 @AhmadBaracat Does `0.11.0` work for you? It works on my Mac, which lets me use the `0.11.x` features, but anything `0.11.1+` does not work.

**Comment by prewettg** [comment]
There appears to be a problem with our linking to OpenGL through Filament, which results in the OpenGL functions not being loaded. As a workaround, you can compile with the cmake flag -DBUILD_GUI=OFF and then we will link to OpenGL directly.

**Comment by AhmadBaracat** [comment]
Thanks @guy4261 and @cygann. I have tried `0.10.0.0` and `0.11.0` and both of them work fine now 🎉

**Comment by ZhongYupei** [comment]
@guy4261 Thanks it works!
