### ISSUE TITLE
Cannot create pointcloud from numpy array, "array is not writeable"

### ISSUE THREAD

**Issue by Martzi** [intel-isl/Open3D#2557]
I am not sure it is strictly related to Open3D instead of numpy, but I encountered a "**ValueError: array is not writeable**" error.
I tried to read pointcloud stream from Intel RealSense D435i and show points with Open3D (v0.10.0) through pyzmq.
I get the correct numpy array, formed as required, but I cannot process it as it would have been directly connected to my pc with usb.
This code
`pts = receive_pointcloud(socket)`
`pointcloud.points = o3d.utility.Vector3dVector(pts)`
Results in:
**pointcloud.points = o3d.utility.Vector3dVector(pts)
ValueError: array is not writeable**
My numpy version is 1.19.3 and I write this in python3 (3.6.9)
Has anyone seen this problem before?
I read this issue before at [https://github.com/PyTables/PyTables/issues/719](https://github.com/PyTables/PyTables/issues/719) it seems solved at newer versions, but still does not help me.

**Comment by iretiayo** [comment]
Try:
```
pts = receive_pointcloud(socket)
pointcloud = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(pts))
```

**Comment by BojanMatovski** [comment]
I had this issue as well, it worked well for me when I made a copy of the original data:

```
from copy import deepcopy

pointcloud = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(deepcopy(pts)))
```

It might have something to do with the way the array is read, since you read it with `receive_pointcloud(socket)` and I got my data from a binary serialized file through `np.from_buffer(binary_data)`.

Hope this helps,
Bojan
