### ISSUE TITLE
Get wrong results when make fragment

### ISSUE THREAD

**Issue by Anlarry** [intel-isl/Open3D#2565]
Hi, I'm trying to run Reconstruction system. I followed the tutorial, but got strange results when **Make fragments**. My config is folowing.

```json
{
    "name": "Open3D reconstruction tutorial http://open3d.org/docs/release/tutorial/reconstruction_system/system_overview.html",
    "path_dataset": "/home/user_name/test/Open3D/examples/python/reconstruction_system/",
    "path_intrinsic": "",
    "max_depth": 3.0,
    "voxel_size": 0.05,
    "max_depth_diff": 0.07,
    "preference_loop_closure_odometry": 0.1,
    "preference_loop_closure_registration": 5.0,
    "tsdf_cubic_size": 30.0,
    "icp_method": "color",
    "global_registration": "ransac",
    "python_multi_threading": "true"
}
```
Below is the `frament_001.ply` I got.I want to know why I got this result.

![图片](https://user-images.githubusercontent.com/42707884/97898502-e7f4f600-1d72-11eb-82d3-3a93484f29e1.png)

Thanks!

**Comment by nanotuxi** [comment]
v@Anlarry Seems to be related with #2107 as the results here look very similar. In v0.11 the reconstruction examples don't work stable. As suggested by @devernay [ here](https://github.com/intel-isl/Open3D/issues/2107#issuecomment-719808802) you should downgrade to version 0.10 for a robust and stable working base.

**Comment by theNded** [comment]
Please check my analysis in #2107, thanks!

**Comment by theNded** [comment]
Updates can be found in #2107, this is closed for now. There will be a fix soon, thanks for your patience!
