### ISSUE TITLE
How to display point clouds and words at the same time?

### ISSUE THREAD

**Issue by chenxyyy** [intel-isl/Open3D#2586]
Can the Open3D show words? I'm doing point cloud detection and want it to show the category of each target.

Does anyone know?

Thanks! @ @adamlofts

**Comment by sanskar107** [comment]
Right now there is no method to show words. We would appreciate if you want to contribute.

**Comment by errissa** [comment]
The ability to put text labels in a 3D scene was recently added to the roadmap for 0.12.

**Comment by chenxyyy** [comment]
Oh！ Great！I'm looking forward to version 0.12
