### ISSUE TITLE
Open3DViewer macOS crash

### ISSUE THREAD

**Issue by griegler** [intel-isl/Open3D#2591]
I loaded a mesh in the open3d viewer application on macOs (10.15.7) and then I wanted to save an image via menu - "Export Current Image". This crashes the application, no image is saved.

In the terminal I get the following error `illegal hardware instruction ./Open3D`.

**Comment by prewettg** [comment]
I just checked this, it seems to work in `master` on 10.14. I'm closing as not reproducible, but please re-open if it still is a problem.
