### ISSUE TITLE
Brief instruction\explanation about the CUDA (GPU) module required

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2595]
Hello, 

Really hope that we can see some instructions\explanations about the CUDA (GPU) module. Maybe just a few more lines? Which parts of v0.11.1 can be accelerated by GPU? How much acceleration can be expected and how to enable the GPU acceleration? 

Yesterday I have just built the Open3D with CUDA module enabled on Windows 10. Everything seems OK with CUDA 10.1 and VS2019. But how can I know which part is running on GPU which part is running on CPU. 

Running some my old Open3D C++ test code with the newly CUDA module enabled build,  it seems no any performance improvement comparing with before, or even something went slower.  For example the 20000 points pcd->OrientNormalsConsistentTangentPlane(10) operation, before it is something 350 ms, now it is 640 ms. 

Thank you!

**Comment by sanskar107** [comment]
We are actively working on CUDA support on most of the modules. Currently only some utilities(hashmap, solvers, reduction, etc ) are accelerated. Full pipeline acceleration will be supported in future release.
