### ISSUE TITLE
Pointcloud convert to RGBD image

### ISSUE THREAD

**Issue by SwagJ** [intel-isl/Open3D#2596]
**Is your feature request related to a problem? Please describe.**
Dear all, 
My task is like the following:
1. Performs rgbd image to 3d pointcloud, with camera intrinsic and pose.
2. Process transformation on generated 3d pointcloud. 
3. get rgbd image from transformed 3d pointclouds, with the same camera intrinsic and pose.

**Describe the solution you'd like**
For 1 and 2, there are available build in open3d. 
But for 3, I didn't find such function api. Is there any?
If not, what might be the best solution?

Thank you very much. 

Best,

**Comment by prewettg** [comment]
We do not have an API for this, however you can do the following:
1) create a scene, add your point cloud, then setup the camera
2) render to an image to get the RGB values (open3d.geometry.Image)
3) render to a depth image to get the depth values (in [0, 1], where 0 is the near plane and 1 is the far plane). You may need to convert the depth value to whatever your RGBD format requires
4) combine the RGB and D images and save.

You may find the `examples/python/gui/render-to-image.py` example helpful. `render_to_image` is in 0.12, but just this week we added `render_to_depth_image`, so you will need to build from source or wait for 0.13. You may also find the `examples/python/gui/mouse-and-point-coord.py` example in #3192 (should be merged in a few days) helpful if you need to convert from depth to world coordinates.

**Comment by hjy94wo777** [comment]
Hi, do you find a way to convert the point clouds into rgbd?

**Comment by saurabheights** [comment]
https://stackoverflow.com/questions/77633300/projection-issue-in-open3d-cpp/77636025
