### ISSUE TITLE
add "IntrinsicCamera" support in "open3d.visualization.rendering"

### ISSUE THREAD

**Issue by kaixin-bai** [intel-isl/Open3D#2602]
please add IntrinsicCamera model in rendering, sothat the rendered depth image can be totally the same as the real depth intrinsic camera. (￣ε(#￣)☆

**Comment by prewettg** [comment]
This was added for 0.12. `open3d.visualization.rendering.Camera` has a `set_projection` method that takes an intrinsic matrix, and near, far, view width, view height as its parameters. You will need to be using the new GUI, and you can get the camera from the `open3d.visualization.rendering.Open3DScene` object with the `camera` property.
