### ISSUE TITLE
Example code for ML visualizer

### ISSUE THREAD

**Issue by hduonggithub** [intel-isl/Open3D#2603]
Hi All,

I am working on Open3D new GUI from vis-gui.py and all-widgets.py. I do see that there is another GUI based Viewer/Visualizer (see the picture) in ML which is very closed to what I am doing.

I am wondering if we have this code somewhere in your github?
![image](https://user-images.githubusercontent.com/11492480/98828686-fdff5800-23fd-11eb-835b-f518a4bd0fc7.png)

**Comment by prewettg** [comment]
Yes, the code is available in the Open3D-ML repository, in the ml3d/vis directory. Most of the code is in [visualizer.py](https://github.com/intel-isl/Open3D-ML/blob/master/ml3d/vis/visualizer.py). See also the [visualize.py example](https://github.com/intel-isl/Open3D-ML/blob/master/examples/visualize.py) for how to call it. The visualizer is available in `open3d.ml.vis.Visualizer` if you would like to use it directly.

**Comment by hduonggithub** [comment]
Thanks for your prompt answer @prewettg !
