### ISSUE TITLE
Reconstruction Multiscale ICP throwing an error with args that use to work.

### ISSUE THREAD

**Issue by FLS-BP-US** [intel-isl/Open3D#2608]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Was there a change to the registration_colored_icp function args in 0.11.2?

**Expected behavior**
Registration use to work with 0.11.0

**Screenshots**
![image](https://user-images.githubusercontent.com/18273358/98956405-39149080-24bd-11eb-8647-6fa59415381b.png)

**Environment:**
- Operating system: Windows 10 64-bit
- Python version: 3.8
- Open3D version: 0.11.2
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by theNded** [comment]
Did you upgrade your github repo as well?

**Comment by theNded** [comment]
Should be fixed by synchronizing the pip installed open3d and the source code. Closed for now.
