### ISSUE TITLE
Please consider to add "deintegrate" functionality to Volume class

### ISSUE THREAD

**Issue by lombardm** [intel-isl/Open3D#2613]
I am a huge fan of your library. Currently I am working with the pipeline.integration class. Personally, I think it could be very nice to have the symmetric version of the "integrate" function, therefore a "deintegrate" that is able to remove from the current volume some previously integrated data at a specific position. Indeed, as stated in "BundleFusion" paper from 2017, the TSDF is symmetric, so it is possible to go backward. This is particularly helpful in a pipeline such as the one of BundleFusion, where newly optimized poses can be used to update the model in online fashion. 
Thanks in advance,
Marco

**Comment by theNded** [comment]
We will be providing a new design of TSDF volumes in the next release. Please stay tuned!

**Comment by lombardm** [comment]
Thanks! 
Then I will close this request for the moment :)

**Comment by martinakos** [comment]
Is this "deintegrate" functionality is already available within the VoxelBlockGrid?
