### ISSUE TITLE
Default normal value [0, 0, 1] ?

### ISSUE THREAD

**Issue by nachovizzo** [intel-isl/Open3D#2622]
Is there any reason to use `Eigen::Vector3d(0.0, 0.0, 1.0)` instead of `Eigen::Vector3d::Zero()` when the normal compution goes wrong?

https://github.com/intel-isl/Open3D/blob/7f3080b53bce7c7d9cb30e41dc1b92258b4324ab/cpp/open3d/geometry/EstimateNormals.cpp#L341

**Comment by theNded** [comment]
I think normals have to be with norm 1, they are basically on a sphere. The selection of the axis is random though.
