### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by thinker696** [intel-isl/Open3D#2627]
Is there a function that can convert multiple pictures from different angles into 3D?

**Comment by NomitRwt** [comment]
Depth images are supported. For rgb images you can try [here.](https://github.com/openMVG/awesome_3DReconstruction_list#opensource-sfm-structure-from-motion)

**Comment by theNded** [comment]
This is out of the scope of Open3D. Please refer to Colmap or other SfM tools.
