### ISSUE TITLE
Build filament from source on Windows faild  -- is  looking for Linux stuff  

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2628]
Hello,

I was trying to build Open3D on Windows 10 with BUILD_FILAMENT_FROM_SOURCE option selected. It was failed because the compiler was trying to look for Linux stuff.    Might need to add WIN32 flag in somewhere on CMakeLists.txt?

I'm using Visual Studio 2019,  Open3D v0.11.2

Thank you!

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'sys/time.h': No such file or directory [D:\git\Open3D\build_debug\filament\src\ext_filament-build\third_party\astcenc\tnt\astcenc.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\third_party\astcenc\Source\astc_toplevel.cpp	26	
Error	MSB8066	Custom build for 'D:\git\Open3D\build_debug\CMakeFiles\7cc2c6a422e22b918ac0247bb49deee5\ext_filament-mkdir.rule;D:\git\Open3D\build_debug\CMakeFiles\7cc2c6a422e22b918ac0247bb49deee5\ext_filament-download.rule;D:\git\Open3D\build_debug\CMakeFiles\7cc2c6a422e22b918ac0247bb49deee5\ext_filament-update.rule;D:\git\Open3D\build_debug\CMakeFiles\7cc2c6a422e22b918ac0247bb49deee5\ext_filament-patch.rule;D:\git\Open3D\build_debug\CMakeFiles\7cc2c6a422e22b918ac0247bb49deee5\ext_filament-configure.rule;D:\git\Open3D\build_debug\CMakeFiles\7cc2c6a422e22b918ac0247bb49deee5\ext_filament-build.rule;D:\git\Open3D\build_debug\CMakeFiles\7cc2c6a422e22b918ac0247bb49deee5\ext_filament-install.rule;D:\git\Open3D\build_debug\CMakeFiles\289bcf7be02eeb63d717475a99ab24e9\ext_filament-complete.rule;D:\git\Open3D\build_debug\CMakeFiles\6885f1eee1e42c7ba44898b405f62a14\ext_filament.rule' exited with code 1.	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	238	
Error	C3861	'_close': identifier not found [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\src\ashmem.cpp	160	
Error	C3861	'posix_memalign': identifier not found [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\include\utils\memalign.h	45	
Error	C3861	'posix_memalign': identifier not found [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\include\utils\memalign.h	45	
Error	C3861	'posix_memalign': identifier not found [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\include\utils\memalign.h	45	
Error	C3861	'_chsize': identifier not found [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\src\ashmem.cpp	159	
Error	C3861	'_open': identifier not found [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\src\ashmem.cpp	156	
Error	C3861	'_mktemp': identifier not found [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\src\ashmem.cpp	155	
Error	C3861	'GetCurrentProcessId': identifier not found [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\src\ashmem.cpp	154	
Error	C2065	'_O_BINARY': undeclared identifier [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\src\ashmem.cpp	156	
Error	C2039	'posix_memalign': is not a member of '`global namespace'' [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\include\utils\memalign.h	45	
Error	C2039	'posix_memalign': is not a member of '`global namespace'' [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\include\utils\memalign.h	45	
Error	C2039	'posix_memalign': is not a member of '`global namespace'' [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\include\utils\memalign.h	45	
Error	C1083	Cannot open include file: 'unistd.h': No such file or directory [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\src\Profiler.cpp	23	
Error	C1083	Cannot open include file: 'dlfcn.h': No such file or directory [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\bluegl\test_bluegl.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\bluegl\tests\OpenGLSupport.cpp	33	
Error	C1083	Cannot open include file: 'execinfo.h': No such file or directory [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\src\CallStack.cpp	27	
Error	C1083	Cannot open include file: 'pthread.h': No such file or directory [D:\git\Open3D\build_debug\filament\src\ext_filament-build\libs\utils\utils.vcxproj]	ext_filament (ExternalProjectTargets\ext_filament\ext_filament)	D:\git\Open3D\build_debug\filament\src\ext_filament\libs\utils\src\JobSystem.cpp	35	
`

**Comment by Rebornown** [comment]
I had the same problem MSB8066,what is the reason

**Comment by xuanchibkd14** [comment]
i had the same problem MSB8066, i tried google to fix it, but i can't sloved
