### ISSUE TITLE
FPFH feature

### ISSUE THREAD

**Issue by adimesika1** [intel-isl/Open3D#2633]
Hi 
I would like to know why the FPFH feature returns 33-dimensional vector.
I have read Rusu's paper https://www.cvl.iis.u-tokyo.ac.jp/class2017/2017w/papers/5.3DdataProcessing/Rusu_FPFH_ICRA2009.pdf 
and still have no idea which features return.

Thanks to all

**Comment by theNded** [comment]
Please check the tutorials by the original author: https://pcl.readthedocs.io/projects/tutorials/en/latest/#features, especially section PFH and FPFH. Ours is a reimplementation of his work.

**Comment by FeliceSfravara** [comment]
Sorry, but I don't understand why the Feature extraction has a 33 dimensional vector. I read the paper and the paper of Ruse et al. shows the four features used. I can't understand the return of the function in Open3D. I expected for each point a number of bins equal to: d^4 (with d the division of the ranges of the features). I can't understand why 33. Please Can you explain it? I'd like to plot the histogram like in the paper. 
If you have suggestions and more explanation it could be very useful. 
Thank you
