### ISSUE TITLE
Different frame numbers extracted from MKV files captured from multiple synchronized Kinects

### ISSUE THREAD

**Issue by AstitvaSri** [intel-isl/Open3D#2639]
When I try to extract RGBD frames captured from multiple synchronous Azure Kinects, I see different number of frames for each of the MKVs. 
For synchronized capture, I have used Azure SDK to get MKV files for all Kinects. I am trying to read frames using azure_kinect_mkv_reader.py

To Reproduce
1.  python examples/python/ReconstructionSystem/sensors/azure_kinect_mkv_reader.py --input master.mkv
     python examples/python/ReconstructionSystem/sensors/azure_kinect_mkv_reader.py --input slave.mkv
I have recorded for 15 sec at 30FPS but got 536 frames for master and 519 frames for slave.

Operating system: Ubuntu 18.04
- Python version: (e.g. Python 3.6)
- Open3D version: 0.10.0
- Is this remote workstation?: no
- How did you install Open3D?: Conda

How do I get away the problem?

**Comment by ssheorey** [comment]
Can you open the files with [k4aviewer](https://docs.microsoft.com/en-us/azure/kinect-dk/azure-kinect-viewer) or `ffmpeg`? How many frames does it report?
eg: `ffmpeg -i input.mkv -map 0:v:0 -c copy -f null -`
See `frame=` entry at the end of the output.

**Comment by AstitvaSri** [comment]
Thanks for the suggestion. 
Frame numbers are different for master and slave when done with ffmpeg.

**Comment by ssheorey** [comment]
This looks like an issue with the Kinect device or Kinect settings. Closing this issue.
