### ISSUE TITLE
Does open3D support  menu in transparent style ?  

### ISSUE THREAD

**Issue by JianqiangDing** [intel-isl/Open3D#2642]
I know ImGui support setting menu in transparent color, does this feature supported in Open3D?  if supported，cloud you please provide related APIs?

**Comment by prewettg** [comment]
Transparent menus are not supported in Open3D at this time. Unfortunately, even though this is probably a fairly easy change, we have a lot of higher priority items for the next the release, so we aren't going to have time to add it ourselves. We would definitely consider accepting a pull request, though.

My initial thinking would be to add a gui::Menu::SetAlpha() and gui::Menu::GetAlpha(), with the documentation that it is only used if the object is the top-level menu object (i.e. the Menu that is assigned with Application::SetMenuBar()). If you do create a PR, please remember to add Python bindings, see `cpp/pybind/visualization/gui/gui.cpp`. (You can build the Python package with `make pip-package`, which creates a wheel in `lib/python_package/pip_package`)

**Comment by JianqiangDing** [comment]
thanks for your reply, I'll consider what you said, you may close the issue now
