### ISSUE TITLE
Azure Kinect not included in windows build since 0.11.0

### ISSUE THREAD

**Issue by okitu** [intel-isl/Open3D#2644]
_____

Since version 0.11.0 Azure Kinect is not included in the Windows 10 64 build/wheel
I can run the azure kinect examples on 0.8.0 - 0.10.0, but in 0.11.0 the azure kinect is not included in the api. When i try to run the viewer example i get the following error:

*AttributeError: module 'open3d.cpu.pybind.io' has no attribute 'AzureKinectSensorConfig'*

**To Reproduce**

Execute the following commands:

1. git clone https://github.com/intel-isl/Open3D.git
2. cd Open3D
3. git checkout tags/v0.11.0
4. pip install open3d==0.11.0
4.1 pip uninstall numpy (https://github.com/numpy/numpy/issues/17726)
4.2 pip install numpy==11.9.3
5. python examples\python\reconstruction_system\sensors\azure_kinect_viewer.py --align_depth_to_color
6. Error occurs (see Screenshot).

**Expected behavior**
The viewer app should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/619708/99690559-934abe00-2a88-11eb-9f0c-e91e67b36883.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7.9
- Open3D version: 0.11.0+
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by Fred3D-tech** [comment]
same problem...
