### ISSUE TITLE
question about convert open3d pointcloud into numpy

### ISSUE THREAD

**Issue by CrazyPopLin** [intel-isl/Open3D#2649]
Hi, thanks for contribute to this awesome project. 

I am trying to plot the point cloud with xyz metric.  And the code is following:
```python
#!/usr/bin/python3

import open3d as o3d
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

### read pcd
pcd = o3d.io.read_point_cloud("/home/lin/develop/ros/soslab_ws/src/sidescan_slam/data/saved/test.pcd")
arr = np.asarray(pcd.points)
### python plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(arr[:,0], arr[:,1], arr[:,2], c='red', s=0.01)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
plt.show()

### Visual in open3d Viewer
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(pcd)
o3d.visualization.ViewControl.set_zoom(vis.get_view_control(), 0.8)
vis.run()
```

**My question is**:  Am I using the right code to convert the pointcloud into numpy array? The first plot is visualization from open3d. It looks right and flat(may have some height difference in color), second one is from pyplot. The plot is **twisty** in Z axix. Thanks for your help.
![viewer](https://user-images.githubusercontent.com/11235093/99840210-209a1b00-2b3a-11eb-83d3-de492c76d950.png)
![pyplot](https://user-images.githubusercontent.com/11235093/99840225-2859bf80-2b3a-11eb-8a14-49057755aeb5.png)

**Comment by yxlao** [comment]
`arr = np.asarray(pcd.points)` looks coorect to me

**Comment by CrazyPopLin** [comment]
Found my issue. My plot just not set same scale ratio to X,Y,Z axis.
