### ISSUE TITLE
Different color in colorEdit widget and main window 

### ISSUE THREAD

**Issue by JianqiangDing** [intel-isl/Open3D#2653]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
different color in colorEdit widget and main window

**To Reproduce**

python3 examples/python/gui/vis-gui.py

**Expected behavior**
same color in colorEdit widget and main window

**Screenshots**
![image](https://user-images.githubusercontent.com/7833870/99925902-cc31ae00-2d7a-11eb-9bf0-1a208cff2fa0.png)

**Environment (please complete the following information):**

- Operating system: (Linux Mint 20 Cinnamon 64-bit)
- Python version: (ePython 3.8.5)
- Open3D version: 0.11.2
- Is this remote workstation?: no
- How did you install Open3D?: ( pip3)

**Additional context**

**Comment by prewettg** [comment]
Filament does color-mapping, which affects the color of the background. I tried on macOS and Linux using the latest from `master` and it looks like this is fixed now.
