### ISSUE TITLE
'open3d' has no attribute 'open3d_pybind'

### ISSUE THREAD

**Issue by vajrag** [intel-isl/Open3D#2668]
I was using open3d to get a point cloud from the RGBD image. I don't remember which version of open3d supported this function. Can anybody help in pointing out the open3d version which supports this?

` image = open3d.open3d_pybind.geometry.Image(img)`

 `depth_scaled = open3d.open3d_pybind.geometry.Image(depth_scaled)`

ERROR:
`module 'open3d' has no attribute 'open3d_pybind'`

 

**Environment information :**

- Operating system: Ubuntu 18.04
- Python version:  Python 3.6)
- Open3D version: 0.11.2
- Is this remote workstation?: no
- How did you install Open3D?:  conda,

Thanks

**Comment by cartacamilla** [comment]
I have the same problem, would you please post your solution (I assume that you found something as you closed your issue)?
