### ISSUE TITLE
Build open3D jetson nano issues

### ISSUE THREAD

**Issue by readblack1234** [intel-isl/Open3D#2669]
Build related issues  on jetson nano issues

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04 - aarch64
- Python version: (e.g. Python 3.6)-None, C++ install
- Open3D version:0.11.2

- How did you install Open3D?: build from source
- Compiler version (if built from source): clang 7.0, gcc 7.5

**Additional context**

While running building open3d from source, at step
cmake ..
Issue with cmake version less than 3.10,
I installed cmake VERSION 3.15
sudo snap install cmake --classic
cmake --version
https://graspingtech.com/upgrade-cmake/
(Its not an issue of other places cmake version older is required, as this is min required version)

Next at step
cmake ..
I had issue of 
-- Filament can only be built with Clang >= 7
-- Using /usr/bin/clang++-10 to build Filament
CMake Error at 3rdparty/find_dependencies.cmake:919 (find_library):
  Could not find CPP_LIBRARY using the following names: c++

I installed clang 10, since issue was with clang verion >=7 while I had 6.
https://apt.llvm.org/
Install
(old-stable branch)
To install all key packages:
steps
when I got to this step, I had issue that "libc++-7-dev libc++abi-7-dev" were already having libs causing overwrite issue "overwrite libc++abi.so.1"
apt-get install libc++-10-dev libc++abi-10-dev

I had mistakely tried from remove manually libc++.so related 5 files (symbolic links) which resulted in a lot of issues and I had to follow this link to resolve 
https://linuxhint.com/apt_get_fix_missing_broken_packages/
Only Method 2 worked!

After that I went to following official link to install pre-requiste dependencies- 
!!!!!!!!!!             **I would suggest only this link as starting point** !!!!!!!!!!!!!!!!

http://www.open3d.org/docs/release/arm.html

option(BUILD_CUDA_MODULE          "Build the CUDA module"                    OFF)

Did not change this:
option(GLIBCXX_USE_CXX11_ABI      "Set -D_GLIBCXX_USE_CXX11_ABI=1"           OFF)
option(WITH_OPENMP                "Use OpenMP multi-threading"               ON )

Now when

```
cmake ..

-- THIRD_PARTY_DOWNLOAD_DIR is not specified, will download directly.
-- No CMAKE_BUILD_TYPE specified, default to RelWithDebInfo
CMake Deprecation Warning at CMakeLists.txt:95 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Open3D 0.11.2+49d7fc2b
CMake Warning at CMakeLists.txt:182 (message):
  ARM CPU detected, setting USE_BLAS=ON.


-- Using python from PATH: /usr/bin/python
-- Performing Test HAS_GLIBCXX_USE_CXX11_ABI
-- Performing Test HAS_GLIBCXX_USE_CXX11_ABI - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Building library Assimp from source
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Building with OpenMP
-- Building library 3rdparty_eigen3 from source
-- Building library 3rdparty_flann from source
-- Building library 3rdparty_nanoflann from source
-- Building library 3rdparty_glew from source
-- Building library 3rdparty_glfw3 from source
-- Found Vulkan: /usr/lib/aarch64-linux-gnu/libvulkan.so  
-- Using X11 for window creation
-- Found X11: /usr/include   
-- Building third-party library JPEG from source
-- Looking for a ASM_NASM compiler
-- Looking for a ASM_NASM compiler - NOTFOUND
-- NASM assembler not found - libjpeg-turbo performance may suffer
-- libturbojpeg: WITH_CRT_DLL=OFF
-- Building library 3rdparty_jsoncpp from source
-- Building library 3rdparty_lzf from source
-- Building library 3rdparty_tritriintersect from source
-- Building third-party library zlib from source
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Building third-party library libpng from source
-- Building library 3rdparty_rply from source
-- Building library 3rdparty_tinyfiledialogs from source
-- Building library 3rdparty_tinygltf from source
-- Building library 3rdparty_tinyobjloader from source
-- Building library 3rdparty_qhull_r from source
-- Building library 3rdparty_qhullcpp from source
-- Building library 3rdparty_fmt from source
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython2.7.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.0
-- Building library 3rdparty_poisson from source
-- Found OpenGL: /usr/lib/aarch64-linux-gnu/libOpenGL.so   
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/aarch64-linux-gnu/libblas.so  
-- Looking for cheev_
-- Looking for cheev_ - not found
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found LAPACK: /usr/lib/aarch64-linux-gnu/liblapack.so;/usr/lib/aarch64-linux-gnu/libblas.so  
-- A cache variable, namely LAPACKE_DIR, has been set to specify the install directory of LAPACKE
-- Looking for LAPACKE_dgeqrf
-- Looking for LAPACKE_dgeqrf - not found
-- Looking for lapacke : test with lapack fails
-- Looking for LAPACKE_dgeqrf
-- Looking for LAPACKE_dgeqrf - found
-- Found LAPACKE: /usr/lib/aarch64-linux-gnu/liblapacke.so  
-- Using system BLAS/LAPACK
-- Building third-party library faiss from source
-- FAISS_INCLUDE_DIR: /home/user/open3d/Open3D/build/mkl_install/include/
-- FAISS_LIB_DIR: /home/user/open3d/Open3D/build/mkl_install/lib
-- BUILD_JUPYTER_EXTENSION is set to OFF
-- Using Python version: 2.7
-- Using Python version major: 2
-- PYPI_PACKAGE_NAME: open3d
-- ========================================================================
-- Open3D 0.11.2 Configuration Summary
-- ========================================================================
-- Enabled Features:
--   OpenMP .................................. ON
--   Headless Rendering ...................... OFF
--   Azure Kinect Support .................... OFF
--   CUDA Support ............................ OFF
--   Build GUI ............................... OFF
--   Build Shared Library .................... OFF
--   Build Unit Tests ........................ OFF
--   Build Examples .......................... 
--   Build Python Module ..................... ON
--   - with Jupyter Notebook Support ......... OFF
--   Build TensorFlow Ops .................... OFF
--   Build PyTorch Ops ....................... OFF
--   Build Benchmarks ........................ OFF
--   Bundle Open3D-ML ........................ OFF
--   Build RPC interface ..................... OFF
--   Force GLIBCXX_USE_CXX11_ABI= ............ 0
-- ========================================================================
-- Third-Party Dependencies:
--   EIGEN3 .................................. yes (build from source)
--   FAISS ................................... yes (build from source)
--   FILAMENT ................................ no
--   FLANN ................................... yes (build from source)
--   FMT ..................................... yes (build from source)
--   GLEW .................................... yes (build from source)
--   GLFW .................................... yes (build from source)
--   GOOGLETEST .............................. no
--   IMGUI ................................... no
--   JPEG .................................... yes (build from source)
--   JSONCPP ................................. yes (build from source)
--   LIBLZF .................................. yes (build from source)
--   OPENGL .................................. yes (build from source)
--   PNG ..................................... yes (build from source)
--   PYBIND11 ................................ yes (build from source)
--   QHULL ................................... yes (build from source)
--   LIBREALSENSE ............................ no
--   TINYFILEDIALOGS ......................... yes (build from source)
--   TINYGLTF ................................ yes (build from source)
--   TINYOBJLOADER ........................... yes (build from source)
-- ========================================================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/open3d/Open3D/build
```
Issue is resolved and its building now!

**Comment by yxlao** [comment]
Glad that the issue has been resolved. 

For future reference, we need additional dependencies for ARM64: http://www.open3d.org/docs/release/arm.html#install-dependencies .

**Comment by andrew-ampersand** [comment]
I am working to install Open3D now on my Jetson Nano. I get a similar error on cmake: 

-- Filament can only be built with Clang >= 7
-- Using /usr/local/clang_9.0.0/bin/clang++ to build Filament
CMake Error at 3rdparty/find_dependencies.cmake:941 (find_library):
  Could not find CPP_LIBRARY using the following names: c++
Call Stack (most recent call first):
  CMakeLists.txt:533 (include)


I have clang_9.0.0 that I have built from source. Could you clarify what steps you took to get around this issue? I went to the link you provided (https://apt.llvm.org/), and read the steps to install (old-stable branch) all key packages. When I ran the install commands I got errors:

$ sudo apt-get install libc++-10-dev libc++abi-10-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libc++-10-dev
E: Couldn't find any package by regex 'libc++-10-dev'
E: Unable to locate package libc++abi-10-dev
E: Couldn't find any package by regex 'libc++abi-10-dev'


I went back to check my dependencies, as yxlao said, and it failed on:
$ sudo apt-get install -y apt-utils build-essential git cmake
The following packages have unmet dependencies:
 apt-utils : Depends: apt (= 1.6.1) but 1.6.12ubuntu0.1 is to be installed
 cmake : Depends: cmake-data (= 3.10.2-1ubuntu2) but 3.10.2-1ubuntu2.18.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

And
$ sudo apt-get install -y libsdl2-dev libc++-7-dev libc++abi-7-dev libxi-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libc++-7-dev
E: Couldn't find any package by regex 'libc++-7-dev'
E: Unable to locate package libc++abi-7-dev
E: Couldn't find any package by regex 'libc++abi-7-dev'

**Comment by AncientRemember** [comment]
`# Find corresponding libc++ and libc++abi libraries. On Ubuntu, clang
        # libraries are located at /usr/lib/llvm-{version}/lib, and the default
        # version will have a sybolic link at /usr/lib/x86_64-linux-gnu/ or
        # /usr/lib/aarch64-linux-gnu.
        # For aarch64, the symbolic link path may not work for CMake's
        # find_library. Therefore, when compiling Filament from source, we
        # explicitly find the corresponidng path based on the clang version.
        execute_process(COMMAND ${FILAMENT_CXX_COMPILER} --version OUTPUT_VARIABLE clang_version)
        if(clang_version MATCHES "clang version ([0-9]+)")
            set(CLANG_LIBDIR "/usr/lib/llvm-${CMAKE_MATCH_1}/lib")
        endif()`
the above code is not always excuted,but find_library(CPP_LIBRARY    c++    PATHS ${CLANG_LIBDIR} REQUIRED NO_DEFAULT_PATH) is always excuted on unix platform,so move the above code outeside the if block will resove the issue
