### ISSUE TITLE
How can i get the ply data 

### ISSUE THREAD

**Issue by BiaoBiaoLi** [intel-isl/Open3D#2672]
hi, thanks your work. I down load the dataset  in http://redwood-data.org/indoor/dataset.html
and i utilize this code below to get ply data
        pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
            rgbd_image,
            o3d.camera.PinholeCameraIntrinsic(
            o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault))
        pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])

but I cannot get the correct transformation like this in  traj.txt, even if i get the successful registration.
Is it because I used the wrong parameters ( o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault ) ?
Or is there a converted point cloud file?
thanks!

**Comment by theNded** [comment]
1. You need to run the reconstruction system to obtain the camera poses: https://github.com/intel-isl/Open3D/tree/master/examples/python/reconstruction_system. There will be a final output `trajectory.log`.
2. Open3D now does not fully reproduce results in the aforementioned dataset due to the unimplemented non-rigid transform.
3. The flip transform you used was only for visualization. Please do not use it in state estimation.

**Comment by BiaoBiaoLi** [comment]
thanks, is the code of reconstruction_system only use the pictures ?
Is the multiway_registration.ipynb in :https://github.com/intel-isl/Open3D/blob/master/examples/python/pipelines/multiway_registration.ipynb. have any connection with reconstruction_system ？

**Comment by theNded** [comment]
It uses RGB-D images as the input. They both use pose graph optimization with loop closure pruning, aka multiway registration.
Please refer to docs for further information: http://www.open3d.org/docs/release/tutorial/reconstruction_system/index.html

**Comment by BiaoBiaoLi** [comment]
thank you very much, I haven't studied this before.
As for reconstruction，is  the camera poses trajectory.log  used for pairwise registration as initialization ?

**Comment by theNded** [comment]
`trajectory.log` is the **OUTPUT** of the reconstruction system based on pairwise registration and multiway registration. **PLEASE** read the doc.

**Comment by BiaoBiaoLi** [comment]
ok, thank you very much
