### ISSUE TITLE
Query for multiple points in Octree

### ISSUE THREAD

**Issue by Sterris** [intel-isl/Open3D#2681]
**Is your feature request related to a problem? Please describe.**
Is it possible to access points inside a leaf node directly?

**Describe the solution you'd like**
A method returning points (either indices or coordinates) belonging to a leaf node. 
i.e: given leaf node N-> return np.array([3,1], [3,1], ...)

**Describe alternatives you've considered**
Possible alternative could be quering all points in the respective point cloud thus proving link between point and leafnode, using the method locate_leaf_node(from Octree), but to slow on larger point clouds. 

Another approach is to traverse the tree, when reaching a leaf node get coordinates then filtering point cloud based on these coordinates. But unable to acess coordinates of leafNodes when traversing, as it returns ->OctreeColorLeafNode with color [0, 0, 0]

**A clear and concise description of any alternative solutions or features you've considered.**
Simply using VoxelGrid instead, where I can query on a list of points.

I might just have overlooked the method or I am blind, but can not seem to find a meaningful way to get the list of points belonging to a leaf node.

Thanks.
/j

**Comment by plusk01** [comment]
see #1178
