### ISSUE TITLE
find RGBD frames belongs to each point in the point clouds

### ISSUE THREAD

**Issue by hosseinshirali** [intel-isl/Open3D#2699]
Hi, i use the reconstruction-system to create point clouds of some objects from a sequence of RGBD frames
then I create a 3d bounding box on an object of my point clouds so now I have some points with coordinates
i want to know that how can I find the related RGB frames to each point (my object)?
i mean if i select a 3d point on my final point clouds how can i find this point belongs to which RGB frames?
is there any function to do that?
i appreciate any hint 
thanks

**Comment by sanskar107** [comment]
I don't think this is possible right now.

**Comment by hosseinshirali** [comment]
@syncle can you also tell me is it possible or not? my project depends on this part so I need to do that
I would be grateful if you could give me some idea to solve my problem
thanks
