### ISSUE TITLE
reconstruct surface with triangle mesh in python

### ISSUE THREAD

**Issue by rarilurelo** [intel-isl/Open3D#270]
I'd like to reconstruct surfaces of point cloud `.pcd` file and convert it to mesh `.ply` file.

```
import argparse
from py3d import *
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--file', type=str)
    args = parser.parse_args()
    pcd = read_point_cloud(args.file)
    draw_geometries([pcd])
    mesh = TriangleMesh()
    mesh.vertices = pcd.points
    mesh.triangles = triangle_mesh_surface(pcd.points)
    draw_geometries([mesh])
    write_triangle_mesh('out.ply', mesh)
```

Is there any function like `triangle_mesh_surface()` in Open3D?

**Comment by syncle** [comment]
Nope. We don't have meshing algorithm from raw point cloud yet. I think good candidate is [poisson surface reconstruction](https://github.com/mkazhdan/PoissonRecon), or you can suggest any. We can consider as a next milestone.

As a side note, We do have an implementation for mesh from TSDF volume. [Check out this link.](http://open3d.org/docs/tutorial/Advanced/rgbd_integration.html)

**Comment by griegler** [comment]
There is now a BPA implementation for surface reconstruction in Open3D, #1130.
