### ISSUE TITLE
ReconstructionSystem integration  is killed

### ISSUE THREAD

**Issue by BiaoBiaoLi** [intel-isl/Open3D#2700]
Thanks your work. 
1. why i use the python run_system.py --integrate ./config/our_test/office2-simulated.json, it would be killed like below ?
![image](https://user-images.githubusercontent.com/44672683/101062945-347b5d80-35cd-11eb-8f4b-2de8cc6b0fe8.png)
2. and i also want to know if the fragments is produced by the config file in https://github.com/intel-isl/Open3D/tree/master/examples/python/reconstruction_system/config/redwood_simulated ? 
3. how to evaluate several reconstruction methods with  ATE ?
Thanks !

**Comment by BiaoBiaoLi** [comment]
The first problem is due to out of memory, i want to ask the other question,thanks

**Comment by theNded** [comment]
1. Memory issue should have been fixed, see discussions in #2107. Please update to the latest Open3D.
2. You get fragments by what you feed in the reconstruction system. You feed in office2-simulated, you get office2-simulated.
3. For ATE computation, one reference is https://github.com/MichaelGrupp/evo. You will have to first convert 4x4 matrices to quaternion+translation format. http://kieranwynn.github.io/pyquaternion/ is a useful tool for the task.
