### ISSUE TITLE
ImGUI application 

### ISSUE THREAD

**Issue by bumbastic** [intel-isl/Open3D#2705]
I would like to build a GUI application with multiple visualizers in the same form. e.g. 1..n RGBDImages with live input from sensors and 1..n editable pointclouds, together with ImGui buttons, sliders, graphs, etc.

Is this possible? If it is. Where would I start?

**Comment by Zumbalamambo** [comment]
+1

**Comment by yxlao** [comment]
Yes, it is possible. @ssheorey is working on an RGBD recorder example with RealSense camera and ImGUI-based visualizer:
https://github.com/intel-isl/Open3D/pull/2646/files#diff-92dc7e0af058a36a9f5118411b6b7d1cf31536e43d9f4331a02937b5108c2e87 . Other RGBD sensors could follow the same idea.
