### ISSUE TITLE
draw_geometries() takes forever to show scene with a only few simple meshes

### ISSUE THREAD

**Issue by ssavary** [intel-isl/Open3D#2706]
I'm using open3d 0.11.0 (see #2643 as for why I'm not using the latest).

Visualization is slow to setup. Here's a working example of the issue. It takes almost 30 seconds to setup and display a scene with 40 random boxes. Using 60 meshes doubles to 1 minute.

Once the window is shown, rendering speed seems fine though.

I'm seeing the same behaviour with open3d 0.10.0. I couldn't test with 0.9.0, as it does not work anymore on my OS version.

```
import numpy as np
import open3d as o3d
from open3d import visualization
boxes = []
for i in range(40):
    mesh = o3d.geometry.TriangleMesh.create_box()
    mesh.scale(np.random.rand(), np.zeros((3,1)))
    mesh.translate(np.random.randn(3,1)*10)
    boxes.append(mesh)
visualization.draw_geometries(boxes)
```

- Operating system: OSX 10.14.6
- Python version: 3.7.7
- Open3D version: 0.11.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by prewettg** [comment]
This is fixed in 0.11.2, with #2523. Regarding 2643 for why you are not using the 0.11.2, since you are not using the new GUI, if you build passing `-DBUILD_GUI=OFF` to cmake it should fix the crash.
