### ISSUE TITLE
Open3d Viewer is not found

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#2707]
I have installed the open3d viewer in Ubuntu 20.0.4. It is nowhere to be found after installation. How do I open it? where is it installed?

**Comment by yxlao** [comment]
It can be found in the 1) build directory and the 2) installation directory.

E.g.
```bash
mkdir build && cd build

# We configure the install path to be `~/open3d_install`.
cmake -DCMAKE_INSTALL_PREFIX=~/open3d_install ..

# The viewer will be located at: ../build/bin/Open3D/Open3D
make -j

# The installed viewer will be located at:
# ~/open3d_install/bin/Open3D/Open3D
# The Ubuntu desktop files will be located at
# $HOME/.local/share/applications/Open3D.desktop
# $HOME/.local/share/icons/hicolor/scalable/apps/Open3D.svg
# $HOME/.local/share/mime/packages/Open3D.xml
make install
```

**Comment by littlesaohuo** [comment]
> It can be found in the 1) build directory and the 2) installation directory.
> 
> E.g.
> 
> ```shell
> mkdir build && cd build
> 
> # We configure the install path to be `~/open3d_install`.
> cmake -DCMAKE_INSTALL_PREFIX=~/open3d_install ..
> 
> # The viewer will be located at: ../build/bin/Open3D/Open3D
> make -j
> 
> # The installed viewer will be located at:
> # ~/open3d_install/bin/Open3D/Open3D
> # The Ubuntu desktop files will be located at
> # $HOME/.local/share/applications/Open3D.desktop
> # $HOME/.local/share/icons/hicolor/scalable/apps/Open3D.svg
> # $HOME/.local/share/mime/packages/Open3D.xml
> make install
> ```
Dear official, I am using the ubuntu18.04 system, I installed the open3d-viewer v0.12 app, but I encountered an error when opening the app. The terminal displays:


FEngine (64 bits) created at 0x7f1150190010 (threading is enabled)
FEngine resolved backend: OpenGL
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  33
  Current serial number in output stream:  31
