### ISSUE TITLE
2D bounding box on RGB frames from 3D bounding box on point clouds

### ISSUE THREAD

**Issue by hosseinshirali** [intel-isl/Open3D#2709]
Hi, i use the reconstruction-system to create point clouds of an object from a sequence of RGBD frames
then I created a 3d bounding box on the object in the point clouds so now I have 8 points with 3d coordinates.
my question is how can I have 2d bounding box of the object on all of the RGB frames at the same coordinates of the 3d bounding box? 
my initial idea Is to project 3d bb to 2d bb but as it is clear, the position of the object is different in each frame, so I do not know how can i use this approach?
 i appreciate any help or other solution, thanks

**Comment by Zumbalamambo** [comment]
+1

**Comment by YashRunwal** [comment]
Hi, I am actually trying to do the opposite. I have 2D bounding box and the point cloud along with the depth information of the object and am trying to plot the 3D bbox in the point cloud. Can you tell me how you managed to do the opposite so that I can take some hints and apply it for my problem?

**Comment by Litao917** [comment]
> Hi, I am actually trying to do the opposite. I have 2D bounding box and the point cloud along with the depth information of the object and am trying to plot the 3D bbox in the point cloud. Can you tell me how you managed to do the opposite so that I can take some hints and apply it for my problem?

Hi Yash, 

have you solved the problem? I met the same question exactly as you. Any clue? THX in advance!
