### ISSUE TITLE
documentation C++ Test

### ISSUE THREAD

**Issue by takanokage** [intel-isl/Open3D#271]
Do we have documentation for the C++ Test?
I could use some examples on how to run the C++ test samples.

**Comment by syncle** [comment]
No we don't. We would need to make documents for C++ test. However, it should be self-explanationaly. This issue is related to #130.
What we have for now is 
- C++ test: https://github.com/IntelVCL/Open3D/tree/master/src/Test
- C++ api reference: http://open3d.org/cppapi/

**Comment by takanokage** [comment]
Yes, I agree this is related to #130. The same goes for #166, also related to #130. I've looked into unit testing and it seems common practice to coordinate it through cmake.

What I propose is that at some point in time the documentation could show both python and c++ code samples.

**Comment by takanokage** [comment]
@syncle would you like to take care of this? I don't have the information to do it.
Alternatively you can write a brief doc explaining the cmd line args to me and I'll handle the commit for you.

**Comment by syncle** [comment]
Got it. I will work on this.
