### ISSUE TITLE
Convert RGBD to colored Point Cloud (setting convert_rgb_to_intensity=False doesn't help)

### ISSUE THREAD

**Issue by czha5168** [intel-isl/Open3D#2713]
Dear all,

I'd like to use open3d to generate a coloured point cloud from RGB-D image. After few close research from my side, I have fixed a few potential problems from my side (such as setting covert_rgb_to_intensity=False and restrict the format of rgb_img to have three channels within uint8). **However, I still cannot obtain the coloured point cloud as desired.** Could you please give me some comments or kindly instructions? Much appreciated.

**My code runs as below:**
```
rgb_img = o3d.geometry.Image(rgb_img)
depth_img = o3d.geometry.Image(depth_img) 
camera_intr = o3d.camera.PinholeCameraIntrinsic(img_resolution,img_resolution,128.0,128.0,127.0,127.0)
rgbd =  o3d.geometry.RGBDImage.create_from_color_and_depth(rgb_img, depth_img, convert_rgb_to_intensity=False)        
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd, intrinsic=camera_intr)
pcd.transform([[1,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,1]])
o3d.visualization.draw_geometries([pcd], window_name='Visualizer Window', width=img_resolution, height=img_resolution)
```

**The output of print(rgbd):**
RGBDImage of size 
Color image : 256x256, with 3 channels.
Depth image : 256x256, with 1 channels.
Use numpy.asarray to access buffer data.

**The output of print(rgb_img.dtype, depth_img.dtype):**
uint8 float32

Updated: the code above could actually generate a _fake_ coloured point cloud, however, its colour encoding seems abnormal, while the raw rgb image (rgb_img) is shown appropriately and correctly.
![fake_colored_pc](https://user-images.githubusercontent.com/40653168/101339303-5842ea00-38d2-11eb-98c8-30486f3585a8.png)

**Comment by czha5168** [comment]
Update: The colors might be corrected by reshaping the rgb img and assign it to _pcd.colors_. However, the intuitive approach (above) still does not work.

**Comment by yxlao** [comment]
Could you post a visualization of the point cloud and the point cloud file?

**Comment by czha5168** [comment]
Hi yxlao, 

Thanks for your reply!

Unfortunately, I do not keep the middle results (I have solved my problems alternatively as updated above). However, the problem still exists I suppose and the corresponding incorrect point cloud visualization is added to my original question.

**Comment by BBO-repo** [comment]
I was also wondering why the point cloud form RGBD images was not colored.
I'm using the C++ api to buid point cloud from RGBD image with such piece of code:
```
void saveRGBDPointCloud(const std::string &rgb_filename, const std::string &depth_filename, const std::string &pc_filename)
{
    std::shared_ptr<open3d::geometry::Image> rgb(new open3d::geometry::Image());
    std::shared_ptr<open3d::geometry::Image> depth(new open3d::geometry::Image());

    open3d::io::ReadImage(rgb_filename, *rgb);
    open3d::io::ReadImage(depth_filename, *depth);
    std::shared_ptr<open3d::geometry::RGBDImage> rgbd = open3d::geometry::RGBDImage::CreateFromColorAndDepth(*rgb, *depth);
   
    open3d::camera::PinholeCameraIntrinsic intrinsic(
        640/*width*/,480/*height*/,
        614.6111450195312/*fx*/, 615.08447265625/*fy*/,
        320.40966796875/*cx*/,249.20108032226562/*cy*/);	

    std::shared_ptr<open3d::geometry::PointCloud> pointcloud = open3d::geometry::PointCloud::CreateFromRGBDImage(*rgbd,intrinsic);
    open3d::io::WritePointCloudOption pcOutputOption{};
    if(open3d::io::WritePointCloudToXYZRGB(pc_filename, *pointcloud, pcOutputOption))
    {
        std::cout << "Written pc file: " << pc_filename << std::endl;
    }
    
}
```
I'm visualizing it with Open3D app and also other app but it is gray.
Is there something I should add to have the point cloud colored?
