### ISSUE TITLE
3D to 2D projection

### ISSUE THREAD

**Issue by hosseinshirali** [intel-isl/Open3D#2715]
Hi, i used the reconstruction system to create point clouds from a sequence of RGBD frames
now I selected some points on point clouds and I want to project these points to my RGB frames(i just need to find the location of these 3d points in RGB frames so I think the projection from 3d to 2d will do the work)
since I am new in this field can someone explain to me how to do that? is there any script for this operation?
i appreciate any help

**Comment by Zumbalamambo** [comment]
+1

**Comment by roncapat** [comment]
OpenCV has projectPoints()

I was looking, as you, for a solution in Open3D, but I believe that using Python and the Numpy support it can be possible to use both libraries without heavy data conversions (I hope, still need to investigate...)

**Comment by hosseinshirali** [comment]
thank you @roncapat, projectPoints() solved my problem.

**Comment by roncapat** [comment]
@hosseinshirali do you mind sharing a little snippet about how you passed the point cloud managed by Open3D to OpenCV?

**Comment by hosseinshirali** [comment]
if you used the reconstruction system to create point clouds, you have already got camera parameters such as camera intrinsic, extrinsic(which is saved as trajectory file) ... so after getting the coordinate of your 3d point from your point clouds you can use projectPoint() function with these camera parameters to do projection from world frame to pixel coordinates
