### ISSUE TITLE
Draw 3D bounding box

### ISSUE THREAD

**Issue by hosseinshirali** [intel-isl/Open3D#2716]
Hello
i created point clouds by using the reconstruction system
I want to know that how can I draw a 3d bounding box on the point clouds to find and save the position of the 8 points(corners) in the world coordinate?
thanks

**Comment by prewettg** [comment]
You can use geometry.AxisAlignedBoundingBox or geometry.OrientedBoundingBox to draw bounding boxes, just pass the bounding boxes into draw_geometries() along with the point clouds. I'm not sure what you mean by "save the position", but you get_box_points() to get the 8 points defining the box.

**Comment by J1dan** [comment]
Hello, you said that to draw the boxes, _just pass the bounding boxes into draw_geometries()_, but when I o3d.visualization.draw_geometries(BBoxes), the image just goes blank. I have checked the BBoxes as 
```
for i in range (5):
    print(f"box points = {np.asarray(BBoxes[i].get_box_points())}")
```
And it returns some box points. Could you offer some help?
Thank you.

**Comment by arianme** [comment]
Hi, I hope you were able to find the solution. For future readers, the bounding boxes are white by default. So you need to either render them against a non white background, or change their `color` property to black for example.

**Comment by Petros626** [comment]
```python
center = gt_boxes[0:3]
lwh = gt_boxes[3:6]
axis_angles = np.array([0, 0, gt_boxes[6] + 1e-10])
rot = open3d.geometry.get_rotation_matrix_from_axis_angle(axis_angles)
box3d = open3d.geometry.OrientedBoundingBox(center, rot, lwh)

line_set = open3d.geometry.LineSet.create_from_oriented_bounding_box(box3d)

lines = np.asarray(line_set.lines)
line_set.lines = open3d.utility.Vector2iVector(lines)
```

**Comment by chadrs2** [comment]
But how do you click in the point cloud to get your cursor 3D points to manually draw the bounding boxes?
