### ISSUE TITLE
Reconstruction System - Integration giving bad results

### ISSUE THREAD

**Issue by sharish33** [intel-isl/Open3D#2728]
Hi Team,

I am working on 3D Object reconstruction system of small objects using Opend3D reconstruction system. I am able to build a very good fragments to cover all the views of objects but the Integration of fragments is giving very bad results. I also worked worked on few workarounds suggested in previous github issues about this but no success yet. 

Below workarounds implemented but no success.
1. I think global registration is problem here and I tried recording dataset by placing some objects around and it did not work.
2. I tried changing the ICP method  - color to Point_to_plane
3. Also adjusted the parameters in realsense.json. Below is the used Json file. tried with different values in voxel_size, max_depth_diff, max_depth, icp_method, global_registration
{
    "name": "Captured frames using Realsense",
    "path_dataset": "dataset/realsense/",
    "path_intrinsic": "dataset/realsense/camera_intrinsic.json",
    "max_depth": 1.5,
    "voxel_size": 0.01,
    "max_depth_diff": 0.007,
    "preference_loop_closure_odometry": 0.1,
    "preference_loop_closure_registration": 5.0,
    "tsdf_cubic_size": 3.0,
    "icp_method": "color",
    "global_registration": "ransac",
    "python_multi_threading": true,
    "n_frames_per_fragment" : 100
}

 Please can you suggest some method for integration or any suggested parameters to adjust in json file to resolve this issue. Any suggestion would be very helpful for us.

Below are some screen shots of fragments:

![fragment3](https://user-images.githubusercontent.com/51229156/101745185-6b6cda00-3acb-11eb-8083-5d5cfe597d6b.png)
![fragment_0](https://user-images.githubusercontent.com/51229156/101745207-6c057080-3acb-11eb-95d2-9357f475e43a.png)
![fragment_1](https://user-images.githubusercontent.com/51229156/101745214-6c9e0700-3acb-11eb-87f8-2b388ea4119a.png)
![fragment_2](https://user-images.githubusercontent.com/51229156/101745225-6d369d80-3acb-11eb-935c-4ec1904a6b4f.png)

Final Integrated Scene:
![integrated_scene](https://user-images.githubusercontent.com/51229156/101746047-a111c300-3acb-11eb-9951-a8e946bce4bd.png)

System Details:

- Operating system: Ubuntu 18.04
- Python version: Python 3.6.9(Virtual env)
- Open3D version: 0.11.2
- Is this remote workstation?: no
-  pip install open3d
 - Sensor used for recording dataset : Realsense L515 Lidar camera

Best Regards,
Harish

**Comment by Fred3D-tech** [comment]
same problem... the system is really not working.

**Comment by theNded** [comment]
Open3D is good at scene-scale reconstruction, and there can be a localization issue for small objects. So it is not the integration step but the global registration step that fails to register and align all these fragments.

One potential solution is to set `n_frames_per_fragment` to the number of total frames and treat the first fragment as the final reconstruction result. Another (unimplemented) solution is to use frame-to-model tracking introduced in KinectFusion, which is on our roadmap.
