### ISSUE TITLE
the colors and normals element of pcd read with 0 elements ,use numpy.asarray raise error

### ISSUE THREAD

**Issue by Michelangelo-Y** [intel-isl/Open3D#2754]
colors=std::vector<Eigen::Vector3d> with 0 elements.
Use numpy.asarray() to access data.

normals=std::vector<Eigen::Vector3d> with 0 elements.
Use numpy.asarray() to access data.

points=std::vector<Eigen::Vector3d> with 460400 elements.
Use numpy.asarray() to access data.

**Comment by yxlao** [comment]
- What error did you get?
- Could you share the full code that triggers this error? 
- Could you share your OS / installation method and etc., as specified in the issue template?

It works fine for me with the following code:
```python
>>> import open3d as o3d
>>> import numpy as np
>>> pcd = o3d.geometry.PointCloud()
>>> pcd.colors
std::vector<Eigen::Vector3d> with 0 elements.
Use numpy.asarray() to access data.
>>> np.asarray(pcd.colors)
array([], shape=(0, 3), dtype=float64)
```

**Comment by Michelangelo-Y** [comment]
here is the code:
pcd = o3d.io.read_point_cloud("D:\\PCDs\\table_scene_lms400.pcd")
print(len(pcd.colors))
print(len(pcd.normals))
print(len(pcd.points))

0
0
460400

and i tried another file:
pcd = o3d.io.read_point_cloud("D:\\PCDs\\five_people.pcd")
print(len(pcd.colors))
print(len(pcd.normals))
print(len(pcd.points))

239075
0
239075

i dont know why sometimes pcd.colors has no element,because of the different file?

**Comment by yxlao** [comment]
Yes, a point cloud file may or may not contain color information.

**Comment by Michelangelo-Y** [comment]
but i confirm it contains color information with "open3d.visualization.draw_geometries([pcd])",the two files:"D:\PCDs\table_scene_lms400.pcd" and "D:\PCDs\five_people.pcd" both contain color information i can see with open3d.visualization
