### ISSUE TITLE
Is Open3d possible to draw registration correspondence for source and target point cloud?

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2773]
Dear developers,

Is Open3d possible to draw registration correspondence for source and target point cloud, or [visualize the check of the correspondence of two pcd](https://mordohai.github.io/public/Guo_NonRigidCorrespondence15.pdf)?

I saw that 

- We can get a line-set from the function open3d::geometry::LineSet::CreateFromPointCloudCorrespondences.
- But where can I get the correspondence? From RegistrationResult..correspondence_set_?
- But it seems that each (Eigen::Vector2i) element of the CorrespondenceSet contains two indexes -- one is the index for source pcd ponts, another index is for target pcd points KDTree. 
- How can I get the corresponding target pcd point index according to the target KDTree index?

After a successful fpfh based FastGlobalRegistration, I tried to draw the correspondences. Here is my code

`
    auto corres = reg_result.correspondence_set_;
    std::vector<std::pair<int, int> > corres_lines;
    for (const auto& c : corres) {
        std::pair<int, int> pair = { c[0], c[1] };
        corres_lines.push_back(pair);
    }
    auto lineset = open3d::geometry::LineSet::CreateFromPointCloudCorrespondences(*pcd1, *pcd2, corres_lines);
    lineset->PaintUniformColor({ 1, 0, 0 });
    open3d::visualization::DrawGeometries({ pcd1, pcd2, lineset });
`

Below is the drawn of the two pcds and their correspondences. For the rotated one it is difficult to say that the correspondences is correct, but for the translated one it seems correct. 

Can any one give me a hint how to get a better registration correspondences?

Thank you 

![image](https://user-images.githubusercontent.com/59957922/102472661-cd42bc00-4056-11eb-8f31-c4fc6928ede7.png)
![image](https://user-images.githubusercontent.com/59957922/102485137-7db8bc00-4067-11eb-8069-650fd989122e.png)

**Comment by ouceduxzk** [comment]
me too
