### ISSUE TITLE
Extrinsic matrix

### ISSUE THREAD

**Issue by hosseinshirali** [intel-isl/Open3D#2778]
Hi 
i use the reconstruction system for creating the point clouds from a sequence of RGBD frames and it gives me trajectory.log which is the extrinsic matrix for each frame.
i want to do projection from world coordinate to pixel coordinates by `cv2.projectPoints()` and it needs rotation vector (rvec) and translation vector (tvec) 
can you confirm that can i extract and use the rotation matrix and translation vector from trajectory.log and pass it to `cv2.projectPoints()`?
thanks for your help

**Comment by theNded** [comment]
These are poses (i.e., camera to world transformation). Extrinsics are their inverse (i.e., world to camera transformation). So after an inversion you can refer to this answer https://answers.opencv.org/question/162932/create-a-stereo-projection-matrix-using-rvec-and-tvec/ and obtain rvec and tvec for projection.

**Comment by hosseinshirali** [comment]
@theNded thanks for your help, is there any python version of that question?
