### ISSUE TITLE
viewer.capture_screen_image('name.jpg')

### ISSUE THREAD

**Issue by lingtengqiu** [intel-isl/Open3D#2779]
```
I use the function 'capture_screen_image' to capture the visualization screen. But I got  black image actually. what happen? who can help me
```

**Comment by qsisi** [comment]
Sorry to bother you again, but have you solved the question and how did u solve it?

**Comment by arbab-ml** [comment]
put the do_render flag: 
`    vis.capture_screen_image(image_path, do_render=True)`

**Comment by lyhnsn** [comment]
> put the do_render flag: ` vis.capture_screen_image(image_path, do_render=True)`

Thank you very much! It does work!
