### ISSUE TITLE
RegistrationResult.correspondence_set_   getting mess when registration transformation needs to rotate

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2780]
Hello,

I tried both fpfh based fast global registration and ICP registration. The returned RegistrationResult.transformation_ has no problem, but RegistrationResult.correspondence_set_  seems getting mess when registration transformation needs to rotate. Only translation seems OK. See the following pictures.

Thank you!

Here is my code to draw the correspondence_set

`
 auto corres = reg_result.correspondence_set_;
    std::vector<std::pair<int, int> > corres_lines;
    for (const auto& c : corres) {
        std::pair<int, int> pair = { c[0], c[1] };
        corres_lines.push_back(pair);
    }
    auto lineset = open3d::geometry::LineSet::CreateFromPointCloudCorrespondences(*pcd1, *pcd2, corres_lines);
    lineset->PaintUniformColor({ 1, 0, 0 });
    open3d::visualization::DrawGeometries({ pcd1, pcd2, lineset });
`

![image](https://user-images.githubusercontent.com/59957922/102472661-cd42bc00-4056-11eb-8f31-c4fc6928ede7.png)
![image](https://user-images.githubusercontent.com/59957922/102485137-7db8bc00-4067-11eb-8069-650fd989122e.png)

**Comment by theNded** [comment]
What is your setup for obtaining the putative correspondences? They can be potentially noisy even if the result is correct.

**Comment by 1939938853** [comment]
Hello theNded,

After the registration either with  fast global or ICP, the returned RegistrationResult will contain a correspondence_set_. I think, If the registration is successful, this correspondence_set_ should give an one to one point correspondences for the source and target PCDs. Am I right? Do I need to use some kind of setup to extract a correct correspondences? 

Now, in order to get the correct correspondences. I do the following workaround

1. calculate source target registration -> to get the transform matrix 
2. use the transform matrix to transform a source-copy pcd to target
3. use open3d point cloud distance function, to calculate the  (closed)  distance between   source-copy pcd to target pcd.
4. I have modified this distance function so that it can output the "index" of the target.

In this way I get the correct "clean" correspondences. 

I think open3d registration should return a correct correspondence_set_.  If so I can skip  the step 3 and 4.

**Comment by theNded** [comment]
> Hello theNded,
> 
> After the registration either with fast global or ICP, the returned RegistrationResult will contain a correspondence_set_. I think, If the registration is successful, this correspondence_set_ should give an one to one point correspondences for the source and target PCDs. Am I right? Do I need to use some kind of setup to extract a correct correspondences?

No, correspondences will be filtered by a distance threshold, which is not necessarily one-on-one mapping. Otherwise point cloud registration will be reduced to solving [Umeyama SVD](http://graphics.stanford.edu/~smr/ICP/comparison/eggert_comparison_mva97.pdf). In fact, searching for correct correspondences is a fundamental problem and cannot be easily solved.

> 
> Now, in order to get the correct correspondences. I do the following workaround
> 
> 1. calculate source target registration -> to get the transform matrix
> 2. use the transform matrix to transform a source-copy pcd to target
> 3. use open3d point cloud distance function, to calculate the  (closed)  distance between   source-copy pcd to target pcd.
> 4. I have modified this distance function so that it can output the "index" of the target.
> 
> In this way I get the correct "clean" correspondences.
> 
> I think open3d registration should return a correct correspondence_set_. If so I can skip the step 3 and 4.

This is equivalent to calling nearest neighbor search with the estimated transformation. Open3D is responsible for returning the relatively accurate pose with filtered correspondence set as a reference. Obtaining clean correspondences can be a helpful utility function and we welcome contribution, but should not be included in ICP/registration itself. It requires one more iteration and will do harm to performance without improving accuracy.
