### ISSUE TITLE
Question: Ask If Visualizer Is Closed

### ISSUE THREAD

**Issue by Me817** [intel-isl/Open3D#2787]
Hello,

I need to know if I can proof or ask by an if-statemant if the VisualizerWithKeyCallback is closed via the red cross. Because if that happens I want to save some data. Is this possible? If yes, how can I do this? I found nothing helpful for me in the documentation...

Thank you in advance.

**Comment by prewettg** [comment]
If you are using C++, inherit from VisualizerWithKeyCallback and override WindowCloseCallback(). If you are using Python there is unfortunately no way at the moment.

This is also not supported in the new GUI/visualizer, so I am marking this as a feature request.

**Comment by Me817** [comment]
All right! I am using Python. 
Thank you for the quick response and for marking it as a feature request.

**Comment by prewettg** [comment]
#2958 implements this. 
```
...
widow.set_on_closed(on_close)
...
def on_close():   # could also a be a method of a class
    ... # do whatever needs to be done here
    return True  # returning False will cancel the close
```
This feature is also used in the new `examples/python/gui/video.py` example in #3002
