### ISSUE TITLE
[QUESTION] How to use ExternalVisualizer

### ISSUE THREAD

**Issue by chuong98** [intel-isl/Open3D#2789]
Hi, I am developing the code through a Remote Server (that has GPU), and I am looking for a way to visualize the results.

Currently, I have no luck with JVisualizer. And I see from the documents, there is a class:
```
open3d.visualization.ExternalVisualizer(address='tcp://127.0.0.1:51454', timeout=10000)
```
But I got error `AttributeError: module 'open3d' has no attribute 'visualizer'` .

I install the latest version:
`pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.11.2+543e34e-cp38-cp38-linux_x86_64.whl`.

And, assume that I can pass the error, how do I visualize the result on my local machine. 
Thank for your help.

**Comment by benjaminum** [comment]
Hi,

I see that the example in the docstring is wrong and uses `open3d.visualizer` but instead it should be `open3d.visualization`.
The code you posted seems correct and should work.
You can also try to use the default instance of the ExternalVisualizer, which is `open3d.visualization.EV`

Visualization of data from a remote machine works like this:
### local machine
Start a visualizer window. With the latest master this can be done on the commandline with
```
python -m open3d.visualization --external-vis 
```
The visualizer will listen on the localhost on port 51454. Therefore we have to create an ssh tunnel to the remote with
```
ssh -R 51454:localhost:51454 remote_machine
# as an alternative I can recommend to use eternal terminal (et), which
# can also do remote port forwarding and nicely restores connections after drops or when the computer restores from sleep.
```
### remote machine
On the remote you can run your python session or script and use the ExternalVisualizer
```
# This is from the docstring of the draw function of the ExternalVisualizer
import open3d as o3d
torus = o3d.geometry.TriangleMesh.create_torus()
sphere = o3d.geometry.TriangleMesh.create_sphere()
# create shortcut for draw
draw = o3d.visualization.EV.draw
draw([ {'geometry': sphere, 'name': 'sphere'},
           {'geometry': torus, 'name': 'torus'} ])
```
There should be now a sphere and a torus in the local visualizer window. (The geometries do not appear in the list of geometries. This is a bug and we are working on fixing this.)

Please note that the RPC interface is experimental. Let us know what you think.

**Comment by chuong98** [comment]
Hi, when I start the command:
`python -m open3d.visualization --external-vis 
I got the error:
`No module named open3d.visualization.__main__; 'open3d.visualization' is a package and cannot be directly executed`

**Comment by chuong98** [comment]
Oh, my bad. Install with the latest master branch can start the External visualizer.
I first test within my local machine only. 
Running the above two commands does not yield errors, but I don't see anything on the Window. 
I guess I am missing some thing.

**Comment by chuong98** [comment]
Oh, after I click Reset Camera, it works now. Awesome. Thanks a lot.

**Comment by ahmedaskar18** [comment]
excuse me guys, what he meant about the "external"?...........does he mean an external ui?

**Comment by anuzk13** [comment]
After following the instructions to create an ssh tunnel with a remote server I get the following:

[Open3D INFO] Connection::send() recv failed with: Resource temporarily unavailable

**Comment by KaboomHBR** [comment]
I suspect it's due to the size of the point cloud and maybe the limit of the TCP tunnel. My point cloud file has 4147200 points and while using draw I faced the same issue as you. 

Using [Voxel Downsampling](https://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html#Voxel-downsampling) solves my issue.

**Comment by jinhanzhang** [comment]
I tried this command: `python -m open3d.visualization --external-vis`  on my local machine and the Python application crashed in a second and got the segmentation fault 11. I am using python=3.10.11 and open 3d=0.18.0. Any ideas?
