### ISSUE TITLE
Object has no attribute 'radius_outlier_removal' in Python

### ISSUE THREAD

**Issue by arudomanenko** [intel-isl/Open3D#2790]
Hi, Thanks a lot for your work! This library looks very promising. But I have a bug (I think so, maybe I made smth wrong).
I am use Open3d Python and trying to use `radius_outlier_removal` method. Unfortunately, this call throw exception for me:
`cl, ind = voxel_down_pcd.radius_outlier_removal(voxel_down_pcd,
AttributeError: 'open3d.cpu.pybind.geometry.PointCloud' object has no attribute 'radius_outlier_removal'`
It should be noticed, that I tried a lot of ways to install Open3d to my computer
1) with help of pip
2) using conda (but in this case I cant event import module)
3) building from source
But the way I am installing library doesn't change anything 

1. run any python IDE (pycharm in my case)
2. read or create a point cloud
3. Try to call pcd.radius_outlier_removal(pcd, nb_points=16, radius=0.05) (pcd in my case it a point cloud name)

To make it more clear, I paste my code and error text below:

    import open3d as o3d

    def main():
        pc_name = "up.ply"
        pcd = o3d.io.read_point_cloud(pc_name)
        pcd.radius_outlier_removal(pcd, nb_points=16, radius=0.05)

    if __name__ =="__main__":
        main()

Error:
```
    Traceback (most recent call last):
    File "/home/arud/PycharmProjects/cv/main.py", line 10, in <module>
    main()
    File "/home/arud/PycharmProjects/cv/main.py", line 6, in main 
    pcd.radius_outlier_removal(pcd, nb_points=16, radius=0.05)
    AttributeError: 'open3d.cpu.pybind.geometry.PointCloud' object has no attribute 'radius_outlier_removal'
```

- Operating system: Ubuntu 18.04
- Python version: python 3.7
- Open3D version: 0.11.2
- Is this remote workstation?: no
- How did you install Open3D?: pip, conda, build from source (but I prefer pip)
- Compiler version (if built from source): gcc 7.5.0

**Comment by yxlao** [comment]
It is now called `remove_radius_outlier`, to be consistent with the related functions `remove_non_finite_points` and `remove_statistical_outlier`. See the documentation: http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.remove_radius_outlier.
