### ISSUE TITLE
Unable to import open3d

### ISSUE THREAD

**Issue by jonnymaserati** [intel-isl/Open3D#2806]
**Describe the bug**
Unable to import open3d in Python.

**To Reproduce**
Type `python -c "import open3d"` in terminal and I get:
```
/home/username/anaconda3/envs/myenv/lib/python3.7/site-packages/open3d/cpu/pybind.cpython-37m-x86_64-linux-gnu.so: undefined symbol: glPopGroupMarkerEXT
```
**Expected behavior**
I expect open3d to be imported.

**Screenshots**

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04.01 LTS
- Python version: tried Python 3.7 and 3.8
- Open3D version: 0.11.1 (and tried latest dev version)
- Is this remote workstation?: no
- How did you install Open3D?: tried them all: pip, conda, build from source
- Compiler version (if built from source): cmake 3.19.2 (I installed the latest version)

**Comment by ssheorey** [comment]
Closing this since reporter opened duplicate bug report #2903
