### ISSUE TITLE
QUESTION: How can I add ImGui labels in my Visualizer permanently and on key pressed event?

### ISSUE THREAD

**Issue by Me817** [intel-isl/Open3D#2812]
Hello,

I would like to add some ImGui labels to my visualizer while displaying a point cloud to tell the user which keys have to be pressed to do certain actions. This should look like this:
![grafik](https://user-images.githubusercontent.com/56630682/102945197-5f1a5100-44bd-11eb-9226-5a3f6136e95a.png)

How could I do this? Unfortunately I can't find a documentation how to use ImGui with the visualizer in Python.
Is it possible to display labels on a key event? For example if the user pressed enter and there should be displayed a label that informs the user that everything is saved correctly.

Thank you in advance.

**Comment by errissa** [comment]
Take a look at vis-gui.py in examples/python/gui which has a number of examples of using a label widget to add text. Also, you can look at cpp/open3d/visualization/visualizer/GuiVisualizer.cpp although it is a C++ example. `CreateHelpDisplay` builds a display similar to your example.

Yes, it is possible to add labels in response to callback events. Again, take a look at vis-gui.py for examples of callback handling.

**Comment by Me817** [comment]
@errissa Thank you for the quick response. This helped me a lot!

**Comment by FikiCarDev** [comment]
@errissa @Me817 where are they moved to?

**Comment by nnop** [comment]
What's the relationship between `GuiVisualizer` and `O3DVisualizer`? @errissa
