### ISSUE TITLE
Create a point cloud from a RGBD image

### ISSUE THREAD

**Issue by ivankrstev7** [intel-isl/Open3D#2814]
I am trying to create a pointcloud fron an RGBD image, I am reading the images with the following code:
`color_raw = o3d.io.read_image('1RGB.png')`
 `depth_raw = o3d.io.read_image('1.png')`
 `color = o3d.geometry.Image(np.array(np.asarray(color_raw)[:, :, :3]).astype('uint8'))`
 `rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(color, depth_raw,
                                                                    convert_rgb_to_intensity=True)`

The results turn out to be pretty okay when i print rgbd_image.color and rgbd_image.depth, bu the problem is when i try to create the point cloud:
`pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, phc_ipad_1)`
i get a white screen (an empty pcd).

**Comment by theNded** [comment]
Did you check that the `depth_scale` is correct? You are using the default `1000`, but for various sensors it can be varying, for instance, `5000` for the TUM RGBD dataset, `4000` for the latest RealSense L515 in some cases, and so on.

**Comment by ivankrstev7** [comment]
@theNded I saw that my problem was in visualizing the point cloud on the end, the depth image was okay. But i wonder, in which format our custom depth images should be? Because, when i read the depth image, it is a regular image with pixels range [0-255] and then when i create the RGBD, I can extract the depth values. So, how does it get converted and is it okay that on the beginning the depth images are regular RGB images?

**Comment by theNded** [comment]
> @theNded I saw that my problem was in visualizing the point cloud on the end, the depth image was okay. 

A 'perceptually' correct visualization of the depth image does not indicate it is correct. As I said, the real depth value is depending on both the pixel value and the `depth_scale`.

> But i wonder, in which format our custom depth images should be? Because, when i read the depth image, it is a regular image with pixels range [0-255] and then when i create the RGBD, I can extract the depth values. So, how does it get converted and is it okay that on the beginning the depth images are regular RGB images?

In this case, the depth image is not correctly stored. We expect a 16-bit png storing `unsigned short` per pixel, ranging in [0-65535]. Conventionally we expect to see values between [0-10000],  so the pixel value divided by`depth_scale = 1000` yields depth ranging from [0-10] meters. Please check your depth format and reorganize it accordingly.

**Comment by theNded** [comment]
Closed due to inactivity for now. Please reopen if this problem persists.

**Comment by glassTransition** [comment]
I can't find an example of how to use geometry.PointCloud.create_from_rgbd_image.... with 0.12.0, Python and a Realsense camera.

There is a very terse snippet for capturing the images, but I don't see how to get the camera intrinsics and other paramters?

**Comment by pranman11** [comment]
@ivankrstev7 I am facing a similar issue of the white screen/empty point cloud. What was your solution?
