### ISSUE TITLE
pip install open3d fails on Ubuntu 18.04 since scikit-learn update to 0.24

### ISSUE THREAD

**Issue by jackjansen** [intel-isl/Open3D#2825]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**

Installing open3d with `pip install open3d`, since the scikit-learn update to 0.24.
Seen on Ubuntu 18.04 with Python 3.6.

Installation of scikit-learn fails, because Python is not installed.

I have reported this bug first to scikit-learn, as https://github.com/scikit-learn/scikit-learn/issues/19068 and the suggestion there was that this was due to open3d depending on `sklearn` where it should depend on `scikit-learn`.

(Note: I am only the messenger. I have very limited knowledge of open3d and even less of scikit-learn).

**To Reproduce**

1. pip install open3d

**Expected behavior**
It should work.

**Screenshots**

Here is the relevant part of the logfile of installing open3d (taken from a gitlab CI/CD system building a product that uses open3d):
[scikit-learn-install-log.txt](https://github.com/intel-isl/Open3D/files/5740657/scikit-learn-install-log.txt)

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: Current pypi release
- Is this remote workstation?: yes
- How did you install Open3D?: pip

**Additional context**

**Comment by yxlao** [comment]
thanks @jackjansen, this issue has been resolved
