### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jhx2002** [intel-isl/Open3D#2834]
Build version: 0.10.0
On ubuntu 18.04 with gcc 7 and cmake 3.16.2

Scanning dependencies of target Open3D
[ 78%] Building CXX object src/Open3D/CMakeFiles/Open3D.dir/Open3DConfig.cpp.o
[ 78%] Linking CXX shared library ../../lib/libOpen3D.so
/usr/bin/ld: cannot find -lc++
collect2: error: ld returned 1 exit status

**Comment by yxlao** [comment]
Did you run `util/install_deps_ubuntu.sh`?

**Comment by jhx2002** [comment]
Yes, I did

**Comment by yxlao** [comment]
First, looks like you're using version 0.10.0. Please try again with the latest `mater` branch or `0.12.0`. Additionally, please double-check if these two packages are installed: https://github.com/intel-isl/Open3D/blob/ae4178f59c2224ac918248f329b08a34bac5a908/util/install_deps_ubuntu.sh#L23-L24

If the issue still persists, you may submit the build scripts in a `Dockerfile` with `ubuntu:18.04` as the base image and we'd be happy to take a look at that.

**Comment by theNded** [comment]
Closed due to inactivity and non up-to-date version. Please reopen if problem persists.
