### ISSUE TITLE
Bug with RealSense bag reader

### ISSUE THREAD

**Issue by shiyoung77** [intel-isl/Open3D#2837]
I was trying to use the sample code from "http://www.open3d.org/docs/release/tutorial/sensor/realsense.html". 
```
import open3d as o3d
bag_reader = o3d.t.io.RSBagReader()
bag_reader.open('L515_test.bag')
while not bag_reader.is_eof():
    im_rgbd = bag_reader.next_frame()
bag_reader.close()
```
However, open3d failed to open the bag but gave me the following error instead.
```
free(): invalid pointer
Aborted
```

**Environment:**

- Operating system:Ubuntu 18.04
- Python version: Python 3.7
- Open3D version: 0.12.0
- Is this remote workstation?:  no
- How did you install Open3D?:
  - conda create -n open3d
  - conda activate open3d
  - pip install open3d-0.12.0-cp37-cp37m-manylinux2014_x86_64.whl 
- Compiler version (if built from source): N/A

**Comment by colabi** [comment]
Is it known what version worked last?  I've been banging my head on this and just found this new issue.
