### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by jhx2002** [intel-isl/Open3D#2838]
Build version: 0.10.0
On ubuntu 18.04 with gcc 7 and cmake 3.16.

Filament library loaded.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Open3D ERROR] GLFW Error: Linux: Failed to watch for joystick connections in /dev/input: No such file or directory
Aborted (core dumped)

**Comment by yxlao** [comment]
Could you try again with `0.12.0` or `master`? Also it would be helpful to share your full build scripts, as well as terminal outputs.

**Comment by theNded** [comment]
Closed due to inactivity and non up-to-date version. Please reopen if problem persists.
