### ISSUE TITLE
pip install open3d doesn't find 0.12.0 on Ubuntu 20.04

### ISSUE THREAD

**Issue by meder-yembo** [intel-isl/Open3D#2840]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Installation via `pip` doesn't seem to find the newest version on Ubuntu 20.04 (both my system python and my conda environment have this issue), despite [it looking up-to-date on PyPi](https://pypi.org/project/open3d/).

**To Reproduce**

```
$ python -m pip install --no-cache-dir open3d==0.12.0
ERROR: Could not find a version that satisfies the requirement open3d==0.12.0 (from versions: 0.10.0.0, 0.11.0, 0.11.1, 0.11.2)
ERROR: No matching distribution found for open3d==0.12.0
```

**Expected behavior**
Version 0.12.0 to be installed

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: 0.12.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**
I notice that the [downloadable files on the PyPi site](https://pypi.org/project/open3d/#files) only include the Windows and Mac wheels for 0.12.0, but [include pip wheels for Linux for prior releases](https://pypi.org/project/open3d/0.11.2/#files). Is there something preventing Linux users from using 0.12.0 or was this an accidental omission?

**Comment by ssheorey** [comment]
Please use the Python wheels from the Github releases section for now. We are waiting for PyPI to approve the increased file size for v0.12 Linux wheels.

https://github.com/pypa/pypi-support/issues/809

**Comment by meder-yembo** [comment]
Okay, thanks for the info!

BTW, using the Python3.6 wheel in releases gives this error now when installed to a docker container (whereas 11.2 from pip did not):

 `OSError: libusb-1.0.so.0: cannot open shared object file: No such file or directory`

The solution is simple enough: `sudo apt install libusb-1.0-0`, but it seems odd that `libusb-1.0-0` is now a new dependency. Previously, the only non-python dependency when installing to a container was `libgl1-mesa-glx`.

**Comment by YoushaaMurhij** [comment]
@meder-yembo Can You please tell how to install it from the repository?
Thanks!

**Comment by ssheorey** [comment]
Open3D v0.12 Linux wheels have been uploaded to PyPI and can be installed through pip now.
@meder-yembo The `libusb` dependence was removed in PR #2876 (now in master).
