### ISSUE TITLE
Cannot install Open3D 0.12.0

### ISSUE THREAD

**Issue by fireflying12** [intel-isl/Open3D#2842]
I had already picked the latest version of "open3d-0.12.0-cp38-cp38-win_amd64" to install, when I typed "conda list" to check the Open3D version I installed, it always shows "open3d                    0.11.2 ". How can I install or upgrade the Open3D to Open3D 0.12.0? 
Also, my L515 cannot be detected by the Open3D is it due to the version problem? only Open3D 0.12.0 can detect the L515 camera?

**Comment by chris-aeviator** [comment]
I was successfully able to install 0.12.0 this morning by mixing pip and conda install

![image](https://user-images.githubusercontent.com/11522213/103403454-7063fd00-4b50-11eb-92f0-69e3970cb958.png)

**Comment by theNded** [comment]
See #2840. Closed for now.
