### ISSUE TITLE
How can i use the function of remove_statistical_outlier() to remove noise points?

### ISSUE THREAD

**Issue by arkerman** [intel-isl/Open3D#2855]
def display_inlier_outlier(cloud, ind):
        inlier_cloud = cloud.select_by_index(ind)
        outlier_cloud = cloud.select_by_index(ind, invert=True)
        print (type(outlier_cloud))
        print("Showing outliers (red) and inliers (gray): ")
        outlier_cloud.paint_uniform_color([1, 0, 0])
        inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
        o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud],
                                          zoom=0.3412,
                                          front=[0.4257, -0.2125, -0.8795],
                                          lookat=[2.6172, 2.0475, 1.532],
                                          up=[-0.0694, -0.9768, 0.2024])

    print("Statistical oulier removal")
    cl, ind = voxel_down_pcd.remove_statistical_outlier(nb_neighbors=2000, std_ratio=0.5)
    display_inlier_outlier(voxel_down_pcd, ind)

I can use these codes to show outliers (red) and inliers (gray). But i wanna to delete outliers (red). So how can i achieve it.

**Comment by theNded** [comment]
Why don't you use `inlier_cloud`?

**Comment by arkerman** [comment]
i wanna to delete outliers(red).And my goal is to show images without noise.So how can i achieve it?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "intel-isl/Open3D"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 中午1:51
收件人:&nbsp;"intel-isl/Open3D"<Open3D@noreply.github.com&gt;;
抄送:&nbsp;"1106848468"<1106848468@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [intel-isl/Open3D] How can i use the function of remove_statistical_outlier() to remove noise points? (#2855)





 
Why don't you use inlier_cloud?

**Comment by theNded** [comment]
Please at least **try** to understand the code snippet you are using. You are using a wrapper of the `remove_statistical_outlier` that has already fed everything you need.

Let me modify your code and show you how to achieve it.
```python
def display_inlier(cloud, ind):
    inlier_cloud = cloud.select_by_index(ind)
    print("Showing outliers (red): ")
    inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
    o3d.visualization.draw_geometries([inlier_cloud],
                                      zoom=0.3412,
                                      front=[0.4257, -0.2125, -0.8795],
                                      lookat=[2.6172, 2.0475, 1.532],
                                      up=[-0.0694, -0.9768, 0.2024])
    return inlier_cloud
```

**Comment by arkerman** [comment]
oh， I see. Thank you for your reply. Hope you have a good day！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "intel-isl/Open3D"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 下午2:28
收件人:&nbsp;"intel-isl/Open3D"<Open3D@noreply.github.com&gt;;
抄送:&nbsp;"1106848468"<1106848468@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [intel-isl/Open3D] How can i use the function of remove_statistical_outlier() to remove noise points? (#2855)





 
Please at least try to understand the code snippet you are using. You are using a wrapper of the remove_statistical_outlier that has already fed everything you need.
 
Let me modify your code and show you how to achieve it.
 def display_inlier(cloud, ind):     inlier_cloud = cloud.select_by_index(ind)     print("Showing outliers (red): ")     inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])     o3d.visualization.draw_geometries([inlier_cloud],                                       zoom=0.3412,                                       front=[0.4257, -0.2125, -0.8795],                                       lookat=[2.6172, 2.0475, 1.532],                                       up=[-0.0694, -0.9768, 0.2024])     return inlier_cloud
