### ISSUE TITLE
compile issue with source code

### ISSUE THREAD

**Issue by GITSHOHOKU** [intel-isl/Open3D#2856]
I compiled this C++ source code on ubuntu18.04. The cmake step is successful,but when I run make -j, the compile process always stop at built target ext_faiss,the detail is :
`Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/lib/libfaiss.a
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/DirectMap.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IVFlib.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/Index.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/Index2Layer.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexBinary.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexBinaryFlat.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexBinaryFromFloat.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexBinaryHash.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexBinaryIVF.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexFlat.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexIVF.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexIVFFlat.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexIVFPQ.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexIVFPQR.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexIVFSpectralHash.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexLSH.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexLattice.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexPQ.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexPreTransform.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexReplicas.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexScalarQuantizer.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/IndexShards.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/InvertedLists.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/MatrixStats.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/MetaIndexes.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/MetricType.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/VectorTransform.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/index_io.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/ParallelUtil.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/AuxIndexStructures.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/FaissAssert.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/FaissException.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/PolysemousTraining.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/ProductQuantizer-inl.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/ProductQuantizer.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/ScalarQuantizer.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/ThreadedIndex-inl.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/ThreadedIndex.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/io.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/io_macros.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/lattice_Zn.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/impl/platform_macros.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/utils/Heap.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/utils/WorkerThread.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/utils/distances.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/utils/extra_distances.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/utils/hamming-inl.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/utils/hamming.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/utils/random.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/utils/utils.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/include/faiss/OnDiskInvertedLists.h
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/share/faiss/faiss-config.cmake
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/share/faiss/faiss-config-version.cmake
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/share/faiss/faiss-targets.cmake
-- Installing: /home/hongkl/Software/Open3D/build/mkl_install/share/faiss/faiss-targets-relwithdebinfo.cmake
[ 29%] Completed 'ext_faiss'
[ 29%] Built target ext_faiss
`
the process stop here for a long time . What should I do?

**Comment by ssheorey** [comment]
Can you try building with `make -j4` instead? `make -j` sometimes has problems since it can launch too many simultaneous processes.

**Comment by GITSHOHOKU** [comment]
> Can you try building with `make -j4` instead? `make -j` sometimes has problems since it can launch too many simultaneous processes.

make -j4  solved this problem, thanks!
