### ISSUE TITLE
Unable to rotate point cloud 

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [intel-isl/Open3D#2858]
I am trying to rotate pointcloud with the following code - 

`import open3d as o3d 
import numpy as np 

xyz = o3d.io.read_point_cloud("data.pcd")
xyz = xyz.rotate(xyz.get_rotation_matrix_from_xyz((0.7 * np.pi, 0, 0.6 * np.pi)),center=True)`

But I get the following error - 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_rotation_matrix_from_xyz(): incompatible function arguments. The following argument types are supported:
    1. (rotation: numpy.ndarray[float64[3, 1]]) -> numpy.ndarray[float64[3, 3]]

Invoked with: array([[-0.30901699, -0.95105652,  0.        ],
       [-0.55901699,  0.18163563, -0.80901699],
       [ 0.76942088, -0.25      , -0.58778525]]); kwargs: center=True`

help to resolve it is appreciated.

**Comment by ValentinSteiner** [comment]
The `center` argument is not boolean, but should describe the rotation center (see [docs](http://www.open3d.org/docs/latest/python_api/open3d.geometry.PointCloud.html)):
> center (numpy.ndarray[float64[3, 1]]) – Rotation center used for transformation

**Comment by CaptainEven** [comment]
@ValentinSteiner @ShettyHarapanahalli Do you guys know how to auto-rotate a point cloud and show(save each frame) like dome paper demos did?
