### ISSUE TITLE
L515 do not detected by the program

### ISSUE THREAD

**Issue by fireflying12** [intel-isl/Open3D#2861]
When I running these code:

import json
import open3d as o3d
with open("RS2_L500_VISUAL_PRESET_MAX_RANGE.json") as cf:
    rs_cfg = o3d.t.io.RealSenseSensorConfig(json.load(cf))

rs = o3d.t.io.RealSenseSensor()
rs.init_sensor(rs_cfg, 0, "record test_data.bag")
rs.start_capture(True)  # true: start recording with capture
for fid in range(150):
    im_rgbd = rs.capture_frame(True, True)  # wait for frames and align them
    # process im_rgbd.depth and im_rgbd.color

rs.stop_capture()

With configuration file:

{
    "serial": "",
    "color_format": "RS2_FORMAT_RGB8",
    "color_resolution": "0,720",
    "depth_format": "RS2_FORMAT_Z16",
    "depth_resolution": "0,768",
    "fps": "30",
    "visual_preset": "RS2_L500_VISUAL_PRESET_MAX_RANGE"
 }

it shows the error
RuntimeError: In function bool __cdecl open3d::t::io::RealSenseSensor::InitSensor(const class open3d::t::io::RealSenseSensorConfig &,unsigned __int64,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &):
D:\a\Open3D\Open3D\cpp\open3d\t\io\sensor\realsense\RealSenseSensor.cpp:212 [Open3D Error] Invalid RealSense camera configuration, or camera not connected:
UNKNOWN: No device connected

How may I solve this problem? I have already connected the camera with USB3

**Comment by HelliceSaouli** [comment]
I have the same problem with D435 but i'm using the c++ code  example. it says no device connected

**Comment by eltonhcchan** [comment]
So is it a bug? Should a bug report be created to fix it?

**Comment by ssheorey** [comment]
@fireflying12 @HelliceSaouli Can [`realsense-viewer`](https://www.intelrealsense.com/sdk-2/) detect your L515 camera? The 2nd line in the error message:
`UNKNOWN: No device connected`
is from the `librealsense` backend library.

**Comment by HelliceSaouli** [comment]
@ssheorey for me yes the realsense-view detect my D435 camera and works fine. it is when i compile the realsense recorder example in cpp and run i got this message. btw i'm on windows 10, i have not installed realsense sdk2 i thought it was integrated with open3d

**Comment by ssheorey** [comment]
Your don't need the RealSense SDK to use this, but we want to make sure that the official software works correctly in a situation before trying to debug our software. Please ensure that the official SDK can detect the camera on the same machine.

If the official SDK / `realsense-viewer` works, but Open3D is not able to detect the camera on your machine, please create and upload debug logs (and any output on the terminal):

Environment variable:
bash: `export LRS_LOG_LEVEL=debug` 
powershell: `$ENV:LRS_LOG_LEVEL = debug`
cmd: `set LRS_LOG_LEVEL=debug`

For Python:
`python <open3d_src_dir>/examples/python/misc/realsense.py`

For C++, build with examples and librealsense from the cmake options and:
`<open3d_build_dir>/bin/examples/RealSenseRecorder`

The log file will be created in the same folder with the name `<date>-<time>.log`

**Comment by eltonhcchan** [comment]
@ssheorey, here it is

(spyder-env) D:\python>set LRS_LOG_LEVEL=debug
(spyder-env) D:\python>python D:\python\Open3D\examples\python\misc\realsense.py
[Open3D WARNING] No RealSense devices detected.
Traceback (most recent call last):
  File "D:\python\Open3D\examples\python\misc\realsense.py", line 15, in <module>
    rscam.start_capture()
RuntimeError: In function bool __cdecl open3d::t::io::RealSenseSensor::StartCapture(bool):
D:\a\Open3D\Open3D\cpp\open3d\t\io\sensor\realsense\RealSenseSensor.cpp:241 [Open3D Error] StartCapture() failed: UNKNOWN: No device connected

log file:
 09/01 11:13:43,365 DEBUG [13824] (context.cpp:110) Librealsense VERSION: 2.40.0
 09/01 11:13:43,375 INFO [13824] (context.cpp:381) Found 0 RealSense devices (mask 254)
 09/01 11:13:43,385 INFO [13824] (context.cpp:381) Found 0 RealSense devices (mask 254)
 09/01 11:13:43,391 INFO [13824] (context.cpp:381) Found 0 RealSense devices (mask 254)
 09/01 11:13:43,396 INFO [13824] (context.cpp:381) Found 0 RealSense devices (mask 255)
 09/01 11:13:48,416 INFO [13824] (context.cpp:381) Found 0 RealSense devices (mask 254)
 09/01 11:13:48,419 INFO [13824] (context.cpp:381) Found 0 RealSense devices (mask 255)
 09/01 11:13:53,428 INFO [13824] (context.cpp:381) Found 0 RealSense devices (mask 254)
 09/01 11:13:53,432 INFO [13824] (context.cpp:381) Found 0 RealSense devices (mask 255)
 09/01 11:13:58,442 WARNING [13824] (rs.cpp:1886) null pointer passed for argument "profile"

Realsense viewer can connect to L515 and work properly.

**Comment by HelliceSaouli** [comment]
> "For C++, build with examples and librealsense from the cmake options and:"
what do you mean by that ?
any way i run the example with log enabled and i get an empty log file

**Comment by skyek** [comment]
I am having the same problems. My L515s are not being detected in o3d. Using the pyrealsense2 and the realsense viewer, the devices are detected correctly.
Using Windows 10 and Python 3.7. Tried o3d 0.12 and dev build

**Comment by ssheorey** [comment]
Hi @skyek @eltonhcchan @HelliceSaouli can you test the bug fix PR and let us know if it works for you?
C++: branch `ssheorey/fix-2861`
Python 3.6 wheel: Download artifact from the checks tab -> Windows CI: https://github.com/intel-isl/Open3D/actions/runs/500067599
Wheels for other versions of Python will be available after the PR is merged into master.

**Comment by skyek** [comment]
Hi @ssheorey , thank you for the patch. I tested it and it appears to be working. I haven't done anything in depth yet, but t.io.RealSenseSensor().list_devices() now lists all of my devices

**Comment by eltonhcchan** [comment]
@ssheorey , It works on python 3.6 environment. Hope it can support 3.8 soon. See below output. 
runfile('D:/python/realsense/untitled11.py', wdir='D:/python/realsense')
[Open3D INFO] [0] Intel RealSense L515: f0xxxxxx
[Open3D INFO] 	color_format: [RS2_FORMAT_BGR8 | RS2_FORMAT_BGRA8 | RS2_FORMAT_RGB8 | RS2_FORMAT_RGBA8 | RS2_FORMAT_Y16 | RS2_FORMAT_YUYV]
[Open3D INFO] 	color_resolution: [1280,720 | 1920,1080 | 640,360 | 640,480 | 960,540]
[Open3D INFO] 	color_fps: [15 | 30 | 6 | 60]
[Open3D INFO] 	depth_format: [RS2_FORMAT_Z16]
[Open3D INFO] 	depth_resolution: [1024,480 | 1024,768 | 640,480]
[Open3D INFO] 	depth_fps: [30]
[Open3D INFO] 	visual_preset: [RS2_L500_VISUAL_PRESET_CUSTOM | RS2_L500_VISUAL_PRESET_DEFAULT | RS2_L500_VISUAL_PRESET_LOW_AMBIENT | RS2_L500_VISUAL_PRESET_MAX_RANGE | RS2_L500_VISUAL_PRESET_NO_AMBIENT | RS2_L500_VISUAL_PRESET_SHORT_RANGE]
[Open3D INFO] Open3D only supports synchronized color and depth capture (color_fps = depth_fps).
[Open3D INFO] Capture started with RealSense camera f0232090
{
	"color_format" : "RGB8",
	"depth_format" : "Z16",
	"depth_scale" : 3999.999755859375,
	"device_name" : "Intel RealSense L515",
	"fps" : 30.0,
	"height" : 720,
	"intrinsic_matrix" : 
	[
		905.5811767578125,
		0.0,
		0.0,
		0.0,
		906.38787841796875,
		0.0,
		644.589111328125,
		361.8388671875,
		1.0
	],
	"serial_number" : "f0xxxxxx",
	"stream_length_usec" : 0,
	"width" : 1280
}

Frame: 0, time: 1471.1999979999998s
Frame: 1, time: 1471.266374s
Frame: 2, time: 1471.432315s
Frame: 3, time: 1471.498691s
Frame: 4, time: 1471.5650679999999s
[Open3D INFO] Capture stopped.

**Comment by HelliceSaouli** [comment]
Hey, my realsense is at work i will test the new patch next week

**Comment by eltonhcchan** [comment]
@ssheorey I tested o3d.t.io.RealSenseSensor.enumerate_devices() as well. There is nothing return from this function.
