### ISSUE TITLE
How can i measure the height in one point cloud file ?

### ISSUE THREAD

**Issue by arkerman** [intel-isl/Open3D#2870]
I saw "compute_point_cloud_distance" example , but it just show the difference between source point cloud and target point cloud.
I wanna measure the height in one point cloud just like the pic i uploaded. How can i achieve it ?
by using compute_point_cloud_distance or other function
![height](https://user-images.githubusercontent.com/63221199/103841644-022eb580-50cf-11eb-901b-978227b6455a.png)

**Comment by yxlao** [comment]
How do you define hight? Do we know the point could's orientation? 

This might be related: [get_max_bound](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html?highlight=min_bound#open3d.geometry.PointCloud.get_max_bound) and [get_min_bound](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html?highlight=min_bound#open3d.geometry.PointCloud.get_min_bound) returns the max and min for each of the `x, y, z` coordinates.

**Comment by arkerman** [comment]
> How do you define hight? Do we know the point could's orientation?
> 
> This might be related: [get_max_bound](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html?highlight=min_bound#open3d.geometry.PointCloud.get_max_bound) and [get_min_bound](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html?highlight=min_bound#open3d.geometry.PointCloud.get_min_bound) returns the max and min for each of the `x, y, z` coordinates.

Height refers to the height distance between the upper plane and the lower plane. I just wanna to achieve the value. Here are my codes. How can i achieve the height value base on my codes? 

     import open3d as o3d
     import numpy as np

     print('testing~')
     pcd = o3d.io.read_point_cloud("C:/Users/lcs/Desktop/replay_88171_2020-12-31.txt", format = 'xyz') 
     print(pcd)   
     print(np.asarray(pcd.points))   

     voxel_down_pcd = pcd.voxel_down_sample(voxel_size=2)     
     print(np.asarray(voxel_down_pcd.points)[0])

     voxel_down_pcd.estimate_normals(
          search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))   

     def display_inlier_outlier(cloud, ind):      
         inlier_cloud = cloud.select_by_index(ind)
         outlier_cloud = cloud.select_by_index(ind, invert=True)

         print("Showing outliers (red) and inliers (gray): ")
         outlier_cloud.paint_uniform_color([1, 0, 0])       
         inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])  
         o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud],       
                                       window_name = 'rubber',
                                       zoom=0.3412,
                                       front=[0.4257, -0.2125, -0.8795],
                                       lookat=[2.6172, 2.0475, 1.532],
                                       up=[-0.0694, -0.9768, 0.2024])

     print("Statistical oulier removal")
 
     cl, ind = voxel_down_pcd.remove_statistical_outlier(nb_neighbors=2000, std_ratio=0.5)

     display_inlier_outlier(voxel_down_pcd, ind)

**Comment by arkerman** [comment]
Height refers to the height distance between the upper plane and the lower plane. I just wanna to achieve the value. Here are my codes. How can i achieve the height value base on my codes?
 import open3d as o3d  import numpy as np  print('testing~')  pcd = o3d.io.read_point_cloud("C:/Users/lcs/Desktop/replay_88171_2020-12-31.txt", format = 'xyz')   print(pcd)     print(np.asarray(pcd.points))     voxel_down_pcd = pcd.voxel_down_sample(voxel_size=2)       print(np.asarray(voxel_down_pcd.points)[0])  voxel_down_pcd.estimate_normals(       search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))     def display_inlier_outlier(cloud, ind):            inlier_cloud = cloud.select_by_index(ind)      outlier_cloud = cloud.select_by_index(ind, invert=True)      print("Showing outliers (red) and inliers (gray): ")      outlier_cloud.paint_uniform_color([1, 0, 0])             inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])        o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud],                                           window_name = 'rubber',                                    zoom=0.3412,                                    front=[0.4257, -0.2125, -0.8795],                                    lookat=[2.6172, 2.0475, 1.532],                                    up=[-0.0694, -0.9768, 0.2024])  print("Statistical oulier removal")  cl, ind = voxel_down_pcd.remove_statistical_outlier(nb_neighbors=2000, std_ratio=0.5)  display_inlier_outlier(voxel_down_pcd, ind)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "intel-isl/Open3D"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月7日(星期四) 上午10:29
收件人:&nbsp;"intel-isl/Open3D"<Open3D@noreply.github.com&gt;;
抄送:&nbsp;"1106848468"<1106848468@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [intel-isl/Open3D] How can i measure the height in one point cloud file ? (#2870)





 
How do you define hight? Do we know the point could's orientation?
 
This might be related: get_max_bound and get_min_bound returns the max and min for each of the x, y, z coordinates.

**Comment by theNded** [comment]
Please use `get_oriented_bounding_box`to obtain a box that contains the point cloud, and measure the height of the dimension of interest. You may want to use `remove_statistical_outlier` to remove the noise before extracting the bounding box.
