### ISSUE TITLE
cmake-gui source successful ,and open project ,but  when generator one of all, it just generater lib,but not exe 

### ISSUE THREAD

**Issue by UEBoy2019** [intel-isl/Open3D#2873]
i had try many times ,and now the visual studio 2019 's MSBuild.exe is awayls run  in back-process ,and i try cancer it  ,is not vailed,just kill it by task-manager process;
and the visual studio 2019 is always download something but i don't know what's .
i just want to run it successful. it was so difficult!!!!!!!!
i crying....................
thank u  man!!!!!!!!

**Comment by theNded** [comment]
Please fill in a new issue with a bug report template and identify your exact problems and setups. This issue is not quite comprehendible.
