### ISSUE TITLE
New rendering C++ example (headless rendering in Filament ) reuired

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2887]
Hello

Is it possible to give a few lines c++ code example on headless rendering in Filament?

It seems need to use FilamentRenderer like this
 `auto renderer = std::make_shared<visualization::rendering::FilamentRenderer>();` 
But what should be the detailed and correct way?

In Python it looks quite simple. But what dose the C++ code look like?

Thank you!

PS: I copy the Python code from [the v0.12.0 release note](http://www.open3d.org/author/administratorivcl-org/)

`
box = o3d.geometry.TriangleMesh.create_box(2, 2, 1)
render = rendering.OffscreenRenderer(640, 480)
render.scene.add_geometry("box", box, grey)
render.scene.camera.look_at([0, 0, 0], [0, 10, 0], [0, 0, 1])
img = render.render_to_image()
`

**Comment by prewettg** [comment]
The C++ code turns out to be ... not simple.  I have added an example, [`OffscreenRendering.cpp`](https://github.com/intel-isl/Open3D/blob/master/examples/cpp/OffscreenRendering.cpp) that should do it.
