### ISSUE TITLE
C++/clr with Open3D, LNK2038 Error

### ISSUE THREAD

**Issue by triplehoon** [intel-isl/Open3D#2889]
Hello

I'm trying to wrap open3d C++ code to .Net with C++/clr.

As C++/clr runtime library is MD(Multi-threaded DLL), LNK2038 error comes up when I link Open3D.lib.

I think because I build open3d with CMake with the Option

```cmake 
option(STATIC_WINDOWS_RUNTIME     "Use static (MT/MTd) Windows runtime"      ON)
```

But, when I re-build open3d with option

```cmake 
option(BUILD_SHARED_LIBS    "Build shared libraries"    ON)
option (STATIC_WINDOWS_RUNTIME     "Use static (MT/MTd) Windows runtime"      OFF)
```

The error still occurs. LNK2005
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"public: __cdecl std::exception::exception(class std::exception const &)" (??0exception@std@@QEAA@AEBV01@@Z) already defined in Open3d.lib(Open3D.dll)	Open3dTestWrapper	C:\Users\tpgns\source\repos\Open3dTestWrapper\MSVCRT.lib(throw_bad_alloc.obj)	1	
```
 Is there a way to make a dynamic library or dll files of Open3d?

Or is there another way you recommend to wrap open3d in .Net?

**Comment by yxlao** [comment]
Try cleaning the whole `build` directory and before re-building with different options.

**Comment by triplehoon** [comment]
@yxlao Thanks for your reply.

I managed to use Open3d Library in c++/clr by build open3d as a dynamic library and not build a shared library.

It works fine when I change CMakeList options as

```cmake
option(BUILD_SHARED_LIBS    "Build shared libraries"    OFF)
option (STATIC_WINDOWS_RUNTIME     "Use static (MT/MTd) Windows runtime"      OFF)
```

And I want to ask one more question. Is there any plan to make a wrapper for .NET?

**Comment by yxlao** [comment]
We don't have a plan for .NET yet.

**Comment by triplehoon** [comment]
@yxlao 
Thanks for your fast reply.
