### ISSUE TITLE
Building from source on Raspberrypi

### ISSUE THREAD

**Issue by rafal-mrowka** [intel-isl/Open3D#2895]
**Describe the bug**
Following procedure described here:
http://www.open3d.org/docs/release/arm.html

during "make" command I got: 

[ 60%] Linking CXX shared library ../../lib/Release/libOpen3D.so
/usr/bin/ld: ../../mkl_install/lib/libmkl_merged.a: error adding symbols: file format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [cpp/open3d/CMakeFiles/Open3D.dir/build.make:511: lib/Release/libOpen3D.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1350: cpp/open3d/CMakeFiles/Open3D.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

I've checked mkl zip content and i've found libmkl_merged.a. Is it possible that the file is only for x64/x86 architecture and not for amr64? What else could be the reason for this issue?

**To Reproduce**

1. git clone --recursive https://github.com/intel-isl/Open3D
2. cd Open3D
3. git submodule update --init --recursive
4. mkdir build && cd build
5. cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_CUDA_MODULE=OFF -DBUILD_GUI=OFF -DBUILD_TENSORFLOW_OPS=OFF -DBUILD_PYTORCH_OPS=OFF -DBUILD_UNIT_TESTS=ON -DPYTHON_EXECUTABLE=$(which python3)  -DBUILD_SHARED_LIBRATY=OFF -DBUILD_LIBREALSENSE=ON -DCMAKE_CXX_FLAGS_RELEASE=-faligned-new ..

6. make -j4

**Environment (please complete the following information):**

- Operating system: Linux raspberrypi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
- Python version: Python 3.7.3 (default, Jul 25 2020, 13:03:44)  [GCC 8.3.0] on linux
- Open3D version: 0.12.0
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version: gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1), clang version 7.0.1-8+rpi3+deb10u2 (tags/RELEASE_701/final)
Target: armv6k-unknown-linux-gnueabihf

**Comment by sanskar107** [comment]
Yes, that is true, MKL only works with x86, and will not work on arm64. Hence we use BLAS+LAPACK as an alternative to MKL. Please ensure you've installed all the dependencies listed here http://www.open3d.org/docs/release/arm.html#install-dependencies

**Comment by rafal-mrowka** [comment]
Thanks for your answer. Eventually I managed to compile and install it on my RPi. There are two tricks not described on your site (http://www.open3d.org/docs/release/arm.html).

1. In cmake you need to change options:  -DUSE_BLAS=ON -DBUILD_FILAMENT_FROM_SOURCE=ON
2. Add flag for the compiler: -faligned-new. The easiest way is by cmake: -DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG -**faligned-new**

Anyway, excellent work!!!

**Comment by HemantGhugeTarsyer** [comment]
A cmake command which helped me **build open3d from source** on **Raspberry Pi OS 64 bit**.

```
cmake \     
    -DCMAKE_BUILD_TYPE=Release \     
    -DBUILD_SHARED_LIBS=ON \     
    -DBUILD_CUDA_MODULE=OFF \     
    -DBUILD_GUI=OFF \     
    -DBUILD_TENSORFLOW_OPS=OFF \     
    -DBUILD_PYTORCH_OPS=OFF \     
    -DBUILD_UNIT_TESTS=ON \     
    -DCMAKE_INSTALL_PREFIX=~/open3d_install \     
    -DPYTHON_EXECUTABLE=$(which python3) \    
    -DUSE_BLAS=ON \    
    -DBUILD_FILAMENT_FROM_SOURCE=ON \    
    -DCMAKE_CXX_FLAGS_RELEASE=ON \    
    -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -faligned-new"  \    ..
```

**Comment by 9and3** [comment]
Amzing, thank you for sharing! How did you figure out the missing flags?

**Comment by Tarsyer-Hemant** [comment]
It was mentioned in [Build Failed on Jetson Nano #2606](https://github.com/isl-org/Open3D/issues/2606)

**Comment by dhruvsheth-ai** [comment]
Hi @Tarsyer-Hemant , is there a way to directly install the wheel? I have installed the wheel you provided using
```
pip install /home/pi/Downloads/open3d-0.13.0+3b97597a5-cp37-cp37m-linux_aarch64.whl
```
in my general directory, but it doesn't help. The import fails this way -
```bash
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/open3d/__init__.py", line 75, in <module>
    from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
ImportError: libOpen3D.so: cannot open shared object file: No such file or directory
```

**Comment by Tarsyer** [comment]
Please build it from source. I also faced the same problem and trying to solve it as soon as possible.

**Comment by Tarsyer-Hemant** [comment]
Please build it from source. I also faced the same problem and trying to solve it as soon as possible.

**Comment by funatsufumiya** [comment]
@dhruvsheth-ai @Tarsyer-Hemant 
To solve the ImportError, put `libOpen3D.so` to `/usr/lib/`, or put it to `/usr/local/lib/` and then add `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib` to your `.bash_profile`.
https://stackoverflow.com/questions/1099981/why-cant-python-find-shared-objects-that-are-in-directories-in-sys-path

**Comment by dhruvsheth-ai** [comment]
@funatsufumiya Thanks for the suggestion! I tried to search for the `libOpen3D.so` file in the Open3D folder and library, but couldn't locate it anywhere installed on my system from the whl provided here - 

> [open3d-0.13.0+3b97597a5-cp37-cp37m-linux_aarch64.zip](https://github.com/intel-isl/Open3D/files/6653560/open3d-0.13.0%2B3b97597a5-cp37-cp37m-linux_aarch64.zip)

Is there a way to install it on the system, after that I can follow the suggestion you've provided to solve the issue. 
Thanks for your help!

**Comment by funatsufumiya** [comment]
@dhruvsheth-ai 
This is full instruction to build Open3D 0.13.0 on Raspberry Pi OS 64 bit. 

```
sudo apt-get update -y
sudo apt-get install -y apt-utils build-essential python3-dev xorg-dev libglu1-mesa-dev libblas-dev liblapack-dev liblapacke-dev libsdl2-dev libc++-7-dev libc++abi-7-dev libxi-dev clang-7 libjpeg-dev gfortran

git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D
git checkout v0.13.0
git submodule update --init --recursive
mkdir build
cd build

# Note: please change configs about LIBREALSENS if you need
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_CUDA_MODULE=OFF \
    -DBUILD_GUI=OFF \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUILD_PYTORCH_OPS=OFF \
    -DBUILD_UNIT_TESTS=ON \
    -DPYTHON_EXECUTABLE=$(which python3) \
    -DUSE_BLAS=ON \
    -DBUILD_FILAMENT_FROM_SOURCE=ON \
    -DCMAKE_CXX_FLAGS_RELEASE=ON \
    -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -faligned-new"  \
    -DBUILD_LIBREALSENSE=OFF \
    -DUSE_SYSTEM_LIBREALSENSE=OFF \
    ..

# Build C++ library
make -j4

# Run tests (optional)
make tests -j4
./bin/tests --gtest_filter="-*Reduce*Sum*"

# Install C++ package (optional)
sudo make install

# Install Open3D python package (optional)
sudo make install-pip-package -j4
python3 -c "import open3d as o3d; print(o3d)"
```

**Comment by georgeswani** [comment]
Hi,
Thank you for the details shared. Is the wheel expected work in other machines without copying the libOpen3D.so file? we are not copying this file in x86 architecture, it is just the wheel from PyPi takes care of the dependent libraries, So thought of checking why that is different for arm64 builds when we follow the instructions clearly ?
Thanks
George
