### ISSUE TITLE
Can't use open3d on python 2.7

### ISSUE THREAD

**Issue by Mostafa-wael** [intel-isl/Open3D#2897]
**Error Message:**
`
pyrsistent requires Python '>=3.5' but the running Python is 2.7.17
`

**I ran to this error while using the following commands:**
```
pip  install open3d-python
pip2  install open3d-python
```
I tried running those commands on vs code terminal on Ubuntu 16.04
I have python 2.7 only on my system
---
**Here, are screenshots for the error**

![open3d error message](https://user-images.githubusercontent.com/56788883/104636143-91c5fc80-56ab-11eb-8d42-ebb71ff57766.png)
![open3d error message2](https://user-images.githubusercontent.com/56788883/104636151-94c0ed00-56ab-11eb-8d21-f6b3825e8fe1.png)

**Comment by ssheorey** [comment]
Sorry, Open3D doesn't support Python 2.7 any more, since it has reached End of Life. Please install Python 3 on your system. If you need Python 2 for other software, use `conda` or `pyenv`to manage multiple Python versions in your system.

**Comment by Mostafa-wael** [comment]
Okay, thanks for your response!

**Comment by Vemokaz** [comment]
Installing open3d in previous versions is available.
