### ISSUE TITLE
How can I get a fitness curve?

### ISSUE THREAD

**Issue by bigpehi** [intel-isl/Open3D#2901]
I want to use the fitness curve to optimize hyperparameters ，so I need all the fitnesses of RANSAC & ICP every step. How can I get all the fitnesses to draw a curve? Thank you in advance! 
And the same question with "inlier_rmse".

**Comment by reyanshsolis** [comment]
Hello, 
If you make Open3D using `make VERBOSE=1` or `make VERBOSE=1 install-pip-package` (for python), then LogDebug() statements from functions that are being called, will be printed. 

The registration functions ICP and RANSAC functions has such statemetns like,
```utility::LogDebug("ICP Iteration #{:d}: Fitness {:.4f}, RMSE {:.4f}", i,  result.fitness_, result.inlier_rmse_);```
which will help you, by printing these values at each itteration.

Here is an example output after I built Open3D using `make VERBOSE=1`
```
[Open3D DEBUG] ICP Iteration #0: Fitness 1.0000, RMSE 0.7064
[Open3D DEBUG] ICP Iteration #1: Fitness 1.0000, RMSE 1.0767
```
I hope you find this helpful, let me know if there is something else you want to know. 
Thanks.

**Comment by reyanshsolis** [comment]
One may also set the verbosity level, at the example or project level, by using this ```  utility::SetVerbosityLevel(utility::VerbosityLevel::Debug);``` in the main function. Checkout cpp and python examples in  Open3D/examples

**Comment by robertoruizmu** [comment]
But, how con I acces data in each iteration in :
utility::LogDebug("ICP Iteration #{:d}: Fitness {:.4f}, RMSE {:.4f}", i, result.fitness_, result.inlier_rmse_) 
using:
with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm: 
to make a plot?
