### ISSUE TITLE
how to use two PointClouds of AzureKinect to build mesh,runtime

### ISSUE THREAD

**Issue by UEBoy2019** [intel-isl/Open3D#2916]
i would like to know the step:
such as 👍 ,calibration...
help please.....

**Comment by ssheorey** [comment]
Hi @UEBoy2019 , please check out the [surface reconstruction tutorial](http://www.open3d.org/docs/latest/tutorial/geometry/surface_reconstruction.html) to create a mesh from a point cloud. 

You will need calibration to create the PointCloud from the RGBD images obtained from AzureKinect with the function [`create_from_point_cloud`](http://www.open3d.org/docs/latest/python_api/open3d.geometry.PointCloud.html?highlight=create_from_rgbd_image#open3d.geometry.PointCloud.create_from_rgbd_image)

**Comment by UEBoy2019** [comment]
@ssheorey  thanks a lot ,if i get two pointcloud from AzureKinect, and next ,how should i Registration it use ICP 。
first ,i must to be convert the same  coordinate system,right?
i am new pointcloud ,so maybe this question is stupid,sorry!

**Comment by ssheorey** [comment]
Your questions are specifically about RGBD odometry and registration. See the [scene reconstruction pipeline tutorial](http://www.open3d.org/docs/latest/tutorial/reconstruction_system/index.html) for a good overview of the entire processing pipeline.
