### ISSUE TITLE
Setting color grading from python

### ISSUE THREAD

**Issue by aweinmann** [intel-isl/Open3D#2918]
Hi,
I'm having hard time figuring out how I am supposed to set the color grading using the rendering api.

I create a offscreen renderer 
`render = o3d.visualization.rendering.OffscreenRenderer(1920, 1080)`

and then want to set the tone mapping using
`render.scene.get_view.set_color_grading`

but cant figure out how to set the parameters of this function to use linear tone mapping.

Thanks a lot in advance for any help!

**Comment by prewettg** [comment]
It looks like the enums were not exported to Python. This is fixed by #3193. Note that #3193 changes `get_view` to `view` to be consistent with being a property and not a function. After #3193 is merged you should be able to set color grading with (for example):
```
color_grading = rendering.ColorGrading(
            rendering.ColorGrading.Quality.HIGH,
            rendering.ColorGrading.ToneMapping.LINEAR)
o3dscene.view.set_color_grading(color_grading)
```
