### ISSUE TITLE
Labeling 3D Model

### ISSUE THREAD

**Issue by Zumbalamambo** [intel-isl/Open3D#2922]
It would be a nice option to be able to annotate the 3d model as in [Sketchfab](https://help.sketchfab.com/hc/en-us/articles/202512456-Annotations)  . It will certainly help in directly switching to a specific viewpoint by name or tag programmatically or visually.

**Comment by prewettg** [comment]
There is now a gui::Label3D class, which can be added with gui::SceneWidget::AddLabel() (or gui.SceneWidget.add_3d_label() in python):
```
import open3d as o3d
import open3d.visualization.gui as gui

app = gui.Application.instance
app.initialize()

w = app.create_window("Open3D - 3D Labels", 1024, 768)
widget3d = gui.SceneWidget()
w.add_child(widget3d)
widget3d.scene = o3d.visualization.rendering.Open3DScene(w.renderer)

# Add torus
torus = o3d.geometry.TriangleMesh.create_torus()
torus.compute_vertex_normals()
mat = o3d.visualization.rendering.Material()
mat.shader = "defaultLit"
widget3d.scene.add_geometry("Torus", torus, mat)

# Add torus vertices
pts = o3d.geometry.PointCloud(torus.vertices)
mat = o3d.visualization.rendering.Material()
mat.shader = "defaultUnlit"
mat.point_size = 5 * w.scaling
mat.base_color = (0, 0, 0, 1)
widget3d.scene.add_geometry("Points", pts, mat)


# Add 3D labels
for i in range(0, len(torus.vertices)):
    widget3d.add_3d_label(torus.vertices[i], str(i))

bounds = widget3d.scene.bounding_box
widget3d.setup_camera(60, bounds, bounds.get_center())

app.run()
```

It does not have any abilities to interact, e.g. via a mouse click. Also, it seems that the labels ignore the z-buffer, which I think is a bug.

**Comment by Zumbalamambo** [comment]
thank you!

**Comment by errissa** [comment]
@prewettg The 3D labels intentionally draw without depth testing so they are always visible. We should discuss internally if a depth-tested version of the labels is desirable.
