### ISSUE TITLE
Inconsistency in GPU and CPU TSDF

### ISSUE THREAD

**Issue by jsaisagar** [intel-isl/Open3D#2927]
Hi,

When I am using CUDA TSDF using python, I am getting 0 vertices extracted. While the same dataset, TSDF on CPU is succesfull and am getting nice mesh. I am attaching a sample depth frame for one camera for reference. May I know what might cause this issue?
Here are the parameters I am using for both CPU and GPU:

voxel_size = 4/1024
sdf_trunc = 0.04
block_resolution = 16
initial_block_count = 800
print('here 1')
volume = o3d.t.geometry.TSDFVoxelGrid(
{
'tsdf': o3d.core.Dtype.Float32,
'weight': o3d.core.Dtype.UInt16,
'color': o3d.core.Dtype.UInt16
},
voxel_size=voxel_size,
sdf_trunc=sdf_trunc,
block_resolution=block_resolution,
block_count=initial_block_count,
device=device)
Integrate function:
volume.integrate(
depth,color, intrinsic_gpu,
extrinsic_alignment_gpu,1000,5.0)

I have tried for different voxel sizes and intial block count as suggested in example. However, with any setting vertices are always 0.

PS: I captured depth map using Azure Kinect MKV reader
Thanks for any help,
Sai

![00000](https://user-images.githubusercontent.com/6646353/105345134-e4526c00-5c09-11eb-94b5-c2f2a16bfe99.png)

**Comment by theNded** [comment]
Is there any error thrown from the GPU side?

**Comment by jsaisagar** [comment]
Thanks for the reply.
 I didn't get any gpu error

**Comment by theNded** [comment]
That is weird... Would you mind sharing a minimal dataset that can reproduce the error?

**Comment by jsaisagar** [comment]
Please find the data in link [here](https://drive.google.com/drive/folders/1SN3S1nNYClUOUMzPpOmEZHkbU6m223Ts?usp=sharing). 

Extrinsic matrix is identity.

**Comment by theNded** [comment]
This issue is caused by https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L371, where we aggressively filter TSDF outliers by assuming any reliable vertex comes from at least a fusion of 3 frames. This consistently happens to me with both CPU and GPU. I will update the function by making this threshold customizable.

**Comment by jsaisagar** [comment]
Is there any workaround for this solution I can fix at my end?

On CPU my function is:

volume = o3d.integration.ScalableTSDFVolume(
	    voxel_length=4.0 / 1024.0,
	    sdf_trunc=0.04,
	    color_type=o3d.integration.TSDFVolumeColorType.RGB8)

for i in range(1):
		volume.integrate(
	        rgbd[i],intrinsics[i],
	        poses[i])

**Comment by theNded** [comment]
I'm fixing this in a PR. Meanwhile, you can change this parameter to 0 and compile the python library if you want to temporarily fix it: https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L371

**Comment by jsaisagar** [comment]
Got the same reconstruction now

**Comment by jsaisagar** [comment]
Hi,

Is there any performance report on TSDF with GPU vs CPU? May I what speed to expect (in terms of FPS) on GPU with 2MP RGBD resolution?

Thanks,
Sai
