### ISSUE TITLE
Please expose O3DVisualizer inherited functions in Python

### ISSUE THREAD

**Issue by dd-ff** [intel-isl/Open3D#2928]
As I can see in C++ code O3DVisualizer inherits Window class, but unfortunately it doesn’t expose some of the useful member functions of the Window class in Python API such as the “show_dialog” or “show_message_box”. I can understand the reasoning behind fencing of Window’s member variables and functions if you don’t want the users in messing up the GUI of the new visualizer but it really restricts in using the new visualizer on the app level.
If you enable us to access the window behind the O3DVisualizer then we can run new dialogs and messages when using actions added when calling new draw function and therefore augment user gui interaction.

**Comment by ssheorey** [comment]
Both [`show_dialog()`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.O3DVisualizer.html?highlight=show_dialog#open3d.visualization.O3DVisualizer.show_dialog) and [`show_message_box()`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.O3DVisualizer.html?highlight=show_dialog#open3d.visualization.O3DVisualizer.show_message_box) are already exposed in Python.

**Comment by prewettg** [comment]
Heh, they were just merged this morning from #2970. I added them (and a few others) as a result of this issue. Anyway, I believe this issue is resolved now.
