### ISSUE TITLE
Build from Source with Ninja fails

### ISSUE THREAD

**Issue by 3ddiddE** [intel-isl/Open3D#2937]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Using ninja as a buildsystem I cannot compile the project because of the following error:

> ninja: error: 'assimp/lib/libassimp.a', needed by 'bin/ViewGeometry', missing and no known rule to make it

**To Reproduce**

1. git clone --recurse-submodules repo
2. cd repo
3. mkdir build && cd build
4. cmake -GNinja ..
5. ninja

**Expected behavior**
No errors for the build process

**Screenshots**
![image](https://user-images.githubusercontent.com/45269130/105622257-47155480-5e10-11eb-83cc-db36649042f7.png)

**Environment (please complete the following information):**

- Operating system: Arch
- Python version: Python 3.9.1
- Open3D version: master
- Is this remote workstation?:no
- How did you install Open3D?: /
- Compiler version (if built from source): gcc 10.2.0

**Additional context**
With make as buildsystem, the build works fine. It seems that using make a rule is defined to download additional dependencies?!

**Comment by ssheorey** [comment]
Please paste the entire output of `ninja -v` (verbose mode).
