### ISSUE TITLE
Build from Source Make fails

### ISSUE THREAD

**Issue by 3ddiddE** [intel-isl/Open3D#2938]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Building the master branch from source fails with make buildsystem
> make[3]: *** No rule to make target 'libjpeg-turbo-install/lib/libturbojpeg.a', needed by 'lib/Release/Python/cuda/pybind.cpython-39-x86_64-linux-gnu.so'.

**To Reproduce**

1. clone repo
2. mkdir build && cd build
2. ccmake .. to enable CUDA
3. make

**Expected behavior**
No errors.

**Screenshots**

**Environment (please complete the following information):**

- Operating system: Arch
- Python version: 3.9.1
- Open3D version: master
- Is this remote workstation?: no
- How did you install Open3D?: /
- Compiler version (if built from source): gcc 10.2.0

**Additional context**
The 'missing' library is actually there.
Here is the directory tree.

> libjpeg-turbo-install
├── bin
│   ├── cjpeg
│   ├── djpeg
│   ├── jpegtran
│   ├── rdjpgcom
│   ├── tjbench
│   └── wrjpgcom
├── include
│   ├── jconfig.h
│   ├── jerror.h
│   ├── jmorecfg.h
│   ├── jpeglib.h
│   └── turbojpeg.h
├── lib64
│   ├── libjpeg.a
│   ├── libturbojpeg.a
│   └── pkgconfig
│       ├── libjpeg.pc
│       └── libturbojpeg.pc
└── share
    ├── doc
    │   └── libjpeg-turbo
    │       ├── example.txt
    │       ├── libjpeg.txt
    │       ├── LICENSE.md
    │       ├── README.ijg
    │       ├── README.md
    │       ├── structure.txt
    │       ├── tjexample.c
    │       ├── usage.txt
    │       └── wizard.txt
    └── man
        └── man1
            ├── cjpeg.1
            ├── djpeg.1
            ├── jpegtran.1
            ├── rdjpgcom.1
            └── wrjpgcom.1

9 directories, 29 files

**Comment by uneidelvizuu** [comment]
any updates?

**Comment by 3ddiddE** [comment]
`mv libjpeg-turbo-install/lib64 libjpeg-turbo-install/lib`
did the trick, then it successfully compiles!

**Comment by yxlao** [comment]
Fixed in https://github.com/intel-isl/Open3D/pull/3102
