### ISSUE TITLE
[Question] ARCore camera pose as camera extrinsic to open3d::integration::ScalableTSDFVolume

### ISSUE THREAD

**Issue by sajusathyan** [intel-isl/Open3D#2939]
I am trying to perform volumetric integration using Open3D ScalableTSDFVolume on Android devices with ARCore. Offboard reconstruction using the captured depth and camera images with Open3D pose estimation work very well. I am now trying to implement onboard reconstruction using pose data from ARCore. The resulting mesh is not generated correctly.

I believe the issue occurs due to fact that ARCore uses different coordinate system for camera poses than Open3D PinholeCameraParameters::extrinsic_ and I haven't probably translated it correctly.

- ARCore uses coordinate system similar to OpenGL - +X pointing right, +Y pointing right up, -Z pointing in the direction the camera is looking.
- As far as I understand, Open3D uses OpenCV coordinate system - +X pointing right, +Y pointing down, +Z pointing in the direction the camera is looking.

I implemented the following transformation to convert the ARCore pose to Open3D camera extrinsics:
     
    ArCamera_getPose(mArSession, arCamera, cameraPose);
    ArPose_getPoseRaw(mArSession, cameraPose, rawPose);
    float qx, qy, qz, qw, tx, ty, tz;
    qx = rawPose[0];
    qy = rawPose[1];
    qz = rawPose[2];
    qw = rawPose[3];
    tx   = rawPose[4];
    ty   = rawPose[5];
    tz  = rawPose[6];

    Eigen::AngleAxisd r(180 * (M_PI/180), Eigen::Vector3d::UnitX());

    Eigen::Matrix4d transform;
    transform.setIdentity();
    transform.topLeftCorner<3, 3>() = Eigen::Quaterniond(qw, qx, qy, qz).toRotationMatrix();
    transform.topRightCorner<3, 1>() = Eigen::Vector3d(tx, -ty, -tz);
    transform.topLeftCorner<3, 3>() = r.toRotationMatrix() * transform.topLeftCorner<3, 3>();

    pinholeCameraParams->extrinsic_ = transform.inverse();

Is this transformation correct?

**Comment by pablospe** [comment]
I believe `r` should be: [1 0 0; 0 -1 0; 0 0 -1]

```
transform.topLeftCorner<3, 3>()  = r.toRotationMatrix() * Eigen::Quaterniond(qw, qx, qy, qz).toRotationMatrix();
transform.topRightCorner<3, 1>() = r.toRotationMatrix() * Eigen::Vector3d(tx, ty, tz);
```

Is it necessary the inverse?

**Comment by pablospe** [comment]
Related issue https://github.com/intel-isl/Open3D/issues/1347

**Comment by sajusathyan** [comment]
@pablospe Thank you!

So the code is as following:

```
ArCamera_getPose(mArSession, arCamera, cameraPose);
ArPose_getPoseRaw(mArSession, cameraPose, rawPose);
float qx, qy, qz, qw, tx, ty, tz;
qx = rawPose[0];
qy = rawPose[1];
qz = rawPose[2];
qw = rawPose[3];
tx = rawPose[4];
ty = rawPose[5];
tz = rawPose[6];

Eigen::AngleAxisd r(180 * (M_PI/180), Eigen::Vector3d::UnitX());

Eigen::Matrix4d transform;
transform.setIdentity();
transform.topLeftCorner<3, 3>()  = r.toRotationMatrix() * Eigen::Quaterniond(qw, qx, qy, qz).toRotationMatrix();
transform.topRightCorner<3, 1>() = r.toRotationMatrix() * Eigen::Vector3d(tx, ty, tz);

pinholeCameraParams->extrinsic_ = transform;
```

**Comment by pablospe** [comment]
I noticed you are multiplying and dividing they 180, this should be equivalent:

      Eigen::AngleAxisd r(M_PI, Eigen::Vector3d::UnitX());

Alternatively, you could directly define:

    Matrix3d r;
    r << 1,  0,  0,
         0, -1,  0,
         0,  0, -1;

And replace `r.toRotationMatrix() ` by this new `r`:

    transform.topLeftCorner<3, 3>()  = r * Eigen::Quaterniond(qw, qx, qy, qz).toRotationMatrix();
    transform.topRightCorner<3, 1>() = r * Eigen::Vector3d(tx, ty, tz);


_(maybe better naming would help too)_

**Comment by pablospe** [comment]
I believe the line `transform.setIdentity();` is not needed, right?

**Comment by pablospe** [comment]
@theNded @sajusathyan I guess you can close this issue.

**Comment by sajusathyan** [comment]
> I believe the line `transform.setIdentity();` is not needed, right?

This is needed, or transform[3][3] must be set to 1

**Comment by sajusathyan** [comment]
> I noticed you are multiplying and dividing they 180, this should be equivalent:
> 
> ```
>   Eigen::AngleAxisd r(M_PI, Eigen::Vector3d::UnitX());
> ```
> 

True - but the reason is due to the fact that the code is clearer when we can see it is 180 degree in radians - the actual code is as following:

```
namespace {
    constexpr float kDegToRad = M_PI / 180.f;
} // namespace

Eigen::AngleAxisd r(180 * kDegToRad, Eigen::Vector3d::UnitX());
```
> Alternatively, you could directly define:
> 
> ```
> Matrix3d r;
> r << 1,  0,  0,
>      0, -1,  0,
>      0,  0, -1;
> ```
> 
> And replace `r.toRotationMatrix() ` by this new `r`:
> 
Agreed.
> ```
> transform.topLeftCorner<3, 3>()  = r * Eigen::Quaterniond(qw, qx, qy, qz).toRotationMatrix();
> transform.topRightCorner<3, 1>() = r * Eigen::Vector3d(tx, ty, tz);
> ```
> 
> _(maybe better naming would help too)_

**Comment by pablospe** [comment]
> > I believe the line `transform.setIdentity();` is not needed, right?
> 
> This is needed, or transform[3][3] must be set to 1

ah, true, I see, I thought it was a `[R t]_3x4` matrix rather than a 4x4 matrix.

**Comment by pankajbadatia** [comment]
Hello Guys 
Sorry to write in the closed issue.  But I have same issues . 

Can anyone write correct code or function for proper documentation  in python with reason?
Its difficult to understand from above discussion .It is really important issue.

 It  will be really big contributions .
 even i am facing issues because of arcore . coordinate system

**Comment by sith228** [comment]
> @pablospe Thank you!
> 
> So the code is as following:
> 
> ```
> ArCamera_getPose(mArSession, arCamera, cameraPose);
> ArPose_getPoseRaw(mArSession, cameraPose, rawPose);
> float qx, qy, qz, qw, tx, ty, tz;
> qx = rawPose[0];
> qy = rawPose[1];
> qz = rawPose[2];
> qw = rawPose[3];
> tx = rawPose[4];
> ty = rawPose[5];
> tz = rawPose[6];
> 
> Eigen::AngleAxisd r(180 * (M_PI/180), Eigen::Vector3d::UnitX());
> 
> Eigen::Matrix4d transform;
> transform.setIdentity();
> transform.topLeftCorner<3, 3>()  = r.toRotationMatrix() * Eigen::Quaterniond(qw, qx, qy, qz).toRotationMatrix();
> transform.topRightCorner<3, 1>() = r.toRotationMatrix() * Eigen::Vector3d(tx, ty, tz);
> 
> pinholeCameraParams->extrinsic_ = transform;
> ```

Hi, do you solve the issue? Is it works good?

**Comment by pankajbadatia** [comment]
It didn't worked for me..

**Comment by sith228** [comment]
> It didn't worked for me..

Try r = 
1 0 0
0 1 0
0 0 1

I dont know why, but it works more or less good
