### ISSUE TITLE
Capture depth buffer in the new viewer (Filament)

### ISSUE THREAD

**Issue by pablospe** [intel-isl/Open3D#2940]
Currently, there is no interface to render depth maps. The rendering handle in Open3D is hardcoded to 3 channels, so cannot produce usable depth maps: https://github.com/intel-isl/Open3D/blob/829c4e87aeb5df6608fc925e0aca7f55eb25bed1/cpp/open3d/visualization/rendering/Renderer.cpp#L98

Apparently the depth shader uses a heatmap from Filament:
https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/visualization/gui/Materials/depth.mat
https://github.com/google/filament/blob/master/shaders/src/common_graphics.fs#L96-L99
That looks bijective so we could retrieve the depth value; however, **the image is in uint8** so we would loose a lot in precision.

---------------

Possible solution? Apparently it's possible with Filament. See the following Issue:

**Depth Support**
https://github.com/google/filament/issues/3100#issuecomment-705154519

---------------

Here an **example** of what I was trying (`new_viewer_filament` branch):
https://github.com/pablospe/open3D_depthmap_example/blob/new_viewer_filament/main.py

This example renders an image given an intrinsic and extrinsic matrix, but when [Line 22](https://github.com/pablospe/open3D_depthmap_example/blob/new_viewer_filament/main.py#L22) is changed to `render_depth = True`, I can't get the expected depth map.

**Comment by pablospe** [comment]
I would appreciate any guidance in how to change the `depth.mat` share, if this is the solution. @prewettg @errissa

**Comment by prewettg** [comment]
You would need to pack the depth value into the RGB values (by bit-hacking in the shader), clone the Scene so that you can override the materials with the depth material (unless you are only ever rendering), fix the background object to not use the depth material but use a value that the shader turns into 1.0f, render to an image, restore the Scene's materials before it gets rendered again, and unpack the RGB channels and bit-twiddle them into a float.

Let me assure you that this is all a royal pain, as I just did the above a week ago in the `prewettg/recenter` branch (see PR #2905). So you could use `prewettg/recenter` or wait until it gets merged and use `master` and use `Renderer::RenderToDepthImage()`. Or you can wait until @errissa updates Filament to read back the depth buffer directly without this depth shader nonsense (since the buffer already exists).

**Comment by pablospe** [comment]
> Let me assure you that this is all a royal pain, as I just did the above a week ago in the `prewettg/recenter` branch (see PR #2905).

Thanks a lot for the effort! :)


> So you could use `prewettg/recenter` or wait until it gets merged and use `master` and use `Renderer::RenderToDepthImage()`.

I will give it a try.


> Or you can wait until @errissa updates Filament to read back the depth buffer directly without this depth shader nonsense (since the buffer already exists).

Is there a PR in the Filament side? (in order to track it)

**Comment by pablospe** [comment]
Something I think it is missing to have a completed set of tools to create depth maps properly (in a offline manner). It is to be able to modify the camera extrinsics. I did a python function in the example I sent before which do that:

https://github.com/pablospe/open3D_depthmap_example/blob/new_viewer_filament/main.py#L5-L15

```
def update_view(camera, intrinsics, extrinsic, width, height):
    camera.set_projection(intrinsics, 0.1, 100, width, height)
    R = extrinsic[:3, :3]
    t = extrinsic[:3, 3]

    eye = - R.T @ t
    up = -extrinsic[1, :3]     # Y camera axis in world frame
    front = -extrinsic[2, :3]  # Z camera axis in world frame
    center = eye - front       # any point on the ray through the camera center

    camera.look_at(center, eye, up)
```

It would makes sense to have this directly in C++. I was thinking it could be an extension (maybe an overloaded function) of the `SetProjection` function:
```
Camera::SetProjection(const Eigen::Matrix3d& intrinsics,
                      const Eigen::Matrix<float, 3, 4>& extrinsics,       // <-- new
                      double near,
                      double far,
                      double width,
                      double height)
```

**Comment by pablospe** [comment]
@errissa I was wondering if you could comment about the progress updating the Filament. Maybe I could also help or giving a try to your code. Do you have a patch somewhere? Thanks!

**Comment by orweiser-code** [comment]
Hey guys,
Any idea on when reading of the depth buffer will be possible?

**Comment by Skydes** [comment]
I am also very interested in this!

**Comment by orweiser-code** [comment]
@errissa any thoughts on if this is selected for development?

**Comment by pablospe** [comment]
@prewettg 

Related to this PR:
https://github.com/intel-isl/Open3D/pull/2905/files#r574935161
```
            .def("render_to_depth_image",
                 &PyOffscreenRenderer::RenderToDepthImage,
                 "Renders scene depth buffer to a float image, blocking until "
                 "the image is returned. Pixels range from 0 (near plane) to "
                 "1 (far plane)");
```
Pixels range from 0 (near plane) to 1 (far plane). Then, how do you obtain the actual depth value? Using the near and far plane? It seems there is a missing interface in python for this, or how can you get the near/far plane of the camera (in python)?

**Comment by pablospe** [comment]
Any idea how to get the correct depth values, in meters (if the reconstruction is metric) instead of 0 to 1?

**Comment by pablospe** [comment]
I've noticed that getting the depth buffer has been already implemented in PR https://github.com/intel-isl/Open3D/pull/3028
Also the python interface for `get_near()` and `get_far()` in PR https://github.com/intel-isl/Open3D/pull/3033

Now, I was trying to use this formula to convert from z_buff to actual z_values:

```
        img = render.render_to_depth_image()

        z_near = render.scene.camera.get_near()
        z_far = render.scene.camera.get_far()

        # conversion inside Open3D:
        # https://github.com/intel-isl/Open3D/blob/b467935323ca3f9b0d9b2672438bb88e396fd325/cpp/open3d/visualization/visualizer/VisualizerRender.cpp#L410-L413
        img_numpy = 2.0 * z_near * z_far / (z_far + z_near - (2.0 * np.asarray(img) - 1.0) * (z_far - z_near)
```

I've created an example in order to compare the old visualizer with the new one, and it seems that the depth buffer is incorrect (or I am doing something wrong). Here the example if someone wants to take a look:
https://github.com/pablospe/open3D_depthmap_example/tree/new_viewer_filament

```
git clone git@github.com:pablospe/open3D_depthmap_example.git -b new_viewer_filament
```

**Comment by prewettg** [comment]
@pablospe You're using the calculation for the old renderer. The depth values are read directly from Filament's depth buffer, which are 1 - depth. See gui/SceneWidget.cpp's use of RenderToDepthImage, which does 1 - depth on the resulting pixels/values of interest.

**Comment by pablospe** [comment]
@prewettg Thanks a lot for the answer. What I understand from the function comment is that the depth is from 0 to 1,  for that reason I thought to use that formula, and also from here: https://stackoverflow.com/questions/17659362/get-depth-from-camera-for-each-pixel#62792952

If the `depth` range is [0,1] then `1 - depth` doesn't seem to solve my problem. Basically, if an object is at 3 meters I would except to have a depth of 3.0.

Thanks again for the help!

**Comment by prewettg** [comment]
@pablospe A depth range in [0, 1] is typical for OpenGL implementations, but you can convert it to world space coordinates by calling o3dscene->GetCamera()->Unproject() and passing the depth value for z, and mouse (x, y) for x and y. You can then get the distance from the camera by subtracting the camera origin from the result of Unproject() and take the magnitude of the vector.

**Comment by Leerw** [comment]
> 
> 
> Something I think it is missing to have a completed set of tools to create depth maps properly (in a offline manner). It is to be able to modify the camera extrinsics. Here a python function (in the example I sent before) which do that:
> 
> https://github.com/pablospe/open3D_depthmap_example/blob/new_viewer_filament/main.py#L5-L15
> 
> ```
> def update_view(camera, intrinsics, extrinsic, width, height):
>     camera.set_projection(intrinsics, 0.1, 100, width, height)
>     R = extrinsic[:3, :3]
>     t = extrinsic[:3, 3]
> 
>     eye = - R.T @ t
>     up = -extrinsic[1, :3]     # Y camera axis in world frame
>     front = -extrinsic[2, :3]  # Z camera axis in world frame
>     center = eye - front       # any point on the ray through the camera center
> 
>     camera.look_at(center, eye, up)
> ```
> 
> It would makes sense to have this directly in C++. I was thinking it could be an extension (maybe an overloaded function) of the `SetProjection` function:
> 
> ```
> Camera::SetProjection(const Eigen::Matrix3d& intrinsics,
>                       const Eigen::Matrix<double, 3, 4>& extrinsics,       // <-- new
>                       double near,
>                       double far,
>                       double width,
>                       double height)
> ```

Similar to this, I use scene.camera.set_projection to use a ortho camera like this:

```python
scene.camera.set_projection(rendering.Camera.Projection.Ortho, -0.1, 0.1, -0.1, 0.1, 0.1, 100.0)
```
this raised an error:
```
in coid __decl filament::FCamera::setProjection(...)
reason: Camera preconditions not met. Using default projection.
```

I do not now why this bug exists. Could you please look at this? @prewettg

**Comment by ZyuZyuZyu** [comment]
> > Something I think it is missing to have a completed set of tools to create depth maps properly (in a offline manner). It is to be able to modify the camera extrinsics. Here a python function (in the example I sent before) which do that:
> > https://github.com/pablospe/open3D_depthmap_example/blob/new_viewer_filament/main.py#L5-L15
> > ```
> > def update_view(camera, intrinsics, extrinsic, width, height):
> >     camera.set_projection(intrinsics, 0.1, 100, width, height)
> >     R = extrinsic[:3, :3]
> >     t = extrinsic[:3, 3]
> > 
> >     eye = - R.T @ t
> >     up = -extrinsic[1, :3]     # Y camera axis in world frame
> >     front = -extrinsic[2, :3]  # Z camera axis in world frame
> >     center = eye - front       # any point on the ray through the camera center
> > 
> >     camera.look_at(center, eye, up)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It would makes sense to have this directly in C++. I was thinking it could be an extension (maybe an overloaded function) of the `SetProjection` function:
> > ```
> > Camera::SetProjection(const Eigen::Matrix3d& intrinsics,
> >                       const Eigen::Matrix<double, 3, 4>& extrinsics,       // <-- new
> >                       double near,
> >                       double far,
> >                       double width,
> >                       double height)
> > ```
> 
> Similar to this, I use scene.camera.set_projection to use a ortho camera like this:
> 
> ```python
> scene.camera.set_projection(rendering.Camera.Projection.Ortho, -0.1, 0.1, -0.1, 0.1, 0.1, 100.0)
> ```
> 
> this raised an error:
> 
> ```
> in coid __decl filament::FCamera::setProjection(...)
> reason: Camera preconditions not met. Using default projection.
> ```
> 
> I do not now why this bug exists. Could you please look at this? @prewettg

Facing the same issue too. I am using python Open3D v0.15.2. 
When I want to set visualization.rendering.Camera Projection type Ortho, this error came out.
I have searched the source code for more information, but cant find the error reference.
`in void filament::FCamera::setProjection(Camera::Projection, double, double, double, double, double, double):100
reason: Camera preconditions not met. Using default projection.
#0      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3f54c3500 _ZN5utils7details8panicLogEPKcS2_iS2_z + 480
#1      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3f53d3e1b (null) + 140685768211995
#2      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3ee44668e _ZN6open3d13visualization9rendering14FilamentCamera13SetProjectionEddddNS1_6Camera7FovTypeE + 62
#3      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3ee2f5148 _ZN6open3d13visualization3gui11SceneWidget4DrawERKNS1_11DrawContextE + 1800
#4      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3ee30bd46 (null) + 140685649952070
#5      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3ee30eb27 _ZN6open3d13visualization3gui6Window8DrawOnceEb + 919
#6      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3ee30f414 _ZN6open3d13visualization3gui6Window6OnDrawEv + 36
#7      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3f53cd388 _glfwPlatformPollEvents + 1416
#8      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3f53ce3a5 _glfwPlatformWaitEventsTimeout + 517
#9      pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3ee2e03db _ZN6open3d13visualization3gui16GLFWWindowSystem17WaitEventsTimeoutEd + 27
#10     pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3ee2d0271 _ZN6open3d13visualization3gui11Application19ProcessQueuedEventsERNS2_11EnvUnlockerE + 81
#11     pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3ee2d0a1b _ZN6open3d13visualization3gui11Application10RunOneTickERNS2_11EnvUnlockerEb + 443
#12     pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3eb6c8906 (null) + 140685603539206
#13     pybind.cpython-38-x86_64-linux-gnu.so     0x7ff3eb47f675 (null) + 140685601142389
#14     python                              0x55deb23db834 PyCFunction_Call + 84
#15     python                              0x55deb239cda8 _PyObject_MakeTpCall + 344
#16     python                              0x55deb23d4712 (null) + 94414961461010
#17     python                              0x55deb2377149 (null) + 94414961078601
`
Any suggestion here?
