### ISSUE TITLE
Embedding Visualizer view controls in SceneWidget

### ISSUE THREAD

**Issue by lozino** [intel-isl/Open3D#2942]
Hi all,

Is there a way of utilizing the same view controls used in Visualizer in a SceneWidget? More specifically,
I am referring to the following controls (taken from the docs):

>  -- Mouse view control --
>   Left button + drag         : Rotate.
>   Ctrl + left button + drag  : Translate.
>   Wheel button + drag        : Translate.
>   Shift + left button + drag : Roll.
>   Wheel                      : Zoom in/out.

I am particularly interested in the camera roll feature, which seems absent (correct me if I am wrong) in all
SceneWidget view controls (ROTATE_CAMERA, FLY etc...).

Thank you.

**Comment by prewettg** [comment]
I think the documentation is incorrect, shift + left drag is dolly in/out.  On macOS option + left drag is roll; on Windows/Linux it should be the windows key + left drag.

**Comment by prewettg** [comment]
Ah, I see the problem. The documentation your referencing is for visualization::visualizer::Visualizer, not the documentation in visualization::visualizer::GuiVisualizer (which uses gui::SceneWidget). You can find the full list of controls by running the Open3D app, and doing Help >> Show Controls.

**Comment by nchodosh** [comment]
Where do you find the help menu? None of the examples have it when I run them
