### ISSUE TITLE
Issue installing open3d

### ISSUE THREAD

**Issue by filorigen** [intel-isl/Open3D#2943]
Hi,
I am new in programming and python and I want to install open3D and I have got the following message:
CondaHTTPError: HTTP 500 INTERNAL SERVER ERROR for url <https://conda.anaconda.org/open3d-admin/win-64/repodata.json>
Elapsed: 00:00.799376
CF-RAY: 6171f610eb790676-LHR

A remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.

**Comment by ssheorey** [comment]
Please [install from PyPI](http://www.open3d.org/docs/latest/getting_started.html#pip-pypi). We are deprecating `conda`.
`pip install open3d`

You can re-open the issue or open another one if you still have problems.
