### ISSUE TITLE
ICP registration gives always zero values

### ISSUE THREAD

**Issue by arudomanenko** [intel-isl/Open3D#2945]
Hi! I have a task to find an orientation of object on point cloud. My objects is very simple - just wood plank (this about is as a cube)
So I am using open3d ICP point2point registration to find a rotation matrix of object. To do this, I saved reference point cloud plank with zero rotation) to a file and loading it as a source of ICP. Also the target of ICP is object on my cloud
But I have a very strange result - it is always zero! I don know is it a bug or just ICP really don't work in my case, but I will be thanksfull if you can help me. Thanks!

To Reproduce:
run the code below

Expected behavior
Rotation for 45 degrees around z axis

Screenshots is attached

Environment (please complete the following information):

- Operating system:Ubuntu 18.04
- Python version: python 3.8.6
- Open3D version: 0.12
- Is this remote workstation?: no
- How did you install Open3D?: pip

Additional context

    import open3d as o3d
    import numpy as np
    import copy

    def draw_registration_result(source, target, transformation, point_size):
        source_temp = copy.deepcopy(source)
        target_temp = copy.deepcopy(target)
        source_temp.paint_uniform_color([1, 0.706, 0])
        target_temp.paint_uniform_color([0, 0.651, 0.929])
        source_temp.transform(transformation)
        o3d.visualization.draw([source_temp, target_temp], point_size=point_size)

    def get_orientation_icp(icp_reference: o3d.geometry.PointCloud):
        pcd = o3d.io.read_point_cloud("../files/test.ply")
        pcd = pcd.voxel_down_sample(70)
        pcd.remove_radius_outlier(5, 30)

        threshold = 1e-2

        trans_init = np.array([[1., 0., 0., 0],
                           [0., 1., 0., 0],
                           [0., 0., 1., 0],
                           [0., 0., 0., 1.]])

        # aling objects to center
        translation_vec = pcd.get_center() - icp_reference.get_center()
        icp_reference.translate(translation_vec)

        reg_p2p = o3d.pipelines.registration.registration_icp(icp_reference, pcd, threshold, trans_init,
                                                          o3d.pipelines.registration.
                                                          TransformationEstimationPointToPoint())

        print(reg_p2p)

        rotation = reg_p2p.transformation[:-1, :-1].reshape((3, 3))

        return rotation

     ICP_REFERENCE = o3d.io.read_point_cloud("../files/icp_reference.ply")
     get_orientation_icp(ICP_REFERENCE)

Registration result:
source and target after preprocessing. Object is rotated on 45 degrees

![to_git](https://user-images.githubusercontent.com/26182779/105737730-58ad4800-5f47-11eb-8628-f9ab325fa9c1.png)

    RegistrationResult with fitness=0.000000e+00, inlier_rmse=0.000000e+00, and correspondence_set size of 0
    Access transformation to get result.

**Comment by arudomanenko** [comment]
In addition, I tried to run exactly the same code for other point clouds (in attach) and it also didn't work for me:

Result (with result matrix):

    RegistrationResult with fitness=2.712674e-06, inlier_rmse=0.000000e+00, and correspondence_set size of 1
    Access transformation to get result.
    [[ 1.          0.          0.         -0.00601707]
     [ 0.          1.          0.         -0.00594054]
     [ 0.          0.          1.          0.        ]
     [ 0.          0.          0.          1.        ]]

![to_git_2](https://user-images.githubusercontent.com/26182779/105835440-dd967100-5fdc-11eb-8a3b-45a46ea02a58.png)
![to_git_3](https://user-images.githubusercontent.com/26182779/105835444-dec79e00-5fdc-11eb-8010-4e2e13c52003.png)

**Comment by reyanshsolis** [comment]
Hi, 
I see there are no correspondences detected between source and target point cloud. You may try increasing the value of the "threshold" variable (which is actually the maximum distance in which the search tried to find a correspondence for each point), to get more correspondences. Let me know what happens.

This is a tutorial you may refer to for your project: http://www.open3d.org/docs/release/tutorial/pipelines/icp_registration.html

Thanks,
Rishabh

**Comment by arudomanenko** [comment]
Hi @sanskar107! Thanks for the reply! I have tried to set 'threshold' as 1e-2, 0.1, 1, 10, 25, 50, 75, 100 and 1000 (why not?))
But result is always the same for cloud with cubes and for cloud with floor

**Comment by reyanshsolis** [comment]
One possibility is that the downsampling parameter is too high, therefore the point cloud might be having very few points. Could you upload the point cloud to some drive and share it with me, so that I can check myself once.

**Comment by arudomanenko** [comment]
Ok, I see. Thank you for your help! I will provide you a link to drive with point clouds with original size and color
https://drive.google.com/drive/folders/0Bxde39e9SVqTfkhleG0wLUtkNDJNS3R3dGRQVHlTc2ZXSEFrZ3Z1TFVoZkp3ZUgxWU5oVVE?usp=sharing

**Comment by reyanshsolis** [comment]
It's working fine on the point cloud you sent, on your code, as well as on the code given in the tutorial. 
This is on your code: 
![Screenshot from 2021-01-27 01-28-08](https://user-images.githubusercontent.com/32535717/105898023-f6377300-603e-11eb-9aa2-4e20f69b2d4d.png)

This is the tutorial code with your pointcloud:
[Reading data]:
![Screenshot from 2021-01-27 01-21-11](https://user-images.githubusercontent.com/32535717/105898121-1404d800-603f-11eb-927e-bbeccbf2782c.png)
[Initial alignment]:
![Screenshot from 2021-01-27 01-21-35](https://user-images.githubusercontent.com/32535717/105898159-1ff09a00-603f-11eb-8b55-2d524f751863.png)
[Point to Plane ICP with default ICPConvergenceCriteria]:
![Screenshot from 2021-01-27 01-21-44](https://user-images.githubusercontent.com/32535717/105898243-3565c400-603f-11eb-93a5-1f9c1d86877e.png)
[Point to Plane ICP with modified ICPConvergenceCriteria]:
![Screenshot from 2021-01-27 01-22-05](https://user-images.githubusercontent.com/32535717/105898283-41ea1c80-603f-11eb-9868-30d0d88c24d3.png)

As the point cloud contains only planes, it takes more iterations to fit, as the change in rmse / fitness, in that case, is very less between iterations. That's why in many applications, planes are removed before using ICP operation.

Anyways, your code seems to be working on the point cloud you shared, with a threshold = 10, try changing ICPConvergenceCriteria according to your need. 

Thanks,
Rishabh

**Comment by arudomanenko** [comment]
I see, am I right, that it doesn't working because of high voxel size?
Thank you a lot)

**Comment by reyanshsolis** [comment]
Hey @arudomanenko,
Yes, that might be the case, you have to adjust voxel size, maximum distance threshold (the distance range in which neighbour will look for the correspondences), and ICPConvergenceCriteria(double relative_fitness = 1e-6, double relative_rmse = 1e-6, int max_iteration = 30). 

If you are looking at 0 or very few correspondences, then you might be providing a bad initial transformation estimate, maximum distance threshold might be very less, or voxel downsampling factor might be too large. 
When you are getting correspondences, and you see that it is converging, but alignment is not complete / you want to further align the point cloud data, you may increase the max_iteration parameter in ICPConvergenceCriteria(). 

relative_fitness If the relative change (difference) of fitness score is lower than relative_fitness, the iteration stops. 
relative_rmse If the relative change (difference) of inliner RMSE score is lower than relative_rmse, the iteration stops. 
max_iteration Maximum iteration before iteration stops.

If you want to observe fitness and rmse at each step, then you may refer this #2901.
Also, if you are always getting Identity as transformation output, you might be passing the same point cloud as the source and target point cloud.

I hope this will help you debug your code in the future.
Thanks,
Rishabh
