### ISSUE TITLE
ImportError: generic_type: type "VerbosityLevel" is already registered

### ISSUE THREAD

**Issue by altimerk** [intel-isl/Open3D#2950]
after 

`from open3d.cuda.pybind.geometry import PointCloud`

got an error:

`Python 3.8.6 (default, Dec  4 2020, 17:59:05) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

from open3d.cuda.pybind.geometry import PointCloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: generic_type: type "VerbosityLevel" is already registered!`

**To Reproduce**

1. python3 -m venv venv
2. source venv/bin/activate
3. pip install open3d
4.  python
5. from open3d.cuda.pybind.geometry import PointCloud

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04.5
- Python version: Python 3.8.6
- Open3D version: 0.12.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by sanskar107** [comment]
`open3d.cuda..` is not exposed, Please use
```
import open3d as o3d
o3d.geometry.PointCloud`

**Comment by altimerk** [comment]
Thanks, @sanskar107! It works now. But why it is not posible:
 
`import open3d.geometry.PointCloud as PointCloud`?

**Comment by altimerk** [comment]
`import open3d.geometry.PointCloud as PointCloud` 
works again after nvidia driver has been been reinstalled. nvidia-drivers-460.x +cuda 10.2 caused error despite of document https://docs.nvidia.com/deploy/cuda-compatibility/index.html which says nvidia-drivers is backward compatible with older cuda versions. After installing nvidia-drivers-440.x its now working again.
