### ISSUE TITLE
how to use VisualizerWithEditing to crop point cloud step by step in Python?

### ISSUE THREAD

**Issue by liuliu66** [intel-isl/Open3D#2952]
The example to crop point cloud using VisualizerWithEditing is directly selecting vertex and crop by polygon. 
 Is there any way to step by step achieve this process? e.g. create VisualizerWithEditing() object. apply pick_points (or other polygon selection function) to get the point set that describe the selected point cloud, finally apply crop function to get the cropped one. so on

Thanks !

**Comment by prewettg** [comment]
You could use VisualizerWithVertexSelection, which just returns the selected points. Alternatively, if you do not need polygon selection, you can use the new O3DVisualizer, which also returns the selected points. You can add an action to get a button / menu entry that will let you provide a callback function in which you can get the selection and crop. See the `examples/python/gui/draw.py` / `examples/cpp/Draw.cpp` examples for examples of adding an action and getting the points from a callback.
