### ISSUE TITLE
feeding my camera intrinsics to o3d.geometry.PointCloud.create_from_depth_image

### ISSUE THREAD

**Issue by monacv** [intel-isl/Open3D#2954]
The following code doesn't work since I changed it such that it would use my own camera intrinsics:

```
import open3d as o3d
import matplotlib.pyplot as plt
import numpy as np
import pickle
import pyrealsense2 as rs
def set_intrinsics(intrinsics_dict):
    intrinsics = rs.intrinsics()
    intrinsics.width = intrinsics_dict['width']
    intrinsics.height = intrinsics_dict['height']
    intrinsics.ppx = intrinsics_dict['ppx']
    intrinsics.ppy = intrinsics_dict['ppy']
    intrinsics.fx = intrinsics_dict['fx']
    intrinsics.fy = intrinsics_dict['fy']
    intrinsics.model = intrinsics_dict['model']
    intrinsics.coeffs = intrinsics_dict['coeffs']
    return intrinsics

camera = pickle.load(open('camera.pkl', 'rb'))

color_intrinsics = set_intrinsics(camera['color_intrinsics'])
print('color intrinsics: ', color_intrinsics)

raw_depth = o3d.io.read_image('depth_images/000248.png')
pcd = o3d.geometry.PointCloud.create_from_depth_image(raw_depth, color_intrinsics)
print(np.asarray(pcd.points)[1,:])
o3d.visualization.draw_geometries([pcd])
```

The error is:

```
color intrinsics:  [ 1280x720  p[644.629 358.26]  f[925.577 924.895]  Inverse Brown Conrady [0 0 0 0 0] ]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-9296723c7a18> in <module>
      5 
      6 raw_depth = o3d.io.read_image('depth_images/000248.png')
----> 7 pcd = o3d.geometry.PointCloud.create_from_depth_image(raw_depth, color_intrinsics)
      8 print(np.asarray(pcd.points)[1,:])
      9 o3d.visualization.draw_geometries([pcd])

TypeError: create_from_depth_image(): incompatible function arguments. The following argument types are supported:
    1. (depth: open3d::geometry::Image, intrinsic: open3d.cuda.pybind.camera.PinholeCameraIntrinsic, extrinsic: numpy.ndarray[float64[4, 4]] = array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), depth_scale: float = 1000.0, depth_trunc: float = 1000.0, stride: int = 1, project_valid_depth_only: bool = True) -> open3d.cuda.pybind.geometry.PointCloud

Invoked with: Image of size 1280x720, with 1 channels.
Use numpy.asarray to access buffer data., [ 1280x720  p[644.629 358.26]  f[925.577 924.895]  Inverse Brown Conrady [0 0 0 0 0] ]

```?

This is despite the fact that this other code works and visualizes a 3d pointcloud. 


```
raw_depth = o3d.io.read_image('depth_images/000248.png')
pcd = o3d.geometry.PointCloud.create_from_depth_image(raw_depth,
o3d.camera.PinholeCameraIntrinsic(
                                  o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)
                                , np.identity(4), depth_scale=1000.0, depth_trunc=1000.0)
pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
print(np.asarray(pcd.points)[1,:])
o3d.visualization.draw_geometries([pcd])
```


How can I feed color_intrinsics of my camera to the `o3d.geometry.PointCloud.create_from_depth_image`?

**Comment by sanskar107** [comment]
`intrinsics` as a `dict` won't work as `create_from_depth_image` expects a `open3d.camera.PinholeCameraIntrinsic` object.
You can convert your intrinsic to `PinholeCameraIntrinsic` object. Refer to this link for constructor. http://www.open3d.org/docs/release/python_api/open3d.camera.PinholeCameraIntrinsic.html#open3d.camera.PinholeCameraIntrinsic 

Basically use `intrinsic = o3d.camera.PinholeCameraIntrinsic(width, height, fx, fy, cx, cy)`

**Comment by monacv** [comment]
@sanskar107 
Thanks a lot for your prompt reply.

I tried what you mentioned and the code throws no error, however, using my own camera intrinsics produces a very terrible output which is no way similiar to actual photo. While, when I use your own code, my pointcloud is much better and more resembles the actual photo. What are your thoughts on this and do you know how I could fix it?

The code with my own camera intrinsics:
import open3d as o3d
import matplotlib.pyplot as plt
import numpy as np
import pickle
import pyrealsense2 as rs


def set_intrinsics(intrinsics_dict):
    intrinsics = rs.intrinsics()
    intrinsics.width = intrinsics_dict['width']
    intrinsics.height = intrinsics_dict['height']
    intrinsics.ppx = intrinsics_dict['ppx']
    intrinsics.ppy = intrinsics_dict['ppy']
    intrinsics.fx = intrinsics_dict['fx']
    intrinsics.fy = intrinsics_dict['fy']
    intrinsics.model = intrinsics_dict['model']
    intrinsics.coeffs = intrinsics_dict['coeffs']
    return intrinsics

camera = pickle.load(open('../layout_estimation/datasets/processed/demoroom/camera.pkl', 'rb'))
color_intrinsics = set_intrinsics(camera['color_intrinsics'])

type(color_intrinsics)

## pyrealsense2.intrinsics

color_intrinsics.fx
## 925.577392578125

intrinsics = o3d.camera.PinholeCameraIntrinsic(color_intrinsics.width,
                                              color_intrinsics.height,
                                              color_intrinsics.fx,
                                              color_intrinsics.fy,
                                              color_intrinsics.ppx,
                                              color_intrinsics.ppy)

print('color intrinsics: ', color_intrinsics)

raw_depth = o3d.io.read_image('depth_images/000248.png')
pcd = o3d.geometry.PointCloud.create_from_depth_image(raw_depth, intrinsics)
print(np.asarray(pcd.points)[1,:])
o3d.visualization.draw_geometries([pcd])

---------------

color intrinsics:  [ 1280x720  p[644.629 358.26]  f[925.577 924.895]  Inverse Brown Conrady [0 0 0 0 0] ]
[-2.38511913 -1.36464274  3.523     ]

and the code with your preset intrinsics:
```

raw_depth = o3d.io.read_image('depth_images/000248.png')
pcd = o3d.geometry.PointCloud.create_from_depth_image(raw_depth,
o3d.camera.PinholeCameraIntrinsic(
                                  o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)
                                , np.identity(4), depth_scale=1000.0, depth_trunc=1000.0)
pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
print(np.asarray(pcd.points)[1,:])
o3d.visualization.draw_geometries([pcd])
```

**Comment by vsg-root** [comment]
@monacv, I have the same problem. Did you manage to solve it? I used a camera with the following intrinsic values:
"width": 840,
"height": 480,
"ppx": 422,649,
"ppy": 241,433,
"fx": 241,433,
"fy": 426,341,
"model": "Conrady Marrom",
"coefficients": [0 0 0 0 0],
When I pass these values, the generated point cloud showed unwanted deformation.
