### ISSUE TITLE
retrieve camera intrinsics for Azure Kinect?

### ISSUE THREAD

**Issue by zapaishchykova** [intel-isl/Open3D#2956]
Hi! Thanks for your awesome work!
I would like to know if there is any way to retrieve camera intrinsic for Azure Kinect in the same way as for Intel cameras?
related to issue #1183

**Comment by ivankrstev7** [comment]
@zapaishchykova Did you by any chance find a way to retrieve the intrinsics? I am also trying to find it for the hololens

**Comment by zapaishchykova** [comment]
yes it did! i build from source azure sdk with visual studio using this https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md and then I was able to build a calibration_info.exe https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/examples/calibration which outputs the intrinsics. Hope this helps!
