### ISSUE TITLE
read_triangle_mesh saturate ram

### ISSUE THREAD

**Issue by mett96** [intel-isl/Open3D#2963]
[mesh.zip](https://github.com/intel-isl/Open3D/files/5890885/mesh.zip)

**Describe the bug**
I'm using open3d library in python.
I'm trying to load an stl file thanks to the `read_triangle_mesh` function.
With a determinate file the loading freeze and the ram starts to be fulled by python 

**To Reproduce**
Try the same function with the attached file

**Environment:**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6.9
- Open3D version:  0.11.2
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Note**
The attached file is zipped

[mesh.zip](https://github.com/intel-isl/Open3D/files/5890891/mesh.zip)

**Comment by yxlao** [comment]
This seems to be related to https://github.com/intel-isl/Open3D/pull/2506 . Please try the `0.12.0` version.

**Comment by mett96** [comment]
Yes it fix the problem! thank you very mush!!!
