### ISSUE TITLE
Not able to use VisualizerWithEditing with new gui api

### ISSUE THREAD

**Issue by saikiran321** [intel-isl/Open3D#2967]
Hi, I'm trying to add VisualizerWithEditing to new gui api. But i'm facing difficulty.

To create a normal editor in open3d, I use

```
vis = o3d.visualization.VisualizerWithEditing()
vis.create_window("test")
vis.add_geometry(pcd)
vis.run()  # user picks points
vis.clear_geometries()
vis.close()
vis.destroy_window()
return vis.get_picked_points()

```

to use a new gui api

```
import open3d as o3d
import open3d.visualization.gui as gui
import open3d.visualization.rendering as rendering
import open3d.visualization as vis
def main():
    gui.Application.instance.initialize()

    app = gui.Application.instance


    vis = o3d.visualization.O3DVisualizer("o3d",640,480)

    window = app.add_window(vis)

    app.run()

if __name__ == "__main__":
    main()

```

How do we connect **VisualizerWithEditing** to  **gui.Application.instance.**? 

Thanks

**Comment by prewettg** [comment]
The new GUI API replaces VisualizerWith* and is not compatible with it. However, O3DVisualizer includes almost all of the features of the old visualizers. You can see some examples in (examples/python/gui/draw.py)[https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py]; this uses the easier `draw()` function (replacement for `draw_geometries()`, but if you take a look at the implementation of `draw()` ((python/open3d/visualization/draw.py)[https://github.com/intel-isl/Open3D/blob/master/python/open3d/visualization/draw.py]) you can see an example of using O3DVisualizer directly.

**Comment by saikiran321** [comment]
@prewettg  Thanks. I ran  draw.py [https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py]. I'm more interested in selection points hence I switched to selection tab. How ever when I click on a point  some random point is being clicked. How many time I click that random point is only being selected constantly.

I use Mac, hence using cmd+click to select point. I have added screenshots below and marked them with a red border for reference. 

<img width="1136" alt="Screenshot 2021-01-30 at 12 33 21 AM" src="https://user-images.githubusercontent.com/6077731/106317370-40fdf880-6294-11eb-938f-f4cf3f955d97.png">
<img width="1136" alt="Screenshot 2021-01-30 at 12 34 52 AM" src="https://user-images.githubusercontent.com/6077731/106317383-44917f80-6294-11eb-8eee-773c4aef2281.png">

**Comment by prewettg** [comment]
Does your Mac use a Radeon Pro 560 by any chance? (If not, can you send us your macOS version and graphics card version?) We just recently discovered that we are getting completely incorrect results from reading color buffers back from Filament on Macs with that setup. If you are encountering this problem, then you should see the 0-th vertex being selected. Unfortunately, if this is the case we do not have a workaround yet, as it is a Filament or driver problem and we have not been able to determine where the problem is yet. But do let us know if this is the case, so that we can open an issue for this.

**Comment by saikiran321** [comment]
This is the same issue i'm facing currently. I use mac with Radeon pro 5300, my pc specifications are as below
Graphics: Radeon Pro 5300M. 

Os:  10.15.7
Processor : i7
Ram: 16Gb

**Comment by ivan-gallego** [comment]
I'm facing a similar issue with a MacBook Pro M1 (2020). 

After running the following script (simplified version of draw.py):

![Screenshot 2021-02-23 at 16 32 45](https://user-images.githubusercontent.com/13086014/108866977-036f5f80-75f5-11eb-8117-ec5846446df3.png)

I selected some of the points and the pink point seems to appear at random locations:

<img width="1021" alt="Screenshot 2021-02-23 at 16 29 43" src="https://user-images.githubusercontent.com/13086014/108867031-1124e500-75f5-11eb-92ce-4e506f2f9e0a.png">

Currently I'm using the development version: open3d==0.12.0+2cc25e3. Previously, when using the latest release (0.12.0), a critical error happened when pressing cmd+left click on the scene:

![Screenshot 2021-02-23 at 16 42 16](https://user-images.githubusercontent.com/13086014/108868292-57c70f00-75f6-11eb-9a73-9a9e25d4a23d.png)
