### ISSUE TITLE
Non blocking implementation of VisualizerWithVertexSelection crashes on mouse drag events

### ISSUE THREAD

**Issue by lakshmipathyarjun6** [intel-isl/Open3D#2969]
Hello! Thank you for making this library available - it has proven immensely useful to our group's current efforts. I have never actually posted on a repository before, so apologies in advance if the question is naive.

OS: Ubuntu 20.04
Open3D: 0.11.2 installed via Conda
Language: Python

Context: I would like to open 2 separate windows - one for performing a vertex selection, and another to display the result after saving the selection. The selection will then be cleared in the selection window. I understand that currently it is not possible to open multiple PCs / meshes in a VisualizerWithEdit window and that the new gui / rendering approaches are more general purpose; however, this is sufficient for what I am trying to do for now. I am currently doing this via non blocking calls as indicated both in the documentation and here: https://github.com/intel-isl/Open3D/issues/999. 

Problem: (also partially referenced here: https://github.com/intel-isl/Open3D/issues/999) Mouse drag events (after hitting Shift) instantly crash the program. I am able to select / deselect individual vertices only at this time. This issue does not exist if I use a blocking call to run(), but I need the ability to concurrently run the second window.

Current Efforts: I checked the Visualizer::run() implementation here: https://github.com/intel-isl/Open3D/blob/b467935323ca3f9b0d9b2672438bb88e396fd325/cpp/open3d/visualization/visualizer/Visualizer.cpp and the non blocking implementation should more or less mirror what is going on here; however, it appears BuildUtilities() is not exposed as a python binding (looked here: https://github.com/intel-isl/Open3D/blob/59c5b3abba78047294658ee2b2a0639e93f878b5/cpp/pybind/visualization/visualizer.cpp). But looking at the implementation of this particular method in https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/visualization/visualizer/VisualizerWithVertexSelection.cpp#L270, it appears that this is a necessary method to call since, at least from what I can tell, there is no other place that the member variables selection_polygon_ptr_ or pointcloud_picker_ptr_ is set otherwise. I suspect the program is crashing when this part is reached as a result: https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/visualization/visualizer/VisualizerWithVertexSelection.cpp#L622. Is there somewhere else I am missing by any chance?

I was wondering if there was a reason BuildUtilities() is not exposed as a python binding, and that if doing so and calling it before the loop of render / geometry updates this issue would be resolved. Alternatively is there something else I can do as a workaround if this indeed is the issue?

Thanks in advance for your help, and again really appreciate your work!

**Comment by prewettg** [comment]
We're glad that Open3D has been helpful for you, and thanks for taking the time to alert us of this crash. We are no longer doing active maintenance on the old visualizer and recommend that you use the new GUI instead. However, if the crash is an easy fix (it may be, but the fact that you are using two windows might be exposing some assumptions that would require more extensive changes) we may be able to fix it. Could you post a short example that illustrates the problem?

**Comment by lakshmipathyarjun6** [comment]
Thanks for the reply. Sure - if this part is run with an arbitrary mesh it works fine (1 window only):

vis = open3d.visualization.VisualizerWithVertexSelection()
vis.create_window(window_name='Patch select')
vis.add_geometry(mesh)
vis.run()

I am instead doing this:

vis1 = open3d.visualization.VisualizerWithVertexSelection()
vis1.create_window(window_name='Patch select')
vis1.add_geometry(mesh)

vis2 = open3d.visualization.Visualizer()
vis2.create_window(window_name='Saved patches')
vis2.add_geometry(mesh)

while True:
        vis1.update_geometry(mesh)
        if not vis1.poll_events():
            break
        vis1.update_renderer()

        vis2.update_geometry(mesh)
        if not vis2.poll_events():
            break
        vis2.update_renderer()

vis1.destroy_window()
vis2.destroy_window()


After running each example I just hit shift and perform a mouse drag over a set of vertices. The second one crashes the instant the drag event is started

**Comment by lakshmipathyarjun6** [comment]
Just wanted to give this a gentle bump. If it is determined to be too much work to fix, I'd be happy to go with GUI instead. Would it be possible to provide an example of how to reproduce the functionality of vertex selection?

**Comment by prewettg** [comment]
It looks like the design of the old visualizers is not fully compatible with using poll_events(), and is reproducible with just the vis1 window by itself. The run() function calls Visualizer::BuildUtilities(), which does initialization for some of the visualizers, including allocating the selection rectangle. You would need to call that function yourself before calling poll_events(), but it isn't exported to python.

Vertex selection is supported in the new GUI, although we haven't implemented rectangle/polygon selection yet, just clicking individual vertices. You can see an example in [`examples/python/gui/draw.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py)

**Comment by anticdimi** [comment]
@prewettg Hi, the link you provided for `examples/python//gui/draw.py` is not working anymore, could you post an updated version?
I also need the functionality to have vertex selection without blocking but I cannot find a way to make it work with GUI classes. Any help would be much appreciated :smile:

**Comment by Timezyxdev** [comment]
Hi, I would like to add another voice to this. I require vertex selection functionality using the Open3dScene GUI class but haven't been able to find any info about making that work. As mentioned above the link that @prewettg provided no longer works. More insight on this would be very helpful.

**Comment by miltonsegura-cobionix** [comment]
> @prewettg Hi, the link you provided for `examples/python//gui/draw.py` is not working anymore, could you post an updated version? I also need the functionality to have vertex selection without blocking but I cannot find a way to make it work with GUI classes. Any help would be much appreciated 😄

This is the version referenced: https://github.com/isl-org/Open3D/blob/fd61a44f0ca904c7819f7e301a7ec680da724bfc/examples/python/gui/draw.py

This is the example at the updated location: https://github.com/isl-org/Open3D/blob/5b6ef4b04b1a4184f12a2c1181ad2b7d2fe45248/examples/python/visualization/draw.py
