### ISSUE TITLE
Open3d Crash after adding pointscloud via add_geometry

### ISSUE THREAD

**Issue by yitao-yu** [intel-isl/Open3D#2973]
**IMPORTANT: Please use the following template to report the bug.**
_____

I'm using open3d to visualize a self-written python slam program. 
I'm visualizing the points cloud of feature points from a frame, and I have calculated the location of the features in world coordinate using OpenCV.

**Describe the bug**
This is not a bug that comes out every single time(when I run the program on the same file)
As I continue to add pointclouds that I generated from frames in a video file(if I run the full file the bug will definitely come out, so I trimmed it). There are times it throws a warning:

GLFW is not initialized
and
```
[Open3D WARNING] [SimpleShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] [SimpleShaderForPointCloud] Something is wrong in compiling or binding.
```

If I rerun the program, it might run without crashing. 
The program works just fine before it comes up. After it comes up, the open3d visualization part crash, but the other part of the python program is still running and processing frames.
I want to know if the bug is a software issue or a hardware issue. (I've checked to use the best GPU of this computer)
and if it's happening because I should be clearing some memory, how should I do that? 

Since I've run several demo programs, and they work fine, there's not likely to have a problem with the dependency on GLFW, right?

**Comment by prewettg** [comment]
It sounds like something is definitely strange somewhere, especially since it sometimes works and sometimes doesn't. What OS and what version of Open3D are you using? What libraries besides Open3D are you using, there might be a conflict with one of them. Can you remove things from your script until you have a small script that shows the problem?

**Comment by santoshreddy254** [comment]
@prewettg I am also facing the same issue and this happens only once when I run the rendering application for first time. I cannot reproduce the bug consistently but this happens and I get black images from render
`[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] Shader error:
[Open3D WARNING] [SimpleShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] Shader error:
[Open3D WARNING] [PhongShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] [NormalShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] [SimpleBlackShaderForPointCloudNormal] Compiling shaders failed.
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] [SimpleShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] [SimpleShaderForPointCloud] Something is wrong in compiling or binding.
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] GLFW Error: The GLFW library is not initialized`
