### ISSUE TITLE
How can I change the width and height of the Visualizer?

### ISSUE THREAD

**Issue by FabianSchuetze** [intel-isl/Open3D#2975]
**IMPORTANT: Please use the following template to report the bug.**
_____
I would like to adjust the width and height of the visualizer. At the moment, it seems to be fixed at the default width and height. To reproduce:

```Python
vis = o3d.visualization.Visualizer()
vis.create_window(width=256, height=320)
ctr = vis.get_view_control()
ctr.convert_to_pinhole_camera_parameters().intrinsic
```
that returns:
```Shell
PinholeCameraIntrinsic with width = 956 and height = 1040.
Access intrinsics with intrinsic_matrix.
```
Is it possible to adjust the visualizer and change its width and height? Is that possible with the c++ api? I am grateful for any hints and sugestions! 

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04 
- Python version: Python 3.8.5
- Open3D version: 0.12
- Is this remote workstation?: no 
- How did you install Open3D?: pip
- Compiler version (if built from source): -

**Comment by prewettg** [comment]
No, it is not possible to programmatically resize the Visualizer window, but it is possible with the new O3DVisualizer.
The simple way:
```
def on_init(o3dvis):
    o3dvis.os_frame = o3d.visualization.gui.Rect(o3dvis.os_frame.x, o3dvis.os_frame.y, 1024, 768)

torus = o3d.geometry.TriangleMesh.create_torus()
torus.compute_vertex_normals()
o3d.visualization.draw([torus], title="Open3D", width=640, height=480, on_init=on_init)
```
The full-featured way:
```
app = o3d.visualization.gui.Application.instance
app.initialize()
o3dvis = o3d.visualization.O3DVisualizer("Open3D", 640, 480)
torus = o3d.geometry.TriangleMesh.create_torus()
torus.compute_vertex_normals()
o3dvis.add_geometry("Torus", torus)
o3dvis.reset_camera_to_default()
o3dvis.os_frame = o3d.visualization.gui.Rect(o3dvis.os_frame.x, o3dvis.os_frame.y, 1024, 768)
app.add_window(o3dvis)
app.run()
```

**Comment by FabianSchuetze** [comment]
Thank you very much @prewettg  for the detailed and helpful instructions !
