### ISSUE TITLE
Import OBJ file - number of vertices is bigger than number of "v" lines in the obj file

### ISSUE THREAD

**Issue by rafal-mrowka** [intel-isl/Open3D#2978]
**Describe the bug**
Based on a simple mesh (a flat squeeze square, 2 triangles, 4 vertices), try to import exported OBJ file using io.read_triangle_mesh():

`source = o3d.io.read_triangle_mesh("msquare.obj")
print(np.asarray(source.vertices))`

output:

[**[ 0.77946299  0.          1.        ]**
 **[-1.          0.         -0.68007398]**
 [-1.          0.          1.                ]
 **[ 0.77946299  0.          1.        ]**
 [ 1.          0.         -1.                ]
 **[-1.          0.         -0.68007398]**]

It creates mesh with: triangles = 2 and vertices = 6. 

But the content of the obj file is:

'# Blender v2.91.2 OBJ File: 'cube.blend'
o Plane
v -1.000000 0.000000 1.000000
v 0.779463 0.000000 1.000000
v -1.000000 0.000000 -0.680074
v 1.000000 0.000000 -1.000000
vn 0.0000 1.0000 0.0000
s off
f 2//1 3//1 1//1
f 2//1 4//1 3//1'

As you can see there are only **4 lines** with the vertices data (4 "v" lines). It meas there are 4 vertices in the original mesh. I've intentionally changed x and y coordinates of joint vertices to be sure that they are duplicated in the internal data (python object) 
The duplicated vertices: [ 0.77946299  0.          1.        ] and [-1.          0.         -0.68007398]. 

It looks like they are duplicated because they are common to two triangles. Please refer to the screenshot of the model from Blender (msquare.png).

![msquare](https://user-images.githubusercontent.com/2647797/106471454-edf99080-64a1-11eb-8d6e-70606824087b.png)

**To Reproduce**

1. Export OBJ file from Blender using this simple model: 
[cube.zip](https://github.com/intel-isl/Open3D/files/5904484/cube.zip)

2. Execute:
`import numpy as np
import open3d as o3d
source = o3d.io.read_triangle_mesh("msquare.obj")
print(np.asarray(source.vertices))`

3. Compare output with the obj content:
v -1.000000 0.000000 1.000000
v 0.779463 0.000000 1.000000
v -1.000000 0.000000 -0.680074
v 1.000000 0.000000 -1.000000

**Expected behavior**
The different number of vertices in the python object creates a issue when you want to use vertices indexes outside of the open3d environment (eg. when using visualization.VisualizerWithVertexSelection() to select vertices and export it to Matlab).

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
- Python version: Python 3.8.5
- Open3D version: 0.12.0+313315d9
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 8.4.0

**Comment by errissa** [comment]
@rafal-mrowka Would you please try `source = o3d.io.read_triangle_mesh("msquare.obj", enable_post_processing=True)` and report the results? Thanks!

**Comment by rafal-mrowka** [comment]
Thanks for quick response!!!

The result is:
[[ 0.77946299  0.          1.        ]
 [-1.          0.         -0.68007398]
 [-1.          0.          1.        ]
 [ 1.          0.         -1.        ]]

So it works. Great!!!.Can You give some more insight about this flag?

**Comment by errissa** [comment]
Glad it worked! The `enable_post_processing` enables a set of post-processing operations applied during object loading one of which ensures that shared vertices are not unnecessarily duplicated. The operations are generally intended to improve rendering performance (merging meshes, joining vertices, reordering vertices, etc.) which may not be desired by some users which is why the post-processing is disabled by default.

**Comment by thachdo** [comment]
I met the same issue. Turning on 'enable_post_processing' is not solved in my cause. The duplicated vertices appear in the loaded obj. How can I solve this?

**Comment by mohamad-hasan-sohan-ajini** [comment]
Hey
I'm here for the exact same reason that @thachdo was.
Any update on this thread?

Regards
