### ISSUE TITLE
OffscreenRenderer does not shut down properly

### ISSUE THREAD

**Issue by aweinmann** [intel-isl/Open3D#2984]
**Describe the bug**
When rendering a pointcloud using the OffscreenRenderer the program does not exit.

**To Reproduce**

Simple program to reproduce the issue. The python program prints finished but does not terminate.

````
import open3d as o3d
import numpy as np

resolution = (1920, 1080)
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(np.random.rand(100, 3))
pcd.colors = o3d.utility.Vector3dVector(np.random.rand(100, 3) * 255)

mat = o3d.visualization.rendering.Material()
mat.shader = 'defaultUnlit'

renderer_pc = o3d.visualization.rendering.OffscreenRenderer(resolution[0], resolution[1])
renderer_pc.scene.set_background(np.array([0, 0, 0, 0]))
renderer_pc.scene.add_geometry("pcd", pcd, mat)

img = renderer_pc.render_to_image()
print("finished")
````

**Expected behavior**
Expectation would be that the program terminates after finishing.

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7
- Open3D version: 0.12
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by prewettg** [comment]
Fixed in #3273
