### ISSUE TITLE
when i build project,such as AzureKinectMKVReader,but it always download code is:

### ISSUE THREAD

**Issue by UEBoy2019** [intel-isl/Open3D#2989]
已启动生成…
1>------ 已启动生成: 项目: ext_zlib (ExternalProjectTargets\ext_zlib\ext_zlib), 配置: Release x64 ------
2>------ 已启动生成: 项目: ext_mkl (ExternalProjectTargets\ext_mkl\ext_mkl), 配置: Release x64 ------
3>------ 已启动生成: 项目: ext_mkl_include (ExternalProjectTargets\ext_mkl_include\ext_mkl_include), 配置: Release x64 ------
4>------ 已启动生成: 项目: ext_tbb (ExternalProjectTargets\ext_tbb\ext_tbb), 配置: Release x64 ------
5>------ 已启动生成: 项目: ShaderFileTarget, 配置: Release x64 ------
6>------ 已启动生成: 项目: ext_turbojpeg (ExternalProjectTargets\ext_turbojpeg\ext_turbojpeg), 配置: Release x64 ------
7>------ 已启动生成: 项目: ext_assimp (ExternalProjectTargets\ext_assimp\ext_assimp), 配置: Release x64 ------
8>------ 已启动生成: 项目: ext_ippicv (ExternalProjectTargets\ext_ippicv\ext_ippicv), 配置: Release x64 ------
1>Performing build step for 'ext_zlib'
1>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.3+39993bd9d
1>版权所有(C) Microsoft Corporation。保留所有权利。
1>
1>  zlib.vcxproj -> D:\Open3D\download\Open3D\build\zlib\src\ext_zlib-build\Release\zlib.dll
1>  example.vcxproj -> D:\Open3D\download\Open3D\build\zlib\src\ext_zlib-build\Release\example.exe
1>  minigzip.vcxproj -> D:\Open3D\download\Open3D\build\zlib\src\ext_zlib-build\Release\minigzip.exe
1>  zlibstatic.vcxproj -> D:\Open3D\download\Open3D\build\zlib\src\ext_zlib-build\Release\zlibstatic.lib
1>Performing install step for 'ext_zlib'
1>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.3+39993bd9d
1>版权所有(C) Microsoft Corporation。保留所有权利。
1>
1>  zlib.vcxproj -> D:\Open3D\download\Open3D\build\zlib\src\ext_zlib-build\Release\zlib.dll
1>  example.vcxproj -> D:\Open3D\download\Open3D\build\zlib\src\ext_zlib-build\Release\example.exe
1>  minigzip.vcxproj -> D:\Open3D\download\Open3D\build\zlib\src\ext_zlib-build\Release\minigzip.exe
1>  zlibstatic.vcxproj -> D:\Open3D\download\Open3D\build\zlib\src\ext_zlib-build\Release\zlibstatic.lib
1>  -- Install configuration: "Release"
1>  -- Up-to-date: D:/Open3D/download/Open3D/build/zlib/lib/zlib.lib
1>  -- Up-to-date: D:/Open3D/download/Open3D/build/zlib/bin/zlib.dll
1>  -- Up-to-date: D:/Open3D/download/Open3D/build/zlib/lib/zlibstatic.lib
1>  -- Up-to-date: D:/Open3D/download/Open3D/build/zlib/include/zconf.h
1>  -- Up-to-date: D:/Open3D/download/Open3D/build/zlib/include/zlib.h
1>  -- Up-to-date: D:/Open3D/download/Open3D/build/zlib/share/man/man3/zlib.3
1>  -- Up-to-date: D:/Open3D/download/Open3D/build/zlib/share/pkgconfig/zlib.pc
1>Completed 'ext_zlib'
1>Building Custom Rule D:/Open3D/download/Open3D/CMakeLists.txt
9>------ 已启动生成: 项目: ext_jsoncpp (ExternalProjectTargets\ext_jsoncpp\ext_jsoncpp), 配置: Release x64 ------
10>------ 已启动生成: 项目: ext_k4a (ExternalProjectTargets\ext_k4a\ext_k4a), 配置: Release x64 ------
11>------ 已启动生成: 项目: ext_libpng (ExternalProjectTargets\ext_libpng\ext_libpng), 配置: Release x64 ------
9>Performing build step for 'ext_jsoncpp'
10>Performing download step (download, verify and extract) for 'ext_k4a'
11>Creating directories for 'ext_libpng'
10>-- File already exists but no hash specified (use URL_HASH):
10>  file='D:/Open3D/download/Open3D/build/k4a/src/archive.tar'
10>Old file will be removed and new file downloaded from URL.
10>-- Downloading...
10>   dst='D:/Open3D/download/Open3D/build/k4a/src/archive.tar'
10>   timeout='none'
10>   inactivity timeout='none'
10>-- Using src='https://www.nuget.org/api/v2/package/Microsoft.Azure.Kinect.Sensor/1.4.1'
9>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.3+39993bd9d
9>版权所有(C) Microsoft Corporation。保留所有权利。
9>
11>Performing download step (git clone) for 'ext_libpng'
11>Cloning into 'ext_libpng'...
9>  jsoncpp_static.vcxproj -> D:\Open3D\download\Open3D\build\jsoncpp\src\ext_jsoncpp-build\lib\Release\jsoncpp.lib
9>Performing install step for 'ext_jsoncpp'
9>用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.3+39993bd9d
9>版权所有(C) Microsoft Corporation。保留所有权利。
9>
9>  jsoncpp_static.vcxproj -> D:\Open3D\download\Open3D\build\jsoncpp\src\ext_jsoncpp-build\lib\Release\jsoncpp.lib
9>  -- Install configuration: "Release"
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/lib/pkgconfig/jsoncpp.pc
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/lib/cmake/jsoncpp/jsoncppConfig.cmake
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/lib/cmake/jsoncpp/jsoncppConfig-release.cmake
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/lib/cmake/jsoncpp/jsoncppConfigVersion.cmake
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/lib/jsoncpp.lib
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/allocator.h
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/assertions.h
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/config.h
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/forwards.h
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/json.h
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/json_features.h
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/reader.h
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/value.h
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/version.h
9>  -- Up-to-date: D:/Open3D/download/Open3D/build/jsoncpp/include/json/writer.h
9>Completed 'ext_jsoncpp'
9>Building Custom Rule D:/Open3D/download/Open3D/CMakeLists.txt
10>-- [download 0% complete]

**Comment by ssheorey** [comment]
Thanks for pointing this out. The duplicated download is step is here. You are welcome to provide a patch for this, else we'll patch this shortly.

> 10>-- File already exists but no hash specified (use URL_HASH):
> 10> file='D:/Open3D/download/Open3D/build/k4a/src/archive.tar'
> 10>Old file will be removed and new file downloaded from URL.
> 10>-- Downloading...
> 10> dst='D:/Open3D/download/Open3D/build/k4a/src/archive.tar'
> 10> timeout='none'
> 10> inactivity timeout='none'
> 10>-- Using src='https://www.nuget.org/api/v2/package/Microsoft.Azure.Kinect.Sensor/1.4.1'
