### ISSUE TITLE
AttributeError: module 'open3d.open3d.visualization' has no attribute 't'

### ISSUE THREAD

**Issue by kathanvyas** [intel-isl/Open3D#2990]
I am using open3d-python 0.7.0 and trying to implement the reconstruction system by recording a bag file using intel real sense. while I am following everything as mentioned, I have been getting a lot of errors like pipeline and others which I was able to solve. however the recent error I am getting while implementing

`python run_system.py config\tiger_bag.json --make`

to which I get an error

`Traceback (most recent call last):
  File "run_system.py", line 52, in <module>
    initialize_config(config)
  File "C:\Users\Kathan\Desktop\ACLAB\3D_Registeration\Open3D-master\examples\python\reconstruction_system\initialize_config.py", line 59, in initialize_config       
    "depth_scale"] = extract_rgbd_frames(config["path_dataset"])
  File "../utility\file.py", line 127, in extract_rgbd_frames
    rgbd_video = o3d.t.io.RGBDVideoReader.create(rgbd_video_file)
AttributeError: module 'open3d.open3d.visualization' has no attribute 't'`

**Comment by prewettg** [comment]
I believe the open3d.t.io.RGBDVideoReader was first available in 0.12. Please use the `open3d` package from PyPI, and `open3d-python` is no longer the official name of the package and is stuck at 0.7, which is missing out on a lot of new features.

**Comment by masterchop** [comment]
i got the same under the latest version on pip
```

>>> import open3d as o3d
>>> o3d.__version__
'0.12.0'
```

**Comment by 88ili88** [comment]
this is not solved

**Comment by XRarach** [comment]
Still not solved, which means no geometry can be visualized 
mtl = o3d.visualization.rendering.Material()
AttributeError: module 'open3d.visualization.rendering' has no attribute 'Material'

**Comment by VuHuy-cse-9** [comment]
> import open3d as o3d
> 
> > > > o3d.**version**
> > > > '0.15.1'
> 
> Still not solved, which means no geometry can be visualized mtl = o3d.visualization.rendering.Material() AttributeError: module 'open3d.visualization.rendering' has no attribute 'Material'

According to documentation, I think your class Material has changed to [MaterialRecord](http://www.open3d.org/docs/release/python_api/open3d.visualization.rendering.MaterialRecord.html). (open3d.visualization.rendering.MaterialRecord)

**Comment by XRarach** [comment]
Thank you very much, I will try that, I would expect the old one to remain with a deprecation message overloaded with a new one, this I consider a good practice, which I would also recommend as it is still in all the tutorials which I was able to find. But thank you for pointing me to the documentation, my bad there.  :) Wish you a nice day, I will definitely try that.

**Comment by prixbug** [comment]
Hi all,

Using open3d with pytorch to visualize data. Respective requirements have been installed as below.  
-f https://download.pytorch.org/whl/torch/
torch==1.13.1+cu116
-f https://download.pytorch.org/whl/torchvision/
torchvision==0.14.1+cu116
tensorboard

Cuda version - 11.6
open3d version - 0.16.0
python version - 3.10.8
OS - Windows

The import open3d.ml.torch as ml3d is giving an error 'Open3d was not built with Pytorch support'
and also the below statement
vis = ml3d.vis.Visualizer() this particular line is giving error 'module 'open3d.ml.vis' has no attribute 'Visualizer''

Upon checking looks like some functions are missing from imported package. Any idea why this is happening ?
