### ISSUE TITLE
Example for visualizing sequential point clouds and bounding boxes with GUI

### ISSUE THREAD

**Issue by bigsheep2018** [intel-isl/Open3D#2994]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Here is what I got from your repo home page 
![getting_started_ml_visualizer](https://user-images.githubusercontent.com/45345643/106878275-b7777c00-6714-11eb-8d64-dcea59d63aa3.gif)

I am writing to know if there is a code example (c++ or python) that I can reproduce this demo with my own point cloud(pcd, bin, etc) and bounding box data(txt, json, etc)

I am using ubuntu 18.04.

Thanks in advance.
Lin

**Comment by prewettg** [comment]
@bigsheep2018 I believe the [`examples/visualize.py`](https://github.com/intel-isl/Open3D-ML/blob/master/examples/visualize.py) example should do that. Run it as `python examples/visualize.py custom`.
