### ISSUE TITLE
Running both a headless and a non-headless Visualizer in the same process

### ISSUE THREAD

**Issue by marcoct** [intel-isl/Open3D#2998]
**Is your feature request related to a problem? Please describe.**
I have two very different use cases for Open3D and have been able to use it successfully for them separately: (1) to build interactive visualizations, and (2) to render low-resolution depth images of low-poly scenes at very high frame rates (e.g. 1000s of FPS) into memory, as part of a perception algorithm. Use case 1 requires a window of course, and for use case 2 I have been able to get over 60 FPS only when I build Open3D to use headless rendering with OSMesa (following [this](http://www.open3d.org/docs/release/tutorial/visualization/headless_rendering.html)). I am using the Python API.

**Describe the solution you'd like**
I would like to start two visualizers (specifically `open3d.visualization.Visualizer()`), one that is not headless (for use case 1) and one that is headless (for use case 2) within the same process. Is this something Open3D could support, possibly with an option passed at run-time to the constructor? If not, does anyone have a recommended workaround?

**Describe alternatives you've considered**
I have tried to simultaneously import two versions of the `open3d` python package, one built with the OSMesa and one obtained from PyPI, using some kludges involving renaming the package. I ended up running into an error from pybind (`ImportError: generic_type: type "VerbosityLevel" is already registered!`). Running them in separate processes is of course an option, but I would prefer not to.

**Additional context**
That you for creating Open3D. I am loving it.

**Comment by errissa** [comment]
It is not currently possible to run both headless and non-headless in the same process. It could be possible to support that but it is not currently on our roadmap to support that. Your alternative to run two separate processes is the best solution. I am closing this issue but if this limitation becomes an insurmountable problem for your use case, please reopen the issue.

**Comment by rubenverhack** [comment]
I second @marcoct for this feature. I was also drawn to this library for exactly this functionality of being able to render in notebooks and to render images at the same time. For me this seems to be a logical case for who ever is remote developing AI on 3D objects. You would want to visually inspect in a notebook/browser and to be able to batch export PNGs (and , even better, moving GIFs).

**Comment by rubenverhack** [comment]
@errissa You mention that is not possible in the same process. However, is there a possible workaround by using multiprocessing? From my experience, I'm not even able to build Open3D with both ENABLE_HEADLESS_RENDERING=ON as well as the required flags for Jupyter (BUILD_JUPYTER_EXTENSION=ON, BUILD_WEBRTC=ON,  BUILD_GUI=ON)
