### ISSUE TITLE
L515 do not detected

### ISSUE THREAD

**Issue by charmowen** [intel-isl/Open3D#3006]
![image](https://user-images.githubusercontent.com/34369626/107139915-9784ca00-6959-11eb-9077-031009804187.png)

but Intel RealSense Viewer is ok!

**Comment by Zumbalamambo** [comment]
+1

**Comment by ssheorey** [comment]
This is likely the same as #2861 
The fix is in `master` but not in v0.12 on PyPI. Please test with the latest development wheel (see documentation for how to install the development version) and let us know.

**Comment by charmowen** [comment]
![20210207150532](https://user-images.githubusercontent.com/34369626/108576471-bcfdd480-7358-11eb-8a4e-3140f2ad873f.png)
It is OK!

**Comment by hduonggithub** [comment]
@charmowen 
Did you have to build from source master branch? As I have installed the latest release version, it still does not recognize my device.

**Comment by ssheorey** [comment]
@hduonggithub We have not made a release with this fix yet. Please use the latest development wheel from here:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

**Comment by hduonggithub** [comment]
Thanks @ssheorey. It works if installing from the link!
