### ISSUE TITLE
mac M1 [Open3D ERROR] GLFW Error: Cocoa: Failed to find service port for display

### ISSUE THREAD

**Issue by Jianghanxiao** [intel-isl/Open3D#3012]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I meet the problem on my mac M1. I'm not sure if it's relevant to the computer. Do you have some idea on how to solve this?

**Screenshots**
![image](https://user-images.githubusercontent.com/32015651/107382451-bc398880-6aa4-11eb-956e-2c54ebe65218.png)

**Environment (please complete the following information):**

- Operating system: (e.g. OSX 11.2) mac M1
- Open3D version: 0.10.0.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by Jianghanxiao** [comment]
The latest version open3d solves the problem

**Comment by harora** [comment]
I have open3d==0.11.2 but still getting this problem.

**Comment by GeoVectorMatrix** [comment]
> I have open3d==0.11.2 but still getting this problem.

how to solve this problem?

**Comment by GeoVectorMatrix** [comment]
> I have open3d==0.11.2 but still getting this problem.

Solved by fixing the latest version.  such as ‘pip install open3d== 0.13.0‘

**Comment by sanjivjha** [comment]
it is still the issue with 0.17.0. I tried older version but same issue.
