### ISSUE TITLE
save Visualizer into *.ply file

### ISSUE THREAD

**Issue by abahnasy** [intel-isl/Open3D#3034]
I've a point cloud and set of bounding boxes, I use `vis = o3d.visualization.Visualizer()` to add the point cloud and the bboxes and visualize them, is there a way to save the final visualization in a *.ply file (I mean the pc and the bboxes together)?

**Comment by prewettg** [comment]
No, this is not possible with a PLY file, primarily because a PLY file only supports one triangle mesh. I am not aware of a format that supports both point clouds and lines (assuming that you want lines for the bounding boxes).
