### ISSUE TITLE
Offscreen renderer memory leaking

### ISSUE THREAD

**Issue by aweinmann** [intel-isl/Open3D#3042]
**Describe the bug**
rendering images with offscreen renderer leaks memory (GPU and CPU)

**To Reproduce**
running the following program results in GPU memory filling up as well as CPU memory usage increasing each frame

````
import open3d as o3d
import numpy as np

resolution = (1920, 1080)
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(np.random.rand(100, 3))
pcd.colors = o3d.utility.Vector3dVector(np.random.rand(100, 3) * 255)

mat = o3d.visualization.rendering.Material()
mat.shader = 'defaultUnlit'

renderer_pc = o3d.visualization.rendering.OffscreenRenderer(resolution[0], resolution[1])
renderer_pc.scene.set_background(np.array([0, 0, 0, 0]))
renderer_pc.scene.add_geometry("pcd", pcd, mat)

for _ in range(1000):
    img = renderer_pc.render_to_image()

````
**Expected behavior**
rendering multiple images should not change the memory consumption

**Screenshots**
![image](https://user-images.githubusercontent.com/2863595/108038170-d17d5c80-703a-11eb-9df6-a61de9302a83.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7
- Open3D version: 0.12
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by errissa** [comment]
Thank you for this report. I was able to confirm the behavior you reported and will look into it.

**Comment by aweinmann** [comment]
@errissa any news on this issue?

**Comment by prewettg** [comment]
#3002 may fix this, I added some code to free texture resources.

**Comment by aweinmann** [comment]
I tried the above snipped on todays master, still having the same issue

**Comment by aweinmann** [comment]
#3273 apparently fixed this issue. works fine on current master.
