### ISSUE TITLE
Build error: 'patch does not apply' for ext_jsoncpp

### ISSUE THREAD

**Issue by Algomorph** [intel-isl/Open3D#3053]
**Description**

I'm getting a build error, it seems like it stems from a failed attempt at patching CMakeLists.txt for jsoncpp dependency. 
https://github.com/intel-isl/Open3D/blob/6eaee80d6b083f5d49fe0f41db26e3d9daf817ee/3rdparty/jsoncpp/jsoncpp.cmake#L10

**To Reproduce**
To reproduce, build after configuring with the following CMake flags (aside: probably none of these are related, included for pedantry):
```
-DBUILD_CUDA_MODULE=ON
-DBUILD_UNIT_TESTS=ON
-DBUILD_AZURE_KINECT=ON
-DPYTHON_EXECUTABLE=/usr/bin/python3
```
Example build command specific to ext_jsoncpp target and output:
```
/usr/bin/cmake --build /home/user/Open3D/cmake-build-debug --target ext_jsoncpp
[100%] Performing patch step for 'ext_jsoncpp'
error: patch failed: CMakeLists.txt:22
error: CMakeLists.txt: patch does not apply
error: patch failed: src/lib_json/CMakeLists.txt:125
error: src/lib_json/CMakeLists.txt: patch does not apply
make[3]: *** [CMakeFiles/ext_jsoncpp.dir/build.make:120: jsoncpp/src/ext_jsoncpp-stamp/ext_jsoncpp-patch] Error 1
make[2]: *** [CMakeFiles/Makefile2:1141: CMakeFiles/ext_jsoncpp.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1148: CMakeFiles/ext_jsoncpp.dir/rule] Error 2
make: *** [Makefile:378: ext_jsoncpp] Error 2
```

**Environment**

- Operating system: Ubuntu 20.04
- Python version: 3.8.5
- Open3D version: 016c03e7 / 0.12.0-dev
- Is this remote workstation?: no
- Compiler version (if built from source): gcc 9.3

**Comment by Dai-z** [comment]
I'm got the same error, and successfully build the code after rolling back my cmake version from 20 to 19.

**Comment by ssheorey** [comment]
`cmake` uses `git apply` for patching. This is known to fail in these conditions:
- The patch has already been applied once by a previous build run. In this case, remove the `build/jsoncpp` folder and rebuild.
- File permissions are incorrect. This may happen on network mounted filesystems, or on Windows.

Does this help?

**Comment by Algomorph** [comment]
A freshly checked-out repository seems to have helped in my case, so I suppose removal of `jsoncpp` from the build folder would have worked. Thank you for you time!
