### ISSUE TITLE
Build fails: no rule to make target libpng/lib/libpng16.a

### ISSUE THREAD

**Issue by Algomorph** [intel-isl/Open3D#3054]
**Description**
For non-MSVC compilers, CMake is using the wrong path to find libpng, which results in `no rule to make target libpng/lib/libpng16.a`

It stems from this line:
https://github.com/intel-isl/Open3D/blob/6eaee80d6b083f5d49fe0f41db26e3d9daf817ee/3rdparty/libpng/libpng.cmake#L30

If I change this line to the line below, libpng is found correctly :
```CMake
    set(LIBPNG_LIBRARIES png)
```

I would submit a PR with this change if you think that would be reliable, but I don't have time / resources currently to test the build on other systems than Ubuntu 20.04.

**To Reproduce**
Steps to reproduce the behavior: run CMake, make sure USE_SYSTEM_PNG=OFF in the CMake cache (default), run the build.

**Environment**

- Operating system: Ubuntu 20.04
- Python version: 3.8.5
- Open3D version: 016c03e7 / 0.12.0-dev
- Is this remote workstation?: no
- Compiler version (if built from source): gcc 9.3

**Comment by ssheorey** [comment]
Hi @Algomorph I wasn't able to reproduce this issue with Ubuntu 20.04 and USE_SYSTEM_PNG=OFF. This configuration is regularly tested in our CI as well. Can you try a new build in a fresh folder and see if the problem persists? Checking CMake build logs may also help. You are welcome to post them here.

PS: If you wish to make a PR, the CI will test it on a fair number of platforms automatically for you.

**Comment by Algomorph** [comment]
Good call. On a freshly checked-out copy, I wasn't able to reproduce this issue. I must have accidentally updated the `libpng` submodule, my bad. Thank you for your time.

**Comment by Algomorph** [comment]
Spoke too early. Nope, the problem persists when I try to build the `install-pip-package` target.
```
/usr/bin/cmake --build /home/algomorph/Garage/Open3D/cmake-build-debug --target install-pip-package -j 8
```

`libpng` consistently builds the library without the "16" suffix, so it's definitely a build system issue:
![image](https://user-images.githubusercontent.com/1050606/108597752-b40d0300-7358-11eb-821a-bd4ce798e062.png)

Removing the suffix effectively resolves the issue. I'll submit a PR.

**Comment by Algomorph** [comment]
My bad, it was really the "d" suffix that was missing for debug build, i.e. libpng.a is a symlink to libpng16d.a in my case. Fixing and updating PR shortly to include the "d" suffix for debug builds. @ssheorey , this is probably why you weren't able to replicate.
