### ISSUE TITLE
How to convert core::Tensor to Eigen::Matrix? 

### ISSUE THREAD

**Issue by VladMVLX** [intel-isl/Open3D#3087]
Hello open3d creators and masters,

I am trying to test t::pipelines::registration::RegistrationICP from the latest master branch (24.02.2020), and stuck with an issue:

What I am trying to do:

1. Load geometry::PointCloud
2. Create t::geometry::PointCloud
3. Initialize t::geometry::PointCloud using t::geometry::PointCloud::FromLegacyPointCloud
4. Convert initial transformation matrix to core::Tensor using open3d::core::eigen_converter::EigenMatrixToTensor
5. run t::pipelines::registration::RegistrationICP and check the results

t::pipelines::registration::RegistrationICP returns t::pipelines::registration::RegistrationResults which have field: transformation_ of core::Tensor type.

I tried my best to find a proper way to cast/convert core::Tensor to Eigen::Matrix looking thru examples, documentation and open3d source code, but no luck for me.

Is there any way to convert it back to the Eigen::Matrix for the future use on CPU side? 
What I am missing?

Thanks in advance.

**Comment by reyanshsolis** [comment]
Hi @VladMVLX,
If you are looking for Eigen to Tensor conversions and back, here are a few implemented functions to help [Link](http://www.open3d.org/docs/release/cpp_api/_eigen_converter_8h.html). 
A general method is to convert Tensor to the flat vector [`tensor.ToFlatVector<float>()`] and then vector to Eigen. 
I will add Eigen to Tensor functionality as a feature request and when there is any update in this functionality will update you accordingly.
By the way, tensor operations are supported on both CUDA and CPU.
Thanks,
Rishabh

**Comment by reyanshsolis** [comment]
Hi @VladMVLX, the requested feature for Tensor to Eigen Matrix conversion op., has been added to master, from PR #3163. You may refer `cpp/tests/core/EigenConverter.cpp` for example. 
The ops include: `TensorToEigenMatrixXd`, `TensorToEigenMatrixXf` and `TensorToEigenMatrixXi` to convert any 2D tensor to double, float, int type EigenMatrix of the same dimension. 

Thanks for helping us improve :)
Rishabh

**Comment by VladMVLX** [comment]
Hello @reyanshsolis thank you for your support solving this problem, this new functions looks neat and helps a lot!
