### ISSUE TITLE
help with o3DVisualizer

### ISSUE THREAD

**Issue by tairch** [intel-isl/Open3D#3092]
hi, 
found no example for using o3DVisualizer. after trial and error this is what I have at the moment:

```
gui.Application.instance.initialize()
w = o3d.visualization.O3DVisualizer("03DVisualizer",640, 480)
gui.Application.instance.add_window(w)
w.show_axes = True
#material = o3d.visualization.rendering.Material()
w.add_geometry("flower", flower) # flower is a point cloud
gui.Application.instance.run()
```

but that doesn't seem stable at all, the cloud flashes and disappears upon moving in the window and there are two circles I didn't put in: one red (maybe suppose to be the axes?) and one blue with more colors (mainly green) taking symmetric sectors of it.
is this my misuse or a bug?

**Comment by hduonggithub** [comment]
@tairch 

Thanks for the code. I tried your code and was able to see my point cloud displayed correctly.

**Comment by tairch** [comment]
@hduonggithub 
Good to hear:)

**Comment by prewettg** [comment]
Add `w.reset_camera_to_default()` before `run()`. The default camera is sitting at (0, 0, 0) looking down -z, which happens to be awkwardly positioned regarding the axes geometry, and also is probably not convenient for your point cloud geometry.  In 0.13 you can find two examples using O3DVisualizer directly ([`examples/python/gui/multiple-windows.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/multiple-windows.py) and [`examples/python/gui/text3d.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/text3d.py)), and the most comprehensive example is the `open3d.visualization.draw()` function itself, [`python/open3d/visualization/draw.py`](https://github.com/intel-isl/Open3D/blob/master/python/open3d/visualization/draw.py).

**Comment by baraujo98** [comment]
Hi, my Open3D app also recently started flashing when moving the mouse. Both the point cloud and the menus flash. It happens both with the Open3D app and when I prompt the visualizer via Python code.

(did you find the cause @prewettg?)

**Comment by prewettg** [comment]
@baraujo98 if the menus are flashing it's likely that it is a different problem. We have seen problems in the past with flashing when using an Intel integrated graphics with the Ubuntu 18.04 drivers, for instance. We believe that all flashing problems are resolved in the current `master` branch. If it still exists in `master`, please open a new issue with a simple script to reproduce (such as was posted in this issue), the version of Open3D used to reproduce the problem, the operating system, and the graphics card that you are using.
