### ISSUE TITLE
Loading .ply triangular mesh file recognizing only points

### ISSUE THREAD

**Issue by vincenzo-palmacci** [intel-isl/Open3D#3093]
Hello everyone,
I am a newbie of Open3D and I was trying to load a triangular mesh of a PDB file with the command 

mesh = o3d.io.read_triangle_mesh(surf)

and when I print the content I obtain:

geometry::TriangleMesh with 192974 points and 0 triangles.

and when I try to plot it nothing comes out.
I checked the .ply file content and everything looks good.
Someone had a similar issue? Thanks for your help

**Comment by kaushik25T** [comment]
why did you close the issue?
