### ISSUE TITLE
Issue with CMake add_subdirectory

### ISSUE THREAD

**Issue by mrsaleh** [intel-isl/Open3D#3116]
**Hello**

### Bug:
I can't create an empty project which depends on Open3D as a git submodule and build correctly.
When I dig in the CMakeError.log I saw this line 
`fatal error C1083: Cannot open include file: 'cxxabi.h': No such file or directory
I don't know whether this is the source of the issue, but it seems that it is looking for a gnu compiler file that is missing on the visual studio compiler.
**I also attached CMakeError.log and CMakeOutput.log files to the issue.**

### How to reproduce:

I'm using Windows 10 and Visual Studio 2019.

I just created a new empty project that only prints "Hello World" to the console. 

This is how my CMakeLists.txt looks like:

```
cmake_minimum_required(VERSION 3.18)

project(FitAdviser VERSION 1.0)

add_subdirectory(Open3D)

add_executable(FitAdviser main.cpp)

target_link_libraries(FitAdviser Open3D)

```

And I have added Open3D as a Git SubModule.
This is how my .gitmodules file looks like.

```
[submodule "Open3D"]
	path = Open3D
	url = https://github.com/intel-isl/Open3D.git
```

And then I made a build directory and do the following in the windows console.

```
md build
cd build
cmake ..

```
And this the error message I got.

```
-- IPP-ICV 2020.0.0 Gold available. Building interface wrappers IPP-IW.
CMake Error at Open3D/cpp/CMakeLists.txt:26 (target_compile_options):
  Cannot specify compile options for target "Open3D" which is not built by
  this project.
Call Stack (most recent call first):
  Open3D/cpp/open3d/CMakeLists.txt:63 (open3d_show_and_abort_on_warning)


CMake Error at Open3D/CMakeLists.txt:461 (get_target_property):
  get_target_property() called with non-existent target "Open3D".
Call Stack (most recent call first):
  Open3D/cpp/open3d/CMakeLists.txt:64 (open3d_set_global_properties)


CMake Error at Open3D/cpp/open3d/CMakeLists.txt:7 (target_compile_definitions):
  Cannot specify compile definitions for target "Open3D" which is not built
  by this project.
Call Stack (most recent call first):
  Open3D/cpp/open3d/CMakeLists.txt:65 (open3d_set_open3d_lib_properties)


CMake Error at Open3D/CMakeLists.txt:433 (target_link_libraries):
  Cannot specify link libraries for target "Open3D" which is not built by
  this project.
Call Stack (most recent call first):
  Open3D/cpp/open3d/CMakeLists.txt:66 (open3d_link_3rdparty_libraries)
```
[CMakeError.log](https://github.com/intel-isl/Open3D/files/6083088/CMakeError.log)
[CMakeOutput.log](https://github.com/intel-isl/Open3D/files/6083089/CMakeOutput.log)

Thanks in Advance

**Comment by yxlao** [comment]
It could be tricky to get `add_subdirectory` working across different projects. When you `add_subdirectory`, the dependency project will share the same flags as the main project. 

I recommend the following options:
1. Build Open3D alongside your project with `ExternalProject_Add()`. See https://github.com/intel-isl/Open3D-Example-Project for a working example. 
2. Build and install open3d, and then use `find_package()` to import Open3D to CMake, see http://www.open3d.org/docs/release/cpp_project.html for details.
