### ISSUE TITLE
Scale with different values for different axis

### ISSUE THREAD

**Issue by ashwath98** [intel-isl/Open3D#3127]
**Describe the solution you'd like**
Currently TriangleMesh.scale function supports uniform scaling about centre; 

Is it possible to scale non uniformly about different axis with current API version

One Approach I think to do this would be :Translate Mesh Origin to Centre -> Scale vertex x,y and z values -> Translate Mesh Back
Any other suggestions to do this will be greatly appreciated

**Comment by prewettg** [comment]
The `transform()` method lets you pass in a 4x4 matrix, so you should be able to do any transformation you want with that.
