### ISSUE TITLE
Drawing plane to point cloud with Python

### ISSUE THREAD

**Issue by zhaocheng-hub** [intel-isl/Open3D#3131]
How to draw a plane `ax + by +cz +d ` to a point cloud through open3d

**Comment by prewettg** [comment]
One way would be to generate a grid of x, y values and find the z value via the equation, which will give you the point cloud. You can then visualize it with `open3d.visualization.draw()`. See [`examples/python/gui/draw.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py) for examples of creating a point cloud (`make_point_cloud()` on line 21) and using `open3d.visualization.draw()`.
