### ISSUE TITLE
Why the downloaded source code doesn't contain 3rdparty?

### ISSUE THREAD

**Issue by caibf** [intel-isl/Open3D#3134]
I had downloaded the source code from [release page](https://github.com/intel-isl/Open3D/releases). When configured by cmake, a lot of dependencies were lost. Ah, they were not exist.

How do I deal with it?

**Comment by ssheorey** [comment]
Third party code is downloaded separately during build. What error are you getting?

**Comment by ssheorey** [comment]
Here are some things that will help:
- Some 3rd party code is downloaded as archives and others as git submodules. The archives can be separately downloaded and cached locally in a location specified by the environment variable `OPEN3D_THIRD_PARTY_DOWNLOAD_DIR`
- We are in the process of moving downloads (both 3rd party code and test data) to a separate location. See this PR for details: https://github.com/intel-isl/Open3D/pull/3105

**Comment by stotko** [comment]
Hi @caibf. we are working on that. #3643 is a first step to port all submodules to URL downloading. Once we finished that effort, zipped archives of Open3D should work just like cloning the repository.
