### ISSUE TITLE
Merge multiple meshes into one single mesh

### ISSUE THREAD

**Issue by HollowHeartNet** [intel-isl/Open3D#3140]
Dear community,

I would like to put a feature request: A function that is able to merge multiple meshes into one single mesh similar to the "Flatten Visible Layer" function in meshlab.

**Comment by dd-ff** [comment]
You can merge meshes using '+=' operator.
For example:
mesh1 = o3d.geometry.TriangleMesh()
mesh2 = o3d.geometry.TriangleMesh()
mesh2 += mesh1

**Comment by HollowHeartNet** [comment]
Thank you, Sir.
