### ISSUE TITLE
ModuleNotFoundError: No module named'open3d.cpu' when build with GCC10

### ISSUE THREAD

**Issue by NobuoTsukamoto** [intel-isl/Open3D#3141]
**Describe the bug**
When build from source with GCC10, import python module fails.
- The CMAKE flags are:
  `-DBUILD_SHARED_LIBS=ON -DBUILD_CUDA_MODULE=ON -DBUILD_LIBREALSENSE=ON -DGLIBCXX_USE_CXX11_ABI=ON`
- No error occurs with `make` and `make install-pip-package`.
- Occurs when building with GCC 10. It does not occur when building with GCC 9.

When import open3d module in python, I get the following error:
```
$ python -c "import open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/name/.virtualenvs/open3d/lib/python3.9/site-packages/open3d/__init__.py", line 76, in <module>
    from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
ModuleNotFoundError: No module named 'open3d.cpu'
```

**To Reproduce**
```
$ git clone --recursive https://github.com/intel-isl/Open3D
$ cd Open3d
$ mkdir build && cd build
$ cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DPYTHON_EXECUTABLE=$(which python3) \
    -DBUILD_CUDA_MODULE=ON \
    -DGLIBCXX_USE_CXX11_ABI=ON \
    -DBUILD_LIBREALSENSE=ON  \
    -DCMAKE_BUILD_TYPE=Release \
    ...
$ make -j$(nproc)
$ sudo make install
$ make install-pip-package
$ python -c "import open3d"
```

**Expected behavior**
  

**Screenshots**
  

**Environment (please complete the following information):**

- Operating system: Fedora 33
- Python version: 3.9.2 
  ```
  $ python
  Python 3.9.2 (default, Feb 20 2021, 00:00:00) 
  [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
  ```
- Open3D version: commit 5d6a1cebc247a38dc979833c28591cebeb053034
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): GCC 10.2.1
  ```
  $ gcc -v
  Using built-in specs.
  COLLECT_GCC=/usr/bin/gcc
  COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
  OFFLOAD_TARGET_NAMES=nvptx-none
  OFFLOAD_TARGET_DEFAULT=1
  Target: x86_64-redhat-linux
  Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
  Thread model: posix
  Supported LTO compression algorithms: zlib zstd
  gcc version 10.2.1 20201125 (Red Hat 10.2.1-9) (GCC) 
  ```

**Additional context**
Failed to load pybind.cpython-39-x86_64-linux-gnu.so (Line 62-63).
https://github.com/intel-isl/Open3D/blob/17b0e6c2b214ebfb3a7bcd30c72d8a00bdfd5e4d/python/open3d/__init__.py#L52-L72

Modify \_\_init\_\_.py as follows to see the details.
```python
        # Check CUDA availability without importing CUDA pybind symbols to
        # prevent "symbol already registered" errors if first import fails.
        _pybind_cuda = _CDLL(
            next((_Path(__file__).parent / 'cuda').glob('pybind*')))
        if _pybind_cuda.open3d_core_cuda_device_count() > 0:
            from open3d.cuda.pybind import (camera, geometry, io, pipelines,
                                            utility, t)
            from open3d.cuda import pybind
            __DEVICE_API__ = 'cuda'
    except OSError as e:  # CUDA not installed
        print(e) # print exception
```

An undefined symbol error (RSBagReader::DEFAULT_BUFFER_SIZEE) occurred in pybind.cpython-39-x86_64-linux-gnu.so.
```
$ python -c "import open3d"
/home/nnn/.virtualenvs/open3d/lib/python3.9/site-packages/open3d/cuda/pybind.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN6open3d1t2io11RSBagReader19DEFAULT_BUFFER_SIZEE
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nnn/.virtualenvs/open3d/lib/python3.9/site-packages/open3d/__init__.py", line 76, in <module>
    from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
ModuleNotFoundError: No module named 'open3d.cpu'
```

Result of nm command (RSBagReader::DEFAULT_BUFFER_SIZEE is an undefined symbol).
```
$ nm -D /home/nnn/.virtualenvs/open3d/lib/python3.9/site-packages/open3d/cuda/pybind.cpython-39-x86_64-linux-gnu.so | grep RSBag
                 U _ZN6open3d1t2io11RSBagReader19DEFAULT_BUFFER_SIZEE
                 U _ZN6open3d1t2io11RSBagReaderC1Em
                 U _ZTIN6open3d1t2io11RSBagReaderE
```

__In libOpen3d.so:__
RSBagReader::DEFAULT_BUFFER_SIZE is declared only in the header.No memory is allocated for the variable ([odr-used](https://en.cppreference.com/w/cpp/language/definition#ODR-use)).
https://github.com/intel-isl/Open3D/blob/17b0e6c2b214ebfb3a7bcd30c72d8a00bdfd5e4d/cpp/open3d/t/io/sensor/realsense/RSBagReader.h#L69

__In pybind.xxx.so:__
RSBagReader::DEFAULT_BUFFER_SIZE is referenced in cpp/pybind/t/io/sensor.cpp
For this reason, it seems that the undefinition symbol error occurred when loading the shared library.
https://github.com/intel-isl/Open3D/blob/17b0e6c2b214ebfb3a7bcd30c72d8a00bdfd5e4d/cpp/pybind/t/io/sensor.cpp#L194

This only happens when building with GCC 10 (Fedora 33). It does not occur with GCC 9 (Fedora 33: build from source or Ubuntu: 20.04 LTS).
I don't know why it's caused by different versions of GCC.

I think it can be fixed by assigning a variable to RSBagReader.cpp.
```cpp
namespace open3d {
namespace t {
namespace io {

const size_t RSBagReader::DEFAULT_BUFFER_SIZE ;       // Definition

RSBagReader::RSBagReader(size_t buffer_size)
```

**Comment by NobuoTsukamoto** [comment]
- `RSBagReader::DEFAULT_BUFFER_SIZE` is a declaration only and has never been declared.  
  As a result, calls that need to be referenced can be undefined symbols.
  See the discussion of pybind/pybind11#682
- The following C++ sample code can reproduce the error of undefined symbols.
  ``` cpp  #include "open3d/Open3D.h"

  int main(int argc, char **argv) {

      std::vector<size_t> v;
      v.push_back(open3d::t::io::RSBagReader::DEFAULT_BUFFER_SIZE);

      return 0;
  }
  ```
  ``` 
  $ make
  main.cpp:(.text.startup+0xc): undefined reference to `open3d::t::io::RSBagReader::DEFAULT_BUFFER_SIZE'
  ```
- The fix proposed in https://github.com/intel-isl/Open3D/pull/3142#pullrequestreview-606870952  is work for C++17 (See  [P0386R2 Inline Variables](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0386r2.pdf)).
  However, it does not work on C++11/14.
- At this point, I think one of the following fixes is appropriate:
  1. Declare `RSBagReader::DEFAULT_BUFFER_SIZE`.
      However, this fix is deprecated in C++17 (P0386R2 Inline Variables In Annex D).
      ``` cpp
      diff --git a/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp b/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp
      index 342f0f07..49f67b5e 100644
      --- a/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp
      +++ b/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp
      @@ -42,6 +42,8 @@ namespace open3d {
       namespace t {
       namespace io {
       
      +const size_t RSBagReader::DEFAULT_BUFFER_SIZE;
      +
       RSBagReader::RSBagReader(size_t buffer_size)
           : frame_buffer_(buffer_size),
             frame_position_us_(buffer_size),
      ```
  2. Modify cpp/pybind/t/io/sensor.cpp to prevent undefined symbol errors.
      However, `RSBagReader::DEFAULT_BUFFER_SIZE` is not declared.
      ```cpp
      diff --git a/cpp/pybind/t/io/sensor.cpp b/cpp/pybind/t/io/sensor.cpp
      index 990ec520..a3d4b8ff 100644
      --- a/cpp/pybind/t/io/sensor.cpp
      +++ b/cpp/pybind/t/io/sensor.cpp
      @@ -191,7 +191,7 @@ void pybind_sensor(py::module &m) {
                           "long time (>10 frame intervals) to process a frame.");
           rs_bag_reader.def(py::init<>())
                   .def(py::init<size_t>(),
      -                 "buffer_size"_a = RSBagReader::DEFAULT_BUFFER_SIZE)
      +                 "buffer_size"_a = []() { return RSBagReader::DEFAULT_BUFFER_SIZE; })
                   .def("is_opened", &RSBagReader::IsOpened,
                        "Check if the RS bag file  is opened.")
                   .def("open", &RSBagReader::Open, "filename"_a,
      
      ```

**Comment by ssheorey** [comment]
@NobuoTsukamoto I was able to build the `master` branch with `gcc-10` (Without CUDA on Ubuntu 20.04. I don't have a Fedora 33 system and CUDA doesn't support `gcc-10 `on Ubuntu 20.04).

```
cmake -DBUILD_SHARED_LIBS=ON -DBUILD_LIBREALSENSE=ON -DGLIBCXX_USE_CXX11_ABI=ON ..
make
```

`RSBagReader::DEFAULT_BUFFER_SIZE`: The header initialization of `static const int` member variables is explicitly allowed:
https://en.cppreference.com/w/cpp/language/static


I suspect the problem may be something else.

Be careful with `make install-pip-package`. You should run `pip uninstall open3d` before re-running `make install-pip-package`, else `pip` may not overwrite the open3d install with a newly build Python package. It is accidentally possible to try linking `pybind*.so` from an older build to `libOpen3D.so` from a newer build (perhaps with different build configs). Using `make python_package` and adding `build/lib/python_package` to your `PYTHONPATH` is safer.

**Comment by NobuoTsukamoto** [comment]
@ssheorey 
Thank you for your relay.
> The header initialization of static const int member variables is explicitly allowed:
In my understanding
- If a const static dada member is odr-used, a definition at namespace scope is required.
  https://en.cppreference.com/w/cpp/language/static
  > If a const non-inline (since C++17) static data member or a constexpr static data member (since C++11)(until C++17) is odr-used, a definition at namespace scope is still required, but it cannot have an initializer. A definition may be provided even though redundant (since C++17).
- [Inline Variable P0386R2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0386r2.pdf) is C++17 or later.
- GCC 9, 10 default to C++14.


In my environment:
- Fedora 33 (native)
  - GCC10 and -DBUILD_CUDA_MODULE=ON occurs.
  - GCC9 and

**Comment by NobuoTsukamoto** [comment]
@ssheorey

I built it again with master (commit 1fee14277727d7016e96c0a1d6ae623f1eff853b).
- Fedora 33
- GCC 10.2.1
- CUDA 11.2
- Python 3.9.2 (virtualenv + virtualenvwrapper)

I created a new Python virtual environment and cleared ccache as well.  
However, I get this error.
```
$ mkvirtualenv --python=python3 test
$ git clone --recursive https://github.com/intel-isl/Open3D
$ cd Open3D
$ mkdir build && cd build
$ ccache -C
$ cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DPYTHON_EXECUTABLE=$(which python3) \
    -DBUILD_CUDA_MODULE=ON \
    -DGLIBCXX_USE_CXX11_ABI=ON \
    -DBUILD_LIBREALSENSE=ON  \
    -DCMAKE_BUILD_TYPE=Release \
    ..
$ make
$ sudo make install
$ make install-pip-package
$ python -c "import open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nobuo/.virtualenvs/test/lib/python3.9/site-packages/open3d/__init__.py", line 75, in <module>
    from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
ModuleNotFoundError: No module named 'open3d.cpu'
```


Check `pybind.cpython-39-x86_64-linux-gnu.so` with **nm** command:  
`RSBagReader::DEFAULT_BUFFER_SIZE` is undefined symbol (U).
```
$ nm -D lib/Release/Python/cuda/pybind.cpython-39-x86_64-linux-gnu.so | grep RSBagReader
                 U _ZN6open3d1t2io11RSBagReader19DEFAULT_BUFFER_SIZEE
                 U _ZN6open3d1t2io11RSBagReaderC1Em
                 U _ZTIN6open3d1t2io11RSBagReaderE
```
Check `libOpen3d.so` with **nm** command:  
The symbol for `RSBagReader::DEFAULT_BUFFER_SIZE` does not exist.
Therefore, `RSBagReader::DEFAULT_BUFFER_SIZE` is a declaration only.
```
$ nm -D lib/Release/libOpen3D.so | grep RSBagReader
0000000000dcfdf0 W _ZN6open3d1t2io11RSBagReader11GetMetadataEv
0000000000dd1320 T _ZN6open3d1t2io11RSBagReader13SeekTimestampEm
0000000000dd1b80 T _ZN6open3d1t2io11RSBagReader17fill_frame_bufferEv
0000000000dd1520 T _ZN6open3d1t2io11RSBagReader4OpenERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
0000000000dd0ba0 T _ZN6open3d1t2io11RSBagReader5CloseEv
0000000000dd0c20 T _ZN6open3d1t2io11RSBagReader9NextFrameEv
0000000000dd3920 T _ZN6open3d1t2io11RSBagReaderC1Em
0000000000dd3920 T _ZN6open3d1t2io11RSBagReaderC2Em
0000000000dd41b0 T _ZN6open3d1t2io11RSBagReaderD0Ev
0000000000dd3e20 T _ZN6open3d1t2io11RSBagReaderD1Ev
0000000000dd3e20 T _ZN6open3d1t2io11RSBagReaderD2Ev
0000000000dcfe10 W _ZNK6open3d1t2io11RSBagReader11GetFilenameB5cxx11Ev
0000000000dcfde0 W _ZNK6open3d1t2io11RSBagReader11GetMetadataEv
0000000000dd1440 T _ZNK6open3d1t2io11RSBagReader12GetTimestampEv
0000000000dd0800 T _ZNK6open3d1t2io11RSBagReader5IsEOFEv
0000000000dcfe00 W _ZNK6open3d1t2io11RSBagReader8IsOpenedEv
0000000000dd4330 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEE6_M_runEv
0000000000dd4450 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEED0Ev
0000000000dd4430 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEED1Ev
0000000000dd4430 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEED2Ev
00000000098920a0 V _ZTIN6open3d1t2io11RSBagReaderE
0000000009892268 V _ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEEE
000000000515f9d0 V _ZTSN6open3d1t2io11RSBagReaderE
000000000515fc40 V _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEEE
0000000009892540 V _ZTVN6open3d1t2io11RSBagReaderE
00000000098925f0 V _ZTVNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEEE
```

----------
I was able to build with ubuntu20.04 (docker container).
- ubuntu20.04 (nvidia/cuda:11.2.1-devel-ubuntu20.04)
- GCC 10.2.0 (gcc-10)
- CUDA 11.2
- Python 3.8.5 (virtualenv + virtualenvwrapper)

Build procedure is the same as Fedora 33.  
`python -c "import open3d"` does not output an error.

Check `pybind.cpython-39-x86_64-linux-gnu.so` with **nm** command:  
The symbol for `RSBagReader::DEFAULT_BUFFER_SIZE` does not exist.
```
# nm -D lib/Release/Python/cuda/pybind.cpython-38-x86_64-linux-gnu.so | grep RSBagReader
                 U _ZN6open3d1t2io11RSBagReaderC1Em
                 U _ZTIN6open3d1t2io11RSBagReaderE
```
Check `libOpen3d.so` with **nm** command:  
The symbol for `RSBagReader::DEFAULT_BUFFER_SIZE` does not exist.
```
# nm -D lib/Release/libOpen3D.so | grep RSBagReader        
0000000000eb4690 W _ZN6open3d1t2io11RSBagReader11GetMetadataEv
0000000000eb6140 T _ZN6open3d1t2io11RSBagReader13SeekTimestampEm
0000000000eb63c0 T _ZN6open3d1t2io11RSBagReader17fill_frame_bufferEv
0000000000eb5a60 T _ZN6open3d1t2io11RSBagReader4OpenERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
0000000000eb52f0 T _ZN6open3d1t2io11RSBagReader5CloseEv
0000000000eb5370 T _ZN6open3d1t2io11RSBagReader9NextFrameEv
0000000000eb9350 T _ZN6open3d1t2io11RSBagReaderC1Em
0000000000eb9350 T _ZN6open3d1t2io11RSBagReaderC2Em
0000000000eb9330 T _ZN6open3d1t2io11RSBagReaderD0Ev
0000000000eb8ef0 T _ZN6open3d1t2io11RSBagReaderD1Ev
0000000000eb8ef0 T _ZN6open3d1t2io11RSBagReaderD2Ev
0000000000eb46c0 W _ZNK6open3d1t2io11RSBagReader11GetFilenameB5cxx11Ev
0000000000eb4680 W _ZNK6open3d1t2io11RSBagReader11GetMetadataEv
0000000000eb62e0 T _ZNK6open3d1t2io11RSBagReader12GetTimestampEv
0000000000eb5120 T _ZNK6open3d1t2io11RSBagReader5IsEOFEv
0000000000eb46a0 W _ZNK6open3d1t2io11RSBagReader8IsOpenedEv
0000000000eb99f0 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEE6_M_runEv
0000000000eb9b90 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEED0Ev
0000000000eb9b70 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEED1Ev
0000000000eb9b70 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEED2Ev
0000000009b831a0 V _ZTIN6open3d1t2io11RSBagReaderE
0000000009b83368 V _ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEEE
000000000545f620 V _ZTSN6open3d1t2io11RSBagReaderE
000000000545f8a0 V _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEEE
0000000009b83640 V _ZTVN6open3d1t2io11RSBagReaderE
0000000009b836f0 V _ZTVNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6open3d1t2io11RSBagReaderEFvvEPS6_EEEEEE
```

It may also be affected by compiler optimizations and versions of python, distributions, etc.  
However, I think that it is necessary the definition of `RSBagReader::DEFAULT_BUFFER_SIZE` (As discussion in pybind/pybind11#682).

**Comment by NobuoTsukamoto** [comment]
It can also be fixed by not adding the definition of `RSBagReader::DEFAULT_BUFFER_SIZE`.
```cpp
diff --git a/cpp/pybind/t/io/sensor.cpp b/cpp/pybind/t/io/sensor.cpp
index 990ec520..bf3bffad 100644
--- a/cpp/pybind/t/io/sensor.cpp
+++ b/cpp/pybind/t/io/sensor.cpp
@@ -191,7 +191,7 @@ void pybind_sensor(py::module &m) {
                     "long time (>10 frame intervals) to process a frame.");
     rs_bag_reader.def(py::init<>())
             .def(py::init<size_t>(),
-                 "buffer_size"_a = RSBagReader::DEFAULT_BUFFER_SIZE)
+                 "buffer_size"_a = size_t{RSBagReader::DEFAULT_BUFFER_SIZE})
             .def("is_opened", &RSBagReader::IsOpened,
                  "Check if the RS bag file  is opened.")
             .def("open", &RSBagReader::Open, "filename"_a,
```

**Comment by ssheorey** [comment]
> If a const static dada member is odr-used, a definition at namespace scope is required.
> https://en.cppreference.com/w/cpp/language/static
> 
>     If a const non-inline (since C++17) static data member or a constexpr static data member (since C++11)(until C++17) is odr-used, a definition at namespace scope is still required, but it cannot have an initializer. A definition may be provided even though redundant (since C++17).

`RSBagReader::DEFAULT_BUFFER_SIZE` is meant to be a compile time constant (no symbol needed in the library), so we should be able to bypass these issues by using `static constexpr int` instead of `static const int` (@yxlao 's suggestion). That didn't work for you, though.

This fixing it is pretty strange:
```
-                 "buffer_size"_a = RSBagReader::DEFAULT_BUFFER_SIZE)
+                 "buffer_size"_a = size_t{RSBagReader::DEFAULT_BUFFER_SIZE})
```
Please go ahead and update PR #3142 with this and add a comment about this issue to the code.
Thanks for the detailed debugging!

**Comment by NobuoTsukamoto** [comment]
> Please go ahead and update PR #3142 with this and add a comment about this issue to the code.
Thanks for the detailed debugging!

Later, I would like to add comments and update the PR.
Also, according to [P0386R2 Inline Variables](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0386r2.pdf) Annex D:
Definition of constexpr static data member without initializer is deprecated (C++17).
For this reason, I would like to change it to `static const`.

Thanks.
