### ISSUE TITLE
How to sample points from external surface and ignore faces inner the object?

### ISSUE THREAD

**Issue by xiaodongww** [intel-isl/Open3D#3148]
Thanks for your great job!

Here is a question about points sampling. I want to sample points on the surface of 3D models. However when I use `mesh.sample_points_uniformly`, it sample points from both internal surface mesh and external surface mesh. Is there anyway to ignore the internal meshes?

Here is the code and [3D model](https://mailsucaseducn-my.sharepoint.com/:u:/g/personal/wuxiaodong18_mails_ucas_edu_cn/Eba04f35s2ZPlb4IkvivaocB84ISOEyFpx6FSpA0bnyXXw?e=2ldzxu).

```python
import open3d as o3d
obj_path = 'raw_model.obj'
mesh = o3d.io.read_triangle_mesh(obj_path)
full_pcd = mesh.sample_points_uniformly(3000)
o3d.visualization.draw_geometries([full_pcd])
```

The object mesh look like this (red arrow indicates the internal faces):
![image](https://user-images.githubusercontent.com/33693065/110447727-77ccf700-80fb-11eb-885e-6a373b1988c7.png)
![image](https://user-images.githubusercontent.com/33693065/110448227-f3c73f00-80fb-11eb-85df-793758575e04.png)

Any suggestion will be helpful. Thanks very much!

**Comment by prewettg** [comment]
`sample_points_uniformly` simply looks at the points, so it will be unable to distinguish between faces. However, I believe that any internal faces would be non-manfold edges, so you could call `get_non_manifold_vertices()` and ignore any vertices that are in that list.
