### ISSUE TITLE
Visualize, interact and integrate manually multiple point clouds

### ISSUE THREAD

**Issue by rimoune** [intel-isl/Open3D#3149]
Is there a way to interact with multiple point clouds in the same visualizer? 
For example, if I have multiple point clouds representing rooms of a house and I want to compose them in a 3d floor map, is there a way to do this?
Many thanks!!
Rima

**Comment by jwesolo** [comment]
Yes, just create multiple point cloud objects and add them all to the scene. Just make sure that they are all in the same coordinate system. For example:

`o3d.visualization.draw ([cloud1, cloud2, cloud3], bg_color=[0,0,0,0], show_ui=True, point_size=4)`

Or, using the old visualizer:

`visualizer.add_geometry (cloud1)`
`visualizer.add_geometry (cloud2)`
`visualizer.add_geometry (cloud3)`
`visualizer.run ()`

(Don't forget to set your options and other settings, which I have left out here.)

**Comment by rimoune** [comment]
Cheers, thanks for taking time to reply!
