### ISSUE TITLE
Build error when building from source (Windows 10 64 - Visual Studio 19)

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [intel-isl/Open3D#3158]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Building Open3D from source leaves me with 55 errors when building the ALL_BUILD target. See build output and steps below. 
Most probably the error sits in front of the screen, however maybe someone can point me in the right direction. 

**To Reproduce**

1. Clone Open3d repository into new folder using git bash `git clone --recursive https://github.com/intel-isl/Open3D` 
2. Open CMake GUI (v3.18.4) with the following Configuration/Changes:
     a) Where is the source code: `C:/Users/Johannes/source/repos/Open3D/Open3D`
     b) Where to build the binaries: `C:/Users/Johannes/source/repos/Open3D/Open3D/build` 
     c) CMAKE_INSTALL_PREFIX: `C:/Open3D`
     d) PYTHON_EXECUTABLE: `C:\Users\Johannes\Anaconda3\python.exe`
     e) PYTHON_IN_PATH: `C:\Users\Johannes\Anaconda3\python.exe`
     d) BUILD_CUDA_MODULE: `TRUE`
3. Configure for Visual Studio 2019 until no errors are shown, none of the configuration is marked red
4. Generate
5. Open Project
6. Change Build Configuration to "Release"
7. Right-Click CMakePredefinedTargets/ALL_BUILD and select `Build` (or `Rebuild`)

**Expected behavior**
Except for building with CUDA Modules this is mostly the standard procedure described in Build from [Source Section of the documentation](http://www.open3d.org/docs/release/compilation.html#). CMAKE doesn't show any errors and finds all the path to the installed NVIDIA CUDA Toolkit (v11.2) items as well as the nvcc compiler. Not sure, why the build fails. 

**Build Output**
[build_output.txt](https://github.com/intel-isl/Open3D/files/6115817/build_output.txt)

**Error List**
[error_list.txt](https://github.com/intel-isl/Open3D/files/6115818/error_list.txt)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7.4 (Anaconda)
- Open3D version: 0.12.0
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): VS2019

**Comment by yxlao** [comment]
Windows CUDA build is not officially supported yet on `master`. You may try #3036 and see if it works for you.

**Comment by TheRealRolandDeschain** [comment]
Hey thanks for the info!
Building without the CUDA module still leaves me with a few `unresolved external symbol_imp_strerror` issues. How can I get rid of those?
I will also read into the link you posted.

**Comment by yxlao** [comment]
Could you post the commands used and the full error message?

**Comment by Dudulle** [comment]
> unresolved external symbol __imp_strerror

This is solved in #3151
The error can also be avoided by setting `STATIC_WINDOWS_RUNTIME=OFF`

**Comment by TheRealRolandDeschain** [comment]
Hi, thanks @Dudulle, turning off `STATIC_WINDOWS_RUNTIME` seemed to work, I only had the project `TIntegrateRGBD` fail at building ([warning treated as error](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2220?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2220)%26rd%3Dtrue&view=msvc-160)), which so far I have resolved by turning off `/WX` in the options. 


For CUDA: Is it planned to be supported on Master in the future?
