### ISSUE TITLE
Is it will be support for win32 Complier?

### ISSUE THREAD

**Issue by liang0724s** [intel-isl/Open3D#3171]
My project only support win32 platform , because of hardware iterface.

**Comment by yxlao** [comment]
32-bit is no longer officially supported. 

To get it working, you'll need to :
- Compile from source and use the right CMake config flags to generate 32-bit binaries
- Some CMake tweaks will be required. For example, in `3rdparty/mkl/mkl.cmake`, you'll need to change the links to point to 32-bit pre-compiled MKL.
