### ISSUE TITLE
Open3D build from source fails during make step

### ISSUE THREAD

**Issue by JeffR1992** [intel-isl/Open3D#3173]
I've been trying to install Open3D by following the instructions given at http://www.open3d.org/docs/release/compilation.html

I am running Ubuntu 18.04 with gcc 10.1.0, clang 10.0.0 and cmake version 3.18.0.

Everything is fine up until I have to build the project with `make`. These are the exact commands I used:
```
git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D
git submodule update --init --recursive
util/install_deps_ubuntu.sh
mkdir build
cd build
cmake -DBUILD_PYTHON_MODULE=OFF ..
make -j$(nproc)
```

The first error I see is near the end of the build process, where I get:
```
[ 99%] Building C object code/CMakeFiles/assimp.dir/__/contrib/zip/src/zip.c.o
[100%] Linking CXX static library libassimp.a
[100%] Built target assimp
[ 12%] Performing install step for 'ext_assimp'
[  0%] Built target IrrXML
[  7%] Built target zlibstatic
[ 14%] Built target zlib
[100%] Built target assimp
Install the project...
-- Install configuration: "Release"
-- Installing: /home/alex/Open3D/build/assimp/lib/cmake/assimp-5.0/assimp-config.cmake
-- Installing: /home/alex/Open3D/build/assimp/lib/cmake/assimp-5.0/assimp-config-version.cmake
-- Installing: /home/alex/Open3D/build/assimp/lib/cmake/assimp-5.0/assimpTargets.cmake
-- Installing: /home/alex/Open3D/build/assimp/lib/cmake/assimp-5.0/assimpTargets-release.cmake
-- Installing: /home/alex/Open3D/build/assimp/lib/pkgconfig/assimp.pc
-- Installing: /home/alex/Open3D/build/assimp/lib/libzlibstatic.a
.
.
.
-- Installing: /home/alex/Open3D/build/assimp/include/assimp/Compiler/pushpack1.h
-- Installing: /home/alex/Open3D/build/assimp/include/assimp/Compiler/poppack1.h
-- Installing: /home/alex/Open3D/build/assimp/include/assimp/Compiler/pstdint.h
[ 12%] Completed 'ext_assimp'
[ 12%] Built target ext_assimp
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

Any help would be appreciated. If any more information is required from my side, I'd be happy to provide this. Thanks.

**Comment by sanskar107** [comment]
@JeffR1992  can you share the full terminal log and error message?

make: *** [all] Error 2 is the error message summary. Usually there are some other error messages printed before this. If you can't find any, please make using VERBOSE=1

**Comment by alexmillane** [comment]
Hi @JeffR1992 I just had the same issue and it was resolved by specifying a path to python3

`cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_INSTALL_PREFIX=../libs ..`

Note that, like you, I am not building the python bindings; this is apparently still required.

**Comment by JeffR1992** [comment]
Thank you @alexmillane, this solved the issue.

**Comment by AncientRemember** [comment]
git checkout v0.12.0,don't use master branch
