### ISSUE TITLE
How to crop/split mesh in Open3D based on vertices?

### ISSUE THREAD

**Issue by rasunag27** [intel-isl/Open3D#3186]
Is it possible to split the mesh in Open3D based on vertex threshold?

For example, I need the mesh into two stl outputs, one with the z-vertex less than 0.5 (with x and y throughout the domain) and second stl with remaining z-vertex or z-coordinates > 0.5.

In Open3D documentation, there is a way to crop the mesh. But it is according to the triangles assigned. Below is the code from the website itself.

` mesh1 = copy.deepcopy(mesh)
 mesh1.triangles = o3d.utility.Vector3iVector(
 np.asarray(mesh1.triangles)[:len(mesh1.triangles) // 2, :])
 mesh1.triangle_normals = o3d.utility.Vector3dVector(
 np.asarray(mesh1.triangle_normals)[:len(mesh1.triangle_normals) // 2, :])

 o3d.visualization.draw_geometries([mesh1])`

So, based on this, How can I crop/split the mesh with respect to vertex? I can access the vertex with mesh.vertices.

Any leads will be appreciated.

Regards, 

Sunag R A.

**Comment by prewettg** [comment]
You don't mention which version of Open3D you are using, but in 0.10 and later there is an `open3d.geometry.TriangleMesh.crop()` function crops to either an `open3d.geometry.AxisAlignedBoundingBox` or an `open3d.geometry.OrientedBoundingBox`. If you need more fine-grained control, or if you need to split into to meshes, you can iterate over the vertices and place each vertex index in one of two arrays, one for each mesh, and then call select_by_index() on each array.  So something like the following (which is untested pseudocode):
```
out1_indices = []
out2_indices = []
for i in range(mesh.vertices):
    if is_vertex_in_out1(mesh.vertices[i]):
        out1_indices.append(i)
    else:
        out2_indices.append(i)
out1 = mesh.select_by_indices(out1_indices, True)
out2 = mesh.select_by_indices(out2_indices, True)
```
