### ISSUE TITLE
Incorrect depth frame in o3d.t.io.RSBagReader()

### ISSUE THREAD

**Issue by YoniChechik** [intel-isl/Open3D#3197]
When reading the demo l515 .bag file from your example (http://www.open3d.org/docs/release/tutorial/sensor/realsense.html) the output depth image seams corrupted (plus it looks as if this is only the upper left quadrant of the image beneath the noise)
```
import open3d as o3d
import matplotlib.pyplot as plt 

bag_filename = r"C:\Users\chech\Desktop\python_testing\L515_test.bag"

bag_reader = o3d.t.io.RSBagReader()
bag_reader.open(bag_filename)
while not bag_reader.is_eof():
    im_rgbd = bag_reader.next_frame()
    plt.subplot(1, 2, 1)
    plt.title('RGB image')
    plt.imshow(im_rgbd.color)
    plt.subplot(1, 2, 2)
    plt.title("Depth image")
    plt.imshow(im_rgbd.depth)
    plt.pause(0.1)

bag_reader.close()
```
![image](https://user-images.githubusercontent.com/16686924/111915301-2bc86d80-8a7e-11eb-9afc-d16aaa2df84c.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: 0.12
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by ssheorey** [comment]
Hi @YoniChechik You are trying to display a `UInt16` depth image and `matplotlib` needs some help to display it correctly. This works instead:

    depth = o3d.t.geometry.Image((im_rgbd.depth.as_tensor() / 256).to(o3d.core.Dtype.UInt8))
    plt.imshow(depth)

For this file, `bag_reader.metadata.depth_scale` is ~4000 (meter^-1) and `max_depth` is ~4 (meters)., so dividing by 16000 will scale values down to 1 or dividing by 256 will scale down the values to fit in the display range [0,255].

![Screenshot from 2021-05-12 14-06-09](https://user-images.githubusercontent.com/41028320/118051582-1a8d3600-b336-11eb-849d-fb43ca4b6ada.png)

**Comment by YoniChechik** [comment]
Correct. my bad.
