### ISSUE TITLE
How to save the o3D point cloud poisson converted mesh to ascii stl format?

### ISSUE THREAD

**Issue by rasunag27** [intel-isl/Open3D#3200]
Dear All,

I have converted a point cloud mesh to stl format using Open3D. But when I save the mesh, it writes the stl format in a binary form. I need to save it in an ascii format. How can I do that?

`o3d.io.write_triangle_mesh('mesh.stl', mesh)`

The above code saves in binary format. How can I save in  ascii format?

Regards,
Sunag R A.

**Comment by nikhilpatil99** [comment]
> Dear All,
> 
> I have converted a point cloud mesh to stl format using Open3D. But when I save the mesh, it writes the stl format in a binary form. I need to save it in an ascii format. How can I do that?
> 
> `o3d.io.write_triangle_mesh('mesh.stl', mesh)`
> 
> The above code saves in binary format. How can I save in ascii format?
> 
> Regards,
> Sunag R A.

```
o3d.io.write_triangle_mesh('mesh.stl', mesh,ascii = True)
o3d.io.write_triangle_mesh('mesh.stl', mesh, binary = False)
```
Use any one of the we can get the ascii file of mesh
