### ISSUE TITLE
[Open3D ERROR] MemoryManager::GetDeviceMemoryManager: Unimplemented device

### ISSUE THREAD

**Issue by vfdev-5** [intel-isl/Open3D#3204]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I'm trying to execute this tutorial : http://www.open3d.org/docs/release/tutorial/core/tensor.html#Tensor-creation
and see the same issue as in the tutorial:
```
# Specify device.
a = o3c.Tensor(np.array([0, 1, 2]), device=o3c.Device("CUDA:0"))
print("\nSpecified device:\n{}".format(a))
> ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-a10e55b872d3> in <module>
     16
     17 # Specify device.
---> 18 a = o3c.Tensor(np.array([0, 1, 2]), device=o3c.Device("CUDA:0"))
     19 print("\nSpecified device:\n{}".format(a))

RuntimeError: [Open3D ERROR] MemoryManager::GetDeviceMemoryManager: Unimplemented device
```

**To Reproduce**

See http://www.open3d.org/docs/release/tutorial/core/tensor.html#Tensor-creation

**Expected behavior**
Should work or give a comprehensible error message.

**Screenshots**

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.7
- Open3D version: 0.12.0
- Is this remote workstation?: yes
- How did you install Open3D?: pip
- Compiler version (if built from source): gcc 7.5

**Additional context**

NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2

**Comment by yxlao** [comment]
There are two possibilities:
1. You may have a copy of Open3D that is compiled with CPU-only
2. Open3D cannot detect a CUDA device. This could happen when CUDA versions mismatch. Open3D `0.12.0` wheel is compiled with CUDA 10.1. 

You could try compiling Open3D from source with `-DBUILD_CUDA_MODULE=ON` and it should fix the problem.

**Comment by vfdev-5** [comment]
@yxlao Thanks for the reply, yes, in my case it is compiled with CUDA 10.1 and thus few cuda libs are missing due to CUDA versions mismatch.
