### ISSUE TITLE
any plan to support gpu-based kNN

### ISSUE THREAD

**Issue by rancheng** [intel-isl/Open3D#3235]
**Is your feature request related to a problem? Please describe.**
I always use open3d to render very large point cloud (city scale point cloud map) and suffer from the latency, I found that the bottleneck is always at kNN algorithms. Since point-wise normal estimation and cluster algorithms, etc. depends on KNN, and there's a nice gpu based kNN algorithms out there (e.g. [kNN-CUDA](https://github.com/rancheng/kNN-CUDA)). Could you please add the gpu support on the kNN backend to speed up the code.

**Describe the solution you'd like**
add kNN-GPU support along with cpu based flann.

**Comment by yxlao** [comment]
See https://github.com/intel-isl/Open3D/blob/master/python/test/core/test_nn.py

I recommend building from `master` branch from source with `-DBUILD_CUDA_MODULE=ON` since the gpu code was updated recently.
