### ISSUE TITLE
I want to know if open3d can achieve this render effect.

### ISSUE THREAD

**Issue by BiaoBiaoLi** [intel-isl/Open3D#3243]
Thanks your work!!!
I want to know if open3d can achieve this render effect, instead of just one color effect.
![image](https://user-images.githubusercontent.com/44672683/113491332-85ab4780-9502-11eb-9528-966a8b05a848.png)
![image](https://user-images.githubusercontent.com/44672683/113491355-ab385100-9502-11eb-820e-b9e2777085d2.png)

**Comment by prewettg** [comment]
Yes, this effect is possible. `open3d.geometry.PointCloud` has a `colors` field than lets you specify a color for each point. (It looks like you are using a point cloud, but `LineSet` and `TriangleMesh` also have a `colors` field.)  For the circles, the easiest way is to create a sphere using `open3d.geometry.TriangleMesh.create_sphere` and use an unlit shader. If you use `open3d.visualization.draw()`, it will automatically draw anything without normals unlit and anything with normals lit. You can also provide the `open3d.visualization.rendering.Material` yourself, specifying either `m.shader = "defaultUnlit"` or `m.shader = "defaultLit"`. Please see the [`examples/python/gui/draw.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py) for an example. In particular, look at `make_point_cloud()` and `multi_objects()`.
