### ISSUE TITLE
Using geometry::RGBDImage in cuda function t::geometry::PointCloud::CreateFromRGBDImage sets depth values to zero

### ISSUE THREAD

**Issue by HM102** [intel-isl/Open3D#3250]
I want to use the created rgbd_image from **redwood dataset**, and pass it to a cuda point cloud. I tried the following:

```
//Color : 640 x 480 x 3 (8 bits per channel)
//Depth : 640 x 480 x 1 (16 bits per channel)
geometry::Image color, depth;
io::ReadImage(color_filename, color);
io::ReadImage(depth_filename, depth); 
std::shared_ptr<geometry::RGBDImage> rgbd_image = geometry::RGBDImage::CreateFromColorAndDepth(
                        color, depth, 1000.0, 4.0, false);
auto pcd = geometry::PointCloud::CreateFromRGBDImage(*rgbd_image,intrinsic);
visualization::DrawGeometries({pcd});
```
![image](https://user-images.githubusercontent.com/43437535/113605046-6cabaf00-9646-11eb-9c0e-40b922cfe03b.png)
 
The above works perfectly. Now I pass the created rgbd into the cuda pointcloud

```
t::geometry::Image depth_cuda = t::geometry::Image::FromLegacyImage(rgbd_image->depth_, device);
t::geometry::Image color_cuda = t::geometry::Image::FromLegacyImage(rgbd_image->color_, device);
depth_cuda  = depth_cuda.To(core::Dtype::UInt16); // t::geometry::PointCloud::CreateFromRGBDImage takes only Uint16
t::geometry::RGBDImage rgbd_t = open3d::t::geometry::RGBDImage(color_cuda,depth_cuda);

//Depth image already scaled, scale should be 1.0 now
t::geometry::PointCloud pcd = t::geometry::PointCloud::CreateFromRGBDImage(rgbd_t, intrinsic_t, extrinsic_t, 1.0, max_depth, 4);
auto pcd_legacy = std::make_shared<geometry::PointCloud>(pcd.ToLegacyPointCloud()); 
visualization::DrawGeometries({pcd_legacy});
```
![image](https://user-images.githubusercontent.com/43437535/113605091-7a613480-9646-11eb-9e1b-b2fe3cd162b6.png)
 
The values appear to be lost during a conversion step. Note sure which step. @theNded any idea?

**Comment by ssheorey** [comment]
> depth  = depth.To(core::Dtype::UInt16); // t::geometry::PointCloud::CreateFromRGBDImage takes only Uint16

What was the original data type?

> //Depth image already scaled, scale should be 1.0 now
> t::geometry::PointCloud pcd = t::geometry::PointCloud::CreateFromRGBDImage(rgbd_t, intrinsic_t, extrinsic_t, 1.0, max_depth, 4);

Are you using `meters` as units for each of `extrinsic_t`, `max_depth` and the `depth_cuda` image values?  Scaling (e.g. by 1000) will leave `uint16_t` values such as {0, 1, 2, 3, 4} resulting in flat planes like you see. In this case please try using the unscaled depth image and provide the scale to the function.

**Comment by HM102** [comment]
Hi @ssheorey 

I setup the following for sanity check: 

I use the original color and depth directly with a scale 1000.0, it works perfect.
```
geometry::Image color, depth;
io::ReadImage(color_filename, color);
io::ReadImage(depth_filename, depth); 
t::geometry::Image depth_cuda = t::geometry::Image::FromLegacyImage(depth, device);
t::geometry::Image color_cuda = t::geometry::Image::FromLegacyImage(color, device);

core::Dtype dtype = depth_cuda.AsTensor().GetDtype();
std::cout<<dtype.ToString()<<std::endl;

t::geometry::RGBDImage rgbd_t = open3d::t::geometry::RGBDImage(color_cuda,depth_cuda);
t::geometry::PointCloud pcd = t::geometry::PointCloud::CreateFromRGBDImage(rgbd_t, intrinsic_t, extrinsic_t, 1000.0, max_depth, 4);
auto pcd_legacy = std::make_shared<geometry::PointCloud>(pcd.ToLegacyPointCloud());
visualization::DrawGeometries({pcd_legacy});
```
`UInt16`

![image](https://user-images.githubusercontent.com/43437535/113605046-6cabaf00-9646-11eb-9c0e-40b922cfe03b.png)

The problem happens as mentioned in the initial comment when I use:
```
t::geometry::Image depth_cuda = t::geometry::Image::FromLegacyImage(rgbd_image->depth_, device);
t::geometry::Image color_cuda = t::geometry::Image::FromLegacyImage(rgbd_image->color_, device);
// rgbd_image->depth_ here is Float32 contrartry to Uint16. 
```
instead of 
```
t::geometry::Image depth_cuda = t::geometry::Image::FromLegacyImage(depth, device);
t::geometry::Image color_cuda = t::geometry::Image::FromLegacyImage(color, device);
```
In my application I need to use `rgbd_image` as input and not the original images.

**Comment by ssheorey** [comment]
If you are on `master`, the recently merged PR #3229 added support for `float32` depth images in `CreateFromRGBDimage()`. We'll update the documentation. You shouldn't need to convert to `UInt16` any more.
I think here is the problem:

> depth_cuda  = depth_cuda.To(core::Dtype::UInt16); // t::geometry::PointCloud::CreateFromRGBDImage takes only Uint16

You have to scale the image back up if you convert from float in range [0, 1] to uint16, otherwise information is lost. Image::To() allows you to specify a scale and offset.

**Comment by HM102** [comment]
Works when merging the PR. No need for conversion anymore. 
Thanks!

**Comment by vocdex** [comment]
I had the same problem when creating point clouds from RGBD image in Open3D Python. I can confirm changing np.uint16 to np.float32 when creating depth image solved the problem
