### ISSUE TITLE
Bug in t::geometry::PointCloud::CreateFromDepthImage when using Float32 depth

### ISSUE THREAD

**Issue by HM102** [intel-isl/Open3D#3260]
I have a float32 `cv::Mat depth`  and convert it to open3d image:

```
auto depth_im = std::make_shared<open3d::geometry::Image>();
    depth_im->Prepare(color.cols, color.rows, 1, sizeof(uint32_t));
    uint32_t * p = (uint32_t *)depth_im->data_.data();

    for (int i = 0; i < color.rows; i++) {
        for (int k = 0; k < color.cols; k++) {
            *p++ = depth.at<uint32_t>(i, k) ;
        }
    }
```
![image](https://user-images.githubusercontent.com/43437535/113900062-ba9eef00-97cd-11eb-98e2-0946c195496b.png)

I create a point cloud using `geometry::PointCloud`

```
auto pcd = open3d::geometry::PointCloud::CreateFromDepthImage(*depth_im, intrinsicc,extrinsic,1.0,4.0,1.0);
open3d::visualization::DrawGeometries({pcd});
```
![image](https://user-images.githubusercontent.com/43437535/113900142-d1dddc80-97cd-11eb-9ef1-3007acb1a7fc.png)

Now I use the `t::geometry::PointCloud`

```
open3d::t::geometry::Image depth_cuda =  open3d::t::geometry::Image::FromLegacyImage(*depth_im, device);

open3d::t::geometry::PointCloud pcd_cuda open3d::t::geometry::PointCloud::CreateFromDepthImage(depth_cuda,intrinsic_t,extrinsic_t,1.0,4.0,1.0);
auto pcd_legacy = std::make_shared<open3d::geometry::PointCloud>(pcd_cuda.ToLegacyPointCloud());
open3d::visualization::DrawGeometries({pcd_legacy});
```
![image](https://user-images.githubusercontent.com/43437535/113899886-8b887d80-97cd-11eb-966b-109e992c862e.png)

I am getting empty point cloud!

**Comment by ssheorey** [comment]
Hi @HM102 `UInt32` is not supported for `CreateFromDepthImage`. Only `UInt16` and `Float32`. You should get an error, though. Are you working on `master`? Do things work if you convert the datatype to `UInt16` or `Float32`?

**Comment by HM102** [comment]
Hi @ssheorey I checked the input `cv::Mat` again, it's actually `float32`. I edit the question accordingly. 

As a sanity check I did this:
```
open3d::core::Dtype dtype = depth_cuda.AsTensor().GetDtype();
std::cout<<dtype.ToString()<<std::endl;

Float32
```

I changed `cv::Mat` -` open3d` conversion (`float` instead of `uint32_t`):
```
auto depth_im = std::make_shared<open3d::geometry::Image>();
    depth_im->Prepare(color.cols, color.rows, 1, sizeof(float));
    float * p = (float *)depth_im->data_.data();

    for (int i = 0; i < color.rows; i++) {
        for (int k = 0; k < color.cols; k++) {
            *p++ = depth.at<float>(i, k) ;
        }
    }
```

got the same results as before!

**Comment by HM102** [comment]
solved when merging latest PR. may be related to #3250
