### ISSUE TITLE
Wrong Python documentation of open3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape

### ISSUE THREAD

**Issue by ludwisc** [intel-isl/Open3D#3282]
In the documentation the parameters are:
[http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.htm#l](url)
```
Parameters
    - alpha (float) – Parameter to control the shape. A very big value will give a shape close to the convex hull.
    - alpha – Parameter to control the shape. A very big value will give a shape close to the convex hull.
    - tetra_mesh (open3d.geometry.TetraMesh) – If not None, than uses this to construct the alpha shape. Otherwise, TetraMesh is computed from pcd.
    - pt_map (List[int]) – Optional map from tetra_mesh vertex indices to pcd points.
```
I think the first parameter is wrong and should be of type `open3d.geometry.PointCloud`

I saw it in the version `0.12.0`

**Comment by ssheorey** [comment]
Looking into this a bit more, I think `docstring::ClassMethodDocInject` does not work correctly for overloaded methods.
