### ISSUE TITLE
some point cloud in the OrientedBoundingBox , but crop result is no points in bbox

### ISSUE THREAD

**Issue by enting8696** [intel-isl/Open3D#3284]
- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: 0.9.0
- Is this remote workstation?: no
- How did you install Open3D: conda

I use bbox = OrientedBoundingBox.create_from_points(points)

and can see the result :

![Screenshot from 2021-04-14 21-00-13](https://user-images.githubusercontent.com/59861551/114714176-6fa05100-9d64-11eb-8123-9b2a574bdeb7.png)

but, then i use pcd.crop(bbox)

the crop result should show points that in bbox

but why no points cloud by OrientedBoundingBox  and .crop

**Comment by ssheorey** [comment]
Hi @enting8696 you are working with an old Open3D version. Please try with the latest [development wheel](http://www.open3d.org/docs/release/getting_started.html#development-version-pip) of Open3D and let us know if you still see this issue. If you do, can you upload a script and minimal data that we can run to reproduce the problem?

**Comment by enting8696** [comment]
In #3038 

Upgrade Open3d to 0.12.0 is work

The result after cropping with the bounding box has no point cloud problem was solved !

Thanks @ssheorey
