### ISSUE TITLE
fatal error: fmt/format.h:   #include <fmt/format.h>  on JetSon Nano Ubuntu18

### ISSUE THREAD

**Issue by 43998213** [intel-isl/Open3D#3306]
make -s -f CMakeFiles/Makefile2 all
[  0%] Performing update step for 'open3d_downloads'
[download_utils.py] /home/zjh/open3d/Open3D/examples/test_data/open3d_downloads/RGBD/raycast_vtx_004.npy already exists, skipped.
[  1%] No patch step for 'open3d_downloads'
[  1%] No configure step for 'open3d_downloads'
[  1%] No build step for 'open3d_downloads'
[  1%] No install step for 'open3d_downloads'
[  2%] Completed 'open3d_downloads'
[  2%] Built target open3d_downloads
[  3%] Built target 3rdparty_lzf
[  5%] Built target ext_turbojpeg
[  6%] Built target ext_zlib
[  7%] Built target ext_libpng
[  9%] Built target ext_assimp
[ 11%] Built target ext_jsoncpp
[ 12%] Built target 3rdparty_tinyfiledialogs
[ 14%] Built target ext_tbb
[ 14%] Built target 3rdparty_rply
[ 17%] Built target 3rdparty_qhull_r
[ 19%] Built target ext_faiss
[ 19%] Built target 3rdparty_glew
[ 24%] Built target 3rdparty_qhullcpp
[ 28%] Built target glfw
[ 29%] Built target EncodeShader
[ 30%] Built target ShaderFileTarget
[ 31%] Building CXX object cpp/open3d/visualization/CMakeFiles/visualization.dir/shader/GeometryRenderer.cpp.o
In file included from /home/zjh/open3d/Open3D/cpp/open3d/geometry/Image.h:34:0,
                 from /home/zjh/open3d/Open3D/cpp/open3d/visualization/shader/ImageMaskShader.h:29,
                 from /home/zjh/open3d/Open3D/cpp/open3d/visualization/shader/GeometryRenderer.h:30,
                 from /home/zjh/open3d/Open3D/cpp/open3d/visualization/shader/GeometryRenderer.cpp:27:
/home/zjh/open3d/Open3D/cpp/open3d/utility/Console.h:40:10: fatal error: fmt/format.h: 
 #include <fmt/format.h>
          ^~~~~~~~~~~~~~
compilation terminated.
cpp/open3d/visualization/CMakeFiles/visualization.dir/build.make:82: recipe for target 'cpp/open3d/visualization/CMakeFiles/visualization.dir/shader/GeometryRenderer.cpp.o' failed
make[2]: *** [cpp/open3d/visualization/CMakeFiles/visualization.dir/shader/GeometryRenderer.cpp.o] Error 1
CMakeFiles/Makefile2:1714: recipe for target 'cpp/open3d/visualization/CMakeFiles/visualization.dir/all' failed
make[1]: *** [cpp/open3d/visualization/CMakeFiles/visualization.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

god ....  too hard

**Comment by TxT1212** [comment]
Hi, 43998213. 
I had the same problem! Did you fix it?
