### ISSUE TITLE
Visualization crashes sometimes in Windows

### ISSUE THREAD

**Issue by ShikiGami** [intel-isl/Open3D#331]
I compiled Open3D on windows, and I've been experiencing some weird crashes while running the tutorials.

One of the more annoying ones is one where from time to time the application just crashes when calling `draw_geometries` . It shows a blank window, and seems to be "loading something" but then it just crashes.

The weird thing is that it isn't constant at all.
Running the same sample multiple times, some times it crashes and some times it doesn't.
I've been trying to run the VS debuger on it, but the application dies before I can run the VS debuger.

**Comment by syncle** [comment]
For better understanding the issue, can you tell me your environment (windows version and visual studio version) and the script makes runtime error? For your reference, we are testing Open3D on windows 8+ and Visual studio 2015 SP3+.

**Comment by ShikiGami** [comment]
My enviroment:
Windows 10 Pro (1709)
Visual Studio 2017 (15.6.6)

I'm building and installing Open3D with the new CMake support included in Visual Studio 2017 using the Ninja generator, as a msvc_x86 Release Build.

It is a Runtime error that crashes the application, and just a few moments ago I was able to get a read of what is going on with the VS debugger, and it's calming to be an unhanded exception or what seems to be a memory access violation error occurring when calling some Eigen function.

It's marking as a breaking point the line 35 of `ProductsEvaluators.h`

**Comment by ShikiGami** [comment]
The last call before the error seems to be:
`Eigen::internal::evaluator<Eigen::Product<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,4,0,4,4>,0>,Eigen::Matrix<float,4,4,0,4,4>,1> >(const Eigen::Product<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,4,0,4,4>,0>,Eigen::Matrix<float,4,4,0,4,4>,1> & xpr)`

**Comment by syncle** [comment]
Just note. I tried to regenerate the issue, but no luck so far. I am using windows10 + cmake3.11.1 + anaconda 64bit based python 3.6.

**Comment by syncle** [comment]
Some updates:

This especially happens in windows 32bit machine. As @ShikiGami and I noted above, it arose from Eigen. Check [Cause 1: Structures having Eigen objects as members](http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html). If class has fixed size vectors, such as `Eigen::Vector2d` the class is no longer memory aligned with SSE format. This crashes an app with segfault error.

I was able to resolve the issue for some point by adding 
```
public:
	EIGEN_MAKE_ALIGNED_OPERATOR_NEW
```
in `ViewControl` class. However, the issue is not completely resolved. Actually, I am not big fan of adding this macro for every classes. I am curious why this issue not happens in 64bit machines. :stuck_out_tongue:

**Comment by DennyLindberg** [comment]
Reporting in that this is still a problem. Windows 10, Python 3.7.3 32-bit and Open3D via pip install. Crashes as soon as I use draw_geometries or any visualization method that spawns a window. It is sporadic just as the OP claims.

Stopped crashing as soon as i re-installed Python 64-bit and got the 64-bit packages via pip install.

**Comment by germanros1987** [comment]
32bits are no longer supported by new releases of Open3D

**Comment by Andyjk1406** [comment]
Hi

This problem still happens on 64 bit windows. I'm running the C++ version, not Python.
Intermittent visualizer crashes which abort the program.

I have added 
public:
	EIGEN_MAKE_ALIGNED_OPERATOR_NEW

into the ViewControl class but the problem persists.

In RelWithDebug it shows it stops on the call to DrawGeometries with:

Unhandled exception at 0x00007FFE42C33B29 in Register_Clouds.exe: Microsoft C++ exception: std::runtime_error at memory location 0x0000000F9CEFDF70. occurred

 	KernelBase.dll!00007ffe42c33b29()	Unknown
 	[External Code]	
 	Register_Clouds.exe!open3d::utility::Logger::VError(char const *,struct fmt::v6::format_args)	C++
 	Register_Clouds.exe!open3d::utility::LogError<char const *>(char const *,char const * const &)	C++
 	Register_Clouds.exe!open3d::visualization::Visualizer::DestroyVisualizerWindow(void)	C++
 	Register_Clouds.exe!_glfwInputError()	C
 	Register_Clouds.exe!_glfwInputErrorWin32()	C
 	Register_Clouds.exe!glfwGetWGLContext()	C
 	Register_Clouds.exe!open3d::visualization::Visualizer::Run(void)	C++
 	Register_Clouds.exe!open3d::visualization::DrawGeometries(class std::vector<class std::shared_ptr<class open3d::geometry::Geometry const >,class std::allocator<class std::shared_ptr<class open3d::geometry::Geometry const > > > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int,int,bool,bool,bool,class Eigen::Matrix<double,3,1,0,3,1> *,class Eigen::Matrix<double,3,1,0,3,1> *,class Eigen::Matrix<double,3,1,0,3,1> *,double *)	C++
>	Register_Clouds.exe!main(int argc, char * * argv) Line 177	C++
 	[External Code]
