### ISSUE TITLE
'open3d.cuda.pybind.visualization.gui.Widget' has no attribute 'Constraints'

### ISSUE THREAD

**Issue by DenisTome** [intel-isl/Open3D#3315]
**'open3d.cuda.pybind.visualization.gui.Widget' has no attribute 'Constraints'**
Pull latest version from master branch and running vanilla vis-gui.py.
This triggers the error
```
Traceback (most recent call last):
  File "vis-gui.py", line 780, in <module>
    main()
  File "vis-gui.py", line 776, in main
    gui.Application.instance.run()
  File "vis-gui.py", line 515, in _on_layout
    theme, gui.Widget.Constraints()).height)
AttributeError: type object 'open3d.cuda.pybind.visualization.gui.Widget' has no attribute 'Constraints'
```

**To Reproduce**

1. cd examples/python/gui
2. python vis-gui.py
3. See error

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04.5 LTS
- Python version: Python 3.7.4 and 3.7.1
- Open3D version: 0.12.0
- Is this remote workstation?: no
- How did you install Open3D?: Conda (same with pip)

**Comment by prewettg** [comment]
You are running an example from the `master` branch but using the wheel from the `v0.12.0` branch, which is almost 4 months behind `master`. You will need to either need to compile the wheel using `master` or use the examples from the [`v0.12.0`](https://github.com/intel-isl/Open3D/tree/v0.12.0) branch. Please see the [compilation guide](http://www.open3d.org/docs/release/compilation.html) if you choose to compile. Once you have run cmake, `make -j6 pip-package` in the build directory will make the wheel, and you can install it using `pip uninstall -y open3d && pip install lib/python_package/pip_package/open3d-<tab>`.
