### ISSUE TITLE
Import/Export of 3D point files in  las/laz file format (ASPRS = American society for photogrammetrie and remote sensing)

### ISSUE THREAD

**Issue by weinacker** [intel-isl/Open3D#3321]
Hello Open3D developer team,

we would like to use Open3D in our projects and also for teaching python
courses.

From research projects in the area of airborne and terrestrial laserscanning
we have a lot of data. But normally all the 3D point clouds we get are stored
as las/laz files and we also have to send processed 3D points (for example segmented or
classified points) stored in las/laz format.
(the format is defined by the ASPRS, American society for photogrammetrie and
remote sensing, https://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf )

As far as I have checked it, it is not possible to import/export these two file formats
into Open3D. This would be of great advantage, because than we have not to save
the 3D point clouds first as pcd, ply or ascci files, which take a lot of additional storage
space and time.

Pherhaps it is an idea you could think about. That would make your great library
even more useable. 

Thank you for allowing users to make suggestions for improvements

Best regards
Holger Weinacker

**Comment by aweinmann** [comment]
Hi, 
I import las files and create open3d point clouds from it by myself using laspy. 
Maybe this helps you in the short term.

```
import numpy as np
import laspy as lp
import open3d as o3d

point_cloud = lp.file.File(las_file, mode="r")

points = np.vstack((point_cloud.x, point_cloud.y, point_cloud.z)).transpose()
colors = np.vstack((point_cloud.red, point_cloud.green, point_cloud.blue)).transpose()

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
pcd.colors = o3d.utility.Vector3dVector(colors / 65535)

```

**Comment by weinacker** [comment]
Thanks a lot for your fast help.
Yes, it helps me/us in the short term

**Comment by Sho-Shoo** [comment]
Hi @aweinmann, 

Simply wondering if the solution you provided above will eat up memory if I am working with rather large pointcloud file > 10GB? Any clue can help. Thanks!
