### ISSUE TITLE
Trying to convert open3d.core.Tensor to np.ndarray throws error

### ISSUE THREAD

**Issue by Algomorph** [intel-isl/Open3D#3333]
**Describe the bug**
Attempt at conversion from any open3d.core.Tensor to np.ndarray throws error.

I realize the above is not yet supported functionality, so this is actually something between a question, bug report, and feature request...

Is there any way to convert an Open3D::core::Tensor to a numpy ND array?

**To Reproduce**

Run the following minimal code example:
```Python
#!/usr/bin/python3
import sys
import open3d.core as o3c
import numpy as np

PROGRAM_EXIT_SUCCESS = 0


def main():
    x = o3c.Tensor([0.1, 1.2, 2.3], dtype=o3c.Dtype.Float32)
    x_np = np.array(x)  # RuntimeError: [Open3D ERROR] Index out-of-range: dim == 3, but it must satisfy -3 <= dim <= 2
    return PROGRAM_EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main())
```

Error:
```
Traceback (most recent call last):
  File "/home/insertyourusernamehere/insertyourworkdirhere/open3d_tensor_test.py", line 17, in <module>
    sys.exit(main())
  File "/home/insertyourusernamehere/insertyourworkdirhere/open3d_tensor_test.py", line 12, in main
    x_np = np.array(x)
RuntimeError: [Open3D ERROR] Index out-of-range: dim == 3, but it must satisfy -3 <= dim <= 2
```

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
- Python version: Python 3.8.5
- Open3D version:  0.12.0 (PiPI)
- Is this remote workstation?: no
- How did you install Open3D?: pip (also tried building from source at 2cf14e942 in master)
- Compiler version (if built from source): gcc 9.3.0

**Comment by Algomorph** [comment]
P.S. I'm looking for a more convenient way than augmenting/using the `TensorToEigen____` converter functions from `cpp/open3d/core/EigenConverter.cpp" from within C++.

If the direct C++ converters (like [pybind11_opencv_numpy](https://github.com/edmBernard/pybind11_opencv_numpy) or [pyboostopencv](https://github.com/Algomorph/pyboostcvconverter) for OpenCV) aren't there yet, are the plans to implement such? (and also, in that case, please feel free to convert this to a feature request)

**Comment by yxlao** [comment]
See http://www.open3d.org/docs/latest/tutorial/core/tensor.html#Numpy-I/O-with-direct-memory-map

Use `tensor.numpy()` and `tensor.from_numpy()`

**Comment by Algomorph** [comment]
@yxlao , thank you, sir! `.numpy()` works like a charm!
