### ISSUE TITLE
VectorEdits in the same CollapsableVert interfere with each other 

### ISSUE THREAD

**Issue by Saafke** [intel-isl/Open3D#3358]
**Describe the bug**
When you put two [VectorEdits](http://www.open3d.org/docs/release/python_api/open3d.visualization.gui.VectorEdit.html) (let's say veditA and veditB) in the same [CollapsableVert](http://www.open3d.org/docs/release/python_api/open3d.visualization.gui.CollapsableVert.html), they interfere with each other. Namely, when changing the first dimension of veditA, veditB will also adopt the same number. 

**To Reproduce**
1. Install development version of Open3D 0.12.0
2. Add two VectorEdits to the same collapsable, example code below:

**Example Code to Reproduce Issue**
```
#!/usr/bin/env python3
import open3d as o3d
import open3d.visualization.gui as gui
import open3d.visualization.rendering as rendering
import platform

isMacOS = (platform.system() == "Darwin")

class AppWindow:

    def __init__(self, width, height):
        resource_path = gui.Application.instance.resource_path

        self.window = gui.Application.instance.create_window(
            "Open3D", width, height)
        w = self.window

        # 3D widget
        self._scene = gui.SceneWidget() 
        self._scene.scene = rendering.Open3DScene(w.renderer) 

        em = w.theme.font_size
        separation_height = int(round(0.5 * em))

        self._settings_panel = gui.Vert(
            0, gui.Margins(0.25 * em, 0.25 * em, 0.25 * em, 0.25 * em))

        # Add GUI panel
        my_settings = gui.CollapsableVert("My bugged settings", 0,
                                                    gui.Margins(em, 0, 0, 0))
        
        # Add two separate vector edits
        vedit1 = gui.VectorEdit()
        vedit1.vector_value = [0,0,0]
        vedit2 = gui.VectorEdit()
        vedit2.vector_value = [1,1,1]

        # Add these to the panel
        row1 = gui.Horiz()
        row1.add_stretch()
        row1.add_child(vedit1)
        row1.add_stretch()

        row2 = gui.Horiz()
        row2.add_stretch()
        row2.add_child(vedit2)
        row2.add_stretch()
        
        my_settings.add_child(row1)
        my_settings.add_child(row2)
        self._settings_panel.add_child(my_settings)

        w.add_child(self._scene)
        w.add_child(self._settings_panel)


def main():
    gui.Application.instance.initialize()
    w = AppWindow(1024, 768)
    gui.Application.instance.run()


if __name__ == "__main__":
    main()
```

**Expected behavior**
The two VectorEdits should not interfere with each other, each should be an independent VectorEdit.

**Screenshots**
N/A

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6.9
- Open3D version: development version 0.12.0 (pip)
- Is this remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): n/a

**Additional context**
Putting the VectorEdits in separate CollapsableVerts solves the problem, however I would like these VectorEdits in the same CollapsableVert.

**Comment by prewettg** [comment]
Thanks for the script to reproduce, that makes things a lot faster! Sadly, I even had code to avoid this very problem, but I forgot to include the last line that actually assigned the unique identifier, *sigh*. This should be fixed by #3360.
