### ISSUE TITLE
Unable to list connected devices (No problems when using PyRealSense2 or Intel Viewer)

### ISSUE THREAD

**Issue by sklipnoty** [intel-isl/Open3D#3364]
I have two Intel Realsense D415 connected to my computer. 
When trying to list devices on Windows 10, I get the 'warning' No Device Connected.
One of the devices is plugged directly into the computer the other one is using an extension cord. I unplugged the one with the extension cord the same problem.

I tried running the same code on Ubuntu 20, then I get a different error:

<pyrealsense2.device: Intel RealSense D415 (S/N: xx  FW: 05.11.06.250  LOCKED: YES)>
<pyrealsense2.device: Intel RealSense D415 (S/N: xx  FW: 05.12.12.100  LOCKED: YES)>
Traceback (most recent call last):
  File "/home/x/PycharmProjects/RealSenseExperiments/main.py", line 9, in <module>
    o3d.t.io.RealSenseSensor.list_devices()
RuntimeError: failed to set power state

The same error occurs when using only the directly plugged in sensor. 

Both PyRealSense and the Viewer seems to work. 

`
import pyrealsense2 as rs
devices = rs.context().query_devices()

for device in devices:
    print(device)

import open3d as o3d
o3d.t.io.RealSenseSensor.list_devices()`

The python version used on both is 3.7, using the latest Open3D version.

**Comment by ssheorey** [comment]
Please test with the latest developer wheel of Open3D from here: http://www.open3d.org/docs/latest/getting_started.html#development-version-pip and let us know if you still have this issue.

**Comment by sklipnoty** [comment]
I tried this solution and it works. I got all sensors listed now. Thanks!
