### ISSUE TITLE
How to set point size and line thickness in visualization module

### ISSUE THREAD

**Issue by TangToy** [intel-isl/Open3D#3371]
I refer the code in http://www.open3d.org/docs/release/tutorial/visualization/visualization.html#Function-draw_geometries and the code as follows:
`print("Let's draw a box using o3d.geometry.LineSet.")
points = [
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [1, 1, 0],
    [0, 0, 1],
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 1],
]
lines = [
    [0, 1],
    [0, 2],
    [1, 3],
    [2, 3],
    [4, 5],
    [4, 6],
    [5, 7],
    [6, 7],
    [0, 4],
    [1, 5],
    [2, 6],
    [3, 7],
]
colors = [[1, 0, 0] for i in range(len(lines))]
line_set = o3d.geometry.LineSet(
    points=o3d.utility.Vector3dVector(points),
    lines=o3d.utility.Vector2iVector(lines),
)
line_set.colors = o3d.utility.Vector3dVector(colors)
point_cloud2 = o3d.geometry.PointCloud()
point_cloud2.points = o3d.utility.Vector3dVector(points)
point_cloud2.paint_uniform_color([0, 1, 0])

o3d.visualization.draw_geometries([line_set, point_cloud2])`

I can get the lines and points:
![截图_2021-05-02_17-15-39](https://user-images.githubusercontent.com/45865043/116808221-32143400-ab6a-11eb-91ab-c23df7245e14.png)
How could I set the plotted point sizes and line thicknesses?

**Comment by prewettg** [comment]
If you press "h" in the visualization window you can get a list of functionality available to you. You can use `=` and `/` to increase and decrease the point size, and `ctrl + =` and `ctrl + -` to change the line width. The old visualizer (`open3d.visualization.Visualizer` / `open3d.visualization.draw_geometries()`) does not support setting the point size and line widths programmatically. However, you can use the new visualizer (`open3d.visualization.O3DVisualizer` / `open3d.visualization.draw()`), which does support them. This feature is supported in 0.12, and you can find an example at [`examples/python/gui/line-width.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/line-width.py).  See also [`examples/python/gui/draw.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py).

**Comment by TangToy** [comment]
Thanks a lot. I have tried to use `open3d.visualization.draw_geometries()`, which can realize adjusting point sizes and line 
thicknesses. However,  when I used the _selection_ function and wanted to select the point and get the point coordinate,  the dialog show as this.
![2021-05-06 16-58-02 的屏幕截图](https://user-images.githubusercontent.com/45865043/117271946-44a1ac80-ae8d-11eb-8a07-5393a846b1c9.png)

 Can I select the points and get the coordinates as the function `o3d.visualization.draw_geometries_with_editing`? Thanks a lot.
> If you press "h" in the visualization window you can get a list of functionality available to you. You can use `=` and `/` to increase and decrease the point size, and `ctrl + =` and `ctrl + -` to change the line width. The old visualizer (`open3d.visualization.Visualizer` / `open3d.visualization.draw_geometries()`) does not support setting the point size and line widths programmatically. However, you can use the new visualizer (`open3d.visualization.O3DVisualizer` / `open3d.visualization.draw()`), which does support them. This feature is supported in 0.12, and you can find an example at [`examples/python/gui/line-width.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/line-width.py). See also [`examples/python/gui/draw.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py).
