### ISSUE TITLE
GUI build is failing on open3d_downloads

### ISSUE THREAD

**Issue by Ravenwater** [intel-isl/Open3D#3376]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Trying to build the GUI application

**To Reproduce**

1. VS build GUI project

**Expected behavior**
A successful build

**Screenshots**
```
2>Creating directories for 'open3d_downloads'
2>Performing download step for 'open3d_downloads'
2>'PYTHON_IN_PATH-NOTFOUND' is not recognized as an internal or external command,
2>operable program or batch file.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Custom build for 'C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-mkdir.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-download.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-update.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-patch.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-configure.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-build.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\fe3cc6bf8faee750f26adb85cc9dfb27\open3d_downloads-install.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\96650b1fe0967a01a2a7e91b04f28ed1\open3d_downloads-complete.rule;C:\Users\tomtz\Documents\dev\forks\Open3D\build\CMakeFiles\3f81b1540b3459cd380024a11e6b4b55\open3d_downloads.rule' exited with code 9009.
2>Done building project "open3d_downloads.vcxproj" -- FAILED.
```

- Operating system: Windows 10 64-bit
- Python version: Python 3.8.5
- Open3D version: commit https://github.com/intel-isl/Open3D/commit/0f59e75e73757c9b52fdfb69b42a09e2581a8b30
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): VS 16.9.3

**Additional context**

**Comment by ssheorey** [comment]
> 2>'PYTHON_IN_PATH-NOTFOUND' is not recognized as an internal or external command,

Python executable was not found in your PATH. Either add it to the `PATH`, or run `cmake` (in an empty `build` folder) with the additional option:
`-D PYTHON_EXECUTABLE=<full_path_to_your_python.exe>`

**Comment by Ravenwater** [comment]
@ssheorey quick double-check. If I am only interested in the C++ side of the library, I STILL NEED a python environment? 

if the answer is yes, can you point me to documentation on how to use virtual environments from an Anaconda environment?

Python is an unpleasant integration environment, so weighting down the C++ environment with a python dependency is unfortunate.

**Comment by ssheorey** [comment]
Hi @Ravenwater I believe Open3D's default configuration still looks for Python even if `BUILD_PYTHON_MODULE=OFF`. We will look into avoiding this going forward.

For now, here is some documentation on setting a up a virtual environment in Anaconda:

https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/

**Comment by yxlao** [comment]
This is a good point.

We did the current design so that a pure-python user (e.g. a user who runs `pip install open3d` and clone the Open3D repo to run Python examples) can trigger downloads without installing CMake.

But, we also want a pure-C++ user to trigger downloads without installing Python. On Linux/macOS, python is typically pre-installed or it is easy to install. On Windows, we run into this issue that we're discussing.

One solution is to add a separate download mechanism in CMake for pure-C++ users. CMake needs to parse `examples/test_data/download_file_list.json` and put the files in the correct location.

We'll look into this going forward. @Ravenwater you're also welcomed to create a pull request if you feel like implementing it.

**Comment by Ravenwater** [comment]
@yxlao yes, let me take a look at that problem and see if I can solve that. Before I tinker with the system, I like to start from a working system, so good to know that I should try to start from a Linux build and work forward towards a pure C++ MSVC build.

**Comment by yxlao** [comment]
@Ravenwater the easiest way to get around this is by disabling the download step. The download step is used to download some supporting datasets for unit test. E.g., you can do something like:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 01895f9a2..5cd1a846c 100755
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -472,8 +472,8 @@ endif()
 include(ExternalProject)
 ExternalProject_Add(
     open3d_downloads
-    DOWNLOAD_COMMAND ${PYTHON_EXECUTABLE} ${PROJECT_SOURCE_DIR}/examples/test_data/download_test_data.py
-    UPDATE_COMMAND   ${PYTHON_EXECUTABLE} ${PROJECT_SOURCE_DIR}/examples/test_data/download_test_data.py
+    DOWNLOAD_COMMAND ""
+    UPDATE_COMMAND   ""
     CONFIGURE_COMMAND ""
     BUILD_COMMAND ""
     INSTALL_COMMAND ""
```
