### ISSUE TITLE
Possible sign errors in CreatePointCloudFromRGBDImageT()

### ISSUE THREAD

**Issue by zachzeyuwang** [intel-isl/Open3D#3378]
In https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/geometry/PointCloudFactory.cpp#L121, `double z = (double)(*p);` should be `double z = -(double)(*p);`.
In https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/geometry/PointCloudFactory.cpp#L123, `double y = (i - principal_point.second) * z / focal_length.second;` should be `double y = -(i - principal_point.second) * z / focal_length.second;`.

This affects functions like `o3d.geometry.PointCloud.create_from_rgbd_image()` and `o3d.pipelines.integration.ScalableTSDFVolume.integrate()`.

I first noticed that the point clouds projected from multiple frames are not registered using `o3d.geometry.PointCloud.create_from_rgbd_image()` even though the recorded extrinsics were correct. Then I noticed `pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]]) # Flip it, otherwise the pointcloud will be upside down` at http://www.open3d.org/docs/latest/tutorial/Basic/rgbd_image.html, which doesn't make sense. After deriving some equations, I found that it should negate y and z before multiplying the pose matrix, not after.

A _temporary_ workaround is to negate the up and front directions in the pose matrix before feeding it to _current_ Open3D functions: `C[:3, 1] = -C[:3, 1]; C[:3, 2] = -C[:3, 2]`, then `volume.integrate(rgbd, o3d.camera.PinholeCameraIntrinsic(...), np.linalg.inv(C))`.

My data was recorded on an iPad Pro with LiDAR using Apple's ARKit. I don't think this issue is specific to ARKit data though. I'd like to post it here in case anyone has trouble creating registered point clouds.

**Comment by theNded** [comment]
No, this is the computer vision's conventional coordinate system.
    z
   ^ 
  /
 /
O --- > x
|
|
v
y

The flip function converts the point cloud from the CV convention to the CG convention so that y is pointing upward.
