### ISSUE TITLE
PyPi dynamic linking errors

### ISSUE THREAD

**Issue by nachovizzo** [intel-isl/Open3D#3388]
**Describe the bug**
Installation of `open3d` through pypi doesn't seem to work on isolated docker environments. Please see #2840 

## To Reproduce

I'm using the following `Docerfile`:
```docker
FROM ubuntu:20.04
RUN apt-get update && apt-get install --no-install-recommends -y python3-pip && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install --upgrade open3d
````
 1. `docker build -t test_open3d .` to build the container
 2. `docker run --rm test_open3d python3 -c "import open3d"` to test the installation

And I see 3 implicit dynamic dependencies:

## 1) OpenMP
```sh
docker run --rm test_open3d python3 -c "import open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/open3d/__init__.py", line 56, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgomp.so.1: cannot open shared object file: No such file or directory
```

This can be solved by adding an `apt install libgomp1` to the Dockerfile.

## 2) libusb

```sh
docker run --rm test_open3d python3 -c "import open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/open3d/__init__.py", line 56, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libusb-1.0.so.0: cannot open shared object file: No such file or directory
```
This can be solved by adding an `apt install libusb-1.0-0` to the Dockerfile.

## 3) OpenGL

```sh
docker run --rm test_open3d python3 -c "import open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/open3d/__init__.py", line 56, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so.1: cannot open shared object file: No such file or directory
```

This can be solved by adding an `apt install libgl1` to the Dockerfile.

## Summary and temporal solution

The final **minimal** `Dockerfile` that works on my case is:

```docker
FROM ubuntu:20.04
RUN apt-get update && apt-get install --no-install-recommends -y python3-pip && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install --upgrade open3d

RUN apt-get update && apt-get install --no-install-recommends -y \
    libgl1 \
    libgomp1 \
    libusb-1.0-0 \
    && rm -rf /var/lib/apt/lists/*
```

**Environment (please complete the following information):**

- Operating system:  Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: 0.12
- Is this remote workstation?: docker
- How did you install Open3D?: pip
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

**Additional context**
I think is important to remark that inside the container looks like `pip` is pulling the [latest wheel from pypi](https://pypi.org/project/open3d/#files):
```sh
Step 4/4 : RUN python3 -m pip install --upgrade open3d
 ---> Running in 1b71897301a0
Collecting open3d
  Downloading open3d-0.12.0-cp38-cp38-manylinux2014_x86_64.whl (188.5 MB)
```

**Comment by ssheorey** [comment]
Hi @nachovizzo The current Open3D wheel only supports Linux server / desktop installs where these packages are installed as part of the OS install. Including these in the wheel has the potential for conflicts with the OS libraries, especially if other Python packages also uses these libraries.

This is very useful information for docker users. We can add this skeleton docker file to the documentation for users. (`Open3D/docs/getting_started.rst.in`)

Would you like to make a PR for this?

**Comment by nachovizzo** [comment]
I understand and I also agree. What was confusing for me was #2840.

I will open a PR soon with the minimal docker setup
