### ISSUE TITLE
How to select points and get point coordinates use open3d.visualization.draw

### ISSUE THREAD

**Issue by TangToy** [intel-isl/Open3D#3398]
Thanks a lot. I have tried to use `open3d.visualization.draw()`, which can realize adjusting point sizes and line 
thicknesses. However,  when I used the _selection_ function and wanted to select the point and get the point coordinate,  the dialog show as this.
![2021-05-06 16-58-02 的屏幕截图](https://user-images.githubusercontent.com/45865043/117271946-44a1ac80-ae8d-11eb-8a07-5393a846b1c9.png)

 Can I select the points and get the coordinates as the function `o3d.visualization.draw_geometries_with_editing`? Thanks a lot.
> If you press "h" in the visualization window you can get a list of functionality available to you. You can use `=` and `/` to increase and decrease the point size, and `ctrl + =` and `ctrl + -` to change the line width. The old visualizer (`open3d.visualization.Visualizer` / `open3d.visualization.draw_geometries()`) does not support setting the point size and line widths programmatically. However, you can use the new visualizer (`open3d.visualization.O3DVisualizer` / `open3d.visualization.draw()`), which does support them. This feature is supported in 0.12, and you can find an example at [`examples/python/gui/line-width.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/line-width.py). See also [`examples/python/gui/draw.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py).

**Comment by prewettg** [comment]
It doesn't look like we support selecting points from lines at the moment, but if you also draw the points of the line as a PointCloud they should be selectable. It looks like you got something selected in the left, though (the purple circle). You can get the index, coordinates, and selection order of the points by querying the O3DVisualizer object that is what implements `draw()`. You can get the object when a custom action is performed. Please see example number four (`selections()`)[https://github.com/intel-isl/Open3D/blob/9e7e99cc972cda8bbee6739981566f718b22b16c/examples/python/gui/draw.py#L126] in `examples/python/gui/draw.py`.

**Comment by TangToy** [comment]
Thanks a lot.
> It doesn't look like we support selecting points from lines at the moment, but if you also draw the points of the line as a PointCloud they should be selectable. It looks like you got something selected in the left, though (the purple circle). You can get the index, coordinates, and selection order of the points by querying the O3DVisualizer object that is what implements `draw()`. You can get the object when a custom action is performed. Please see example number four [`selections()`](https://github.com/intel-isl/Open3D/blob/9e7e99cc972cda8bbee6739981566f718b22b16c/examples/python/gui/draw.py#L126) in `examples/python/gui/draw.py`.
