### ISSUE TITLE
0.13.0 Open3d Release

### ISSUE THREAD

**Issue by johnwlambert** [intel-isl/Open3D#3399]
Hi Open3d team, thanks for all your hard work. Would it be possible to create a new release with wheels that include all of the improvements/features from December to May?

It looks like there are about 250+ pull requests merged since the last release : - )

Would it be possible to push out releases at a more frequent cadence?

Thanks again.

**Comment by ssheorey** [comment]
We are almost finished with 0.13.0 :-) It will be released in a week or two.

**Comment by johnwlambert** [comment]
Very nice. Could you make sure #3338 makes it into 0.13.0? : - )

**Comment by theNded** [comment]
Yes, feature freeze would be hopefully tomorrow -- all the PRs before that will be included.

**Comment by johnwlambert** [comment]
Great -- thanks Wei

**Comment by johnwlambert** [comment]
Any word on the 0.13 release? : - )
