### ISSUE TITLE
make -j 4 clone open3d_ml error

### ISSUE THREAD

**Issue by zpw6106** [intel-isl/Open3D#3400]
When we compiled open3d from source using the make command, I encountered the following error:
正克隆到 'open3d_ml'...
fatal: '/home/zpw/third_party/Open3D-0.12.0/build/https:/github.com/intel-isl/Open3D-ML.git' does not appear to be a git repository
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
-- Had to git clone more than once:
          10 times.
CMake Error at /home/zpw/third_party/Open3D-0.12.0/build/open3d_ml/tmp/open3d_ml-gitclone.cmake:31 (message):
  Failed to clone repository:
  '/home/zpw/third_party/Open3D-0.12.0/build/https:/github.com/intel-isl/Open3D-ML.git'

I checked the source of the error, which is clone Open3d_ML. The command is as follows:
git clone --no-checkout "/home/zpw/third_party/Open3D-0.12.0/build/https:/github.com/intel-isl/Open3D-ML.git" "open3d_ml"

**Comment by sanskar107** [comment]
@zpw6106 If you are using `-DBUNDLE_OPEN3D_ML=ON` in your cmake flags, please clone Open3D-ML and run:
`source <Open3D-ML_PATH>/set_open3d_ml_root.sh`

Alternatively you can set `OPEN3D_ML_ROOT` env variable to your Open3D-ML path.

**Comment by zpw6106** [comment]
Thank you very much, I will try it soon.

**Comment by ajinkyakhoche** [comment]
I also get the same problem (with same output as OP). I tried the suggestions listed but they didn't seem to work. FYI, I'm using Python 3.8.3, Ubuntu 20.04 and CMake 3.18.1. @sanskar107

**Comment by zpw6106** [comment]
Please make sure your path is correct, I have solved this problem. You should specify the path of Open3D-ML in the cmake flag. like this:
`cmake -DOPEN3D_ML_ROOT=/home/zpw/third_party/Open3D-ML # Please replace the path with your Open3D-ML path. In fact, the path info will output in your terminal after your run  source <Open3D-ML_PATH>/set_open3d_ml_root.sh`
@ajinkyakhoche

**Comment by ajinkyakhoche** [comment]
Sorry for late reply @zpw6106 , I can confirm this works. Many thanks
