### ISSUE TITLE
GUI for visualization module

### ISSUE THREAD

**Issue by dhruveshg** [intel-isl/Open3D#342]
Is it possible to change size of point in point cloud?
I found API to set new camera intrinsic but could not find API to get user defined camera intrinsic?

**Comment by syncle** [comment]
> Is it possible to change size of point in point cloud?

Yes. Please refer http://open3d.org/docs/tutorial/Basic/pointcloud.html#visualize-point-cloud. You can press ``+`` or ``-`` to increase/decrease point cloud size.

> I found API to set new camera intrinsic but could not find API to get user defined camera intrinsic?

See http://open3d.org/docs/tutorial/Basic/rgbd_images/redwood.html. You can replace ``PinholeCameraIntrinsic.prime_sense_default`` with 3x3 numpy array.

Thanks for using Open3D. I recommend to go through 'basic' tutorial to be get familiar with the library quickly :)

**Comment by dhruveshg** [comment]
Thanks, this is helpful.

Can we instantiate the Open3D visualizer with different point size, Is there API to do so?
Also one more question, can we rotate over Z Axis (like Ctrl+Mouse Drag in PCL)?

**Comment by dhruveshg** [comment]
Oops sorry did not realize qianyizh had already replied instantiating visualizer from json file.

**Comment by syncle** [comment]
> Also one more question, can we rotate over Z Axis (like Ctrl+Mouse Drag in PCL)?

I don't think we have Z-axis rotation. (@qianyizh can you correct me if I am wrong?). This request can be go for next milestone.

**Comment by qianyizh** [comment]
There is. Call ``draw_geometries_with_editing()``, it will launch a ``py3d.VisualizerWithEditing``. Then you can press ``X``, ``Y``, or ``Z`` to lock the rotation around a certain axis, under an orthogonal view. Key ``F`` releases the view to free view.

**Comment by cysmith** [comment]
@qianyizh @syncle It might be useful to have sliders for the intrinsic matrix like the **Demo** section here:
http://ksimek.github.io/2013/08/13/intrinsic/

**Comment by syncle** [comment]
Oh, I somehow missed this valuable comment by @cysmith. This demo is really great. It is written in java script, so it might be good to find out the way to add UI in our visualizer. I've thinking about https://github.com/wjakob/nanogui for this. How do you think @qianyizh?

**Comment by qianyizh** [comment]
Nanogui looks pretty good.

**Comment by WillEEEEEE** [comment]
hope that opend3d can have an GUI, or can be integrated with other GUIs to help programmers achieve large projects.

**Comment by WillEEEEEE** [comment]
Nanogui looks beautiful and powerful~

**Comment by germanros1987** [comment]
The GUI is around the corner...so I am closing this issue.
