### ISSUE TITLE
AttributeError: 'open3d.cpu.pybind.geometry.PointCloud' object has no attribute 'select_down_sample'

### ISSUE THREAD

**Issue by mcmingchang** [intel-isl/Open3D#3420]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
This error occurs when I run the examples/Python/Basic/pointcloud_plane_segmentation.py

**To Reproduce**

1. cd '...'
2. python '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
- Python version: (e.g. Python 3.6)
- Open3D version:
- Is this remote workstation?: yes or no
- How did you install Open3D?: (e.g. pip, conda, build from source)
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

**Additional context**

**Comment by theNded** [comment]
Your repo is out of date. Please refer to this tutorial: https://github.com/intel-isl/Open3D/blob/master/examples/python/geometry/pointcloud.ipynb. The function has been renamed to `select_by_index`.

**Comment by gabriead** [comment]
Could you update the examples in the official open3d documentation? That would be awesome!

**Comment by ryo-matsuzaka** [comment]
@theNded 
Hello, the site (https://github.com/intel-isl/Open3D/blob/master/examples/python/geometry/pointcloud.ipynb) is 404.
Can you share the link again?

**Comment by Irfan-S** [comment]
The crop function seems to be moved to this `pcd.crop(bounding_box)`.

PCD here refers to the PCD object loaded into your file via `open3d.io.read_point_cloud`

You can define a bounding box that is axis-aligned, or one that is oriented that wraps your area of interest via `o3d.geometry.AxisAlignedBoundingBox(min_bound=min_bound, max_bound=max_bound)` or `o3d.geometry.OrientedBoundingBox(center=center, extent=extent)`
