### ISSUE TITLE
An bug with example with Realsense

### ISSUE THREAD

**Issue by JimXu1989** [intel-isl/Open3D#3428]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When I run python run_system.py --make --register --refine --integrate config/realsense.json, as show in the document: 
http://www.open3d.org/docs/release/tutorial/sensor/realsense.html#

**To Reproduce**
1. cd examples/python/reconstruction_system/
2. python run_system.py --make --register --refine --integrate config/realsense.json

I just give the L515_test.bag file path in the json file, as the path_dataset
{
    "name": "Realsense bag file",
    "path_dataset": "datasets/L515_test/realsense.bag",
    "max_depth": 3.0,
    "voxel_size": 0.05,
    "max_depth_diff": 0.07,
    "preference_loop_closure_odometry": 0.1,
    "preference_loop_closure_registration": 5.0,
    "tsdf_cubic_size": 3.0,
    "icp_method": "color",
    "global_registration": "ransac",
    "python_multi_threading": true
}

**Expected behavior**
register the 3D information

**Screenshots**

![2021-05-12 10-06-28 的屏幕截图](https://user-images.githubusercontent.com/7732706/117907818-05021700-b30a-11eb-9e88-123cc1eaf8a6.png)
![2021-05-12 10-07-48 的屏幕截图](https://user-images.githubusercontent.com/7732706/117907825-07fd0780-b30a-11eb-92c8-2f4d11157765.png)

**Environment (please complete the following information):**

- Operating system: ubuntu 20.04
- Python version: 3.8
- Open3D version: 0.12
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**
L515_JackJack cannot be download after a long time, by "python3 download_dataset.py L515_JackJack"

**Comment by theNded** [comment]
This is not a bug. Since you failed to download the bag file, it is not decoded and fed to the system. The error message could be improved though. 
Please try to download the dataset with a network that has access to google. (https://storage.googleapis.com/isl-datasets/open3d-dev/realsense/L515_JackJack.bag)

**Comment by JimXu1989** [comment]
> This is not a bug. Since you failed to download the bag file, it is not decoded and fed to the system. The error message could be improved though.
> Please try to download the dataset with a network that has access to google. (https://storage.googleapis.com/isl-datasets/open3d-dev/realsense/L515_JackJack.bag)
How about the bug I report above?
