### ISSUE TITLE
I met an Error when I use the python example with realsense data

### ISSUE THREAD

**Issue by JimXu1989** [intel-isl/Open3D#3429]
Describe the bug
When I run python run_system.py --make --register --refine --integrate config/realsense.json, as show in the document:
http://www.open3d.org/docs/release/tutorial/sensor/realsense.html#

To Reproduce

cd examples/python/reconstruction_system/
python run_system.py --make --register --refine --integrate config/realsense.json
I just give the L515_test.bag file path in the json file, as the path_dataset
{
"name": "Realsense bag file",
"path_dataset": "datasets/L515_test/realsense.bag",
"max_depth": 3.0,
"voxel_size": 0.05,
"max_depth_diff": 0.07,
"preference_loop_closure_odometry": 0.1,
"preference_loop_closure_registration": 5.0,
"tsdf_cubic_size": 3.0,
"icp_method": "color",
"global_registration": "ransac",
"python_multi_threading": true
}

Expected behavior
register the 3D information

Screenshots

![2021-05-12 10-07-48 的屏幕截图](https://user-images.githubusercontent.com/7732706/117914171-5bc11e00-b315-11eb-985a-feab4d17fd61.png)
![2021-05-12 10-06-28 的屏幕截图](https://user-images.githubusercontent.com/7732706/117914180-5ebc0e80-b315-11eb-8b43-46574d110dd6.png)

Environment (please complete the following information):

Operating system: ubuntu 20.04
Python version: 3.8
Open3D version: 0.12
Is this remote workstation?: no
How did you install Open3D?: pip

**Comment by ssheorey** [comment]
Hi @JimXu1989 Please check that the `path_dataset` is correct. Can you open and read the RSbag file at that path?

**Comment by JimXu1989** [comment]
> Hi @JimXu1989 Please check that the `path_dataset` is correct. Can you open and read the RSbag file at that path?
Thanks a lot for your reply!
realsense.bag is a file which stores the 3D information, while in the code, the code seems to take the name of .bag file as a folder path, and I can not find any lines of code try to extract 3d information from the .bag file.
Thanks a lot!!

**Comment by ssheorey** [comment]
Hi @JimXu1989 please re-open the issue if you are still having problems.
The code to extract frames from the bag file is here:
https://github.com/intel-isl/Open3D/blob/f9ef634dcb71b17036633baf1323fdbd344c24e1/examples/python/utility/file.py#L112

its called from here:
https://github.com/intel-isl/Open3D/blob/f9ef634dcb71b17036633baf1323fdbd344c24e1/examples/python/reconstruction_system/initialize_config.py#L77
