### ISSUE TITLE
passFilter

### ISSUE THREAD

**Issue by mingyangpeng** [intel-isl/Open3D#3437]
**Is your feature request related to a problem? Please describe.**
I need a Point Cloud Filtering  function.

**Describe the solution you'd like**
a filter function just like PCL pcl::PassThrough. 
 
**Additional context**
Sometimes, I need to intercept the point cloud within a specified coordinate axis,but I didn't find the operation.

**Comment by sanskar107** [comment]
@mingyangpeng you can create an `AxisAlignedBoundingBox` with your dimension range and call `PointCloud::Crop`.
http://www.open3d.org/docs/release/python_api/open3d.geometry.AxisAlignedBoundingBox.html

**Comment by mingyangpeng** [comment]
I'm sorry to get back to you so late. Thank you for your help！
