### ISSUE TITLE
No device detected realsense l515

### ISSUE THREAD

**Issue by YoniChechik** [intel-isl/Open3D#3442]
**Describe the bug**
Realsense L515 is connected (I can view the results in realsense viewer) but isn't detected via open3d (tested on multiple usb ports).

**To Reproduce**
```
import open3d as o3d
print(o3d.t.io.RealSenseSensor.list_devices())
```
Results:
```
[Open3D WARNING] No RealSense devices detected.
False
```

**Environment:**

- Operating system:Windows 10 64-bit
- Python version: python 3.8
- Open3D version: 0.12
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by ssheorey** [comment]
@YoniChechik Please try with the latest development Python wheel from here:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip
and let us know if you still have this issue.

**Comment by YoniChechik** [comment]
Works :)
Used your code snippet with L515 connected:
```

import open3d as o3d

if __name__ == "__main__":

    o3d.t.io.RealSenseSensor.list_devices()
    rscam = o3d.t.io.RealSenseSensor()
    rscam.start_capture()
    print(rscam.get_metadata())
    for fid in range(5):
        rgbd_frame = rscam.capture_frame()
        o3d.io.write_image(f"color{fid:05d}.jpg",
                           rgbd_frame.color.to_legacy_image())
        o3d.io.write_image(f"depth{fid:05d}.png",
                           rgbd_frame.depth.to_legacy_image())
        print("Frame: {}, time: {}s".format(fid, rscam.get_timestamp() * 1e-6))

    rscam.stop_capture()
```
