### ISSUE TITLE
float16 support for binary PLY

### ISSUE THREAD

**Issue by johnwlambert** [intel-isl/Open3D#3444]
Is there support for float16 values in binary PLY files? I couldn't find it in the docs. Would be quite useful.

Thanks.

**Comment by ssheorey** [comment]
`float16` isn't a standard C++ data type, so it's not supported. Is the use case for data compression?

**Comment by johnwlambert** [comment]
I see, perhaps it does not make sense then for Open3d. Indeed, my use case is for data compression. Pytorch might be using this for c++ support: https://github.com/Maratyszcza/FP16/tree/4dfe081cf6bcd15db339cf2680b9281b8451eeb3

**Comment by ssheorey** [comment]
Take a look at [Google Draco](https://github.com/google/draco)  for compression of ply files.
