### ISSUE TITLE
`with_normals` missing in `create_from_depth_image`

### ISSUE THREAD

**Issue by tetterl** [intel-isl/Open3D#3445]
Python bindings of `create_from_depth_image` are missing the argument `with_normals`.

**Comment by ssheorey** [comment]
Hi @tetterl `with_normals` is only supported in the new Tensor API:
http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.PointCloud.html#open3d.t.geometry.PointCloud.create_from_depth_image
