### ISSUE TITLE
Fast global registration vs TEASER++

### ISSUE THREAD

**Issue by Apeiria** [intel-isl/Open3D#3453]
I'm using fast global registration to register point clouds, and it sometimes produces bad results. Has anybody tried benchmarking Fast global registration vs TEASER++? Is TEASER++ more robust?

I saw a feature request for adding TEASER++, what is the progress?

Thanks.

**Comment by theNded** [comment]
> I'm using fast global registration to register point clouds, and it sometimes produces bad results. Has anybody tried benchmarking Fast global registration vs TEASER++? Is TEASER++ more robust?

TEASER++'s paper includes a comprehensive comparison to FGR. In practice, TEASER++ could be more robust, but both are still sensitive to putative correspondences. 

> I saw a feature request for adding TEASER++, what is the progress?

TEASER++ has a python interface that can be directly used along with Open3D, so at current we don't have a clear roadmap to merge it.

**Comment by Apeiria** [comment]
> > I'm using fast global registration to register point clouds, and it sometimes produces bad results. Has anybody tried benchmarking Fast global registration vs TEASER++? Is TEASER++ more robust?
> 
> TEASER++'s paper includes a comprehensive comparison to FGR. In practice, TEASER++ could be more robust, but both are still sensitive to putative correspondences.
> 
> > I saw a feature request for adding TEASER++, what is the progress?
> 
> TEASER++ has a python interface that can be directly used along with Open3D, so at current we don't have a clear roadmap to merge it.

Thank you for your reply!
