### ISSUE TITLE
Error in reconstruction system ()

### ISSUE THREAD

**Issue by ridanlukita** [intel-isl/Open3D#3454]
I'm new to this library and currently try to make reconstruction system using Intel D435i with Open3D after reading through the documentation about it, although the documentation were pretty clear, I got some issues when I try the library using conda.

**Describe the bug**
I had similar error like #2948 where in the `examples/python/reconstruction_system` will show the error below if I apply `python run_system.py config/tutorial.json --register` on Visual Studio powershell or Anaconda Prompt:
```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.cpu.pybind.pipelines.registration.RANSACConvergenceCriteria(arg0: open3d.cpu.pybind.pipelines.registration.RANSACConvergenceCriteria)
    2. open3d.cpu.pybind.pipelines.registration.RANSACConvergenceCriteria(max_iteration: int = 1000, max_validation: int = 1000)

Invoked with: 1000000, 0.999
```

In the #2948 he mentioned that's the version used was Open3D v0.11.2 then it solved because he updated to v0.12.0 (don't know if he's updating via pip or conda)

However, when I try `conda install -c open3d-admin open3d` in the Anaconda Prompt(64-bit) and check the version installed, it shows that my package was installed using v0.11.2 (not v0.12.0 as it should be)

Then I try `conda install -c open3d-admin open3d=0.12.0` but it shows like this:
```
(base) C:\Users\Administrator>conda install -c open3d-admin open3d=0.12.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__archspec==1=x86_64:  60%|█████████████████████████▏                | 3/5 [00:00<00:00, 42.37it/s]/failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**To Reproduce**
Similar with #2948 
1. cd 'the path to reconstruction_system'
2. `run_system.py config/tutorial.json --register`
    The dataset used was [016](https://drive.google.com/file/d/11U8jEDYKvB5lXsK3L1rQcGTjp0YmRrzT/view) as introduced in the document.
3. See error
    - When I try to `--register`:
    ```
    TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.cpu.pybind.pipelines.registration.RANSACConvergenceCriteria(arg0: open3d.cpu.pybind.pipelines.registration.RANSACConvergenceCriteria)
    2. open3d.cpu.pybind.pipelines.registration.RANSACConvergenceCriteria(max_iteration: int = 1000, max_validation: int = 1000)

    Invoked with: 1000000, 0.999
    ```

    - When I try to update the library:
    ```
    (base) C:\Users\Administrator>conda install -c open3d-admin open3d=0.12.0
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: |
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.
    Examining @/win-64::__archspec==1=x86_64:  60%|█████████████████████████▏                | 3/5 [00:00<00:00, 42.37it/s]/failed

    UnsatisfiableError: The following specifications were found to be incompatible with each other:

    Output in format: Requested package -> Available versions
    ```

**Expected behavior**
- The `python run_system.py config/tutorial.json --register` expected to show the [Results](http://www.open3d.org/docs/release/tutorial/reconstruction_system/register_fragments.html#results) as in the document.
- The library expected to be installed with version 0.12.0 using conda

**Screenshots**
![Screenshot 2021-05-16 223520_LI](https://user-images.githubusercontent.com/26058697/118496247-25890180-b74e-11eb-9066-c4331a15b4ad.jpg)

**Environment:**
- Operating system: Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: 0.11.2
- Is this remote workstation?: no
- How did you install Open3D?: conda

**Additional context**
Does the library on the Anaconda has already been updated to v0.12.0 or still in v0.11.2?
Because in my opinion, the error on `--register` were caused by library that still in v0.11.2 (like issues on #2948) that should be using v0.12.0 (which catch an error while using conda package)

Do you have any suggestions?

**Comment by ssheorey** [comment]
HI @ridanlukita please remove the conda Open3D and re-install `v0.12` with `pip` inside your conda virtual environment. We are deprecating `conda` packages. Let us know if that fixes this issue for you.

**Comment by ridanlukita** [comment]
Thank you @ssheorey ! after installing with `pip` now I can get through it. The issues now has been fixed.

**Comment by lkrmbhlz** [comment]
Thank you so much @ssheorey! I ran into the same problem 5 hours after @ridanlukita opened the issue, helped me a lot 🙂
