### ISSUE TITLE
Generate vertex colors

### ISSUE THREAD

**Issue by mxf8bv** [intel-isl/Open3D#3455]
Hi,

I want to use registration_colored_icp as a replacement for standard ICP.
For this, I obviously need vertex colors.

I have reference mesh files with textured surfaces and I can load them and transfer into a PointCloud using the mesh.vertex_color field. Unfortunately, my model files don't have colored vertices set, so the result is uniformly colored and not useful.

Question: How can I assign vertex colors from textures? E.g., using the mean color of adjacent textured faces?
In Meshlab, for example, there is a filter to do this: Filter->Texture->Transfer:TextureToVertexColor. This works but I need to do this programatically for many models in o3d.

BTW, I found that using python and o3d 0.10, 0.11, and 0.12 crashes with a segfault and no error message when calling registration_colored_icp with PointClouds that don't have colors (has_colors()==False). 

Thx!
   Mathias

**Comment by reyanshsolis** [comment]
Hi @mxf8bv, thanks for reporting the bug, PR #3466 may fix it. 
Regarding the requested feature, I may try to add the same in a future PR. 

Thanks,
Rishabh

**Comment by mxf8bv** [comment]
Hi Rishabh,

thanks for the answer!
Looking forward for such a feature!

Is there any documentation on how o3d performs the UV mapping of the texture onto the geometry so that I could hack something in the meantime?

Best,
   Mathias
