### ISSUE TITLE
M1 Mac build from source - Open3D/cpp/open3d/core/hashmap/Dispatch.h error

### ISSUE THREAD

**Issue by Mostafathereal** [intel-isl/Open3D#3462]
In file included from Open3D/cpp/open3d/core/hashmap/CPU/CreateCPUHashmap.cpp:28:
Open3D/cpp/open3d/core/hashmap/Dispatch.h:85:29: error: definition of implicit copy constructor for 'Block<long long, 3>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
    `void OPEN3D_HOST_DEVICE operator=(const Block<T, N>& other) {`
_____

Error when building from source on M1 mac natively

**To Reproduce**

1. `git clone --recursive https://github.com/intel-isl/Open3D`
2. Following these steps https://github.com/intel-isl/Open3D/issues/2675#issuecomment-778681068 , @turtlesoupy 
3. See error after the `make install-pip-package -j8` command

**Screenshots**

<img width="1193" alt="Screen Shot 2021-05-18 at 10 51 49 AM" src="https://user-images.githubusercontent.com/29662854/118673558-198d5600-b7c7-11eb-8475-4401d81ae68e.png">

And this is where the error is occurring (line 85)
<img width="762" alt="Screen Shot 2021-05-18 at 2 34 45 PM" src="https://user-images.githubusercontent.com/29662854/118705430-384f1500-b7e6-11eb-8366-4c6282690585.png">

**Environment**

- Operating system: Big Sur 11.2.3
- Python version: Python 3.9.4 - conda env
- Open3D version: 0.12.0
- Compiler version (if built from source): Apple clang version 12.0.5 (clang-1205.0.22.9) Target: arm64-apple-darwin20.3.0
- CMake version: 3.20.2
- conda 4.10.1

Thanks!!

**Comment by Mostafathereal** [comment]
Update: Same error when also building from source in a rosetta terminal ...

**Comment by stotko** [comment]
Thanks for testing Open3D on Apple Silicon. I was able to reproduce your issue with Clang 11 on Ubuntu 20.04 and submitted a fix in #3470.

**Comment by Mostafathereal** [comment]
Thanks!
