### ISSUE TITLE
Additional examples on how to use KNNSearch on batches

### ISSUE THREAD

**Issue by saltoricristiano** [intel-isl/Open3D#3478]
**Additional examples on how house KNNSearch on batches**
_____

**Describe the bug**
Unclear documentation on how to provide point_row_splits and queries_row_splits for batch based KNNSearch.

**Environment (please complete the following information):**

- Operating system: Ubuntu18.04
- Python version: Python 3.6
- Open3D version: 0.11.2
- Is this remote workstation?: yes
- How did you install Open3D?: pip
- Running on Docker

**Additional context**
Docs report: Optional 1D vector with the row splits information if points/query is batched. This vector is [0, num_points] if there is only 1 batch item. What does it mean? Supposing points of shape [batch_size, num_points, 3] and queries of shape [batch_size, num_queries, 3]. How should be provided *_row_splits? Should it be [batch_size, num_points] or a vector of shape [batch_size, num_points] with batch indexes along axis 1?
Thanks in advance!

**Comment by sanskar107** [comment]
@saltoricristiano we support more generic batching where you can have different batch sizes. We pass points/queries in with shape `[N, 3]`. `row_splits` define how we should break this pointcloud in different batches.
For e.g., if you have points with 3 batches, where each batch has 3, 2, 5 number of points respectively. The `row_split` would look something like `[0, 3, 5, 10]`

For your use case(where you have same batch length), you have to reshape your points/queries to `[B*num_points, 3]` and pass your splits as `[0, B, 2B, 3B...]`

Similarly, if you have only 1 batch, then your split would become `[0, num_points]`

**Comment by saltoricristiano** [comment]
Hi @sanskar107, 

just solved and I was going to close the issue. I know it's super easy, but it may be clearer to better explain in the docs.
Thanks in advance for your help!
