### ISSUE TITLE
Is there a way to disable GPU memory allocation upon import?

### ISSUE THREAD

**Issue by ljj7975** [intel-isl/Open3D#3483]
Thank you for the great tool,
I have found some suspicious behavior with open3d so I would like to ask a question

I am using open3d v 0.11.2 installed through pip

when I have a single GPU, `import open3d as o3d` does not allocate any GPU memory.

However, when there are multiple GPU's available (tested on 2),
it allocates some GPU memory 
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     18101      C   python      189MiB |
|    1   N/A  N/A     18101      C   python      189MiB 
```

I have to create multiple processes and it seems like this behavior is happening for each of the processors taking up some portion of GPU.

I am find not using GPU at all for open3d.
However, I will still need GPU for the other part of the code so touching VISIBLE_CUDA_DEVICES won't be an option

Any explanation on why this is the case and is there any way to disable this behavior?
Thanks

**Comment by yxlao** [comment]
`0.11` is an old version. Please try the latest Open3D `0.13`. In my test, there are no memory allocations on CUDA by just `import open3d` where there are two cards in the system.

**Comment by xiangruhuang** [comment]
I installed Open3D `0.13` via pip.
Running `import open3d` on a python terminal ends up with gpu memory allocation (about 400M) on all gpus (8 in my case).

For the record, I'm using python 3.8 and cuda 11.0.
Also, downgrading to `0.12` does not help.

Please consider re-open this issue.

**Comment by liyujiejiejie** [comment]
i have the same problem , open3d used about 388M memory

**Comment by crypto-g245** [comment]
I am using open3d v 0.13 installed through pip and would like to disable GPU usage . 
is there any update on this topic ?
