### ISSUE TITLE
Use one VoxelGrid to carve out an empty space from another VoxelGrid

### ISSUE THREAD

**Issue by kjans123** [intel-isl/Open3D#3484]
I have two VoxelGrids composed of many voxels. One is smaller than the other and I would like to use the smaller voxel grid to create an open cavity inside the other, larger voxel grid. Is there a way to do this in Open3D?

**Comment by mattj23** [comment]
There is no built-in feature as far as I can tell, but it should be straightforward to implement.

If you're working in C++ the voxel objects are stored in a `std::unordered_map` and you can use the `erase(...)` method to remove a voxel from it.  In that case as long as the grids have the same origin, rotation, and voxel size you can iterate through the voxels of the smaller grid and `erase` any voxel in the larger grid with that same index.  

If you're in python, it doesn't look like you'll be able to mutate the container directly, nor was the `AddVoxel` method exposed through pybind.  We were talking about this in the Discord the other day.  The best workaround I can think of is to create an empty `open3d.geometry.PointCloud` and iterate through the larger voxel grid, adding any voxel that isn't in the smaller voxel to the point cloud as a single point at the voxel center, then converting that `PointCloud` to a `VoxelGrid` using the same parameters as the original grid.
