### ISSUE TITLE
vis.get_view_control() throw an error [Open3D ERROR] GLFW Error: The GLFW library is not initialized

### ISSUE THREAD

**Issue by wzm2256** [intel-isl/Open3D#3489]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
vis.get_view_control() throw an error when run twice.

**To Reproduce**
```
import open3d as o3d
import numpy as np

a = np.random.randn(100,3) 

PC = o3d.geometry.PointCloud()
PC.points = o3d.utility.Vector3dVector(a)

vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(PC)
ctr = vis.get_view_control()  # Everything good
vis.run()
vis.close()

vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(PC)
ctr = vis.get_view_control()  # ERROR: [Open3D ERROR] GLFW Error: The GLFW library is not initialized
vis.run() 

```

**Expected behavior**
There should not be any error.

**Screenshots**

**Environment (please complete the following information):**

- Operating system: windows 10
- Python version:  Python 3.6 
- Open3D version:  0.10.0.1
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by ssheorey** [comment]
Hi @wzm2256 you are using an old version of Open3D.
Please try with the latest development Python wheel from here:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip
and let us know if you still have this issue.

**Comment by wzm2256** [comment]
The issue persisits.
```
# packages in environment at E:\Program\Anaconda3\envs\open3d_test:
#
# Name                    Version                   Build  Channel
certifi                   2020.12.5        py36haa95532_0    defaults
pip                       21.1.1           py36haa95532_0    defaults
python                    3.6.13               h3758d61_0    defaults
setuptools                52.0.0           py36haa95532_0    defaults
sqlite                    3.35.4               h2bbff1b_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
```

In python terminal
```
 import open3d
 open3d.__version__
'0.12.0+ff11ad2'
```

**Comment by RPFey** [comment]
I have the same issue. My situation is that I create a Visualizer inside a GUI Button callback function. When I close the visualizer, it throws the same error

**Comment by wzm2256** [comment]
For anyone who see this, my work around is to seal each visualization code into a seperate function:
```
def vis_PC(PC):
  vis = o3d.visualization.Visualizer()
  vis.create_window()
  vis.add_geometry(PC)
  ctr = vis.get_view_control()  # Everything good
  vis.run()
```
Currently there seems to be a lot of low level bugs in open3d (see the unsolved issues in github). My personal suggestions for the developer are to focus on fixing bugs, re-writing the doc and tutorial, perhaps refractoring the code and releasing a stable version, instead of adding more and more fancy functions, which should only be considered after the stable version.
Nevertheless, I'm thankful to the developers for providing this wonderful tool.
