### ISSUE TITLE
Can't install open3d on macOS with pip

### ISSUE THREAD

**Issue by agurtovoy** [intel-isl/Open3D#3499]
**Describe the bug**

Getting `No matching distribution found for open3d` when trying to install with `pip` on macOS Big Sur.

**To Reproduce**

1. `python -m pip install open3d`
2. Get 
```
ERROR: Could not find a version that satisfies the requirement open3d (from versions: none)
ERROR: No matching distribution found for open3d
```

**Expected behavior**

open3d is installed successfully :)

**Environment (please complete the following information):**

- Operating system: OSX 11.4
- Python version: 3.7.10
- Open3D version: n/a
- Is this remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): n/a

**Comment by ssheorey** [comment]
Is this on Apple Silicon (M1)? We don't have an official build for it yet.

**Comment by agurtovoy** [comment]
@ssheorey Nope, this is on Intel Core i9, 2019 MacBook Pro.

**Comment by ssheorey** [comment]
Please upgrade your `pip` and try again. `python -m pip install -U pip`

**Comment by ssheorey** [comment]
Upon looking into this a bit more, this looks like a packaging issue due to macOS version change. Can you test this workaround for `scipy` with `open3d` and let us know if it works?

https://github.com/scipy/scipy/issues/13102#issuecomment-788160041

**Comment by jselikof** [comment]
@ssheorey with Big Sur 11.4 scipy installs fine without setting SYSTEM_VERSION_COMPAT.  Open3D install continues to return "No matching distribution found" with or without SYSTEM_VERSION_COMPAT.

**Comment by ssheorey** [comment]
@jselikof Please list your system configuration (similar to the original bug report). Also include your processor architecture and pip version.

**Comment by jselikof** [comment]
macOS Big Sur
version 11.4
2.6 GHz 6-Core Intel Core i7
Virtual environment created with virtualenv -p python3 ~/ransac
Python 3.9.5
pip 21.1.2 from ~/ransac/lib/python3.9/site-packages/pip (python 3.9)

Let me know if you need anything else, thanks!

**Comment by ssheorey** [comment]
@jselikof We don't have a Python 3.9 wheel yet. Can you check on Python 3.6, 3.7 or 3.8?

**Comment by jselikof** [comment]
Yep, I will give that a try.

**Comment by jselikof** [comment]
Seems to have Installed successfully with 3.8.10, but the ml_ops test referenced above fails with:

================================================================================= ERRORS =================================================================================
_____________________________________________________________________ ERROR collecting test session ______________________________________________________________________
Open3D/3rdparty/pybind11/tests/conftest.py:237: in _test_import_pybind11
    import pybind11_tests  # noqa: F401 imported but unused
E   ModuleNotFoundError: No module named 'pybind11_tests'

During handling of the above exception, another exception occurred:
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
../open3d-ve/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
Open3D/3rdparty/pybind11/tests/conftest.py:244: in <module>
    _test_import_pybind11()
Open3D/3rdparty/pybind11/tests/conftest.py:241: in _test_import_pybind11
    sys.exit(1)
E   SystemExit: 1
======================================================================== short test summary info =========================================================================
ERROR  - SystemExit: 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 1 error in 3.38s ============================================================================

**Comment by ssheorey** [comment]
@jselikof Thanks for testing. I've updated the test command line -- it was missing the folder containing the tests. Please try the updated test command.

**Comment by jselikof** [comment]
It's failing all tests like this:

**Comment by ssheorey** [comment]
This doesn't look like the right Open3D package. How did you install it?
Please uninstall it (`pip uninstall open3d`) and then install the latest dev package with directions from here:

http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

[You can simply do `pip install open3d` as well. This will get you the latest release v0.12 and then you should test this with the v0.12 tag of the cloned repo, not the latest master]

**Comment by jselikof** [comment]
It's all good with 0.13.0:
395 passed, 3 skipped in 44.05s

Thanks very much for all your help!
