### ISSUE TITLE
When will open3d 0.13 be released?

### ISSUE THREAD

**Issue by luoxiaoliaolan** [intel-isl/Open3D#3519]
Hi： 
     When I ran open3d-ml, I found that the version had been updated to 0.13.0, but the open3d I installed was still version 0.12.0, which caused some dependency errors, so I would like to ask, when will open3D version 0.13.0 be released?

**Comment by sanskar107** [comment]
@luoxiaoliaolan It will be released within a couple of days.

**Comment by nitinkapgate** [comment]
Hey @sanskar107 when can we expect a stable puublc release, say v1.0? Could you share the release roadmap? Thanks

**Comment by ssheorey** [comment]
Closing as v0.13 is released. 

@nitinkapgate we are rapidly adding and updating features in Open3D, so v1.0 is still some way off. Some of the existing functionality is being deprecated as we replace it with more efficient or general functionality. What is your use case?
