### ISSUE TITLE
How to get the camera parameter of Realsense D400?

### ISSUE THREAD

**Issue by JimXu1989** [intel-isl/Open3D#3526]
Hi, I want to use RGBD imgs captured by realsense d400 sensor, to make 3D points cloud.
As the example, 
o3d.camera.PinholeCameraIntrinsic(le
        o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault))
While, the parameter I can not just take and use.

Thanks a lot!

**Comment by ssheorey** [comment]
You are looking for this function: 

http://www.open3d.org/docs/latest/python_api/open3d.t.io.RealSenseSensor.html#open3d.t.io.RealSenseSensor.get_metadata

**Comment by JimXu1989** [comment]
> You are looking for this function:
> 
> http://www.open3d.org/docs/latest/python_api/open3d.t.io.RealSenseSensor.html#open3d.t.io.RealSenseSensor.get_metadata

Thanks a lot, and could you give me an example?

**Comment by ssheorey** [comment]
For getting metadata from a live camera, see here:

https://github.com/intel-isl/Open3D/blob/c3f9de224e13838a72da0e5565a7ba51038b0f11/examples/python/gui/online-processing.py#L100

For reading metadata from recorded bag files, see here:

https://github.com/intel-isl/Open3D/blob/c3f9de224e13838a72da0e5565a7ba51038b0f11/python/test/t/io/test_realsense.py#L53

The returned metadata has these fields (including intrinsics):

http://www.open3d.org/docs/latest/python_api/open3d.t.io.RGBDVideoMetadata.html
