### ISSUE TITLE
free(): invalid pointer Aborted (core dumped) when reconstruction from realsense bag file

### ISSUE THREAD

**Issue by Jonapple** [intel-isl/Open3D#3534]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When I tried to use the reconstruction system as guided in http://www.open3d.org/docs/release/tutorial/sensor/realsense.html
I got following error:
Extracting frames from RGBD video file
free(): invalid pointer
Aborted (core dumped)

**To Reproduce**
1. In examples/python/reconstruction_system/config, I copy a new realsense.json named SR300realsense.json, and modify the  "path_dataset" to the path to my bag file:
2. I tried to leave the "path_intrinsic" to be empty, but I also created another camera_primesense.json following the same structure to create an intrinsic file for my realsense camera
3. python run_system.py --make --register --refine --integrate config/SR300realsense.json in terminal
4. received an error as described above

(If I run the reconstruct in the default way, set a path to my folder which contains aligned image and depth, and path to intrinsic as guided in http://www.open3d.org/docs/release/tutorial/reconstruction_system/system_overview.html, everything works fine)

**Expected behavior**
Reconstruct as expected

**Screenshots**
![Screenshot from 2021-06-03 15-24-35](https://user-images.githubusercontent.com/80305575/120594313-ebbf3700-c47f-11eb-9173-8454d27bce85.png)
![Screenshot from 2021-06-03 15-24-49](https://user-images.githubusercontent.com/80305575/120594323-ef52be00-c47f-11eb-8846-1b80760ad946.png)
![Screenshot from 2021-06-03 15-25-12](https://user-images.githubusercontent.com/80305575/120594329-f083eb00-c47f-11eb-9499-a163b97526c8.png)

**Environment**

- Operating system: Ubuntu 20.04
- Python version: Python 3.8.5
- Open3D version: 
- Is this remote workstation?: no
- How did I install Open3D: pip

**Additional context**
I download the whole open3D code from https://github.com/intel-isl/Open3D, and directly put it into my pycharm project. I already have open3d, pyrealsense2 installed in my pycharm project

**Comment by theNded** [comment]
The reconstruction system only supports extracted images at current. @ssheorey we can think about including an upgrade in the next sprint.

**Comment by ssheorey** [comment]
This is supported. @Jonapple this issue has been fixed. Please test with Open3D **v0.13.**

**Comment by Jonapple** [comment]
> This is supported. @Jonapple this issue has been fixed. Please test with Open3D **v0.13.**

Thanks, problems solved :)
