### ISSUE TITLE
Can it will support the texture image?

### ISSUE THREAD

**Issue by guofengw** [intel-isl/Open3D#3537]
Hi guys，

Open3D supports color map optimization, but it only generates the object model with very colored vertex. 

Can open3d generate the texture image for 3d object model? Then using texture mapping to color the model.

Thanks.

**Comment by theNded** [comment]
This is still an open research topic and we don't have a roadmap towards the topic (though, personally I'm very interested). A relevant publication is https://www.cs.princeton.edu/courses/archive/fall16/cos526/papers/jeon16.pdf
