### ISSUE TITLE
How can i write two point clouds into one pcd file?

### ISSUE THREAD

**Issue by arkerman** [intel-isl/Open3D#3552]
How can i write two point clouds into one pcd file by using the function of "open3d.io.write_point_cloud( )"?
Maybe there are other functions？

**Comment by theNded** [comment]
Add them using operator += in C++ or append one to the other in python, then write.
What is the use case? Why not write two?

**Comment by hduonggithub** [comment]
pcd = pcd1 + pcd2
open3d.io.write_point_cloud(pcd)
