### ISSUE TITLE
There is no Ubuntu 20.04  deb for v0.13

### ISSUE THREAD

**Issue by doisyg** [intel-isl/Open3D#3554]
and the http://www.open3d.org/ download section points to the v0.12
![image](https://user-images.githubusercontent.com/15727892/121215854-a97f6680-c880-11eb-9911-50fa1658817c.png)

**Comment by ssheorey** [comment]
@doisyg thanks for reporting this.
Updated. Thanks @germanros1987.

Link is https://github.com/intel-isl/Open3D/releases/download/v0.13.0/open3d-app-0.13.0-Ubuntu_20.04.deb
