### ISSUE TITLE
TSDF GPU

### ISSUE THREAD

**Issue by Anzzy30** [intel-isl/Open3D#3555]
Hello,

I'm working on a robot exploration system with tsdf mapping. 

Setup:
- Open3D build from source (recently cloned 5 day ago) 
- cuda 10.1 on 
- Ubuntu 20.04.-
- Laptop with Nvidia 1070
- C++

I'm experiencing an issue on large scene (around 28m x 16m x 8m)  reconstruction using TSDF on GPU.
I get this message (spam after around 15-20min and i guess it depend of the robot location in the scene):
``stdgpu::vector::size : Size out of bounds: -5 not in [0, 3045]. Clamping to 0`` 
Value may vary but always negative. 

Here, is an extracted mesh after around 15-20min, black circle shows some artifact on the mesh (probably due to the error message):
![image](https://user-images.githubusercontent.com/15819918/121246817-d2fcba00-c8a1-11eb-9373-a1b17011d9ac.png)
The artifact seems like a block in the scalable voxel grid is missing.

I run the same experience on CPU everything work fine (no error message no artifact on the extracted mesh).

**Comment by theNded** [comment]
This is because of a hashmap overflow, potentially you may increase block_count on the command line.

**Comment by Anzzy30** [comment]
You right, it works.
I already increase the block_count before opening the issue but not enough.
Thx
