### ISSUE TITLE
Open3d-Viewer only supports CUDA 10

### ISSUE THREAD

**Issue by herrvonregen** [intel-isl/Open3D#3583]
**Describe the bug**
The Open3d-Viewer can not be started because it still uses CUDA 10. I installed the current version available from the release page. 

**To Reproduce**

1. Download current openrd-app (open3d-app-0.13.0-Ubuntu_18.04.deb)
2. sudo apt install ./open3d-app-0.13.0-Ubuntu_18.04.deb
3. Open3D

**Expected behavior**
Starting up the viewer app

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: 3.8.8
- Open3D version: 0.13.0
- CUDA: 11.2

**Comment by ssheorey** [comment]
@herrvonregen what error message do you get?

**Comment by herrvonregen** [comment]
@ssheorey output is:
/usr/local/share/Open3D/bin/Open3D: error while loading shared libraries: libcusolver.so.10: cannot open shared object file: No such file or directory

**Comment by ssheorey** [comment]
Thanks for pointing this out @herrvonregen We will update the `deb` package shortly. It should not need CUDA.

**Comment by herrvonregen** [comment]
Thank you very much @ssheorey

**Comment by ssheorey** [comment]
@herrvonregen a new `deb` packages has been uploaded. Please check it out. It does not use CUDA.
Thanks @errissa !
