### ISSUE TITLE
module 'open3d.cuda.pybind.geometry' has no attribute 'estimate_normals'

### ISSUE THREAD

**Issue by victoryc** [intel-isl/Open3D#3584]
I get the following error when I try to call o3d.geometry.estimate_normals. 

`module 'open3d.cuda.pybind.geometry' has no attribute 'estimate_normals'`

Any idea why? Is "estimate_normals" only available in CPU version and not the GPU version? If so, is there a way to indicate to Open3D to use the cpu version instead of defaulting to GPU (cuda) version?
Thanks.

**Comment by theNded** [comment]
The semantic is `pcd.estimate_normals()`.
