### ISSUE TITLE
Registering challenging point clouds & random number generation

### ISSUE THREAD

**Issue by longchao343** [intel-isl/Open3D#359]
Hi, I use Open3D RegistrationRANSACBasedOnFeatureMatching and FastGlobalRegistration api on my c++ project, but I found the results are not that stable. I also test the data using Open3D TestRegistrationRANSAC.cpp, the results are also bad. But when I test the data using python scripts,the results are stable and correct. Can you help me out? Thanks

**Comment by longchao343** [comment]
Seems in openmp environment, open3D would also perform bad.

**Comment by syncle** [comment]
> I found the results are not that stable. But when I test the data using python scripts,the results are stable and correct

I think some parameters for registration was not correctly set. For the registration, it is required to go through some pre-processing. Consider mimic parameters (or use the same relative ratios of downsampling, search radius for normal estimation, feature extraction, and RANSAC) as shown in the python tutorial.

**Comment by longchao343** [comment]
Hi, syncle, I use the parameters just as the python scripts use. Here are my results:
![_023](https://user-images.githubusercontent.com/9880417/40158456-3b4ee0ac-59d7-11e8-9684-b9862da922a6.png)
![_024](https://user-images.githubusercontent.com/9880417/40158457-3b9c0bde-59d7-11e8-981a-0be0036dda35.png)

**Comment by longchao343** [comment]
And here is my usage of global registation
`void RelativePoseIcpSolver::FPFHRoughPoseSolver(three::PointCloud& cloud0,three::PointCloud& cloud1,
                         const Eigen::Matrix4d& init_pose,Eigen::Matrix4d& rela_pose,
                         double& time,bool& converged,double& fitness_score,bool bCalcu_normal,bool buse_fast_reg)
{
    pcl::console::TicToc timer;
    timer.tic();
    //since pcl sac-ia implementation is rubish, we use implementation of zhouqianyi
    //zhouqianyi's implementation seems very fast, so we use finner grid leaf size
    //TODO: internal implement sac-ia
    if(init_pose != Eigen::Matrix4d::Identity() && init_pose != Eigen::Matrix4d::Zero())
        cloud0.Transform(init_pose);

    auto prepareCloud = [&bCalcu_normal,this](const three::PointCloud& input,three::PointCloud& downspaled,shared_ptr<three::Feature>& features)
    {
        auto input_downsample_ptr = three::VoxelDownSample(input,param.fine_leaf_size);
        downspaled = *input_downsample_ptr;
        if(bCalcu_normal)
        {
            double normal_search_radius = param.fine_leaf_size * 2;
            three::EstimateNormals(downspaled,three::KDTreeSearchParamHybrid(normal_search_radius,30));
        }
        double feature_search_radius = param.fine_leaf_size*5;
        features = three::ComputeFPFHFeature(downspaled,three::KDTreeSearchParamHybrid(feature_search_radius,100));
    };

    three::PointCloud src,tgt;
    shared_ptr<three::Feature> src_fpfh_feature,tgt_fpfh_feature;

    prepareCloud(cloud0,src,src_fpfh_feature);
    prepareCloud(cloud1,tgt,tgt_fpfh_feature);

    //sac-ia or fast global registraion
    three::RegistrationResult results;
    if(buse_fast_reg)
    {
        three::FastGlobalRegistrationOption fast_regist_option;
        fast_regist_option.maximum_correspondence_distance_ = param.fine_leaf_size * 0.5;
        results = three::FastGlobalRegistration(src,tgt,*src_fpfh_feature,*tgt_fpfh_feature,fast_regist_option);
    }
    else
    {
        double distance_thresh = param.fine_leaf_size * 1.5;
        std::vector<std::reference_wrapper<const three::CorrespondenceChecker> >
                correspondence_checker;
        auto correspondence_checker_edge_length =
                three::CorrespondenceCheckerBasedOnEdgeLength(0.9);
        auto correspondence_checker_distance =
                three::CorrespondenceCheckerBasedOnDistance(distance_thresh);

        correspondence_checker.push_back(correspondence_checker_edge_length);
        correspondence_checker.push_back(correspondence_checker_distance);

        results = three::RegistrationRANSACBasedOnFeatureMatching(src,tgt,*src_fpfh_feature,*tgt_fpfh_feature,
                                                                  distance_thresh,three::TransformationEstimationPointToPoint(false),
                                                                    4, correspondence_checker,
                                                                  three::RANSACConvergenceCriteria(4000000, 500));
    }
    //retrival pose
    cout<<results.transformation_<<endl;
    rela_pose = results.transformation_ * init_pose;
    fitness_score = results.fitness_;
    time = timer.toc();
    //print ICP report
    cout<<"==============Open3D FPFH SAC-IA Report================\n"<<
        " time: "<<time<<"\n converged: "<<converged<<"\n fittness socre: "<<fitness_score<<
        "\n relative pose: \n"<<rela_pose<<"\n";
    cout<<"==========================================\n";
}`

**Comment by longchao343** [comment]
Here is my usage:
`void RelativePoseIcpSolver::FPFHRoughPoseSolver(three::PointCloud& cloud0,three::PointCloud& cloud1,
                         const Eigen::Matrix4d& init_pose,Eigen::Matrix4d& rela_pose,
                         double& time,bool& converged,double& fitness_score,bool bCalcu_normal,bool buse_fast_reg)
{
    pcl::console::TicToc timer;
    timer.tic();
    //since pcl sac-ia implementation is rubish, we use implementation of zhouqianyi
    //zhouqianyi's implementation seems very fast, so we use finner grid leaf size
    //TODO: internal implement sac-ia
    if(init_pose != Eigen::Matrix4d::Identity() && init_pose != Eigen::Matrix4d::Zero())
        cloud0.Transform(init_pose);

    auto prepareCloud = [&bCalcu_normal,this](const three::PointCloud& input,three::PointCloud& downspaled,shared_ptr<three::Feature>& features)
    {
        auto input_downsample_ptr = three::VoxelDownSample(input,param.fine_leaf_size);
        downspaled = *input_downsample_ptr;
        if(bCalcu_normal)
        {
            double normal_search_radius = param.fine_leaf_size * 2;
            three::EstimateNormals(downspaled,three::KDTreeSearchParamHybrid(normal_search_radius,30));
        }
        double feature_search_radius = param.fine_leaf_size*5;
        features = three::ComputeFPFHFeature(downspaled,three::KDTreeSearchParamHybrid(feature_search_radius,100));
    };

    three::PointCloud src,tgt;
    shared_ptr<three::Feature> src_fpfh_feature,tgt_fpfh_feature;

    prepareCloud(cloud0,src,src_fpfh_feature);
    prepareCloud(cloud1,tgt,tgt_fpfh_feature);

    //sac-ia or fast global registraion
    three::RegistrationResult results;
    if(buse_fast_reg)
    {
        three::FastGlobalRegistrationOption fast_regist_option;
        fast_regist_option.maximum_correspondence_distance_ = param.fine_leaf_size * 0.5;
        results = three::FastGlobalRegistration(src,tgt,*src_fpfh_feature,*tgt_fpfh_feature,fast_regist_option);
    }
    else
    {
        //TODO: stl ref_warpper seems cause error,tobe checked
        double distance_thresh = param.fine_leaf_size * 1.5;
        std::vector<std::reference_wrapper<const three::CorrespondenceChecker> >
                correspondence_checker;
        auto correspondence_checker_edge_length =
                three::CorrespondenceCheckerBasedOnEdgeLength(0.9);
        auto correspondence_checker_distance =
                three::CorrespondenceCheckerBasedOnDistance(distance_thresh);

        correspondence_checker.push_back(correspondence_checker_edge_length);
        correspondence_checker.push_back(correspondence_checker_distance);

        results = three::RegistrationRANSACBasedOnFeatureMatching(src,tgt,*src_fpfh_feature,*tgt_fpfh_feature,
                                                                  distance_thresh,three::TransformationEstimationPointToPoint(false),
                                                                    4, correspondence_checker,
                                                                  three::RANSACConvergenceCriteria(4000000, 500));
    }
    //retrival pose
    cout<<results.transformation_<<endl;
    rela_pose = results.transformation_ * init_pose;
    fitness_score = results.fitness_;
    time = timer.toc();
    //print ICP report
    cout<<"==============Open3D FPFH SAC-IA Report================\n"<<
        " time: "<<time<<"\n converged: "<<converged<<"\n fittness socre: "<<fitness_score<<
        "\n relative pose: \n"<<rela_pose<<"\n";
    cout<<"==========================================\n";
}`

**Comment by longchao343** [comment]
And here is my code snap:
![_025](https://user-images.githubusercontent.com/9880417/40158674-5915963e-59d8-11e8-91e2-b900dc3ec516.png)

**Comment by syncle** [comment]
WOW, this is a lot amount of texts to review. 

I was able to find something suspicious from your result: 
```
total_validation: 0
```
or 
```
total_validation: 1
```

Which means RANSAC iteration could not find enough numbers of valid candidate that satisfies criteria you set such as ``CorrespondenceCheckerBasedOnEdgeLength`` or ``CorrespondenceCheckerBasedOnDistance``. This means the issue comes from early stage: local feature matching.

Some comments for this:
- Based on the log you shared, you are using **MatterPort** scan dataset. How good is it? Is it clean? Do you see the same topology (without noticible distortion) for the same region?
- If the scanned scene is very large, actually FPFH is not very good choice because FPFH is not that strong feature for repetitive geometries.
- If the scene is very large, consider **increase the range** for feature extraction (of course increase parameters for voxel downsampling and normal estimation too). The local feature will see large topologies and will not be distracted by repetitive small geometries. Once rough registration is found, you can apply ICP with high-resolution point clouds.

Actually it reminds me your last question:

> But when I test the data using python scripts, the results are stable and correct.

This is somewhat weird, as python binding just port the c++ implementation. Technically **it should be the same**. What python binding example says? Does it show more RANSAC validation numbers?

**Comment by longchao343** [comment]
Thanks for your kind help. I have pre-process the point cloud, so there would be no distortion or noticible noise. I felt confused because I test a couple of clouds many times,it gives me good results, but when I test the pairs with others, the results becomes bad.  I have also test FastGlobalRegistration, single run the test will give very good results. But when test all cloud pairs, the results become bad. 

Here are my python scripts results:
:: Load two point clouds and disturb initial pose.
Reading PLY: [========================================] 100%
Reading PLY: [========================================] 100%
:: Downsample with a voxel size 0.050.
:: Estimate normal with search radius 0.100.
:: Compute FPFH feature with search radius 0.250.
:: Downsample with a voxel size 0.050.
:: Estimate normal with search radius 0.100.
:: Compute FPFH feature with search radius 0.250.
:: RANSAC registration on downsampled point clouds.
   Since the downsampling voxel size is 0.050,
   we use a liberal distance threshold 0.075.
RegistrationResult with fitness = 0.417139, inlier_rmse = 0.031281, and correspondence_set size of 11400
Access transformation to get result.

**Comment by syncle** [comment]
The point cloud pair you shared looks fine at a first glance.  However, it does not have enough overlapping area having distinguished topologies. Specifically, only small part of planar scenes (walls and floor) overlaps in this case. Local feature extracted from the planar scene is not very useful because there are too many false alarm. That's why local feature struggles. 

Open3D does not have a magical alignment method for this case, but you can try manual alignment example for the following result.
<img width="1072" alt="screen shot 2018-05-17 at 12 37 25 am" src="https://user-images.githubusercontent.com/18297113/40162999-815524b6-596a-11e8-95c4-71c083decf43.png">

I used http://open3d.org/docs/tutorial/Advanced/interactive_visualization.html#manual-registration (with downsampling voxel size 0.2)

**Comment by longchao343** [comment]
It seems that the python scripts' results depends on the compilation. I re-compile the lib , python scripts always failed this time.

**Comment by longchao343** [comment]
Well, I mean each time I compiled the Open3D lib, and run the same dataset, python scripts would give me either all good or all bad results. Very werid.
I have tested to increase the voxel grid size to increase the search radius as you mentioned. RegistrationRANSACBasedOnFeatureMatching method improved a lot :). I have also tested the FastGlobalRegistration, with the same voxel grid size, the results were nearly to Identity. Do you have some suggestions? Which method perform better?
Thanks for your kind help.

**Comment by syncle** [comment]
> python scripts would give me either all good or all bad results

Maybe some randomness may affect the result. I don't think this is just because of compilation condition. However, as you are concerning, there might be some bug in the code regarding the random seed generation. If it is true and actually happening depending on specific environment, we need to find out. Can you tell me your environment? We can also work together for this :)

> I have tested to increase the voxel grid size to increase the search radius as you mentioned. 
RegistrationRANSACBasedOnFeatureMatching method improved a lot :)

Sounds great! Yes. The tutorial examples are tuned for 3x3x3m scenes that is rather small than your dataset. Go ahead and feel free to tune it.

> Which method perform better?

I must say both methods are good, but if you have a strict time constraint, consider using FastGlobalRegistration. I personally prefer FastGlobalRegistration as it is next version of RegistrationRANSACBasedOnFeatureMatching. Next Open3D version will use fast global registration in the reconstruction system.

**Comment by longchao343** [comment]
I use Open3D in ubuntu 16.04 ,and I will begin to learn and read Open3D's code.

**Comment by longchao343** [comment]
Hi @syncle, I have read the code of RegistrationRANSACBasedOnFeatureMatching, is it a problem in using rand() in ransac? since rand give a number between 0~32757, a large cloud may easily bigger than 3257. I used unifrom_in_distribution to uniform sample the points, but the api returned bad results.

**Comment by syncle** [comment]
That is really a problem if RAND_MAX is 32757. However, I don't think that is the case for 32bit integer systems. Can you check RAND_MAX? RAND_MAX should be 2147483647, which is the maximum number of 32-bit integer.

**Comment by longchao343** [comment]
Yes, you are right. I have a question,in ransac process, is it needed to ensure every-time ransac generate different distribution of sample when I use the registration api?  Because I found when I disable srand, the results becomes much stable and correct.

**Comment by syncle** [comment]
That's good point. According to http://en.cppreference.com/w/cpp/numeric/random/rand, it says

> **rand() is not recommended for serious random-number generation needs.** It is recommended to use C++11's random number generation facilities to replace rand(). (since C++11)

As Open3D uses C++11, I think there is no reason not to use the new C++11 implementation. Can you remove ``srand()`` and ``rand()``, try this example, and tell me how it looks like? This fix will be great commit. I will try this too with [redwood benchmark dataset](http://redwood-data.org/indoor/dataset.html).

```
    # initialization 
    std::random_device r;
    std::default_random_engine e1(r());
    std::uniform_int_distribution<int> uniform_dist(1, (int)source.points_.size()); # maybe uniform_real_distribution would be better choice.
    
    # in for loop
    int random_id = uniform_dist(e1);
```
Note: I took this example from http://en.cppreference.com/w/cpp/numeric/random

**Comment by longchao343** [comment]
Actually, I have used uniform distribution for ransac process, mt19337 also be a good choice.It works great for me, no randomness happened. I will continue to read the fast global registration paper and code. Shoud it be `std::uniform_real_distribution<int> uniform_dist(0, (int)source.points_.size()-1);`  here?

**Comment by syncle** [comment]
Correct! I confused with ``uniform_real_distribution``. I am actually using
```
# initialization
std::uniform_int_distribution<int> uniform_dist(0, std::numeric_limits<int>::max());

# in rand() loop
int source_sample_id = uniform_dist(engine) % (int)source.points_.size();
```
to use ``uniform_dist`` for multiple purpose.

**Comment by longchao343** [comment]
Well, uniform_real_distribution accepts float,double, and it stands for [range0,range1). uniform_int_distribution accept integer, and it stands for [range0,range1]

**Comment by syncle** [comment]
You got it right. That is the part I had confused. I think 
```
std::uniform_int_distribution<int> uniform_dist(0, (int)source.points_.size()-1)
``` 
and
```
std::uniform_int_distribution<int> uniform_dist(0, std::numeric_limits<int>::max());
int source_sample_id = uniform_dist(engine) % (int)source.points_.size();
``` 
will produce the same behavior, but I wanted to use the second one as it can be used in other cases. For example, ``uniform_dist(engine) % 2`` to generate {0,1}

**Comment by longchao343** [comment]
Hi, syncle,Do you have suggestions of large scale or low overlap point clouds init registration? I have test Open3D on my matterpot datasets, the results was really bad.

**Comment by qianyizh** [comment]
It is in general a very difficult problem for registration of low-overlapping point clouds. To make any generic global registration algorithms work well, it is usually suggested to have more than 30% overlapping. In practice, more overlapping scans and more redundant data usually always make the registration better.

If your scanning setup is highly constrained, there are other possible ways to explore. For example, you can provide more information regarding point cloud poses, thus limit the problem scope. Many scanners provide a "gravity" direction. Using it reduces rotation from 3DOF to 1DOF.

Open3D currently does not support these features. However, it's provides a quite generic optimization framework. I believe you can hack into the C++ code and write your own optimization.

**Comment by longchao343** [comment]
Hi,@qianyizh，thanks for your good suggestion. Indeed, I use the imu observation to provide good rotation estimate when I get started. But I found both ICP and Fpfh ransac matching perform badly. And then I replaced transform estimate functions using Eigen LM, but I found even if I fixed rotation, translation was still bad for both fpfh and point to plane icp. I think accurate prior rotation did not help when invoving point or feature matching. Seems that false matches are still there.  Is there a good way to only calculate translation when we reduce the problem into 3 dimensiona? Are Fine gained icp a good choise？

**Comment by qianyizh** [comment]
If you have a good initialization, do ICP. If the initialization is not good. There are not many good options. The most promising method is to limit the DOF and write a different optimization for global optimization. It's on our roadmap but Open3D does not have it right now.

**Comment by longchao343** [comment]
Hi, @qianyizh ,I have test fine gained icp, and I found when I set voxel very small, icp could give a good init estimate. But wrong registration happend, if distance bigger than 2m(overlap < 30%).  Can you tell me how to design a good different energy function to only optimise translation? Maybe I can have a try and give some feedback. Thanks.

**Comment by qianyizh** [comment]
@syncle can you followup with the last question and give some insights? You contributed most to the registration part, :)

**Comment by syncle** [comment]
I think this is related to the feature request opened in #409. Let me think how we can modularize ICP or registrations.

**Comment by sambarluc** [comment]
Do I understand correctly that the random number generation never made it into master? I am also trying to understand why my results with RANSAC/FPFH are unstable, and ended up in this conversation.

**Comment by germanros1987** [comment]
@syncle could you please comment on this?

**Comment by germanros1987** [comment]
My understanding is that #1486 solves this issue, so I am closing it.
