### ISSUE TITLE
eglInitialize failed when using webrtc

### ISSUE THREAD

**Issue by eratormortimer** [intel-isl/Open3D#3596]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When trying to use the new webrtc feature on Ubuntu I get this error:
```
[Open3D INFO] WebRTC GUI backend enabled. 
[Open3D INFO] Window window_0 created.
[Open3D INFO] EGL headless mode enabled.
FEngine (64 bits) created at 0x7fbc480a0010 (threading is enabled)
eglInitialize failed
Segmentation fault (core dumped)
```

**To Reproduce**

1. vim test.py: 
  ```
  import open3d as o3d 
  o3d.visualization.webrtc_server.enable_webrtc()
  cube_red = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
  o3d.visualization.draw(cube_red)
```
2. python3.7 test.py
3. See error

**Expected behavior**
I would expect it to behave as in the example provided here: [https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw_webrtc.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw_webrtc.py).  So it should post a link to localhost:8090 where I can see the structure.

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.7
- Open3D version: open3d-0.13.0+66e3204-cp37-cp37m-manylinux_2_27_x86_64
- Is this remote workstation?: yes 
- How did you install Open3D?: pip

**Additional context**
I tried to fix this by installing these libraries:
```
apt install libgl1 \
    libglx0 \
    libegl1 \
    libxext6 \
    libx11-6 \
    libosmesa6-dev \
    libglfw3-dev \
    libgles2-mesa-dev \
    libegl1-mesa-drivers \
```
None of them seemed to effect it. In your demo [video](https://www.youtube.com/watch?v=pLCVCH7ypI4) it seemes to work as I would expect it on Ubuntu. So maybe certain dependencies need to be installed that I dont know about? Would love to have some feedback on this where I could start to try to debug this

**Comment by ssheorey** [comment]
Hi @eratormortimer thanks for reporting this. We are looking into this issue. Can you provide some more information?
- Details on your video card setup
- Output of `eglinfo` command (from the `mesa-utils-extra` package on Ubuntu).

**Comment by eratormortimer** [comment]
Thank you for the quick response!
I think I found the issue, our Xeon lacks an integrated graphics component. I will try out these new features on a different server with an dedicated graphics card. 
Thanks for the great work you guys are doing
