### ISSUE TITLE
Simplifying registration parameters

### ISSUE THREAD

**Issue by syncle** [intel-isl/Open3D#360]
In our python tutorial and c++ examples, there are many parameters required for registration application. We need to reduce the parameters in our examples for better readablity and usability. 

I think in the ideal case, the user only specifies voxel downsampling radius, and the rest of the script/code uses relative values for normal estimation, feature extraction, and registration and so on.

**Comment by qianyizh** [comment]
Actually I think even the voxel size can be automatically computed. It is the similar idea as in #371 

In this case we can create a ``point-and-shoot`` ICP registration algorithm. The only parameter would be a scale between 0 and 10, with 0 being the fastest but least accurate, and 10 being the most accurate but slowest, and -1 being the default (5, e.g.).

This would be really cool.
