### ISSUE TITLE
3D model projection to camera plane

### ISSUE THREAD

**Issue by YufengJin** [intel-isl/Open3D#3608]
The camera parameters (intrinsic parameter, extrinsic parameter) are known. And the mesh file of the object exists with .obj extension. The transform matrix between the object frame and camera frame is updated with time.  I want to get images of the rendered object from the camera view. Can I use open3d to do this? Can open3d do real-time 3d rendering?

**Comment by ssheorey** [comment]
Hi @YufengJin check out the off-screen rendering sample code:

https://github.com/intel-isl/Open3D/blob/master/examples/cpp/OffscreenRendering.cpp

**Comment by YufengJin** [comment]
> Hi @YufengJin check out the off-screen rendering sample code:
> 
> https://github.com/intel-isl/Open3D/blob/master/examples/cpp/OffscreenRendering.cpp

**Comment by YufengJin** [comment]
I found open3d supports Python API (open3d.visualization.rendering). Does it do the same job?
