### ISSUE TITLE
Wrong displacement of t::geometry::PointCloud generated from ray casted TSDFVolume::SurfaceMaskCode::VertexMap trying to receive camera "frustum view" point cloud from t::geometry::TSDFVoxelGrid

### ISSUE THREAD

**Issue by VladMVLX** [intel-isl/Open3D#3613]
Hello open3D developers,

I want to say many thanks to the @theNded for pointing me out on how to solve [#3491](https://github.com/intel-isl/Open3D/issues/3491) issue and to all devs working hard on this fantastic library.

Unfortunately I cannot reopen previous issue as @theNded advised and I am afraid it is to much outdated for being noticed.

I tried approach @theNded [recommended](https://github.com/intel-isl/Open3D/issues/3491#issuecomment-846421759) on master branch (as it seams his branch was merged into the master in v0.13)

I am trying to use extrinsics matrix from T265 tracking camera to integrate and ray cast on TSDFVolume:
```c++
open3d::core::Tensor extrinsics = open3d::core::eigen_converter::EigenMatrixToTensor(Transform);
auto inverse_extrinsics = open3d::t::geometry::InverseTransformation(extrinsics);

_tsdfVolume->Integrate(depth, color, intrinsics, inverse_extrinsics, depthScale, maxDepth);


auto result = _tsdfVolume->RayCast(
	intrinsics, inverse_extrinsics, width, height,
	1, 0.0f, maxDepth, 3.0f,
	TSDFVolume::SurfaceMaskCode::ColorMap | TSDFVolume::SurfaceMaskCode::VertexMap | TSDFVolume::SurfaceMaskCode::DepthMap);
```

get ColorMap and VertexMap:
```c++
open3d::t::geometry::Image vertexImg(result[TSDFVolume::SurfaceMaskCode::VertexMap]);
open3d::t::geometry::Image colorImg(result[TSDFVolume::SurfaceMaskCode::ColorMap]);
```
and convert it into point cloud as @theNded recommended:

```c++
const int64_t im_size = vertexImg.GetRows() * vertexImg.GetCols();

const float invalid_fill = NAN;

auto vertex_list = vertexImg.AsTensor().View({ im_size, 3 });

f32_extrinsics= f32_extrinsics.Inverse();

vertex_list = vertex_list
		.Matmul(f32_extrinsics.Slice(0, 0, 3, 1)
		.Slice(1, 0, 3, 1))
		.Add_(f32_extrinsics.Slice(0, 0, 3, 1)
		.Slice(1, 3, 4, 1)
		.T());

vertexImg = open3d::t::geometry::Image(vertex_list.View(vertexImg.AsTensor().GetShape())
			.Contiguous());
		
auto normal_map_t = vertexImg.CreateNormalMap(invalid_fill)
		.AsTensor()
		.View({ im_size, 3 });
		// all columns are the same
auto valid_idx =
	normal_map_t.Slice(1, 0, 1, 1)
	.IsFinite()
	.LogicalAnd(vertex_list.Slice(1, 0, 1, 1).IsFinite())
	.Reshape({ im_size });
open3d::t::geometry::PointCloud pcd(
			{ {"points",
			  vertex_list.GetItem({open3d::core::TensorKey::IndexTensor(valid_idx),
								   open3d::core::TensorKey::Slice(open3d::core::None, open3d::core::None, open3d::core::None)})},
			 {"normals",
			  normal_map_t.GetItem({open3d::core::TensorKey::IndexTensor(valid_idx),
									open3d::core::TensorKey::Slice(open3d::core::None, open3d::core::None, open3d::core::None)})} });
if (colorImg.GetRows() > 0) {
	pcd.SetPointColors(
		colorImg.AsTensor()
		.View({ im_size, 3 })
		.GetItem({ open3d::core::TensorKey::IndexTensor(valid_idx),
				  open3d::core::TensorKey::Slice(open3d::core::None, open3d::core::None, open3d::core::None) }));
		}
```
Everything works fine, and I am getting pretty accurate point cloud from camera frustum view while camera standing stationary with only rotations applied.

The problem appears when camera moved physically along any of any of directions. Generated point cloud from vertex map seams to have wrong displacement and not aligning with point clouds from previous frames:
![image](https://user-images.githubusercontent.com/58504993/122637994-2b318880-d0fa-11eb-9795-51ebfce82aa8.png)
I also tried to use:

```c++
open3d::t::geometry::PointCloud::CreateFromRGBDImage(rgbd_image, intrinsics, f32_extrinsics, 1.f, maxDepth, 1, true);
```

But results seams to be the same.

This problem only appears on point clouds generated from vertex maps in real-time, the whole point cloud extracted by:

```c++
tsdfVolume->ExtractSurfacePoints(
			3000000, 0.0f,
			TSDFVolume::SurfaceMaskCode::VertexMap | TSDFVolume::SurfaceMaskCode::ColorMap | TSDFVolume::SurfaceMaskCode::NormalMap);
```
Looks fine and don`t have any visual align related artifacts:
![image](https://user-images.githubusercontent.com/58504993/122638003-32f12d00-d0fa-11eb-9c70-454c268892e5.png)

I suspect there are some minor issue in vertex map generation or code that converts it to the point cloud which resulting in wrong point cloud displacement, can you please advise?

Sorry for bad quality scans, made them only for debug purposes, but hopefully they are well representing the problem.

**Comment by theNded** [comment]
```
auto vertex_list = vertexImg.AsTensor().View({ im_size, 3 });

f32_extrinsics= f32_extrinsics.Inverse();

vertex_list = vertex_list
		.Matmul(f32_extrinsics.Slice(0, 0, 3, 1)
		.Slice(1, 0, 3, 1))
		.Add_(f32_extrinsics.Slice(0, 0, 3, 1)
		.Slice(1, 3, 4, 1)
		.T());
```
There might be some issues here, let's try to reason a bit:
`f32_extrinsics` is in fact a pose (say [R | t]), transforming the point cloud from camera frame to world. So the correct way to use it should be 
`R (3, 3) x vertex_list.T (3, N) + t (3, 1)`.
But if we don't want to transpose the point tensor and keep it as `vertex_list (N, 3)`, then we need to transpose the rotation instead:
`vertex_list (N, 3) x R.T (3, 3) + t.T (1, 3)`.

Does it make sense? Please let me know if I misunderstand something.

**Comment by VladMVLX** [comment]
@theNded  thank you,

I changed code to:

```c++
open3d::core::Tensor f32_extrinsics(extrinsics.GetShape(), vertexImg.GetDtype(), vertexImg.GetDevice());
f32_extrinsics.CopyFrom(extrinsics);

const int64_t im_size = vertexImg.GetRows() * vertexImg.GetCols();

auto vertex_list = vertexImg.AsTensor().View({ im_size, 3 });		

vertex_list = vertex_list
  		    .Matmul(f32_extrinsics.Slice(0, 0, 3, 1)
		    .Slice(1, 0, 3, 1).T())
		    .Add_(f32_extrinsics.Slice(0, 0, 3, 1)
		    .Slice(1, 3, 4, 1).T());
```

And now it works as intended.

Not sure, but maybe:
```c++
open3d::t::geometry::PointCloud::CreateFromRGBDImage(rgbd_image, intrinsics, f32_extrinsics, 1.f, maxDepth, 1, true);
```
https://github.com/intel-isl/Open3D/blob/0fb69ce9647e0f13591d8f4275e1fe6fb644bdfa/cpp/open3d/t/geometry/PointCloud.cpp#L252

method needs to be changed as well? 

Seams like it following the same logic as I did: 
https://github.com/intel-isl/Open3D/blob/0fb69ce9647e0f13591d8f4275e1fe6fb644bdfa/cpp/open3d/t/geometry/PointCloud.cpp#L301-L307

and resulting in wrong displacements.

**Comment by theNded** [comment]
Thanks! @ssheorey would you please fix `CreatePointCloudWithNormals` given the discussion above?

**Comment by ssheorey** [comment]
Thanks @VladMVLX for pointing this out. I'll fix `CreatePointCloudWithNormals`.
