### ISSUE TITLE
Possibility to store points as floats instead of doubles 

### ISSUE THREAD

**Issue by FabianSchuetze** [intel-isl/Open3D#3615]
Is there a possibility to store the points inside pointclouds as floats instead of doubles? I am sometimes running out of memory and wonder how much memory I could have saved by not storing the data as a `Eigen::Vector3f` instead of an `Eigen::Vector3d` .

**Comment by cheylong** [comment]
code like this may help u:
Eigen::Vector3d b(1,1,1);
Eigen::Vector3f a = b.cast<float>();

**Comment by ssheorey** [comment]
This is already available in the new Tensor based API available in the `open3d::t` and `open3d::core` namespaces. Please try it out.

http://www.open3d.org/docs/latest/cpp_api/namespaceopen3d_1_1t.html

We are also looking into providing support for very large point clouds. Can you tell us more about your use case?

Closing this issue, but please re-open if specific features are not available.
