### ISSUE TITLE
How to draw a plane with Open3d?

### ISSUE THREAD

**Issue by JimXu1989** [intel-isl/Open3D#3618]
Hi

I want to know how to draw a plane with open3D?

Thanks a lot

**Comment by hduonggithub** [comment]
@JimXu1989 
There is no direct way. 

I know there are 2 possible ways. The 1st method is more flexible for me.
1. Make a triangle mesh from points/vertices of your plane, e.g. 4 corners of a plane
2. Make a flat box (I did not remember how to do it, please search in the doc)

**Comment by yxlao** [comment]
Draw a `TriangleMesh` with 2 triangles. Or, draw a `LineSet` of 4 lines.

**Comment by valmirnjr** [comment]
You can create a box with a tiny value for one of its dimensions:
`mesh_box = o3d.geometry.TriangleMesh.create_box(width=30.0,
                                                                                      height=30.0,
                                                                                      depth=0.1)`

**Comment by JimXu1989** [comment]
> You can create a box with a tiny value for one of its dimensions: `mesh_box = o3d.geometry.TriangleMesh.create_box(width=30.0, height=30.0, depth=0.1)`

Thanks, I also do it in this way

**Comment by achbogga** [comment]
@yxlao I have a plane equation like this Z = X*a1 + Y*a2 + c (I have a1, a2, c values). How can this box be aligned to this plane specifically?

Thanks a lot

**Comment by mbodier** [comment]
> @yxlao I have a plane equation like this Z = X_a1 + Y_a2 + c (I have a1, a2, c values). How can this box be aligned to this plane specifically?
> 
> Thanks a lot

I'm having the same problem here. Your equation is more like `Z = X*a1 + Y*a2 + c` right?

I rearrange it as `a1*X+a2*Y-Z = -c`
Your normal vector is (a1, a2, -1) also known as the plane equation
A possible origin is O = (0, 0, c)
Let's add a point A = (-c/a1, 0, 0)

w would be your plane normal, w=(a1, a2, -1)/norm((a1,a2,-1))
norm((x,y,z))=sqrt(x^2+y^2+z^2)

You get a second vector u = (A-O)/norm(A-O)
The cross product ^ gives you w^u = v

I think you can go two ways:
1. Define the mesh yourself
2. Box + rotation

1. Define the mesh yourself
---------------------------

If your meshed plane is a square, s can be its side length
You can have H, I, J, K points with:
H = O + s/2*(u+v)
I = O + s/2*(u-v)
J = O + s/2*(-u-v)
K = O + s/2*(-u+v)

You define the triangles HIJ and HJK for your TriangleMesh and you're good to go. You can also do a loop with the u, v vectors to get something more refined but I don't know how to connect all the triangles.

2. Box + rotation
----------------

- Create a box parallel to the (X,Y) plane with a thin Z depth.
- Define the trihedrons T1= (X, Y, Z) and T2 = (u, v, w)
- Find the rotation matrix between the two trihedrons.
- You can use Rotation.align_vectors(T1, T2) from scipy.spatial.transform
- Apply the rotation matrix to your plane
- Translate your plane from (0,0,0) to your origin O = (0, 0, c)
- No perfectly sure for the whole process, you must check the orientations, trihedrons, center of rotation... but you get the idea

Hope this helps!
