### ISSUE TITLE
Clustering extraction

### ISSUE THREAD

**Issue by feersantana5** [intel-isl/Open3D#3630]
Is there any possibility to extract clusters resulting from cluster_dbscan and create their point clouds?

I have been trying using the labels but I'm getting runtime error. 

I would appreciate if you attach an example.

**Comment by hduonggithub** [comment]
@feersantana5 

In the code below, pcd_i is your individual cluster.

with o3d.utility.VerbosityContextManager(
        o3d.utility.VerbosityLevel.Debug) as cm:
    labels = np.array( pcd.cluster_dbscan(eps=0.02, min_points=10, print_progress=True))

max_label = labels.max() + 1
for i in range(max_label):
        id = np.where(labels==i)[0]
        pcd_i = pcd.select_by_index(id)

**Comment by Selar007** [comment]
I have added a few comments to make it easier to understand:

 # Labels is array of elements, where element position is point name, element value is cluster label
        with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm:
            labels = np.array(common_pcl.cluster_dbscan(eps=1, min_points=1, print_progress=False))

        if labels != []:
            # Get biggest cluster label
            max_label = labels.max() + 1
            
            for i in range(max_label):
                # id is array of point names in main point cloud, owned by cluster with label i
                id = np.where(labels == i)[0]
                # Creating a new point cloud from cluster with label i
                pcd_i = common_pcl.select_by_index(id)

**Comment by Selar007** [comment]
I have added a few comments to make it easier to understand:

```
#Labels is array of elements, where element position is point name, element value is cluster label
    with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm:
        labels = np.array(common_pcl.cluster_dbscan(eps=1, min_points=1, print_progress=False))

    if labels != []:
        # Get biggest cluster label
        max_label = labels.max() + 1
        
        for i in range(max_label):
            # id is array of point names in main point cloud, owned by cluster with label i
            id = np.where(labels == i)[0]
            # Creating a new point cloud from cluster with label i
            pcd_i = common_pcl.select_by_index(id)
```
