### ISSUE TITLE
Jetson Nano - Open3D 0,13.0

### ISSUE THREAD

**Issue by iacisme** [intel-isl/Open3D#3634]
Hi;

I'm trying to build Open3D 0.13.0 from source, using the same instructions I made to successfully build 0.11.x. 

I have a Jetson Nano with Jetpack 4.5.1, freshly installed. 

Here is my cmake build list

```
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS=ON \
-DBUILD_CUDA_MODULE=ON \
-DBUILD_GUI=ON \
-DBUILD_TENSORFLOW_OPS=OFF \
-DBUILD_PYTORCH_OPS=OFF \
-DBUILD_UNIT_TESTS=ON \
-BUILD_WEBRTC=ON \
-DBUILD_JUPYTER_EXTENSION=ON \
-DCMAKE_INSTALL_PREFIX=~/open3d_install \
-DPYTHON_EXECUTABLE=$(which python) \
..
```

 Here are the errors I get:

```
-- CMAKE_BUILD_TYPE is set to Release.
-- ccache found at /usr/bin/ccache
-- Downloading 3rdparty dependencies to /home/jiac/Documents/Open3D/3rdparty_downloads
CMake Deprecation Warning at CMakeLists.txt:131 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Warning at CMakeLists.txt:139 (message):
  ARM CPU detected, setting USE_BLAS=ON.


CMake Warning at CMakeLists.txt:143 (message):
  ARM CPU detected, setting BUILD_FILAMENT_FROM_SOURCE=ON.

CMake Error at CMakeLists.txt:172 (message):
  BUILD_JUPYTER_EXTENSION=ON requires BUILD_WEBRTC=ON

-- Configuring incomplete, errors occurred!
```
Can someone please give suggestions on how to fix? As you can see by the build list, I have both JUPYTER and WEBRTC = ON.

Thanks guys.

--Igor

**Comment by sanskar107** [comment]
@iacisme WebRTC is not yet supported on arm, and we disable it internally. This results in your error if Jupyter extension is ON. You can try building it again with both `BUILD_WEBRTC=OFF` and `BUILD_JUPYTER_EXTENSION=OFF`

**Comment by iacisme** [comment]
@sanskar107 ok, thanks! I'll try that.

**Comment by iacisme** [comment]
Hi;

Can I please ask a follow up question?

I've run the following command on a new Jetson Nano (JP 4.5.1) to see if webrtc is installed:

`
gst-inspect-1.0 webrtcbin
`
And this is the result, which to me implies WebRTC is available on the nano.

Can you please confirm what the script is looking for to confirm if WEBRTC is installed?

Many thanks!

`
Factory Details:
  Rank                     primary (256)
  Long-name                WebRTC Bin
  Klass                    Filter/Network/WebRTC
  Description              A bin for webrtc connections
  Author                   Matthew Waters <matthew@centricular.com>

Plugin Details:
  Name                     webrtc
  Description              WebRTC plugins
  Filename                 /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstwebrtc.so
  Version                  1.14.5
  License                  LGPL
  Source module            gst-plugins-bad
  Source release date      2019-05-29
  Binary package           GStreamer Bad Plugins (Ubuntu)
  Origin URL               https://launchpad.net/distros/ubuntu/+source/gst-plugins-bad1.0

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBin
                         +----GstWebRTCBin

Implemented Interfaces:
  GstChildProxy

Pad Templates:
  SRC template: 'src_%u'
    Availability: Sometimes
    Capabilities:
      application/x-rtp
  
  SINK template: 'sink_%u'
    Availability: On request
    Capabilities:
      application/x-rtp
    Type: GstWebRTCBinPad
    Pad Properties:

Element has no clocking capabilities.
Element has no URI handling capabilities.

Pads:
  none

Element Properties:
  name                : The name of the object
                        flags: readable, writable
                        String. Default: "webrtcbin0"
  parent              : The parent of the object
                        flags: readable, writable
                        Object of type "GstObject"
  async-handling      : The bin will handle Asynchronous state changes
                        flags: readable, writable
                        Boolean. Default: false
  message-forward     : Forwards all children messages
                        flags: readable, writable
                        Boolean. Default: false
  connection-state    : The overall connection state of this element
                        flags: readable
                        Enum "GstWebRTCPeerConnectionState" Default: 0, "new"
                           (0): new              - GST_WEBRTC_PEER_CONNECTION_STATE_NEW
                           (1): connecting       - GST_WEBRTC_PEER_CONNECTION_STATE_CONNECTING
                           (2): connected        - GST_WEBRTC_PEER_CONNECTION_STATE_CONNECTED
                           (3): disconnected     - GST_WEBRTC_PEER_CONNECTION_STATE_DISCONNECTED
                           (4): failed           - GST_WEBRTC_PEER_CONNECTION_STATE_FAILED
                           (5): closed           - GST_WEBRTC_PEER_CONNECTION_STATE_CLOSED
  signaling-state     : The signaling state of this element
                        flags: readable
                        Enum "GstWebRTCSignalingState" Default: 0, "stable"
                           (0): stable           - GST_WEBRTC_SIGNALING_STATE_STABLE
                           (1): closed           - GST_WEBRTC_SIGNALING_STATE_CLOSED
                           (2): have-local-offer - GST_WEBRTC_SIGNALING_STATE_HAVE_LOCAL_OFFER
                           (3): have-remote-offer - GST_WEBRTC_SIGNALING_STATE_HAVE_REMOTE_OFFER
                           (4): have-local-pranswer - GST_WEBRTC_SIGNALING_STATE_HAVE_LOCAL_PRANSWER
                           (5): have-remote-pranswer - GST_WEBRTC_SIGNALING_STATE_HAVE_REMOTE_PRANSWER
  ice-gathering-state : The collective gathering state of all ICETransport's
                        flags: readable
                        Enum "GstWebRTCICEGatheringState" Default: 0, "new"
                           (0): new              - GST_WEBRTC_ICE_GATHERING_STATE_NEW
                           (1): gathering        - GST_WEBRTC_ICE_GATHERING_STATE_GATHERING
                           (2): complete         - GST_WEBRTC_ICE_GATHERING_STATE_COMPLETE
  ice-connection-state: The collective connection state of all ICETransport's
                        flags: readable
                        Enum "GstWebRTCICEConnectionState" Default: 0, "new"
                           (0): new              - GST_WEBRTC_ICE_CONNECTION_STATE_NEW
                           (1): checking         - GST_WEBRTC_ICE_CONNECTION_STATE_CHECKING
                           (2): connected        - GST_WEBRTC_ICE_CONNECTION_STATE_CONNECTED
                           (3): completed        - GST_WEBRTC_ICE_CONNECTION_STATE_COMPLETED
                           (4): failed           - GST_WEBRTC_ICE_CONNECTION_STATE_FAILED
                           (5): disconnected     - GST_WEBRTC_ICE_CONNECTION_STATE_DISCONNECTED
                           (6): closed           - GST_WEBRTC_ICE_CONNECTION_STATE_CLOSED
  local-description   : The local SDP description to use for this connection
                        flags: readable, writable
                        Boxed pointer of type "GstWebRTCSessionDescription"
  remote-description  : The remote SDP description to use for this connection
                        flags: readable, writable
                        Boxed pointer of type "GstWebRTCSessionDescription"
  stun-server         : The STUN server of the form stun://hostname:port
                        flags: readable, writable
                        String. Default: null
  turn-server         : The TURN server of the form turn(s)://username:password@host:port
                        flags: readable, writable
                        String. Default: null

Element Signals:
  "pad-added" :  void user_function (GstElement* object,
                                     GstPad* arg0,
                                     gpointer user_data);
  "pad-removed" :  void user_function (GstElement* object,
                                       GstPad* arg0,
                                       gpointer user_data);
  "no-more-pads" :  void user_function (GstElement* object,
                                        gpointer user_data);
  "on-negotiation-needed" :  void user_function (GstElement* object,
                                                 gpointer user_data);
  "on-ice-candidate" :  void user_function (GstElement* object,
                                            guint arg0,
                                            gchararray arg1,
                                            gpointer user_data);
  "on-new-transceiver" :  void user_function (GstElement* object,
                                              GstWebRTCRTPTransceiver* arg0,
                                              gpointer user_data);

Element Actions:
  "create-offer" :  void user_function (GstElement* object,
                                        GstStructure* arg0,
                                        GstPromise* arg1);
  "create-answer" :  void user_function (GstElement* object,
                                         GstStructure* arg0,
                                         GstPromise* arg1);
  "set-local-description" :  void user_function (GstElement* object,
                                                 GstWebRTCSessionDescription* arg0,
                                                 GstPromise* arg1);
  "set-remote-description" :  void user_function (GstElement* object,
                                                  GstWebRTCSessionDescription* arg0,
                                                  GstPromise* arg1);
  "add-ice-candidate" :  void user_function (GstElement* object,
                                             guint arg0,
                                             gchararray arg1);
  "get-stats" :  void user_function (GstElement* object,
                                     GstPad* arg0,
                                     GstPromise* arg1);
  "add-transceiver" :  GstWebRTCRTPTransceiver * user_function (GstElement* object,
                                                                GstWebRTCRTPTransceiverDirection arg0,
                                                                GstCaps* arg1);
  "get-transceivers" :  GArray * user_function (GstElement* object);

Children:
  rtpbin


`
