### ISSUE TITLE
Large scale pose graph optimization

### ISSUE THREAD

**Issue by syncle** [intel-isl/Open3D#367]
Related to #363.

Open3D's built-in pose graph optimizer utilizes Eigen dense matrix solver, which is inefficient for large scale pose graph optimization. Here are todos:

- [x] Replace/improve linear matrix solver 
- [x] Consider using Eigen/Dense for small matrix, Eigen/Sparse for large matrix
- [ ] Testing it with g2o dataset

Useful links:
g2o dataset: https://github.com/RainerKuemmerle/g2o/wiki/File-Format-SLAM-2D

**Comment by SubMishMar** [comment]
The first two points have been more or less addressed and is now in master. I would love to get some leads on how to use open3d for g2o data sets, like the manhattan and the cubicle datasets, etc.

**Comment by qianyizh** [comment]
Can anyone provide some sample files of the g2o dataset?

**Comment by minxuanjun** [comment]
@qianyizh When I reading source code in src/Core/Registration/GlobalOptimization.cpp , I have some question.
 I think code in 225 line that  b.block<6, 1>(id_i, 0).noalias() -=line_process_iter * eT_Info.transpose() * Js is a bug, it should be b.block<6, 1>(id_i, 0).noalias() -=line_process_iter *Js.transpose()* eT_Info.transpose() ;

**Comment by minxuanjun** [comment]
@qianyizh it solve the equation is J.T* inform_matrix * J = -J.T inform_matrix* error, but in code , b = inform_matrix* error* J

**Comment by syncle** [comment]
@minxuanjun: Thanks for the feedback! I think you have a valid point. I also observe some redundant lines that doesn't require transpose actually. For example this lines:
```
Eigen::Vector6d eT_Info = e.transpose() * t.information_;
b.block<6, 1>(id_i, 0).noalias() -=
                line_process_iter * eT_Info.transpose() * Js;
```
could be the following lines:
```
b.block<6, 1>(id_i, 0).noalias() -=
                line_process_iter * Js.transpose() * t.information_ * e;
```
This is what you mean to say, right?

**Comment by minxuanjun** [comment]
@syncle yes

**Comment by syncle** [comment]
Thanks. @minxuanjun for the clarification. I will double-check the equation and do test-run with the real data sets. Stay tuned!

**Comment by germanros1987** [comment]
@syncle should we close this? It seems this won't be happening any time soon

**Comment by germanros1987** [comment]
Time to close this. Let's reconsider this in the future.
