### ISSUE TITLE
undefined reference to symbol 'cublasCreate_v2'  when running open3d::t::pipelines::registration::RegistrationMultiScaleICP

### ISSUE THREAD

**Issue by manhha1402** [intel-isl/Open3D#3671]
Hi,
I built Open3D master branch from source today with the config `cmake -DUSE_SYSTEM_EIGEN3=ON -DBUILD_CUDA_MODULE=ON -DGLIBCXX_USE_CXX11_ABI=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -DUSE_SYSTEM_JPEG=ON ..` and test the function `open3d::t::pipelines::registration::RegistrationMultiScaleICP` and got the errror:
`/usr/bin/ld: /usr/local/lib/libOpen3D_3rdparty_faiss_faiss.a(StandardGpuResources.cpp.o): undefined reference to symbol 'cublasCreate_v2@@libcublas.so.11'`
Do you have any idea how to solve it?
Thank you.

**Comment by reyanshsolis** [comment]
Hi @manhha1402, what are your system configuration and CUDA version?

**Comment by manhha1402** [comment]
Hi @reyanshsolis ,
Thank you for quick reply. Somehow I fixed this linking issues. I tested the code in ROS system, CUDA 11.0, probably it conflicts with other ROS packages.

**Comment by reyanshsolis** [comment]
Thanks, @manhha1402 for using Open3D with different systems. 
Also, Open3D does not have any direct support for ROS integration afaik, so if you are using them together, please let us know if there are any issues/feature requests. 
Thanks.

**Comment by manhha1402** [comment]
Hi @reyanshsolis ,
I am having a problem when writing the TSDF integration in a ROS service. After finishing the TSDF integration, the GPU memory of the TSDFVoxelGrid is not yet release because the ros service is still available. This affects other applications that use GPU. Do you have any idea how to release GPU memory of TSDFVoxelGrid if the program is not finished?

**Comment by reyanshsolis** [comment]
in python you may try `open3d.core.cuda.release_cache()`
or in C++ you may try `open3d::core::cuda::ReleaseCache()`
to manually release CUDA memory. 

Also may you please share how you got Open3D to work with ROS properly? It would be very helpful information.

Thanks!

**Comment by manhha1402** [comment]
I managed to solve the problem with the build flag : `-DBUILD_CACHED_CUDA_MANAGER=OFF`. Not sure how it works ... I will try your solution also.
For ROS, it's quite straightforward. I dont see any problem when using Open3D in ROS so far
