### ISSUE TITLE
TSDFVoxelGrid GPU, ExtractSurface, GPU Memory issue

### ISSUE THREAD

**Issue by Anzzy30** [intel-isl/Open3D#3676]
Hello,

I'm working on a robot exploration system with tsdf mapping on GPU.

Setup:

    Open3D build from source (recently cloned)
    cuda 10.1
    Ubuntu 20.04.-
    Laptop with Nvidia 1070
    C++

During the exploration experiment, I use **ExtractSurfacePoint** and/or **ExtractSufaceMesh** each 20 seconds.
When one of the two function is called the **VRAM increase slightly and seemingly is not release**.

Two similar run: one with ExtractSurface.. and the other without extraction here is the VRAM after 15min
[with ExtractSurface..] **~4350MiB (gradually increases)**
[without ExtractSurface..] **~2533MiB (do not increases)**

I could try to plot the VRAM if needed.

**Comment by stotko** [comment]
@Anzzy30 Did you set a value to the CMake variable `BUILD_CACHED_CUDA_MANAGER` when building Open3D? If not, the default is `ON` which means that Open3D internally uses a cached memory manager for CUDA. This manager delays freeing the allocated memory to the end of the program and, instead, tries to reuse the set of allocated memory blocks. So your observations are in line with its behavior.

You could try to disable the cached memory manager by adding `-DBUILD_CACHED_CUDA_MANAGER=OFF` to CMake when building Open3D.

**Comment by Anzzy30** [comment]
Thx, I didn't know about this option.
