### ISSUE TITLE
How to keep  viewer window open?

### ISSUE THREAD

**Issue by mingyangpeng** [intel-isl/Open3D#3708]
Hello, I need help that I want to see the change state of point cloud before and after processing, how to keep the previous window open and create a new window. I didn't find any example.

**Comment by ssheorey** [comment]
Hi @mingyangpeng  check out this example for visualizing updating point clouds in multiple windows:

https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/multiple-windows.py
