### ISSUE TITLE
How to draw multiple pointcould successfully one after the other in the user interface

### ISSUE THREAD

**Issue by bilel-bj** [intel-isl/Open3D#3711]
I want to build an application that:

1. It has a file selection menu to select two point clouds.
2. A button:"ICP" that starts the ICP registration algorithm between the two algorithms.
3. After pushing the ICP button:
4. it will show the two pointcloud registered and a text zone that displays the transformation matrix.

Any idea on how to do that

**Comment by ssheorey** [comment]
Hi @bilel-bj check out this C++ registration example:

https://github.com/intel-isl/Open3D/blob/master/examples/cpp/TICPOdometry.cpp

Python GUi examples are in the `examples/python/gui` folder
