### ISSUE TITLE
PackageNotFoundError (Python package for Apple M1 ARM)

### ISSUE THREAD

**Issue by meixuan-stephanie** [intel-isl/Open3D#3717]
**Describe the bug**

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - open3d

Current channels:

  - https://conda.anaconda.org/open3d-admin/osx-arm64
  - https://conda.anaconda.org/open3d-admin/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**To Reproduce**

type **conda install -c open3d-admin -c conda-forge open3d** into terminal
Laptop: Mac M1(Silicon chip)

**Expected behavior**
open3d should be installed

**Screenshots**

**Environment (please complete the following information):**

- Operating system:  Mac OS Big Sur 11.4
- Python version: 3.8.10
- Open3D version: latest(0.13.0)
- Is this remote workstation?: no
- How did you install Open3D?: Miniforge
- Compiler version (if built from source): NA

**Additional context**

**Comment by ssheorey** [comment]
Open3D does not have a build for Apple M1 yet.
Related: #2675

**Comment by meixuan-stephanie** [comment]
For those wish to install open3d on your Mac M1. Rosetta would be the best option.
Procedure :
 1. You may split your terminal into two. One is running using Rosetta and the other is running natively. There are quite some posts on how to do that. After splitting your terminal. Please open the one running with rosetta and type arch to double check. Once it outputs i386, you are on the right track.
 2. type python3 -m venv env and then source env/bin/activate to activate a virtual environment and then go ahead to install by using command pip install open3d. If you need note book and other libraries, pip commands will get you there. You are then all set.
