### ISSUE TITLE
Request a proper display of colored gui.Label3D bounding box meta info in o3d gui

### ISSUE THREAD

**Issue by Eralien** [intel-isl/Open3D#3718]
I have been trying to visualize my own pointcloud sequence data, using the  `open3d._ml3d.vis.visualize.Visualizer`in **Linux**. I am using pip installed open3d in python=3.8, ubuntu 18.04.

I implemented my own class inherited from [`open3d._ml3d.datasets.base_dataset.BaseDataset`](https://github.com/intel-isl/Open3D-ML/blob/15fefa7364a312e562379283dc191ecb4c74c221/ml3d/datasets/base_dataset.py#L15) and `BaseDatasetSplit`following the example [customdataset.py](https://github.com/intel-isl/Open3D-ML/blob/15fefa7364a312e562379283dc191ecb4c74c221/ml3d/datasets/customdataset.py), and called the [`Visualizer.visualize_dataset`](https://github.com/intel-isl/Open3D-ML/blob/2638375c7a326a2f76b973ca0e11cb6696808284/examples/visualize.py) method. The plotting of bounding boxes labels/info were not what I expected. My implementation was based on the SemanticKitti and NuScenes visualization impl.

The problems are:

1. **Unable to show bbox meta information**. The [`o3d._ml3d.vis.boundingbox.BoundingBox3D`](https://github.com/intel-isl/Open3D-ML/blob/200bee315a55772a9b40f1304d9165242f896786/ml3d/vis/boundingbox.py)  constructor implies that a user-defined string \p `meta` can be initialized, and \p `show_meta` is the proper way to show it. Yet the `open3d._ml3d.vis.visualize.Visualizer` calls `BoundingBox3D.create_lines` static method, which only returns a `o3d.geometry.LineSet` object. There was no text shown.
2. **Unable to change the color of the [`Label3D`](http://www.open3d.org/docs/release/python_api/open3d.visualization.gui.Label3D.html#open3d-visualization-gui-label3d)**.  Method `add_3d_label` returns a `Label3D` object, and I found no way I can change its shown color. I tried to call `Label3D.color.set_color` which could change the color memory but not the label color shown.

**Comment by Eralien** [comment]
This issue is probably better to ask under [intel-isl/Open3D-ML](https://github.com/intel-isl/Open3D-ML).

**Comment by Nasrudin78** [comment]
You can change labelling color by applying this:

```
            label_position = [(box_min[0] + box_max[0]) / 2,
                            (box_min[1] + box_max[1]) / 2,
                            box_max[2]]
            label3d = self.widget.add_3d_label(label_position, f"Track #{track_id}")
            label3d.color = gui.Color(r=color[0], g = color[1], b = color[2], a = 1.0)
```
