### ISSUE TITLE
Need C++ functions for  reading and writing SelectionPolygonVolume from and to json file

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#3734]
Hello,

I want to write and read SelectionPolygonVolume to and from json file. In Python  there is one for reading

`open3d.visualization.read_selection_polygon_volume
`
But I cannot find the corresponding functions in C++. Can any one give me an example how to do that?

Thank you very much!

**Comment by sushidelivery** [comment]
Hello,
I can't find the function either. If you've done it, can you, please, share the snippet?
Thanks!
