### ISSUE TITLE
Write 2 point clouds as 1

### ISSUE THREAD

**Issue by feersantana5** [intel-isl/Open3D#3756]
Is there any way to save the point cloud I get from o3d.visualization.draw_geometries([inliner_cloud, outlier_cloud]) ??

I can save both individually using o3d.io.write_point_cloud but not the combination

**Comment by hduonggithub** [comment]
cloud_all = inliner_cloud + outlier_cloud
o3d.io.write_point_cloud("path", cloud_all)
