### ISSUE TITLE
Could not find CPPABI_LIBRARY using the following names: c++abi (when using GCC 6.3.0)

### ISSUE THREAD

**Issue by samfux84** [intel-isl/Open3D#3762]
**Describe the bug**
On http://www.open3d.org/docs/release/compilation.html#system-requirements it is stated that a C++14 Compiler is required to build open3d, but when trying to configure the build with CMake 3.20.3 and GCC 6.3.0, I get the error message

```
 CMake Error at 3rdparty/find_dependencies.cmake:971 (find_library):
   Could not find CPPABI_LIBRARY using the following names: c++abi
 Call Stack (most recent call first):
   CMakeLists.txt:613 (include)

 Configuring incomplete, errors occurred!
```

I am not building the software with LLVM, therefore I don't understand why a library from LLVM is required to build the software with GCC. GCC 6.3.0 has complete support for C++14, so this should be sufficient.

**To Reproduce**

1. check out source code from github
2. run configure in the CMake GUI (ccmake)

**Expected behavior**
All dependencies (compiled from source, not installed via package manager from the OS) should be found

**Environment (please complete the following information):**

- Operating system: CentOS 7.9
- Python version: 3.8
- Open3D version: 0.13.0
- Is this remote workstation?: yes
- How did you install Open3D?: source
- Compiler version (if built from source): GCC 6.3.0

**Comment by ssheorey** [comment]
Please install build dependencies:
http://www.open3d.org/docs/release/compilation.html#install-dependencies
The package names will be different for CentOS. Please let us know the correct package names for CentOS so we can update the documentation.

`libc++` is needed by the `filament` library that Open3D uses for visualization. Please see here for their build instructions:
https://github.com/google/filament/blob/main/BUILDING.md

We provide a pre-built filament library to avoid the need for `clang`, but `libc++` is still needed.

**Comment by samfux84** [comment]
@ssheorey Thank you for your reply. As described in my initial post, I compiled all dependencies from source code, so I can't provide you any package names for CentOS RPMs.

It would be nice if the documentation of Open3d would contain a list of dependencies (not names of RPM packages hidden in a script), such that people interested in installing the software see right away what is required.

> We provide a pre-built filament library to avoid the need for clang, but libc++ is still needed.

This does not really help. I don't have a recent LLVM installation so it does not matter if  I need libc++ or libc++ and clang. I don't have any of the two. So your list of dependencies should also mention LLVM.

Is it possible to  build Open3d without filament? If yes, which is the most recent version of Open3d that does not use filament?

I am installing the software on the HPC cluster of our university on request of a cluster user. I will give the installation a last try today and if this fails then I will tell the user that I cannot provide the software on our cluster.

So feel free to close this request.

Best regards

Sam

**Comment by ssheorey** [comment]
Here is a list of build dependencies for Open3D (Ubuntu package names. CentOS packages are named differently):
```
dependencies=(
    # Open3D deps
    xorg-dev
    libglu1-mesa-dev
    python3-dev
    # Filament build-from-source deps
    libsdl2-dev
    libc++-7-dev
    libc++abi-7-dev
    ninja-build
    libxi-dev
    # ML deps
    libtbb-dev
    # Headless rendering deps
    libosmesa6-dev
    # RealSense deps
    libudev-dev
    autoconf
    libtool
)
```

Note that `llvm` or `clang` is **not** a requirement, though `libc++` is. The pre-built `filament` library is automatically downloaded during the build process, so you don't need to install it. v0.9.0 was the last Open3D to not use `filament`.

from here:
https://github.com/intel-isl/Open3D/blob/4d900f02ec6272c144a46832d2c6d4867848a222/util/install_deps_ubuntu.sh#L16

We will add this to the build docs for greater clarity.

**Comment by samfux84** [comment]
Thank you for your reply.

libc++ is part of llvm (https://libcxx.llvm.org/). I tested the prebuilt filament library from google, and it does not work on CentOS 7.9 because it requires a newer glibc than CentOS 7.9 has.

I have now installed v0.9.0.

**Comment by adamjstewart** [comment]
Hey @samfux84, fancy meeting you here! I actually recently added a [Spack package for Open3D](https://github.com/spack/spack/pull/27577). I just ran into the same issue as you and adding a dependency on LLVM fixed it.

@ssheorey the apt/yum installation instructions aren't particularly helpful on systems where users don't have admin privileges. In my case, I'm building on the Frontera supercomputer and have to build all dependencies myself.

**Comment by samfux84** [comment]
Hi @adamjstewart ,

Happy new year. Nice to meet you here. I just saw in the top500 list that Frontera is running CentOS 7 On ETH's Euler cluster (not listed in the top500, but around 5-6 PFLOPS), we are running CentOS 7.9, so we often run into the same or similar issues.

I am not sure if adding the LLVM dependency will be sufficient to build Open3D versions > 0.9.0. I think that this would require a package for google filament (https://github.com/google/filament). The precompiled version requires a too new GLIBC for CentOS 7.x, so compiling filament from source seems necessary when you would like to install versions newer than 0.9.0:

https://github.com/google/filament/blob/main/BUILDING.md

For the moment I stay with version Open3D version 0.9.0 but at some point I will have to install a recent LLVM version and build googles filament rendering engine.

**Comment by adamjstewart** [comment]
Yep, I'm having that exact issue in https://github.com/isl-org/Open3D/issues/4570, will debug this there.

**Comment by jinfagang** [comment]
for more decent g++, it was no longer support:

``` sudo apt install libc++11-dev libc++abi11-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libc++11-dev
E: Unable to locate package libc++abi11-dev

```
