### ISSUE TITLE
Conda-forge feedstock

### ISSUE THREAD

**Issue by gsakkis** [intel-isl/Open3D#3775]
The [conda_meta](https://github.com/intel-isl/Open3D/tree/master/python/conda_meta) folder is not a proper conda recipe, it is only usable via `make conda-package`. Also it only installs the Open3D Python bindings; the Open3D core library is built by `cmake`. 

So I've been trying to create a standalone conda recipe for (a fork of) Open3D but I'm hitting several issues. It would be great if there was a conda-forge feedstock repo I can clone.

**Comment by ssheorey** [comment]
Hi @gsakkis sorry, but we are planning to deprecate `conda` packages, since Python wheels (installed with `pip`) work in `conda` environments as well. Do you have a use case where `pip` would not work?

**Comment by gsakkis** [comment]
Hi @ssheorey, the use case is building a (hopefully temporary) fork of Open3D and uploading it to a personal conda channel. As long there is a reproducible way to build (e.g. in a Docker container) a wheel from the repo, I guess the same could be achieved with a private PyPI index (even if less convenient that using the conda-forge infrastructure).

**Comment by ssheorey** [comment]
The best way would be to use Github Actions (CI). The existing build-wheel action builds both a conda package and a pip wheel and you can enable that in your repo as well. The conda package and pip wheel are available to download after the CI run completes.

https://github.com/intel-isl/Open3D/blob/9a49100bce12589de5410546995f59dbfa23e990/.github/workflows/ubuntu.yml#L170

Alternately, you can create a Dockerfile easily from these 3 files:

`util/install_ubuntu_deps.sh`: Ubuntu packages needed for building.
`.github/workflows/ubuntu.yml`: Sets up build configuration and drives the build.
`util/ci_utils.sh`: Bash functions from here are called during the build.

**Comment by gsakkis** [comment]
Thanks @ssheorey, that's exactly the approach I'm following after giving up on writing a conda recipe - a trimmed down, modified version of the `ubuntu.yml` GH action. 

Closing this issue as conda will be deprecated.
