### ISSUE TITLE
Get python module binaries from CI builds

### ISSUE THREAD

**Issue by takanokage** [intel-isl/Open3D#390]
In the future we'll need to extend #388 to:
- Python 2.7+ and 3.0+ 32bit and 64bit in order to cover at least all (4) options on Windows 64bit
- Ubuntu 2.7+ and 3.0+ (TravisCI)
- MacOS (TravisCI)

**Comment by martinResearch** [comment]
this tool could help https://github.com/joerick/cibuildwheel.

**Comment by takanokage** [comment]
I think that's a great tool.
Let me ask you whether this would work specifically for our case:

As you've noticed we're building the python module from source. We're actually building one binary per OS per Python version per architecture (32bit, 64bit) where it matters. That's one CI session per binary (4 AppVeyor sessions, 2 Ubuntu, 1 Mac).

Which part does your tool handle? Can your tool help us build and pack all these together?

**Comment by takanokage** [comment]
Ok, your understanding on how this works matches my own: build the binaries with CI then download all the binaries locally before pypi packaging. In which case I don't need that tool, we already have a structure in place for pypi packaging.

A few links about Travis CI artifacts (saved here for later usage):
https://docs.travis-ci.com/user/deployment/releases/
https://docs.travis-ci.com/user/uploading-artifacts/
https://blog.travis-ci.com/2012-12-18-travis-artifacts

**Comment by syncle** [comment]
@yxlao: we have built CIs for this, can you double check on this issue?

**Comment by yxlao** [comment]
@syncle I believe this has not yet been addressed. 
1. Currently, Travis CI is not storing artifacts after each build for ubuntu and mac.
2. If we were to make the compiled python module useful (for pip and conda distribution), we'll need to add build with all supported python versions (2.7, 3.5, 3.6). However, this has not been done in Travis. 
Do you recommend moving up the priority of this issue?
