### ISSUE TITLE
Use a faster sparse linear solver (SuiteSparse)

### ISSUE THREAD

**Issue by qianyizh** [intel-isl/Open3D#405]
Currently we use Eigen built-in functions as the sparse linear solver. However, for large linear systems, it is not as fast as the state-of-the-art sparse linear solvers such as [CHOLMOD in SuiteSparse](http://faculty.cse.tamu.edu/davis/suitesparse.html). See [this benchmark](https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html#title7). (In my experience, CholmodSupernodalLLT solver can be orders of magnitude faster than Eigen's built-in solver for large linear problems that take seconds to solve.)

As an external reference point, [Ceres Solver](http://ceres-solver.org/installation.html) prefers SuiteSparse over Eigen, written in its installation guide.

There are downsides of SuiteSparse too. First, [it is not very compatible with CMake](https://github.com/jlblancoc/suitesparse-metis-for-windows), this makes Windows support of SuiteSparse a pain. Second, it is under the LGPL license, which is less permissive than MIT. I am not sure how to work with this.

So far most problems in Open3D that require sparse linear solver are not too big, so Eigen built-in solver works. But speed is still an issue and we would like to hear suggestions regarding how to improve on this.

I have a couple of ideas but none of them are promising, including:
 * Make Ceres Solver or SuiteSparse as a dependency and ask the user to install it before using Open3D.
 * Similar to Ceres, the out-of-the-box version of Open3D uses Eigen built-in solver. For users interested in performance, we offer the option of installing SuiteSparse by the user and link to it. This requires some eng work and a sophisticated guide in the document.
 * Call python function ``scikits.sparse.cholmod`` from cpp code, when ``scikits`` is installed.
 * Use ``csparse``. It is simpler and more friendly to CMake, than CHOLMOD. It is still quite fast, although not as fast as CHOLMOD.

**Comment by saedrna** [comment]
In mac and linux, suitesparse is not an issue, and in Windows vcpkg already ports suitesparse and cmake is supported. The only drawback is only VS 2015 and later version are supported.

**Comment by qianyizh** [comment]
Wow, I did not know vcpkg (https://github.com/Microsoft/vcpkg). It looks like a very promising package management system for Windows, which can solve lots of our headaches regarding dependency.

@syncle @takanokage mind to check it out?

**Comment by syncle** [comment]
I just tried. In summary, vcpkg is awesome tool to build/install unix libraries on windows. It also provides cmake targets to be used with VS2015+. 

The following is my log to build/install SuiteSparse from scratch.
```
> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg
> bootstrap-vcpkg.bat
> vcpkg install suitesparse:x64-windows
The following packages will be built and installed:
  * clapack[core]:x64-windows
  * openblas[core]:x64-windows
    suitesparse[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: openblas:x64-windows
Building package openblas[core]:x64-windows...
-- Downloading https://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz...
-- Extracting source C:/git/vcpkg/downloads/xianyi-OpenBLAS-v0.2.20.tar.gz
-- Using source at C:/git/vcpkg/buildtrees/openblas/src/v0.2.20-7d967f7fc4
-- Applying patch C:/git/vcpkg/ports/openblas/install-openblas.patch
-- Applying patch C:/git/vcpkg/ports/openblas/whitespace.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package openblas[core]:x64-windows... done
Installing package openblas[core]:x64-windows...
Installing package openblas[core]:x64-windows... done
Elapsed time for package openblas:x64-windows: 5.435 min
Starting package 2/3: clapack:x64-windows
Building package clapack[core]:x64-windows...
-- Downloading http://www.netlib.org/clapack/clapack-3.2.1-CMAKE.tgz...
-- Extracting source C:/git/vcpkg/downloads/clapack-3.2.1.tgz
-- Applying patch C:/git/vcpkg/ports/clapack/use-other-blas-and-install-include.patch
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package clapack[core]:x64-windows... done
Installing package clapack[core]:x64-windows...
Installing package clapack[core]:x64-windows... done
Elapsed time for package clapack:x64-windows: 1.584 min
Starting package 3/3: suitesparse:x64-windows
Building package suitesparse[core]:x64-windows...
-- Warning: Dynamic building not supported yet. Building static.
-- Downloading http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.5.tar.gz...
-- Downloading https://github.com/jlblancoc/suitesparse-metis-for-windows/archive/v1.3.1.zip...
-- Extracting source C:/git/vcpkg/downloads/suitesparse-metis-for-windows-1.3.1.zip
-- Extracting source C:/git/vcpkg/downloads/SuiteSparse-4.5.5.tar.gz
-- Applying patch C:/git/vcpkg/ports/suitesparse/fix-install-suitesparse.patch
-- Applying patch C:/git/vcpkg/ports/suitesparse/remove-debug-postfix.patch
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package suitesparse[core]:x64-windows... done
Installing package suitesparse[core]:x64-windows...
Installing package suitesparse[core]:x64-windows... done
Elapsed time for package suitesparse:x64-windows: 1.707 min

Total elapsed time: 8.725 min

The package suitesparse:x64-windows provides CMake targets:

    find_package(SuiteSparse CONFIG REQUIRED)
    # Note: 10 target(s) were omitted.
    target_link_libraries(main PRIVATE amd btf klu ldl)


> vcpkg integrate install
```

**Comment by takanokage** [comment]
One idea is to enable Open3D user to pick and chose the solver from a list of supported solvers.
I'm a bit against the idea of replacing Eigen with another solver because I can imagine no single solver is perfect for everyone.
This could be based on a plugin interface. A plugin would need to be implemented for each solver in order to "enable" it in Open3D.
