### ISSUE TITLE
Add functions to accept more RGB-D input formats (different resolution, different view, etc)

### ISSUE THREAD

**Issue by qianyizh** [intel-isl/Open3D#44]
As discussed in #42 , in the future, we should add conversion function to covert different size and different view point RGB-D image pairs. Quote:

There are some minor formatting issues. Others are good.

I have an additional question: what if the input color image is of different size of depth image? There are some use cases:

1. We use Primesense to capture a higher resolution image stream (my color mapping paper).
2. We use RealSense DS4 to capture a higher resolution image stream.
3. We use occipital sensor with an iPhone camera.

We don't need to handle them immediately. But I think we should leave a note at the class definition of RGBDImage, saying that it is for a pair of registered color and depth images, viewed from the same view, of the same resolution. If you have other format, convert it first.

In the future, we can provide similar helper functions for other kinds of input (as long as the input resolution and the calibrated extrinsic matrix is given). But it is future work.

**Comment by sk9331657** [comment]
@yxlao  Can please guide me what needs to be done in documentation part ??

**Comment by yxlao** [comment]
@sk9331657 please redirect the docs discussion to a new github issue or through discord, thanks
