### ISSUE TITLE
Poisson Sampling of meshes for point cloud generation

### ISSUE THREAD

**Issue by Hippogriff** [intel-isl/Open3D#470]
Is it possible to sample meshes using Poisson sampling algorithm, or something similar? It will also be great to have a correspondence routine that gives correspondence between point from the point cloud and face on the mesh.

**Comment by syncle** [comment]
Thanks @Hippogriff for the suggestion. We are preparing other new features, so this might not be implemented in the near feature. We are always welcome if you are willing to contribute. :)

**Comment by syncle** [comment]
I just read this https://www.cct.lsu.edu/~fharhad/ganbatte/siggraph2007/CD2/content/sketches/0250.pdf, but it is not clear how to extend this idea for 3D mesh. Here is another good example http://devmag.org.za/2009/05/03/poisson-disk-sampling/, but it is for 3D volumes. @Hippogriff: you suggested to resampling points on surface of the mesh, right?

**Comment by syncle** [comment]
Hi @Hippogriff. Can I ask if you already had worked on this? I think this is very useful feature so I am considering to work on this.

**Comment by Hippogriff** [comment]
@syncle hI! I have not worked on this. I just know the basic theory.

**Comment by pavan4** [comment]
Hi, just a quick suggestion - You can use libigl to sample the mesh and generate a pointcloud. I managed to do it. 

Here is a sample from libigl: 

https://github.com/libigl/libigl-examples/tree/master/randomly-sample-mesh

**Comment by YouYue123** [comment]
PCL has a similar implementation here. Hope this helps. 

https://github.com/PointCloudLibrary/pcl/blob/master/tools/mesh_sampling.cpp

**Comment by griegler** [comment]
Implemented in #955
