### ISSUE TITLE
Add coordinate axis in the visualization

### ISSUE THREAD

**Issue by DKandrew** [intel-isl/Open3D#483]
**Is your feature request related to a problem? Please describe.**
This feature request is related to the cropping of the point cloud. I don't understand the data in cropped.json Why are there so many "bounding_polygon"? 
There is currently no a efficient way for me to crop the point cloud, so I guess I have to do it myself. Therefore, understanding the coordinate axis become very important in this case. 

**Solution**
Add an option for use to display the coordinate axis in the visualization. User can turn it on/off manually. Currently a workaround is to add the coordinate axis manually at a customized position like here: http://www.open3d.org/docs/tutorial/Basic/visualization.html

I know it is not an elegant solution. Please reply for any improvement or suggestion. Thanks.

**Comment by syncle** [comment]
This is a valid request. It would be good if it also visualize a bounding box of the scene.

**Comment by germanros1987** [comment]
We will work on this for the new visualization system.

**Comment by germanros1987** [comment]
Done as part of 0.10. Please have a look at the new Open3D App added in the 0.10  release.

**Comment by li2508264** [comment]
so,how to visualize a bounding box of the scene?

**Comment by votecoffee** [comment]
Coordinate axis:
```
viewer = open3d.visualization.Visualizer()
viewer.create_window()
for geometry in geometries:
    viewer.add_geometry(geometry)
opt = viewer.get_render_option()
opt.show_coordinate_frame = True
opt.background_color = np.asarray([0.5, 0.5, 0.5])
viewer.run()
viewer.destroy_window()
```

**Comment by lucasjinreal** [comment]
I want remove it, how to do????

**Comment by jediofgever** [comment]
is this coordinate frame placed according to the minimal bounding box of the added geometries? 

The frame does not seem at the right location w.r.t the expected location in my data. 

The coordinate frame is off in the y-axis, should have been in the middle but it stands on the left. 

![image](https://github.com/isl-org/Open3D/assets/18460336/7514990c-fec0-4f3d-a793-7efcf43687ec)

**Comment by InigoMoreno** [comment]
> is this coordinate frame placed according to the minimal bounding box of the added geometries?
> 
> The frame does not seem at the right location w.r.t the expected location in my data.
> 
> The coordinate frame is off in the y-axis, should have been in the middle but it stands on the left.
> 
> ![image](https://user-images.githubusercontent.com/18460336/256874507-7514990c-fec0-4f3d-a793-7efcf43687ec.png)

Yes, it seems like that
