### ISSUE TITLE
16 to 32 Bit Depth Image Copy as TSDF Workaround

### ISSUE THREAD

**Issue by nigeljw1** [intel-isl/Open3D#502]
There really should be 16 bit uint depth format support for TSDF, as this is the most common format, but it wasn't added as part of pull request https://github.com/IntelVCL/Open3D/pull/450

Because of this, an array copy is required to reshape for the input into the TSDF integrate function which isn't optimal. I am actually having trouble doing the copy:

```
three::Image depth_16bit;
three::ReadImage(file_name, depth_16bit);

three::Image depth_32bit;
depth_32bit.PrepareImage(depth.width_, depth.height_, 1, 4);

uint16_t* depth_data_src = reinterpret_cast<uint16_t*>(depth_16bit.data_.data());
uint32_t* depth_data_dst = reinterpret_cast<uint32_t*>(depth_32bit.data_.data());

for (int32_t j = 0; j < depth.width_*depth.height_; ++j) {
      depth_data_dst[j] = static_cast<uint32_t>(depth_data_src[j]);
}
```

I am not sure what is wrong with this copy, but I get the following result:

![depth32bit](https://user-images.githubusercontent.com/42150597/43955904-0830f7f4-9c9a-11e8-9e77-c730db3254ce.png)

I tried matching the copy exactly from the issue https://github.com/IntelVCL/Open3D/issues/417 but it still doesn't work:

```
for (int32_t j = 0; j < depth.width_*depth.height_; ++j) {
    uint8_t *src = (uint8_t *)(depth.data_.data() + j * sizeof(uint16_t));
    uint8_t *dst = (uint8_t *)(depth_32bit.data_.data() + j * sizeof(uint32_t));
    dst += sizeof(uint16_t); // I tried with and without this offset, and it still doesn't work
    std::memcpy(dst, src, sizeof(uint16_t));
}
```

I would prefer not to have to do this conversion at all, but I would happy with just getting the copy to work for now. Does anyone see anything obvious about why my copy does not work as expected?

Irrespective of the copy, should the input into TSDF integrate be a floating point value? Should it be this instead:

```
float* depth_data_dst = reinterpret_cast<float*>(depth_32bit.data_.data());
uint16_t* depth_data_src = reinterpret_cast<uint16_t*>(depth.data_.data());

for (int32_t j = 0; j < depth.width_*depth.height_; ++j) {
    depth_data_dst[j] = static_cast<float>(depth_data_src[j]);
}

std::shared_ptr<three::RGBDImage> rgbd = three::CreateRGBDImageFromColorAndDepth(color, depth_32bit);
volume.Integrate(*rgbd, intrinsics, pose);
```

Any help is very much appreciated!

**Comment by syncle** [comment]
Hi @nigeljw1. You don't need to do this by yourself. Consider to use ``ConvertDepthToFloatImage``. This will transform uint16 image into float type image. 

TSDF integrate function takes float type color image + float type depth image. ``CreateRGBDImageFromColorAndDepth`` will transform [8bit 3channel rgb image + 16bit depth image] or [16bit gray image + 16bit depth image] into [float type color image + float type depth image]. Actually ``CreateRGBDImageFromColorAndDepth`` internally utilizes ``ConvertDepthToFloatImage``, so you can just use  ``CreateRGBDImageFromColorAndDepth``.

Please also check this usage case:
https://github.com/IntelVCL/Open3D/blob/ef042a6c50e54c4bb56ccb4657a745c9b38c1b7f/src/Experimental/IntegrateRGBD.cpp#L103-L112
it just reads the aforementioned format, transform them into float type images, and pass the images to the integration.

**Comment by nigeljw1** [comment]
Thanks for the information!

I would really like to understand why the depth array copy failed, but currently I can work around it as you mentioned. I was getting an unsupported format error from the Integrate call, which I assumed was depth, but it was actually because I didn't pass false into CreateRGBDImageFromColorAndDepth for color intensity float conversion, which isn't supported by the Integrate function.

I would really prefer for it to be possible to skip the ConvertDepthToFloatImage in CreateRGBDImageFromColorAndDepth. This is currently called even if the image is already in a float format. The type cast should really happen at integrate time to avoid the array copy. The array copy isn't really necessary and it is a huge performance hit.
