### ISSUE TITLE
Fails to build without LDFLAGS=-pthread

### ISSUE THREAD

**Issue by yurivict** [intel-isl/Open3D#510]
Found this problem on FreeBSD 11.2.
Version 0.2.

**Comment by syncle** [comment]
Thanks! Do you think we need to add the flag in src/CMakeLists.txt?

**Comment by yurivict** [comment]
> Thanks! Do you think we need to add the flag in src/CMakeLists.txt?

Yes.

**Comment by qianyizh** [comment]
I will try to duplicate it in virtual environment and fix it.

**Comment by qianyizh** [comment]
@yurivict thanks for the bug report.

**Comment by syncle** [comment]
Any updates @qianyizh?

**Comment by qianyizh** [comment]
I got busy and did not follow up. @yxlao can you take a look at op?

**Comment by syncle** [comment]
This issue have not been addressed for a long time. @yxlao: any updates?

**Comment by yxlao** [comment]
ok, I'll try it on FreeBSD soon

**Comment by germanros1987** [comment]
Unfortunately, we don't have the bandwidth to support freeBSD tests.
