### ISSUE TITLE
[Question] return points obtained by cropping

### ISSUE THREAD

**Issue by gkeechin** [intel-isl/Open3D#522]
Hello, Im reading through the current documentation, I would like to clarify if there's any existing way to obtain the points that have been cropped as a return statement from `return vis.get_picked_points()` instead of saving them into a `.ply` file?

As of now the code : 
```
vis = VisualizerWithEditing()
vis.create_window()
vis.add_geometry(pcd)
vis.run() # user picks points
vis.destroy_window()
return vis.get_picked_points()
```

only return points selected by individual picking.

**Comment by syncle** [comment]
HI @gkeechin. I think this is the relevant example for you: http://www.open3d.org/docs/tutorial/Basic/pointcloud.html#crop-point-cloud

**Comment by gkeechin** [comment]
Thanks for your reply @syncle , Im interested in the manual cropping of points, such as the polygonal or box clipping done with the users' mouse after entering `VisualizerWithEditing()` mode.

As of now, if I were to press `k`, draw a crop selection area and press `c`, it will offer to save the points as a `.ply` file. Is there a way to get the points as an array to return?

**Comment by ibrahimLearning** [comment]
@syncle 
Sorry for comment in the closed issue.
After changing VisualizerWithEditing avd Visualizer, how can I use it in my installed open3d on Anaconda?

**Comment by ArchakGoel** [comment]
> @syncle Sorry for comment in the closed issue. After changing VisualizerWithEditing avd Visualizer, how can I use it in my installed open3d on Anaconda?

@AI-ML-Enthusiast  were you able to find a solution to the integration issue with custom open3d? I could find this http://www.open3d.org/docs/release/compilation.html but not sure how this would work with Anaconda.
