### ISSUE TITLE
[Question] Visualizing RGB image with 3D points marked on it

### ISSUE THREAD

**Issue by gilsm** [intel-isl/Open3D#525]
I want to display an image relating to a 3D scene I am analyzing 
Further more I would like to select pixels on the image corresponding to the scene
I have the pixels location on the image and would like to use open3D utilities to display it and the relevant pixels
Is it possible?

**Comment by syncle** [comment]
Drawing points are not implemented in Open3D yet. For the quick solution, I would like to recommend opencv or mathplotlib.

**Comment by qianyizh** [comment]
Can you describe your use case in details?
Open3D can render images, but it is very limited function - it just pastes the image in the middle of the screen.
You can, however, convert an image to a point cloud and render the point cloud. This way you can pick points (pixels) and render them as needed.
I need to understand your use case more.

**Comment by richipower** [comment]
Hello, i am trying to do something similar, i created a pointcloud from a scene, and i have an image of that scene (2D) looking from above, i need to pick the points on the pointcloud, and pick also the same points in the 2D image to make a "mapping" of the values, so if the points in the cloud are valid, obtain the color from the 2D image.. is there a function in open3d that maps 2D-3D values?

**Comment by gilsm** [comment]
Hi
I did not solve this eventually

**Comment by qianyizh** [comment]
@richipower there is no off-the-shelf mapping function. But I think it is not difficult to write one? E.g., you can have a w*h image, then create a point cloud, then create a w*h mapping function that map pixels to the point index in the point cloud.
