### ISSUE TITLE
Remove previously added geometry from the Visualizer

### ISSUE THREAD

**Issue by LossOfHumanIdentity** [intel-isl/Open3D#543]
Hello, 

How do you remove a previously added geometry from Open3D `Visualizer`?

I've searched the documentation but am not able to find any utility that would accomplish the task. 

I am trying to create a **dynamic PLY Visualizer** in a Python environment: let's say I have 2 different PLY point clouds and want to visualize each one of them, for a specified interval of time, one after the other in the same Visualizer. The approach would be: 

- Read Point Cloud 1
- Add it to the Visualizer
- Display it for 5 seconds
- Remove Point Cloud 1 from the Visualizer

- Read Point Cloud 2 
- Add it to the Visualizer
- Display it for 5 seconds
- Remove Point Cloud 2 from the Visualizer

How could this task being accomplished? 

Thank you a lot in advance.

**Comment by qianyizh** [comment]
There is currently no way to do it with Python interface. You can do it in C++ interface.

However, I think I intentionally hid this type of behavior. One reason is that when you render, you need to set up a view. Currently, the default view is computed from the bounding box of the added geometries. Thus dynamically adding or removing geometry from Visualizer requires dynamically maintaining the view, which is not implemented yet. So this type of behavior is discouraged and hidden from the python interface.

**Comment by bigsheep2018** [comment]
Hello @qianyizh,

Is it possible to remove previously added geometry in python now?
I guess there is a branch of people needing to work with sequence data.
Please add these kind of feature into open3d.

Thanks.

**Comment by syncle** [comment]
I was thinking about this. Technically, we may can link a geometry with a name so that we can remove specific geometry from the visualizer. @qianyizh: we may can provide an option, so that user can update view after removing the geometry.

**Comment by qianyizh** [comment]
I think, you can use ``std::shared_ptr`` as key to ``std::map``. In this case, you don't even need a name.

W.r.t. view, I think the right behavior is to set up a specific function named ``ResetView()``, which automatically computes a bounding box of the current available geometries and set the best view for it.

The first time the scene is rendered, this function is called. After it, only keyboard / mouse input can change the view. Adding geometry / deleting geometry do not change the view. And of course we need to bind a key (e.g., ``r``) to let the user recompute and reset the view.

**Comment by bigsheep2018** [comment]
@syncle @qianyizh Thanks for the reply. 
Please let us know if there is any update for this.
Thanks.

**Comment by jing-IG** [comment]
@syncle @qianyizh This would be very useful. Currently in python, I have to destroy window and re-create window to render new geometries. Since I switch geometries a lot, this is painful. Any plan/progress to implement the geometry removal feature for python?

**Comment by jelmr** [comment]
@jing-IG @bigsheep2018 Updates to the .colors and .points attribute will be reflected in the rendering after update. This allows you to effectively remove geometry by setting their point- and color sets to empty.

I only have experience with point clouds, so I cannot tell you if something similar is possible with other geometries.

Example: 


```
import open3d
import time

vis = open3d.Visualizer()
vis.create_window()
pc = open3d.read_point_cloud("/path/to/some/pointcloud.ply")

vis.add_geometry(pc)
vis.update_geometry()
vis.update_renderer()
vis.poll_events()
vis.run()

# The point cloud is now shown

pc.points = open3d.Vector3dVector([])
pc.colors = open3d.Vector3dVector([])

vis.update_geometry()
vis.update_renderer()
vis.poll_events()
vis.run()

# The point cloud is no longer shown

time.sleep(5)
```

**Comment by wadimkehl** [comment]
Hi people, 
I want to push this issue, too, as this functionality is quite important, @germanros1987. At the moment, the API does not allow dynamic scene adjustments, which is fundamental for visualization tools.

**Comment by yxlao** [comment]
@wadimkehl and folks, https://github.com/intel-isl/Open3D/pull/904, when merged, shall address this problem

**Comment by germanros1987** [comment]
It is currently under review.

**Comment by wadimkehl** [comment]
Awesome, thanks! Maybe also a vis.clear_scene() as a convenience function to remove all registered geometry? This would keep the window alive, together with viewport config and camera settings.

**Comment by syncle** [comment]
That's good suggestion. Let me add it.

**Comment by jonra1993** [comment]
Hi anyone I was trying to use Non-blocking visualization from here http://www.open3d.org/docs/latest/tutorial/Advanced/non_blocking_visualization.html to hide and show pointclouds After hiding points, it does not show pointclouds anymore.
as @jelmr suggested I hide points using 
pc.points = open3d.Vector3dVector([])
pc.colors = open3d.Vector3dVector([])

Any one knows if I am using correct approach?

**Comment by germanros1987** [comment]
This is strange. @griegler  could you take a look?

**Comment by griegler** [comment]
@jonra1993 did you have a look [here](https://github.com/intel-isl/Open3D/blob/master/examples/Python/Advanced/remove_geometry.py)? You could use `add_geometry` and `remove_geometry` to show/hide your point clouds.

**Comment by jonra1993** [comment]
Hello @griegler thanks. add_geometry and remove_geometry worked.

**Comment by karlita101** [comment]
> @jonra1993 did you have a look [here](https://github.com/intel-isl/Open3D/blob/master/examples/Python/Advanced/remove_geometry.py)? You could use `add_geometry` and `remove_geometry` to show/hide your point clouds.

Hi there, I've implemented this with a 1) constant point cloud ( always there) 2) a point cloud that is added/removed at different time instances.

When making use of the add and remove_geomtry I can no longer use my mouse to manipulate the visualizer view. Should this be the case?
 ( I can only manipulate the visualizer's view when ONLY the constant geometry is present) # # #3712
