### ISSUE TITLE
How to load viewpoint in Visualization?

### ISSUE THREAD

**Issue by szx0112** [intel-isl/Open3D#567]
It looks like we can store the viewpoint to Json file, any method for us to load specific viewpoint when opening the visualization through 'draw_geometries' ?

Any comment is appreciated.

**Comment by qianyizh** [comment]
The easiest way is to open the json file, select all, copy, then paste in the Visualizer window.

The programmatic way is to call ``Visualizer.get_view_control().convert_to_pinhole_camera_parameters()`` (and/or ``convert_from_pinhole_camera_parameters()``), then use ``write_pinhole_camera_intrinsic()`` (and/or ``read_pinhole_camera_intrinsic``).

**Comment by syncle** [comment]
This issue is related to #387.
@qianyizh: ``read/write_pinhole_camera_intrinsic``  can only save camera intrinsic matrix, not extrinsic 4x4 matrix that are necessary for saving a view point. I just tried
```
    vis = Visualizer()
    vis.create_window()
    ctr = vis.get_view_control()
    pcd = read_point_cloud("../../TestData/fragment.pcd")
    vis.add_geometry(pcd)
    vis.run()
    param = ctr.convert_to_pinhole_camera_parameters()
    write_pinhole_camera_intrinsic("test.json", param)
    vis.destroy_window()
```
and got
```
    write_pinhole_camera_intrinsic("test.json", param)
TypeError: write_pinhole_camera_intrinsic(): incompatible function arguments. The following argument types are supported:
    1. (filename: str, intrinsic: open3d.PinholeCameraIntrinsic) -> bool
```

I think we need to expose ``PinholeCameraParameters`` and ``read/write_pinhole_camera_parameters``

**Comment by qianyizh** [comment]
Yes, I think you just need to save a ``PinholeCameraTrajectory``. As long as it only has one extrinsic matrix, it is basically a pair of intrinsic and extrinsic.

**Comment by kentaroy47** [comment]
@qianyizh 
Can we load the view point within a script?

>The easiest way is to open the json file, select all, copy, then paste in the Visualizer window.
I confirmed this working, but I'm not sure how to get the  `PinholeCameraTrajectory` pipeline working.

**Comment by kentaroy47** [comment]
Oh, this script worked perfectly.
https://github.com/intel-isl/Open3D/blob/master/examples/Python/Advanced/load_save_viewpoint.py

Did not realize that it was in the examples..

**Comment by syncle** [comment]
You're right. Thanks for the clarification!

**Comment by gonultasbu** [comment]
New link is as follows if anyone is interested:

https://github.com/intel-isl/Open3D/blob/1860e75f820f60a4c84d441720020c1e7e4237a7/examples/python/visualization/load_save_viewpoint.py

**Comment by Kin-Zhang** [comment]
Could be an option if future coders interested: https://gist.github.com/Kin-Zhang/77e8aa77a998f1a4f7495357843f24ef
