### ISSUE TITLE
Point Cloud Segmentation - Ground Plane Removal

### ISSUE THREAD

**Issue by lschaupp** [intel-isl/Open3D#591]
Anything like this in Open3d yet? 
Wasnt able to find anything in the docs...
Thanks for the info!

**Comment by syncle** [comment]
Could you propose good algorithm, or propose a PR for this? How to define and identify the ground plane is the thing I would like to discuss. Open3D is under development, so we are welcome your contribution.

**Comment by martinakos** [comment]
I've been doing this plane removal using either PCL or pycilantro.get_plane(). It would be nice to have it in Open3D though.

**Comment by spiegelss** [comment]
Late comment but something that might be useful to you is PDAL for [ground segmentation](https://pdal.io/stages/filters.smrf.html?highlight=smrf).  I have used PDAL for point cloud processing and it has been incredibly useful.  I don't know if Open3d would want to implement something like this, but I hope this helps!!
