### ISSUE TITLE
Improving ViewControl

### ISSUE THREAD

**Issue by syncle** [intel-isl/Open3D#596]
Raised by #594.

**Is your feature request related to a problem? Please describe.**
- The visualizer class only supports the same focal length for x and y axis. 
- ViewControl only accepts the camera parameter that is consistent with the rendered window size. 

**Describe the solution you'd like**
- Open3D/src/Visualization/Visualizer/ViewControl.cpp transforms 3x3 intrinsic to the OpenGL view point parameter. Modification on this code will be starting point.

Good reference: http://ksimek.github.io/2013/06/03/calibrated_cameras_in_opengl/

**Comment by wadimkehl** [comment]
Hi people,

is there any movement on this? And is there an immediate workaround that allows me to set the view matrix through python manually?

Thanks!

**Comment by qianyizh** [comment]
Yes, you can get the ViewControl, convert it into a CameraParameter, change extrinsic, then convert it back. This is so far the best practice.

We had lots of discussion on this. See #834 too

**Comment by cosama** [comment]
@qianyizh I am looking into doing something similar. Could you maybe provide some more specific example code how to get the ViewControl and convert it to CameraParameters, change it and convert it back? Thanks.

**Comment by christianbrugger** [comment]
Here you go @cosama 
```python
# build visualization
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(pcd)  # your point cloud goes here
# change extrinsic
cam = vis.get_view_control().convert_to_pinhole_camera_parameters()
pose = np.eye(4)
R = np.eye(3)
T = [0, 0, 0]
pose[:3, :3] = R
pose[:3, 3] = T
cam.extrinsic = pose
# load changed extrinsic
vis.get_view_control().convert_from_pinhole_camera_parameters(cam)
vis.run()
vis.destroy_window()
```

**Comment by germanros1987** [comment]
I know this is old, but we will soon have a cleaner solution for this issue in the new rendering engine.
