### ISSUE TITLE
Console log & UnitTest enhancement

### ISSUE THREAD

**Issue by theNded** [intel-isl/Open3D#603]
**Console Log**
The built-in functions (i.e. PrintInfo, PrintError) work well, but when the project grows larger, the feature in [glog](https://github.com/google/glog) that prints line number and file name may be helpful for tracing outputs and errors. Macros '\__FILE__', '\__LINE__' can do that.

**Unit test**
Now unit tests are not very systematic. [gtest](https://github.com/google/googletest) may be a good tool.

**Comment by takanokage** [comment]
I can answer regarding the unit tests: we're working on adding unit tests based on gtest. A majority of the open pull requests today are related to unit testing. PR #556 will enable running the unit tests during the Travis CI checks.

**Comment by theNded** [comment]
OK I see, it looks great. I was one commit behind and didn't notice that. Thanks.

**Comment by takanokage** [comment]
Thanks ;-).
Please note this is work in progress and as such I don't recommend relying on it at the moment.

**Comment by theNded** [comment]
No problem. I am trying to build a CUDA component upon it. If it works well, I will try to make a pull request.
