### ISSUE TITLE
Is it possible to update visualizer with a new pcd file in the same window?

### ISSUE THREAD

**Issue by ats27** [intel-isl/Open3D#609]
In the Non-blocking visualization, it shows how to transform source pcd and add it to the window, but is it possible to edit a point cloud or remove it and add a new one in its stead in the same window?

**Comment by syncle** [comment]
If I understand the question correctly, adding geometry is easy - just add ``vis.add_geometry(source)`` inside of the loop. To remove geometry, we don't have implementation yet. There is an open discussion here - #543

**Comment by qianyizh** [comment]
Another option is to reassign ``points``, something like this:
```
...
vis.add_geometry(source)
for non_blocking_loop:
    new_pcd = read_point_cloud("new.pcd")
    source.points = new_pcd.points
    # source.colors = new_pcd.colors
    # source.normals = new_pcd.normals
    ...
```

**Comment by syncle** [comment]
I just found out that @qianyizh's recommendation doesn't work out because the geometry gets bind to glsl_buffer at the time of add_geometry. Therefore, even if we do ``source.points = new_pcd.points``, it does not show the ``new_pcd``. This happens even if do ``update_geometry`` inside each for loop. ``updated_geometry`` works if the original point cloud buffer is unchanged. I think this is a bug, and need to be fixed.

**Comment by rancheng** [comment]
Hi @qianyizh, I wrote a simple wrapper for subscribe ros pointcloud2, and try to update the `viz` in the callback function, but this **re-assign** trick doesn't work. 

```python
class viz_pointcloud:

    def __init__(self):
        o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Debug)
        self.pcd = o3d.geometry.PointCloud()
        self.vis = o3d.visualization.Visualizer()
        self.vis.create_window()
        self.vis.add_geometry(self.pcd)
        self.pcdsub = rospy.Subscriber("/sensor/velodyne_points", PointCloud2, self.vis_callback)
        self.save_image = False
        self.img_cout = 0

    def vis_callback(self, cloud_msg):
        print('callback')
        self.img_cout += 1
        xyz_points = ros_numpy.point_cloud2.pointcloud2_to_xyz_array(cloud_msg)
        self.pcd.points = o3d.utility.Vector3dVector(xyz_points)
        self.vis.update_geometry()
        self.vis.poll_events()
        self.vis.update_renderer()
        if self.save_image:
            self.vis.capture_screen_image("temp_%04d.jpg" % self.img_cout)

    def destroy_vis(self):
        self.vis.destroy_window()
```

**Comment by Hammania689** [comment]
@rancheng, Here's an example of working code using @qianyizh  proposed method, which works nicely for my needs. 


`def play_motion(list_of_pcds: []):
    play_motion.vis = o3d.Visualizer()
    play_motion.index = 0

    def reset_motion(vis):
        play_motion.index = 0
        pcd.points = tensor_to_pcd(list_of_pcds[0]).points
        vis.update_geometry()
        vis.poll_events()
        vis.update_renderer()
        time.sleep(.25)
        vis.register_animation_callback(forward)
        return False

    def backward(vis):
        pm = play_motion

        if pm.index > 0:
            pm.index -= 1
            pcd.points = tensor_to_pcd(list_of_pcds[pm.index]).points
            time.sleep(.05)
            vis.update_geometry()
            vis.poll_events()
            vis.update_renderer()
        else:
            vis.register_animation_callback(forward)

    def forward(vis):
        pm = play_motion
        if pm.index < len(list_of_pcds) - 1:
            pm.index += 1
            pcd.points = tensor_to_pcd(list_of_pcds[pm.index]).points
            time.sleep(.05)
            vis.update_geometry()
            vis.poll_events()
            vis.update_renderer()
        else:
            # vis.register_animation_callback(reset_motion)
            vis.register_animation_callback(backward)
        return False

    # Geometry of the initial frame
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(list_of_pcds[0].reshape(-1, 3))
    pcd.colors = o3d.utility.Vector3dVector(np.ones(list_of_pcds[0].view(-1, 3).shape) * orange)

    # Initialize Visualizer and start animation callback
    vis = play_motion.vis
    vis.create_window()
    ctr = vis.get_view_control()
    ctr.rotate(0, -50)
    vis.add_geometry(pcd)
    vis.register_animation_callback(forward)
    vis.run()
    vis.destroy_window()`
 
Here's what the end result looks like. Keep in mind one could refine the `time.sleep` calls for smoother transitions. 
 
![open3d_animation_example](https://user-images.githubusercontent.com/20171200/72884840-6b55c700-3ccc-11ea-909f-27d17460a83f.gif)

**Comment by IgorZaton** [comment]
> @rancheng, Here's an example of working code using @qianyizh proposed method, which works nicely for my needs.
> 
> ```python
> def play_motion(list_of_pcds: []):
>     play_motion.vis = o3d.Visualizer()
>     play_motion.index = 0
> 
>     def reset_motion(vis):
>         play_motion.index = 0
>         pcd.points = tensor_to_pcd(list_of_pcds[0]).points
>         vis.update_geometry()
>         vis.poll_events()
>         vis.update_renderer()
>         time.sleep(.25)
>         vis.register_animation_callback(forward)
>         return False
> 
>     def backward(vis):
>         pm = play_motion
> 
>         if pm.index > 0:
>             pm.index -= 1
>             pcd.points = tensor_to_pcd(list_of_pcds[pm.index]).points
>             time.sleep(.05)
>             vis.update_geometry()
>             vis.poll_events()
>             vis.update_renderer()
>         else:
>             vis.register_animation_callback(forward)
> 
>     def forward(vis):
>         pm = play_motion
>         if pm.index < len(list_of_pcds) - 1:
>             pm.index += 1
>             pcd.points = tensor_to_pcd(list_of_pcds[pm.index]).points
>             time.sleep(.05)
>             vis.update_geometry()
>             vis.poll_events()
>             vis.update_renderer()
>         else:
>             # vis.register_animation_callback(reset_motion)
>             vis.register_animation_callback(backward)
>         return False
> 
>     # Geometry of the initial frame
>     pcd = o3d.geometry.PointCloud()
>     pcd.points = o3d.utility.Vector3dVector(list_of_pcds[0].reshape(-1, 3))
>     pcd.colors = o3d.utility.Vector3dVector(np.ones(list_of_pcds[0].view(-1, 3).shape) * orange)
> 
>     # Initialize Visualizer and start animation callback
>     vis = play_motion.vis
>     vis.create_window()
>     ctr = vis.get_view_control()
>     ctr.rotate(0, -50)
>     vis.add_geometry(pcd)
>     vis.register_animation_callback(forward)
>     vis.run()
>     vis.destroy_window()
> ```
> 
> Here's what the end result looks like. Keep in mind one could refine the `time.sleep` calls for smoother transitions.
> 
> ![open3d_animation_example](https://user-images.githubusercontent.com/20171200/72884840-6b55c700-3ccc-11ea-909f-27d17460a83f.gif)

What is ```tensor_to_pcd``` in Your code? I mean where can I find the definition?

**Comment by jinfagang** [comment]
not work for newer version open3d

**Comment by mocialov** [comment]
This works for me open3d version 0.15.1

```
import numpy as np
import open3d as o3d
import time

def play_motion(list_of_pcds: []):
    play_motion.vis = o3d.visualization.Visualizer()
    play_motion.index = 0

    def reset_motion(vis):
        play_motion.index = 0
        pcd.points = list_of_pcds[0].points
        vis.update_geometry(pcd)
        vis.poll_events()
        vis.update_renderer()
        time.sleep(.25)
        vis.register_animation_callback(forward)
        return False

    def backward(vis):
        pm = play_motion

        if pm.index > 0:
            pm.index -= 1
            pcd.points = list_of_pcds[pm.index].points
            time.sleep(.05)
            vis.update_geometry(pcd)
            vis.poll_events()
            vis.update_renderer()
        else:
            vis.register_animation_callback(forward)

    def forward(vis):
        pm = play_motion
        if pm.index < len(list_of_pcds) - 1:
            pm.index += 1
            pcd.points = list_of_pcds[pm.index].points
            pcd.colors = list_of_pcds[pm.index].colors
            time.sleep(0.1)
            vis.update_geometry(pcd)
            vis.poll_events()
            vis.update_renderer()
        #else:
        #    # vis.register_animation_callback(reset_motion)
        #    #vis.register_animation_callback(backward)
        return False

    # Geometry of the initial frame
    pcd = o3d.geometry.PointCloud()
    first = np.array(list_of_pcds[0].points)
    pcd.points = o3d.utility.Vector3dVector(first.reshape(-1, 3))
    pcd.colors = o3d.utility.Vector3dVector(np.ones(first.reshape(-1, 3).shape) * [0,0,0])

    # Initialize Visualizer and start animation callback
    vis = play_motion.vis
    vis.create_window(window_name='')
    ctr = vis.get_view_control()
    ctr.rotate(0, -50)
    vis.add_geometry(pcd)
    vis.register_animation_callback(forward)
    vis.run()
    vis.destroy_window()


pcds = []
for i in range(0,299):
    pcd = o3d.io.read_point_cloud("your_ply_file"+str(i)+".ply")
    print (pcd.get_center())
    pcds.append(pcd)
play_motion(pcds)
```

**Comment by saurabheights** [comment]
@syncle @qianyizh The code actually does fail in one condition. If add_geometry is called with empty PointCloud, i.e. o3d.geometry.PointCloud().  

Approach 1 below works perfectly, whereas Approach 2 only shows white background.

I think the issue might be due to 0 capacity of points vector during initialization, which means memory allocation is not yet happened - See https://stackoverflow.com/questions/12271017/initial-capacity-of-vector-in-c 

```
if __name__ == '__main__':
    vis = o3d.visualization.Visualizer()
    vis.create_window()
    prev_geometry = None
    approach = 2

    while True:
        // Generate pcd_frame.
        pcd_frame: o3d.t.geometry.PointCloud
        if approach == 1:
            tmp = pcd_frame.cpu().to_legacy()
            if prev_geometry is None:  # Initialize vis (add_geometry) with filled point cloud
                prev_geometry = o3d.geometry.PointCloud()
                prev_geometry.points = tmp.points[:100000]  # Just to verify if in case only first 100000 points get used in each successive frame. It's not, no relation to size of first points buffer to successive update_geometry.
                prev_geometry.colors = tmp.colors[:100000]
                vis.add_geometry(prev_geometry)
            else:
                prev_geometry.points = tmp.points
                prev_geometry.colors = tmp.colors
                vis.update_geometry(prev_geometry)
        elif approach == 2:
            tmp = pcd_frame.cpu().to_legacy()
            if prev_geometry is None:  # Initialize vis with empty point cloud
                prev_geometry = o3d.geometry.PointCloud()
                vis.add_geometry(prev_geometry)
            prev_geometry.points = tmp.points
            prev_geometry.colors = tmp.colors
            vis.update_geometry(prev_geometry)

        if not vis.poll_events():
            break
        vis.update_renderer()
    vis.destroy_window()
```
