### ISSUE TITLE
Bilateral Filter 

### ISSUE THREAD

**Issue by iurim** [intel-isl/Open3D#612]
Is it possible to get a function as:

  int k = 35;                // size of neighborhood. The bigger the smoother the result will be.
                               // This value should bigger than 1.
  double sharpness_angle = 25; // control sharpness of the result.
                              // The bigger the smoother the result will be
  int iter_number = 1;         // number of times the projection is applied
 std::cerr << "init bilateral" << std::endl;
  for (int i = 0; i < iter_number; ++i)
  {
    /* double error = */
    CGAL::bilateral_smooth_point_set <Concurrency_tag>(
      points,
      k,
      CGAL::parameters::point_map(CGAL::Nth_of_tuple_property_map<0, PV>()).
      normal_map(CGAL::Nth_of_tuple_property_map<2, PV>()).
      sharpness_angle (sharpness_angle));
  }
from  CGAL::

**Comment by syncle** [comment]
Hi @iurim, Could you elaborate the question bit more? Is this feature request?
