### ISSUE TITLE
How to rotate a model along X axis? 

### ISSUE THREAD

**Issue by TaoHuUMD** [intel-isl/Open3D#617]
I used python. There is a simple code about rotation, but "ctr.rotate(0.0, 10.0)" only supports rotation along Y or Z.  How can I rotate a model along X? And translation also has the same problem. 

Another way is to set view matrix, but there is no related interface for python. How can I do?

**Comment by syncle** [comment]
Hi, Please see my answer for setting view matrix: https://github.com/IntelVCL/Open3D/issues/615

``ctr.rotate`` and ``ctr.translate`` is intended for 2-dimensional mouse event; It computes view point change using mouse drag event. To freely rotate or translate the model, I recommend to use ``pcd.transform(T)`` with your transformation matrix ``T``.

**Comment by tsyj0404** [comment]
thanks. pcd.transform(T)  seems work for rotation, but I cannot translate the model. Do I have to set camera?

    vis = Visualizer()
    vis.create_window(window_name = 'open3d',width = 600, height = 600) #false
    vis.add_geometry(pcd)

    trans_init = np.asarray(
                [[0.862, 0.011, -0.507,  **10**],
                [-0.139, 0.967, -0.215,  0],
                [0.487, 0.255,  0.835, 0],
                [0.0, 0.0, 0.0, 1.0]])

    pcd.transform(trans_init)

    draw_geometries_with_animation_callback([pcd], rotate_view)

**Comment by syncle** [comment]
``draw_geometries*`` family function has ``reset_view_point`` inside that automatically adjusts camera depending on the geometry. In this manner, even though the geometry is translated, the camera follows too, and you are looking the same image as a result. 

In this case, you will need to mimic ``draw_geometries`` family, but without using ``reset_view_point``. A good example is [here](http://open3d.org/docs/tutorial/Advanced/non_blocking_visualization.html). You will see the script makes use of explicit call of ``Visualizer`` class, and using its helper function explicitly.

**Comment by tsyj0404** [comment]
Thanks. It seems that the next transformation is based on the current state. There is no function in Visualizer() to delete the current geometry.  Can I transform the object always from its original state?  
And the transformation matrix is the same as the matrix of OpenGL, right?

**Comment by tsyj0404** [comment]
thanks. I will make a try.

**Comment by syncle** [comment]
Hi @tsyj0404. I submitted a PR that can do rolling the geometry (rotating along the viewing direction) hope this will be helpful.

**Comment by taohucs** [comment]
thanks for your wonderful work!

**Comment by g2ragrawal** [comment]
@syncle can i rotate model with angles along to x axis and y axis. something like i have value of yaw and pitch so how can i get view of model with this two angles?

**Comment by g2ragrawal** [comment]
i am able to rotate with rotation matrix form yaw, pitch, roll and using pcd.geometry.PointCloud.rotate()

**Comment by vuptran** [comment]
@syncle Could you show how I can have the geometry rotate along the viewpoint (or roll along the Z axis)? Which PR is this? Thanks.

**Comment by jinfagang** [comment]
@syncle Hi, I have a model, default orientation is opposite, how to quickly make it normal without any time cost??


<img width="1286" alt="image" src="https://user-images.githubusercontent.com/21303438/152681720-7f598948-f3c7-4307-91f4-cd660840aca6.png">

I think this is caused by different definition of z axis with my data and open3d, how to quickly make it right??
