### ISSUE TITLE
can I capture normal map of a point cloud?

### ISSUE THREAD

**Issue by TaoHuUMD** [intel-isl/Open3D#626]
Visualizer() has functions "capture_screen_float_buffer" and 
        capture_depth_float_buffer, and it works very well. But can I extract normal map (of a point cloud) at the same time?

**Comment by tsyj0404** [comment]
One method may be I could encode the normal in color channels of a point cloud, and then capture capture_screen_float_buffer. Does this work? But it is not a general way. Other methods?

**Comment by syncle** [comment]
Hi, to render normal map, changing rendering option is the easiest way. Can you try [this example](http://open3d.org/docs/tutorial/Advanced/customized_visualization.html#mimic-draw-geometries-with-visualizer-class)?

**Comment by tsyj0404** [comment]
thanks. So "renderoption.json" is just set to show normal map of any point clouds? where can I find the introduction of changing rendering option?

**Comment by tsyj0404** [comment]
cool!  I need to estimate normal from point cloud, and clarify inside and outside of the object. But I do not find documents about "orient_normals_towards_camera_location" or orient_normals_to_align_with_direction. How to orient the normals?

**Comment by syncle** [comment]
There are two python functions to orient estimated normal based on camera location or certain viewing direction:
https://github.com/IntelVCL/Open3D/blob/e5f205e7614d3bd20037af7ff8ef4f8442a70ded/src/Python/Core/open3d_pointcloud.cpp#L114-L122
