### ISSUE TITLE
Capturing the rendering on an invisible window

### ISSUE THREAD

**Issue by martinakos** [intel-isl/Open3D#652]
This is related with [this](https://github.com/IntelVCL/Open3D/issues/608) issue.

I'm have tried to create a window with vis.create_window(visible = False) and certainly no window appears. Later in my code I'm using vis.capture_screen_float_buffer(True) to get a snapshot of what I've rendered in the now invisible window and display it within my own GUI. However, with visible=False, the snapshot captures whatever is on the screen at that moment. Any way of capturing what is being rendered in the invisible window?

**Comment by syncle** [comment]
HI @martinakos! ``vis.create_window(visible = False)`` is experimental; it guarantees hiding window, but may not work with glbuffer access. The workaround is to use virtual display environment like OSMesa. Can you try [headless rendering tutorial](http://open3d.org/docs/tutorial/Advanced/headless_rendering.html)?

**Comment by martinakos** [comment]
I build Open3D with headless rendering as explained in the link you give me and tried in my project. It worked but in my application I can get 11fps with the standard rendering whereas only 1 or 2 fps for the headless rendering. I'm suspecting it's slower because is using a software backend for OSMesa. If that's the case, do you know how to set it up so that it uses the graphics hardware?

**Comment by qianyizh** [comment]
Can you try the method I described in https://github.com/IntelVCL/Open3D/issues/17#issuecomment-339391580 ?

It sets up a hardware graphics acceleration environment (with a NVidia graphics card), then renders the window inside.

**Comment by germanros1987** [comment]
This is definitely solved now with the new EGL system.
