### ISSUE TITLE
Raycasting functionality?

### ISSUE THREAD

**Issue by martinakos** [intel-isl/Open3D#658]
I'm using Open3D to do object reconstruction using the UniformTSDFVolume. I've made a demo were the user moves the camera to do the reconstruction and it works quite well. Now I need an automatic way to tell what areas of the object have been "successfully" reconstructed without me having to inspect the rendering of the object. I think this could be achieved by casting rays from sampled points on a sphere around the TSDFVolume towards the center of the volume and testing if they cross a surface or not. Before attempting to implement anything myself, I'd like to check if raycasting is something on the Open3D roadmap?

**Comment by qianyizh** [comment]
Not in the near future. The current focus is on providing support for deep learning frameworks.

**Comment by qianyizh** [comment]
If you can implement this and contribute to Open3D that would be awesome!

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
