### ISSUE TITLE
Supporting print functions for Eigen::matrix

### ISSUE THREAD

**Issue by syncle** [intel-isl/Open3D#700]
**Is your feature request related to a problem? Please describe.**
It is not a problem - it is a feature request

**Describe the solution you'd like**
Print[Warning/Info/etc] functions can take Eigen::matrix and prints out matrix elements.
There is a discussion related to this request: https://github.com/IntelVCL/Open3D/pull/681#issuecomment-438399294

**Comment by takanokage** [comment]
I think this is a great idea.
The Print utilities I originally implemented to help with the implementation of the unit tests can be repurposed, with minor changes, to be used inside Open3D.

**Comment by griegler** [comment]
This is actually possible by now using `utility::LogInfo("{}", some_eigen_matrix);`.
