### ISSUE TITLE
Improving Python API

### ISSUE THREAD

**Issue by syncle** [intel-isl/Open3D#702]
This issue is raised after I had some discussion with @germanros1987 

### Consistent C++ and Python API 
We need to improve Python API in order to have consistent use case as we can do with C++. 
It is mainly because not all the public class/functions are not exposed to Python.
- For example, we can control visualizer with some parameters in C++, but we cannot change color map in Python interface because SetGlobalColorMap is not exposed. We need to check if there are such cases.

Not intuitive - it is not a bug, but functions does not behave the way user expected
- For example #609 - even if the assigned geometry is updated with new point cloud, visualizer class still shows the original geometry because it only shows originally binded glsl buffer.
- Another example is 3D translation - even if the mesh is translated, we cannot see the difference. It is because ViewControl automatically translates camera poses based on the geometry. However, it makes confusion for Open3D users. https://github.com/IntelVCL/Open3D/issues/617#issuecomment-430327512

### Utility functions
- It would be useful if we can provide utility functions - such as rotation or translation not only proving the transformation

The questions/requests are mostly about Visualizer class. I think we can begin to work from there.

**Comment by germanros1987** [comment]
I am going to close this issue, because since Open3D 0.8 we have tried to align our core python and C++ APIs.
