### ISSUE TITLE
Any plan to support occupancy grid mapping and visualization?

### ISSUE THREAD

**Issue by ZF-AR** [intel-isl/Open3D#703]
Would be nice to integrate OctoMap or implement something similar
https://github.com/OctoMap
Thanks!

**Comment by syncle** [comment]
Thanks for the suggestion @ZF-AR, but our current workload is not assigned for OctoMap support. This issue make me to think factorize this request into two pieces - 1) octree support 2) octomap support. Actually 1) will be useful in general if we go for adding Poission surface reconstruction https://github.com/IntelVCL/Open3D/issues/270. If you are willing to contribute any of those, we are always welcome :)

**Comment by ZF-AR** [comment]
Got it. Thanks for your response!
