### ISSUE TITLE
Enter preview mode by python code

### ISSUE THREAD

**Issue by ajayrfhp** [intel-isl/Open3D#704]
Is it possible to enter the preview mode for drawing mesh through python code. I find that using control +W preview mode shows much greater depth information for my point cloud

**Comment by syncle** [comment]
If I understand the question correctly, you should able to enter preview mode with Python. Sometimes, python mode does not accept key events (especially MacOS), in that case, you can run your script with ``pythonw [your_script].py``. 

Here is a good example to try: ``examples/Python/Advanced/interactive_visualization.py``, and there is a demo video about [this feature](https://www.youtube.com/watch?v=I3UjXlA4IsU&index=1&list=PLLMgZwl-AQOm9wDOWzup2KTl9Ak0CnpjI) from 00:53.

**Comment by ajayrfhp** [comment]
Sorry, I will add some clarification. I want to draw 30 meshes and all of the look better with the preview. Currently we can turn on the preview mode by pressing `control + W` after the mesh is rendered. So I have to do manually do this 30 times. Is it possible to turn on the preview inside the .py file and not during the user interaction.

**Comment by germanros1987** [comment]
Given the new visualization system, it is not clear if this issue still exists. I am closing it for the time being. Feel free to create a new one if needed;
