### ISSUE TITLE
Non-existing include directories in Open3D_INCLUDE_DIRS

### ISSUE THREAD

**Issue by pezcode** [intel-isl/Open3D#710]
I'm using `find_package` with CMake to populate `Open3D_INCLUDE_DIRS`. So far so good, but when I try to add the directories to an interface library in CMake:
```cmake
find_package(Open3D 0.4 REQUIRED)
target_include_directories(Open3D INTERFACE ${Open3D_INCLUDE_DIRS})
```
I get the following error:
> CMake Error in CMakeLists.txt:
>   Imported target "Open3D" includes non-existent path
> 
>     "S:/lib/Open3D/install/open3d-armeabi-v7a/include/Open3D/IO/FileFormat"

This is related to https://github.com/IntelVCL/Open3D/issues/509 and a result of the fix. In the install step the _FileFormat_ folder is explicitly excluded from being copied, but in the previous call to
```cmake
Directories(${CMAKE_CURRENT_SOURCE_DIR} IO_INCLUDE_DIRS)
```
it still adds _FileFormat_ to the list of directories.

**Comment by pezcode** [comment]
There is a workaround, namely removing all non-existing directories from the list. Not ideal but it works:
```cmake
foreach(dir ${Open3D_INCLUDE_DIRS})
  if(NOT EXISTS ${dir})
    list(REMOVE_ITEM Open3D_INCLUDE_DIRS ${dir})
  endif()
endforeach()
```

**Comment by yxlao** [comment]
Hi @pezcode, I couldn't reproduce the issue using the cmake `INTERFACE`. Here's my try: https://github.com/yxlao/Open3D/commit/c072004455bcc68290a822a39ddc4253f062732 . You're right that there are empty directories in the imported cmake file, but in my case the compilation and linking still works.

So could you please
1. Try renaming `Open3D` to other names like `Open3DInterface`? In my case, if the name interface name is also `Open3D`, it will cause problem. Something like:
```cmake
add_library(Open3DInterface INTERFACE)
target_include_directories(Open3DInterface INTERFACE ${Open3D_INCLUDE_DIRS})
```
2. Provide an example reproducing the issue with [this sample project](https://github.com/IntelVCL/Open3D/tree/master/docs/_static/C%2B%2B)?

Thanks.

**Comment by yxlao** [comment]
BTW, your https://github.com/pezcode/open3d-core-android looks pretty cool. I saw that this CMake file is used in your android build. We'd like to know whether this build issue is specific to the android build environment.

I've been thinking about trying out Open3D on devices like Raspberry Pi, however it looks like the official version of GLEW does not work with OpenGL ES [from this post](https://stackoverflow.com/a/31474052/1255535), so some porting works may be required.

**Comment by pezcode** [comment]
Hey @yxlao, thanks for the quick reply.

I unfortunately left out a detail I didn't realize made a difference. Apparently CMake doesn't care for normal interface libraries, but it does care for imported libraries.

I'm not super familiar with CMake but [imported libraries](https://cmake.org/cmake/help/latest/command/add_library.html#imported-libraries) seemed to be the proper way to add a pre-compiled library. Especially in my use case of compiling every 3rd-party lib so `Open3D_LIBRARIES` only contained Open3D.

Switching to imported library instead of interface brings back the same error message about non-existent directories.
Quick repro: https://github.com/pezcode/Open3D/commit/7dd5a15a531468969bfec7f666f5d7ee9d92db0a

Now there is another issue with this which i noticed after trying to reproduce this with MSVC. On Windows toolchains, [IMPORTED_LOCATION](https://cmake.org/cmake/help/v3.12/prop_tgt/IMPORTED_LOCATION.html) doesn't point to the shared library, it points to the .dll binary. Instead, you have to set IMPORTED_IMPLIB to the .lib library.

**Comment by pezcode** [comment]
Had some freetime and added some code to Open3DConfig.cmake that takes care of creating the library. On top of the old variables it now adds a target Open3D::Open3D with all the transient properties set. All you have to do in your code is:
```cmake
find_package(Open3D REQUIRED)
target_link_libraries(TestVisualizer Open3D::Open3D)
```
This is the standard way find_package works for the packages CMake finds (Boost, Bzip, etc).

Also found a neat way to make the paths relative so the entire install folder will be movable.

Should I clean it up and send a pull request? Or would you prefer if I put it here or file another issue?

**Comment by yxlao** [comment]
From [Boost's example](https://cmake.org/cmake/help/v3.12/module/FindBoost.html),
```
if(Boost_FOUND)
  include_directories(${Boost_INCLUDE_DIRS})
  add_executable(foo foo.cc)
  target_link_libraries(foo ${Boost_LIBRARIES})
endif()
```
we do need to add `include_directories(${Boost_INCLUDE_DIRS})`.  Are you suggesting that we don't need to use `include_directories`?

Yeah, please submit a PR -- it shall be easier to discuss there when we have the concrete code. Thanks

**Comment by pezcode** [comment]
You shouldn't have to if you link to the generated targets instead of using the variables. Boost defines one for each requested component, e.g.
```cmake
find(BOOST COMPONENTS filesystem regex)
target_link_libraries(foo Boost::filesystem Boost::regex).
```
is enough.

To get the header-only part you can use `Boost::boost`. Check out the example right below the one you quoted. The catch is that you need to explicitly list all the modules you want in the call to target_link_libraries (or I guess you could keep using `Boost_LIBRARIES` but it's better not to mix the two approaches).

I'll clean up the code and send a PR sometime this week then.

**Comment by pezcode** [comment]
I've been drowning in assignments and kinda forgot, my bad. Will send a PR tomorrow that adds CMake imported targets and fixes this (and https://github.com/IntelVCL/Open3D/issues/716) along the way.
