### ISSUE TITLE
Cannot reconstruct pcl from depth image

### ISSUE THREAD

**Issue by sjwhhhi** [intel-isl/Open3D#732]
Hi, it is an excited project!! However, I met a problem.

After running the following code, the result show nothing.

`depth = read_image('1.png')
pcd = create_point_cloud_from_depth_image(depth, PinholeCameraIntrinsic(
            PinholeCameraIntrinsicParameters.PrimeSenseDefault))
pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
draw_geometries([pcd])`

And here is my depth image:
![result](https://user-images.githubusercontent.com/28922123/49773809-d5fcab00-fd35-11e8-846d-8cc70bbfcfe5.png)

Thx!!

**Comment by syncle** [comment]
Could you check your depth map is written with 16bit png image, and follows the one of the following format described here? http://www.open3d.org/docs/tutorial/Basic/rgbd_images/index.html
There are corresponding examples of depth images:
https://github.com/IntelVCL/Open3D/tree/master/examples/TestData/RGBD
