### ISSUE TITLE
ICP ,Global regestration and the method for testing

### ISSUE THREAD

**Issue by MulinYu** [intel-isl/Open3D#733]
Hi, I have a question ,for ICP(Point to Point) and Global registration, if i give the method points cloud with color. Dose they consider the color when they do registration.

For testing the result of the ICP with color, you seem to use the same method as when we don't consider color. Is there better method for testing the result when we consider color ?

thanks,

waiting for your reply.

**Comment by MulinYu** [comment]
Hi，I am sorry that I said it is not clear.

1，I want to know if you consider the color of the point cloud when you use ICP registration(point to point) and Global registration.

2,  I found that the results of the ‘Colored point cloud registration’ method and the ‘ICP registration’ output are both “Fitness, RMSE and number of related points”. Is the calculation of the 'Fitness, RMSE and number of related points' in the two methods the same?

3，Is there any other way to measure the registration result when we consider the color of the point cloud?

Thanks.
waiting for your reply.

**Comment by MulinYu** [comment]
> Sorry I don't fully understand the question. Could you elaborate it more?

**Comment by MulinYu** [comment]
> Sorry I don't fully understand the question. Could you elaborate it more?

Hi，I am sorry that I said it is not clear.

1，I want to know if you consider the color of the point cloud when you use ICP registration(point to point) and Global registration.

2, I found that the results of the ‘Colored point cloud registration’ method and the ‘ICP registration’ output are both “Fitness, RMSE and number of related points”. Is the calculation of the 'Fitness, RMSE and number of related points' in the two methods the same?

3，Is there any other way to measure the registration result when we consider the color of the point cloud?

Thanks.
waiting for your reply.

**Comment by syncle** [comment]
1. Yes. We considered color for the local and global registrations.
2. Yes. It is RMSE for point to point distance.
3. I am not sure, as we can judge that the geometry is correctly aligned using RMSE, but the color alignment could be arbitrary. It is because the color value is not absolutely consistent in practice.
