### ISSUE TITLE
get depth map from raw mesh(.obj) project

### ISSUE THREAD

**Issue by ChenDRAG** [intel-isl/Open3D#739]
hi.
i,m trying to use open3d to extract depth map from an obj file(given camera parameters).currently i'm using 
the method below

```

#!/usr/bin/env python3
from __future__ import absolute_import, print_function
import math
import os
import camera
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import open3d
import cv2 as cv
import loader.loader as load

smplpath="./data/smpl/1.obj"

filepath,fullflname = os.path.split(smplpath)
fname,ext = os.path.splitext(fullflname)
outpath=os.path.dirname(filepath)+'/depth/'+fname+'.png'

def dict_to_open3dmesh(dict):
    mesh=open3d.TriangleMesh()
    mesh.vertices=open3d.open3d.Vector3dVector(dict['vertices'])
    mesh.vertex_colors=open3d.open3d.Vector3dVector(dict['rgbs'])
    mesh.triangles=open3d.open3d.Vector3iVector(dict['faces'])
    return mesh

def custom_draw_geometry_with_key_callback(pcd):
    w=1080
    h=1440
    f=3214.285714

    def capture_depth(vis):
        depth = vis.capture_depth_float_buffer()
        #open3d.write_image('depth.png',depth)
        cv.imwrite(outpath,(np.asarray(depth)*1000).astype(np.uint16))
        #plt.imshow(np.asarray(depth))
        #plt.savefig('depth.png')
        #plt.show()
        return False

    def apply_camera(vis):
        intrinsic=open3d.PinholeCameraIntrinsic()
        intrinsic.set_intrinsics(w,h, f, f, w/2.0-0.5, h/2.0-0.5)
        extrinsic=np.array([
        [    0.9981 ,-0.0160041,  0.0593907 ,   -1.0298],
        [0.0123974 ,  0.998087 , 0.0605806  , -1.59618],
        [-0.060248, -0.0597236 ,  0.996391  ,  1.32826],
        [       0.  ,        0. ,       0.     ,     1.]
        ],dtype='float64')
        extrinsic=np.identity(4,dtype=np.float64)
        #from IPython import embed;embed()
        #extrinsic=np.identity(4, dtype='float64')
        vis.get_view_control().convert_from_pinhole_camera_parameters(intrinsic, extrinsic)  

    key_to_callback = {}
    key_to_callback[ord(",")] = capture_depth
    #key_to_callback[ord(".")] = capture_image
    key_to_callback[ord("A")] = apply_camera


    open3d.draw_geometries_with_key_callbacks([pcd], key_to_callback,width=w,height=h,left=0,top=0)

m = load.Obj(smplpath)
m=m.data
mesh=dict_to_open3dmesh(m)
mesh.compute_vertex_normals()
custom_draw_geometry_with_key_callback(mesh)

```

however there are two drawbacks:
1.every time i want to save a depth map ,i have to open the render displayer,i want to know that if i can get 
depth buffer without doing that?
2.as you can see, if i set
```
    w=1080
    h=1440
```
it will report error

> > .[ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not 
> match.

but if i set
```
    w=540
    h=720
```
the result is good.

i think this is because that (1080,1440) is beyond my window's size,so it automatically shrink window size?
so how should i do it? could you please help me ?
thanks.

**Comment by ChenDRAG** [comment]
also if i set
w=300
h=200
it reports bugs
[ViewControl] ConvertFromPinholeCameraParameters() failed because field of view is impossible.
 
i don't know why this happens?

**Comment by syncle** [comment]
Hi @ChenDRAG, could you distinguish the code part and question part more clearly? You can use github web features (buttons on the right corner of the textbox) to polish. It will help to understand the issue better for us or for potential Open3D users.

**Comment by ChenDRAG** [comment]
> Hi @ChenDRAG, could you distinguish the code part and question part more clearly? You can use github web features (buttons on the right corner of the textbox) to polish. It will help to understand the issue better for us or for potential Open3D users.

Oh sorry,i didn't notice that.I've already edit my question. So, is there a possibly more convenient way to do this?

**Comment by syncle** [comment]
Hi @ChenDRAG. I just tried with your code, but I cannot reproduce the issue. Are you using windows? This issue seems to be related to #762.

**Comment by nitish11** [comment]
@ChenDRAG  : From which library or module, are you referring this import 

`import loader.loader as load
`
Could you please share that.
