### ISSUE TITLE
Add rolling support to visualizer

### ISSUE THREAD

**Issue by syncle** [intel-isl/Open3D#744]
**Is your feature request related to a problem? Please describe.**
Interactive visualization need to add support rolling. It is useful as the current rotation is based on x and y directional rotations. To rotate geometry along z axis, it is not straightforward.

**Describe the solution you'd like**
Adding a new key + drag option to support z-axis rotation.

**Comment by qianyizh** [comment]
I think rotation along z-axis only makes sense when it is under orthogonal view. And I think in Open3D there is such a function (in EditingVisualizer? at least I had it in ManuallyCropGeometry). To do it, you can first press X or Y or Z to lock to one axis.

**Comment by syncle** [comment]
That's true, but the motivation here is that supporting z-axis rotation in basic visualizer with free view mode. Remember with the basic visualizer, there were cases we are struggled to orient a geometry. We did this by zig-zag + drag which was not very fancy. I actually have submitted #745, so that the only OpenGL up vector and right vector to be rotated. This is feasible without orthogonal projection model. You may want to check #745. :)

**Comment by germanros1987** [comment]
This is done in the new 0.10 release.
