### ISSUE TITLE
Walk mode in Visualizer

### ISSUE THREAD

**Issue by syncle** [intel-isl/Open3D#746]
**Is your feature request related to a problem? Please describe.**
Camera system implemented in Visualizer class is good for examining single geometry (like viewing an objects from different view points). It would be useful if we can support walk mode - like walking through the indoor/outdoor scenes, or like FPS game. It is useful to visualize large 3D scans.

**Describe the solution you'd like**
Support another mode in visualizer class that changes mouse and keyboard behavior.

**Comment by qianyizh** [comment]
This is great!

**Comment by germanros1987** [comment]
This was added in 0.10. You can have a look in the Open3D App: https://github.com/intel-isl/Open3D/releases/download/v0.10.0/Open3DApp-0.10.1.0-linux.deb
