### ISSUE TITLE
Virtual Scanning

### ISSUE THREAD

**Issue by densechen** [intel-isl/Open3D#761]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by syncle** [comment]
Hi @LittleLampChen. Can you describe more on this feature request?

**Comment by LittleLampChen** [comment]
Thanks for your reply. @syncle 
There is a similar implementation in pcl. https://github.com/PointCloudLibrary/pcl/blob/master/tools/virtual_scanner.cpp
It is useful when we want to gain a more realistic point from cad or mesh file.

**Comment by syncle** [comment]
Thanks for the clarification @LittleLampChen. The application would be very useful if it is added in ``examples/Cpp``. If you don't mind, could you contribute ``virtual_scanner`` for Open3D? Although I am maxed-out right now, I can help you if you are willing to do. :)
