### ISSUE TITLE
Please test Open3d with Windows 10 Anaconda Jupyter and/or CLI

### ISSUE THREAD

**Issue by graphedge** [intel-isl/Open3D#764]
I see Anaconda support was added https://github.com/IntelVCL/Open3D/issues/430 .  I am able to import Open3d within my conda virtual environment.  I assume the only dependencies and resources I need for rgbd_redwood.py are matplotlib and the two pictures, one for color and one for depth.  When I run a copy and pasted version of rgbd_redwood.py inside Jupyter Notebook, the kernel dies without an error message.

**Describe the solution you'd like**
I want to use Open3d in Jupyter Notebook inside an Anaconda virtual environment on Windows 10 64-bit.

**Describe alternatives you've considered**
I need to try Open3d's normal plane estimation as an alternative for [Sympy Plane](https://docs.sympy.org/latest/modules/geometry/plane.html), which seems to be slowing my project down a lot.

**Additional context**

1. I tried to conda install, received conda-proxy-error from the picture
![conda-proxy-error](https://user-images.githubusercontent.com/45630928/50835433-b18bf280-1324-11e9-8b1b-aa78b033f7e1.PNG)

2. I pip installed
3. I could import Open3d without apparent error, but assumed I was having issues because of lacking the conda package.
4. I started with a fresh 3.6 / pandas / bokeh environment, changed my .condarc to the following, and conda installed apparently successfully:

```
channels:
	- admin

ssl_verify: company.crt
show_channel_urls: true
allow_other_channels: true
report_errors: true 
```
5. When I run a copy/pasted rgbd_redwood.py with the correct two 0000.jpg files, it kills my Jupyter kernel.

6. with conda install, I have had 'import Open3d' both work and fail, so I tried pip install again:
_____________________________________________________________________________

```
(_py36pd-O3d-3) randompath>pip install Open3d
Collecting Open3d
  Downloading https://files.pythonhosted.org/packages/76/1a/3942b3528e6b6b29d16dc910df6bc4610e43819fe5dc7d890dcf13bcd351/open3d-0.1.1.zip (77kB)
    100% |████████████████████████████████| 81kB 842kB/s
Building wheels for collected packages: Open3d
  Running setup.py bdist_wheel for Open3d ... done
  Stored in directory: C:\Users\user\AppData\Local\pip\Cache\wheels\cf\bf\e5\0e6fe5f121dedd5061ed814b59dd00a41f5a0ce8e83256f943
Successfully built Open3d
Installing collected packages: Open3d
Successfully installed Open3d-0+unknown

(_py36pd-O3d-3) randompath>python -c "import open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'open3d'

(_py36pd-O3d-3) randompath>python -c "import Open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Open3d'
```

**Comment by syncle** [comment]
@yxlao: could you comment on this?

**Comment by yxlao** [comment]
Looks like there are two questions.

### Q1: Installing Open3D with Conda, Win10-64, Python 3.6

Here are the full commands:

```batch
conda create -y -q -n env3.6_conda python=3.6
activate env3.6_conda
conda install -y -q -c open3d-admin open3d
python -c "from open3d import *; import open3d; print(open3d)"
deactivate
```

This combination has already been tested on our CI, see [here](https://ci.appveyor.com/project/yxlao/open3d-python-ci/build/job/aa9gxd4h5e3469vu#L335) for the full log (look for blue-colored lines for the commands). I also tried config manually and it works in my case. Perhaps you could check the network/proxy settings to figure out the issue. 

Will try to reproduce the Jupyter issue and update this post.

**Comment by brettbrocato** [comment]
Thanks - I don't know yet if it works on my Anaconda installation, but I have it up and running on WinPython64-3.6.7.0Zero .

I experienced the 'dead kernel' in WinPython/Jupyter a couple more times.  That was probably caused by 1) not using os.path to normalize slashes or 2) mistyping 00000.jpg as 0000.jpg .

**Comment by yxlao** [comment]
Tried copy-paste `rgbd_redwood.py` to Jupyter, it works fine for me. Did you have the same source code and valid file names? Potentially you could run the Jupyter code line by line and try to see which line caused the issue.
![capture](https://user-images.githubusercontent.com/1501945/51133077-cebf3600-17e8-11e9-8f1c-cc367c77c18a.PNG)

Regrading the `CondaHTTPError` issue, it seems to be a Conda config and network set up issue, which is not specific to Opne3D. Simillar issue has been reported, for example [here](https://stackoverflow.com/questions/42563757/conda-update-condahttperror-http-none).
