### ISSUE TITLE
Crop in XY plane

### ISSUE THREAD

**Issue by kira-on** [intel-isl/Open3D#774]
Is there any faster way to corp the point cloud data, using x,y boundary values (circle/rectangle). The Z values are unknown before cropping.

Thank you

**Comment by syncle** [comment]
Hi @H-Paul. I am not sure what 'faster' means, but you can crop point cloud using numpy
```
from open3d import *
pts = np.asarray(pcd.points)
pts_cropped = your_cropping_function(pts)
pcd.points = Vector3dVector(pts_cropped)
```

**Comment by syncle** [comment]
@H-Paul: try to avoid making explicit for loop that could be done by ``numpy``.

Here is what I got:
```
import numpy as np
import time

n_points = 1000000
xyz = np.random.rand(n_points,3)

xc = 0
yc = 0
zc = 0
radius400 = 1.0

# original code
mask_index_round400 = []
z400 = []
t = time.time()
for i in range(len(xyz)):
    if (((xyz[i,0] - xc)*(xyz[i,0] - xc))) + (((xyz[i,1] - yc)*(xyz[i,1] - yc))) <= (radius400*radius400):
        mask_index_round400.append(i)
        z400.append(xyz[i,2])
print("Elapsed %f seconds (original code)" % (time.time() - t))


# new code
t = time.time()
c = np.zeros((1,2))
c[0,0] = xc
c[0,1] = yc
temp = xyz[:,:2] - np.repeat(c, n_points, axis=0)
valid_idx = np.where(np.linalg.norm(temp, axis=1) < radius400)
mask_index_round400 = np.arange(0,n_points)[valid_idx]
z400 = xyz[valid_idx,2]
print("Elapsed %f seconds (new code)" % (time.time() - t))
```

and the result is
```
Elapsed 2.150195 seconds (original code)
Elapsed 0.098208 seconds (new code)
```

**Comment by H-Paul** [comment]
@syncle Thank you for the help.

I have 2 point clouds, one generated by the camera (A) and the other one is generated using numpy (B). Where the number of points in A > B. I want to get the index of all the points in A that intersects with the points in B. 
Is there any way I can do this with numpy functions or any of the Open3D functions?
Thanks in advance!

**Comment by syncle** [comment]
How do you define 'intersection' for the point cloud? Do you mean overlapping region?

**Comment by H-Paul** [comment]
@syncle Yes! Overlapping region (approximate overlap is also fine)

**Comment by syncle** [comment]
In this case, consider using KDTree (http://open3d.org/docs/tutorial/Basic/kdtree.html). You can transform the A into Open3D point cloud, and build a KDTree. You can iterate single points in B and find the nearest neighbor in A. This is more efficient than opposite method (making KDTree using B and querying using A).

**Comment by H-Paul** [comment]
Thank you @syncle for the suggestion. 

I want to perform the above operation because I have to change all the Z axis values of the points in B mentioned earlier to the lowest Z axis level of points in A(only in the XY region that overlaps B). So I am extracting Z by comparing XY values.

I tried to do this:

//Compare XY values
for i in len(Axyz):
    idx = np.where(((round(Bxyz[i][0]/10), round(Bxyz[i][1]/10) == (round(Axyz[i][0]/10), round(Axyz[i][1]/10))).all(axis=1))
            if len(idx[0])>0:
                matchidxA.append(i)
                zA.append(Axyz[i][2])

//Shift the Z axis level of B to match with Z level of A
Bxyz[:,2] = Bxyz[:,2]  + np.amin(zA)

//Then compare Bxyz with Axyz in matchidxA

There there any efficient way to do this? I apologize in advance if it is too confusing!
Thank you for reading!

**Comment by ibrahimLearning** [comment]
@syncle 
Sorry to comment at closed issue.
My problem is similar to this issue, except mouse event. How can I draw polygon on XY plane and extract points. it looks like 2D image annotation.

**Comment by ibrahimLearning** [comment]
> @syncle
> Sorry to comment at closed issue.
> My problem is similar to this issue, except mouse event. How can I draw polygon on XY plane and extract points. it looks like 2D image annotation.

I got a solution using pick point. However, is there way to connect the points using lines?

**Comment by reyanshsolis** [comment]
Moving discussion to https://github.com/isl-org/Open3D/issues/1203
