### ISSUE TITLE
Wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by suptec19** [intel-isl/Open3D#789]
I compiled Open3D in Raspbian (Raspberry Pi3 B+), spending some time to make sure that all the required libraries were correctly intalled. Once finished the compilation, I installed the library in the system. After that I installed the python library, as discribed in the guide. Everything went well and without errors.
I started python3 and to test the library I imported it, but at that point I received the following error:

`>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/open3d/__init__.py", line 9, in <module>
    from open3d.linux import *
  File "/home/pi/.local/lib/python3.5/site-packages/open3d/linux/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.linux.open3d').__dict__)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/pi/.local/lib/python3.5/site-packages/open3d/linux/open3d.so: wrong ELF class: ELFCLASS64`

It seems that the library is for 64bit only, and infact in the directory ~/.local/lib/python3.5/site-packages/open3d/linux there are these libs:
open3d.cpython-36m-x86_64-linux-gnu.so
open3d.cpython-35m-x86_64-linux-gnu.so
open3d.so

May be Raspbian dosn't have the right OpenGL drivers?

**Comment by suptec19** [comment]
Executing: `glxinfo | grep OpenGL`, this is what I get:
`OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits)
OpenGL version string: 3.0 Mesa 13.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:`

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
