### ISSUE TITLE
[Win10 WinPython3 JupyterLab] quiver of normals

### ISSUE THREAD

**Issue by graphedge** [intel-isl/Open3D#790]
**Describe the bug**
I don't believe this is related to [my other issue](https://github.com/IntelVCL/Open3D/issues/764).  Open3d seems to generally work for me on WinPython jupyter notebook and lab after a git clone.  However, when I draw_geometries after estimate_normals, I don't see quiver arrows.

**To Reproduce**
You can see my notebook code in the picture, which is exactly the pointcloud basic example.  After reviewing some similar issue resolutions, I checked whether normals were calculated.
![image](https://user-images.githubusercontent.com/45630928/51483482-23256100-1d67-11e9-86de-3e8d2da1ce7a.png)

**Expected behavior**
I expected to see the quiver arrows as seen [here](http://www.open3d.org/docs/tutorial/Basic/pointcloud.html#vertex-normal-estimation)

**Screenshots**
![image](https://user-images.githubusercontent.com/45630928/51483464-16a10880-1d67-11e9-9303-7aeef3fb8387.png)

**Desktop (please complete the following information):**
 - OS: Win10-64
 - Chrome
 - WinPython3.6.7 Qt5

**Additional context**

**Comment by syncle** [comment]
Hi @brettbrocato. Currently Open3D for Jupyter visualization only supports point cloud render, so the lines would not appear. @yxlao: shall we add a support for other geometric primitives, such as lines, triangles and so on?

**Comment by yxlao** [comment]
Right, currently Jupyter only has basic support for point cloud rendering and we can look into supporting more geometries in the future. 

However, it seems like the example code above is not calling `j_visualizer`. @brettbrocato could you clarify whether you're seeing the visualized rendering inside the browser or in another pop-up window?  Would you mind showing a full screenshot?

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
