### ISSUE TITLE
question on default setting of config  parameters for depth_map_type

### ISSUE THREAD

**Issue by rnunziata** [intel-isl/Open3D#794]
Why is depth_map_type  in config file in reconstructionsystem python examples set to redwood as the default. It is never over ridden in any of the examples config files even when they are not the redwood dataset. This causes specific code to be executed for redwood in read_rgbd image func in make_fragments.py every time weather or not it is the redwood dataset.  It appears that the func can not work if the values is not set to redwood as the variable rgbd_image would be undefined. Look like it the if statement and config var should be removed.

**Comment by germanros1987** [comment]
@syncle do you think this is still a relevant issue? Have we taken any action to fix this?
