### ISSUE TITLE
Depth range clipping issue in Visualizer

### ISSUE THREAD

**Issue by syncle** [intel-isl/Open3D#803]
**Describe the bug**
The depth buffer for the rendering does not configure correctly if the camera is located to far to the object we want to render. This is not happening when Visualizer class automatically determine the view point, but happens if the real intrinsic and extrinsic matrices are used.

Because of this issue, some geometries are not rendered and clipped based on the depth.

**To Reproduce**
Load a object, place camera very far, render image

**Expected behavior**
All the geometries should be rendered

**Desktop (please complete the following information):**
 - OS: Every platform
 - Version Open3D 0.5 dev

----

**Additional context**
I was able to render the full object by changing this line
https://github.com/IntelVCL/Open3D/blob/fab6441b763b4964ef898cbb3fae8d10ef98442f/src/Visualization/Visualizer/ViewControl.cpp#L69
to be:
```
z_far_ = distance_ + 10.0 * bounding_box_.GetSize(); 
```
I think ``distance_`` or ``bounding_box_.GetSize()`` was not correctly set.

**Comment by syncle** [comment]
This issue is more related how to compute ``distance_``. We have hard coded parameter ``MAX_ZOOM`` that is defined here:
https://github.com/IntelVCL/Open3D/blob/fab6441b763b4964ef898cbb3fae8d10ef98442f/src/Visualization/Visualizer/ViewControl.cpp#L43
Increasing MAX_ZOOM can avoid this issue.

**Comment by pmkalshetti** [comment]
Thanks for this temporary solution of setting `3.0` to `10.0`.

**Comment by ndrplz** [comment]
Is there any news about this?

I think I run into the same issue trying to render 3D vehicle models aligned with the corresponding image. When the car is "far from the camera" the rendering fails (i.e. image is black). In some edge case you can really see the rendered model disappearing when it gets too far (see below).

![image](https://user-images.githubusercontent.com/3187598/61221920-e5a00000-a719-11e9-9082-274a13c651db.png)

**Comment by Chris45215** [comment]
I am working with an issue that I think is similar, though we are getting it when using Realsense sensors. I don't know if setting ZOOM_MAX is an option for us, as I can't find any documentation on how to do that in Python. I am also finding the camera limits a bit inexplicable. The maximum and minimum zoom levels are so close that, if we start with an incorrect scaling, the viewer is basically unusable because we can't zoom out enough to view our pointcloud.
