### ISSUE TITLE
weak error notification  in make_fragments for opencv

### ISSUE THREAD

**Issue by rnunziata** [intel-isl/Open3D#806]
Using the ReconstuctionSystem the code in make_fragments that calls the initialize_opencv  does  not produce a noticeable indicator when the import opencv fails. I feel this should be a configurable parameter that  should produce and terminal error if not specified and not default as it currently does ,  as it can lead to very different and unintended results.

**Comment by rnunziata** [comment]
Unfortunately it did not  ..does run a lot longer though. Did not do a qualitative assessment to see if it improved the results or how much.

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
