### ISSUE TITLE
More feature point algorithms

### ISSUE THREAD

**Issue by pezcode** [intel-isl/Open3D#813]
It would be nice to have some commonly used features besides FPFH. In certain scenarios other features could give better results, e.g. (C)VFH for object detection and pose estimation.

Is this on the roadmap? Or did you make a conscious choice to not implement other features for now?

**Comment by syncle** [comment]
@pezcode: Sorry, we are not prioritizing adding support for hand-crafted features for now. If you are willing to contribute, we are always welcome!

**Comment by pezcode** [comment]
I'd be willing but I'm afraid I lack the expertise. But good to know you're not against the idea.

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
