### ISSUE TITLE
I have a issue about the function  void RGBDOdometryJacobianFromHybridTerm::ComputeJacobianAndResidual when I read RGBDOdometryJacobian.cpp

### ISSUE THREAD

**Issue by minxuanjun** [intel-isl/Open3D#814]
I have a issue about the function   when I read RGBDOdometryJacobian.cpp.
Is the jacobian for gemometry term  that 
<a href="https://www.codecogs.com/eqnedit.php?latex=J&space;=&space;\begin{bmatrix}&space;D_u&space;&&space;D_v&space;&&space;-1&space;\end{bmatrix}&space;\begin{bmatrix}&space;\frac{f_x}{Z}&space;&&space;0&space;&&space;\frac{-f_x}{Z^2}\\&space;0&&space;\frac{f_y}{Z}&&space;\frac{-f_y}{Z^2}\\&space;0&&space;0&&space;1&space;\end{bmatrix}&space;\begin{bmatrix}&space;-(TP)^\Lambda&space;&&space;I&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?J&space;=&space;\begin{bmatrix}&space;D_u&space;&&space;D_v&space;&&space;-1&space;\end{bmatrix}&space;\begin{bmatrix}&space;\frac{f_x}{Z}&space;&&space;0&space;&&space;\frac{-f_x}{Z^2}\\&space;0&&space;\frac{f_y}{Z}&&space;\frac{-f_y}{Z^2}\\&space;0&&space;0&&space;1&space;\end{bmatrix}&space;\begin{bmatrix}&space;-(TP)^\Lambda&space;&&space;I&space;\end{bmatrix}" title="J = \begin{bmatrix} D_u & D_v & -1 \end{bmatrix} \begin{bmatrix} \frac{f_x}{Z} & 0 & \frac{-f_x}{Z^2}\\ 0& \frac{f_y}{Z}& \frac{-f_y}{Z^2}\\ 0& 0& 1 \end{bmatrix} \begin{bmatrix} -(TP)^\Lambda & I \end{bmatrix}" /></a>

**Comment by syncle** [comment]
@minxuanjun: Can you elaborate your issue bit more?

**Comment by syncle** [comment]
Could you point out specific line you think it is wrong? You can see a code and click line number and use ``copy permalink`` to paste the exact the position. It would be also great to identify issue better if you can try the fix and submit a PR with validation examples.

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
