### ISSUE TITLE
get transform matrix from 2 known positions of cameras

### ISSUE THREAD

**Issue by lukaspistelak** [intel-isl/Open3D#817]
I have 2 cameras with a fixed position. I know this position to each other in 3D Euclidean space:
xyz: Target. camera :(0,0,0) and Source.camera:(0,-0.50,0)

How can I compute the  4x4 affine transformation matrix?

Maybe my suggestion-solution is:
1. Finding the normal to a plane(but which one?) and find  plane-equation
[2.](https://en.wikipedia.org/wiki/Transformation_matrix#Examples_in_3D_computer_graphics)
   compute the matrix values with these equations

note: I am not sure how to get 3 random points from which plane?

**Comment by qianyizh** [comment]
If the two cameras have the same rotation, just apply a translation, something like:
```
1 0 0 0
0 1 0 -0.5
0 0 1 0
0 0 0 1
```

**Comment by lukaspistelak** [comment]
Rotation can be around y-axis : 90 degrees to the right or left

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
