### ISSUE TITLE
Colormap Optimization Not Working for me

### ISSUE THREAD

**Issue by jeongjoonpark** [intel-isl/Open3D#823]
I'm trying to project and average RGB images onto a mesh, so I'm using color_map_optimization without optimization iteration to achieve this.

However, as can be seen from the second image, the colored mesh I get from color_map_optimization does not look valid. I verified that my RGBD images and camera trajectory is correct by visualizing the volumetric color as shown in the first image. 

Please refer to the code below that generates these images. Why do you think the color_map_optimization is not working?

Thanks in advance!

`        

    for i in range(10):
        volume.integrate(rgbd_images[i], intrinsic,
                w2c_trajec.parameters[i].extrinsic)

    mesh = volume.extract_triangle_mesh()
    draw_geometries([mesh])

    # Project RGB images to mesh
    option = ColorMapOptimizationOption()
    option.maximum_iteration = 0
    color_map_optimization(mesh, rgbd_images, w2c_trajec, option)
    draw_geometries([mesh])
`

![image](https://user-images.githubusercontent.com/42125136/52452631-b3e69580-2af8-11e9-96b6-1f01c8749999.png)

![image](https://user-images.githubusercontent.com/42125136/52452653-ce207380-2af8-11e9-8f4f-72985be5b6f8.png)

**Comment by syncle** [comment]
Could you try with ColorMapOptimization with inverse of extrinsic matrices? As we can see in Reconstruction example, https://github.com/IntelVCL/Open3D/blob/3bd4efda67819299931035ec257f103f1feac88e/examples/Python/ReconstructionSystem/integrate_scene.py#L42
The inverse of camera matrices are used for the integration. 

Based on this, In your case, I think ``w2c_trajec`` is the set of inverse of camera extrinsic matrices. So, try convert ``w2c_trajec`` to ``w2c_trajec_inverse`` and put ``w2c_trajec_inverse`` for ColorMapOptimization

**Comment by jeongjoonpark** [comment]
Hi, thank you for your response! Yes w2c_trajec is the set of inverse of camera matrices, which I am obtaining through `read_pinhole_camera_trajectory` function, which automatically inverts the matrices. 

If you look at the example of ColorMapOptimization https://github.com/IntelVCL/Open3D/blob/3bd4efda67819299931035ec257f103f1feac88e/examples/Python/Advanced/color_map_optimization.py#L57
it's using the output of the `read_pinhole_camera_trajectory` so using the inverted matrices. 

Anyways, I tried both inverted and uninverted matrices for my above experiment, and the ColorMapOptimization actually generates completely black surface for uninverted case.

Maybe there's a bug in the code?

**Comment by syncle** [comment]
could you provide the minimal example (dataset, stand alone script), so that I can reproduce the result?

**Comment by jeongjoonpark** [comment]
Please find the attached link that contains the images, trajectory, and the code.
https://drive.google.com/open?id=1egiYPBnWDGJeP8iLblURGRgXmME8dmrX

Thank you!

**Comment by syncle** [comment]
Is this dataset was synthesized? It seems that there are unrealistic camera motion in this dataset, and some issue comes here. 

As a sanity check I used [fountain dataset](https://drive.google.com/open?id=1eT45y8qw3TLED2YY9-K1Ot6dQuF9GDPJ) (it is real camera pose and depth dataset) to integrate depth image and apply color map optimization just using a single RGBD frame:
```
from open3d import *
from trajectory_io import *

if __name__ == "__main__":
    camera_raw = read_pinhole_camera_trajectory("/Users/jaesik/Downloads/fountain_small/scene/key.log")
    camera = PinholeCameraTrajectory()
    camera.parameters = camera_raw.parameters[:1]
    intrinsic = PinholeCameraIntrinsic(PinholeCameraIntrinsicParameters.PrimeSenseDefault)

    rgbd_images = []
    depth_image_path = ["/Users/jaesik/Downloads/fountain_small/depth/0000038-000001234662.png"]
    color_image_path = ["/Users/jaesik/Downloads/fountain_small/image/0000010-000001228920.jpg"]
    assert(len(depth_image_path) == len(color_image_path))

    volume = ScalableTSDFVolume(voxel_length = 1.0 / 1000.0,
            sdf_trunc = 0.01, color_type = TSDFVolumeColorType.RGB8)

    for i in range(len(depth_image_path))[:1]:
        depth = read_image(depth_image_path[i])
        color = read_image(color_image_path[i])
        rgbd_image = create_rgbd_image_from_color_and_depth(color, depth,
                convert_rgb_to_intensity = False)
        rgbd_images.append(rgbd_image)
        volume.integrate(rgbd_image, intrinsic, camera.parameters[i].extrinsic)

    mesh = volume.extract_triangle_mesh()
    write_triangle_mesh("integrated.ply", mesh)
    mesh = read_triangle_mesh("integrated.ply")
    draw_geometries([mesh])

    option = ColorMapOptimizationOption()
    option.maximum_iteration = 0
    color_map_optimization(mesh, rgbd_images, camera, option)
    draw_geometries([mesh])
    write_triangle_mesh("color_map_before_optimization.ply", mesh)
```
As it is shown below, integrated mesh (first) and the color mapped mesh (second) is about the same, except for few pixels on the boundary that are not being used intentionally in color map optimization. 
<img width="400" alt="screen shot 2019-02-10 at 4 50 36 pm" src="https://user-images.githubusercontent.com/18297113/52542400-125b8000-2d54-11e9-92d3-d2af3000f99b.png">
<img width="400" alt="screen shot 2019-02-10 at 4 50 42 pm" src="https://user-images.githubusercontent.com/18297113/52542401-17203400-2d54-11e9-8ae9-a43e704e085b.png">
This means color map optimization and integration is working correctly.

I also tested your dataset in the same way, this is a script I used for the sanity check:
```
from open3d import *
import numpy as np

if __name__ == "__main__":
    set_verbosity_level(VerbosityLevel.Debug)
    intrinsic = read_pinhole_camera_intrinsic("camera-blender.json")

    volume = ScalableTSDFVolume(voxel_length = 1.0 / 1000.0,
            sdf_trunc = 0.01, color_type = TSDFVolumeColorType.RGB8)
    rgbd_images = []
    w2c_trajec = read_pinhole_camera_trajectory("poseO3D.log")
    camera = PinholeCameraTrajectory()
    camera.parameters = w2c_trajec.parameters[:1]

    for i in range(1):
        depth = read_image("depth/Image{:04d}.png".format(i))
        color = read_image("rgb/Image{:04d}.jpg".format(i))
        rgbd = create_rgbd_image_from_color_and_depth(color, depth, 1000.0, 0.8, False)

        volume.integrate(rgbd, intrinsic, camera.parameters[i].extrinsic)
        rgbd_images.append(rgbd)

    mesh = volume.extract_triangle_mesh()
    mesh.compute_vertex_normals()
    write_triangle_mesh("test.ply", mesh)
    mesh = read_triangle_mesh("test.ply")
    draw_geometries([mesh])

    option = ColorMapOptimizationOption()
    option.maximum_iteration = 0
    color_map_optimization(mesh, rgbd_images, camera, option)
    draw_geometries([mesh])
```
<img width="400" alt="screen shot 2019-02-10 at 4 53 44 pm" src="https://user-images.githubusercontent.com/18297113/52542438-79793480-2d54-11e9-82f5-8c6a4ebc63fd.png">
<img width="400" alt="screen shot 2019-02-10 at 4 53 51 pm" src="https://user-images.githubusercontent.com/18297113/52542440-7f6f1580-2d54-11e9-9e7f-0e64a5213cb5.png">

Something not plausible happens as shown above. First one is integrated mesh and the second one is color map optimization.

I think some unrealistic camera matrix is making some issue. Can you check my code and data and see how your camera poses are different? This will help to understand the issue.

**Comment by jeongjoonpark** [comment]
Hi, yes, the dataset is generated synthetically to test the Open3D library. I'm not sure what you mean by unrealistic camera matrix, as far as I understand when `option.maximum_iteration = 0` the ColorMapOptimization simply back-projects the RGB image onto the mesh. This should work even when the extrinsics of the neighboring frames are far away from each other?

I've also tried the same experiment you tried but got the same result -- it works for the sample data but does not for my data. 

Thank you!

**Comment by syncle** [comment]
> This should work even when the extrinsics of the neighboring frames are far away from each other?

I am not trying to say multiple frames - that's why I used the single frame for the sanity check. Can you analyze the difference the fountain dataset and yours? Such as coordinate, minus depth after projection, and so on?

**Comment by yd-yin** [comment]
So yes, I met the exact same problem as you did. The extrinsic should be camera2world since `read_pinhole_camera_trajectory` internally invert the matrices.

So did you find any solution afterwards? or any other optional methods?

Thanks in advance

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.

**Comment by zengletian1491** [comment]
> Hi, yes, the dataset is generated synthetically to test the Open3D library. I'm not sure what you mean by unrealistic camera matrix, as far as I understand when `option.maximum_iteration = 0` the ColorMapOptimization simply back-projects the RGB image onto the mesh. This should work even when the extrinsics of the neighboring frames are far away from each other?
> 
> I've also tried the same experiment you tried but got the same result -- it works for the sample data but does not for my data.
> 
> Thank you!

I have the same problem as you. How do you solve this problem finally? Thanks.

**Comment by zengletian1491** [comment]
I have the same problem as you. How do you solve this problem finally? Thanks. @jeongjoonpark

**Comment by yd-yin** [comment]
I don't remember clearly. But the error is just because of the range of
depth. There's a truncation of depth somewhere in the code, and if your
depth is larger than the threshold, the error appears.

zengletian1491 <notifications@github.com> 于2020年10月21日周三 下午12:07写道：

**Comment by zengletian1491** [comment]
OK! Thanks a lot. @yd-yin
