### ISSUE TITLE
Intersection / collision of object & pointcloud

### ISSUE THREAD

**Issue by jattiogbe** [intel-isl/Open3D#835]
Hi everyone, 

is it possible to know if some object (sphere, cone, cylinder)  touches points from the pointcloud, some kind of intersection ? or if some points are inside this object ?

Thanks.

**Comment by qianyizh** [comment]
We don't have good primitive (sphere, cone, etc) support right now. So no, we don't have such functions.
Do you have a specific use case?

**Comment by jattiogbe** [comment]
Ok
I would like to identify points in the cloud ( representing à wall) that would be in front of me, or facing positions from à trajectory. Si I was imagining a cone to highlight those points and change their color.
That's what I have in mind.

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.

**Comment by SmileyScientist** [comment]
@jattiogbe , I am now trying to do something similar. Did you manage to figure it out?
