### ISSUE TITLE
Draco Compatibility 

### ISSUE THREAD

**Issue by barnjamin** [intel-isl/Open3D#844]
Give the ability to compress ply file with [draco](https://github.com/google/draco).

Add some flag to save PointCloud or TriangleMesh with float32 values.  Currently just int32 and float32 are supported by Draco.
See: https://github.com/google/draco/issues/360

I modified the ply writer to use the compressed flag as a switch to write float instead of double but this is likely not a good solution.

```
+    auto dt = PLY_DOUBLE;
+    if(compressed){
+        dt = PLY_FLOAT;
+    }
+
     ply_add_comment(ply_file, "Created by Open3D");
     ply_add_element(ply_file, "vertex",
             static_cast<long>(pointcloud.points_.size()));
-    ply_add_property(ply_file, "x", PLY_DOUBLE, PLY_DOUBLE, PLY_DOUBLE);
-    ply_add_property(ply_file, "y", PLY_DOUBLE, PLY_DOUBLE, PLY_DOUBLE);
-    ply_add_property(ply_file, "z", PLY_DOUBLE, PLY_DOUBLE, PLY_DOUBLE);
+    ply_add_property(ply_file, "x", dt, dt, dt);
+    ply_add_property(ply_file, "y", dt, dt, dt);
+    ply_add_property(ply_file, "z", dt, dt, dt);
+
     if (pointcloud.HasNormals()) {
-        ply_add_property(ply_file, "nx", PLY_DOUBLE, PLY_DOUBLE, PLY_DOUBLE);
-        ply_add_property(ply_file, "ny", PLY_DOUBLE, PLY_DOUBLE, PLY_DOUBLE);
-        ply_add_property(ply_file, "nz", PLY_DOUBLE, PLY_DOUBLE, PLY_DOUBLE);
+        ply_add_property(ply_file, "nx", dt, dt, dt);
+        ply_add_property(ply_file, "ny", dt, dt, dt);
+        ply_add_property(ply_file, "nz", dt, dt, dt);
     }
+
```

It seems well worth it to try and support this compression, before and after compression by draco:
```
-rw-r--r--  1 ben ben 6.0M Feb 23 07:16 ds.ply
-rw-r--r--  1 ben ben 663K Feb 23 07:16 ds.ply.drc
```

**Comment by yxlao** [comment]
Thanks @barnjamin . First, regarding float32 vs float64, we're investigating the option to support both types in the future. At the current state, i think it is fine to convert float64 to float32 if the compression flag is set. We'll also need a reader to convert back to float64. Second, this will introduce a 3rd party library dependency for Open3D, which needs to be handled as well.

**Comment by barnjamin** [comment]
Would you like me to submit a pr with the above modifications?  I can also modify the reader.  

I'm not sure what you mean for the 3rd party dependency.  This change only modifies the datatype we're writing, it doesn't include any Draco specific code.  For compression I still passed it through a separate program.  

Would it make sense to add Draco as an option for file format to this library as well?

**Comment by germanros1987** [comment]
@barnjamin sorry for not following up on this issue back in the days. However, I think this is a very attractive feature. If you are still willing to contribute we would love to have it.

**Comment by barnjamin** [comment]
@germanros1987 this was for a project I've since abandoned so I have no build environment anymore. The diff from what I did is above but I recall having some doubt that it was the best way to implement it.

**Comment by germanros1987** [comment]
Thanks for clarifying.
