### ISSUE TITLE
PNG write configurability

### ISSUE THREAD

**Issue by barnjamin** [intel-isl/Open3D#846]
For the project I'm working on I want to prioritize fast PNG writes over compression.

There is a flag [here](https://github.com/IntelVCL/Open3D/blob/master/src/Open3D/IO/FileFormat/FilePNG.cpp#L77) to set quality level but it doesn't appear to be used.

```
+    pngimage.flags |= PNG_IMAGE_FLAG_FAST;
```

In testing, this flag addition changes a 640x480 image to be written in ~8ms from ~24ms but the file size almost doubles.  Larger images are OK for my use case but likely will hurt others.  

What would be a good method to add some way to configure prioritizing speed/compression?

**Comment by yxlao** [comment]
Good point, that flag should have been used. We can do default parameter value in both C++ and python that prioritize compression, while the user can specify other values to optimize speed.

**Comment by barnjamin** [comment]
Okay, great.  Can I take this to mean you will look at other flags for allowing a trade off? Or would you like me to put something together?

**Comment by germanros1987** [comment]
@yxlao do you think we should take care of this any time soon?
