### ISSUE TITLE
Any plan for computor graphics function like mesh decimation?

### ISSUE THREAD

**Issue by CanCanZeng** [intel-isl/Open3D#847]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
After I have reconstructed a scene, I would also like to process the mesh, like mesh decimation, and also I needs to do struct from motion, after the sparse or dense reconstruction, I want to create mesh from the point cloud. Would you like to add these kind of function? 

**Describe alternatives you've considered**
not yet

**Additional context**
not yet

**Comment by griegler** [comment]
Mesh simplification has been implemented in #945 . Surface reconstruction is planned to be added to the library soon.
