### ISSUE TITLE
Make H matrix sparse

### ISSUE THREAD

**Issue by mike239x** [intel-isl/Open3D#848]
Related to [#367](https://github.com/IntelVCL/Open3D/issues/367). In `Registration/GlobalOptimization.cpp` [line 194](https://github.com/IntelVCL/Open3D/blob/8121e77737460d648f7f8b57ce3bff7e053576d7/src/Open3D/Registration/GlobalOptimization.cpp#L194) a matrix of size `6n x 6n` is allocated, where n is number of vertices in the graph. I suggest making this a sparse matrix (Eigen::SparseMatrix), since in the current state it greatly limits number of vertices one can have in an optimization graph.

Exactly the same problem is with the [line 582](https://github.com/IntelVCL/Open3D/blob/8121e77737460d648f7f8b57ce3bff7e053576d7/src/Open3D/Registration/GlobalOptimization.cpp#L582) in the same file.

**Comment by yxlao** [comment]
Thanks @mike239x , this could be a good idea for future work. Internally we tried using sparse matrix for colormap optimization and it seems to help.

**Comment by germanros1987** [comment]
This seems like something that @theNded could do...

**Comment by theNded** [comment]
This will be addressed when we start to integrate MKL-PARDISO and cuSparse on demand.
