### ISSUE TITLE
ICP for small unequal number of points

### ISSUE THREAD

**Issue by JPeetersKUL** [intel-isl/Open3D#853]
Dear Open3D users.
I'm trying to find the transformation matrix to match a small number of points in a 2D (later also 3D) space on a another smaller set of points. For our application the number of points will in first instance be below 50 and the distance between the two point sets will be limited as in the example below. However, I don't manage to obtain a transformation matrix from the code below.
Many thanks for your help!

```
from open3d import *
import numpy as np
import copy

def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    draw_geometries([source_temp, target_temp])
    
xco= [1043, 1554, 1807, 2050, 2037, 2058, 1057, 1465, 2732,]
yco= [ 431,  390,  382,  377, 1032, 1467, 1775, 1975, 1933,]

xyz=[]    
for x,y in zip(xco,yco):
    xyz.append([x,y,0])
print xyz

#same image but all fasteners marked
xco_db= [1544, 1509, 1086, 1043, 1556, 1809, 2051, 2036, 2678, 2060, 2015, 2090, 2734, 2694, 1464, 1142, 1059, 1033, 1341,]
yco_db= [ 706,  880,  943,  386,  349,  339,  332,  985,  427, 1400, 1771, 1903, 1886, 1731, 1928, 1937, 1729, 1032,  416,]

xyz_db=[]    
for x,y in zip(xco_db,yco_db):
    xyz_db.append([x,y,0])
print xyz_db

pcd = PointCloud()
pcd.points = Vector3dVector(xyz)

pcd_db = PointCloud()
pcd_db.points = Vector3dVector(xyz_db)

source = pcd_db
target = pcd

threshold = 0.02
trans_init = np.asarray(
            [[1, 0, 0,  0],
            [0, 1, 0,  0],
            [0, 0,  1, 0],
            [0, 0, 0, 1]])
draw_registration_result(source, target, trans_init)
print("Initial alignment")
evaluation = evaluate_registration(source, target,
        threshold, trans_init)
print(evaluation)

print("Apply point-to-point ICP")
reg_p2p = registration_icp(source, target, threshold, trans_init,
        TransformationEstimationPointToPoint(),
        ICPConvergenceCriteria(max_iteration = 200))
print(reg_p2p)
print("Transformation is:")
print(reg_p2p.transformation)
print("")
draw_registration_result(source, target, reg_p2p.transformation)

print("Apply point-to-plane ICP")
reg_p2l = registration_icp(source, target, threshold, trans_init,
        TransformationEstimationPointToPlane(),
        ICPConvergenceCriteria(max_iteration = 200))
print(reg_p2l)
print("Transformation is:")
print(reg_p2l.transformation)
print("")
draw_registration_result(source, target, reg_p2l.transformation)
````

**Comment by mike239x** [comment]
a) nice mix of print statements, do you use python 2 or 3?
b) your threshold is too small, your points are about 45 units apart, so setting theshold to 0.02 would make ICP do nothing. Set it to 50 and it would work.
c) point to plane registration doesn't work in your situation since you do not have normal vectors, which you can only properly compute for a proper 3d scene.
d) IMHO you might want to look into [tinyslam](https://openslam-org.github.io/tinyslam.html) instead

**Comment by qianyizh** [comment]
Yes, as @mike239x pointed out, try PointToPoint ICP with threshold = 50.
```
>>> threshold = 50
>>> reg_p2p = registration_icp(source, target, threshold, trans_init,
...         TransformationEstimationPointToPoint(),
...         ICPConvergenceCriteria(max_iteration = 200))
>>> print(reg_p2p)
RegistrationResult with fitness = 0.473684, inlier_rmse = 7.164259, and correspondence_set size of 9
Access transformation to get result.
>>> print("Transformation is:")
Transformation is:
>>> print(reg_p2p.transformation)
[[ 9.99999192e-01 -1.27143005e-03  0.00000000e+00  3.20034266e-01]
 [ 1.27143005e-03  9.99999192e-01  0.00000000e+00  4.53226325e+01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> draw_registration_result(source, target, reg_p2p.transformation)
```

It worked well. You don't have normals and the points are sparse, so point to point ICP makes more sense.

**Comment by JPeetersKUL** [comment]
Many thanks for your help. With the threshold at 5 it indeed works well! I would like to also use this method to find a best match between a 1 set of 2D points and several thousands of 2d points saved in a database. I found in other examples that there are two options of accelerating the search: 1 using KD trees and 2. using GPU (CUDA) processing. Does Open3D allows one of or both these options ?

**Comment by qianyizh** [comment]
Open3D by default is using flann with an optimized configuration as KDTree implementation for nearest neighbor queries.

For CUDA, it is not implemented in Open3D yet but Wei has a nice fork which implements many stuff in Open3D in GPU. You may want to check it out:
https://github.com/theNded/Open3D/
But setting up a fast nearest neighbor query algorithm in CUDA is quite complicated.
