### ISSUE TITLE
RegistrationColoredICP crashing when provided point clouds without normals

### ISSUE THREAD

**Issue by DarthBlitz** [intel-isl/Open3D#863]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
RegistrationColoredICP function does not error check for point clouds without normals. When given point clouds without normals the program will crash. See error below.

**To Reproduce**
1. Run RegistrationColoredICP function with an input point cloud that does not have normals.

**Expected behavior**
Error catch that displays message stating point cloud doesn't have normals and a null/void/default output of the function.

**Screenshots**

Error message:
![image](https://user-images.githubusercontent.com/48295684/53906951-23797300-401a-11e9-8108-09729f08224b.png)

Section of code where error occurs:
![image](https://user-images.githubusercontent.com/48295684/53907027-53c11180-401a-11e9-8840-31f165f74518.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 
 - Open3D version: 0.5.0
 - Is this remote workstation?: no
 - How did you install Open3D?: build_from_source (cmake and visual studio)

**Comment by mike239x** [comment]
I would argue with is not a bug but an undefined behavior - although point to plane ICP does inform the user about the lack of normals...

**Comment by qianyizh** [comment]
@syncle mind to take a look at this?

**Comment by keunhong** [comment]
When running colored ICP in a Jupyter notebook if normals aren't given then a warning is printed in the Jupyter log and the kernel dies rather than an exception being raised.

**Comment by tuwrraphael** [comment]
thanks @keunhong saved me a lot of time
