### ISSUE TITLE
UnitTest fix: no erros, no custom output/only gtest output

### ISSUE THREAD

**Issue by takanokage** [intel-isl/Open3D#866]
**Describe the bug**
HalfEdgeTriangleMesh test case may be bugged.
Eigen.SolveLinearSystemPSD unit test may be bugged.

**To Reproduce**
1. build open3d from source
2. run unit tests
3. See error

**Expected behavior**
- no error messages
- no other messages displayed except the googletest pass/fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/2706828/54043894-884fdd00-4182-11e9-97f8-55ac92f2b0b3.png)
![image](https://user-images.githubusercontent.com/2706828/54043955-aa495f80-4182-11e9-965b-9ee2a80509ec.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: unrelated
 - Open3D version: 0.0.5.0

**Comment by yxlao** [comment]
these are expected results, we can just remove the prints

**Comment by takanokage** [comment]
Yep, goggletest only messages is best as it avoids potential confusions.

**Comment by takanokage** [comment]
Please, when you have time, clean up the output of these unit tests and leave only googletest messages.

Not urgent.
