### ISSUE TITLE
Visualizer gets stuck on key callback

### ISSUE THREAD

**Issue by KeyMaster-** [intel-isl/Open3D#871]
**Describe the bug**
VisualizerWithKeyCallback does not call my callback when I press the key, and stops responding to any input.

**To Reproduce**
1. Load geometry
2. Run the `custom_draw_geometry_with_key_callback` function (from [here](http://www.open3d.org/docs/tutorial/Advanced/customized_visualization.html#use-callback-functions)) on it.
3. Press the K key
4. The window freezes, and no change happens.

**Expected behavior**
The background color changes to black, and the visualizer keeps running.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: OSX High Sierra 10.13.6
 - Python version: 3.7.2
 - Open3D version: 0.5.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Additional context**
This issue occurs with any uses of VisualizerWithKeyCallback, whether via draw_geometries_with_key_callbacks, or creating the class myself and running the rendering loop myself.

**Comment by germanros1987** [comment]
Could you provide us a minimum code example? I will close this in the meantime.
