### ISSUE TITLE
Clarification on transformation form

### ISSUE THREAD

**Issue by Jason420Git** [intel-isl/Open3D#872]
Hi,

I am looking for some clarification on the format of the transformation matrices passed through to the TSDF volume. It expects a pose for the extrinsics parameter of integrate()

We compute ICP transform using ICP. We then want to integrate a volume.
`open3d::RegistrationColoredICP(*srcSubsampled_ptr, *targetSubsampled_ptr, corrDist, priorTransform.cast<double>(), convergenceCriteria);`

However, the transforms we get from a series of clouds we then need to inverse to get it into the correct form for the TSDF integrate function. Can you give an explanation of what camera space is expected at both of these points please?

**Comment by Jason420Git** [comment]
I think the real question is to clarify if you expect transformations in forward or inverse kinematics. Are your transformations from origin -> sensor position, or sensor position -> origin.

**Comment by qianyizh** [comment]
It is sensor -> world.
Assume the transformation matrix is ``T``.
In sensor coordinate, you have a point ``p`` in homogeneous coordinates, then its world coordinate is ``Tp``
