### ISSUE TITLE
Fast Global registration poses are not as accurate as I need it to be

### ISSUE THREAD

**Issue by sunit1409** [intel-isl/Open3D#873]
Hey fellow, 
I am trying to register 2 point clouds using fast global registration but the results are not very convincing. The translation matrices are fine but the rotation matrices seem  to be little too off. Can you please help. I am uploading a few sample files for your perusal. 

https://drive.google.com/drive/folders/14pnGDYrMxx4qYPBG-_-4jCsA9rx6OELj?usp=sharing

@qianyizh   @yxlao

**Comment by mike239x** [comment]
@sunit1409 can you provide code sample as well?

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
