### ISSUE TITLE
PoseGraph: different result between Python and C++, why?

### ISSUE THREAD

**Issue by Joezzr** [intel-isl/Open3D#882]
I have some confusion and need help, thanks.
Here is my C++ code.

```cpp
const double max_correspondence_distance = 0.03;
PoseGraph pose_graph;

Eigen::Matrix4d odometry = Eigen::Matrix4d::Identity();
pose_graph.nodes_.push_back(PoseGraphNode(odometry));

for (int source_id = 0; source_id < modelNum; ++source_id)
{
    for (int target_id = source_id + 1; target_id < modelNum; ++target_id)
    {
        auto source = pcds[source_id];
        auto target = pcds[target_id];

        printf("Apply point-to-plane ICP\n");
        auto icp_coarse = RegistrationICP(*source, *target, max_correspondence_distance * 10, Eigen::Matrix4d::Identity(), TransformationEstimationPointToPlane());
        auto icp_fine = RegistrationICP(*source, *target, max_correspondence_distance, icp_coarse.transformation_, TransformationEstimationPointToPlane());
        //auto icp_fine = RegistrationICP(*source, *target, max_correspondence_distance, Eigen::Matrix4d::Identity(), TransformationEstimationPointToPlane());
        auto transformation_icp = icp_fine.transformation_;
        auto information_icp = GetInformationMatrixFromPointClouds(*source, *target, max_correspondence_distance, icp_fine.transformation_);
        std::cout << icp_fine.transformation_ << std::endl;
        //VisualizeRegistration(*source, *target, icp_fine.transformation_);

        printf("Build PoseGraph\n");
        if (target_id == source_id + 1) // # odometry case
        {
            
            odometry = transformation_icp * odometry;

            std::cout << "current odometry " << std::endl << odometry << std::endl;
            pose_graph.nodes_.push_back(PoseGraphNode(odometry.inverse()));
            pose_graph.edges_.push_back(PoseGraphEdge(source_id, target_id, transformation_icp, information_icp, false));
        }
        else//: # loop closure case
        {
            pose_graph.edges_.push_back(PoseGraphEdge(source_id, target_id, transformation_icp, information_icp, true));
        }
    }
}

printf("Optimizing PoseGraph ...\n");
GlobalOptimizationConvergenceCriteria criteria;
GlobalOptimizationOption option(max_correspondence_distance, 0.25, 0);
GlobalOptimizationLevenbergMarquardt optimization_method;
GlobalOptimization(pose_graph, optimization_method, criteria, option);

printf("Transform points and display\n");
std::vector<std::shared_ptr<const Geometry>> pcds2;

for (int point_id = 0; point_id < modelNum; ++point_id)
{
    std::cout << pose_graph.nodes_[point_id].pose_ << std::endl;
    //pcds[point_id]->Transform(pose_graph.nodes_[point_id].pose_);
    pcdsOri[point_id]->Transform(pose_graph.nodes_[point_id].pose_);
    //			visualizer.AddGeometry(pcds[point_id]);
    char fileName[128] = { '\0' };
    sprintf(fileName, "F:\\Test\\transformed_%d.xyzn", point_id);
    //WritePointCloudToXYZ(fileName, *(pcdsOri[point_id]), true);
    WritePointCloudToXYZN(fileName, *(pcdsOri[point_id]), true);
    pcds2.push_back(pcdsOri[point_id]);
}
```

test 1:  data(cloud_bin_0.pcd, cloud_bin_0.pcd, cloud_bin_0.pcd)
result:  almost the same resutl.
![image](https://user-images.githubusercontent.com/5101183/55076707-10b20580-50d1-11e9-84df-40acaaff2584.png)

test 2: data(afterReg_rangData_0.xyzn, afterReg_rangData_1.xyzn, afterReg_rangData_2.xyzn)
result: different matrix.
![image](https://user-images.githubusercontent.com/5101183/55076972-aa79b280-50d1-11e9-89f6-174feee6d511.png)

**Comment by Abelliu1** [comment]
Hi Joezzr,
I don't know whether your input data which was voxel down sample or not. If not,it should be voxeldownsample. I have try use the un-downsampled data for test, then the result is wrong.  After add the voxel downsample code,it works! maybe you can add the following code for test again:
auto voxel = open3d::geometry::VoxelDownSample(*input_pcd, 0.02);
		pcds.push_back(voxel);
My result see below[test data is cloud_bin_0.pcd, cloud_bin_1.pcd, cloud_bin_2.pcd ]:
![image](https://user-images.githubusercontent.com/15999497/55523844-739d3100-56bd-11e9-8c93-c96df6b2a2e1.png)
![image](https://user-images.githubusercontent.com/15999497/55523893-9a5b6780-56bd-11e9-9a54-131f7ea71abe.png)
![image](https://user-images.githubusercontent.com/15999497/55524182-fd99c980-56be-11e9-9a07-86fd126f4f7a.png)

Hope can help you!

**Comment by Joezzr** [comment]
> Hi Joezzr,
> I don't know whether your input data which was voxel down sample or not. If not,it should be voxeldownsample. I have try use the un-downsampled data for test, then the result is wrong. After add the voxel downsample code,it works! maybe you can add the following code for test again:
> auto voxel = open3d::geometry::VoxelDownSample(*input_pcd, 0.02);
> pcds.push_back(voxel);
> My result see below[test data is cloud_bin_0.pcd, cloud_bin_1.pcd, cloud_bin_2.pcd ]:
> ![image](https://user-images.githubusercontent.com/15999497/55523844-739d3100-56bd-11e9-8c93-c96df6b2a2e1.png)
> ![image](https://user-images.githubusercontent.com/15999497/55523893-9a5b6780-56bd-11e9-9a54-131f7ea71abe.png)
> ![image](https://user-images.githubusercontent.com/15999497/55524182-fd99c980-56be-11e9-9a07-86fd126f4f7a.png)
> 
> Hope can help you!

thanks for your test. I've just uploaded my test data(https://drive.google.com/drive/folders/1v44XtyUubRGG5WEL_th1BFN1S6EmCKej?usp=sharing).
Please try again, thanks!

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
