### ISSUE TITLE
Built-in python function wrappers for pcd.points, pcd.colors

### ISSUE THREAD

**Issue by chrischoy** [intel-isl/Open3D#883]
In python, a point cloud object does not support default built-in python functions such as __len__, __iter__, 
Currently, `len(pcd.points)` or `len(pcd.colors )` fail.

Let self be the Vector3dVector. Adding the following functions would make python usage easier.

```
def __len__(self):
   return self.num()

def __iter__(self):
  arr = np.array(self)
  for i in range(len(self)):
    yield arr[i]
```

**Comment by syncle** [comment]
> Currently, ``len(pcd.points)`` or ``len(pcd.colors )`` fail.

Could you double check if this is true? This is my counter example.

```
>>> from open3d import *
>>> pcd = PointCloud()
>>> len(pcd.points)
0
>>> len(pcd.colors)
0

>>> pcd.points = Vector3dVector(np.zeros((100,3)))
>>> print(pcd)
PointCloud with 100 points.
>>> len(pcd.points)
100
```

**Comment by syncle** [comment]
and ``iter`` should work as well.
```
>>> for p in pcd.points:
>>>   print(p)
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
:
```
