### ISSUE TITLE
Trouble with screen_capture_image

### ISSUE THREAD

**Issue by Prashant3282** [intel-isl/Open3D#891]
I'm currently writing a script to take a ply file and create a custom trajectory to view all sides of the model and turn it into a gif. Here is the script right now:

    import os
    from open3d import *
    import numpy as np
    import matplotlib.pyplot as plt
    import imageio
    import argparse

    def iterate(vis, ctr, x, y, i):

        ctr.rotate(x,y)
        vis.update_geometry()
        vis.poll_events()
        vis.update_renderer()
        vis.capture_screen_image("%04d.jpg" % i)

    def custom_draw_geometry(pcd):
   
        vis = Visualizer()
        vis.create_window()
        vis.add_geometry(pcd)
        ctr = vis.get_view_control()

        for i in range(350):

            if i >= 0 and i < 100:
                iterate(vis, ctr, 10.0, 0.0, i)
            elif i >= 100 and i < 110:
                iterate(vis, ctr, 9.0, 1.0, i)
            elif i >= 110 and i < 120:
                iterate(vis, ctr, 8.0, 2.0, i)
            elif i >= 120 and i < 130:
                iterate(vis, ctr, 6.0, 4.0, i)
            elif i >= 130 and i < 140:
                iterate(vis, ctr, 4.0, 6.0, i)
            elif i >= 140 and i < 150:
                iterate(vis, ctr, 2.0, 8.0, i)
            elif i >= 150 and i < 160:
                iterate(vis, ctr, 1.0, 9.0, i)
            elif i >= 160 and i < 180:
                iterate(vis, ctr, 0.0, 10.0, i)
            elif i >= 180 and i < 190:
                iterate(vis, ctr, -1.0, 9.0, i)
            elif i >= 190 and i < 200:
                iterate(vis, ctr, -2.0, 8.0, i)
            elif i >= 200 and i < 210:
                iterate(vis, ctr, -4.0, 6.0, i)
            elif i >= 210 and i < 220:
                iterate(vis, ctr, -5.0, 5.0, i)
            elif i >= 220 and i < 230:
                iterate(vis, ctr, -6.0, 4.0, i)
            elif i >= 230 and i < 240:
                iterate(vis, ctr, -7.0, 3.0, i)
            elif i >= 240 and i < 250:
                iterate(vis, ctr, -8.0, 2.0, i)
            elif i >= 250 and i < 260:
                iterate(vis, ctr, -9.0, 1.0, i)
            elif i >= 260 and i < 350:
                iterate(vis, ctr, -10.0, 0.0, i)

        vis.destroy_window()

    def main():

        parser = argparse.ArgumentParser()
        parser.add_argument('--ply_path', type=str, default='')

        args = parser.parse_args()
        pcdDIR = args.ply_path

        pcd = read_point_cloud(pcdDIR)
        custom_draw_geometry(pcd)

        images = []
        for i in range(350):
            image_name = "%04d.jpg" % i
            images.append(imageio.imread(image_name))
        imageio.mimsave("output/visualize.gif", images)

    if __name__ == '__main__':
        main()

My main issue here is that the screen capture isn't working. The program will execute that line, but there are no error messages and the image doesn't appear in the directory. Is there something wrong with how I'm using the screen capture?

**Comment by qianyizh** [comment]
The code is correct. I just tested on my machine. The jpg files are created.
```
> python test.py --ply_path ../Open3D/examples/TestData/fragment.ply
Reading PLY: [========================================] 100%

> ls
0000.jpg  0030.jpg  0060.jpg  0090.jpg  0120.jpg  0150.jpg  0180.jpg  0210.jpg  0240.jpg  0270.jpg  0300.jpg  0330.jpg
0001.jpg  0031.jpg  0061.jpg  0091.jpg  0121.jpg  0151.jpg  0181.jpg  0211.jpg  0241.jpg  0271.jpg  0301.jpg  0331.jpg
0002.jpg  0032.jpg  0062.jpg  0092.jpg  0122.jpg  0152.jpg  0182.jpg  0212.jpg  0242.jpg  0272.jpg  0302.jpg  0332.jpg
0003.jpg  0033.jpg  0063.jpg  0093.jpg  0123.jpg  0153.jpg  0183.jpg  0213.jpg  0243.jpg  0273.jpg  0303.jpg  0333.jpg
0004.jpg  0034.jpg  0064.jpg  0094.jpg  0124.jpg  0154.jpg  0184.jpg  0214.jpg  0244.jpg  0274.jpg  0304.jpg  0334.jpg
0005.jpg  0035.jpg  0065.jpg  0095.jpg  0125.jpg  0155.jpg  0185.jpg  0215.jpg  0245.jpg  0275.jpg  0305.jpg  0335.jpg
0006.jpg  0036.jpg  0066.jpg  0096.jpg  0126.jpg  0156.jpg  0186.jpg  0216.jpg  0246.jpg  0276.jpg  0306.jpg  0336.jpg
0007.jpg  0037.jpg  0067.jpg  0097.jpg  0127.jpg  0157.jpg  0187.jpg  0217.jpg  0247.jpg  0277.jpg  0307.jpg  0337.jpg
0008.jpg  0038.jpg  0068.jpg  0098.jpg  0128.jpg  0158.jpg  0188.jpg  0218.jpg  0248.jpg  0278.jpg  0308.jpg  0338.jpg
0009.jpg  0039.jpg  0069.jpg  0099.jpg  0129.jpg  0159.jpg  0189.jpg  0219.jpg  0249.jpg  0279.jpg  0309.jpg  0339.jpg
0010.jpg  0040.jpg  0070.jpg  0100.jpg  0130.jpg  0160.jpg  0190.jpg  0220.jpg  0250.jpg  0280.jpg  0310.jpg  0340.jpg
0011.jpg  0041.jpg  0071.jpg  0101.jpg  0131.jpg  0161.jpg  0191.jpg  0221.jpg  0251.jpg  0281.jpg  0311.jpg  0341.jpg
0012.jpg  0042.jpg  0072.jpg  0102.jpg  0132.jpg  0162.jpg  0192.jpg  0222.jpg  0252.jpg  0282.jpg  0312.jpg  0342.jpg
0013.jpg  0043.jpg  0073.jpg  0103.jpg  0133.jpg  0163.jpg  0193.jpg  0223.jpg  0253.jpg  0283.jpg  0313.jpg  0343.jpg
0014.jpg  0044.jpg  0074.jpg  0104.jpg  0134.jpg  0164.jpg  0194.jpg  0224.jpg  0254.jpg  0284.jpg  0314.jpg  0344.jpg
0015.jpg  0045.jpg  0075.jpg  0105.jpg  0135.jpg  0165.jpg  0195.jpg  0225.jpg  0255.jpg  0285.jpg  0315.jpg  0345.jpg
0016.jpg  0046.jpg  0076.jpg  0106.jpg  0136.jpg  0166.jpg  0196.jpg  0226.jpg  0256.jpg  0286.jpg  0316.jpg  0346.jpg
0017.jpg  0047.jpg  0077.jpg  0107.jpg  0137.jpg  0167.jpg  0197.jpg  0227.jpg  0257.jpg  0287.jpg  0317.jpg  0347.jpg
0018.jpg  0048.jpg  0078.jpg  0108.jpg  0138.jpg  0168.jpg  0198.jpg  0228.jpg  0258.jpg  0288.jpg  0318.jpg  0348.jpg
0019.jpg  0049.jpg  0079.jpg  0109.jpg  0139.jpg  0169.jpg  0199.jpg  0229.jpg  0259.jpg  0289.jpg  0319.jpg  0349.jpg
0020.jpg  0050.jpg  0080.jpg  0110.jpg  0140.jpg  0170.jpg  0200.jpg  0230.jpg  0260.jpg  0290.jpg  0320.jpg  test.py
0021.jpg  0051.jpg  0081.jpg  0111.jpg  0141.jpg  0171.jpg  0201.jpg  0231.jpg  0261.jpg  0291.jpg  0321.jpg
0022.jpg  0052.jpg  0082.jpg  0112.jpg  0142.jpg  0172.jpg  0202.jpg  0232.jpg  0262.jpg  0292.jpg  0322.jpg
0023.jpg  0053.jpg  0083.jpg  0113.jpg  0143.jpg  0173.jpg  0203.jpg  0233.jpg  0263.jpg  0293.jpg  0323.jpg
0024.jpg  0054.jpg  0084.jpg  0114.jpg  0144.jpg  0174.jpg  0204.jpg  0234.jpg  0264.jpg  0294.jpg  0324.jpg
0025.jpg  0055.jpg  0085.jpg  0115.jpg  0145.jpg  0175.jpg  0205.jpg  0235.jpg  0265.jpg  0295.jpg  0325.jpg
0026.jpg  0056.jpg  0086.jpg  0116.jpg  0146.jpg  0176.jpg  0206.jpg  0236.jpg  0266.jpg  0296.jpg  0326.jpg
0027.jpg  0057.jpg  0087.jpg  0117.jpg  0147.jpg  0177.jpg  0207.jpg  0237.jpg  0267.jpg  0297.jpg  0327.jpg
0028.jpg  0058.jpg  0088.jpg  0118.jpg  0148.jpg  0178.jpg  0208.jpg  0238.jpg  0268.jpg  0298.jpg  0328.jpg
0029.jpg  0059.jpg  0089.jpg  0119.jpg  0149.jpg  0179.jpg  0209.jpg  0239.jpg  0269.jpg  0299.jpg  0329.jpg
```

Can you check if it is the write permission or something else?

**Comment by Prashant3282** [comment]
@qianyizh I gave the file write permissions using chmod +w but still no images are being written. I'm just using my regular home directory. Did you run with sudo?

**Comment by qianyizh** [comment]
No.

Maybe try a minimal example. In Python console, read a file, write a file. See if this works.
