### ISSUE TITLE
Support for 3DMatch Dataset

### ISSUE THREAD

**Issue by XuyangBai** [intel-isl/Open3D#892]
I wonder whether Open3D has support for [3DMatch](http://3dmatch.cs.princeton.edu/) Dataset? I searched in the document but found nothing.

**Comment by yxlao** [comment]
Specifically, which dataset are you looking for? We do have a [SUN3D](http://www.open3d.org/docs/python_api/open3d.geometry.create_rgbd_image_from_sun_format.html#open3d.geometry.create_rgbd_image_from_sun_format) loader which is used in 3DMatch.

For the full list of RGBD loader, please refer to [RGBDImageFactory.cpp](https://github.com/IntelVCL/Open3D/blob/master/src/Open3D/Geometry/RGBDImageFactory.cpp). It shall be straight forward to extend it for a new dataset.
