### ISSUE TITLE
VisualizerWithEditing: No filename is given. Abort saving.

### ISSUE THREAD

**Issue by noscript** [intel-isl/Open3D#894]
**Describe the bug**
Python's `VisualizerWithEditing` doesn't bring up save file dialog.

**To Reproduce**
1. `pip3 install open3d-python`
2.
 ```python
#!/usr/bin/python3

from open3d import *

if __name__ == "__main__":
    pcd = read_point_cloud("./examples/TestData/fragment.ply")
    vis = VisualizerWithEditing()
    vis.create_window()
    vis.add_geometry(pcd)
    vis.run()
    vis.destroy_window()
```
3. Press <kbd>K</kbd>, select a square area, press <kbd>C</kbd>.
4. Error:
```
Cropping geometry: [========================================] 100%
No filename is given. Abort saving.
```

**Expected behavior**
A dialog to save file pops up.

**Environment:**
 - OS: Ubuntu 18.04
 - Python version: 3.6.5
 - Open3D version: 0.6.0.0-cp36
 - Is this remote workstation?: no
 - How did you install Open3D?: pip3

**Additional context**
It would be nice to be have API to `VisualizerWithEditing` to set a fixed file name for storing crop results.

**Comment by noscript** [comment]
The issue was that I that I'm running a non-interactive shell, otherwise ncurses interface shows a dialog to enter file name. But it would be still nice to allow a fixed file name.

**Comment by yxlao** [comment]
How did you run on "non-interactive shell", could you share the procedure? It works for me for both cases: 1) running it as a `.py` script, or 2) in a python interactive shell.

**Comment by noscript** [comment]
I run it an external command in vim `:!./crop_save_fail.py`.

**Comment by yxlao** [comment]
Also, looks like the python path is hardcoded, is open3d installed in the environment of `#!/usr/bin/python3`?

**Comment by noscript** [comment]
I changed it to `#!/usr/bin/env python3` but it didn't make any difference.

**Comment by griegler** [comment]
Actually, you can avoid the file dialog by changing the constructor to `vis = VisualizerWithEditing(-1, False, "")`. In the last string parameter you could also define a default directory (otherwise the `cwd` will be used).

**Comment by fabiopoiesi** [comment]
> Actually, you can avoid the file dialog by changing the constructor to `vis = VisualizerWithEditing(-1, False, "")`. In the last string parameter you could also define a default directory (otherwise the `cwd` will be used).

What is the meaning of these parameters?
