### ISSUE TITLE
GLFW Error: GLX: Failed to create context: GLXBadFBConfig

### ISSUE THREAD

**Issue by AbhiDarisi** [intel-isl/Open3D#897]
I'm trying to see the results of (https://github.com/fregu856/3DOD_thesis) 3d object detection on kitti data set.In this, open3d is used for the visualization part of 3d bounding boxes. I'm getting the below mentioned error while running visualize_eval_test.py:

**part of code creating error:**
inside visualize_eval_test.py:
def draw_geometries_dark_background(geometries):
    print("inside draw_geometries_dark_background")
    vis = open3d.visualization.Visualizer()
    **vis.create_window()**
    opt = open3d.visualization.RenderOption()
    opt.background_color = np.asarray([0, 0, 0])
    for geometry in geometries:
        vis.add_geometry(geometry)
    vis.run()
    vis.destroy_window()

**error:**
$python visualization/visualize_eval_test.py
**GLFW Error: GLX: Failed to create context: GLXBadFBConfig
Failed to create window
Segmentation fault (core dumped)**

**Environment:**
 - OS: Ubuntu 16.04 [e.g. OSX Mojave, Ubuntu 16.04, Windows 10.0]
 - Python version: Python 3.5.2
 - Open3D version:0.5.0.0
 - I'm using a GPU using SSH.
 - How did you install Open3D?: pip

Any solution for this?

Regards
Abhi

**Comment by qianyizh** [comment]
ssh into a remote server is a headless use case.
The visualizer expect you have a monitor.
(After all, without a monitor and a mouse, how do you interact with the visualizer, :)

However, if you have a predefined animation, you can run headless rendering.
Check this out:
http://www.open3d.org/docs/tutorial/Advanced/headless_rendering.html

**Comment by maxjaritz** [comment]
@qianyizh Why isn't it possible to forward via X11? For matplotlib, it works to have an interactive window via SSH -X, given the environment variable DISPLAY is correctly configured. In order to test OpenGL, I tried glxgears with remote rendering and it also works. However, for open3d, the error I get is:
```
GLFW Error: GLX: GLX version 1.3 is required
Failed to create window
[DrawGeometries] Failed creating OpenGL window.
```

**Comment by qianyizh** [comment]
umm, interesting, last time I checked it worked well with X-window. Not sure about its current status though. @syncle any comment on this?

**Comment by bakar-a** [comment]
Hi guys, having a similar problem using XRDP. Any updates on this by any chance?

**Comment by huangkuns** [comment]
> @qianyizh Why isn't it possible to forward via X11? For matplotlib, it works to have an interactive window via SSH -X, given the environment variable DISPLAY is correctly configured. In order to test OpenGL, I tried glxgears with remote rendering and it also works. However, for open3d, the error I get is:
> 
> ```
> GLFW Error: GLX: GLX version 1.3 is required
> Failed to create window
> [DrawGeometries] Failed creating OpenGL window.
> ```

Hi, have you ever figured out how to forward x11 without glx version error message?

**Comment by tkasarla** [comment]
Have same error that glx version 1.3 is required. My local Ubuntu (in WSL) has glx version 1.2. How do I update to 1.3? 

> 
> 
> @qianyizh Why isn't it possible to forward via X11? For matplotlib, it works to have an interactive window via SSH -X, given the environment variable DISPLAY is correctly configured. In order to test OpenGL, I tried glxgears with remote rendering and it also works. However, for open3d, the error I get is:
> 
> ```
> GLFW Error: GLX: GLX version 1.3 is required
> Failed to create window
> [DrawGeometries] Failed creating OpenGL window.
> ```

**Comment by rancheng** [comment]
> > @qianyizh Why isn't it possible to forward via X11? For matplotlib, it works to have an interactive window via SSH -X, given the environment variable DISPLAY is correctly configured. In order to test OpenGL, I tried glxgears with remote rendering and it also works. However, for open3d, the error I get is:
> > ```
> > GLFW Error: GLX: GLX version 1.3 is required
> > Failed to create window
> > [DrawGeometries] Failed creating OpenGL window.
> > ```
> 
> Hi, have you ever figured out how to forward x11 without glx version error message?

I have the same question, I need to forward rviz through ssh...

**Comment by Angericky** [comment]
> Have same error that glx version 1.3 is required. My local Ubuntu (in WSL) has glx version 1.2. How do I update to 1.3?
> 
> > @qianyizh Why isn't it possible to forward via X11? For matplotlib, it works to have an interactive window via SSH -X, given the environment variable DISPLAY is correctly configured. In order to test OpenGL, I tried glxgears with remote rendering and it also works. However, for open3d, the error I get is:
> > ```
> > GLFW Error: GLX: GLX version 1.3 is required
> > Failed to create window
> > [DrawGeometries] Failed creating OpenGL window.
> > ```

Hello, have you solved the problem? I met the same situation and didn't find solution..

**Comment by YangJae96** [comment]
This is really difficult problem. Did any of you guys solved the headless rendering issue..
GLFW Error: GLX: GLX version 1.3 is required
Failed to create window
[DrawGeometries] Failed creating OpenGL window.

I keep getting this Error

**Comment by germanros1987** [comment]
This issue should be solved in the latest release of Open3D.

**Comment by meder411** [comment]
> This issue should be solved in the latest release of Open3D.

Which release is that? I'm still getting this issue with version 0.10 as installed via `pip`. Would a source install resolve this for me?

**Comment by blarkj** [comment]
Still facing a similar issue. Using open3d version 0.11.2

**Comment by JoaoAVDuarte** [comment]
> Still facing a similar issue. Using open3d version 0.11.2

Same issue here, with the same version

**Comment by MoritzZa** [comment]
I also have the same problems with open3d 0.11.2.

**Comment by Liuchongpei** [comment]
I also have the same problems with open3d **0.12.0.**

**Comment by Rschleyen** [comment]
same issue with open3d version 0.12.0

**Comment by scimad** [comment]
same issue with open3d version 0.12.0

**Comment by dcy0577** [comment]
@maxjaritz Hi, did you solve this issue? I was running your mvpnet code via SSH -X and got exactly the same issue mentioned here when trying to visualize the result. Btw thanks for your fantastic work!

> @qianyizh Why isn't it possible to forward via X11? For matplotlib, it works to have an interactive window via SSH -X, given the environment variable DISPLAY is correctly configured. In order to test OpenGL, I tried glxgears with remote rendering and it also works. However, for open3d, the error I get is:
> 
> ```
> GLFW Error: GLX: GLX version 1.3 is required
> Failed to create window
> [DrawGeometries] Failed creating OpenGL window.
> ```

**Comment by maxjaritz** [comment]
Thanks :) 

No, sorry :(
However, I also did not try for a long time.

**Comment by maxjaritz** [comment]
> @maxjaritz Hi, did you solve this issue? I was running your mvpnet code via SSH -X and got exactly the same issue mentioned here when trying to visualize the result. Btw thanks for your fantastic work!
> 
> > @qianyizh Why isn't it possible to forward via X11? For matplotlib, it works to have an interactive window via SSH -X, given the environment variable DISPLAY is correctly configured. In order to test OpenGL, I tried glxgears with remote rendering and it also works. However, for open3d, the error I get is:
> > ```
> > GLFW Error: GLX: GLX version 1.3 is required
> > Failed to create window
> > [DrawGeometries] Failed creating OpenGL window.
> > ```

Thanks :)

No, sorry :(
However, I also did not try for a long time.

**Comment by nairouzshehata** [comment]
Same here! using x2go ang]d getting same messages with open3d 0.12.0

**Comment by davodogster** [comment]
@germanros1987 why is this issue closed? Lot's of people still face the issue including me

**Comment by schauppi** [comment]
i have the sam issue - open3d version 0.13.0

**Comment by 459737087** [comment]
0.14.1仍然有这个问题

**Comment by fhandke-fugro** [comment]
Same issue with 0.14.1 trying to run on WSL2 together with X11 forwarding. Would be helpful to fix this.

**Comment by enting8696** [comment]
My open3d version : 0.11.2
and use Ubuntu18.04 in  Oracle VM VirtualBox
![pic_00000](https://user-images.githubusercontent.com/59861551/169455071-3fac3e67-cd80-48e0-b8c6-9475ddf3c58d.png)

still error , could any one give some advice for Ubuntu not for Windows ?

**Comment by RainEggplant** [comment]
This [answer](https://stackoverflow.com/a/66506098) helped me out.

**Comment by EZreal-zhangxing** [comment]
same issue, And open3d vision：0.14.1
![image](https://user-images.githubusercontent.com/8359625/178885956-332193be-55bb-4494-8c7e-d773747b8650.png)

**Comment by YananJian** [comment]
## Env
I'm using WSL on windows and visualizing pointcloud through jupyter notebook running inside my Ubuntu app.
## Findings
**Xming** gave me the `GLX version 1.3 is required` error.
After switching to **vcxsrv** the GLX version error disappeared but `GLXBadFBConfig `error surfaced up. 

Then I followed this answer https://stackoverflow.com/a/66645230 to setup X. 
Some minor changes from the stackoverflow answer: as @RainEggplant suggested, set `export LIBGL_ALWAYS_INDIRECT=0`. </br>
The Calculator app never worked on my side, but if you see the key outputs from glxinfo matching what's described here https://stackoverflow.com/a/66506098, you are good to go. Now I can visualize pointclouds with open3d launched from a jupyter notebook inside WSL.

**Comment by tomas-aftalion** [comment]
same issue, version 0.15.1

**Comment by zhangyun2743** [comment]
> ## Env
> I'm using WSL on windows and visualizing pointcloud through jupyter notebook running inside my Ubuntu app.
> 
> ## Findings
> **Xming** gave me the `GLX version 1.3 is required` error. After switching to **vcxsrv** the GLX version error disappeared but `GLXBadFBConfig `error surfaced up.
> 
> Then I followed this answer https://stackoverflow.com/a/66645230 to setup X. Some minor changes from the stackoverflow answer: as @RainEggplant suggested, set `export LIBGL_ALWAYS_INDIRECT=0`. The Calculator app never worked on my side, but if you see the key outputs from glxinfo matching what's described here https://stackoverflow.com/a/66506098, you are good to go. Now I can visualize pointclouds with open3d launched from a jupyter notebook inside WSL.

thank you~~~. I also have met this problem and by tring your suggestion, vcxsrv can display images normal, that is amazing.

**Comment by Miladiouss** [comment]
I'm having the same issue on Ubuntu via python:

![image](https://user-images.githubusercontent.com/20514398/193168526-0d2f6c9f-b196-491d-9ff6-356aa288c6fa.png)

**Comment by 459737087** [comment]
Why not reopening this bug @qianyizh

**Comment by demul** [comment]
Why not reopening this bug @qianyizh

**Comment by zjr-bit** [comment]
I use the GPU by ssh on Ubuntu18.04. I met the same issue `GLX version 1.3 is required` using Xming. And I switch to vcxsrv then it works well like https://github.com/isl-org/Open3D/issues/897#issuecomment-1203354342. 
Hope this will help you all.

**Comment by z1xy2** [comment]
The key to make open3d work is  make open3d communication with GPU directly .

export LIBGL_ALWAYS_INDIRECT=0
​​​​ ​​​​​​and in x-server don not use native opengl
![QQ截图20230427221140](https://user-images.githubusercontent.com/67009385/234888712-f69f0aff-2109-4b11-8329-3f89943f4761.png)

these tow steps enable open3d communication with GPU directly .
now open3d workes well in my wsl on x-server

**Comment by RepublicHo** [comment]
We are still faced with this issue. it is disappointing to see that it was closed without a satisfactory resolution...

**Comment by A3itor** [comment]
Is this really going to be closed forever when everybody is still facing the issue in 2023???

**Comment by KJYoung** [comment]
@z1xy2's solution perfectly worked for my Windows10-WSL2(Ubuntu20.04) Settings.
Open3D Windows successfully created! Thanks!

**Comment by A3itor** [comment]
> We are still faced with this issue. it is disappointing to see that it was closed without a satisfactory resolution...

Ok, so I had to do do so many workarounds on my python pipeline to make it work. If you import torch from the file BEFORE you import open3d and visualize a window it will not work. To my understanding this feels like the GPU resources are being reserved for torch and they are locked for open3D. Make sure torch is not first imported by any module that is imported

**Comment by kiesed** [comment]
Still facing the issue even after trying all solutions proposed in this thread
```
[Open3D WARNING] GLFW Error: GLX: Failed to create context: GLXBadFBConfig
[Open3D WARNING] Failed to create window
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

**Comment by 2019211753** [comment]
> 即使尝试了该线程中提出的所有解决方案后仍然面临问题
> 
> ```
> [Open3D WARNING] GLFW Error: GLX: Failed to create context: GLXBadFBConfig
> [Open3D WARNING] Failed to create window
> [Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.
> libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: swrast
> ```
> 
> 在 ubuntu 服务器上使用 open3d 0.17.0，使用 nvidia 显卡（最新支持的驱动程序）运行 jupyter 服务器和 Windows 10 客户端

same with u. RTX4090 & open3d 0.17.0

**Comment by Boxxfish** [comment]
> > We are still faced with this issue. it is disappointing to see that it was closed without a satisfactory resolution...
> 
> Ok, so I had to do do so many workarounds on my python pipeline to make it work. If you import torch from the file BEFORE you import open3d and visualize a window it will not work. To my understanding this feels like the GPU resources are being reserved for torch and they are locked for open3D. Make sure torch is not first imported by any module that is imported

This along with exporting `LIBGL_ALWAYS_INDIRECT=0` works for me as well. For reference, I'm on Ubuntu WSL2.

**Comment by TingmanYan** [comment]
`libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[Open3D WARNING] GLFW Error: GLX: Failed to create context: GLXBadFBConfig
[Open3D WARNING] Failed to create window
`
I'm working on a ubuntu server with nvidia graphic card and using conda to setup the python environment. The error is caused by libstdc++.so version used by conda is different from that of the system. I replaced the libstdc++.so of the virtual env with the system version and it works. The solution is referenced from [https://askubuntu.com/questions/1352158/libgl-error-failed-to-load-drivers-iris-and-swrast-in-ubuntu-20-04](here)

**Comment by whyn0tdance** [comment]
same issue , has anybody's been sovled?

**Comment by Atticuszz** [comment]
see here ,it works for me https://github.com/isl-org/Open3D/issues/5126#issuecomment-2024590081

**Comment by jaycions** [comment]
According to https://stackoverflow.com/questions/74774761/problem-with-x-display-when-open3d-draw-geometry-used, if you only use "o3d.visualization.draw" function, just change it to "o3d.visualization.draw_plotly" and it works fine for me.

**Comment by Abbsalehi** [comment]
It worked for by this:
see this #5126

**Comment by ErTen-6** [comment]
If none of the above attempts work, you can change the Mesa driver, just add this `export MESA_LOADER_DRIVER_OVERRIDE=llvmpipe` and `export GALLIUM_DRIVER=llvmpipe` before running the program, or add this to `~/.bashrc`

**Comment by Mengqi97** [comment]
![Image](https://github.com/user-attachments/assets/26960523-4e05-4afa-8181-f36d1753ab35)

This is my error. I seem to have solved the problem using the following code. I'm not entirely sure, but it's worth a try.

```bash
conda install -c conda-forge mesalib  
```
