### ISSUE TITLE
Cannot update view angle during loop

### ISSUE THREAD

**Issue by ljc19800331** [intel-isl/Open3D#910]
Hello, 

I have issue changing the view point when I do the animation. I update the pcd point cloud every step and I want to change the view angle when I created the vis window at the beginning. However, the result doesn't show a change of view angle and it is still the same. Here is my code. Thanks.

This is the script:

import open3d
import numpy as np

// Initialized the values
// Load the 3D point cloud of the object
pts_use = np.load('/home/mgs/PycharmProjects/IV_Vessel/edge.npy')
pts_use = pts_use[0]
geometrie_added = False
vis = open3d.Visualizer()
vis.create_window("Test")
ctr = vis.get_view_control()
// ctr.rotate(100.0, 0.0)
pcd = open3d.PointCloud()
ctr.change_field_of_view(step = 200.0)
// vis.run()

count = 0
// Load the 3D point cloud of the object
edge = np.load('/home/mgs/PycharmProjects/IV_Vessel/edge.npy')
vis.add_geometry(pcd)
for i in range(len(edge) - 1):
    print(count)
    pcd.clear()
    pcd.points = open3d.Vector3dVector(pts_use)
    vis.update_geometry()
    vis.poll_events()
    image = vis.capture_screen_float_buffer()
    pts_use = np.vstack([pts_use, edge[count + 1]])
    if not geometrie_added:
        vis.add_geometry(pcd)
        geometrie_added = True
    count += 1

**Comment by qianyizh** [comment]
Can you paste the full script so I can duplicate it?

**Comment by ljc19800331** [comment]
> Can you paste the full script so I can duplicate it?

yes sure @qianyizh . The script is attached but the .npy file is not able to be uploaded. The point cloud plotter becomes slow when the more point cloud are shown. I checked multiple time but not sure what is the problem. Thanks for your help.

**Comment by germanros1987** [comment]
@ljc19800331 did you manage to solve the problem?

**Comment by germanros1987** [comment]
This feature is available in Open3D 0.11, using the new Python rendering API.
