### ISSUE TITLE
read_point_cloud to read PTS file without header and float intensity

### ISSUE THREAD

**Issue by YouYue123** [intel-isl/Open3D#913]
**Is your feature request related to a problem? Please describe.**

Some point cloud software will generate PTS file without header. This is quite common recently from our client using Recap.

**Describe the solution you'd like**

read_point_cloud should be able to handle this file without taking the first number as amount of points.

**Describe alternatives you've considered**

A preprocessing programme to validate and add total amount as head if needed.

**Comment by YouYue123** [comment]
Like reading a PTS file , the current function can not process it correctly

![Screenshot 2019-04-17 at 11 21 39 AM](https://user-images.githubusercontent.com/8738486/56276573-08af1980-6103-11e9-9977-51732e5e3614.png)

I think there are 2 issues here.

1. read_point_cloud assumes PTS file is as (%lf, %lf, %lf, %d, %d, %d) for each line
 
2. read_point_cloud assumes the first number is always the amount of points. 

I think read_point_cloud should do a validation about this assumption first

**Comment by qianyizh** [comment]
Yeah. The true problem is that PTS is a poorly designed file format. Different hardware vendors have different definitions. When I wrote the IO for PTS file, all my knowledge was based on a FARO laser scanner. The PTS format is just too bad.

In your use case, I think you can rename your file to xyz, then Open3D should be able to load it, at least the geometry part.

**Comment by YouYue123** [comment]
That could be an alternative solution.  But have you considered to change the implementation of PTS reader in a more error-tolerance way like reading every number as string first then parsing it to the corresponding type. 

https://github.com/intel-isl/Open3D/blob/e8517a6902b4979fdadb2bd526aa0b66e621e203/src/Open3D/IO/FileFormat/FilePTS.cpp#L75-L85

**Comment by qianyizh** [comment]
I would like to have a more standard specification of the pts format then we can work on that. Otherwise it is hard for us to actually make it compatible.

**Comment by germanros1987** [comment]
I don't see a way to cover this feature. I am closing this issue.
