### ISSUE TITLE
Color map optimisation not working properly 

### ISSUE THREAD

**Issue by abuzaina** [intel-isl/Open3D#916]
I am using the color_map_optimization.py example for texturing. I am able to generate a point cloud from rgbd image.  The point cloud fits perfectly to the mesh after applying the transformation. Please see image below.
![image](https://user-images.githubusercontent.com/6253920/56326580-6eaf9700-612b-11e9-8a0e-1f7d3b720b6a.png)

However when I use the same transformation matrix in color_map_optimization to do texturing  I get this result. 
![image](https://user-images.githubusercontent.com/6253920/56326627-a4ed1680-612b-11e9-9e5d-998f92e35725.png)

Which is totally off. It does not make any sense to me. Any ideas ?

**Comment by yxlao** [comment]
Could you provide more information?
- Did you get the expected outputs by running the color map optimization example?
- "I am able to generate a point cloud from rgbd image.": how did you generate the point cloud? 
- "The point cloud fits perfectly to the mesh after applying the transformation.": how is the mesh generated and what's the relation among the "mesh", the "point cloud" and "rgbd image"?
- "However when I use the same transformation matrix in color_map_optimization to do texturing I get this result.": How did you use color_map_optimization and how did you apply transformation?
- As a sanity check, the `color_map_optimization.py` creates the default color mapping with 0 iterations, this, in theory, should produce blurry but roughly aligned results, what are the results with 0 iteration in your dataset?

**Comment by abuzaina** [comment]
hi @yxlao ,
- Yes I get the expected outputs by running the color map optimization example on the fountain dataset.
- I've generated the point cloud using first create_rgbd_image_from_color_and_depth, then create_point_cloud_from_rgbd_image, exactly like color map optimization example.
- The mesh generated by a custom code. I've tested it with other texturing algorithms with the same image and camera geometries and it gave the expected results. So there is no error in the mesh or the image or in the camera parameters. 
- I used it exactly like the example, I just edited the example to put my data. The only difference is that the depth map I have is in raw format and has a scale of 10000, which is accounted for in the code.
- I am aware of the iterations, here are the results of 0 iterations and 300 iterations respectively. 
-- I attach the data and my code so please try to re-generate. 
[anas.zip](https://github.com/intel-isl/Open3D/files/3099450/anas.zip)

![image](https://user-images.githubusercontent.com/6253920/56446134-bfeb9200-62b5-11e9-99af-123d563f9f5a.png)
![image](https://user-images.githubusercontent.com/6253920/56446202-1953c100-62b6-11e9-9f0d-ac71b54c6358.png)

**Comment by abuzaina** [comment]
@yxlao any luck with running it on my data ?

**Comment by abuzaina** [comment]
@yxlao any luck with running it on my data ?

**Comment by abuzaina** [comment]
I figured out the issue, needed to edit camera.parameters[i].intrinsic.intrinsic_matrix
