### ISSUE TITLE
Inaccuracy in  information matrix calculation

### ISSUE THREAD

**Issue by ohadmen** [intel-isl/Open3D#917]
calculation of information matrix in (Open3D/Registration/Registration.cpp@374) is inconsistent with documentation.
according to: http://redwood-data.org/indoor/registration.html, matrices, matrix init at line 392 and 387 should be zero, and not identity

**Comment by qianyizh** [comment]
I think you are right.
@syncle take a look?
https://github.com/intel-isl/Open3D/blob/e8517a6902b4979fdadb2bd526aa0b66e621e203/src/Open3D/Registration/Registration.cpp#L392
This line should be:
```
    Eigen::Matrix6d GTG = Eigen::Matrix6d::Zero();
```
