### ISSUE TITLE
AttributeError: 'open3d.open3d.camera.PinholeCameraTrajectory' object has no attribute 'intrinsic'

### ISSUE THREAD

**Issue by tianchengdw** [intel-isl/Open3D#920]
Hey, Guys! I met an error when I used Open3D to visualize my 3D object detection result. And I wanna output the result as a Video. The following message is from terminal. I use conda install opencv-python and Open3D. Any one can help me? Thanks!

visualization/visualize_eval_val_seq.py
PinholeCameraTrajectory read JSON failed: empty trajectory.
000000
Traceback (most recent call last):
  File "visualization/visualize_eval_val_seq.py", line 802, in <module>
    img_lidar = lidar_img_creator.create_img(gt_bboxes + pred_bboxes + [pcd])
  File "visualization/visualize_eval_val_seq.py", line 448, in create_img
    vis.run()
  File "visualization/visualize_eval_val_seq.py", line 422, in move_forward
    ctr.convert_from_pinhole_camera_parameters(self.trajectory.intrinsic, self.trajectory.extrinsic[0])
AttributeError: 'open3d.open3d.camera.PinholeCameraTrajectory' object has no attribute 'intrinsic'

camera_trajectory.json:
{
	"class_name" : "PinholeCameraTrajectory",
	"extrinsic" : 
	[
		[
			1.0,
			0.0,
			0.0,
			0,
			0.0,
			0.866,
			0.5,
			0,
			0.0,
			-0.5,
			0.866,
			0,
			0.0,
			3.0,
			5.0,
			1
		]
	],
	"intrinsic" : 
	{
		"height" : 1080,
		"intrinsic_matrix" : [ 935.30743608719376, 0, 0, 0, 935.30743608719376, 0, 959.5, 539.5, 1 ],
		"width" : 1920
	},
	"version_major" : 1,
	"version_minor" : 0
}

Any solution for this?

Regards
Cheng

**Comment by qianyizh** [comment]
I read your json file and it works well for me.
Can you paste a minimal complete code snippet so that I can duplicate the error?

**Comment by tianchengdw** [comment]
class ImgCreatorLiDAR:
    def __init__(self):
        self.counter = 0
        self.trajectory = read_pinhole_camera_trajectory("/media/orange/work/3DOD_thesis/visualization/camera_trajectory.json") 

    def move_forward(self, vis):
        # this function is called within the Visualizer::run() loop.
        # the run loop calls the function, then re-renders the image.

        if self.counter < 2: # (the counter is for making sure the camera view has been changed before the img is captured)
            # set the camera view:
            ctr = vis.get_view_control()
            ctr.convert_from_pinhole_camera_parameters(self.trajectory.intrinsic, self.trajectory.extrinsic[0])

            self.counter += 1
        else:
            # capture an image:
            img = vis.capture_screen_float_buffer()
            img = 255*np.asarray(img)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = img.astype(np.uint8)
            self.lidar_img = img

            # close the window:
            vis.destroy_window()

            self.counter = 0

        return False

    def create_img(self, geometries):
        vis = Visualizer()
        vis.create_window()
        opt = vis.get_render_option()
        opt.background_color = np.asarray([0, 0, 0])
        for geometry in geometries:
            vis.add_geometry(geometry)
        vis.register_animation_callback(self.move_forward)
        vis.run()

        return self.lidar_img
###########################
out_lidar_img_GT_pred = cv2.VideoWriter("eval_val_seq_%s_lidar_img_GT_pred.avi" % sequence, cv2.VideoWriter_fourcc(*'XVID'), 12, (1920, 1080), True)

lidar_img_creator = ImgCreatorLiDAR()
for img_id in sorted_img_ids:
    print(img_id)

    img = cv2.imread(img_dir + img_id + ".png", -1)
    img_with_bboxes = img
    if img_id in img_data_dict:
        data_dict = img_data_dict[img_id]
        gt_bbox_polys = data_dict["gt_bbox_polys"]
        pred_bbox_polys = data_dict["pred_bbox_polys"]
        img_with_bboxes = draw_3d_polys(img_with_bboxes, gt_bbox_polys)
        img_with_bboxes = draw_3d_polys(img_with_bboxes, pred_bbox_polys)
    small_img_with_bboxes = cv2.resize(img_with_bboxes, (small_img_width, small_img_height))

    lidar_path = lidar_dir + img_id + ".bin"
    point_cloud = np.fromfile(lidar_path, dtype=np.float32).reshape(-1, 4)

    # remove points that are located behind the camera:
    point_cloud = point_cloud[point_cloud[:, 0] > -2.5, :]

    point_cloud_xyz = point_cloud[:, 0:3]
    point_cloud_xyz_hom = np.ones((point_cloud.shape[0], 4))
    point_cloud_xyz_hom[:, 0:3] = point_cloud[:, 0:3] # (point_cloud_xyz_hom has shape (num_points, 4))

    # transform the points into (rectified) camera coordinates:
    point_cloud_xyz_camera_hom = np.dot(R0_rect, np.dot(Tr_velo_to_cam, point_cloud_xyz_hom.T)).T # (point_cloud_xyz_hom.T has shape (4, num_points))
    # normalize:
    point_cloud_xyz_camera = np.zeros((point_cloud_xyz_camera_hom.shape[0], 3))
    point_cloud_xyz_camera[:, 0] = point_cloud_xyz_camera_hom[:, 0]/point_cloud_xyz_camera_hom[:, 3]
    point_cloud_xyz_camera[:, 1] = point_cloud_xyz_camera_hom[:, 1]/point_cloud_xyz_camera_hom[:, 3]
    point_cloud_xyz_camera[:, 2] = point_cloud_xyz_camera_hom[:, 2]/point_cloud_xyz_camera_hom[:, 3]

    pcd = PointCloud()
    pcd.points = Vector3dVector(point_cloud_xyz_camera)
    pcd.paint_uniform_color([0.65, 0.65, 0.65])

    gt_bboxes = []
    pred_bboxes = []

    if img_id in img_data_dict:
        data_dict = img_data_dict[img_id]
        gt_bboxes = data_dict["gt_bboxes"]
        pred_bboxes = data_dict["pred_bboxes"]

    img_lidar = lidar_img_creator.create_img(gt_bboxes + pred_bboxes + [pcd])

    combined_img = img_lidar
    combined_img[-small_img_height:, ((1920/2)-(small_img_width/2)):((1920/2)+(small_img_width/2))] = small_img_with_bboxes

    out_lidar_img_GT_pred.write(combined_img)
``

> I read your json file and it works well for me.
> Can you paste a minimal complete code snippet so that I can duplicate the error?

 @qianyizh Thanks for your reply. This is part of the code. Thank you again!

Cheng

**Comment by yxlao** [comment]
@tianchengdw see [PinholeCameraTrajectory](http://www.open3d.org/docs/python_api/open3d.camera.PinholeCameraTrajectory.html), [PinholeCameraParameters](http://www.open3d.org/docs/python_api/open3d.camera.PinholeCameraParameters.html) and
 [PinholeCameraIntrinsic](http://www.open3d.org/docs/python_api/open3d.camera.PinholeCameraIntrinsic.html) docs. `open3d.camera.PinholeCameraTrajectory.parameters` is a list of `open3d.camera.PinholeCameraParameters`. You can get one element from the list and get intrinsic matrix accordingly.

```python
# "self.trajectory" is of type "open3d.camera.PinholeCameraTrajectory"
parameter = self.trajectory.parameters[0]
print(parameter.intrinsic.intrinsic_matrix)
```

In general, you can use `dir(object)` to check Python attributes, e.g. `print(dir(self.trajectory))`, or, refer to the Open3D docs.

**Comment by tianchengdw** [comment]
@yxlao Thank you very much! I will try it!

**Comment by yutaroyamanaka** [comment]
@tianchengdw 
Did you solve this problem?
I met the same situation as yours.
I'll be glad if you show the result.

**Comment by 459737087** [comment]
I also met this problem.
