### ISSUE TITLE
Would read_point_cloud() read intensity from pcd files?

### ISSUE THREAD

**Issue by bigsheep2012** [intel-isl/Open3D#921]
Hello open3d team,

I am using Python API.
I am writing to check if current 'read_point_cloud' would read intensity as well from a .pcd file? 
If yes, how can I access these intensity values like pcd.points?
Exactly like the format here:
http://pointclouds.org/documentation/tutorials/pcd_file_format.php
```
# .PCD v.7 - Point Cloud Data file format
VERSION .7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 213
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 213
DATA ascii
0.93773 0.33763 0 4.2108e+06
0.90805 0.35641 0 4.2108e+06
0.81915 0.32 0 4.2108e+06
0.97192 0.278 0 4.2108e+06
0.944 0.29474 0 4.2108e+06
```

Thanks in advance.

**Comment by yxlao** [comment]
Open3D `PointCloud` class supports: x, y, z, r, g, b, normal_x, normal_y, normal_z, see [here](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Geometry/PointCloud.h#L88).

If what you're referring to is the RGB value encoded into a float, Open3D does support that:
```
x          y         z    rgb-encoded
0.93773    0.33763   0    4.2108e+06
```

For the point cloud in the link http://pointclouds.org/documentation/tutorials/pcd_file_format.php, here's Open3D's visualization: 

![Screenshot from 2019-04-22 19-06-12](https://user-images.githubusercontent.com/1501945/56547255-b4a49a80-6531-11e9-98fc-3949abbd1dec.png)

**Comment by bigsheep2012** [comment]
Thanks for the reply. 
So if I hope to access the rgb-encoded values, I just need to use code like
'pcd.rgb-encoded' (similar to pcd.points)?
I hope to know if it is possible to specify a field name as well, e.g., my pcd file would be like:
FIELDS x y z intensity
where 'rgb' becomes 'intensity'.

Thanks in advance.

**Comment by yxlao** [comment]
PointCloud has:
```python
pcd.colors
pcd.normals
pcd.points
```

**If you're reading from pcd**
Currently, there is no direct access to the encoded value. Since we only support the standard pcd storage format. If you'd need to gain direct access to the encoded value, compile from source and hack around: https://github.com/intel-isl/Open3D/blob/eea7fd2290160513a14f20a891ada08892326447/src/Open3D/IO/FileFormat/FilePCD.cpp#L389-L391

**If you can write to that pcd**
If you don't need the actual RGB value, one hack could be we use "R" as intensity, and keep "G" and "B" to be zero. Then when you save the point cloud, it will be converted to the encoded float value. E.g.

```python
import open3d as o3d

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(np.array([[1, 2, 3], [4, 5, 6]]))

# 0.2, 0.3 are the intensity of the two points
pcd.colors = o3d.utility.Vector3dVector(np.array([[0.2, 0, 0], [0.3, 0, 0]])) 

o3d.io.write_point_cloud("hello.pcd", pcd, write_ascii=True)
```

After that, if you read from "hello.pcd", the "R" value will be the intensity.

**Comment by bigsheep2012** [comment]
I see. I would try to modify the IO cpp files.
Thanks.

**Comment by funatsufumiya** [comment]
`o3d.t` can treat custom attributions like intensities

 ```python  
pcdt = o3d.t.geometry.PointCloud()
pcdt.point.positions = o3d.core.Tensor(positions)
pcdt.point.intensities = o3d.core.Tensor(intensities.reshape(-1,1))
print(pcdt)

o3d.t.io.write_point_cloud("test.ply", pcdt)
```

Check http://www.open3d.org/docs/0.14.1/python_api/open3d.t.geometry.PointCloud.html#open3d.t.geometry.PointCloud

**Comment by abhishekbawkar** [comment]
Hi all,

I know this is pretty old issue and already closed, but I was facing the same issue in my application as well. What we wanted to do is to use the intensity information as color info to visualize the pointcloud in gray-scale. I could save the poincloud using `open3d.t` as mentioned by @funatsufumiya, but couldn't visualize it with intensity as gray-scale.

So i did following:
```python
import open3d as o3d
import cv2
import numpy as np

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(positions)

# If the intensity array is RGB encoded, first normalize it using opencv to 16-bit precision
intensities_norm = cv2.normalize(intensities, dst=None, alpha=0, beta=65535, norm_type=cv2.NORM_MINMAX)

# Using numpy.column_stack() provide equal values to RGB values and then assign to 'colors' property 
# of the point cloud.
# Since Open3D point cloud's 'colors' property is float64 array of shape (num_points, 3), range [0, 1],
# we have to normalize the intensity array by dividing it by 65535
colors = np.column_stack((intensities_norm, intensities_norm, intensities_norm)) / 65535

# Now colors array is grayscale array (r = g = b)
pcd.colors = o3d.utility.Vector3dVector(colors)

# Now visualize the gray-scale point cloud using Open3D itself
o3d.visualization.draw_geometries([pcd])
```
Let me know if this is found to be useful.

BR
Abhishek
