### ISSUE TITLE
SIGABRT when import torch

### ISSUE THREAD

**Issue by Jiayuan-Gu** [intel-isl/Open3D#922]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When the user import pytorch before importing open3d, it will raise an error.

**To Reproduce**
```python
import torch
import open3d
```

**Expected behavior**
The program crashes. When you swap the order, it works.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04 / 18.04
 - Python version: 3.6
 - Open3D version: 0.6.0
 - Pytorch version: 1.0.1
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Additional context**
When back to 0.5.0, this error disappears.

**Comment by yxlao** [comment]
Hi @Jiayuan-Gu could you try 
```python
import open3d
import torch
```
Also make sure that in all python files in your project, `open3d` is imported before `torch`

**Comment by Jiayuan-Gu** [comment]
> Hi @Jiayuan-Gu could you try
> 
> ```python
> import open3d
> import torch
> ```
> 
> Also make sure that in all python files in your project, `open3d` is imported before `torch`

Yes, I already find this solution and mention that in the Expected behavior. 
I also use gdb to find the error, but I do not really understand it. I think that it might indicate some potential errors.

**Comment by yxlao** [comment]
Thanks for reporting. We're not yet sure if that's a problem with Open3D or PyTorch.

**Comment by jiangwei221** [comment]
Link a issue from Pytorch: https://github.com/pytorch/pytorch/issues/19739
Here is a quick fix: https://github.com/pytorch/pytorch/issues/19739#issuecomment-523969436

**Comment by mcarletti** [comment]
> Thanks for reporting. We're not yet sure if that's a problem with Open3D or PyTorch.

Maybe this open question on Blender StackExchange could help finding the issue:
[ImportError when loading Open3D module into Blender python console](https://blender.stackexchange.com/questions/153802/importerror-when-loading-open3d-module-into-blender-python-console)

**Comment by yxlao** [comment]
See https://github.com/intel-isl/Open3D/issues/922 for the fix

**Comment by DomL2018** [comment]
Hi @yxlao 
Thanks for the wonderful work, I am new here , and trying to do Octomap (octotree ? )using Open3D python, and visualising the mapping results with CV2 as well , could you please kindly provide a guild or example in the library to reference or use?
Any other experts are welcome and appreciated for information. 
many thanks
Dom
