### ISSUE TITLE
Headless rendering: capturing screen-buffer produces black images

### ISSUE THREAD

**Issue by ykaganov** [intel-isl/Open3D#927]
I Followed the instructions here: http://www.open3d.org/docs/tutorial/Advanced/headless_rendering.html  for headless rendering (without display) and then ran the script https://github.com/intel-isl/Open3D/blob/master/examples/Python/Advanced/headless_rendering.py.
Strangely, only the depth images are produces correctly from the depth buffer (vis.capture_depth_float_buffer) but the capturing of the screen buffer (vis.capture_screen_float_buffer) produces images that are all black (all pixels are zero). See examples below.
I am running inside a docker container and followed the advice here https://github.com/intel-isl/Open3D/issues/253 (using Xfvb and defining a virtual display 1920x1080x24).
What am I missing ??!!!
 
![image](https://user-images.githubusercontent.com/37039796/56665874-8d75d680-66b3-11e9-8a0e-5f54c0381b9b.png)
![image](https://user-images.githubusercontent.com/37039796/56665901-9a92c580-66b3-11e9-8952-49c8cfe02e9c.png)

**Comment by pvarvak** [comment]
This should be resolved if following updated instructions from master (after #1695 was merged).  When using OSMesa there is no need for Xfvb.  If there are still issues please compile master and post output of bin/GLInfo and your environment.
