### ISSUE TITLE
open3D <IO.h> conflict with <io.h> of Windows

### ISSUE THREAD

**Issue by sunchaothu** [intel-isl/Open3D#931]
**Describe the bug**
In my C++ program I used  open3d and another 3rd-party library and the 3rd-party is internally include <io.h> of windows. When I click in the header, it jumps into open3d <IO.h>; I guess  that the header is conflict with Windows VC IO header. Besides, It will also conflict with gtest, because 
gtest_port.h use <io.h> internally.

**Reproduce**
use <io.h> of Windows platform and <IO.h> at the same time.

**Screenshots**
![image](https://user-images.githubusercontent.com/14788898/56725736-05113780-6780-11e9-93a7-a63f49b83a19.png)

**Environment (please complete the following information):**
 - OS: [Windows 10.0,vs2017]
 - Open3D version:0.4.0.0
 - How did you install Open3D?:build_from_source (vc15 release of VS2017)

**Comment by yxlao** [comment]
Could you try the latest Open3D version (master branch is 0.6.0+)? 
First, `src/IO/IO.h` was removed in current master; second, you could probably use the full include path rather than the relative path.

**Comment by sunchaothu** [comment]
I see. Thank you
