### ISSUE TITLE
Error loading .ply file (RPly) with read_point_cloud

### ISSUE THREAD

**Issue by pmwenzel** [intel-isl/Open3D#932]
Hi all, the function read_point_cloud() gives an error while loading similar point cloud files (.ply). The error is the following:

`RPly: Error reading 'blue' of 'vertex' number 222225`

It occurs randomly on files with similar content. The header of all files is the same.

>
ply
format ascii 1.0
element vertex 149906
property float32 x
property float32 y
property float32 z
property uchar red
property uchar green
property uchar blue
end_header
> 

The error occurs while calling: `pcd = read_point_cloud(ply_file_path)`

Expected behavior should be:
Reading PLY: [========================================] 100%

I am using Ubuntu 16.04 with Python 3.6.8 and anaconda. Open3d version 0.6.0.0.

Thanks

**Comment by mike239x** [comment]
Do you have a file which consistently cannot be loaded?

**Comment by pmwenzel** [comment]
Yes, please find attached two point clouds. Point cloud `point_cloud_00001.ply` can be loaded without any problems, however, `point_cloud_00002.ply` throws the error.

[point_clouds_test.tar.gz](https://github.com/intel-isl/Open3D/files/3116772/point_clouds_test.tar.gz)

**Comment by mike239x** [comment]
Wow, this is weird. I unzipped your data, I try to read the second point cloud, I get 
```
>>> open3d.read_point_cloud("point_cloud_00002.ply")
RPly: Error reading 'blue' of 'vertex' number 150062=>] 97%
Read PLY failed: unable to read file: point_cloud_00002.ply
geometry::PointCloud with 150063 points.
```
I open PLY file with vim, save+close, try same thing again, it works without errors.
Looking at the hexdump, I see:
Your file ends with 
```
004afec0  33 39 37 2e 31 38 20 38  36 20 38 39 20 39 38     |397.18 86 89 98|
```
after vim it becomes
```
004afec0  33 39 37 2e 31 38 20 38  36 20 38 39 20 39 38 0a  |397.18 86 89 98.|
```
So, basically, your last line doesn't end with a line-ending character.
I do not know though why first file works and second doesn't, though they both do not end with `0a`.

**Comment by pmwenzel** [comment]
Thanks for catching this. It seems like it is a weird problem. I guess the library should be able to handle files either with a line-ending character or not.

**Comment by germanros1987** [comment]
This issue is not Open3D specific.

**Comment by SebastianGrans** [comment]
I believe this should be reopened. Open3D relies on the RPly library version 1.1.3. 
The latest version is 1.1.4. 

```
 ~$ bpython
bpython version 0.20 on top of Python 3.8.5 /usr/bin/python3
>>> import open3d as o3d
>>> o3d.io.read_point_cloud('~/Desktop/obj_23.ply')
[Open3D WARNING] Read PLY failed: unable to open file: ~/Desktop/obj_23.ply
PointCloud with 0 points.
>>>
>>> o3d.__version__
'0.11.0'
```

If I download the latest version of the RPly library [here](http://w3.impa.br/~diego/software/rply/) and run the example program on the same file: 

```c++

#include <stdio.h>
#include "rply.h"

static int vertex_cb(p_ply_argument argument) {
    long eol;
    ply_get_argument_user_data(argument, NULL, &eol);
    printf("%g", ply_get_argument_value(argument));
    if (eol) printf("\n");
    else printf(" ");
    return 1;
}

int main(void) {
    long nvertices, ntriangles;
    ntriangles = 0;
    p_ply ply = ply_open("/home/grans/Desktop/obj_23.ply", NULL, 0, NULL);
    if (!ply) return 1;
    if (!ply_read_header(ply)) return 1;
     nvertices = ply_set_read_cb(ply, "vertex", "x", vertex_cb, NULL, 0);
    ply_set_read_cb(ply, "vertex", "y", vertex_cb, NULL, 0);
    ply_set_read_cb(ply, "vertex", "z", vertex_cb, NULL, 1);
    printf("%ld\n%ld\n", nvertices, ntriangles);
    if (!ply_read(ply)) return 1;
    ply_close(ply);
    return 0;
}
```
It runs completely fine:
```
~$ ./RPlyTest
2947 # of vertices
-17.317 -17.25 -18.2171
-13.7883 -18.25 -20.9777
-11.8549 -18.25 -22.1133
-9.8287 -17.25 -23.0736
-5.5618 -18.25 -24.4395
[...] 
```

Here's an example `.ply` that doesn't work: 
[obj_23.zip](https://github.com/intel-isl/Open3D/files/5524209/obj_23.zip)

**Comment by monjoybme** [comment]
I faced a similar error `Error reading 'x' of 'vertex' number 817658`. I noticed that the element vertex is less than or equal to 817658. When I changed `element vertex = 817658`, the issue was resolved. My suggestion for the above issue: match your `element vertex` and `vertex number`.
`element vertex=149906` and your `vertex number=222225`
Then your problem should be solved.

**Comment by ivankrstev7** [comment]
I am facing a similar error with RPly when trying to load a .ply file from a scene reconstruction, which is kinda enormous, 3.5GB. I get `RPly: unable to open file`.

**Comment by ErnieLud** [comment]
Hello guys, I had a similar error output: "RPly: Error reading 'blue' of 'vertex' number 22042"
and I solved it by closing the file I was trying to read... I forgot to close it before reading  it with the function "read_point_cloud".
So after a "file.close()" I didn't have any problem.
