### ISSUE TITLE
Can not compile, since unary_function is removed from c++17

### ISSUE THREAD

**Issue by tfjiang** [intel-isl/Open3D#934]
When I use Open3D in a C++17 project (compiled with visual studio 2019 preview), I get an error :
“unary_function”: is not a member of "std", which occurs in Open3D/Utility/Helper.h Line 90.

And I find that unary_function is removed from c++17, could you use std::function to replace that, and make it compiled by c++ 17 compiler?

**Comment by griegler** [comment]
Adressed in #1023
