### ISSUE TITLE
Remove dependencies on LGPL libraries in Eigen

### ISSUE THREAD

**Issue by jornb** [intel-isl/Open3D#938]
Currently, Open3D depends on Eigen's SimplicialCholesky implementation, [which is licensed under LGPL](http://eigen.tuxfamily.org/index.php?title=Main_Page#License). This is vastly more limiting than the licenses of all other third party dependencies, and I presume several people do not realize they need to comply to LGPL when using Open3D out of the box.

I found this when trying to build Open3D with the `EIGEN_MPL2_ONLY` compile definition, which disables Eigen components licensed under LGPL.

Suggested fixes in increasing severity (note that I don't know the internals of Open3d and cannot assess the feasibility of these suggestions):
* Clearly indicate the use of dependencies licensed under LGPL
* Detect the `EIGEN_MPL2_ONLY` cmake flag and disable compilation of all parts that require SimplicialCholesky
* Replace SimplicialCholesky with another solver

May be related to #405.

**Comment by jornb** [comment]
For reference, the pull request #939 fixes my compilation errors when `EIGEN_MPL2_ONLY` is defined. However, I don't know enough of Open3D to know what effects this will have.

**Comment by kuonangzhe** [comment]
Are there any updates? How will Open3D deal with LGPL problem? Thanks a lot! @qianyizh

**Comment by kuonangzhe** [comment]
@yxlao @syncle @takanokage Could you mind sharing a bit of the design and plan for this part? It's been inactive for a while. Thank you so much!

**Comment by AndyMender** [comment]
@yxlao @syncle @takanokage @kuonangzhe heads-up about licensing changes in Eigen3: https://gitlab.com/libeigen/eigen/-/commit/1dc1677d525b1df3cc32b3df5cd816e150b07185

**Comment by germanros1987** [comment]
problem solved!
