### ISSUE TITLE
will Open3D  automatically use cuda to speed up?

### ISSUE THREAD

**Issue by densechen** [intel-isl/Open3D#942]
I have try the example of registration_icp, and the speed is slow. will Open3D  automatically use cuda to speed up?

**Comment by barnjamin** [comment]
There is a cuda branch but it appears to be in early stages.  There is also a fork https://github.com/theNded/Open3D, that implements a registration and other things in Cuda

**Comment by germanros1987** [comment]
CUDA support is being incrementally rolled out as we speak. You can find the new Tensor library in master with support for GPU.
