### ISSUE TITLE
Get image data (like pixels) inside open3d.open3d.geometry.Image

### ISSUE THREAD

**Issue by lvgeng** [intel-isl/Open3D#957]
From the documentation:
http://www.open3d.org/docs/tutorial/Basic/working_with_numpy.html

It is pretty easy to work with numpy, however it seems that the python interface of 
open3d.geometry.Image
is kind of difficult to get data out from it.

Unlike open3d.geomety.Pointcloud, the Image class does not have access to the data inside of it like pixels.

Is there any way to check the image in it, like converting an open3D Image to a numpy array?

**Comment by yxlao** [comment]
This shall work:
```python
# open3d -> np
np_image = np.array(o3d_image)

# np -> open3d
np_image = o3d.(o3d_image)
```

![image](https://user-images.githubusercontent.com/1501945/57579124-6148ac80-744c-11e9-85b9-c672773b389d.png)

**Comment by lvgeng** [comment]
Em.... never expect it to be something this straightforward.
Is there anything special while dealing with depth image? It seems to be tricky. Sometime it works, some time it doesn't....

**Comment by gledsonmelotti** [comment]
Hello everyone. I have a question about using open3D functions. I am trying to get the FPFH feature. However, I cannot access the numerical values. I am using the following commands:

`import numpy as np`
`import open3d as o3d`
`pcd = o3d.geometry.PointCloud()`
`pcd.points = o3d.utility.Vector3dVector(velo_point)`
`voxel_size = 0.05 # means 5cm for the dataset`
`radius_feature = voxel_size * 5`
`radius_normal = voxel_size * 2`
`pcd.estimate_normals(o3d.geometry.KDTreeSearchParamHybrid(radius=radius_normal, max_nn=30))`
`pcd_fpfh = o3d.registration.compute_fpfh_feature(pcd, o3d.geometry.KDTreeSearchParamHybrid(radius=radius_feature, max_nn=100))`

How do I access the numerical values of pcd_fp?
@yxlao, can you help me?

**Comment by germanros1987** [comment]
Closing this issue since the original question got solved. Please @gledsonmelotti use a new issue to ask your question.
