### ISSUE TITLE
Synthesizing depth image for ReconstructionSystem.

### ISSUE THREAD

**Issue by lvgeng** [intel-isl/Open3D#961]
I have a data set of color images scanned from a sphere surface, therefore I hope to synthesize some depth images (a sphere is easy to calculate....) and use the indoor reconstruction system to put them together.

The strange thing is sometime the opencv_pose_estimation works pretty good, but estimate_3D_transform_RANSAC fail to give a reasonable result...

I mean. it is kind of hard to understand what affects the result of estimate_3D_transform_RANSAC().
Did the camera intrinsic also take a part in this?

What should I look into if I need to fake a depth sensor and a depth data set?

**Comment by syncle** [comment]
``estimate_3D_transform_RANSAC`` requires per-pixel depth value to compute 3D transformation. Please check your depth map is correct enough.
