### ISSUE TITLE
A really bad case 

### ISSUE THREAD

**Issue by zxwang96** [intel-isl/Open3D#962]
Hi,

I tried to register two point clouds by `registration_icp`. Previously open3d works perfectly, while for this case the result is very bad. Here you can access my compressed bag containing two .ply file and the code. 
[https://drive.google.com/file/d/1LeXIBsvpj2VOLtXlNKUOSiQdhE-vIGuK/view?usp=sharing](https://drive.google.com/file/d/1LeXIBsvpj2VOLtXlNKUOSiQdhE-vIGuK/view?usp=sharing)

**Comment by yxlao** [comment]
in your code, try 
```python
trans_init = np.eye(4)
```
the original matrix is just used in the tutorial for illustration
