### ISSUE TITLE
Return None when calling vis.get_render_option()

### ISSUE THREAD

**Issue by HaiyongJiang** [intel-isl/Open3D#972]
Dear authors, 

I encountered some errors when running "headless_rendering.py". The following is the log information. I am not sure what is the potential problem. Can you kindly help me figure it out? Thank you. 

> Reading PLY: [========================================] 100%
Customized visualization playing a camera trajectory. Ctrl+z to terminate
GLFW Error: X11: Failed to open display localhost:13.0
Failed to initialize GLFW
Traceback (most recent call last):
  File "headless_rendering.py", line 61, in <module>
    custom_draw_geometry_with_camera_trajectory(pcd)
  File "headless_rendering.py", line 52, in custom_draw_geometry_with_camera_trajectory
    vis.get_render_option().load_from_json("../../TestData/renderoption.json")
AttributeError: 'NoneType' object has no attribute 'load_from_json'

**Comment by HTLife** [comment]
Any progress on this issue?

**Comment by mightypirate1** [comment]
I am also encountering this error trying to run the second code snippet from [the documentation](http://www.open3d.org/docs/release/tutorial/Advanced/customized_visualization.html#mimic-draw-geometries-with-visualizer-class
)

Any ideas on how to troubleshoot?

**Comment by pvarvak** [comment]
This should be resolved if following updated instructions from master (after #1695 was merged).  When using OSMesa there should not be any errors like "Failed to open display localhost:*", that would indicate OSMesa is not being used and display is being used.  If there are still issues please compile master and post output of bin/GLInfo and your environment.
