### ISSUE TITLE
Create point cloud from nothing in Python

### ISSUE THREAD

**Issue by tpwrules** [intel-isl/Open3D#986]
It doesn't seem possible to create a point cloud from nothing in Python i.e. just instantiate a PointCloud with no points. Additionally, I can't add points to an existing cloud from e.g. a Numpy array.

I would like a constructor of an open3d.geometry.PointCloud that I can specify the number of points (that all start at zero) or create it from an existing Numpy array. This would include point locations, color data, and normals.

This would let me create or modify a point cloud using other Python libraries (or my own code), then load it directly into Open3D for visualization or other operations.

**Comment by griegler** [comment]
All of that should already be possible. For example this creates a empty PointCloud first and then populates it with a random numpy array.

```python
import open3d as o3d
import numpy as np
pcl = o3d.PointCloud()
pcl.points = o3d.Vector3dVector(np.random.randn(500,3))
o3d.draw_geometries([pcl])
```

If this does not work for you, could you give more details on your open3d version, platform and so on.

**Comment by tpwrules** [comment]
My mistake, I was missing the requirement to create some Vector3dVectors to populate the points. Thanks for the assistance. Perhaps the documentation could be improved?

**Comment by BlGene** [comment]
pcl = o3d.geometry.PointCloud()

**Comment by Martzi** [comment]
Has anyone experienced problems while tried to add points to the pointcloud?
I read a numpy array from an rgbd cam through pyzmq in the correct form.
`pts = receive_pointcloud(socket)`
type: <class 'numpy.ndarray'> 
shape: (105972, 3)
I try to use these point to create a pointcloud:
`pointcloud = o3d.geometry.PointCloud()`
`pointcloud.points = o3d.utility.Vector3dVector(pts)`
But I get the following error:
"pointcloud = o3d.utility.Vector3dVector(pts)
ValueError: array is not writeable"

How can I assign the values read from camera to the pointcloud? Or how can I make this variable writable?

**Comment by spyridon-amp** [comment]
Similarly, I need to create a point cloud, but I also want to add normals. However, I get ValueError: array is not writeable when I do pcd.normals = o3d.utility.Vector3dVector(np.asarray(normals)).
Is there a way to add normals to a newly created point cloud?

**Comment by jinfagang** [comment]
AttributeError: module 'open3d.cuda.pybind.geometry' has no attribute 'Vector3dVector'
