### ISSUE TITLE
Documentation down?

### ISSUE THREAD

**Issue by jbohnslav** [intel-isl/Open3D#988]
**Describe the bug**
Nothing under http://www.open3d.org/docs/ is available. It says: "Not Found
The requested URL /docs/ was not found on this server."

**To Reproduce**
Go to http://www.open3d.org/docs/

**Expected behavior**
Viewing documentation

**Screenshots**

**Environment (please complete the following information):**
 -N/A

**Additional context**

**Comment by yxlao** [comment]
yes, we're fixing it right now

**Comment by yxlao** [comment]
fixed

**Comment by jbohnslav** [comment]
Thank you!
