### ISSUE TITLE
Error: TransformationEstimationPointToPlane requires pre-computed normal vectors.

### ISSUE THREAD

**Issue by havean** [intel-isl/Open3D#990]
在使用全局注册时，我已经使用ownpcd = o3d.geometry.voxel_down_sample()下采样 
o3d.geometry.estimate_normals()计算法线，粗配准时fitness=0.92,rmse=0.69
然后运行到精注册时PointToPlane()就出现fitness=0.00    ,rmse=0.00控制台出现Error: TransformationEstimationPointToPlane requires pre-computed normal vectors.
 
求各位大神指点一下

**Comment by uros171513** [comment]
Have the same question.

**Comment by qianyizh** [comment]
You need to do ``estimate_normals()`` for finer grade point cloud too.

**Comment by havean** [comment]
> 你也需要`estimate_normals()`为更好的等级点云做。

我在精配准之前已经用了estimate_normals()计算法线 ，后面依然报错

**Comment by qianyizh** [comment]
Can you share a minimal code snippet for us to reproduce the error?

**Comment by havean** [comment]
数据预处理
def preprocess_point_cloud(pcd, voxel_size)：
#估算法线
o3d.geometry.estimate_normals(pcd_down,o3d.geometry.KDTreeSearchParamHybrid(radius=radius_normal, max_nn=50))
  
#全局注册  
def execute_global_registration(source_down, target_down, source_fpfh, target_fpfh, voxel_size):
o3d.registration.TransformationEstimationPointToPoint()
#精密注册
def refine_registration(source, target, source_fpfh, target_fpfh, voxel_size):
    distance_threshold = voxel_size*4.5
    result = o3d.registration.registration_icp( source, target, distance_threshold， 
   result_ransac.transformation,o3d.registration.TransformationEstimationPointToPlane())
    return result
先估计法线，然后全局粗略注册，然后精密注册              控制台就会出现Error: TransformationEstimationPointToPlane requires pre-computed normal vectors.   fitters=0     rmse=0

**Comment by qianyizh** [comment]
I think you need to call ``o3d.geometry.estimate_normals`` for ``source`` and ``target`` too.
