### ISSUE TITLE
Expose Visualizer::CaptureDepthPointCloud to python api

### ISSUE THREAD

**Issue by JackLangerman** [intel-isl/Open3D#992]
I'd like to expose Visualizer::CaptureDepthPointCloud to the python api.

I think I can just modify this file 
```src/Python/visualization/visualizer.cpp```

and add this to get the behaviour

121:
```
.def("capture_depth_point_cloud",
     &visualization::Visualizer::CaptureDepthPointCloud,
     "Function to capture and save local point cloud", "filename"_a,
     "do_render"_a = false, "convert_to_world_coordinate"_a = false)
```

and then modify like this for docs
52:
```
{"convert_to_world_coordinate", 
                 "Set to ``True`` to convert to world coordinates"}
```

172:
``` 
docstring::ClassMethodDocInject(m, "Visualizer", "capture_depth_point_cloud",
                                    map_visualizer_docstrings);
```

Is that correct? Happy to work on this, but haven't worked on this before so I may need some pointers. 

Will file a matching PR if this seems reasonable. 

Thanks!

related to:
#702

**Comment by qianyizh** [comment]
Looks reasonable to me, @yxlao take a look?

**Comment by yxlao** [comment]
@JackLangerman thanks, yes, this looks good

**Comment by JackLangerman** [comment]
#1014 merged so closing this issue.  Thanks for your help!
