### ISSUE TITLE
geometry.TriangleMesh object has no attribute 'rotate'

### ISSUE THREAD

**Issue by fengniu08** [intel-isl/Open3D#995]
Hi, 
I used pip to install the open3D. Got this error when run the example transformation.py. I also printed the attributre of  TriangleMesh and found there is no 'rotate' for sure. What's the problem? Did I miss something ?

**Comment by griegler** [comment]
The `rotate` methods are only in the master branch at the moment and will be part of the next release that will be available in a couple of days. Then they will also be included in the versions of open3d installed via `pip`/`conda`.
