### ISSUE TITLE
Visualizer has no attribute "remove_geometry"

### ISSUE THREAD

**Issue by Ceege** [intel-isl/Open3D#998]
There doesn't seem to be a remove_geometry function, even though I saw it in the python bindings 

Running the remove_geometry.py example works fine for the adding of geometries to the viewer, but when the first call to remove_geometry to compiler throws 

vis.remove_geometry(pcds[i])
AttributeError: 'open3d.open3d.visualization.Visualizer' object has no attribute 'remove_geometry'

I did install open3d via the package manager in pyCharm, however the version is 0.6. Could this installation method be the reason the method cannot be found?

 - OS: Windows 10.0
 - Python version: 2.7, pyCharm
 - Open3D version: 0.6

**Comment by griegler** [comment]
Same problem as in #995
