### ISSUE TITLE
Multiple viewports per window

### ISSUE THREAD

**Issue by sammo2828** [intel-isl/Open3D#999]
A common use case is comparing multiple point clouds side-by-side. In PCL, this could be done by creating multiple viewports in the same window. However, Open3D Visualizer only provides a single window with a single viewport and a single ViewControl.

Feature request to extend the API to be able to attach multiple viewports to a window.

With the current API, a workaround is to create multiple windows with multiple Visualizer instances:

```python
vis = o3d.Visualizer()
vis.create_window(window_name='TopLeft', width=960, height=540, left=0, top=0)
vis.add_geometry(pcd)

vis2 = o3d.Visualizer()
vis2.create_window(window_name='TopRight', width=960, height=540, left=960, top=0)
vis2.add_geometry(pcd)

while True:
    vis.update_geometry()
    if not vis.poll_events():
        break
    vis.update_renderer()

    vis2.update_geometry()
    if not vis2.poll_events():
        break
    vis2.update_renderer()

vis.destroy_window()
vis2.destroy_window()
```

**Comment by qianyizh** [comment]
Yes, we are working on a better GUI that can have multiple viewports.
Meanwhile the workaround should work.

**Comment by hduonggithub** [comment]
Hi @qianyizh 
Do we have multiple viewports yet? if yes, please advise. Thanks!

**Comment by MaxChanger** [comment]
The new version of open3d (0.9.0 and 0.10.0) needs to add the parameters you want to update in update_geometry().
You can check [here](http://www.open3d.org/docs/release/python_api/open3d.visualization.Visualizer.html?highlight=update_geometry#open3d.visualization.Visualizer.update_geometry)
```python
vis.add_geometry(src_pcd)
while True:
    vis.update_geometry(src_pcd)
    if not vis.poll_events():
        break
    vis.update_renderer()
```

**Comment by hduonggithub** [comment]
Thanks @MaxChanger. It works now.

My 2nd question is it possible to have each viewport window with interaction features like **draw_geometries_with_editing**

**Comment by MaxChanger** [comment]
@hduonggithub  It doesn't seem to be working properly. It can normally display like a `Visualizer()`, but only seems to show one geometry (`Visualizer()` can add multiple geometries in list), and I cannot edit it, a segfault occurs when I try to select a point, like this
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
Do you have any test results?

**Comment by hduonggithub** [comment]
@MaxChanger I could display multiple windows and pick up a point but could not edit or even draw a polygon.

**Comment by MaxChanger** [comment]
@hduonggithub Hello，the version I used was 0.9.0, some test results and code are as follows, I guess yours is 0.10.0 ? 

It's worth noting that I can't pick a point, but you can. 

[Yes] F : Enter freeview mode.
[Yes] X : Enter orthogonal view along X axis, press again to flip.
[Yes] Y : Enter orthogonal view along Y axis, press again to flip.
[Yes] Z : Enter orthogonal view along Z axis, press again to flip.
[Yes] K : Lock / unlock camera.
[Yes] Ctrl + D : Downsample point cloud with a voxel grid.
[Yes] R : Reset geometry to its initial state.   **[Not Ctrl + R]**
[Yes] +/- : Increase/decrease picked point size.. **[Not Shift + +/-]**

------failure ------
[No] Shift + mouse left button : Pick a point and add in queue.
[-] Shift + mouse right button : Remove last picked point from queue.

```python
vis = o3d.visualization.VisualizerWithEditing()
vis.create_window(window_name='TopLeft', width=600, height=540, left=0, top=0)
vis.add_geometry(pcd)
# vis.add_geometry(point_mesh_sphere)

vis_result = o3d.visualization.VisualizerWithEditing()
vis_result.create_window(window_name='TopRight', width=600, height=540, left=800, top=0)
vis_result.add_geometry(pcd)

while True:
    vis.update_geometry(pcd)
    if not vis.poll_events():
        break
    vis.update_renderer()

    vis_result.update_geometry(pcd)
    if not vis_result.poll_events():
        break
    vis_result.update_renderer()

vis.destroy_window()
vis_result.destroy_window()
```

**Comment by hduonggithub** [comment]
@MaxChanger Yes, I use 0.10.0. I have the similar code, and got the same error (still can only pick one point and window closed immediately).

I did try to add 2 geometries to the same vis, but not able show with VisualizerWithEditing(), still can show with Visualizer() only.

I wonder why these features not available in Visualizer() only or o3d.visualization.draw_geometries(). They are very useful.
F : Enter freeview mode.
X : Enter orthogonal view along X axis, press again to flip.
Y : Enter orthogonal view along Y axis, press again to flip.
Z : Enter orthogonal view along Z axis, press again to flip.

**Comment by MaxChanger** [comment]
Indeed, after picking a point, it will be closed immediately, but the ID of the selected point will be shown in the terminal with the above errors. It seems that there is no difference between 0.9.0 and 0.10.0.

VisualizerWithEditing() can only add one geometry, I also found this problem, unfortunately, I did not find a solution.

I think one reason may be that if there are two geometries at the same time, it is very likely that you don’t know which geometry point you picked.

**Comment by MaxChanger** [comment]
@hduonggithub  If you only want to display many point clouds and pick some points, can you concate the two point clouds together and spend some experience to save the number of each point cloud, and then distinguish it by the returned Point ID ?

But I think this is not the optimal solution, and it will not work for mesh.

In addition, displaying two windows at the same time seems to have some problems with the response to the keyboard keys. For example, I did not find a way to close one and keep the other open. When you press esc or q, both windows will be closed. #1917

**Comment by hduonggithub** [comment]
@MaxChanger 

> @hduonggithub The parameter of `vis.add_geometry()` cannot be a list, only Geometry, you can refer to the official documentation. But, you could use
> 
> ```python
> vis.add_geometry(pcd)
> vis.add_geometry(point_mesh_sphere)
> ```
> 
> to add multi-geometries to the `Visualizer()`, but will only show the first one in `VisualizerWithEditing()` I founded.

Completely right. 

I am looking for how to turn these features on Visualizer() only. Do you have any idea?
F : Enter freeview mode.
X : Enter orthogonal view along X axis, press again to flip.
Y : Enter orthogonal view along Y axis, press again to flip.
Z : Enter orthogonal view along Z axis, press again to flip.

**Comment by MaxChanger** [comment]
`VisualizerWithEditing()` inherits from `Visualizer()`, and if you want to implement these features, you may need to modify its c++ code.  

But I don't know if there's a conflict, so why don't they just provide it.

**Comment by prewettg** [comment]
This is not possible with the current visualizer in 0.11. With the new rendering and gui module it is possible to have multiple scenes, as long as they are different scenes. Your stated use case would work in this case: create one scene with point cloud 1, and then create a second scene with point cloud 2, then put them next to each other. I have included an example below. If you need multiple viewports on the same scene, we are working on that, hopefully for 0.12.
```
#!/usr/bin/env python

import open3d as o3d
import open3d.visualization.gui as gui
import numpy as np

def make_box():
    box = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
    box.compute_vertex_normals()
    return box

def main():
    gui.Application.instance.initialize()

    mat = o3d.visualization.rendering.Material()
    mat.base_color = (1.0, 0.0, 0.0, 1.0)
    mat.shader = "defaultLit"

    w = gui.Application.instance.create_window("Two scenes", 1025, 512)
    scene1 = gui.SceneWidget()
    scene1.scene = o3d.visualization.rendering.Open3DScene(w.renderer)
    scene1.scene.add_geometry("cube1", make_box(), mat)
    scene1.setup_camera(60, scene1.scene.bounding_box, (0, 0, 0))
    scene2 = gui.SceneWidget()
    scene2.scene = o3d.visualization.rendering.Open3DScene(w.renderer)
    mat.base_color = (0.0, 0.0, 1.0, 1.0)
    scene2.scene.add_geometry("cube1", make_box(), mat)
    scene2.setup_camera(60, scene2.scene.bounding_box, (0, 0, 0))

    w.add_child(scene1)
    w.add_child(scene2)

    def on_layout(theme):
        r = w.content_rect
        scene1.frame = gui.Rect(r.x, r.y, r.width / 2, r.height)
        scene2.frame = gui.Rect(r.x + r.width / 2 + 1, r.y, r.width / 2, r.height)

    w.set_on_layout(on_layout)

    gui.Application.instance.run()

if __name__ == "__main__":
    main()
```

**Comment by hduonggithub** [comment]
Thanks @prewettg

**Comment by MaxChanger** [comment]
The development is real and rapid. I started using version 0.8.0, and now I am stuck at 0.9.0. Some functions in the above example are already unfamiliar. Hahaha
> By the way, I used PyVista to solve my needs @hduonggithub

**Comment by hduonggithub** [comment]
@MaxChanger Thanks. It is good to know!

**Comment by fabioruetz** [comment]
@prewettg Thanks a lot! Is there a way to synchronize the camera/viewpoints over the different viewports?  I.e I would like to move one the viewpoint in one window and have the other follow the movement. 

Cheers Fabio

**Comment by prewettg** [comment]
@fabioruetz Unfortunately there is no way to synchronize them at the moment. You'd need to monitor mouse movement so that you can update the appropriate camera, but that has not been exported to Python yet, although it's on my list of things to do. I just created a specific issue for this, #2610, if you want to follow.

**Comment by prewettg** [comment]
You can now add Python callbacks for mouse events on SceneWidget, so you should be able to synchronize multiple scenes now.  Please see #2320 for an example of the callback usage. (For any C++ visitors from Google, you don't need any callbacks, just inherit from SceneWidget and override OnMouse()). This is available in the `master` branch now and will be in 0.12.

**Comment by prewettg** [comment]
Just fyi, there is now a multiple window example, which includes updating in the background: [`examples/python/gui/multiple-windows.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/multiple-windows.py)

**Comment by hduonggithub** [comment]
Thanks @prewettg

**Comment by aryasenna** [comment]
Hi @prewettg,

What about the GUI class? Does this limitation apply?

I'd like to have different view port (scenewidgets) inside one window.
The following does not seem to work

```
     self._3d = gui.SceneWidget()
     self._3d.enable_scene_caching(True)  # makes UI _much_ more responsive
     self._3d.scene = rendering.Open3DScene(self.window.renderer)
     self.window.add_child(self._3d)

      # try image

     self._img = gui.SceneWidget()
     self._img.enable_scene_caching(True)  # makes UI _much_ more responsive
     self._img.scene = rendering.Open3DScene(self.window.renderer)
     self.window.add_child(self._img)
```

Only the first scenewidget is shown.

**Comment by aryasenna** [comment]
Uh-Oh, it turns out multi widget is somehow broken in devel version (0.12.0+b223e0d)
After downgrading to 0.12.0 stable, both SceneWidgets are shown correctly..

**Comment by prewettg** [comment]
It looks like this broke during the render target refactor (we now draw into a bitmap on the GPU and then draw the bitmap, rather than drawing directly). I have verified with my sample code above that #3212 fixes this, and I expect that #3002 should also fix it. I anticipate those PRs being reviewed and merged within the week. If you still have problems, please open a new issue (as it would be a regression, rather than a feature request) and will be easier for us to track.

**Comment by Yukichiii** [comment]
Hi, I notice that you mentioned we can monitor mouse movement to synchronize the camera/viewpoints of different viewport. But as for zoom in/out operations using the mouse wheel, or translation the object using right button, it may be troublesome to set synchronizing methods for all these operations. So do you have some methods to copy the view status of a gui.SceneWidget to other gui.SceneWidgets, like we can use Ctrl+C and Ctrl+V for Visualizers ? Or is it possible that all the gui.SceneWidget share single view-controller to control the view status ? @prewettg @qianyizh

**Comment by nhhai** [comment]
Hi @prewettg,

I can't figure out how to sync the cameras of the 2 scenes in your example above. I'm using version 0.12.0. What I'm trying is to set the scene1.scene.camera to scene2, but I didn't get anywhere with it. I saw a function copy_from in the camera class in the latest version, but in 0.12.0 it's not available.

Can you show me how to achieve this?

Thank you,

**Comment by koalaaaaaaaaa** [comment]
> 

ohhhhhh! It took me so much effort to work out why.. thanks anyway.

**Comment by matthewjmuscat** [comment]
Has the problem of multiple 3d rendering viewports within a single window been addressed yet as of 0.16.0? I am currently attempting to create a gui with two scenes/viewports that I can visualize and render simultaneously in a single window.

**Comment by frallebini** [comment]
> Has the problem of multiple 3d rendering viewports within a single window been addressed yet as of 0.16.0? I am currently attempting to create a gui with two scenes/viewports that I can visualize and render simultaneously in a single window.

Same here

**Comment by emilio-cartoni** [comment]
> This is not possible with the current visualizer in 0.11. With the new rendering and gui module it is possible to have multiple scenes, as long as they are different scenes. Your stated use case would work in this case: create one scene with point cloud 1, and then create a second scene with point cloud 2, then put them next to each other. I have included an example below. If you need multiple viewports on the same scene, we are working on that, hopefully for 0.12.
> 
> ```
> #!/usr/bin/env python
> 
> import open3d as o3d
> import open3d.visualization.gui as gui
> import numpy as np
> 
> def make_box():
>     box = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
>     box.compute_vertex_normals()
>     return box
> 
> def main():
>     gui.Application.instance.initialize()
> 
>     mat = o3d.visualization.rendering.Material()
>     mat.base_color = (1.0, 0.0, 0.0, 1.0)
>     mat.shader = "defaultLit"
> 
>     w = gui.Application.instance.create_window("Two scenes", 1025, 512)
>     scene1 = gui.SceneWidget()
>     scene1.scene = o3d.visualization.rendering.Open3DScene(w.renderer)
>     scene1.scene.add_geometry("cube1", make_box(), mat)
>     scene1.setup_camera(60, scene1.scene.bounding_box, (0, 0, 0))
>     scene2 = gui.SceneWidget()
>     scene2.scene = o3d.visualization.rendering.Open3DScene(w.renderer)
>     mat.base_color = (0.0, 0.0, 1.0, 1.0)
>     scene2.scene.add_geometry("cube1", make_box(), mat)
>     scene2.setup_camera(60, scene2.scene.bounding_box, (0, 0, 0))
> 
>     w.add_child(scene1)
>     w.add_child(scene2)
> 
>     def on_layout(theme):
>         r = w.content_rect
>         scene1.frame = gui.Rect(r.x, r.y, r.width / 2, r.height)
>         scene2.frame = gui.Rect(r.x + r.width / 2 + 1, r.y, r.width / 2, r.height)
> 
>     w.set_on_layout(on_layout)
> 
>     gui.Application.instance.run()
> 
> if __name__ == "__main__":
>     main()
> ```

For anyone wondering, this code works :)
The only thing I needed to change to make it work on 0.15.2 was to change
> mat = o3d.visualization.rendering.Material()  

into

> mat = o3d.visualization.rendering.MaterialRecord()  

It also works with adding more than two scenes (tested with 12 and it worked fine), but you have to change the layout function to distribute them in the window.

**Comment by 0i0i0i** [comment]
> 

Thanks. I run your code and found if I resize the window, it shows strange residue of the previous frame.
